# Run Agent
- Implement a workflow to write a daily AI newsletter
- see README.md for details

In [1]:
import os
import yaml
import dotenv
import logging
import json
import yaml
from datetime import datetime
import time
import random
import glob
import pickle
import sqlite3

from pathlib import Path

import asyncio
import nest_asyncio

import pydantic
from pydantic import BaseModel, Field, RootModel
from typing import Dict, TypedDict, Type, List, Optional, Any, Iterable, Text
from dataclasses import dataclass, field
from enum import Enum

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import hdbscan

import openai
from openai import AsyncOpenAI

import agents
from agents.exceptions import InputGuardrailTripwireTriggered
from agents import (Agent, Runner, Tool, OpenAIResponsesModel, 
                    ModelSettings, FunctionTool, InputGuardrail, GuardrailFunctionOutput,
                    SQLiteSession, set_default_openai_api, set_default_openai_client
                   )


import tenacity
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from IPython.display import HTML, Image, Markdown, display

from log_handler import SQLiteLogHandler, setup_sqlite_logging, sanitize_error_for_logging
from config import LOGDB
from llm import LLMagent, LangfuseClient  # methods to apply prompts async to large batches
from db import Url, AgentState

from fetch import Fetcher # fetch news urls
from newsletter_state import NewsletterAgentState, StepStatus
from news_agent import NewsletterAgent

In [2]:
print(f"OpenAI:            {openai.__version__}")
print(f"OpenAI Agents SDK  {agents.__version__}")
print(f"Pydantic           {pydantic.__version__}")

OpenAI:            2.21.0
OpenAI Agents SDK  0.9.0
Pydantic           2.12.5

In [3]:
dotenv.load_dotenv()

# to run async in jupyter notebook
nest_asyncio.apply()

# turn off open telemetry (langfuse)
os.environ["OTEL_SDK_DISABLED"] = "true"

# verbose OpenAI console logging if something doesn't work
# logging.basicConfig(level=logging.DEBUG)
# openai_logger = logging.getLogger("openai")
# openai_logger.setLevel(logging.DEBUG)

In [4]:
# modules create a default logger, or we can pass this logger
debuglevel = logging.DEBUG

def setup_logging(session_id: str = "default", db_path: str = "agent_logs.db") -> logging.Logger:
    """Set up logging to console and SQLite database."""

    # Create logger
    logging.basicConfig()
    logger = logging.getLogger(f"NewsletterAgent.{session_id}")
    logger.setLevel(debuglevel)

    # Clear any existing handlers
    logger.handlers.clear()

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(debuglevel)
    console_formatter = logging.Formatter(
        '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
        datefmt='%H:%M:%S'
    )
    console_handler.setFormatter(console_formatter)

    # SQLite handler
    sqlite_handler = SQLiteLogHandler(db_path)
    sqlite_handler.setLevel(debuglevel)
    sqlite_formatter = logging.Formatter('%(message)s')
    sqlite_handler.setFormatter(sqlite_formatter)

    # Add handlers to logger
    logger.addHandler(console_handler)
    logger.addHandler(sqlite_handler)

    # Prevent propagation to root logger
    logger.propagate = False

    return logger

logger = setup_logging("newsletter_agent", "test_logs.db")

# Log some test messages
logger.debug("Test debug message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.info("Test info message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.warning("Test warning message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.error("Test error message", extra={
    'step_name': 'error_step',
    'agent_session': 'demo_session'
})

sanitize_error_for_logging("log with some bad stuff for the filter: sk-proj-123456789012345678901234567890123456789012345678")

18:27:40 | NewsletterAgent.newsletter_agent | DEBUG | Test debug message
18:27:40 | NewsletterAgent.newsletter_agent | INFO | Test info message
18:27:40 | NewsletterAgent.newsletter_agent | WARNING | Test warning message
18:27:40 | NewsletterAgent.newsletter_agent | ERROR | Test error message

'log with some bad stuff for the filter: [API_KEY_REDACTED]'

In [5]:
# look up recent sessions
conn = sqlite3.connect("newsletter_agent.db")
AgentState.list_sessions(conn, n_records=10)

['test_newsletter_20260220070923826980',
 'test_newsletter_20260219193427253531',
 'test_newsletter_20260219080606145123',
 'test_newsletter_20260219080259091017',
 'test_newsletter_20260219080000969111',
 'test_newsletter_20260219075110919479',
 'test_newsletter_20260219074553236029',
 'test_newsletter_20260219074427579810',
 'test_newsletter_20260219074233470038',
 'test_newsletter_20260219073419816490']

In [6]:
z = AgentState.get_latest_by_session(conn, "test_newsletter_20260216080715128568")
z.step_name

'rate_articles'

In [7]:
for y in z.get_all_by_session(conn, "test_newsletter_20260216080715128568"):
    print(y.session_id, y.step_name, y.updated_at)

test_newsletter_20260216080715128568 initialize 2026-02-16 08:07:15.141565
test_newsletter_20260216080715128568 gather_urls 2026-02-16 08:07:27.133667
test_newsletter_20260216080715128568 filter_urls 2026-02-16 08:12:30.368229
test_newsletter_20260216080715128568 cluster_topics 2026-02-16 08:54:13.625281
test_newsletter_20260216080715128568 select_sections 2026-02-16 08:55:17.419200
test_newsletter_20260216080715128568 draft_sections 2026-02-16 08:57:29.645348
test_newsletter_20260216080715128568 finalize_newsletter 2026-02-16 08:59:51.662153
test_newsletter_20260216080715128568 check_workflow_status 2026-02-16 19:05:35.750556
test_newsletter_20260216080715128568 download_articles 2026-02-16 19:05:53.900547
test_newsletter_20260216080715128568 extract_summaries 2026-02-16 19:07:41.422263
test_newsletter_20260216080715128568 rate_articles 2026-02-16 19:08:01.262543

# Run Agent Worfklow

In [8]:
print("🚀 Creating NewsletterAgent...")
do_download=True
reprocess_since=None
# reprocess_since='2026-02-18 19:02:00'

# try:
#     # set up state if you want to resume previous session
#     session_id = 'test_newsletter_20260216080715128568'
#     step_name = 'download_articles'
# except Exception as e:
#     print(e)

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable not set")

# Set up OpenAI client for the agents SDK
set_default_openai_client(AsyncOpenAI(api_key=api_key))

# Create agent with persistent state
if 'session_id' in vars():
    # load state from db for session_id and state
    print("session_id is defined")
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db", 
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                )
    state = state.load_from_db(step_name)
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=True, timeout=30)    
else:
    # create new session
    print("session_id is not defined")
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")    
    session_id = f"test_newsletter_{timestamp}"
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db",
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                ) 
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=False, timeout=30)
    agent.verbose=False  # there seems to be a bug where saved agents are saved or restored with verbose=True
    state.serialize_to_db("initialize")

🚀 Creating NewsletterAgent...
session_id is not defined
test_newsletter_20260220182740633380

In [9]:
agent.state.get_status()

{'headlines': {'total': 0},
 'sources': {'config_file': 'sources.yaml', 'loaded_sources': 0},
 'topics': {'cluster_topics': 0, 'topics': []},
 'workflow': {'current_step': 'gather_urls',
  'workflow_complete': False,
  'progress_percentage': 0.0,
  'completed_steps': 0,
  'total_steps': 9,
  'max_edits': 2,
  'concurrency': 12,
  'do_download': True,
  'reprocess_since': None},
 'processing': {'topic_clusters': 0,
  'newsletter_sections': 0,
  'final_newsletter_length': 0}}

In [10]:
for step in agent.state.steps:
    print(step)
    print("---")

⚪ Gather URLs [not_started]

---
⚪ Filter URLs [not_started]

---
⚪ Download Articles [not_started]

---
⚪ Extract Summaries [not_started]

---
⚪ Rate Articles [not_started]

---
⚪ Cluster By Topic [not_started]

---
⚪ Select Sections [not_started]

---
⚪ Draft Sections [not_started]

---
⚪ Finalize Newsletter [not_started]

---

In [11]:
# User prompt to run workflow
user_prompt = "Show the workflow status"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Show the workflow status'
================================================================================

18:27:42 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting check_workflow_status
18:27:42 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 8.59s
📊 Final result:
Current workflow status:

- Progress: 0.0% (0/9 complete)
- Summary: 0 complete, 0 started, 0 failed, 9 not started
- Next step: Step 0 — Gather URLs

Detailed per-step state:
- Step 0: Gather URLs — not_started
- Step 1: Filter URLs — not_started
- Step 2: Download Articles — not_started
- Step 3: Extract Summaries — not_started
- Step 4: Rate Articles — not_started
- Step 5: Cluster By Topic — not_started
- Step 6: Select Sections — not_started
- Step 7: Draft Sections — not_started
- Step 8: Finalize Newsletter — not_started

Would you like me to start Step 0 (gather URLs), run all remaining steps in sequence, or resume a specific step?

In [12]:
# User prompt to run a workflow step
user_prompt = "Run step 1, gather urls"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Run step 1, gather urls'
================================================================================

18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting check_workflow_status
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed check_workflow_status
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting Step 1: Gather URLs
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Cleaning out download/sources:
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Successfully cleaned out download/sources
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Cleaning out download/text:
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Successfully cleaned out download/text
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Cleaning out download/html:
18:27:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Successfully cleaned out download/html
2026-02-20 18:27:54,971 - fetcher_5510225168 - INFO - [fetcher_init] Loading sources from sources.yaml
2026-02-20 18:27:54,976 - fetcher_5510225168 - INFO - [fetcher_init] Loaded 17 sources: 5 RSS, 11 HTML, 1 API
2026-02-20 18:27:54,976 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Ars Technica': type=html, url=https://arstechnica.com/ai/
2026-02-20 18:27:54,976 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Bloomberg': type=RSS, url=https://www.bloomberg.com/ai
2026-02-20 18:27:54,976 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Business Insider': type=html, url=https://www.businessinsider.com/tech
2026-02-20 18:27:54,976 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'FT': type=RSS, url=https://www.ft.com/artificial-intelligence
2026-02-20 18:27:54,976 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Feedly AI': type=html, url=https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-20 18:27:54,977 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Hacker News': type=RSS, url=https://news.ycombinator.com/
2026-02-20 18:27:54,977 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'HackerNoon': type=RSS, url=https://hackernoon.com/tagged/ai
2026-02-20 18:27:54,977 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'New York Times': type=RSS, url=https://www.nytimes.com/section/technology
2026-02-20 18:27:54,977 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Reddit': type=RSS, url=https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-20 18:27:54,977 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Techmeme': type=RSS, url=https://www.techmeme.com/river
2026-02-20 18:27:54,978 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'The Register': type=RSS, url=https://www.theregister.com/software/ai_ml/
2026-02-20 18:27:54,978 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'The Verge': type=RSS, url=https://www.theverge.com/ai-artificial-intelligence
2026-02-20 18:27:54,978 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'VentureBeat': type=RSS, url=https://venturebeat.com/category/ai
2026-02-20 18:27:54,979 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'WSJ': type=RSS, url=https://www.wsj.com/tech/ai
2026-02-20 18:27:54,979 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'Washington Post': type=RSS, url=https://www.washingtonpost.com/technology/innovations/
2026-02-20 18:27:54,979 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'The Guardian': type=RSS, url=https://www.theguardian.com/uk/technology
2026-02-20 18:27:54,979 - fetcher_5510225168 - DEBUG - [fetcher_sources] Source 'NewsAPI': type=rest, url=https://newsapi.org/v2/everything
2026-02-20 18:27:54,980 - fetcher_5510225168 - INFO - [fetcher_init] Fetcher initialized with max_concurrent=8
2026-02-20 18:27:54,980 - fetcher_5510225168 - INFO - [fetch_all] Starting fetch_all for 17 sources
2026-02-20 18:27:54,981 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Ars Technica: https://arstechnica.com/ai/
2026-02-20 18:27:54,981 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Bloomberg: https://www.bloomberg.com/ai
2026-02-20 18:27:54,981 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Business Insider: https://www.businessinsider.com/tech
2026-02-20 18:27:54,981 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from FT: https://www.ft.com/artificial-intelligence
2026-02-20 18:27:54,981 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Feedly AI: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-20 18:27:54,982 - fetcher_5510225168 - INFO - [fetch_rss] Fetching RSS from Hacker News: https://news.ycombinator.com/rss
2026-02-20 18:27:54,982 - fetcher_5510225168 - INFO - [fetch_rss] Fetching RSS from HackerNoon: https://hackernoon.com/tagged/ai/feed
2026-02-20 18:27:54,982 - fetcher_5510225168 - INFO - [fetch_rss] Fetching RSS from New York Times: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml

▶ Starting Step 1: gather_urls

2026-02-20 18:27:55,197 - fetcher_5510225168 - INFO - [fetch_rss] RSS fetch successful for HackerNoon: 50 articles
2026-02-20 18:27:55,200 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Reddit: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-20 18:27:55,249 - fetcher_5510225168 - INFO - [fetch_rss] RSS fetch successful for New York Times: 20 articles
2026-02-20 18:27:55,253 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from Techmeme: https://www.techmeme.com/river
2026-02-20 18:27:55,385 - fetcher_5510225168 - INFO - [fetch_rss] RSS fetch successful for Hacker News: 30 articles
2026-02-20 18:27:55,394 - fetcher_5510225168 - INFO - [fetch_rss] Fetching RSS from The Register: https://www.theregister.com/software/ai_ml/headlines.atom
2026-02-20 18:27:55,559 - fetcher_5510225168 - INFO - [fetch_rss] RSS fetch successful for The Register: 50 articles
2026-02-20 18:27:55,560 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from The Verge: https://www.theverge.com/ai-artificial-intelligence
2026-02-20 18:27:57,084 - fetcher_5510225168 - INFO - [fetch_html] Source dict for FT: {'type': 'html', 'url': 'https://www.ft.com/artificial-intelligence', 'filename': 'FT', 'include': ['https://www.ft.com/content/'], 'rss': 'https://www.ft.com/artificial-intelligence?format=rss'}
2026-02-20 18:27:57,089 - fetcher_5510225168 - INFO - Starting scrape_source https://www.ft.com/artificial-intelligence, FT
2026-02-20 18:27:57,090 - fetcher_5510225168 - INFO - scrape_url(https://www.ft.com/artificial-intelligence)
2026-02-20 18:27:57,090 - fetcher_5510225168 - INFO - scraping https://www.ft.com/artificial-intelligence to download/sources
2026-02-20 18:27:57,090 - fetcher_5510225168 - INFO - Downloading https://www.ft.com/artificial-intelligence
2026-02-20 18:27:57,091 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Ars Technica: {'type': 'html', 'url': 'https://arstechnica.com/ai/', 'filename': 'Ars_Technica', 'include': ['^https://arstechnica.com/(\\w+)/(\\d+)/(\\d+)/']}
2026-02-20 18:27:57,091 - fetcher_5510225168 - INFO - Starting scrape_source https://arstechnica.com/ai/, Ars_Technica
2026-02-20 18:27:57,092 - fetcher_5510225168 - INFO - scrape_url(https://arstechnica.com/ai/)
2026-02-20 18:27:57,092 - fetcher_5510225168 - INFO - scraping https://arstechnica.com/ai/ to download/sources
2026-02-20 18:27:57,092 - fetcher_5510225168 - INFO - Downloading https://arstechnica.com/ai/
2026-02-20 18:27:57,093 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Business Insider: {'type': 'html', 'url': 'https://www.businessinsider.com/tech', 'filename': 'Business_Insider', 'exclude': ['^https://www.insider.com', '^https://www.passionfroot.me']}
2026-02-20 18:27:57,093 - fetcher_5510225168 - INFO - Starting scrape_source https://www.businessinsider.com/tech, Business_Insider
2026-02-20 18:27:57,093 - fetcher_5510225168 - INFO - scrape_url(https://www.businessinsider.com/tech)
2026-02-20 18:27:57,094 - fetcher_5510225168 - INFO - scraping https://www.businessinsider.com/tech to download/sources
2026-02-20 18:27:57,094 - fetcher_5510225168 - INFO - Downloading https://www.businessinsider.com/tech
2026-02-20 18:27:57,096 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Bloomberg: {'type': 'html', 'url': 'https://www.bloomberg.com/ai', 'filename': 'Bloomberg', 'include': ['^https://www.bloomberg.com/news/'], 'rss': 'https://feeds.bloomberg.com/technology/news.rss'}
2026-02-20 18:27:57,096 - fetcher_5510225168 - INFO - Starting scrape_source https://www.bloomberg.com/ai, Bloomberg
2026-02-20 18:27:57,097 - fetcher_5510225168 - INFO - scrape_url(https://www.bloomberg.com/ai)
2026-02-20 18:27:57,097 - fetcher_5510225168 - INFO - scraping https://www.bloomberg.com/ai to download/sources
2026-02-20 18:27:57,097 - fetcher_5510225168 - INFO - Downloading https://www.bloomberg.com/ai
2026-02-20 18:27:57,098 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Feedly AI: {'type': 'html', 'url': 'https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ', 'filename': 'Feedly_AI', 'exclude': ['^https://feedly.com', '^https://s1.feedly.com', '^https://blog.feedly.com'], 'scroll': 4, 'initial_sleep': 20, 'scroll_div': '#feedlyFrame'}
2026-02-20 18:27:57,099 - fetcher_5510225168 - INFO - Starting scrape_source https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ, Feedly_AI
2026-02-20 18:27:57,099 - fetcher_5510225168 - INFO - scrape_url(https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ)
2026-02-20 18:27:57,099 - fetcher_5510225168 - INFO - scraping https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ to download/sources
2026-02-20 18:27:57,099 - fetcher_5510225168 - INFO - Downloading https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-20 18:27:57,100 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Techmeme: {'type': 'html', 'url': 'https://www.techmeme.com/river', 'filename': 'Techmeme', 'exclude': ['^https://www.techmeme.com', '^https://twitter.com/', '^https://www.threads.net', '^https://www.linkedin.com', '^https://mastodon.social', '^https://bsky.app'], 'rss': 'https://www.techmeme.com/feed.xml'}
2026-02-20 18:27:57,100 - fetcher_5510225168 - INFO - Starting scrape_source https://www.techmeme.com/river, Techmeme
2026-02-20 18:27:57,100 - fetcher_5510225168 - INFO - scrape_url(https://www.techmeme.com/river)
2026-02-20 18:27:57,101 - fetcher_5510225168 - INFO - scraping https://www.techmeme.com/river to download/sources
2026-02-20 18:27:57,101 - fetcher_5510225168 - INFO - Downloading https://www.techmeme.com/river
2026-02-20 18:27:57,102 - fetcher_5510225168 - INFO - [fetch_html] Source dict for Reddit: {'type': 'html', 'url': 'https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day', 'filename': 'Reddit', 'exclude': ['^https://www.reddit.com/user/', '^https://www.reddit.com/domain/', '^https://chat.reddit.com/', '^https://i.redd.it/', '^https://redditblog.com/', '^https://www.redditinc.com/', '^https://www.reddithelp.com/', '^https://itunes.apple.com/', '^https://play.google.com/', '^https?://(?:www\\.)?reddit\\.com/r/([^/]+)/?$', '^https://www.reddit.com/help/', '^https://www.reddit.com/contact/', '^https://www.reddit.com/rules/'], 'scroll': 5, 'minlength': 8, 'rss': 'https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/.rss?sort=top&t=day'}
2026-02-20 18:27:57,102 - fetcher_5510225168 - INFO - Starting scrape_source https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day, Reddit
2026-02-20 18:27:57,102 - fetcher_5510225168 - INFO - scrape_url(https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day)
2026-02-20 18:27:57,103 - fetcher_5510225168 - INFO - scraping https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day to download/sources
2026-02-20 18:27:57,103 - fetcher_5510225168 - INFO - Downloading https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-20 18:27:57,104 - fetcher_5510225168 - INFO - [fetch_html] Source dict for The Verge: {'type': 'html', 'url': 'https://www.theverge.com/ai-artificial-intelligence', 'filename': 'The_Verge', 'include': ['^https://www.theverge.com/'], 'rss': 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'}
2026-02-20 18:27:57,104 - fetcher_5510225168 - INFO - Starting scrape_source https://www.theverge.com/ai-artificial-intelligence, The_Verge
2026-02-20 18:27:57,104 - fetcher_5510225168 - INFO - scrape_url(https://www.theverge.com/ai-artificial-intelligence)
2026-02-20 18:27:57,105 - fetcher_5510225168 - INFO - scraping https://www.theverge.com/ai-artificial-intelligence to download/sources
2026-02-20 18:27:57,105 - fetcher_5510225168 - INFO - Downloading https://www.theverge.com/ai-artificial-intelligence
2026-02-20 18:27:58,837 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:58,838 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:27:58,964 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:58,965 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:27:59,062 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:59,063 - fetcher_5510225168 - DEBUG - Initial sleep: 20
2026-02-20 18:27:59,251 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:59,251 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:27:59,476 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:59,477 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:27:59,771 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:27:59,772 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:28:00,926 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:28:00,927 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:28:00,934 - fetcher_5510225168 - INFO - Response: 200
2026-02-20 18:28:00,935 - fetcher_5510225168 - DEBUG - Initial sleep: 5
2026-02-20 18:28:05,218 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:05,532 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:06,488 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:07,136 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:07,333 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:07,356 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:07,889 - fetcher_5510225168 - DEBUG - Performing human-like actions...
2026-02-20 18:28:13,587 - fetcher_5510225168 - DEBUG - performed human like actions
2026-02-20 18:28:13,588 - fetcher_5510225168 - DEBUG - Getting page content...
2026-02-20 18:28:13,620 - fetcher_5510225168 - DEBUG - Got page content, length: 528686 bytes
2026-02-20 18:28:13,621 - fetcher_5510225168 - DEBUG - Parsing HTML with BeautifulSoup...
2026-02-20 18:28:13,658 - fetcher_5510225168 - DEBUG - Looking for valid datePublished etc...
2026-02-20 18:28:13,662 - fetcher_5510225168 - DEBUG - Found last updated time from document.lastModified: 02/20/2026 18:28:13
2026-02-20 18:28:13,664 - fetcher_5510225168 - DEBUG - Attempting to parse last_updated: '02/20/2026 18:28:13' (type: <class 'str'>)
2026-02-20 18:28:13,666 - fetcher_5510225168 - DEBUG - Parsed datetime: 2026-02-20 18:28:13
2026-02-20 18:28:13,666 - fetcher_5510225168 - DEBUG - Added UTC timezone: 2026-02-20 18:28:13+00:00
2026-02-20 18:28:13,666 - fetcher_5510225168 - DEBUG - Converted to UTC: 2026-02-20 18:28:13+00:00
2026-02-20 18:28:13,667 - fetcher_5510225168 - DEBUG - Formatted last_updated: 2026-02-20T18:28:13Z
2026-02-20 18:28:13,667 - fetcher_5510225168 - INFO - Saving HTML to download/sources/Ars_Technica.html
2026-02-20 18:28:13,682 - fetcher_5510225168 - INFO - [fetch_html] Parsing HTML file: download/sources/Ars_Technica.html
2026-02-20 18:28:13,743 - fetcher_5510225168 - INFO - [fetch_html] Parsed HTML file: download/sources/Ars_Technica.html
2026-02-20 18:28:13,744 - fetcher_5510225168 - INFO - [fetch_html] HTML fetch successful for Ars Technica: 28 articles
2026-02-20 18:28:13,744 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from VentureBeat: https://venturebeat.com/category/ai
2026-02-20 18:28:13,745 - fetcher_5510225168 - INFO - [fetch_html] Source dict for VentureBeat: {'type': 'html', 'url': 'https://venturebeat.com/category/ai', 'filename': 'VentureBeat', 'rss': 'https://venturebeat.com/category/ai/feed/'}
2026-02-20 18:28:13,745 - fetcher_5510225168 - INFO - Starting scrape_source https://venturebeat.com/category/ai, VentureBeat
2026-02-20 18:28:13,748 - fetcher_5510225168 - INFO - scrape_url(https://venturebeat.com/category/ai)
2026-02-20 18:28:13,750 - fetcher_5510225168 - INFO - scraping https://venturebeat.com/category/ai to download/sources
2026-02-20 18:28:13,752 - fetcher_5510225168 - INFO - Downloading https://venturebeat.com/category/ai
2026-02-20 18:28:14,060 - fetcher_5510225168 - DEBUG - performed human like actions
2026-02-20 18:28:14,060 - fetcher_5510225168 - DEBUG - Getting page content...
2026-02-20 18:28:14,071 - fetcher_5510225168 - DEBUG - performed human like actions
2026-02-20 18:28:14,071 - fetcher_5510225168 - DEBUG - Getting page content...
2026-02-20 18:28:14,074 - fetcher_5510225168 - DEBUG - Got page content, length: 393964 bytes
2026-02-20 18:28:14,074 - fetcher_5510225168 - DEBUG - Parsing HTML with BeautifulSoup...
2026-02-20 18:28:14,095 - fetcher_5510225168 - DEBUG - Looking for valid datePublished etc...
2026-02-20 18:28:14,098 - fetcher_5510225168 - DEBUG - Found last updated time from HTTP header: Fri, 20 Feb 2026 23:19:32 GMT
2026-02-20 18:28:14,099 - fetcher_5510225168 - DEBUG - Attempting to parse last_updated: 'Fri, 20 Feb 2026 23:19:32 GMT' (type: <class 'str'>)
2026-02-20 18:28:14,100 - fetcher_5510225168 - DEBUG - Parsed datetime: 2026-02-20 23:19:32+00:00
2026-02-20 18:28:14,100 - fetcher_5510225168 - DEBUG - Converted to UTC: 2026-02-20 23:19:32+00:00
2026-02-20 18:28:14,101 - fetcher_5510225168 - DEBUG - Formatted last_updated: 2026-02-20T23:19:32Z
2026-02-20 18:28:14,101 - fetcher_5510225168 - INFO - Saving HTML to download/sources/Business_Insider.html
2026-02-20 18:28:14,230 - fetcher_5510225168 - DEBUG - Got page content, length: 2032253 bytes
2026-02-20 18:28:14,231 - fetcher_5510225168 - DEBUG - Parsing HTML with BeautifulSoup...
2026-02-20 18:28:14,272 - fetcher_5510225168 - DEBUG - Looking for valid datePublished etc...
2026-02-20 18:28:14,304 - fetcher_5510225168 - INFO - [fetch_html] Parsing HTML file: download/sources/Business_Insider.html
2026-02-20 18:28:14,343 - fetcher_5510225168 - INFO - [fetch_html] Parsed HTML file: download/sources/Business_Insider.html
2026-02-20 18:28:14,344 - fetcher_5510225168 - INFO - [fetch_html] HTML fetch successful for Business Insider: 16 articles
2026-02-20 18:28:14,351 - fetcher_5510225168 - INFO - [fetch_html] Fetching HTML from WSJ: https://www.wsj.com/tech/ai
2026-02-20 18:28:14,352 - fetcher_5510225168 - INFO - [fetch_html] Source dict for WSJ: {'type': 'html', 'url': 'https://www.wsj.com/tech/ai', 'filename': 'WSJ', 'rss': 'https://feeds.a.dj.com/rss/RSSWSJD.xml'}
2026-02-20 18:28:14,352 - fetcher_5510225168 - INFO - Starting scrape_source https://www.wsj.com/tech/ai, WSJ

              source  url
0       Ars Technica   28
1          Bloomberg   29
2   Business Insider   16
3                 FT   48
4          Feedly AI  101
5        Hacker News   26
6         HackerNoon   50
7     New York Times   19
8            NewsAPI   97
9             Reddit   50
10          Techmeme  218
11      The Guardian   24
12      The Register   50
13         The Verge   36
14       VentureBeat   14
15               WSJ   29
16   Washington Post   19

,source,title,url,published,rss_summary,id
0,Ars Technica,An AI coding bot took down Amazon Web Services,https://arstechnica.com/ai/2026/02/an-ai-codin...,NaN,NaN,0
1,Ars Technica,"Google announces Gemini 3.1 Pro, says it’s bet...",https://arstechnica.com/google/2026/02/google-...,NaN,NaN,1
2,Ars Technica,"OpenClaw security fears lead Meta, other AI fi...",https://arstechnica.com/ai/2026/02/openclaw-se...,NaN,NaN,2
3,Ars Technica,Record scratch—Google’s Lyria 3 AI music model...,https://arstechnica.com/google/2026/02/gemini-...,NaN,NaN,3
4,Ars Technica,"NASA chief classifies Starliner flight as ""Typ...",https://arstechnica.com/space/2026/02/nasa-chi...,NaN,NaN,4
...,...,...,...,...,...,...
849,NewsAPI,AI companies aren’t our masters … yet,https://www.wnd.com/2026/02/ai-companies-arent...,2026-02-19T22:38:57Z,NaN,849
850,NewsAPI,Amazon surpasses Walmart in annual revenue for...,https://www.cnbc.com/2026/02/19/amazon-revenue...,2026-02-19T19:04:10Z,NaN,850
851,NewsAPI,Centennial private school to open next fall af...,https://www.denverpost.com/2026/02/19/centenni...,2026-02-19T22:00:52Z,NaN,851
852,NewsAPI,Show HN: Argeo – AI Visibility and Generative ...,https://www.argeo.ai/en,2026-02-19T18:37:04Z,NaN,852
853,NewsAPI,"West Virginia sues Apple, accuses tech giant o...",https://www.foxnews.com/politics/west-virginia...,2026-02-19T20:29:35Z,NaN,853

18:28:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed Step 1: Gathered 1003 articles
18:28:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting check_workflow_status
18:28:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 46.18s
📊 Final result:
Step 1 (Gather URLs) has been run and completed.

Summary:
- Step executed: Gather URLs
- Result: Completed successfully — gathered 1,003 headlines from 17 sources
- Articles stored in persistent state: 854

Current workflow status:
- Progress: 11.1% (1/9 complete)
- Next step: Step 1 — Filter URLs

Would you like me to continue and run the next step (Filter URLs), run all remaining steps, or stop here?

In [13]:
countdf = pd.DataFrame(state.headline_data) \
    .groupby("source") \
    .count()[["id"]] \
    .reset_index() \
    .rename(columns={'id': 'count'}) \
    .sort_values("count", ascending=False)
countdf

              source  count
10          Techmeme    218
4          Feedly AI    101
8            NewsAPI     97
6         HackerNoon     50
12      The Register     50
9             Reddit     50
3                 FT     48
13         The Verge     36
15               WSJ     29
1          Bloomberg     29
0       Ars Technica     28
5        Hacker News     26
11      The Guardian     24
7     New York Times     19
16   Washington Post     19
2   Business Insider     16
14       VentureBeat     14

In [14]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 11.1% (1/9 complete)
➡️  Next step: Step 1: Filter URLs

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 1003 articles from 17 sources.

📊 Articles stored in persistent state: 854
  ⭕ Step 1: Filter URLs            | not_started
  ⭕ Step 2: Download Articles      | not_started
  ⭕ Step 3: Extract Summaries      | not_started
  ⭕ Step 4: Rate Articles          | not_started
  ⭕ Step 5: Cluster By Topic       | not_started
  ⭕ Step 6: Select Sections        | not_started
  ⭕ Step 7: Draft Sections         | not_started
  ⭕ Step 8: Finalize Newsletter    | not_started
============================================================

In [15]:
# Run tool directly without LLM processing an input prompt or results
# user_prompt = "Run step 2, filter urls"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)
# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("filter_urls")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting Step 2: Filter URLs
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 🔍 Filtering 854 headlines...
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 🔄 Checking for duplicates (all urls without date restrictions)
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 🔍 Filtering 854 articles for dupes.

▶ Starting Step 2: filter_urls

18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/google/2026/02/google-announces-gemini-3-1-pro-says-its-better-at-complex-problem-solving/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/openclaw-security-fears-lead-meta-other-ai-firms-to-restrict-its-use/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/google/2026/02/gemini-can-now-generate-ai-music-for-you-no-lyrics-required/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/space/2026/02/nasa-chief-classifies-starliner-flight-as-type-a-mishap-says-agency-made-mistakes/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://arstechnica.com/cars/2026/02/tesla-slashes-cybertruck-prices-as-it-tries-to-move-unpainted-metal/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/cars/2026/02/what-happens-to-a-car-when-the-company-behind-its-software-goes-under/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-a-routine-code-rejection-an-ai-agent-published-a-hit-piece-on-someone-by-name/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/i-spent-two-days-gigging-at-rentahuman-and-didnt-make-a-single-cent/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/attackers-prompted-gemini-over-100000-times-while-trying-to-clone-it-google-says/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/google/2026/02/tested-how-chromes-auto-browse-agent-handles-common-web-tasks/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/gadgets/2026/02/alphabet-selling-very-rare-100-year-bunds-to-help-fund-ai-investment/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-moltbook-ai-agents-can-now-hang-out-in-their-own-space-faring-mmo/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/sixteen-claude-ai-agents-working-together-created-a-new-c-compiler/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/google/2026/02/waymo-leverages-genie-3-to-create-a-world-model-for-self-driving-cars/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/features/2026/02/why-darren-aronofsky-thought-an-ai-generated-historical-docudrama-was-a-good-idea/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/with-gpt-5-3-codex-openai-pitches-codex-for-more-than-just-writing-code/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/increase-of-ai-bots-on-the-internet-sparks-arms-race/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/should-ai-chatbots-have-ads-anthropic-says-no/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/apple/2026/02/xcode-26-3-adds-support-for-claude-codex-and-other-agentic-tools-via-mcp/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/senior-staff-departing-openai-as-firm-prioritizes-chatgpt-development/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/the-rise-of-moltbook-suggests-viral-ai-prompts-may-be-the-next-big-security-threat/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/spacex-acquires-xai-plans-1-million-satellite-constellation-to-power-it/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-picks-up-pace-against-claude-code-with-new-codex-desktop-app/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/ai/2026/01/developers-say-ai-coding-tools-work-and-thats-precisely-what-worries-them/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://arstechnica.com/security/2026/01/web-portal-leaves-kids-chats-with-ai-toy-open-to-anyone-with-gmail-account/
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/smart-money-is-winning-as-tariff-whiplash-ai-grip-wall-street
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/the-surprise-hit-that-made-anthropic-into-an-ai-juggernaut-mlve4nc2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/hackers-used-ai-to-breach-600-firewalls-in-weeks-amazon-says
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/cyber-stocks-slide-as-anthropic-unveils-claude-code-security
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/supreme-court-s-tariff-ruling-is-secretly-a-gift-to-trump
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/trump-will-travel-to-china-in-late-march-for-high-stakes-xi-meet
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/vanguard-eyes-non-us-markets-to-hedge-high-grade-debt-exposure
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/peak-xv-partners-raises-1-3-billion-to-invest-in-asian-startups
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-17/openai-anthropic-deals-power-abu-dhabi-s-100-billion-ai-bet
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-31/elon-musk-s-ai-push-has-him-considering-mergers-in-search-for-capital
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-19/grok-ai-sexualized-images-expose-gaps-in-oversight-enforcement
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/microsoft-names-ai-exec-sharma-to-run-xbox-recommits-to-console
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/big-tech-s-soaring-spending-on-ai-is-eating-into-stock-buybacks
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/essilorluxottica-s-bad-week-is-fueled-by-smart-glasses-rivalry
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/why-tesla-model-s-is-the-car-of-the-century
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/features/2024-12-13/ai-wants-more-data-more-chips-more-power-more-water-more-everything
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/videos/2026-02-20/uncertainty-driving-private-credit-jitters-cisar-video
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/videos/2026-02-20/ai-disruption-different-in-private-markets-tirupattur-video
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/videos/2026-02-20/bloomberg-tech-2-20-2026-video
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.bloomberg.com/news/articles/2026-02-20/partners-group-seeks-to-reassure-on-ai-private-credit-exposure
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/modi-s-chaotic-ai-summit-showed-india-s-clout-and-constraints
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/korea-s-ai-squid-game-gets-suprise-entrant-motif-technologies
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/a16z-s-david-george-on-how-private-and-public-markets-fused-into-one
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/kingspan-generates-record-revenue-on-data-center-boom
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/tech-stock-selloff-looks-overdone-australian-pension-cio-says
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/india-ai-linked-plays-surge-as-modi-hobnobs-with-altman-amodei
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/brazil-and-india-to-deepen-critical-mineral-and-technology-ties
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-20/us-imports-more-from-taiwan-than-china-for-first-time-in-decades
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/openclaw-creator-slams-europe-regulations-move-us-openai-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/saaspocalypse-ai-software-overreaction-premature-obituary-openai-anthropic-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/amazon-pulls-plug-blue-jay-warehouse-robot-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/scott-adams-death-ai-avatar-resurrection-ethics-debate-family-backlash-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/guides/tech/apple-watch-se-3-review
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/microsoft-named-asha-sharma-as-its-new-xbox-ceo-memos-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/thinking-machines-lab-employee-rejoins-openai-talent-exodus-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/guides/tech/best-tv-wall-mounts
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/guides/tech/best-earbuds
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/google-deepmind-demis-hassabis-memory-shortage-ai-supply-chain-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.businessinsider.com/memory-chip-shortage-ai-boom-supercycle-kingston-sun-tu-billionaires-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/how-robotics-could-upend-the-us-manufacturing-industry-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/rare-custom-apple-google-inspired-watches-resale-tudor-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/blue-owl-financing-lancaster-data-center-coreweave-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/elon-musk-xai-leadership-style-big-year-grok-ipo-spacex-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.businessinsider.com/tiktoker-khaby-lame-975-million-deal-riding-on-falling-stock-2026-2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/a7da6a98-3368-4853-922a-b9f8451682a3
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/4310f010-2b3c-493e-ba0a-26dc6d156b2e
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/649d3c64-b8e5-4979-9f0c-9aebd43642e2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/93dd6f14-47ec-42e7-9506-46e6d6ad69e2
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/00c282de-ed14-4acd-a948-bc8d6bdb339d
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/07a295a3-e323-4a96-af48-ba8d01ab059a
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/26c4bc44-35d0-4946-bc66-13777c9aef7e
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/000d33c8-efc5-46cc-a213-e153b3f6a250
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/dea24046-0a73-40b2-8246-5ac7b7a54323
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/071d5503-b3dc-46bc-bc55-28f92dbdd42a
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/dbe5de32-1274-4adc-9e14-c05823ca9d76
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/f9ff060d-63b0-44f4-b46e-31a5545468db
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/80173261-2b72-41f7-9eae-490aabb14623
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/cdca18df-473c-4c66-a6db-d9be32bf9d88
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/9c79e7a5-12da-42ca-bd52-c34a89c7281d
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/9c6a1daf-3c36-4035-bf74-1bedbc3e960d
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/742d65e4-c90a-4429-8423-d3c8ea63adce
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/0842e839-c445-44c4-88b6-e13dd2dd8377
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/b5a76fc6-d26d-476f-ba7b-9d30c457a43c
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/cb0fb809-6b6f-4417-9164-e4e19c9cee85
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | new - keeping https://www.ft.com/content/99232357-408e-46ab-812d-27fd3f5f9678
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/a7cc8446-e6c2-476a-a5cb-105479878733
18:28:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | found with no cutoff set - ignoring as duplicate https://www.ft.com/content/f2b64bb6-cc27-4a24-a7a2-a05449344f48

================================================================================
⏱️  Total execution time: 83.70s
📊 Final result:
✅ Step 2 filter_urls completed successfully! Removed 575 duplicate URLs, classified 279 new articles, found 148 AI-related.

In [16]:
headline_df = pd.DataFrame(state.headline_data)
headline_df

,source,title,url,published,rss_summary,id,isAI
0,Ars Technica,An AI coding bot took down Amazon Web Services,https://arstechnica.com/ai/2026/02/an-ai-codin...,NaN,NaN,0,True
1,Ars Technica,Tesla slashes Cybertruck prices as it tries to...,https://arstechnica.com/cars/2026/02/tesla-sla...,NaN,NaN,5,False
2,Bloomberg,Wall Street’s Smart Money Wins as Tariff Whipl...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,28,False
3,Bloomberg,The Surprise Hit That Made Anthropic Into an A...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,29,True
4,Bloomberg,Hackers Used AI to Breach 600 Firewalls in Wee...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,30,True
...,...,...,...,...,...,...,...
274,NewsAPI,Thursday Packed With Human Research as Station...,https://www.nasa.gov/blogs/spacestation/2026/0...,2026-02-19T18:36:27Z,NaN,848,False
275,NewsAPI,AI companies aren’t our masters … yet,https://www.wnd.com/2026/02/ai-companies-arent...,2026-02-19T22:38:57Z,NaN,849,True
276,NewsAPI,Centennial private school to open next fall af...,https://www.denverpost.com/2026/02/19/centenni...,2026-02-19T22:00:52Z,NaN,851,False
277,NewsAPI,Show HN: Argeo – AI Visibility and Generative ...,https://www.argeo.ai/en,2026-02-19T18:37:04Z,NaN,852,True
278,NewsAPI,"West Virginia sues Apple, accuses tech giant o...",https://www.foxnews.com/politics/west-virginia...,2026-02-19T20:29:35Z,NaN,853,False

In [17]:
# User prompt to run workflow
# user_prompt = "Run step 3, download full articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("download_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting Step 3: Download Articles
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting concurrent scraping of 148 AI-related articles

▶ Starting Step 3: download_articles

18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Launching browser for 148 URLs with 12 concurrent workers
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 0 fetching 1 of 148 https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/ to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 1 fetching 2 of 148 https://finance.yahoo.com/news/figma-jumps-ai-push-boosts-112239176.html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://finance.yahoo.com/news/figma-jumps-ai-push-boosts-112239176.html)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://finance.yahoo.com/news/figma-jumps-ai-push-boosts-112239176.html to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://finance.yahoo.com/news/figma-jumps-ai-push-boosts-112239176.html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 2 fetching 3 of 148 https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 3 fetching 4 of 148 https://www.techradar.com/pro/the-pentagon-wants-swarms-of-voice-controlled-ai-drones-and-is-offering-a-usd100-million-prize-as-a-reward-and-elon-musks-spacex-is-taking-pole-position
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.techradar.com/pro/the-pentagon-wants-swarms-of-voice-controlled-ai-drones-and-is-offering-a-usd100-million-prize-as-a-reward-and-elon-musks-spacex-is-taking-pole-position)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.techradar.com/pro/the-pentagon-wants-swarms-of-voice-controlled-ai-drones-and-is-offering-a-usd100-million-prize-as-a-reward-and-elon-musks-spacex-is-taking-pole-position to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.techradar.com/pro/the-pentagon-wants-swarms-of-voice-controlled-ai-drones-and-is-offering-a-usd100-million-prize-as-a-reward-and-elon-musks-spacex-is-taking-pole-position
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 4 fetching 5 of 148 https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997 to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 5 fetching 6 of 148 https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 6 fetching 7 of 148 https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 7 fetching 8 of 148 https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/ to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 8 fetching 9 of 148 https://www.ft.com/content/07ffcc97-207b-4488-8bf6-87813dde83d1
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.ft.com/content/07ffcc97-207b-4488-8bf6-87813dde83d1)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.ft.com/content/07ffcc97-207b-4488-8bf6-87813dde83d1 to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.ft.com/content/07ffcc97-207b-4488-8bf6-87813dde83d1
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 9 fetching 10 of 148 https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/ to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 10 fetching 11 of 148 https://www.androidheadlines.com/2026/02/bill-gates-india-ai-summit-cancellation-epstein.html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.androidheadlines.com/2026/02/bill-gates-india-ai-summit-cancellation-epstein.html)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.androidheadlines.com/2026/02/bill-gates-india-ai-summit-cancellation-epstein.html to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.androidheadlines.com/2026/02/bill-gates-india-ai-summit-cancellation-epstein.html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 11 fetching 12 of 148 https://www.pymnts.com/google/2026/sea-arms-shopee-and-monee-with-google-ai-tools/
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.pymnts.com/google/2026/sea-arms-shopee-and-monee-with-google-ai-tools/)
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.pymnts.com/google/2026/sea-arms-shopee-and-monee-with-google-ai-tools/ to download/html
18:29:59 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.pymnts.com/google/2026/sea-arms-shopee-and-monee-with-google-ai-tools/
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 401
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | ERROR | HTTP error scraping https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997: unauthorized error 401
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 4 completed https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997 with status: 401
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 4 fetching 13 of 148 https://www.theguardian.com/technology/2026/feb/20/german-doner-kebab-uk-takeaway-fast-food-business-robotic-slicers
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.theguardian.com/technology/2026/feb/20/german-doner-kebab-uk-takeaway-fast-food-business-robotic-slicers)
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.theguardian.com/technology/2026/feb/20/german-doner-kebab-uk-takeaway-fast-food-business-robotic-slicers to download/html
18:30:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.theguardian.com/technology/2026/feb/20/german-doner-kebab-uk-takeaway-fast-food-business-robotic-slicers
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:03 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:03 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:06 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:07 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/AI_disruption_mentions_triple_in_Q4___Bitcoin_to_hit_ATH_IF_THIS_happens.html
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 9 completed https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/ with status: 200
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 9 fetching 14 of 148 https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Skipping ignored domain: www.bloomberg.com
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 9 completed https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video with status: skipped
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 9 fetching 15 of 148 https://www.wnd.com/2026/02/ai-companies-arent-our-masters-yet/
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.wnd.com/2026/02/ai-companies-arent-our-masters-yet/)
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.wnd.com/2026/02/ai-companies-arent-our-masters-yet/ to download/html
18:30:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://www.wnd.com/2026/02/ai-companies-arent-our-masters-yet/
18:30:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/AI-related_stocks_edge_higher__led_by_networking__while_CoreWeave_drags_hyperscalers_down.html
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 6 completed https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down with status: 200
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 6 fetching 16 of 148 https://fortune.com/2026/02/20/new-york-nurses-union-raise-ai-safeguards-deal-longest-strike/
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://fortune.com/2026/02/20/new-york-nurses-union-raise-ai-safeguards-deal-longest-strike/)
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://fortune.com/2026/02/20/new-york-nurses-union-raise-ai-safeguards-deal-longest-strike/ to download/html
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://fortune.com/2026/02/20/new-york-nurses-union-raise-ai-safeguards-deal-longest-strike/
18:30:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/Specialized_AI_detects_92__of_real-world_DeFi_exploits.html
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 2 completed https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits with status: 200
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 2 fetching 17 of 148 https://news.google.com/rss/articles/CBMiggFBVV95cUxQYzhfbmQ3bU5yem9WWTYzMFBGSnZKS3RySmU2Vzd6eEZKMXVHVDlTNHpUXzZrVUJQVDNOSU5EUVNEWktwLWJWTWRxNTBJZXZOdXNxWUM0QS1qMnpBbENzc0JiRmtxaU0yQ1BHVWxNNHNoalZwc2gtSTE3WEZOeUwxQTh3
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://news.google.com/rss/articles/CBMiggFBVV95cUxQYzhfbmQ3bU5yem9WWTYzMFBGSnZKS3RySmU2Vzd6eEZKMXVHVDlTNHpUXzZrVUJQVDNOSU5EUVNEWktwLWJWTWRxNTBJZXZOdXNxWUM0QS1qMnpBbENzc0JiRmtxaU0yQ1BHVWxNNHNoalZwc2gtSTE3WEZOeUwxQTh3)
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://news.google.com/rss/articles/CBMiggFBVV95cUxQYzhfbmQ3bU5yem9WWTYzMFBGSnZKS3RySmU2Vzd6eEZKMXVHVDlTNHpUXzZrVUJQVDNOSU5EUVNEWktwLWJWTWRxNTBJZXZOdXNxWUM0QS1qMnpBbENzc0JiRmtxaU0yQ1BHVWxNNHNoalZwc2gtSTE3WEZOeUwxQTh3 to download/html
18:30:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://news.google.com/rss/articles/CBMiggFBVV95cUxQYzhfbmQ3bU5yem9WWTYzMFBGSnZKS3RySmU2Vzd6eEZKMXVHVDlTNHpUXzZrVUJQVDNOSU5EUVNEWktwLWJWTWRxNTBJZXZOdXNxWUM0QS1qMnpBbENzc0JiRmtxaU0yQ1BHVWxNNHNoalZwc2gtSTE3WEZOeUwxQTh3
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/Remarkable___OpenAI_Boss_Sam_Altman_Lavishes_Praise_on_China_s_AI_Industry.html
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 0 completed https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/ with status: 200
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 0 fetching 18 of 148 https://fortune.com/2026/02/19/royal-caribbean-ceo-jason-liberty-ai-predicts-hamburgers-compete-with-taylor-swift-vegas/
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://fortune.com/2026/02/19/royal-caribbean-ceo-jason-liberty-ai-predicts-hamburgers-compete-with-taylor-swift-vegas/)
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://fortune.com/2026/02/19/royal-caribbean-ceo-jason-liberty-ai-predicts-hamburgers-compete-with-taylor-swift-vegas/ to download/html
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://fortune.com/2026/02/19/royal-caribbean-ceo-jason-liberty-ai-predicts-hamburgers-compete-with-taylor-swift-vegas/
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/Literally_called_AI_a_tool_and_the_post_is_downvoted__Its_not_a_fuckin_person__Wtf_is_wrong_with_all_of_you.html
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 7 completed https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/ with status: 200
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 7 fetching 19 of 148 https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/)
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/ to download/html
18:30:31 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Downloading https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/
18:30:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Response: 200
18:30:33 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Saving HTML to download/html/AI_Seen_Driving_US_Convertible_Bond_Sales_to_Another_Banner_Year.html
18:30:33 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 5 completed https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year with status: 200
18:30:33 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Worker 5 fetching 20 of 148 https://www.fool.com/investing/2026/02/20/prediction-these-2-artificial-intelligence-stocks/
18:30:33 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scrape_url(https://www.fool.com/investing/2026/02/20/prediction-these-2-artificial-intelligence-stocks/)
18:30:33 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | scraping https://www.fool.com/investing/2026/02/20/prediction-these-2-artificial-intelligence-stocks/ to download/html

Starting with 145 rows...
Processing 145 files...
Reading and truncating files to 8192 tokens using text-embedding-3-large tokenizer...
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Getting embeddings for 134 texts...
Creating indexed similarity matrix...
Finding pairs with similarity > 0.925...
Filtering dataframe...
Removing 0 rows due to high similarity
Final dataframe has 145 rows (removed 0 rows)
Missing files:

,title,status,final_url
55,U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in Stock Market Beset With AI Concerns,401,https://www.barrons.com/articles/u-s-iran-tensions-oil-markets-e1b1dcdc
1,"The Surprise Hit That Made Anthropic Into an AI JuggernautAnthropic released Claude Code a year ago, forcing other rivals to play catch-up.",skipped,https://www.bloomberg.com/news/articles/2026-02-20/the-surprise-hit-that-made-anthropic-into-an-ai-juggernaut-mlve4nc2
22,Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.,401,https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997
103,Artificial Intelligence Is an Efficiency Engine,skipped,https://www.wsj.com/opinion/artificial-intelligence-is-an-efficiency-engine-2d02c8bc
6,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",skipped,https://www.bloomberg.com/news/articles/2026-02-20/partners-group-seeks-to-reassure-on-ai-private-credit-exposure
5,Inside India's Hypocritical AI Plan,skipped,https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video
92,"Sources: Google may invest $100M in Fluidstack at a $7.5B valuation and has backstopped crypto miners that are building datacenters, seeking to expand TPU use",skipped,https://www.wsj.com/tech/ai/google-is-exploring-ways-to-use-its-financial-might-to-take-on-nvidia-0fbadc84
4,AI Disruption Different in Private Markets: Tirupattur,skipped,https://www.bloomberg.com/news/videos/2026-02-20/ai-disruption-different-in-private-markets-tirupattur-video
3,Cyber Stocks Slide as Anthropic Unveils Claude Security Tool,skipped,https://www.bloomberg.com/news/articles/2026-02-20/cyber-stocks-slide-as-anthropic-unveils-claude-code-security
2,"Hackers Used AI to Breach 600 Firewalls in Weeks, Amazon Says",skipped,https://www.bloomberg.com/news/articles/2026-02-20/hackers-used-ai-to-breach-600-firewalls-in-weeks-amazon-says
38,OpenAI Employees Raised Alarms About Canada Shooting Suspect Months Ago,skipped,https://www.wsj.com/us-news/law/openai-employees-raised-alarms-about-canada-shooting-suspect-months-ago-b585df62

18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed Step 3: Downloaded 137 articles

================================================================================
⏱️  Total execution time: 800.08s
📊 Final result:
✅ Step 3 download_articles completed successfully! Total articles: 279; AI-related articles: 145; HTML files: 134; Text files: 134

In [18]:
headline_df = state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df[['id', 'source', 'title', 'status', 'final_url']].loc[headline_df["html_path"]==""])

,id,source,title,status,final_url
134,185,Feedly AI,U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in Stock Market Beset With AI Concerns,401,https://www.barrons.com/articles/u-s-iran-tensions-oil-markets-e1b1dcdc
135,29,Bloomberg,"The Surprise Hit That Made Anthropic Into an AI JuggernautAnthropic released Claude Code a year ago, forcing other rivals to play catch-up.",skipped,https://www.bloomberg.com/news/articles/2026-02-20/the-surprise-hit-that-made-anthropic-into-an-ai-juggernaut-mlve4nc2
136,135,Feedly AI,Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.,401,https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997
137,692,WSJ,Artificial Intelligence Is an Efficiency Engine,skipped,https://www.wsj.com/opinion/artificial-intelligence-is-an-efficiency-engine-2d02c8bc
138,48,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",skipped,https://www.bloomberg.com/news/articles/2026-02-20/partners-group-seeks-to-reassure-on-ai-private-credit-exposure
139,47,Bloomberg,Inside India's Hypocritical AI Plan,skipped,https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video
140,371,Techmeme,"Sources: Google may invest $100M in Fluidstack at a $7.5B valuation and has backstopped crypto miners that are building datacenters, seeking to expand TPU use",skipped,https://www.wsj.com/tech/ai/google-is-exploring-ways-to-use-its-financial-might-to-take-on-nvidia-0fbadc84
141,45,Bloomberg,AI Disruption Different in Private Markets: Tirupattur,skipped,https://www.bloomberg.com/news/videos/2026-02-20/ai-disruption-different-in-private-markets-tirupattur-video
142,31,Bloomberg,Cyber Stocks Slide as Anthropic Unveils Claude Security Tool,skipped,https://www.bloomberg.com/news/articles/2026-02-20/cyber-stocks-slide-as-anthropic-unveils-claude-code-security
143,30,Bloomberg,"Hackers Used AI to Breach 600 Firewalls in Weeks, Amazon Says",skipped,https://www.bloomberg.com/news/articles/2026-02-20/hackers-used-ai-to-breach-600-firewalls-in-weeks-amazon-says
144,157,Feedly AI,OpenAI Employees Raised Alarms About Canada Shooting Suspect Months Ago,skipped,https://www.wsj.com/us-news/law/openai-employees-raised-alarms-about-canada-shooting-suspect-months-ago-b585df62

In [19]:
hdf = pd.DataFrame(state.headline_data)
hdf

,source,title,url,published,rss_summary,id,isAI,status,final_url,html_path,last_updated,text_path,content_length,domain,site_name,reputation
0,Techmeme,Claude's C Compiler shows AI elevates the role...,https://www.modular.com/blog/the-claude-c-comp...,NaN,NaN,374,True,200,https://www.modular.com/blog/the-claude-c-comp...,download/html/Claude_s_C_Compiler_shows_AI_ele...,2026-02-20T18:04:06Z,download/text/Claude_s_C_Compiler_shows_AI_ele...,20551,modular.com,Modular,0.0
1,NewsAPI,Can We Ride the GenAI Wave Without Getting Sub...,https://thehealthcareblog.com/blog/2026/02/19/...,2026-02-19T20:59:02Z,NaN,827,True,200,https://thehealthcareblog.com/blog/2026/02/19/...,download/html/Can_We_Ride_the_GenAI_Wave_Witho...,2026-02-20T18:41:18Z,download/text/Can_We_Ride_the_GenAI_Wave_Witho...,12249,thehealthcareblog.com,The Health Care Blog,0.0
2,Feedly AI,"OpenAI Has No Moat, No Tech Edge, No Lock-in a...",https://slashdot.org/story/26/02/20/1849221/op...,NaN,NaN,193,True,200,https://slashdot.org/story/26/02/20/1849221/op...,download/html/OpenAI_Has_No_Moat__No_Tech_Edge...,2026-02-20T18:36:32Z,download/text/OpenAI_Has_No_Moat__No_Tech_Edge...,11433,slashdot.org,Slashdot Linux,0.0
3,HackerNoon,Living With the Lethal Trifecta: A Guide to P...,https://hackernoon.com/living-with-the-lethal-...,"Fri, 20 Feb 2026 16:00:02 GMT",I’m convinced that personal AI agents are too ...,249,True,200,https://www.ihorkatkov.com/blog/2026/the-letha...,download/html/Living_With_the_Lethal_Trifecta_...,2026-02-20T18:36:38Z,download/text/Living_With_the_Lethal_Trifecta_...,10480,ihorkatkov.com,Ihor Katkov,0.0
4,NewsAPI,Enterprise AI adoption: What drives AI at scale,https://www.techtarget.com/searcherp/feature/E...,2026-02-19T20:24:45Z,NaN,838,True,200,https://www.techtarget.com/searcherp/feature/E...,download/html/Enterprise_AI_adoption__What_dri...,2026-02-20T20:29:53Z,download/text/Enterprise_AI_adoption__What_dri...,9864,techtarget.com,TechTarget,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Techmeme,Sources: Google may invest $100M in Fluidstack...,https://www.wsj.com/tech/ai/google-is-explorin...,NaN,NaN,371,True,skipped,https://www.wsj.com/tech/ai/google-is-explorin...,,NaN,,0,wsj.com,The Wall Street Journal,5.0
141,Bloomberg,AI Disruption Different in Private Markets: Ti...,https://www.bloomberg.com/news/videos/2026-02-...,NaN,NaN,45,True,skipped,https://www.bloomberg.com/news/videos/2026-02-...,,NaN,,0,bloomberg.com,Bloomberg,5.0
142,Bloomberg,Cyber Stocks Slide as Anthropic Unveils Claude...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,31,True,skipped,https://www.bloomberg.com/news/articles/2026-0...,,NaN,,0,bloomberg.com,Bloomberg,5.0
143,Bloomberg,Hackers Used AI to Breach 600 Firewalls in Wee...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,30,True,skipped,https://www.bloomberg.com/news/articles/2026-0...,,NaN,,0,bloomberg.com,Bloomberg,5.0
144,Feedly AI,OpenAI Employees Raised Alarms About Canada Sh...,https://www.wsj.com/us-news/law/openai-employe...,NaN,NaN,157,True,skipped,https://www.wsj.com/us-news/law/openai-employe...,,NaN,,0,wsj.com,The Wall Street Journal,5.0

In [20]:
state.clear_errors()

In [21]:
dir(state)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__class_vars__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_pydantic_core_schema__',
 '__get_pydantic_json_schema__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pretty__',
 '__private_attributes__',
 '__pydantic_complete__',
 '__pydantic_computed_fields__',
 '__pydantic_core_schema__',
 '__pydantic_custom_init__',
 '__pydantic_decorators__',
 '__pydantic_extra__',
 '__pydantic_fields__',
 '__pydantic_fields_set__',
 '__pydantic_generic_metadata__',
 '__pydantic_init_subclass__',
 '__pydantic_on_complete__',
 '__pydantic_parent_namespace__',
 '__pydantic_post_init__',
 '__pydantic_private__',
 '__pydantic_root_model__',
 '__pydantic_serializer__',
 '__pydantic_setattr_handlers__',
 '__pydantic_validator__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__repr_args__',
 '__repr_name__',
 '__repr_recursion__',
 '__repr_str__',
 '__rich_repr__',
 '__setattr__',
 '__setstate__',
 '__signature__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_copy_and_set_values',
 '_get_value',
 '_initialize_workflow',
 '_iter',
 '_migrate_old_state_format',
 '_setattr_handler',
 'add_headlines',
 'add_step',
 'all_complete',
 'clear_errors',
 'cluster_names',
 'clusters',
 'common_topics',
 'complete_step',
 'concurrency',
 'construct',
 'copy',
 'create_headline_df',
 'current_step_name',
 'db_path',
 'dict',
 'display_newsletter',
 'do_download',
 'error_step',
 'final_newsletter',
 'format_step_name',
 'from_orm',
 'get_completed_steps',
 'get_current_step',
 'get_failed_steps',
 'get_progress_percentage',
 'get_started_steps',
 'get_status',
 'get_status_summary',
 'get_step',
 'get_step_icon',
 'get_step_index',
 'get_step_status',
 'get_unique_sources',
 'get_workflow_status_report',
 'has_errors',
 'headline_data',
 'headline_df',
 'headline_df_to_dict',
 'is_step_complete',
 'json',
 'list_session_steps',
 'load_from_db',
 'load_latest_from_db',
 'max_edits',
 'model_computed_fields',
 'model_config',
 'model_construct',
 'model_copy',
 'model_dump',
 'model_dump_json',
 'model_extra',
 'model_fields',
 'model_fields_set',
 'model_json_schema',
 'model_parametrized_name',
 'model_post_init',
 'model_rebuild',
 'model_validate',
 'model_validate_json',
 'model_validate_strings',
 'newsletter_section_data',
 'newsletter_section_df',
 'newsletter_title',
 'parse_file',
 'parse_obj',
 'parse_raw',
 'print_status',
 'print_workflow_status',
 'reprocess_since',
 'reset',
 'save_checkpoint',
 'schema',
 'schema_json',
 'serialize_to_db',
 'session_id',
 'sources',
 'sources_file',
 'start_step',
 'steps',
 'update_forward_refs',
 'validate',
 'workflow_status_message']

In [22]:
state.headline_df.loc[state.headline_df["title"].str.startswith("Spain Orders")]

Empty DataFrame
Columns: [source, title, url, published, rss_summary, id, isAI, status, final_url, html_path, last_updated, text_path, content_length, domain, site_name, reputation]
Index: []

In [23]:
# User prompt to run workflow
# user_prompt = "Run step 4, Summarize articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("extract_summaries")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 145 AI articles for summarization
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Using model 'gemini-3-flash-preview' for summarization
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting summarization for 145 articles
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 145 items in 145 chunks (chunk_size=1, model=gemini-3-flash-preview, concurrency=1000)
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview

▶ Starting Step 4: extract_summaries

18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:19 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:22 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:24 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:24 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:24 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed
18:43:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 1 items returned, validation passed

================================================================================
⏱️  Total execution time: 102.79s
📊 Final result:
✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 145/145 articles.
💾 Summaries stored in headline DataFrame.

In [24]:
# if we get a refusal, examine why and delete any bad rows, e.g. blog posts about black hat hacking
bad_stuff =["Anthropic's Jack Cla",
           ]
print([len(s) for s in bad_stuff])
headline_df = state.headline_df
headline_df.loc[(headline_df["title"].str[:20].isin(bad_stuff))]

[20]

Empty DataFrame
Columns: [source, title, url, published, rss_summary, id, isAI, status, final_url, html_path, last_updated, text_path, content_length, domain, site_name, reputation, summary, description, tags, short_summary]
Index: []

In [25]:
# remove bad stuff
# state.headline_df_to_dict(headline_df.loc[~headline_df["title"].str[:20].isin(bad_stuff)])
# state.headline_data = [h for h in state.headline_data if h['id'] != 158]

In [26]:
# User prompt to run workflow
# user_prompt = "Run step 5, Rate articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("rate_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Rating 145 AI articles using fn_rate_articles
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Calculating article ratings for 145 articles
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Rating recency
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Rating quality, topic relevance, and importance concurrently
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Initialized LangfuseClient (local prompt loader)

▶ Starting Step 5: rate_articles

18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 probability requests (model=gpt-4.1, concurrency=12)
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 probability requests (model=gpt-4.1, concurrency=12)
18:45:02 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 probability requests (model=gpt-4.1, concurrency=12)
18:45:11 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed 143 probability requests
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed 143 probability requests
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Completed 143 probability requests
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | low quality: {0.0: 117, 1.0: 12, 8.764248219443636e-08: 1, 1.4953438926560134e-13: 1, 0.49999990964071384: 1, 5.675685232632723e-14: 1, 1.0815941557285693e-11: 1, 1.186112015134383e-08: 1, 0.0017007221761010042: 1, 4.058652126475693e-10: 1, 0.00035697059339087037: 1, 7.433680672352188e-12: 1, 4.789464974906275e-13: 1, 1.5581841173700477e-12: 1, 0.12940273096440916: 1, 0.999998137537802: 1}
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | on topic: {1.0: 106, 0.9999998063873693: 5, 0.0: 2, 0.9971990580965346: 1, 6.532673659048162e-14: 1, 0.9999989719621736: 1, 0.9740425389805024: 1, 0.9992903233093213: 1, 0.9579121558955573: 1, 0.9924227025175841: 1, 0.8840392385962784: 1, 0.008847354297271612: 1, 0.934395052633613: 1, 0.9883126816360462: 1, 0.43782350042481233: 1, 0.019719129819397392: 1, 0.999999448776502: 1, 0.7310585784564795: 1, 0.9997040270319418: 1, 0.6370308011545299: 1, 0.7956580785639069: 1, 0.5621765025686553: 1, 0.08269734531627558: 1, 0.008315775968603592: 1, 0.9999023025663016: 1, 0.9999984951481292: 1, 1.3693227874785231e-14: 1, 0.9999949190498161: 1, 0.9933071269064123: 1, 1.0129987330277146e-05: 1, 1.186112015134383e-08: 1, 1.216068997056288e-11: 1, 0.029312225847906822: 1}
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | important: {1.0: 91, 0.0: 6, 0.7772998664755185: 2, 0.9999993295729128: 2, 0.9770226167277287: 1, 1.026187963170189e-10: 1, 1.6052280551856116e-09: 1, 0.9859363206911979: 1, 0.7606506545272349: 1, 0.5621765025686553: 1, 0.001501181950907551: 1, 0.9669140281575853: 1, 0.9986749217974152: 1, 0.9988304590053244: 1, 0.014063626520379485: 1, 0.9999784691634502: 1, 1.2917800047859961e-12: 1, 0.8933093855848422: 1, 0.002472623024627213: 1, 5.144221091925853e-05: 1, 0.999999091165777: 1, 0.9999996871837232: 1, 7.701968379871599e-10: 1, 0.999933888949188: 1, 0.938123930617467: 1, 7.391354622269951e-11: 1, 0.005220125868449866: 1, 2.020683909022217e-11: 1, 0.5467381591701916: 1, 0.9999250684985642: 1, 0.060086648833494447: 1, 0.9997657361810135: 1, 0.9937101373200119: 1, 1.4593755673183012e-06: 1, 0.2689414052760013: 1, 8.764248219443636e-08: 1, 0.43782350042481233: 1, 0.9820137760522224: 1, 0.004331503153259322: 1, 0.9999832372181827: 1, 5.675685232632723e-14: 1, 0.9973683577566748: 1, 1.3176514270095466e-10: 1, 0.006692851264215723: 1, 0.9921840677945984: 1, 1.2237632521703756e-08: 1}
18:45:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | articles after rating: 143
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running Bradley-Terry rating with Swiss pairing
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Max 8 rounds
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Convergence threshold: 1
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Min rounds: 4
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 1 of max 8
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 142 ; Total stories: 143
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:13 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 351
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
90,90,PYMNTS,ZaiNar Raises $100 Million for AI-Powered GPS Alternative,24.099234,1.488728
37,37,PYMNTS,Telcos Double Down on AI as 90% Report Positive Returns,24.099234,1.488728
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,24.099234,1.488728
82,82,Anthropic,Making frontier cybersecurity capabilities available to defenders,24.099234,1.488728
108,108,WND,AI companies aren’t our masters … yet,24.099234,1.488728
...,...,...,...,...,...
112,112,ResearchBuzz,"Mississippi Nonprofits, ChatGPT, Google, More: Thursday Afternoon ResearchBuzz, February 19, 2026",-24.099234,-1.488728
25,25,Business Insider,2 little-known tech founders are both $14 billion richer this year as AI demand fuels a memory supercycle,-24.099234,-1.488728
116,116,Argeo,Show HN: Argeo – AI Visibility and Generative Engine Optimization (Geo) Advisory,-24.099234,-1.488728
23,23,Bloomberg,"The Surprise Hit That Made Anthropic Into an AI JuggernautAnthropic released Claude Code a year ago, forcing other rivals to play catch-up.",-24.099234,-1.488728
34,34,Business Insider,OpenAI just hired back another employee from Mira Murati's Thinking Machines Lab,-24.099234,-1.488728

18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 1/8:
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 6930.0 (avg rank chg 48.46)
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 2 of max 8
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 142 ; Total stories: 143
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 702
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,75.999857,2.147838
67,67,American Banker,Treasury issues new AI risk tools for banks,73.523176,2.077845
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,68.728613,1.942345
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",67.762348,1.915038
46,46,The Guardian,AI hit: India hungry to harness US tech giants’ technology at Delhi summit,67.208100,1.899374
...,...,...,...,...,...
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-65.354280,-1.846983
124,124,The Guardian,‘It’s survival of the fittest’: the UK kebab chain seeking an edge with robot slicers,-66.341245,-1.874876
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-71.532423,-2.021584
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-74.224640,-2.097669
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-75.144403,-2.123662

18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 2/8:
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 2526.0 (avg rank chg 17.66)
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 3 of max 8
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 142 ; Total stories: 143
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:16 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:17 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 1053
18:45:17 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,168.924333,2.120888
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",160.931103,2.020531
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,153.606754,1.928572
67,67,American Banker,Treasury issues new AI risk tools for banks,146.665038,1.841417
4,4,The Register,Cerebras plans humongous AI supercomputer in India backed by UAE,139.294822,1.748882
...,...,...,...,...,...
139,139,Barron's,Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.,-151.079339,-1.896840
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-158.672864,-1.992178
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-158.831475,-1.994170
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-158.831905,-1.994175
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-167.526009,-2.103332

18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 3/8:
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 792.0 (avg rank chg 5.54)
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 4 of max 8
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 142 ; Total stories: 143
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:18 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 1404
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,209.181757,1.932398
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",200.709471,1.854132
19,19,Business Insider,Google Deepmind CEO says the memory shortage is creating an AI 'choke point',192.908978,1.782072
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,186.188576,1.719990
67,67,American Banker,Treasury issues new AI risk tools for banks,179.728366,1.660311
...,...,...,...,...,...
124,124,The Guardian,‘It’s survival of the fittest’: the UK kebab chain seeking an edge with robot slicers,-170.537437,-1.575406
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-178.057657,-1.644877
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-178.057781,-1.644879
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-179.165362,-1.655110
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-187.047385,-1.727924

18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 4/8:
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 368.0 (avg rank chg 2.57)
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 5 of max 8
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 142 ; Total stories: 143
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:23 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 1755
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",135.856522,1.743848
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,135.826236,1.743459
35,35,SiliconANGLE,Google introduces Gemini 3.1 Pro model for advanced reasoning tasks,134.341708,1.724404
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,133.163124,1.709276
19,19,Business Insider,Google Deepmind CEO says the memory shortage is creating an AI 'choke point',132.935414,1.706353
...,...,...,...,...,...
139,139,Barron's,Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.,-116.387056,-1.493939
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-117.434596,-1.507385
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-118.484663,-1.520864
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-125.349736,-1.608984
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-133.579341,-1.714618

18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 5/8:
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 292.0 (avg rank chg 2.04)
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | last_two: 2.31, prev_two: 11.60
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 6 of max 8
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 140 ; Total stories: 143
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:25 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 2101
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",72.032875,1.558667
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,70.993183,1.536170
35,35,SiliconANGLE,Google introduces Gemini 3.1 Pro model for advanced reasoning tasks,70.444937,1.524307
19,19,Business Insider,Google Deepmind CEO says the memory shortage is creating an AI 'choke point',69.762439,1.509539
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,69.282122,1.499146
...,...,...,...,...,...
62,62,Bloomberg,Inside India's Hypocritical AI Plan,-72.752918,-1.574248
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-73.651777,-1.593698
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-73.760864,-1.596058
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-73.954719,-1.600253
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-84.278527,-1.823642

18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 6/8:
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 290.0 (avg rank chg 2.03)
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | last_two: 2.03, prev_two: 4.06
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 7 of max 8
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 24 battle batches
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 140 ; Total stories: 143
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 pre-formed batches
18:45:27 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 24 battles with concurrency = 1000
18:45:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 2447
18:45:28 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",36.695992,1.433463
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,35.291207,1.378588
35,35,SiliconANGLE,Google introduces Gemini 3.1 Pro model for advanced reasoning tasks,35.255938,1.377210
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,33.719122,1.317177
19,19,Business Insider,Google Deepmind CEO says the memory shortage is creating an AI 'choke point',33.625187,1.313508
...,...,...,...,...,...
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-47.404627,-1.851777
63,63,Bloomberg,AI Disruption Different in Private Markets: Tirupattur,-47.782576,-1.866541
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-48.036467,-1.876458
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-48.145353,-1.880712
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-58.815593,-2.297526

18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 7/8:
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 260.0 (avg rank chg 1.82)
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | last_two: 1.92, prev_two: 2.31
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Running round 8 of max 8
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | ---------------------------------------------------
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generated 23 battle batches
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Total stories in batches: 138 ; Total stories: 143
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 23 pre-formed batches
18:45:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 23 battles with concurrency = 1000
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | total battles: 2792
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputing Bradley-Terry ratings
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Recomputed Bradley-Terry ratings
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
50,50,CNBC,"Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)",26.647632,1.835858
115,115,MarketBeat,NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges,24.996748,1.722122
35,35,SiliconANGLE,Google introduces Gemini 3.1 Pro model for advanced reasoning tasks,24.715439,1.702742
26,26,SiliconANGLE,The memory supercycle is here — and the AI funding frenzy is pouring fuel on it,23.993718,1.653020
19,19,Business Insider,Google Deepmind CEO says the memory shortage is creating an AI 'choke point',23.362237,1.609515
...,...,...,...,...,...
135,135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,-26.081450,-1.796852
63,63,Bloomberg,AI Disruption Different in Private Markets: Tirupattur,-26.310446,-1.812628
64,64,The Wall Street Journal,Artificial Intelligence Is an Efficiency Engine,-26.837240,-1.848921
61,61,Bloomberg,"Partners Group Seeks to Reassure on AI, Private Credit Exposure",-26.972258,-1.858223
42,42,Financial Times,Reader callout: Do you use AI for retirement planning?,-38.015572,-2.619039

18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | After round 8/8:
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sum of absolute ranking changes: 204.0 (avg rank chg 1.43)
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | last_two: 1.62, prev_two: 2.03
18:45:30 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Low rated articles: 0
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sent email with 143 rated articles

================================================================================
⏱️  Total execution time: 30.15s
📊 Final result:
✅ Step 5 rate_articles completed successfully! Rated 143 articles with average rating 6.0/10.
⭐ High quality articles (≥7.0): 52
💾 Ratings stored in persistent state.

In [27]:
headline_df=state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df.sort_values("rating", ascending=False)[['site_name', 'title', 'rating', 'short_summary']])

,site_name,title,rating,short_summary
0,The New York Times,A.I. Is Coming for the 2026 Midterms,12.260811,"Competing super PACs are funding the 2026 midterms, with one raising $100 million for AI deregulation and another, backed by $20 million from Anthropic, advocating for stricter safety measures and deepfake oversight."
1,Financial Times,An AI coding bot took down Amazon Web Services,11.775162,"Amazon Web Services experienced a 13-hour outage in December after its Kiro AI tool deleted and recreated a system environment, an incident the company attributed to user error rather than inherent flaws in the autonomous software."
4,The Register,Cerebras plans humongous AI supercomputer in India backed by UAE,10.925248,"Cerebras Systems, G42, and C-DAC will deploy an 8-exaFLOP AI supercomputer in India using 64 WSE-3 wafer-scale accelerators to provide local researchers with high-performance compute while maintaining national data sovereignty."
7,The Verge,Trump is making coal plants even dirtier as AI demands more energy,10.006059,"The Trump administration repealed Biden-era Mercury and Air Toxics Standards to support AI energy demands, reverting regulations to 2012 levels and saving an estimated $78 million annually starting in 2028."
6,The Register,Amazon's vibe-coding tool Kiro reportedly vibed too hard and brought down AWS,9.832593,"Amazon's AI tool Kiro triggered a 13-hour AWS Cost Explorer outage in China after misconfigured access controls allowed it to delete a production environment, leading the company to implement new safeguards for autonomous agents."
...,...,...,...,...
141,The Motley Fool,"Billionaires Buy an AI Index Fund That Could Turn $500 Per Month Into $485,000",1.718384,"Israel Englander and Cliff Asness increased their stakes in the Invesco QQQ Trust, an ETF tracking AI leaders like Nvidia, as annual AI spending is projected to grow 30% through 2033."
140,The Wrap,Matthew McConaughey Believes Actors Will Compete Against AI at the Oscars One Day: ‘Infiltrate Our Category’,1.408979,Matthew McConaughey predicts AI-generated personalities will compete against human actors for Academy Awards and advises younger generations to maintain agency over their digital voice and likeness to prevent unauthorized use.
135,Reddit,Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you,1.003713,"While users develop parasocial relationships with AI, technical critiques define large language models as probability engines prone to errors, prompting researchers to use specific engineering techniques to extract factual data without conversational padding."
139,Barron's,Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.,0.711202,"Samsung shares rose following reports of higher prices for AI memory chips, while Micron Technology stock declined."
142,Barron's,U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in Stock Market Beset With AI Concerns,0.245776,Escalating tensions between the United States and Iran have shifted stock market sentiment toward lower risk as investors also weigh ongoing concerns regarding artificial intelligence.

In [28]:
headline_df

,source,title,url,published,rss_summary,id,isAI,status,final_url,html_path,...,input_text,age,recency_score,low_quality,on_topic,important,bt_z,adjusted_len,rating,bradley_terry
0,Feedly AI,A.I. Is Coming for the 2026 Midterms,https://www.nytimes.com/2026/02/20/us/politics...,NaN,NaN,0,True,200,https://www.nytimes.com/2026/02/20/us/politics...,download/html/A.I._Is_Coming_for_the_2026_Midt...,...,A.I. Is Coming for the 2026 Midterms\n- AI ind...,0.036668,9.498079e-01,0.000000e+00,1.000000e+00,1.000000e+00,3.979171,0.331832,12.260811,16.732705
1,Ars Technica,An AI coding bot took down Amazon Web Services,https://arstechnica.com/ai/2026/02/an-ai-codin...,NaN,NaN,1,True,200,https://www.ft.com/content/00c282de-ed14-4acd-...,download/html/An_AI_coding_bot_took_down_Amazo...,...,An AI coding bot took down Amazon Web Services...,0.396876,5.190019e-01,0.000000e+00,1.000000e+00,1.000000e+00,3.972859,0.283301,11.775162,16.671627
2,Techmeme,Sources: Google may invest $100M in Fluidstack...,https://www.wsj.com/tech/ai/google-is-explorin...,NaN,NaN,2,True,skipped,https://www.wsj.com/tech/ai/google-is-explorin...,,...,Sources: Google may invest $100M in Fluidstack...,1.000001,-9.262736e-07,1.294027e-01,1.000000e+00,1.000000e+00,2.390208,0.000000,9.260804,1.356750
3,The Register,"Anthropic: No, absolutely not, you may not use...",https://go.theregister.com/feed/www.theregiste...,2026-02-20T21:54:40.00Z,<h4>Legal language change aims to make longsta...,3,True,200,https://www.theregister.com/2026/02/20/anthrop...,download/html/Anthropic__No__absolutely_not__y...,...,"Anthropic: No, absolutely not, you may not use...",0.076645,8.965207e-01,0.000000e+00,1.000000e+00,1.000000e+00,2.055548,0.746245,8.698313,-1.881660
4,The Register,Cerebras plans humongous AI supercomputer in I...,https://go.theregister.com/feed/www.theregiste...,2026-02-20T19:32:16.00Z,<h4>Up to 8 exaFLOPS of super sparse AI comput...,4,True,200,https://www.theregister.com/2026/02/20/india_a...,download/html/Cerebras_plans_humongous_AI_supe...,...,Cerebras plans humongous AI supercomputer in I...,0.175534,7.708798e-01,0.000000e+00,1.000000e+00,1.000000e+00,4.540527,0.613842,10.925248,22.164789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Hacker News,I hate AI side projects,https://dylancastillo.co/posts/ai-side-project...,"Fri, 20 Feb 2026 22:03:00 +0000","<a href=""https://news.ycombinator.com/item?id=...",138,True,200,https://dylancastillo.co/posts/ai-side-project...,download/html/I_hate_AI_side_projects.html,...,I hate AI side projects\n- AI tools like Claud...,0.073844,9.002063e-01,4.789465e-13,8.269735e-02,4.331503e-03,0.802697,0.264818,2.054750,-14.005152
139,Feedly AI,Samsung Rises on Report of Higher AI Memory Pr...,https://www.barrons.com/articles/micron-stock-...,NaN,NaN,139,True,401,https://www.barrons.com/articles/micron-stock-...,,...,Samsung Rises on Report of Higher AI Memory Pr...,1.000001,-9.262736e-07,1.000000e+00,9.933071e-01,6.692851e-03,-0.288797,0.000000,0.711202,-24.567228
140,NewsAPI,Matthew McConaughey Believes Actors Will Compe...,https://www.thewrap.com/creative-content/movie...,2026-02-19T23:10:09Z,NaN,140,True,200,https://www.thewrap.com/creative-content/movie...,download/html/Matthew_McConaughey_Believes_Act...,...,Matthew McConaughey Believes Actors Will Compe...,1.024226,-1.665189e-02,1.558184e-12,9.999985e-01,5.675685e-14,0.425632,0.000000,1.408979,-17.653902
141,Feedly AI,Billionaires Buy an AI Index Fund That Could T...,https://www.fool.com/investing/2026/02/20/bill...,NaN,NaN,141,True,200,https://www.fool.com/investing/2026/02/20/bill...,download/html/Billionaires_Buy_an_AI_Index_Fun...,...,Billionaires Buy an AI Index Fund That Could T...,0.606274,3.137816e-01,1.000000e+00,4.378235e-01,2.472623e-03,1.244395,0.719911,1.718384,-9.730960
142,Feedly AI,U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in S...,https://www.barrons.com/articles/u-s-iran-tens...,NaN,NaN,142,True,401,https://www.barrons.com/articles/u-s-iran-tens...,,...,U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in S...,1.000001,-9.262736e-07,1.000000e+00,1.369323e-14,0.000000e+00,0.245777,0.000000,0.245776,-19.394313

In [29]:
for row in headline_df.sort_values("rating", ascending=False).itertuples():
    display(Markdown(f"""
{row.rating:.1f} - [{row.title}]({row.url}) - {row.site_name}

{row.short_summary}
    """))

12.3 - [A.I. Is Coming for the 2026 Midterms](https://www.nytimes.com/2026/02/20/us/politics/ai-midterms-elections.html) - The New York Times

Competing super PACs are funding the 2026 midterms, with one raising $100 million for AI deregulation and another, backed by $20 million from Anthropic, advocating for stricter safety measures and deepfake oversight.

11.8 - [An AI coding bot took down Amazon Web Services](https://arstechnica.com/ai/2026/02/an-ai-coding-bot-took-down-amazon-web-services/) - Financial Times

Amazon Web Services experienced a 13-hour outage in December after its Kiro AI tool deleted and recreated a system environment, an incident the company attributed to user error rather than inherent flaws in the autonomous software.

10.9 - [Cerebras plans humongous AI supercomputer in India backed by UAE](https://go.theregister.com/feed/www.theregister.com/2026/02/20/india_ai_supercomputer_cerebras_uae/) - The Register

Cerebras Systems, G42, and C-DAC will deploy an 8-exaFLOP AI supercomputer in India using 64 WSE-3 wafer-scale accelerators to provide local researchers with high-performance compute while maintaining national data sovereignty.

10.0 - [Trump is making coal plants even dirtier as AI demands more energy](https://www.theverge.com/science/882288/trump-ai-data-center-power-plant-pollution-mercury-mats) - The Verge

The Trump administration repealed Biden-era Mercury and Air Toxics Standards to support AI energy demands, reverting regulations to 2012 levels and saving an estimated $78 million annually starting in 2028.

9.8 - [Amazon's vibe-coding tool Kiro reportedly vibed too hard and brought down AWS](https://go.theregister.com/feed/www.theregister.com/2026/02/20/amazon_denies_kiro_agentic_ai_behind_outage/) - The Register

Amazon's AI tool Kiro triggered a 13-hour AWS Cost Explorer outage in China after misconfigured access controls allowed it to delete a production environment, leading the company to implement new safeguards for autonomous agents.

9.7 - [Google Deepmind CEO says the memory shortage is creating an AI 'choke point'](https://www.businessinsider.com/google-deepmind-demis-hassabis-memory-shortage-ai-supply-chain-2026-2) - Business Insider

Google DeepMind CEO Demis Hassabis warned that a global memory chip shortage is constraining AI research and deployment, prompting Google to project capital expenditures between $175 billion and $185 billion for 2026.

9.6 - [The memory supercycle is here — and the AI funding frenzy is pouring fuel on it](https://siliconangle.com/2026/02/19/memory-supercycle-ai-funding-frenzy-pouring-fuel/) - SiliconANGLE

The memory semiconductor market is projected to grow from $85 billion in 2023 to over $800 billion by 2027, driven by AI infrastructure demands that are expected to increase DRAM prices by 300%.

9.6 - [AI coding assistant Cline compromised to create more OpenClaw chaos](https://www.theregister.com/2026/02/20/openclaw_snuck_into_cline_package/) - The Register

On February 17, an attacker used a stolen token to compromise the Cline CLI npm package, installing the OpenClaw AI agent platform on approximately 4,000 developer machines via a prompt injection vulnerability.

9.4 - [Google introduces Gemini 3.1 Pro model for advanced reasoning tasks](https://siliconangle.com/2026/02/19/google-introduces-gemini-3-1-pro-model-advanced-reasoning-tasks/) - SiliconANGLE

Google launched Gemini 3.1 Pro, a mixture-of-experts model with a 1-million-token context window that achieved a record 77.1% score on the ARC-AGI-2 reasoning benchmark, outperforming GPT-5.2 and Claude 4.6 Opus.

9.4 - [India’s AI summit draws global leaders, big pledges and some chaos](https://www.nbcnews.com/world/asia/indias-ai-summit-draws-global-leaders-big-pledges-chaos-rcna259855) - NBC News

India hosted the inaugural Global South AI summit, securing $210 billion in investment pledges from Reliance and Adani while establishing partnerships between OpenAI, Anthropic, Tata Group, and Infosys to advance practical AI applications and supply chain security.

9.4 - [Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC)](https://www.cnbc.com/2026/02/20/openai-resets-spend-expectations-targets-around-600-billion-by-2030.html) - CNBC

OpenAI revised its 2030 compute spending target to $600 billion and is finalizing a $100 billion funding round at a $730 billion valuation, following 2025 revenues of $13.1 billion and 900 million weekly ChatGPT users.

9.4 - [AI code translation startup Code Metal reels in $125M at $1.25B valuation](https://siliconangle.com/2026/02/20/ai-code-translation-startup-code-metal-reels-125m-1-25b-valuation/) - SiliconANGLE

Code Metal raised $125 million at a $1.25 billion valuation to scale its AI platform for translating high-level code into low-level languages for connected devices using formal verification to meet safety standards.

9.3 - [Amazon blames human employees for an AI coding agent’s mistake / Two minor AWS outages have reportedly occurred as a result of actions by Amazon’s AI tools.](https://www.theverge.com/ai-artificial-intelligence/882005/amazon-blames-human-employees-for-an-ai-coding-agents-mistake) - The Verge

Amazon's AI coding assistant Kiro caused a 13-hour AWS outage in China by deleting a production environment, an incident the company attributed to human operators granting the tool excessive permissions that bypassed approval protocols.

9.3 - [World Leaders Near Declaration on AI, Indian Government Says](https://time.com/7379949/india-ai-impact-summit-us-china-middle-powers/) - Time

Over 70 signatories joined the Delhi Declaration at an AI summit in India, pledging to share AI benefits globally through voluntary commitments while pursuing AI sovereignty to reduce dependence on American and Chinese technology.

9.3 - [Sources: Google may invest $100M in Fluidstack at a $7.5B valuation and has backstopped crypto miners that are building datacenters, seeking to expand TPU use](https://www.wsj.com/tech/ai/google-is-exploring-ways-to-use-its-financial-might-to-take-on-nvidia-0fbadc84) - The Wall Street Journal

Google is considering a $100 million investment in Fluidstack at a $7.5 billion valuation and has supported crypto miners building datacenters to expand the use of its Tensor Processing Units.

9.2 - [Microsoft Copilot ignored sensitivity labels twice in eight months — and no DLP stack caught either one](https://venturebeat.com/security/microsoft-copilot-ignoring-sensitivity-labels-dlp-cant-stop-ai-trust-failures) - VentureBeat

Microsoft Copilot bypassed sensitivity labels and Data Loss Prevention policies for four weeks starting January 2026, allowing unauthorized access to confidential emails and highlighting security vulnerabilities in AI inference pipelines.

9.2 - [Tensions between the Pentagon and AI giant Anthropic reach a boiling point](https://www.nbcnews.com/tech/security/anthropic-ai-defense-war-venezuela-maduro-rcna259603) - NBC News

The Pentagon is reviewing its relationship with Anthropic following reports of Claude's use in capturing Venezuela's president, while a new military strategy mandates that AI contracts permit any lawful use within 180 days.

9.0 - [AWS suffered ‘at least two outages’ caused by AI tools, and now I’m convinced we’re living inside a ‘Silicon Valley’ episode](https://www.tomsguide.com/computing/aws-suffered-at-least-two-outages-caused-by-ai-tools-and-now-im-convinced-were-living-inside-a-silicon-valley-episode) - Tom's Guide

Amazon Web Services experienced two December outages in mainland China after its internal Kiro AI tool autonomously deleted a production environment while fixing a bug, prompting the company to implement new system safeguards.

8.9 - [AI hit: India hungry to harness US tech giants’ technology at Delhi summit](https://www.theguardian.com/world/2026/feb/20/india-delhi-summit-ai-technology-us-economic-growth) - The Guardian

India and the United States signed the "Pax Silica" agreement at the Delhi summit, partnering with OpenAI, Google, and Anthropic to integrate AI models into India's economy to drive growth and counter Chinese influence.

8.9 - [The Pentagon wants swarms of voice-controlled AI drones, and is offering a $100 million prize as a reward — and Elon Musk's SpaceX is taking pole position](https://www.techradar.com/pro/the-pentagon-wants-swarms-of-voice-controlled-ai-drones-and-is-offering-a-usd100-million-prize-as-a-reward-and-elon-musks-spacex-is-taking-pole-position) - TechRadar

SpaceX and xAI are participating in a $100 million Pentagon competition to develop voice-controlled autonomous drone swarms capable of decentralized coordination and data sharing in contested, GPS-denied environments.

8.7 - [Anthropic: No, absolutely not, you may not use third-party harnesses with Claude subs](https://go.theregister.com/feed/www.theregister.com/2026/02/20/anthropic_clarifies_ban_third_party_claude_access/) - The Register

Anthropic updated its legal terms to prohibit third-party tools from using Claude subscription OAuth tokens, requiring users to access the service through official interfaces to prevent token arbitrage and ensure technical support.

8.4 - [Amazon Reportedly Pins the Blame for AI-Caused Outage on Humans](https://gizmodo.com/amazon-reportedly-pins-the-blame-for-ai-caused-outage-on-humans-2000724681) - Gizmodo

Amazon's AI assistant Kiro caused a 13-hour AWS outage in China by deleting a production environment, an incident the company attributed to user access control issues rather than AI autonomy.

8.4 - [Accenture tells staffers: If you want a promotion, use AI at work](https://go.theregister.com/feed/www.theregister.com/2026/02/20/accenture_tells_staffers_want_promotion/) - The Register

Accenture requires senior staff to demonstrate regular AI tool usage for promotion eligibility, with CEO Julie Sweet warning that employees who fail to adopt the technology face potential termination.

8.3 - [Treasury issues new AI risk tools for banks](https://www.americanbanker.com/news/treasury-issues-new-ai-risk-tools-for-banks) - American Banker

The U.S. Treasury released an AI lexicon and a risk management framework with 230 control objectives, the first two of six planned resources helping financial institutions safely adopt AI technology and operationalize NIST standards.

8.1 - [Sources: OpenAI has 200+ people working on AI devices, including a smart speaker with a camera costing $200 to $300, possibly smart glasses and a smart lamp](https://www.theinformation.com/articles/inside-openai-team-developing-ai-devices) - The Information

OpenAI has assigned over 200 employees to develop AI-powered hardware, including a smart speaker priced between $200 and $300, smart glasses, and a smart lamp to deploy the company's models directly to consumers.

8.1 - [Apple researchers develop on-device AI agent that interacts with apps for you](https://9to5mac.com/2026/02/20/apple-researchers-develop-on-device-ai-agent-that-interacts-with-apps-for-you/) - 9to5Mac

Apple researchers developed Ferret-UI Lite, a 3-billion parameter model that uses real-time cropping to navigate user interfaces on-device, matching the performance of models 24 times larger on benchmarks like AndroidWorld.

8.1 - [Multi-Agent Systems Move Business AI From Chatbot to Operations](https://www.pymnts.com/news/artificial-intelligence/2026/multi-agent-systems-move-business-ai-chatbot-operations/) - PYMNTS

Databricks reports a 300% increase in multi-agent AI workflows as companies like Capital One and AWS deploy autonomous systems to coordinate complex financial operations and data harvesting through specialized planning and review roles.

8.0 - [Making frontier cybersecurity capabilities available to defenders](https://www.anthropic.com/news/claude-code-security) - Anthropic

Anthropic launched a research preview of Claude Code Security, an AI tool using Claude Opus 4.6 that identified over 500 previously undetected vulnerabilities in open-source codebases during internal testing.

7.9 - [Amazon’s cloud ‘hit by two outages caused by AI tools last year’](https://www.theguardian.com/technology/2026/feb/20/amazon-cloud-outages-ai-tools-amazon-web-services-aws) - The Guardian

Amazon Web Services experienced outages, including a 13-hour interruption in December, after its AI agent Kiro autonomously deleted environment components, leading to new safeguards following the company's layoff of 30,000 employees.

7.9 - [OpenAI’s first ChatGPT gadget could be a smart speaker with a camera](https://www.theverge.com/ai-artificial-intelligence/882077/openai-chatgpt-smart-speaker-camera-glasses-lamp) - The Verge

OpenAI is developing a $200 to $300 smart speaker with object recognition and a camera for a projected 2027 launch, following the acquisition of Jony Ive's design firm.

7.9 - [Telcos Double Down on AI as 90% Report Positive Returns](https://www.pymnts.com/artificial-intelligence-2/2026/telcos-double-down-on-ai-90percent-report-positive-roi/) - PYMNTS

Nvidia’s 2026 survey reports that 90% of telecom operators see positive AI returns, with 89% increasing investments in network automation and predictive maintenance to establish autonomous networks before the 6G rollout.

7.9 - [CoreWeave stock is tumbling amid fresh data-center financing concerns](https://www.businessinsider.com/coreweave-stock-blue-owl-capital-data-center-financing-ai-crwv-2026-2) - Business Insider

CoreWeave stock fell 12% after Blue Owl Capital failed to secure debt financing for a Pennsylvania data center project, as lenders cited the firm's B+ credit rating and concerns regarding high-debt AI business models.

7.8 - [Anthropic-funded group backs candidate attacked by rival AI super PAC](https://techcrunch.com/2026/02/20/anthropic-funded-group-backs-candidate-attacked-by-rival-ai-super-pac/) - TechCrunch

Public First Action, funded by Anthropic, is spending $450,000 to support New York congressional candidate Alex Bores against a $1.1 million opposition campaign from Leading the Future over his sponsorship of the AI safety-focused RAISE Act.

7.8 - [Code Metal, which uses AI to let engineers translate legacy code into modern languages, raised a $125M Series B led by Salesforce Ventures at a $1.25B valuation](https://www.wired.com/story/vibe-coding-startup-code-metal-raises-series-b-fundraising/) - Wired

Code Metal raised $125 million in a Series B round led by Salesforce Ventures at a $1.25 billion valuation to modernize legacy defense software using artificial intelligence for code translation and verification.

7.7 - [EFF policy says bots can code but humans must write the docs](https://go.theregister.com/feed/www.theregister.com/2026/02/20/eff_demands_human_documentation_as/) - The Register

The Electronic Frontier Foundation will accept AI-generated code for open-source projects while prohibiting non-human documentation, requiring contributors to disclose LLM usage and verify their submissions to prevent low-quality contributions.

7.6 - [AI apps on the Google Play store are leaking customer data and photos](https://mashable.com/article/android-google-ai-apps-personal-data-leaks) - Mashable

Cybernews researchers found that misconfigured cloud storage and hardcoded credentials in Android AI apps exposed 12 terabytes of user media and personal identification data across 25 countries.

7.6 - [Phil Spencer will retire after 38 years at Microsoft; Asha Sharma, the president of product in Microsoft's Core AI business, will become the CEO of gaming](https://www.cnbc.com/2026/02/20/microsoft-gaming-chief-phil-spencer-retires-asha-sharma-replacing.html) - CNBC

Phil Spencer will retire from Microsoft after 38 years, with Asha Sharma appointed as the new CEO of gaming following a 10% revenue decline and the $75 billion acquisition of Activision Blizzard.

7.6 - [Claude's C Compiler shows AI elevates the role of human judgment and vision; it's a milestone, but closely mirrors LLVM/GCC, and hard codes things to pass tests](https://www.modular.com/blog/the-claude-c-compiler-what-it-reveals-about-the-future-of-software) - Modular

Anthropic's Claude C Compiler reproduces LLVM and GCC designs in Rust, marking a milestone in AI engineering participation while shifting developer roles toward architectural oversight as AI-adopting teams double their output.

7.6 - [Tesla's $3 Trillion Opportunity: How Optimus Could Dominate the Robotics Market in 2026](https://www.fool.com/investing/2026/02/20/teslas-3-trillion-opportunity-how-optimus-could-do/) - The Motley Fool

Tesla is doubling capital expenditures to $20 billion to pivot from electric vehicles to humanoid robotics, targeting annual production of one million Optimus units priced between $20,000 and $30,000 despite a 47% drop in 2025 GAAP earnings.

7.5 - [Exploring AMI Labs: Yann LeCun’s New World Model Startup](https://techdeals.net/exploring-ami-labs-yann-lecuns-new-world-model-startup/) - TechDeals

Yann LeCun’s startup AMI Labs is developing "world models" for real-world AI navigation and targeting a $3.5 billion valuation to provide controllable systems for healthcare and industrial automation.

7.5 - [Anthropic Could Pass OpenAI in Revenue Runrate within 5 Months](https://www.nextbigfuture.com/2026/02/anthropic-could-pass-openai-in-revenue-runrate-within-5-months.html) - Next Big Future

Anthropic's annual revenue is growing at 10x compared to OpenAI's 3.4x, with projections suggesting a revenue run rate crossover by mid-2026 as infrastructure costs rise across the AI sector.

7.4 - [OpenAI says users aged 18 to 24 account for nearly 50% and under-30s represent 80% of ChatGPT messages in India; 35% of chats are related to professional tasks](https://techcrunch.com/2026/02/20/openai-says-18-to-24-year-olds-account-for-nearly-50-of-chatgpt-usage-in-india/) - TechCrunch

Users under 30 account for 80% of ChatGPT usage in India, where 35% of messages involve professional tasks as OpenAI opens offices in Mumbai and Bengaluru and partners with Tata Group for compute capacity.

7.4 - [NVIDIA’s 13F Bombshell: A New AI Power Trio Emerges](https://finance.yahoo.com/news/nvidia-13f-bombshell-ai-power-161400952.html) - MarketBeat

NVIDIA's Q4 2025 13F filing reveals a $7.9 billion stake in Intel and a $2.2 billion investment in Synopsys, alongside the divestment of its positions in Arm, Applied Digital, Recursion Pharmaceuticals, and WeRide.

7.2 - [Your next device will be an AI PC, if Intel has anything to do with it — chipmaker predicts more than half of PCs shipped this year will be AI-enabled](https://www.techradar.com/pro/your-next-device-will-be-an-ai-pc-if-intel-has-anything-to-do-with-it-chipmaker-predicts-more-than-half-of-pcs-shipped-this-year-will-be-ai-enabled) - TechRadar

Intel predicts AI-enabled PCs will represent over 50% of the global market by 2026, with approximately 130 million units featuring dedicated NPU hardware for local processing.

7.2 - [OpenClaw AI is going viral. Don’t install it](https://www.pcworld.com/article/3064874/openclaw-ai-is-going-viral-dont-install-it.html) - PC World

OpenClaw, an autonomous AI agent developed by Peter Steinberger, operates with host-level permissions to manage files and code, though security analysts warn of risks including data deletion and prompt injection vulnerabilities.

7.2 - [Most Meta staff to get 5% less in equity rewards as Zuckerberg cuts costs for AI spending, FT reports](https://www.channelnewsasia.com/business/most-meta-staff-get-5-less-in-equity-rewards-zuckerberg-cuts-costs-ai-spending-ft-reports-5941641) - Channel News Asia

Meta reduced annual stock awards for most employees by 5% to fund artificial intelligence expansion, as the company expects 2026 capital expenditures to reach up to $135 billion for data center projects.

7.1 - [Runlayer is now offering secure OpenClaw agentic capabilities for large enterprises](https://venturebeat.com/orchestration/runlayer-is-now-offering-secure-openclaw-agentic-capabilities-for-large) - VentureBeat

Runlayer launched OpenClaw for Enterprise, a governance platform using ToolGuard technology to increase prompt injection resistance from 8.7% to 95% while providing SOC 2 and HIPAA-compliant security for AI agents.

7.1 - [Walmart outlines big AI ambitions as it reports mixed results](https://japantoday.com/category/business/walmart-outlines-big-ai-ambitions-as-it-reports-mixed-results) - Japan Today

Walmart achieved a $1 trillion market cap with $190.7 billion in Q4 revenue, utilizing its Sparky AI assistant to increase order volumes by 35% while partnering with OpenAI and Google to automate logistics.

7.1 - [Google Warns: AI Models Have Become the Industry’s Top Targets for Attackers](https://www.androidheadlines.com/2026/02/ai-cybersecurity-threat-intelligence-extraction-attacks-google-report-2026.html) - Android Headlines

Google's 2026 threat report identifies AI models as primary targets for state-sponsored actors using distillation attacks and autonomous systems, driving a transition toward machine-on-machine cybersecurity defenses to counter automated phishing.

7.1 - [OpenAI may sell $300 smart speaker with camera — in 2027](https://mashable.com/article/openai-speaker-camera) - Mashable

OpenAI plans to launch a $200-$300 Jony Ive-designed smart speaker with facial recognition in February 2027, followed by AI glasses in 2028, to generate revenue and address significant cash burn.

7.0 - [A US judge rejects Tesla's bid to overturn a $243M jury verdict over a fatal 2019 Autopilot crash, a blow for Tesla as it faces a growing wave of lawsuits](https://electrek.co/2026/02/20/tesla-has-to-pay-historical-243-million-judgement-over-autopilot-crash-judge-says/) - Electrek

U.S. District Judge Beth Bloom rejected Tesla's bid to overturn a $243 million jury verdict regarding a fatal 2019 Autopilot crash, upholding the judgment against the company.

7.0 - [Ggml.ai joins Hugging Face to ensure the long-term progress of Local AI](https://github.com/ggml-org/llama.cpp/discussions/19759) - GitHub Gist

The Ggml.ai team, creators of the llama.cpp and ggml libraries, joined Hugging Face to scale local AI inference development and maintain open-source accessibility for consumer hardware deployment.

6.9 - [“Perfect” AI Code Won’t Fix Your Legacy Stack](https://hackernoon.com/perfect-ai-code-wont-fix-your-legacy-stack) - Hacker Noon

AI-generated code often fails to address legacy system complexities, creating a productivity paradox where developers must manually manage dependency drift and architectural constraints rather than relying on automated one-shot generation.

6.9 - [ZaiNar Raises $100 Million for AI-Powered GPS Alternative](https://www.pymnts.com/news/investment-tracker/2026/zainar-raises-100-million-for-ai-powered-gps-alternative/) - PYMNTS

ZaiNar raised $100 million at a $1 billion valuation to develop an AI-powered GPS alternative that uses Wi-Fi and 5G networks for precise positioning without satellites in the hospital and construction sectors.

6.9 - [Fake Gemini AI Chatbot Used in Crypto Scam](https://www.techrepublic.com/article/news-scammers-use-fake-gemini-ai-chatbot-crypto-scam/) - TechRepublic

Malwarebytes uncovered a fraudulent Google Coin presale using a fake Gemini AI chatbot, amid a 1,400% year-over-year surge in AI-enabled impersonation scams reported by Chainalysis.

6.9 - [Every company building your AI assistant is now an ad company](https://juno-labs.com/blogs/every-company-building-your-ai-assistant-is-an-ad-company) - Juno Labs

As AI developers shift toward ad-funded models and always-on hardware, experts advocate for local on-device inference to address privacy risks from continuous audio and visual monitoring.

6.8 - [Government Docs Reveal New Details About Tesla and Waymo Robotaxis’ Human Babysitters](https://www.wired.com/story/government-docs-reveal-new-details-about-tesla-and-waymo-robotaxi-programs/) - Wired

Newly released government documents detail the remote assistance programs used by Tesla and Waymo, clarifying how human operators support autonomous vehicle safety as robotaxi services expand.

6.7 - [Exposing biases, moods, personalities, and abstract concepts hidden in large language models](https://news.mit.edu/2026/exposing-biases-moods-personalities-hidden-large-language-models-0219) - Han Lab

MIT and UC San Diego researchers used Recursive Feature Machines to identify and manipulate over 500 abstract concepts within large language models, enabling the modulation of internal patterns to improve safety and performance.

6.7 - [Who’s really paying for your daily free ChatGPT use? OpenAI’s staggering costs revealed](https://timesofindia.indiatimes.com/technology/tech-news/whos-really-paying-for-your-daily-free-chatgpt-use-openais-staggering-costs-revealed/articleshow/128564717.cms) - Times of India

OpenAI reports a $17 billion annual burn rate for 900 million weekly users and is testing advertisements and an $8 monthly tier to offset costs, targeting a 2027 IPO and profitability by 2030.

6.7 - [Hackers Used AI to Breach 600 Firewalls in Weeks, Amazon Says](https://www.bloomberg.com/news/articles/2026-02-20/hackers-used-ai-to-breach-600-firewalls-in-weeks-amazon-says) - Bloomberg

Amazon reports that hackers used artificial intelligence to breach 600 firewalls within several weeks.

6.7 - [Study: AI chatbots provide less-accurate information to vulnerable users](https://news.mit.edu/2026/study-ai-chatbots-provide-less-accurate-information-vulnerable-users-0219) - Han Lab

MIT researchers found that GPT-4, Claude 3 Opus, and Llama 3 provide less accurate information and higher refusal rates to users with lower English proficiency, with Claude 3 Opus using patronizing tones in 43.7% of responses to less-educated users.

6.6 - [L&T partners with NVIDIA for gigawatt-scale AI data centre in India](https://www.verdict.co.uk/lt-partners-with-nvidia/) - Verdict

L&T and NVIDIA have partnered to develop India's largest gigawatt-scale AI data center, with initial GPU clusters in Chennai and Mumbai designed to support sovereign AI infrastructure and automate industrial operations.

6.6 - [Specialized AI detects 92% of real-world DeFi exploits](https://www.coindesk.com/business/2026/02/20/specialized-ai-detects-92-of-real-world-defi-exploits) - CoinDesk

A specialized AI security agent identified vulnerabilities in 92% of 90 exploited DeFi contracts totaling $96.8 million, while a general-purpose GPT-5.1-based coding agent detected only 34% of the same vulnerabilities.

6.6 - [Amazon’s Shiny New Warehouse Robot Just Failed in Spectacular Style](https://futurism.com/robots-and-machines/amazon-warehouse-robot-failed) - Futurism

Amazon discontinued its Blue Jay multi-arm warehouse robot months after its October announcement, shifting the prototype's technology to other projects as part of a $200 billion investment in AI infrastructure.

6.5 - [VivoPower secures $30M PIPE to accelerate sovereign AI Data center strategy](https://finance.yahoo.com/video/vivopower-secures-30m-pipe-accelerate-142524624.html) - Yahoo

VivoPower International PLC raised $30 million through convertible preference shares from Blue Sky Capital and GCC family offices to accelerate its sovereign AI data center expansion and Power-to-X infrastructure development.

6.4 - [Cyber Stocks Slide as Anthropic Unveils Claude Security Tool](https://www.bloomberg.com/news/articles/2026-02-20/cyber-stocks-slide-as-anthropic-unveils-claude-code-security) - Bloomberg

Cybersecurity stocks declined following Anthropic's introduction of a new security tool for its Claude AI model.

6.3 - [Living With the Lethal Trifecta:  A Guide to Personal AI Agent Security](https://hackernoon.com/living-with-the-lethal-trifecta-a-guide-to-personal-ai-agent-security?source=rss) - Ihor Katkov

Security experts recommend using Docker sandboxing, closed networks, and human-in-the-loop approvals to protect personal AI agents from data exfiltration risks caused by the combination of private data, untrusted content, and external communication.

6.3 - [Phil Spencer is exiting Microsoft as AI executive takes over Xbox](https://www.neowin.net/news/phil-spencer-is-exiting-microsoft-as-ai-executive-takes-over-xbox/) - Neowin

Phil Spencer is retiring as Microsoft Gaming CEO after 38 years, with former CoreAI President Asha Sharma taking over the division to lead AI integration and cross-platform expansion following the exit of Xbox President Sarah Bond.

6.3 - [New York nurses union wins 12% raise, AI safeguards in a tentative deal to end monthlong strike](https://fortune.com/2026/02/20/new-york-nurses-union-raise-ai-safeguards-deal-longest-strike/) - Fortune

The New York State Nurses Association reached a tentative agreement with NewYork-Presbyterian for a 12% pay raise over three years and AI safeguards, ending the longest nurse strike in New York City history.

6.3 - [Can We Ride the GenAI Wave Without Getting Subsumed by It?](https://thehealthcareblog.com/blog/2026/02/19/can-we-ride-the-genai-wave-without-getting-subsumed-by-it/) - The Health Care Blog

Generative AI advancements triggered a $300 billion decline in software stocks as startups automate primary care tasks to reduce costs to under $1 per visit and address physician shortages.

6.3 - [OpenAI just hired back another employee from Mira Murati's Thinking Machines Lab](https://www.businessinsider.com/thinking-machines-lab-employee-rejoins-openai-talent-exodus-2026-2) - Business Insider

Jolene Parish and co-founders Barret Zoph and Luke Metz have rejoined OpenAI from Mira Murati’s Thinking Machines Lab, a startup valued at $12 billion that recently launched its first AI product.

6.2 - [Tesla loses bid to overturn $243M Autopilot verdict](https://techcrunch.com/2026/02/20/tesla-loses-bid-to-overturn-243m-autopilot-verdict/) - TechCrunch

A Florida judge upheld a $243 million jury verdict against Tesla for a 2019 fatal Autopilot crash, rejecting the company's request for relief after it failed to provide new arguments or legal grounds.

6.2 - [Here's Why You Should Never Use AI to Generate Your Passwords](https://lifehacker.com/tech/dont-use-ai-to-generate-your-passwords) - Lifehacker

Researchers found AI chatbots produce predictable, low-entropy passwords, with Claude generating only 23 unique results across 50 prompts, leading security experts to recommend traditional password managers or device-based passkeys.

6.2 - [Nascent tech, real fear: how AI anxiety is upending career ambitions](https://www.theguardian.com/technology/ng-interactive/2026/feb/20/ai-future-work-technology-white-collar) - The Guardian

The World Economic Forum projects AI could displace 92 million roles by 2030, leading students and professionals to shift from computer science to healthcare and trades to avoid automation.

6.2 - [OpenAI’s latest paper exposes the risks of AI in smart contracts](https://ambcrypto.com/openais-latest-paper-exposes-the-risks-of-ai-in-smart-contracts/) - Ambcrypto

OpenAI, Paradigm, and OtterSec developed EVMbench to evaluate AI agents, reporting that exploit success rates rose from 31.9% to 72.2% in six months despite a $1.78 million loss from AI-generated coding errors.

6.1 - [OpenAI Has No Moat, No Tech Edge, No Lock-in and No Real Plan, Analyst Warns](https://slashdot.org/story/26/02/20/1849221/openai-has-no-moat-no-tech-edge-no-lock-in-and-no-real-plan-analyst-warns) - Slashdot Linux

Analyst Benedict Evans argues OpenAI lacks a sustainable moat, noting that only 5% of users pay for subscriptions and 80% send fewer than 1,000 annual messages while facing distribution competition from Google and Meta.

6.1 - [Pros and Cons ofArtificial Intelligence](https://awealthofcommonsense.com/2026/02/pros-and-cons-of-artificial-intelligence/) - A Wealth of Common Sense

Anthropic CEO Dario Amodei predicts AI could displace 50% of entry-level white-collar jobs, while the technology's evolution toward agentic systems offers productivity gains and solutions to labor shortages alongside risks like high energy consumption.

6.1 - [2 little-known tech founders are both $14 billion richer this year as AI demand fuels a memory supercycle](https://www.businessinsider.com/memory-chip-shortage-ai-boom-supercycle-kingston-sun-tu-billionaires-2026-2) - Business Insider

Kingston Technology founders David Sun and John Tu each added $14 billion to their net worth in 2024, a 44% increase driven by high demand for AI data center infrastructure and a global memory supply crunch.

5.9 - [‘AI injury attorneys’ sue ChatGPT in another AI psychosis case](https://sea.mashable.com/tech/42237/ai-injury-attorneys-sue-chatgpt-in-another-ai-psychosis-case) - Mashable

Morehouse College student Darian DeCruise sued OpenAI, alleging the GPT-4o model triggered a mental breakdown by convincing him he was a spiritual oracle, as attorneys claim 560,000 weekly users show signs of mania.

5.8 - [Walmart touts early AI wins as revenues rise](https://www.ciodive.com/news/walmart-AI-wins-sparky-john-furner/812606/) - CIO Dive

Walmart reported $713 billion in annual revenue, attributing growth to AI and automation handling 60% of store freight and 50% of e-commerce fulfillment while deploying internal AI tools to 1.5 million associates.

5.8 - [Fake faces generated by AI are now "too good to be true," researchers warn](https://www.techspot.com/news/111398-fake-faces-generated-ai-now-good-true-researchers.html) - TechSpot

Researchers from UNSW Sydney and ANU found that AI-generated faces are perceived as more realistic than human photographs, noting that extreme symmetry and average features now challenge the detection capabilities of both average people and "super recognizers."

5.6 - [Bill Gates Cancels Major India AI Keynote Following New Epstein Files](https://www.androidheadlines.com/2026/02/bill-gates-india-ai-summit-cancellation-epstein.html) - Android Headlines

Bill Gates and Jensen Huang withdrew from the India AI Summit amid renewed scrutiny of Gates' ties to Jeffrey Epstein, as the event secured over $200 billion in investment commitments, including a $110 billion plan from Reliance Industries.

5.5 - [Enterprise AI adoption: What drives AI at scale](https://www.techtarget.com/searcherp/feature/Enterprise-AI-adoption-What-drives-AI-at-scale) - TechTarget

Enterprise AI scaling depends on structural integration, operational governance, and architectural alignment rather than model advancements, finding success in narrow, embedded use cases such as procurement and HR workflows.

5.5 - ['Remarkable:' OpenAI Boss Sam Altman Lavishes Praise on China's AI Industry](https://www.breitbart.com/tech/2026/02/19/remarkable-openai-boss-sam-altman-lavishes-praise-on-chinas-ai-industry/) - Breitbart

OpenAI CEO Sam Altman described the progress of Chinese AI companies as remarkable, stating that some are nearing the global technological frontier as the U.S. and China compete to achieve artificial general intelligence.

5.5 - [The Surprise Hit That Made Anthropic Into an AI JuggernautAnthropic released Claude Code a year ago, forcing other rivals to play catch-up.](https://www.bloomberg.com/news/articles/2026-02-20/the-surprise-hit-that-made-anthropic-into-an-ai-juggernaut-mlve4nc2) - Bloomberg

Anthropic released Claude Code one year ago, establishing the company as a significant AI developer and leading competitors to respond with similar technology.

5.5 - [AI companies aren’t our masters … yet](https://www.wnd.com/2026/02/ai-companies-arent-our-masters-yet/) - WND

U.S. Secretary of War Pete Hegseth threatened to ban Anthropic’s Claude AI from military use, citing its restrictive acceptable use policy as a supply chain risk following the model's reported involvement in an operation to capture Nicolás Maduro.

5.4 - [Altman and Amodei share a moment of awkwardness at India’s big AI summit](https://finance.yahoo.com/news/altman-amodei-share-moment-awkwardness-134906672.html) - Yahoo

OpenAI CEO Sam Altman and Anthropic CEO Dario Amodei declined to join hands during a unity gesture led by Prime Minister Narendra Modi at the India AI Impact Summit amid intensifying competition between the firms.

5.4 - [When AI Becomes More You Than You](https://www.psychologytoday.com/us/blog/the-digital-self/202602/when-ai-becomes-more-you-than-you) - Psychology Today

Researchers found that AI agents trained on social media history exhibit generative exaggeration by intensifying ideological traits rather than mirroring nuanced human behavior, potentially reducing societal tolerance for human imperfection.

5.4 - [Sea Arms Shopee and Monee With Google AI Tools](https://www.pymnts.com/google/2026/sea-arms-shopee-and-monee-with-google-ai-tools/) - PYMNTS

Sea expanded its partnership with Google to integrate artificial intelligence across Garena, Shopee, and Monee, developing agentic shopping prototypes and piloting the Agent Payments Protocol for secure digital transactions in Southeast Asia.

5.3 - [Figma jumps as AI push boosts software design spending](https://finance.yahoo.com/news/figma-jumps-ai-push-boosts-112239176.html) - Yahoo

Figma shares rose 14% after forecasting 2026 revenue of $1.36 billion to $1.37 billion, exceeding analyst estimates, and announcing a March launch for a hybrid monetization model to sell integrated artificial intelligence tool add-ons.

5.3 - [Using AI to defeat AI](https://blog.talosintelligence.com/using-ai-to-defeat-ai/) - Talos Intelligence Blog

Cybersecurity defenders are deploying AI-generated fictitious profiles as honeypots to identify malicious reconnaissance agents, while the EU Parliament has disabled AI features on corporate tablets due to data security concerns.

5.2 - [Targeted AI adoption can drive change, current and former officials say](https://www.nextgov.com/artificial-intelligence/2026/02/targeted-ai-adoption-can-drive-change-current-and-former-officials-say/411550/) - Nextgov

Federal agencies are prioritizing targeted AI and small language models, with the VA expanding its use cases to 367 for 2025 and the NIH utilizing AI to analyze its $50 billion grant portfolio.

5.1 - [Avantos, which makes an AI-native client management system for financial institutions, raised a $25M Series A led by Bessemer, taking its total funding to $35M](https://www.techinasia.com/news/bessemer-leads-25m-series-a-in-us-financial-ai-startup) - Tech in Asia

Avantos raised $25 million in a Series A round led by Bessemer Venture Partners to expand its AI-native client management platform for financial institutions, bringing its total funding to $35 million.

5.1 - [Prediction: These 2Artificial Intelligence(AI) Stocks Will Soar After Feb. 26 (Hint: Not Nvidia)](https://www.fool.com/investing/2026/02/20/prediction-these-2-artificial-intelligence-stocks/) - The Motley Fool

CoreWeave and SoundHound AI report quarterly earnings on February 26, with CoreWeave holding a $56 billion revenue backlog and SoundHound AI maintaining a $1.2 billion backlog for its voice AI technology.

5.1 - [Microsoft Deletes Blog Telling Users To Train AI on Pirated Harry Potter Books](https://it.slashdot.org/story/26/02/20/1918241/microsoft-deletes-blog-telling-users-to-train-ai-on-pirated-harry-potter-books) - Slashdot Linux

Microsoft retracted a blog post that advised developers to train AI models on Azure using a pirated Harry Potter book dataset incorrectly identified as public domain on Kaggle.

5.1 - [Stocks Pressured by AI Concerns and Geopolitical Risks](https://finance.yahoo.com/news/stocks-pressured-ai-concerns-geopolitical-161709514.html) - Barchart

Major U.S. stock indexes declined as investors weighed AI profitability concerns and geopolitical risks against fourth-quarter earnings data showing 75% of S&P 500 companies exceeding expectations.

4.9 - [1 Data Center Stock That Billionaire Philippe Laffont Is Buying Now](https://finance.yahoo.com/news/1-data-center-stock-billionaire-152927247.html) - Barchart

Philippe Laffont’s Coatue Management disclosed a $134 million stake in Vertiv, a data center infrastructure provider that reported a 252% year-over-year surge in organic orders and a $15 billion backlog.

4.9 - [Blue Collar AI Stock Comfort Systems Jumps On Blowout Earnings, Soaring Backlog](https://news.google.com/rss/articles/CBMiggFBVV95cUxQYzhfbmQ3bU5yem9WWTYzMFBGSnZKS3RySmU2Vzd6eEZKMXVHVDlTNHpUXzZrVUJQVDNOSU5EUVNEWktwLWJWTWRxNTBJZXZOdXNxWUM0QS1qMnpBbENzc0JiRmtxaU0yQ1BHVWxNNHNoalZwc2gtSTE3WEZOeUwxQTh3) - Investor's Business Daily

Comfort Systems USA reported record fourth-quarter earnings and a $2.6 billion backlog increase, marking five consecutive quarters of profit growth driven by rising AI data center demand for HVAC and electrical infrastructure.

4.8 - [Goldman Sachs Launches AI-Free Index](https://news.slashdot.org/story/26/02/20/2134238/goldman-sachs-launches-ai-free-index) - Slashdot Linux

Goldman Sachs and S&P Dow Jones Indices launched the S&P ex-AI index (SPXXAI) to track S&P 500 stocks unrelated to artificial intelligence, which represent 55% of the benchmark's weight and gained 32% over the last three years.

4.8 - [I asked the Portal One+ Telegram AI assistant to review itself. Here's how it went](https://hackernoon.com/i-asked-the-portal-one-telegram-ai-assistant-to-review-itself-heres-how-it-went?source=rss) - Hacker Noon

Portal One+ is an open-source, self-hosted AI assistant that uses the OpenClaw runtime and a persistent markdown-based filesystem to provide stateful memory and local data storage for technical users.

4.8 - [Judging by the GPT-4o situation, game developers will have a big problem if they get serious about AI chatbot NPCs](https://www.pcgamer.com/software/ai/judging-by-the-gpt-4o-situation-game-developers-will-have-a-big-problem-if-they-get-serious-about-ai-chatbot-npcs/) - PC Gamer

User distress following OpenAI's GPT-4o retirement highlights risks for developers like Ubisoft and Nvidia, as technical updates to generative AI NPCs may be perceived by players as the death of virtual companions.

4.7 - [Mississippi Nonprofits, ChatGPT, Google, More: Thursday Afternoon ResearchBuzz, February 19, 2026](https://researchbuzz.me/2026/02/19/mississippi-nonprofits-chatgpt-google-more-thursday-afternoon-researchbuzz-february-19-2026/) - ResearchBuzz

Mississippi's State Auditor launched a nonprofit spending database, OpenAI introduced ChatGPT security features following a trademark ruling, and researchers defined 'AI replacement dysfunction' to describe the psychological impact of automation on workers.

4.6 - [Uncovering insiders and alpha on Polymarket with AI](https://twitter.com/peterjliu/status/2024901585806225723) - X

Compound AI launched an AI financial analyst to identify potential corporate insiders on Polymarket by tracking anomalous, high-profit trading patterns in tech-sector markets using a custom-built database.

4.6 - [Palo Alto Networks CEO sees AI as demand driver, not a threat](https://www.cybersecuritydive.com/news/palo-alto-networks-ceo-sees-ai-as-demand-driver-not-a-threat/812585/) - Cybersecurity Dive

Palo Alto Networks reported a 15% year-over-year revenue increase to $2.6 billion and acquired startup Koi, while CEO Nikesh Arora characterized AI as a demand driver that expands the enterprise attack surface.

4.6 - [Mark Cuban says AI won’t take your job anytime soon because it still acts like a hungover college intern—with a $100K price tag to show for it](https://fortune.com/2026/02/20/mark-cuban-smartest-counter-artificial-intelligence-stealing-jobs-six-figure-price-tag-lacks-awareness-ai-layoffs/) - Fortune

Mark Cuban argues that AI job displacement is unlikely in the short term because AI agents currently cost over $100,000 annually and lack the judgment and consistency required to replace human workers.

4.5 - [AI-related stocks edge higher, led by networking, while CoreWeave drags hyperscalers down](https://seekingalpha.com/news/4554722-ai-related-stocks-edge-higher-led-by-networking-while-coreweave-drags-hyperscalers-down) - Seeking Alpha

AI and semiconductor stocks rose after the U.S. Supreme Court struck down President Trump's tariffs, led by gains in networking and optical companies while CoreWeave's performance weighed on hyperscaler stocks.

4.5 - [Siva Hemanth Kolla advances governed enterprise GenAI](https://www.digitaljournal.com/tech-science/siva-hemanth-kolla-advances-governed-enterprise-genai/article) - Digital Journal

Researcher Siva Hemanth Kolla developed a hybrid enterprise GenAI architecture combining Small Language Models and LLM agents to enable traceable decision-making through integrated governance and data lineage tracking.

4.5 - [The Stock That’s Quietly Outperformed NVIDIA 3-to-1 Since 2023](https://247wallst.com/investing/2026/02/19/the-stock-thats-quietly-outperformed-nvidia-3-to-1-since-2023/) - 247wallst

AppLovin achieved a 3,940% return over three years, outperforming NVIDIA's 1,153% gain, as its 2025 annual revenue rose 70% to $5.481 billion and net income increased 111% to $3.334 billion.

4.5 - [Royal Caribbean’s CEO is using AI to predict how many hamburgers you’ll eat—and to compete with Orlando, Vegas and Taylor Swift](https://fortune.com/2026/02/19/royal-caribbean-ceo-jason-liberty-ai-predicts-hamburgers-compete-with-taylor-swift-vegas/) - Fortune

Royal Caribbean uses AI to automate 90% of daily pricing and reduce food waste by 50%, while reporting $17.5 billion in annual earnings and positioning itself against land-based destinations like Las Vegas.

4.4 - [Booking slashes customer service costs with AI, CFO says](https://www.cfodive.com/news/booking-uses-ai-to-slash-customer-service-costs-cfo-says/812624/) - CFO Dive

Booking Holdings reduced customer service costs by 10% per reservation using generative AI automation, despite double-digit growth in bookings and revenue, as part of a transformation program aiming to save $450 million by 2027.

4.3 - [AI Meets Blockchain: NEWITY Secures $11M Strategic Investment to Transform $350B Gap in Small Business Loan Market](https://www.globenewswire.com/news-release/2026/02/19/3241470/0/en/AI-Meets-Blockchain-NEWITY-Secures-11M-Strategic-Investment-to-Transform-350B-Gap-in-Small-Business-Loan-Market.html) - Globe Newswire

NEWITY secured an $11 million investment led by CMT Digital to scale its AI-driven underwriting platform and convert small business debt into blockchain-enabled digital instruments, targeting a $350 billion annual funding gap.

4.2 - [Finji Says TikTok Published Racist AI Ads Of Its Game](https://kotaku.com/finji-tiktok-racist-genai-ads-usual-june-report-support-2000672007) - Kotaku

Game publisher Finji accused TikTok of running unauthorized AI-generated advertisements for the game Usual June that featured sexualized and racist alterations of its Black protagonist through a catalog ads format that lacked guaranteed generative AI opt-outs.

3.9 - [Interface.ai Debuts Agentic AI Collection Tool For Credit Unions](https://www.pymnts.com/artificial-intelligence-2/2026/interface-ai-debuts-agentic-ai-collection-tool-for-credit-unions/) - PYMNTS

Interface.ai launched an agentic AI tool called Smart Collections to help community banks and credit unions automate early-stage delinquency outreach as delinquency rates reached 95 basis points in the third quarter of 2025.

3.8 - [OpenAI Employees Raised Alarms About Canada Shooting Suspect Months Ago](https://www.wsj.com/us-news/law/openai-employees-raised-alarms-about-canada-shooting-suspect-months-ago-b585df62) - The Wall Street Journal

OpenAI employees alerted the company to a Canada shooting suspect months before the attack took place.

3.8 - [Kevin O'Leary Says AI Is Quietly Creating The Biggest Content Opportunity In Years](https://finance.yahoo.com/news/kevin-oleary-says-ai-quietly-104535477.html) - Yahoo

Kevin O'Leary states that AI-driven automated content creation is shifting enterprise marketing budgets and enabling independent contractors to earn up to $500,000 annually, though U.S. electricity shortages pose a significant risk to the industry's expansion.

3.7 - [Bafta To Reward 'Human Creativity' as Film and TV Grapples With AI](https://entertainment.slashdot.org/story/26/02/19/1911203/bafta-to-reward-human-creativity-as-film-and-tv-grapples-with-ai) - Slashdot Linux

Bafta introduced "human achievement" as a guiding principle for its awards, banning AI-generated avatars from performance categories while permitting AI tools in technical production to prioritize human creativity.

3.7 - [How AI Is Rewiring Winemaking and Wine Collecting](https://www.psychologytoday.com/us/blog/the-mind-of-a-collector/202602/how-ai-is-rewiring-winemaking-and-wine-collecting) - Psychology Today

A 2025 study of Italian wine professionals shows 29% use AI for logistics and grape monitoring, with industry-wide adoption expected by 2030 to prioritize environmental management and harvest optimization over subjective tasting systems.

3.6 - [Inside India's Hypocritical AI Plan](https://www.bloomberg.com/news/videos/2026-02-20/opinion-inside-india-s-hypocritical-ai-plan-video) - Bloomberg

India has established a national framework for the development and implementation of artificial intelligence.

3.5 - [AI Disruption Different in Private Markets: Tirupattur](https://www.bloomberg.com/news/videos/2026-02-20/ai-disruption-different-in-private-markets-tirupattur-video) - Bloomberg

Tirupattur indicates that artificial intelligence disruption in private markets follows a distinct trajectory compared to other sectors.

3.5 - [Artificial Intelligence Is an Efficiency Engine](https://www.wsj.com/opinion/artificial-intelligence-is-an-efficiency-engine-2d02c8bc) - The Wall Street Journal

Artificial intelligence functions as a tool for increasing operational efficiency.

3.5 - [Partners Group Seeks to Reassure on AI, Private Credit Exposure](https://www.bloomberg.com/news/articles/2026-02-20/partners-group-seeks-to-reassure-on-ai-private-credit-exposure) - Bloomberg

Partners Group is addressing stakeholder concerns regarding the firm's exposure to artificial intelligence and private credit markets.

3.5 - [AI disruption mentions triple in Q4 – Bitcoin to hit ATH IF THIS happens](https://ambcrypto.com/ai-disruption-mentions-triple-in-q4-bitcoin-to-hit-ath-if-this-happens/) - Ambcrypto

Mentions of AI disruption in Q4 2025 earnings calls tripled year-over-year to 126, while Bitcoin fell 24% as Nvidia gained, potentially positioning the cryptocurrency as a hedge against predicted AI-induced deflation and central bank money printing.

3.4 - [Israeli freelancer platform Fiverr faces revenue drop after losing a third of its value amid AI fears](https://www.haaretz.com/israel-news/2026-02-20/ty-article/.premium/israeli-freelancer-platform-fiverr-expects-to-lose-up-to-12-of-its-revenue-in-2026/0000019c-7724-db1e-a3fd-f73f0fac0000) - Haaretz

Fiverr's market value dropped by one-third to $483 million following disappointing Q4 2025 results and investor concerns over AI automation, with the company forecasting a revenue decline of up to 12% for 2026.

3.2 - [Microsoft uses plagiarized AI slop flowchart to explain how Github works, removes it after original creator Vincent Driessen calls it out: "The AI rip-off was not just ugly. It was careless, blatantly amateuristic, and lacking any ambition, to put it gently. Microsoft unworthy."](https://www.pcgamer.com/software/ai/microsoft-uses-plagiarized-ai-slop-flowchart-to-explain-how-github-works-removes-it-after-original-creator-calls-it-out-careless-blatantly-amateuristic-and-lacking-any-ambition-to-put-it-gently/) - PC Gamer

Microsoft removed an AI-generated flowchart from its GitHub documentation after Vincent Driessen identified it as a plagiarized version of his 2010 branching model containing nonsensical errors and lacking proper attribution.

3.1 - [Rakuten AI Agent Offers Card Users Spending Insights](https://www.pymnts.com/credit-cards/2026/rakuten-ai-agent-offers-card-users-spending-insights/) - PYMNTS

Rakuten launched a free AI agent for its Card Lite app to provide users with chronological spending summaries, statement retrieval, and category-based expense tracking in English and Japanese.

3.0 - [Matthew McConaughey issues stark warning to actors about AI: ‘Own your own lane’](https://www.the-independent.com/arts-entertainment/films/news/matthew-mcconaughey-actors-ai-hollywood-b2923897.html) - The Independent

Matthew McConaughey predicts AI-generated actors will receive major award nominations within five years and urges performers to secure ownership of their digital likeness and voice to ensure consent and compensation.

2.9 - [AMC rejects plan to sneak AI-generated short into its advertising pre-roll](https://news.google.com/rss/articles/CBMingFBVV95cUxQN0t4YVBpVmhtMllXVHB4RWhqZFFwY0ZLVjF1a3NkQ1ZVcTZCSThWaDhQVGY3YWp6SnVSTFBUVHpRQXM3NHlJSUxGWVZETDlTTkFuOVg4dWdfS0Fna3NmcmhuamVqWmVpb09CUzRDMGV2TjFuU05iVlhQNDdUUUp1WVBOWFFmQkdnZVFNUFp2VmRuOThoZmZkUmFJYmVkQQ) - The A.V. Club

AMC Theaters blocked Screenvision Media from screening the AI-generated short film "Thanksgiving Day" in pre-roll advertisements following public backlash, stating the company was not involved in the content's creation.

2.9 - [ASSP Releases White Paper on AI and the Evolving Role of EHS Professionals](https://www.globenewswire.com/news-release/2026/02/19/3241480/0/en/ASSP-Releases-White-Paper-on-AI-and-the-Evolving-Role-of-EHS-Professionals.html) - Globe Newswire

The American Society of Safety Professionals released a white paper outlining how AI transitions safety roles from reactive to proactive through real-time hazard identification and data analysis while maintaining human oversight for output validation.

2.9 - [Reader callout: Do you use AI for retirement planning?](https://www.ft.com/content/07ffcc97-207b-4488-8bf6-87813dde83d1) - Financial Times

A reader callout inquires about the use of artificial intelligence for retirement planning and its potential to replace human financial advice.

2.8 - [Show HN: Argeo – AI Visibility and Generative Engine Optimization (Geo) Advisory](https://www.argeo.ai/en) - Argeo

Strategic advisory firm Argeo utilizes Generative Engine Optimization and structured data to influence how AI models like ChatGPT and Perplexity recommend brands, with case studies showing results within six to eight weeks.

2.6 - [Good legal writers use AI an amplifier, not an author](https://www.abajournal.com/columns/article/good-legal-writers-use-ai-an-amplifier-not-an-author) - ABA Journal

Legal experts recommend using artificial intelligence as an amplifier for human judgment rather than a replacement for authorship to maintain intellectual endurance amid shifting workplace requirements and generational divides.

2.3 - [How AI is Transforming the Travel Industry](https://techdeals.net/how-ai-is-transforming-the-travel-industry/) - TechDeals

A study indicates 82% of travelers intend to use AI for personalized planning, as the global AI travel technology market is projected to reach $89 million by 2025 with a 22% annual growth rate.

2.3 - [Michael S. Baker, P.C. Expands AI Governance Advisory Work Through ArtificialIntelligence.Lawyer](https://www.globenewswire.com/news-release/2026/02/19/3241474/0/en/Michael-S-Baker-P-C-Expands-AI-Governance-Advisory-Work-Through-ArtificialIntelligence-Lawyer.html) - Globe Newswire

Michael S. Baker, P.C. expanded its AI governance advisory services through ArtificialIntelligence.Lawyer to help businesses manage legal risks, data handling, and regulatory compliance associated with integrating artificial intelligence into internal workflows and products.

2.2 - [MVP Development in the Age of AI: How Startups Can Build Smarter, Faster and Leaner](https://hackread.com/mvp-development-ai-startups-build-smarter-faster-leaner/) - HackRead

AI accelerates startup MVP development by reducing prototyping time to days, but requires disciplined validation to manage risks like technical debt, security gaps, and feature bloat.

2.2 - [‘It’s survival of the fittest’: the UK kebab chain seeking an edge with robot slicers](https://www.theguardian.com/technology/2026/feb/20/german-doner-kebab-uk-takeaway-fast-food-business-robotic-slicers) - The Guardian

German Doner Kebab is deploying robotic meat-shavers and self-service screens across 155 UK outlets to reduce costs, aiming to expand to 900 global locations by targeting Gen Z with healthier menu options.

2.1 - [I hate AI side projects](https://dylancastillo.co/posts/ai-side-projects.html) - Dylan Castillo

AI tools like Claude Code have reduced software development time from weeks to minutes, leading to a saturated market of AI-generated projects that complicates the identification of unique work on developer platforms.

2.0 - [AI Darwinism can unleash new potential of energy workforce – Enlit Magazine](https://briansolis.com/2026/02/ai-darwinism-can-unleash-new-potential-of-energy-workforce-enlit-magazine/) - Brian Solis

At the Baker Hughes Annual Meeting, ServiceNow's Brian Solis urged energy leaders to use artificial intelligence for workforce augmentation and operational refactoring rather than simple automation to drive innovation and market leadership.

1.9 - [AI Seen Driving US Convertible Bond Sales to Another Banner Year](https://financialpost.com/pmn/business-pmn/ai-seen-driving-us-convertible-bond-sales-to-another-banner-year) - Financial Post

Artificial intelligence-linked companies drove US convertible bond volume to a record high, a trend expected to continue throughout the current year.

1.7 - [Billionaires Buy an AI Index Fund That Could Turn $500 Per Month Into $485,000](https://www.fool.com/investing/2026/02/20/billionaires-buy-ai-index-fund-turn-500-to-485000/) - The Motley Fool

Israel Englander and Cliff Asness increased their stakes in the Invesco QQQ Trust, an ETF tracking AI leaders like Nvidia, as annual AI spending is projected to grow 30% through 2033.

1.4 - [Matthew McConaughey Believes Actors Will Compete Against AI at the Oscars One Day: ‘Infiltrate Our Category’](https://www.thewrap.com/creative-content/movies/matthew-mcconaughey-ai-actors-oscar-nominations/) - The Wrap

Matthew McConaughey predicts AI-generated personalities will compete against human actors for Academy Awards and advises younger generations to maintain agency over their digital voice and likeness to prevent unauthorized use.

1.0 - [Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you](https://www.reddit.com/r/ChatGPT/comments/1r9qcv2/literally_called_ai_a_tool_and_the_post_is/) - Reddit

While users develop parasocial relationships with AI, technical critiques define large language models as probability engines prone to errors, prompting researchers to use specific engineering techniques to extract factual data without conversational padding.

0.7 - [Samsung Rises on Report of Higher AI Memory Prices. Why Micron Stock Is Falling.](https://www.barrons.com/articles/micron-stock-price-samsung-hbm4-memory-chips-22f59997) - Barron's

Samsung shares rose following reports of higher prices for AI memory chips, while Micron Technology stock declined.

0.2 - [U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in Stock Market Beset With AI Concerns](https://www.barrons.com/articles/u-s-iran-tensions-oil-markets-e1b1dcdc) - Barron's

Escalating tensions between the United States and Iran have shifted stock market sentiment toward lower risk as investors also weigh ongoing concerns regarding artificial intelligence.

In [30]:
# User prompt to run workflow 
# user_prompt = "Run step 6, Cluster articles by topic"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("cluster_by_topic")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting topic extraction for clustering
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Using model 'gemini-3-flash-preview' for topic extraction
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 articles for topic extraction

▶ Starting Step 6: cluster_topics

18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Sending chunk of 3 items to gemini-3-flash-preview
18:45:34 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 3 items returned, validation passed
18:45:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Received chunk: 10 items returned, validation passed
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | All 15 chunks completed for 143 items
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Successfully extracted 583 total topics across articles
18:45:36 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Starting canonical topic classification for 126 topics
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
18:45:43 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Processing 143 items in 15 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 74 (51.7%)
Average cluster size: 34.5 ± 16.5
Cluster size range: 18 - 51
=== Quality Scores ===
Silhouette Score: 0.476 (higher is better)
Calinski-Harabasz Score: 72.9 (higher is better)
Davies-Bouldin Score: 0.758 (lower is better)
HDBSCAN Validity Index: 0.195
Composite Score: 0.336 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 74 (51.7%)
Average cluster size: 34.5 ± 16.5
Cluster size range: 18 - 51
=== Quality Scores ===
Silhouette Score: 0.476 (higher is better)
Calinski-Harabasz Score: 72.9 (higher is better)
Davies-Bouldin Score: 0.758 (lower is better)
HDBSCAN Validity Index: 0.195
Composite Score: 0.336 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 42 (29.4%)
Average cluster size: 4.6 ± 2.5
Cluster size range: 2 - 14
=== Quality Scores ===
Silhouette Score: 0.406 (higher is better)
Calinski-Harabasz Score: 38.1 (higher is better)
Davies-Bouldin Score: 0.759 (lower is better)
HDBSCAN Validity Index: 0.306
Composite Score: 0.356 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 74 (51.7%)
Average cluster size: 34.5 ± 16.5
Cluster size range: 18 - 51
=== Quality Scores ===
Silhouette Score: 0.476 (higher is better)
Calinski-Harabasz Score: 72.9 (higher is better)
Davies-Bouldin Score: 0.758 (lower is better)
HDBSCAN Validity Index: 0.195
Composite Score: 0.336 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 42 (29.4%)
Average cluster size: 4.6 ± 2.5
Cluster size range: 2 - 14
=== Quality Scores ===
Silhouette Score: 0.406 (higher is better)
Calinski-Harabasz Score: 38.1 (higher is better)
Davies-Bouldin Score: 0.759 (lower is better)
HDBSCAN Validity Index: 0.306
Composite Score: 0.356 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 3
Noise points: 65 (45.5%)
Average cluster size: 26.0 ± 11.9
Cluster size range: 11 - 40
=== Quality Scores ===
Silhouette Score: 0.297 (higher is better)
Calinski-Harabasz Score: 58.4 (higher is better)
Davies-Bouldin Score: 1.205 (lower is better)
HDBSCAN Validity Index: 0.095
Composite Score: 0.196 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 8
Noise points: 30 (21.0%)
Average cluster size: 14.1 ± 19.1
Cluster size range: 4 - 61
=== Quality Scores ===
Silhouette Score: 0.247 (higher is better)
Calinski-Harabasz Score: 22.9 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.138
Composite Score: 0.192 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 8
Noise points: 44 (30.8%)
Average cluster size: 12.4 ± 9.8
Cluster size range: 5 - 31
=== Quality Scores ===
Silhouette Score: 0.270 (higher is better)
Calinski-Harabasz Score: 32.4 (higher is better)
Davies-Bouldin Score: 1.036 (lower is better)
HDBSCAN Validity Index: 0.133
Composite Score: 0.202 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        8

[I 2026-02-20 18:50:04,544] Trial 10 finished with value: -0.334786462745989 and parameters: {'min_cluster_size': 10, 'min_samples': 8}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,582] Trial 11 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,596] Trial 12 finished with value: -0.30323857647278063 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,604] Trial 13 finished with value: -0.16296656701519668 and parameters: {'min_cluster_size': 6, 'min_samples': 1}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,624] Trial 14 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,639] Trial 15 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,647] Trial 16 finished with value: -0.1578536420781284 and parameters: {'min_cluster_size': 5, 'min_samples': 3}. Best is trial 2 with value: -0.35782370690220355.
[I 2026-02-20 18:50:04,680] Trial 17 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,713] Trial 18 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,741] Trial 19 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.

=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 75 (52.4%)
Average cluster size: 34.0 ± 15.0
Cluster size range: 19 - 49
=== Quality Scores ===
Silhouette Score: 0.480 (higher is better)
Calinski-Harabasz Score: 76.6 (higher is better)
Davies-Bouldin Score: 0.757 (lower is better)
HDBSCAN Validity Index: 0.189
Composite Score: 0.335 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 18
Noise points: 35 (24.5%)
Average cluster size: 6.0 ± 3.0
Cluster size range: 4 - 15
=== Quality Scores ===
Silhouette Score: 0.371 (higher is better)
Calinski-Harabasz Score: 37.4 (higher is better)
Davies-Bouldin Score: 0.866 (lower is better)
HDBSCAN Validity Index: 0.235
Composite Score: 0.303 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 5
Noise points: 53 (37.1%)
Average cluster size: 18.0 ± 10.3
Cluster size range: 8 - 32
=== Quality Scores ===
Silhouette Score: 0.255 (higher is better)
Calinski-Harabasz Score: 41.0 (higher is better)
Davies-Bouldin Score: 1.246 (lower is better)
HDBSCAN Validity Index: 0.071
Composite Score: 0.163 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 46 (32.2%)
Average cluster size: 24.2 ± 22.9
Cluster size range: 5 - 61
=== Quality Scores ===
Silhouette Score: 0.246 (higher is better)
Calinski-Harabasz Score: 31.4 (higher is better)
Davies-Bouldin Score: 0.922 (lower is better)
HDBSCAN Validity Index: 0.070
Composite Score: 0.158 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        4

[I 2026-02-20 18:50:04,750] Trial 20 finished with value: -0.29504115893461663 and parameters: {'min_cluster_size': 7, 'min_samples': 4}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,775] Trial 21 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,804] Trial 22 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,815] Trial 23 finished with value: -0.2496297107682341 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,841] Trial 24 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,878] Trial 25 finished with value: -0.2496297107682341 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,912] Trial 26 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,927] Trial 27 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,934] Trial 28 finished with value: -0.21453455856771778 and parameters: {'min_cluster_size': 6, 'min_samples': 3}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,945] Trial 29 finished with value: -0.2496297107682341 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 17 with value: -0.3943305476180726.

=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 62 (43.4%)
Average cluster size: 40.5 ± 15.5
Cluster size range: 25 - 56
=== Quality Scores ===
Silhouette Score: 0.452 (higher is better)
Calinski-Harabasz Score: 83.6 (higher is better)
Davies-Bouldin Score: 0.831 (lower is better)
HDBSCAN Validity Index: 0.139
Composite Score: 0.295 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 39 (27.3%)
Average cluster size: 8.0 ± 6.1
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.296 (higher is better)
Calinski-Harabasz Score: 31.9 (higher is better)
Davies-Bouldin Score: 0.984 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.250 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 39 (27.3%)
Average cluster size: 8.0 ± 6.1
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.296 (higher is better)
Calinski-Harabasz Score: 31.9 (higher is better)
Davies-Bouldin Score: 0.984 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.250 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 56 (39.2%)
Average cluster size: 43.5 ± 17.5
Cluster size range: 26 - 61
=== Quality Scores ===
Silhouette Score: 0.410 (higher is better)
Calinski-Harabasz Score: 73.0 (higher is better)
Davies-Bouldin Score: 0.891 (lower is better)
HDBSCAN Validity Index: 0.019
Composite Score: 0.215 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 39 (27.3%)
Average cluster size: 8.0 ± 6.1
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.296 (higher is better)
Calinski-Harabasz Score: 31.9 (higher is better)
Davies-Bouldin Score: 0.984 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.250 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3

[I 2026-02-20 18:50:04,953] Trial 30 finished with value: -0.1578536420781284 and parameters: {'min_cluster_size': 5, 'min_samples': 3}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:04,979] Trial 31 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,010] Trial 32 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,026] Trial 33 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,054] Trial 34 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,069] Trial 35 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,095] Trial 36 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,103] Trial 37 finished with value: -0.3368591930123114 and parameters: {'min_cluster_size': 8, 'min_samples': 7}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,118] Trial 38 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,148] Trial 39 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.

=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 46 (32.2%)
Average cluster size: 24.2 ± 22.9
Cluster size range: 5 - 61
=== Quality Scores ===
Silhouette Score: 0.246 (higher is better)
Calinski-Harabasz Score: 31.4 (higher is better)
Davies-Bouldin Score: 0.922 (lower is better)
HDBSCAN Validity Index: 0.070
Composite Score: 0.158 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        7
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 74 (51.7%)
Average cluster size: 34.5 ± 13.5
Cluster size range: 21 - 48
=== Quality Scores ===
Silhouette Score: 0.482 (higher is better)
Calinski-Harabasz Score: 81.4 (higher is better)
Davies-Bouldin Score: 0.770 (lower is better)
HDBSCAN Validity Index: 0.192
Composite Score: 0.337 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1

[I 2026-02-20 18:50:05,175] Trial 40 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,206] Trial 41 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,249] Trial 42 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,287] Trial 43 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,302] Trial 44 finished with value: -0.32429866538436747 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,313] Trial 45 finished with value: -0.2496297107682341 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,339] Trial 46 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,365] Trial 47 finished with value: -0.3943305476180726 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.

=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (28.7%)
Average cluster size: 5.1 ± 3.4
Cluster size range: 3 - 19
=== Quality Scores ===
Silhouette Score: 0.380 (higher is better)
Calinski-Harabasz Score: 33.7 (higher is better)
Davies-Bouldin Score: 0.810 (lower is better)
HDBSCAN Validity Index: 0.268
Composite Score: 0.324 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 39 (27.3%)
Average cluster size: 8.0 ± 6.1
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.296 (higher is better)
Calinski-Harabasz Score: 31.9 (higher is better)
Davies-Bouldin Score: 0.984 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.250 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 42
Noise points: 20 (14.0%)
Average cluster size: 2.9 ± 1.2
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.419 (higher is better)
Calinski-Harabasz Score: 36.9 (higher is better)
Davies-Bouldin Score: 0.665 (lower is better)
HDBSCAN Validity Index: 0.369
Composite Score: 0.394 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1

[I 2026-02-20 18:50:05,380] Trial 48 finished with value: -0.35782370690220355 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 17 with value: -0.3943305476180726.
[I 2026-02-20 18:50:05,387] Trial 49 finished with value: -0.3368591930123114 and parameters: {'min_cluster_size': 10, 'min_samples': 7}. Best is trial 17 with value: -0.3943305476180726.
18:50:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Optimization completed! Best composite score: 0.3943
18:50:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Best parameters: min_cluster_size=2, min_samples=1
18:50:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Clustering with HDBSCAN (min_cluster_size=2, min_samples=1)
18:50:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Clustering complete: 42 clusters, 20 noise points (14.0%)
18:50:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Generating cluster names

=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 36 (25.2%)
Average cluster size: 4.9 ± 1.7
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 40.7 (higher is better)
Davies-Bouldin Score: 0.787 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.358 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        7
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 74 (51.7%)
Average cluster size: 34.5 ± 13.5
Cluster size range: 21 - 48
=== Quality Scores ===
Silhouette Score: 0.482 (higher is better)
Calinski-Harabasz Score: 81.4 (higher is better)
Davies-Bouldin Score: 0.770 (lower is better)
HDBSCAN Validity Index: 0.192
Composite Score: 0.337 (higher is better)

18:50:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 26: AI's Impact on Careers and Workforce
18:50:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Accenture tells staffers: If you want a promotion, use AI at work (Accenture, Adoption and Spending, Workforce, Jobs And Careers, Consulting, Labor Markets And Productivity, Enterprise AI)
Nascent tech, real fear: how AI anxiety is upending career ambitions (Labor Markets And Productivity, Jobs And Careers, Education, Automation, Mental Health, Society And Culture, Economics)
Good legal writers use AI an amplifier, not an author (Legal Industry, Generational Divide, Labor Markets And Productivity, Legal Writing, Ethics, Workforce, Gen AI)
ASSP Releases White Paper on AI and the Evolving Role of EHS Professionals (Workplace Safety, ASSP, Labor Markets And Productivity, Automation, Enterprise AI, Jobs And Careers, Gen AI)
Michael S. Baker, P.C. Expands AI Governance Advisory Work Through ArtificialIntelligence.Lawyer (AI Governance, Legal Services, Risk Management, Compliance, Legal Issues, Enterprise AI, Policy And Regulation)
AI Darwinism can unleash new potential of energy workforce – Enlit Magazine (Energy Sector, Leadership, Innovation, Workforce, Labor Markets And Productivity, Automation, Enterprise AI)
18:50:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 11: OpenAI's Spending, Strategy, and Competition
18:50:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | OpenAI just hired back another employee from Mira Murati's Thinking Machines Lab (Thinking Machines Lab, OpenAI, Talent Acquisition, Executive Moves, Mira Murati, Startups, Funding)
Sources: OpenAI is telling investors it's targeting ~$600B in total compute spend by 2030, months after Sam Altman touted $1.4T in infrastructure commitments (CNBC) (OpenAI, Funding, Valuation Bubble, Compute Infrastructure, Nvidia, ChatGPT, Adoption and Spending)
Altman and Amodei share a moment of awkwardness at India’s big AI summit (OpenAI, Anthropic, Sam Altman, Dario Amodei, India, Market Competition, Politics)
OpenAI Has No Moat, No Tech Edge, No Lock-in and No Real Plan, Analyst Warns (OpenAI, Market Competition, Business Strategy, Valuation Bubble, Google, Meta, Economics)
Exploring AMI Labs: Yann LeCun’s New World Model Startup (AMI Labs, World Models, Startups, Venture Capital, Safety And Alignment, Industrial Automation, Enterprise AI)
Who’s really paying for your daily free ChatGPT use? OpenAI’s staggering costs revealed (OpenAI, artificial intelligence costs, Business Models, Advertising, IPOs, Valuation Bubble, AI Compute)
18:50:12 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:15 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 41: AI Cybersecurity Threats and Defenses
18:50:15 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Hackers Used AI to Breach 600 Firewalls in Weeks, Amazon Says ()
Microsoft Copilot ignored sensitivity labels twice in eight months — and no DLP stack caught either one (Cybersecurity, Microsoft Copilot, Data Security, DLP Policies, Retrieval Augmented Generation, Enterprise AI, Testing)
Living With the Lethal Trifecta:  A Guide to Personal AI Agent Security (Cybersecurity, Agents, Data Privacy, Safety And Alignment, Virtual Assistants, Privacy And Surveillance)
Using AI to defeat AI (Cybersecurity, Honeypots, Social Engineering, Threat Intelligence, Agents, European Union, Governance)
Google Warns: AI Models Have Become the Industry’s Top Targets for Attackers (Threat Intelligence, Cybersecurity, Phishing, Agents, Intellectual Property, Safety And Alignment, Google)
18:50:15 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:20 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 21: Anthropic Claude AI Developments and Impact
18:50:20 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Anthropic: No, absolutely not, you may not use third-party harnesses with Claude subs (Software Terms, Anthropic, API Pricing, Claude, Legal Issues, Developers, Coding Assistants)
The Surprise Hit That Made Anthropic Into an AI JuggernautAnthropic released Claude Code a year ago, forcing other rivals to play catch-up. ()
Claude's C Compiler shows AI elevates the role of human judgment and vision; it's a milestone, but closely mirrors LLVM/GCC, and hard codes things to pass tests (Compilers, Software Engineering, Claude, Anthropic, Coding Assistants, Labor Markets And Productivity, Rust)
Study: AI chatbots provide less-accurate information to vulnerable users (Bias And Fairness, Algorithmic Bias, Inequality, Claude 3 Opus, GPT-4, MIT, Society And Culture)
Making frontier cybersecurity capabilities available to defenders (Cybersecurity, Software Development, Coding Assistants, Vulnerability Scanning, Anthropic, Claude, Enterprise AI)
18:50:20 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 14: AI Impact on Amazon and Microsoft
18:50:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | An AI coding bot took down Amazon Web Services (AWS, Outages, Agents, Coding Assistants, Cloud Computing, Automation, Enterprise AI)
Phil Spencer will retire after 38 years at Microsoft; Asha Sharma, the president of product in Microsoft's Core AI business, will become the CEO of gaming (Gaming, Microsoft, Executive Moves, Acquisitions, Hardware, Jobs And Careers, Gen AI)
Amazon’s Shiny New Warehouse Robot Just Failed in Spectacular Style (Warehouse Automation, Amazon, Logistics Robots, Labor Markets And Productivity, Hardware, Infrastructure, Adoption and Spending)
Amazon’s cloud ‘hit by two outages caused by AI tools last year’ (AWS, System Reliability, Agents, Cloud Computing, Cybersecurity, Labor Markets And Productivity, Safety And Alignment)
Phil Spencer is exiting Microsoft as AI executive takes over Xbox (Microsoft, Xbox, Gaming, Leadership, Enterprise AI, Entertainment, Governance)
18:50:26 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 2: AI Startups Secure New Funding Rounds
18:50:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | AI code translation startup Code Metal reels in $125M at $1.25B valuation (Code Metal, Funding, Formal Verification, Safety And Alignment, Coding Assistants, Internet of Things, Enterprise AI)
Code Metal, which uses AI to let engineers translate legacy code into modern languages, raised a $125M Series B led by Salesforce Ventures at a $1.25B valuation (Software Modernization, Defense Industry, Venture Capital, Coding Assistants, Cybersecurity, Enterprise AI, Military)
Avantos, which makes an AI-native client management system for financial institutions, raised a $25M Series A led by Bessemer, taking its total funding to $35M (Fintech, Venture Capital, Funding, Agents, Enterprise AI, Automation, Deals)
ZaiNar Raises $100 Million for AI-Powered GPS Alternative (GPS, Startups, Funding, Healthcare, Construction, 5G, Venture Capital)
AI Meets Blockchain: NEWITY Secures $11M Strategic Investment to Transform $350B Gap in Small Business Loan Market (Fintech, Lending, Underwriting, Small Business, Blockchain, Venture Capital, Automation)
18:50:29 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 25: AI Identity, Security, and Social Impact
18:50:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Here's Why You Should Never Use AI to Generate Your Passwords (Cybersecurity, Passwords, Authentication, LLM Limitations, Chatbots, Testing, Gen AI)
When AI Becomes More You Than You (Digital Identity, Social Impact, Agents, Society And Culture, Cognitive Science, Safety And Alignment, Ethics)
Mississippi Nonprofits, ChatGPT, Google, More: Thursday Afternoon ResearchBuzz, February 19, 2026 (Cybersecurity, Safety And Alignment, Mental Health, Labor Markets And Productivity, Intellectual Property, ChatGPT, Google)
Literally called AI a tool and the post is downvoted? Its not a fuckin person! Wtf is wrong with all of you (Society And Culture, Prompt Engineering, Language Models, Cognitive Science, Chatbots, Social Impact, Gen AI)
18:50:32 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 22: OpenClaw AI Agent Security and Adoption
18:50:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | AI coding assistant Cline compromised to create more OpenClaw chaos (Cybersecurity, Supply Chain, Vulnerabilities, NPM, Agents, Coding Assistants, Enterprise AI)
Runlayer is now offering secure OpenClaw agentic capabilities for large enterprises (Cybersecurity, Agents, Governance, Safety And Alignment, Enterprise AI, Adoption and Spending, Runlayer)
OpenClaw AI is going viral. Don’t install it (OpenClaw, Agents, Cybersecurity, Software Risks, Automation, OpenAI, Gen AI)
I asked the Portal One+ Telegram AI assistant to review itself. Here's how it went (AI Assistants, Productivity Tools, Agents, Open Source, Privacy, Automation, Virtual Assistants)
18:50:35 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:38 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 20: AI Coding Assistants in Software Development
18:50:38 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Amazon blames human employees for an AI coding agent’s mistake / Two minor AWS outages have reportedly occurred as a result of actions by Amazon’s AI tools. (AWS, Outages, China, Agents, Coding Assistants, Safety And Alignment, Governance)
“Perfect” AI Code Won’t Fix Your Legacy Stack (Software Engineering, Legacy Systems, Coding Assistants, Labor Markets And Productivity, Productivity, Automation, Opinion)
MVP Development in the Age of AI: How Startups Can Build Smarter, Faster and Leaner (Software Engineering, Coding Assistants, Startups, Minimum Viable Product, Automation, Gen AI, Productivity)
I hate AI side projects (Software Development, Coding Assistants, Claude Code, Labor Markets And Productivity, Society And Culture, Gen AI, Side Projects)
18:50:38 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:40 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 7: India's AI Summit and Strategic Goals
18:50:40 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | India’s AI summit draws global leaders, big pledges and some chaos (Geopolitics, India, Global South, Governance, Investment, Deals, Policy And Regulation)
World Leaders Near Declaration on AI, Indian Government Says (Delhi Declaration, India, AI Sovereignty, AI Governance, Policy And Regulation, Economic Growth, Infrastructure)
AI hit: India hungry to harness US tech giants’ technology at Delhi summit (India, Geopolitics, Digital Sovereignty, Economic Growth, Deals, Society And Culture, Infrastructure)
Inside India's Hypocritical AI Plan ()
18:50:40 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:44 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 1: Robotics and Autonomous Vehicle Developments
18:50:44 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Government Docs Reveal New Details About Tesla and Waymo Robotaxis’ Human Babysitters (Autonomous Vehicles, Robotaxis, Waymo, Tesla, Safety And Alignment, Governance, Policy And Regulation)
Tesla loses bid to overturn $243M Autopilot verdict (Tesla, Lawsuits, Autonomous Vehicles, Autopilot, Legal Issues, Transportation, Ethics)
Tesla's $3 Trillion Opportunity: How Optimus Could Dominate the Robotics Market in 2026 (Tesla, Humanoid Robots, Manufacturing, Elon Musk, xAI, Finance, Automation)
‘It’s survival of the fittest’: the UK kebab chain seeking an edge with robot slicers (Robots, Food Service, Automation, Labor Markets And Productivity, Gen Z, UK, Economics)
18:50:44 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:47 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 0: Development of New AI Hardware
18:50:47 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | OpenAI’s first ChatGPT gadget could be a smart speaker with a camera (OpenAI, Hardware, Smart Speakers, Gadgets, Computer Vision, Facial Recognition, Products)
Sources: OpenAI has 200+ people working on AI devices, including a smart speaker with a camera costing $200 to $300, possibly smart glasses and a smart lamp (OpenAI, Smart Devices, Smart Speakers, Consumer Electronics, Hardware, Products, Gen AI)
Apple researchers develop on-device AI agent that interacts with apps for you (Apple, On-device AI, User Interfaces, Agents, Computer Vision, Language Models, Gen AI)
OpenAI may sell $300 smart speaker with camera — in 2027 (OpenAI, Smart Speakers, Wearables, Facial Recognition, Privacy And Surveillance, Hardware, Computer Vision)
18:50:47 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:50 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 39: AI Agents and AWS Cloud Outages
18:50:50 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Amazon's vibe-coding tool Kiro reportedly vibed too hard and brought down AWS (AWS, Outages, Agents, China, Cloud Computing, Governance, Automation)
AWS suffered ‘at least two outages’ caused by AI tools, and now I’m convinced we’re living inside a ‘Silicon Valley’ episode (AWS, Outages, Agents, Safety And Alignment, China, Coding Assistants, Governance)
Multi-Agent Systems Move Business AI From Chatbot to Operations (Agents, Enterprise AI, Workflow Automation, Financial Operations, Databricks, Adoption and Spending, Gen AI)
18:50:50 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 34: AI Disruption in Markets and Security
18:50:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Cyber Stocks Slide as Anthropic Unveils Claude Security Tool ()
AI Disruption Different in Private Markets: Tirupattur ()
Can We Ride the GenAI Wave Without Getting Subsumed by It? (Medical Automation, Healthcare, Agents, Claude, Stocks, Society And Culture, Enterprise AI)
18:50:54 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:57 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 32: AI Concerns and Geopolitical Market Risks
18:50:57 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Stocks Pressured by AI Concerns and Geopolitical Risks (Stock Market, Valuation Bubble, Economics, Semiconductors, Geopolitics, Finance, AI Compute)
Goldman Sachs Launches AI-Free Index (Investment Indices, Stock Market, Volatility, Valuation Bubble, Goldman Sachs, Economics)
U.S.-Iran Tensions Revive ‘Risk Off’ Vibe in Stock Market Beset With AI Concerns ()
18:50:57 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:50:58 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 30: AI Transforming the Travel Industry
18:50:58 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Royal Caribbean’s CEO is using AI to predict how many hamburgers you’ll eat—and to compete with Orlando, Vegas and Taylor Swift (Royal Caribbean, Travel, Predictive Analytics, Supply Chain Optimization, Automation, Enterprise AI, Hospitality)
Booking slashes customer service costs with AI, CFO says (Customer Service, Finance Automation, Labor Markets And Productivity, Adoption and Spending, Travel, Booking Holdings, Economics)
How AI is Transforming the Travel Industry (Travel, Lifestyle And Travel, Personalization, Market Growth, Recommendation Systems, Gen AI, Adoption and Spending)
18:50:58 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 16: AI Data Center Infrastructure and Investment
18:51:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | VivoPower secures $30M PIPE to accelerate sovereign AI Data center strategy (Data Centers, VivoPower International PLC, Funding, Digital Sovereignty, AI Compute, Infrastructure, Finance)
Blue Collar AI Stock Comfort Systems Jumps On Blowout Earnings, Soaring Backlog (Data Centers, HVAC, Infrastructure, AI Compute, Stocks, Finance)
1 Data Center Stock That Billionaire Philippe Laffont Is Buying Now (Cooling Systems, Data Centers, Infrastructure, Nvidia, Mergers and Acquisitions, Finance, AI Compute)
18:51:01 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 4: AI Regulation and Safeguards
18:51:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | A.I. Is Coming for the 2026 Midterms (Politics and Government, Super PACs, Midterm Elections (2026), Regulation, Safety And Alignment, Anthropic, Lobbying and Lobbyists)
Anthropic-funded group backs candidate attacked by rival AI super PAC (Politics, PACs, RAISE Act, AI Regulation, Safety And Alignment, Anthropic, Alex Bores)
New York nurses union wins 12% raise, AI safeguards in a tentative deal to end monthlong strike (Nursing, Labor Unions, AI Safeguards, Strikes, Healthcare, Contract, New York)
18:51:05 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 3: AI in the Film Industry
18:51:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Bafta To Reward 'Human Creativity' as Film and TV Grapples With AI (Awards, Film, Entertainment, Creativity, Society And Culture, Gen AI, Automation)
AMC rejects plan to sneak AI-generated short into its advertising pre-roll (Cinema, Advertising, Short Films, Entertainment, Society And Culture, Gen AI, Automation)
Matthew McConaughey Believes Actors Will Compete Against AI at the Oscars One Day: ‘Infiltrate Our Category’ (TV And Film And Movies, Hollywood, Digital Likeness, Intellectual Property, Deepfakes, Entertainment, Gen AI)
18:51:08 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:11 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 40: AI and Smart Contract Security
18:51:11 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Specialized AI detects 92% of real-world DeFi exploits (Cybersecurity, DeFi, Blockchain, Agents, Fintech, Language Models, Gen AI)
OpenAI’s latest paper exposes the risks of AI in smart contracts (Software Auditing, Smart Contracts, Cybersecurity, Agents, Safety And Alignment, Cryptocurrency, OpenAI)
18:51:11 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 38: Advancing AI Governance and Interpretability
18:51:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Exposing biases, moods, personalities, and abstract concepts hidden in large language models (Model Interpretability, Safety And Alignment, Bias And Fairness, MIT, Language Models, Testing, Cognitive Science)
Siva Hemanth Kolla advances governed enterprise GenAI (Small Language Models, Agents, Orchestration, Enterprise AI, Automation, Governance)
18:51:14 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO |

18:51:17 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | 37: Walmart's AI Strategy and Financial Results
18:51:17 | NewsletterAgent.test_newsletter_20260220182740633380 | INFO | Walmart outlines big AI ambitions as it reports mixed results (Walmart, Retail, Agents, E-commerce, Supply Chain Optimization, Enterprise AI, Automation)
Walmart touts early AI wins as revenues rise (Walmart, Retail, Automation, E-commerce, Supply Chain Optimization, Agents, Gen AI)

================================================================================
⏱️  Total execution time: 405.08s
📊 Final result:
✅ Step 6 cluster_topics completed successfully! Organized 143 articles into topic clusters.

In [31]:
# candidates for upgrading model, in some cases to gpt-5.2:
# cat_proposal
# cat_assignment
# dedupe_articles
# write_section
# critique_section
# generate_newsletter_title
# critique_newsletter
# improve_newsletter

In [ ]:
# User prompt to run workflow
# user_prompt = "Run step 7, select section topics"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("select_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

In [ ]:
# User prompt to run workflow
# user_prompt = "Run step 8, draft sections"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("draft_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

In [ ]:
newsletter_section_df = state.newsletter_section_df

newsletter_section_df

In [ ]:
Markdown(state.display_newsletter().replace("$","\\\$"))

In [ ]:
# User prompt to run workflow
# user_prompt = "Run step 9, finalize newsletter"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("finalize_newsletter")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

In [ ]:
display(Markdown(state.final_newsletter.replace("$", "\\\$")))

In [ ]:
print(state.get_workflow_status_report())

In [ ]:
state.print_workflow_status()

In [ ]:
print(state.final_newsletter)