# Run Agent
- Implement a workflow to write a daily AI newsletter
- see README.md for details

In [1]:
import os
import yaml
import dotenv
import logging
import json
import yaml
from datetime import datetime
import time
import random
import glob
import pickle
import sqlite3

from pathlib import Path

import asyncio
import nest_asyncio

import pydantic
from pydantic import BaseModel, Field, RootModel
from typing import Dict, TypedDict, Type, List, Optional, Any, Iterable, Text
from dataclasses import dataclass, field
from enum import Enum

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import hdbscan

import openai
from openai import AsyncOpenAI

import agents
from agents.exceptions import InputGuardrailTripwireTriggered
from agents import (Agent, Runner, Tool, OpenAIResponsesModel, 
                    ModelSettings, FunctionTool, InputGuardrail, GuardrailFunctionOutput,
                    SQLiteSession, set_default_openai_api, set_default_openai_client
                   )


import tenacity
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from IPython.display import HTML, Image, Markdown, display

from log_handler import SQLiteLogHandler, setup_sqlite_logging, sanitize_error_for_logging
from config import LOGDB
from llm import LLMagent, LangfuseClient  # methods to apply prompts async to large batches
from db import Url, AgentState

from fetch import Fetcher # fetch news urls
from newsletter_state import NewsletterAgentState, StepStatus
from news_agent import NewsletterAgent

In [2]:
print(f"OpenAI:            {openai.__version__}")
print(f"OpenAI Agents SDK  {agents.__version__}")
print(f"Pydantic           {pydantic.__version__}")

OpenAI:            2.21.0
OpenAI Agents SDK  0.9.0
Pydantic           2.12.5

In [3]:
dotenv.load_dotenv()

# to run async in jupyter notebook
nest_asyncio.apply()

# turn off open telemetry (langfuse)
os.environ["OTEL_SDK_DISABLED"] = "true"

# verbose OpenAI console logging if something doesn't work
# logging.basicConfig(level=logging.DEBUG)
# openai_logger = logging.getLogger("openai")
# openai_logger.setLevel(logging.DEBUG)

In [4]:
# modules create a default logger, or we can pass this logger
debuglevel = logging.DEBUG

def setup_logging(session_id: str = "default", db_path: str = "agent_logs.db") -> logging.Logger:
    """Set up logging to console and SQLite database."""

    # Create logger
    logging.basicConfig()
    logger = logging.getLogger(f"NewsletterAgent.{session_id}")
    logger.setLevel(debuglevel)

    # Clear any existing handlers
    logger.handlers.clear()

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(debuglevel)
    console_formatter = logging.Formatter(
        '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
        datefmt='%H:%M:%S'
    )
    console_handler.setFormatter(console_formatter)

    # SQLite handler
    sqlite_handler = SQLiteLogHandler(db_path)
    sqlite_handler.setLevel(debuglevel)
    sqlite_formatter = logging.Formatter('%(message)s')
    sqlite_handler.setFormatter(sqlite_formatter)

    # Add handlers to logger
    logger.addHandler(console_handler)
    logger.addHandler(sqlite_handler)

    # Prevent propagation to root logger
    logger.propagate = False

    return logger

logger = setup_logging("newsletter_agent", "test_logs.db")

# Log some test messages
logger.debug("Test debug message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.info("Test info message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.warning("Test warning message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.error("Test error message", extra={
    'step_name': 'error_step',
    'agent_session': 'demo_session'
})

sanitize_error_for_logging("log with some bad stuff for the filter: sk-proj-123456789012345678901234567890123456789012345678")

08:40:35 | NewsletterAgent.newsletter_agent | DEBUG | Test debug message
08:40:35 | NewsletterAgent.newsletter_agent | INFO | Test info message
08:40:35 | NewsletterAgent.newsletter_agent | WARNING | Test warning message
08:40:35 | NewsletterAgent.newsletter_agent | ERROR | Test error message

'log with some bad stuff for the filter: [API_KEY_REDACTED]'

In [8]:
# look up recent sessions
conn = sqlite3.connect("newsletter_agent.db")
AgentState.list_sessions(conn, n_records=10)

['test_newsletter_20260216080715128568',
 'test_newsletter_20260216074056346407',
 'test_newsletter_20260216071603072063',
 'test_newsletter_20260215230952864288',
 'test_newsletter_20260215223006688628',
 'test_newsletter_20260215215341994191',
 'test_newsletter_20260215073155703123',
 'test_newsletter_20260215072749475436',
 'test_newsletter_20260214083433211276',
 'test_newsletter_20260214082909417070']

In [9]:
z = AgentState.get_latest_by_session(conn, "test_newsletter_20260216080715128568")
z.step_name

'download_articles'

In [10]:
for y in z.get_all_by_session(conn, "test_newsletter_20260216080715128568"):
    print(y.session_id, y.step_name, y.updated_at)

test_newsletter_20260216080715128568 initialize 2026-02-16 08:07:15.141565
test_newsletter_20260216080715128568 gather_urls 2026-02-16 08:07:27.133667
test_newsletter_20260216080715128568 check_workflow_status 2026-02-16 08:07:29.024856
test_newsletter_20260216080715128568 filter_urls 2026-02-16 08:12:30.368229
test_newsletter_20260216080715128568 download_articles 2026-02-16 08:33:04.682609

# Run Agent Worfklow

In [11]:
print("🚀 Creating NewsletterAgent...")
do_download=False
reprocess_since=None
reprocess_since='2026-02-15 23:09:00'

try:
    # set up state if you want to resume previous session
    session_id = 'test_newsletter_20260216080715128568'
    step_name = 'download_articles'
except Exception as e:
    print(e)

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable not set")

# Set up OpenAI client for the agents SDK
set_default_openai_client(AsyncOpenAI(api_key=api_key))

# Create agent with persistent state
if 'session_id' in vars():
    # load state from db for session_id and state
    print("session_id is defined")
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db", 
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                )
    state = state.load_from_db(step_name)
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=True, timeout=30)    
else:
    # create new session
    print("session_id is not defined")
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")    
    session_id = f"test_newsletter_{timestamp}"
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db",
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                ) 
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=False, timeout=30)
    agent.verbose=False  # there seems to be a bug where saved agents are saved or restored with verbose=True
    state.serialize_to_db("initialize")

08:41:12 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using provided state with 94 articles

🚀 Creating NewsletterAgent...
session_id is defined
test_newsletter_20260216080715128568
Initialized NewsletterAgent with persistent state and 9-step workflow
Session ID: test_newsletter_20260216080715128568

In [12]:
agent.state.get_status()

{'headlines': {'total': 94},
 'sources': {'config_file': 'sources.yaml', 'loaded_sources': 0},
 'topics': {'cluster_topics': 0, 'topics': []},
 'workflow': {'current_step': 'download_articles',
  'workflow_complete': False,
  'progress_percentage': 22.22222222222222,
  'completed_steps': 2,
  'total_steps': 9,
  'max_edits': 2,
  'concurrency': 12,
  'do_download': False,
  'reprocess_since': datetime.datetime(2026, 2, 15, 23, 9)},
 'processing': {'topic_clusters': 0,
  'newsletter_sections': 0,
  'final_newsletter_length': 0}}

In [15]:
for step in agent.state.steps:
    print(step)
    print("---")

✅ Gather URLs [complete] (took 1.1s)
   ✅ Step 1 gather_urls completed successfully! Gathered 854 articles from 17 sources.

📊 Articles stored in persistent state: 696
---
✅ Filter URLs [complete] (took 299.9s)
   ✅ Step 2 filter_urls completed successfully! Removed 504 duplicate URLs, classified 192 new articles, found 96 AI-related.
---
✅ Download Articles [complete] (took 10.2s)
   ✅ Step 3 download_articles completed successfully! Total articles: 94; AI-related articles: 94; HTML files: 85; Text files: 85
---
⚪ Extract Summaries [not_started]

---
⚪ Rate Articles [not_started]

---
⚪ Cluster By Topic [not_started]

---
⚪ Select Sections [not_started]

---
⚪ Draft Sections [not_started]

---
⚪ Finalize Newsletter [not_started]

---

In [16]:
# User prompt to run workflow
user_prompt = "Show the workflow status"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Show the workflow status'
================================================================================

08:43:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting check_workflow_status
08:43:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 4.55s
📊 Final result:
Current workflow status:

- Progress: 33.3% (3/9 complete)
- Summary: 3 complete, 0 started, 0 failed, 6 not started
- Next step: Extract Summaries (Step 3)

Step details:
- Step 0: Gather URLs — complete
- Step 1: Filter URLs — complete
- Step 2: Download Articles — complete
- Step 3: Extract Summaries — not_started
- Step 4: Rate Articles — not_started
- Step 5: Cluster By Topic — not_started
- Step 6: Select Sections — not_started
- Step 7: Draft Sections — not_started
- Step 8: Finalize Newsletter — not_started

Data summary:
- Total articles: 94 (AI-related)
- HTML/text files stored: 85

Would you like me to start Step 3 (Extract Summaries) now, run all remaining steps, or do something else?

In [12]:
# User prompt to run a workflow step
user_prompt = "Run step 1, gather urls"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Run step 1, gather urls'
================================================================================

08:07:23 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting check_workflow_status
08:07:23 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed check_workflow_status
08:07:26 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting Step 1: Gather URLs
2026-02-16 08:07:26,015 - fetcher_5737076880 - INFO - [fetcher_init] Loading sources from sources.yaml
2026-02-16 08:07:26,028 - fetcher_5737076880 - INFO - [fetcher_init] Loaded 17 sources: 5 RSS, 11 HTML, 1 API
2026-02-16 08:07:26,029 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Ars Technica': type=html, url=https://arstechnica.com/ai/
2026-02-16 08:07:26,029 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Bloomberg': type=RSS, url=https://www.bloomberg.com/ai
2026-02-16 08:07:26,029 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Business Insider': type=html, url=https://www.businessinsider.com/tech
2026-02-16 08:07:26,029 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'FT': type=RSS, url=https://www.ft.com/artificial-intelligence
2026-02-16 08:07:26,030 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Feedly AI': type=html, url=https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-16 08:07:26,030 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Hacker News': type=RSS, url=https://news.ycombinator.com/
2026-02-16 08:07:26,030 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'HackerNoon': type=RSS, url=https://hackernoon.com/tagged/ai
2026-02-16 08:07:26,030 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'New York Times': type=RSS, url=https://www.nytimes.com/section/technology
2026-02-16 08:07:26,031 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Reddit': type=RSS, url=https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-16 08:07:26,031 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Techmeme': type=RSS, url=https://www.techmeme.com/river
2026-02-16 08:07:26,031 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'The Register': type=RSS, url=https://www.theregister.com/software/ai_ml/
2026-02-16 08:07:26,031 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'The Verge': type=RSS, url=https://www.theverge.com/ai-artificial-intelligence
2026-02-16 08:07:26,032 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'VentureBeat': type=RSS, url=https://venturebeat.com/category/ai
2026-02-16 08:07:26,032 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'WSJ': type=RSS, url=https://www.wsj.com/tech/ai
2026-02-16 08:07:26,032 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'Washington Post': type=RSS, url=https://www.washingtonpost.com/technology/innovations/
2026-02-16 08:07:26,032 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'The Guardian': type=RSS, url=https://www.theguardian.com/uk/technology
2026-02-16 08:07:26,032 - fetcher_5737076880 - DEBUG - [fetcher_sources] Source 'NewsAPI': type=rest, url=https://newsapi.org/v2/everything
2026-02-16 08:07:26,033 - fetcher_5737076880 - INFO - [fetcher_init] Fetcher initialized with max_concurrent=8
2026-02-16 08:07:26,033 - fetcher_5737076880 - INFO - [fetch_all] Starting fetch_all for 17 sources
2026-02-16 08:07:26,033 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Ars Technica: https://arstechnica.com/ai/
2026-02-16 08:07:26,033 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Ars_Technica.html
2026-02-16 08:07:26,073 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Ars_Technica.html
2026-02-16 08:07:26,074 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Ars Technica: 30 articles
2026-02-16 08:07:26,074 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Bloomberg: https://www.bloomberg.com/ai
2026-02-16 08:07:26,074 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Bloomberg.html
2026-02-16 08:07:26,101 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Bloomberg.html
2026-02-16 08:07:26,102 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Bloomberg: 40 articles
2026-02-16 08:07:26,102 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Business Insider: https://www.businessinsider.com/tech
2026-02-16 08:07:26,102 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Business_Insider.html
2026-02-16 08:07:26,119 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Business_Insider.html
2026-02-16 08:07:26,120 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Business Insider: 16 articles
2026-02-16 08:07:26,120 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from FT: https://www.ft.com/artificial-intelligence
2026-02-16 08:07:26,120 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/FT.html
2026-02-16 08:07:26,145 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/FT.html
2026-02-16 08:07:26,145 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for FT: 104 articles
2026-02-16 08:07:26,145 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Feedly AI: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-16 08:07:26,146 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Feedly_AI.html
2026-02-16 08:07:26,192 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Feedly_AI.html
2026-02-16 08:07:26,192 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Feedly AI: 106 articles
2026-02-16 08:07:26,192 - fetcher_5737076880 - INFO - [fetch_rss] Fetching RSS from Hacker News: https://news.ycombinator.com/rss
2026-02-16 08:07:26,192 - fetcher_5737076880 - INFO - [fetch_rss] Fetching RSS from HackerNoon: https://hackernoon.com/tagged/ai/feed
2026-02-16 08:07:26,193 - fetcher_5737076880 - INFO - [fetch_rss] Fetching RSS from New York Times: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
2026-02-16 08:07:26,193 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Reddit: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-16 08:07:26,193 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Reddit.html

▶ Starting Step 1: gather_urls

2026-02-16 08:07:26,220 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Reddit.html
2026-02-16 08:07:26,220 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Reddit: 62 articles
2026-02-16 08:07:26,220 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Techmeme: https://www.techmeme.com/river
2026-02-16 08:07:26,221 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Techmeme.html
2026-02-16 08:07:26,242 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Techmeme.html
2026-02-16 08:07:26,242 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Techmeme: 180 articles
2026-02-16 08:07:26,242 - fetcher_5737076880 - INFO - [fetch_rss] Fetching RSS from The Register: https://www.theregister.com/software/ai_ml/headlines.atom
2026-02-16 08:07:26,243 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from The Verge: https://www.theverge.com/ai-artificial-intelligence
2026-02-16 08:07:26,243 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/The_Verge.html
2026-02-16 08:07:26,277 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/The_Verge.html
2026-02-16 08:07:26,277 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for The Verge: 1 articles
2026-02-16 08:07:26,277 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from VentureBeat: https://venturebeat.com/category/ai
2026-02-16 08:07:26,277 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/VentureBeat.html
2026-02-16 08:07:26,283 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/VentureBeat.html
2026-02-16 08:07:26,284 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for VentureBeat: 23 articles
2026-02-16 08:07:26,284 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from WSJ: https://www.wsj.com/tech/ai
2026-02-16 08:07:26,284 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/WSJ.html
2026-02-16 08:07:26,308 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/WSJ.html
2026-02-16 08:07:26,308 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for WSJ: 55 articles
2026-02-16 08:07:26,308 - fetcher_5737076880 - INFO - [fetch_html] Using existing HTML file from Washington Post: https://www.washingtonpost.com/technology/innovations/
2026-02-16 08:07:26,308 - fetcher_5737076880 - INFO - [fetch_html] Parsing HTML file: download/sources/Washington_Post.html
2026-02-16 08:07:26,325 - fetcher_5737076880 - INFO - [fetch_html] Parsed HTML file: download/sources/Washington_Post.html
2026-02-16 08:07:26,325 - fetcher_5737076880 - INFO - [fetch_html] HTML fetch successful for Washington Post: 24 articles
2026-02-16 08:07:26,326 - fetcher_5737076880 - INFO - [fetch_rss] Fetching RSS from The Guardian: https://www.theguardian.com/uk/technology/rss
2026-02-16 08:07:26,326 - fetcher_5737076880 - INFO - [newsapi] Fetching top 100 stories matching artificial intelligence since 2026-02-15T08:07:26 from NewsAPI
2026-02-16 08:07:26,581 - fetcher_5737076880 - INFO - [fetch_rss] RSS fetch successful for New York Times: 24 articles
2026-02-16 08:07:26,825 - fetcher_5737076880 - INFO - [fetch_rss] RSS fetch successful for The Register: 50 articles
2026-02-16 08:07:26,838 - fetcher_5737076880 - INFO - [fetch_rss] RSS fetch successful for HackerNoon: 50 articles
2026-02-16 08:07:26,849 - fetcher_5737076880 - INFO - [fetch_rss] RSS fetch successful for The Guardian: 24 articles
2026-02-16 08:07:27,109 - fetcher_5737076880 - INFO - [fetch_rss] RSS fetch successful for Hacker News: 30 articles
2026-02-16 08:07:27,111 - fetcher_5737076880 - INFO - [fetch_all] fetch_all completed: 17 successful, 0 failed, 854 total articles

              source  url
0       Ars Technica   29
1          Bloomberg   29
2   Business Insider   16
3                 FT   47
4          Feedly AI   97
5        Hacker News   29
6         HackerNoon   50
7     New York Times   24
8            NewsAPI   35
9             Reddit   48
10          Techmeme  158
11      The Guardian   21
12      The Register   50
13         The Verge    1
14       VentureBeat   14
15               WSJ   30
16   Washington Post   18

,source,title,url,published,rss_summary,id
0,Ars Technica,I spent two days gigging at RentAHuman and did...,https://arstechnica.com/ai/2026/02/i-spent-two...,NaN,NaN,0
1,Ars Technica,OpenAI sidesteps Nvidia with unusually fast co...,https://arstechnica.com/ai/2026/02/openai-side...,NaN,NaN,1
2,Ars Technica,"Attackers prompted Gemini over 100,000 times w...",https://arstechnica.com/ai/2026/02/attackers-p...,NaN,NaN,2
3,Ars Technica,We let Chrome’s Auto Browse agent surf the web...,https://arstechnica.com/google/2026/02/tested-...,NaN,NaN,3
4,Ars Technica,"Retraction: After a routine code rejection, an...",https://arstechnica.com/ai/2026/02/after-a-rou...,NaN,NaN,4
...,...,...,...,...,...,...
691,NewsAPI,‘Iron Sky’ Producers Prepping Communists-on-Ma...,http://www.hollywoodreporter.com/movies/movie-...,2026-02-15T09:30:00Z,NaN,691
692,NewsAPI,"Bill Gates to visit Amaravati tomorrow, meet C...",https://newsmeter.in/top-stories/bill-gates-to...,2026-02-15T09:28:39Z,NaN,692
693,NewsAPI,Maureen Dowd: The world is in peril. Don’t wor...,https://www.irishtimes.comhttps://www.nytimes....,2026-02-15T12:29:44Z,NaN,693
694,NewsAPI,A safety net in sickness and in health,https://www.thehindubusinessline.com/specials/...,2026-02-15T13:04:06Z,NaN,694
695,NewsAPI,Is This Quiet Ad-Tech Firm A Hidden Gem Or A L...,https://bizbrief.ie/news/marketing/is-this-qui...,2026-02-15T10:07:10Z,NaN,695

08:07:27 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed Step 1: Gathered 854 articles
08:07:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting check_workflow_status
08:07:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 9.87s
📊 Final result:
Step 1 (Gather URLs) completed.

Summary:
- Gathered 854 headlines from 17 sources.
- 696 articles stored in persistent state.

Current workflow progress:
- Progress: 11.1% (1/9 complete)
- Next step: Filter URLs (keep AI-related only)

Would you like me to proceed to the next step (Filter URLs), run all remaining steps, or stop here?

In [13]:
countdf = pd.DataFrame(state.headline_data) \
    .groupby("source") \
    .count()[["id"]] \
    .reset_index() \
    .rename(columns={'id': 'count'}) \
    .sort_values("count", ascending=False)
countdf

              source  count
10          Techmeme    158
4          Feedly AI     97
12      The Register     50
6         HackerNoon     50
9             Reddit     48
3                 FT     47
8            NewsAPI     35
15               WSJ     30
0       Ars Technica     29
1          Bloomberg     29
5        Hacker News     29
7     New York Times     24
11      The Guardian     21
16   Washington Post     18
2   Business Insider     16
14       VentureBeat     14
13         The Verge      1

In [14]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 11.1% (1/9 complete)
➡️  Next step: Step 1: Filter URLs

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 854 articles from 17 sources.

📊 Articles stored in persistent state: 696
  ⭕ Step 1: Filter URLs            | not_started
  ⭕ Step 2: Download Articles      | not_started
  ⭕ Step 3: Extract Summaries      | not_started
  ⭕ Step 4: Rate Articles          | not_started
  ⭕ Step 5: Cluster By Topic       | not_started
  ⭕ Step 6: Select Sections        | not_started
  ⭕ Step 7: Draft Sections         | not_started
  ⭕ Step 8: Finalize Newsletter    | not_started
============================================================

In [15]:
# Run tool directly without LLM processing an input prompt or results
# user_prompt = "Run step 2, filter urls"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)
# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("filter_urls")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting Step 2: Filter URLs
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 🔍 Filtering 696 headlines...
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 🔄 Checking for duplicates seen before 2026-02-15T23:09:00
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 🔍 Filtering 696 articles for dupes.
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/i-spent-two-days-gigging-at-rentahuman-and-didnt-make-a-single-cent/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/attackers-prompted-gemini-over-100000-times-while-trying-to-clone-it-google-says/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/tested-how-chromes-auto-browse-agent-handles-common-web-tasks/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-a-routine-code-rejection-an-ai-agent-published-a-hit-piece-on-someone-by-name/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/staff/2026/02/editors-note-retraction-of-article-containing-fabricated-quotations/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/space/2026/02/nasa-chief-vows-to-solve-sls-rocket-fueling-issues-before-artemis-iii/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://arstechnica.com/science/2026/02/it-aint-no-unicorn-these-researchers-have-interviewed-130-bigfoot-hunters/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/gadgets/2026/02/alphabet-selling-very-rare-100-year-bunds-to-help-fund-ai-investment/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-moltbook-ai-agents-can-now-hang-out-in-their-own-space-faring-mmo/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/sixteen-claude-ai-agents-working-together-created-a-new-c-compiler/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/waymo-leverages-genie-3-to-create-a-world-model-for-self-driving-cars/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/features/2026/02/why-darren-aronofsky-thought-an-ai-generated-historical-docudrama-was-a-good-idea/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/with-gpt-5-3-codex-openai-pitches-codex-for-more-than-just-writing-code/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/increase-of-ai-bots-on-the-internet-sparks-arms-race/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/should-ai-chatbots-have-ads-anthropic-says-no/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/apple/2026/02/xcode-26-3-adds-support-for-claude-codex-and-other-agentic-tools-via-mcp/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/senior-staff-departing-openai-as-firm-prioritizes-chatgpt-development/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/the-rise-of-moltbook-suggests-viral-ai-prompts-may-be-the-next-big-security-threat/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/spacex-acquires-xai-plans-1-million-satellite-constellation-to-power-it/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-picks-up-pace-against-claude-code-with-new-codex-desktop-app/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/developers-say-ai-coding-tools-work-and-thats-precisely-what-worries-them/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/security/2026/01/web-portal-leaves-kids-chats-with-ai-toy-open-to-anyone-with-gmail-account/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/how-often-do-ai-chatbots-lead-users-down-a-harmful-path/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-project-genie-lets-you-create-interactive-worlds-from-a-photo-or-prompt/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/new-openai-tool-renews-fears-that-ai-slop-will-overwhelm-scientific-research/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-begins-rolling-out-chromes-auto-browse-ai-agent-today/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/report-china-approves-import-of-high-end-nvidia-ai-chips-after-weeks-of-uncertainty/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/goldman-s-snider-says-analysts-turn-positive-on-software-profits
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/amd-takes-on-nvidia-in-india-with-expanded-tata-ai-partnership
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-13/ai-kingpins-adopt-crypto-s-playbook-in-bid-to-get-allies-elected-to-congress
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/anthropic-boosts-india-ai-push-via-flag-airline-cognizant-pacts
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/ai-is-causing-the-price-of-computer-memory-to-surge
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/fund-beating-99-of-peers-sees-few-software-firms-surviving-ai
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/alibaba-unveils-major-ai-model-upgrade-ahead-of-deepseek-release
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/australia-m-a-sparks-to-life-with-8-billion-macquarie-qube-deal
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-31/elon-musk-s-ai-push-has-him-considering-mergers-in-search-for-capital
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-19/grok-ai-sexualized-images-expose-gaps-in-oversight-enforcement
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2025-11-18/china-s-tsinghua-university-is-beating-us-in-the-race-for-ai-patents
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-10/trump-s-ai-policy-shaped-by-vc-tech-giant-andreessen-horowitz
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-15/a-stock-market-doom-loop-is-hitting-everything-that-touches-ai
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2024-12-13/ai-wants-more-data-more-chips-more-power-more-water-more-everything
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/videos/2026-02-16/musk-cook-warn-of-chip-crisis-as-demand-from-ai-grows-video
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-16/jpmorgan-sees-inflection-point-for-health-care-stocks-video
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/videos/2026-02-13/bloomberg-tech-2-13-2026-video
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/telkom-indonesia-is-said-to-revive-plan-for-data-center-stake-sale
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-16/alibaba-leads-tech-slide-after-pentagon-briefly-shows-blacklist
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-16/india-seeks-role-in-shaping-ai-future-with-summit-of-tech-chiefs
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-15/openai-hires-openclaw-ai-agent-developer-peter-steinberg
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-15/uk-s-starmer-wants-ai-chatbots-to-follow-online-safety-rules
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/amazon-engineers-grate-against-internal-limits-claude-code-kiro-ai-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/salesforce-appoints-new-leaders-executive-reshuffle-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/microsoft-manager-explains-how-she-pivoted-from-admin-to-ai-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/sam-altman
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/instacart-salaries-how-much-pay-tech-engineers-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/dario-amodei-anthropic-profit-pressure-versus-safety-mission-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/mrbeast-is-hiring-a-head-of-tiktok-job-description-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/resignation-letters-quit-openai-anthropic-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/snowflake-ceo-sridhar-ramaswamy-software-dumb-data-pipe-ai-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/elon-musk-anthropic-philosopher-amanda-askell-debate-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/sam-altman-hires-openclaw-creator-peter-steinberger-personal-ai-agents-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/guides/tech/best-dolby-atmos-soundbar
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/job-hunting-on-tinder-hinge-grindr-dating-app-networking-referrals-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/ai-fatigue-gary-marcus-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/dbd1d803-ab37-43f1-920f-fce74952313a
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/c30ded60-bece-45e0-981d-653e1e3e9818
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/131f0e09-88ed-4597-8408-e76a50e36618
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/62f4a0f7-ffc9-49c8-b1e5-649703018dd1
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/94633f65-04c0-4cea-b682-98c17720eebc

▶ Starting Step 2: filter_urls

08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/9784d307-f0d0-4c1e-b81a-0f89b426c1dc
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/45b172e6-df8c-41a7-bba9-3e21e361d3aa
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/298a38bb-4cc1-44f3-bd62-6aff25d58b94
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/e68d68da-3966-47c7-b310-3f39fd4b69b2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/92dfd571-8d34-42f1-8be8-dce126998e37
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/11f4bbdf-51ed-4ac4-80fb-1d6872f1abc6
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/64729378-9a91-4c4f-bd4c-f51fd9b78b1f
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/9e5742e4-adae-4178-9951-7372adeb7ffc
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/c5160af2-3a59-41a2-9948-84566019f4f4
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/3fc82496-1132-4cb3-a967-25c4c274fbea
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/9fbc4ae4-c279-44fa-9d59-d49bc970c4ac
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/414d2b8c-20d4-4892-a730-255c0af7edb8
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/4f40f3fe-43b3-42bd-bcb7-e36e42df55c7
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/89985a10-1283-40fa-8dc1-9daa6c360b45
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/62b8713f-cd72-4838-b8ac-708b91b2830f
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/a5b88548-cf2d-4492-bb67-f1b7db3eed0c
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/3dd3f37b-a783-4f12-a837-764e9f429b01
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/b06ca67e-41b0-4402-9b39-9e4b432a1291
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/0a097786-09b9-4087-8837-0005afdf02b1
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/15dc1349-8da4-4f21-962d-09d9cf4b78bd
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/b04fc3d5-c916-4ac8-ab4f-a65a9f4e60c5
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/15917aa4-2d40-49be-85c3-da395b16e7f1
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/15b014ea-db34-472b-b7f7-e5905f611e9b
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/d47fc46a-12fb-4f2e-8bf5-e97b68dbecf0
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.ft.com/content/3659b953-8a3a-4e13-b322-c973a545b836
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/320c14a2-1428-4904-b978-6fe06b3e25bf
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/90911726-f7c8-40c6-a326-b0f776cb88a7
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/3d4a9683-b70a-4953-b21b-b3ea07d693a3
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/d52b97ba-8199-4877-b210-e7575cbdcaf2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/d5fb92b7-02fa-4c16-93f5-aa1bea70f095
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/40d04966-d526-4314-9c2a-c721c88aaab1
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/915a32cf-d62d-4caf-b539-8525e52257ad
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/513ddbc1-0b68-4200-bb2e-ce920fa601aa
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/715fca08-b496-404a-bd6a-aa7124c4b1b8
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/f1ec830c-2f08-4b1a-b70f-7330f260753c
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/d21f4583-a05d-4a94-8404-f1e02a332283
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.cnn.com/2026/02/16/business/ai-disruption-fears-us-stocks
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/jefferies-sets-28-pt-engene-120409756.html
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.thedailybeast.com/obsessed/simpsons-star-nancy-cartright-68-fears-heartless-replacement-on-show/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/16/fractal-analytics-muted-ipo-debut-signals-persistent-ai-fears-in-india/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.lifeinsuranceinternational.com/news/generali-launches-core-tech/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theregister.com/2026/02/16/anthropic_claude_ai_edits/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.semafor.com/article/02/16/2026/nasa-trials-ai-powered-driving-of-mars-rover
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.technologyreview.com/2026/02/16/1132516/cesar-de-la-fuente-using-ai-antibiotics-hunt/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.inc.com/chris-morris/more-than-a-century-ago-thomas-edison-imagined-a-better-battery-now-scientists-are-making-it-real/91302807
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://fortune.com/2026/02/16/mel-robbins-feeling-stuck-doesnt-mean-youre-broken-biggest-mistake-people-over-40-make/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.zdnet.com/article/best-hosted-endpoint-security-software/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.euronews.com/next/2026/02/15/europe-seen-as-key-market-for-data-sovereignty-technology
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.reuters.com/world/china/alibaba-unveils-new-qwen35-model-agentic-ai-era-2026-02-16/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/how-i-built-fail-safe-legal-ai-engine-for-singapore-laws-using-triple-model-rag
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/the-hard-truth-about-machine-learning-for-amazon-fba-sellers
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/stop-guessing-thread-pool-sizes-how-to-plug-ai-into-spring-batch-safely
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/from-dsp-to-ai-evolving-approaches-in-audio-processing
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/prompts-are-overrated-heres-how-i-built-a-zero-copy-fog-ai-node-without-python
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/building-a-second-brain-for-marketing-using-ai-agents
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/how-cmos-win-cfo-buy-in-at-scale
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://hackernoon.com/decision-engines-in-production-json-logic-rules-engines-and-when-to-scale
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.france24.com/en/asia-pacific/20260216-india-hosts-ai-summit
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://thenextweb.com/news/peter-steinberger-joins-openai
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theverge.com/ai-artificial-intelligence/879644/bytedance-seedance-safeguards-ai-video-copyright-infringement
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.engadget.com/ai/bytedance-promises-to-tighten-up-its-new-ai-video-generator-after-viral-cruise-vs-pitt-clip-112941384.html
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://t.co/iwFZFYyeEB
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/16/all-the-important-news-from-the-ongoing-india-ai-summit/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.barrons.com/articles/stock-market-news-today-europe-asia-dollar-gold-9b06f698
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.tomsguide.com/ai/i-asked-chatgpt-for-a-grocery-trick-and-it-cut-my-food-bill-in-half
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/big-short-michael-burry-substack-investing-strategy-ai-bubble-stocks-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.businessinsider.com/how-to-invest-ai-volatility-top-stock-picks-to-buy-2026-2
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.cnet.com/tech/services-and-software/i-vibe-coded-an-app-with-3-popular-chatbots-the-real-winner-is-a-good-prompt/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://nypost.com/2026/02/16/business/california-ballot-measures-that-appear-aimed-at-openai-were-filed-by-stepbrother-of-employee-at-rival-anthropic/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.nytimes.com/2026/02/16/movies/tom-cruise-brad-pitt-artificial-intelligence-seedance.html
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/wall-street-analysts-target-price-074133595.html
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/16/goldman-sachs-ceo-david-solomon-says-the-tech-sell/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theregister.com/2026/02/16/starmer_social_media/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.bbc.com/news/articles/c93wq6xqgy1o
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/16/the-ai-stock-that-could-turn-the-tables-on-the-mag/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.techradar.com/pro/amazon-has-a-new-creative-agent-to-help-your-business-build-its-own-ads
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://gizmodo.com/former-npr-host-accuses-google-of-copying-his-voice-for-ai-offering-2000722402
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theguardian.com/technology/2026/feb/16/google-puts-users-at-risk-downplaying-disclaimers-ai-overviews
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.cagesideseats.com/wwe/418612/el-grande-americano-warns-original-over-ai-mexican-flag
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theverge.com/gadgets/877858/life-with-casio-moflin-robot-ai-pet
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://interestingengineering.com/ai-robotics/china-humanoid-robot-stunning-sword-dance
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://news.google.com/rss/articles/CBMigwFBVV95cUxNbXJZcHF1NUNBajR2OEZvbHVvQzVEQVc3b0x1U2dCakdmREVuREdtSnlHOHJ2a2lEUUViVVM5ZnFMXzAwUHFBSnVFSEZYcFNKT3JueXA2dEFBbzBTdVZmSHdoOGNhZDlibWJhM01zdC1hdWI0ZFhNeWZmWnp3cXpaQTBZUQ
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.verdict.co.uk/capgemini-2025-q4-results/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/big-tech-stocks-lose-billions-093834534.html
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.theguardian.com/commentisfree/2026/feb/15/the-guardian-view-on-ai-safety-staff-departures-raise-worries-about-industry-pursuing-profit-at-all-costs
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.retail-insight-network.com/news/spar-rolls-out-ai-loss-prevention-tech/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/16/should-you-forget-palantir-and-buy-2-other-artific/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/16/2-dividend-stocks-to-hold-for-the-next-20-years/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fastcompany.com/91492708/demand-for-ai-related-skills-is-up-109-since-last-year-what-that-means-for-you
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.benzinga.com/markets/tech/26/02/50636187/anthropic-ceo-dario-amodei-warns-one-wrong-ai-bet-could-bankrupt-the-company-no-hedge-on-earth-that-could-stop
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://fortune.com/2026/02/16/stephen-schwarzman-blackstone-ceo-48-billion-fortune-to-philanthropic-foundation-focused-on-ai/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/16/the-stock-market-is-doing-something-witnessed-only/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.rd.com/article/tested-productivity-app/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://www.theguardian.com/technology/2026/feb/15/ai-chatbots-children-risk-fines-uk-ban
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.404media.co/ars-technica-pulls-article-with-ai-fabricated-quotes-about-ai-generated-article/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://deadline.com/2026/02/the-simpsons-bart-voice-actress-ai-hopes-human-successor-1236725415/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found before cutoff - ignoring as duplicate https://fortune.com/2026/02/14/who-is-jake-paul-venture-capital-anti-fund-boxer-logan-paul/
08:07:30 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | found after cutoff - keeping https://www.engadget.com/ai/openai-has-hired-the-developer-behind-ai-agent-openclaw-092934041.html

================================================================================
⏱️  Total execution time: 299.86s
📊 Final result:
✅ Step 2 filter_urls completed successfully! Removed 504 duplicate URLs, classified 192 new articles, found 96 AI-related.

In [16]:
headline_df = pd.DataFrame(state.headline_data)
headline_df

,source,title,url,published,rss_summary,id,isAI
0,Ars Technica,"""It ain't no unicorn"": These researchers have ...",https://arstechnica.com/science/2026/02/it-ain...,NaN,NaN,8,False
1,Bloomberg,Goldman’s Snider Says Analysts Turn Positive o...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,29,False
2,Bloomberg,AMD Takes on Nvidia in India With Expanded Tat...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,30,True
3,Bloomberg,Anthropic Boosts India AI Push Via Flag Airlin...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,32,True
4,Bloomberg,Ray Wang on How AI Is Causing DRAM Prices to S...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,33,True
...,...,...,...,...,...,...,...
187,NewsAPI,‘Iron Sky’ Producers Prepping Communists-on-Ma...,http://www.hollywoodreporter.com/movies/movie-...,2026-02-15T09:30:00Z,NaN,691,False
188,NewsAPI,"Bill Gates to visit Amaravati tomorrow, meet C...",https://newsmeter.in/top-stories/bill-gates-to...,2026-02-15T09:28:39Z,NaN,692,True
189,NewsAPI,Maureen Dowd: The world is in peril. Don’t wor...,https://www.irishtimes.comhttps://www.nytimes....,2026-02-15T12:29:44Z,NaN,693,False
190,NewsAPI,A safety net in sickness and in health,https://www.thehindubusinessline.com/specials/...,2026-02-15T13:04:06Z,NaN,694,False
191,NewsAPI,Is This Quiet Ad-Tech Firm A Hidden Gem Or A L...,https://bizbrief.ie/news/marketing/is-this-qui...,2026-02-15T10:07:10Z,NaN,695,False

In [14]:
# User prompt to run workflow
# user_prompt = "Run step 3, download full articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("download_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:41:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting Step 3: Download Articles
08:41:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting concurrent scraping of 94 AI-related articles

▶ Starting Step 3: download_articles

08:41:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Launching browser for 94 URLs with 12 concurrent workers
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 1 of 94 https://www.business-standard.com/technology/tech-news/top-putin-aide-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi-126021500398_1.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Top_Putin_aide_to_lead_Russian_delegation_for_AI_Impact_Summit_in_New_Delhi.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.business-standard.com/technology/tech-news/top-putin-aide-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi-126021500398_1.html with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 2 of 94 https://www.businessinsider.com/microsoft-manager-explains-how-she-pivoted-from-admin-to-ai-2026-2
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/I_started_at_Microsoft_as_an_executive_assistant_and_pivoted_to_an_AI_role._I_don_t_regret_my_English_degree..html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.businessinsider.com/microsoft-manager-explains-how-she-pivoted-from-admin-to-ai-2026-2 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 3 of 94 https://economictimes.indiatimes.com/news/india/top-putin-aide-maxim-oreshkin-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi/articleshow/128381877.cms
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Top_Putin_aide_Maxim_Oreshkin_to_lead_Russian_delegation_for_AI_Impact_Summit_in_New_Delhi.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://economictimes.indiatimes.com/news/india/top-putin-aide-maxim-oreshkin-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi/articleshow/128381877.cms with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 4 of 94 https://www.businessinsider.com/trump-trade-advisor-peter-navarro-ai-internalize-data-center-costs-2026-2
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Trump_s_trade_advisor_says_Big_Tech_must__internalize_the_cost__of_AI_data_centers.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.businessinsider.com/trump-trade-advisor-peter-navarro-ai-internalize-data-center-costs-2026-2 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 5 of 94 https://www.404media.co/ars-technica-pulls-article-with-ai-fabricated-quotes-about-ai-generated-article/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Ars_Technica_Pulls_Article_With_AI_Fabricated_Quotes_About_AI_Generated_Article.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.404media.co/ars-technica-pulls-article-with-ai-fabricated-quotes-about-ai-generated-article/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 6 of 94 https://www.benzinga.com/markets/tech/26/02/50636187/anthropic-ceo-dario-amodei-warns-one-wrong-ai-bet-could-bankrupt-the-company-no-hedge-on-earth-that-could-stop
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Anthropic_CEO_Dario_Amodei_Warns_One_Wrong_AI_Bet_Could_Bankrupt_The_Company___No_Hedge_On_Earth_That_Could_Stop....html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.benzinga.com/markets/tech/26/02/50636187/anthropic-ceo-dario-amodei-warns-one-wrong-ai-bet-could-bankrupt-the-company-no-hedge-on-earth-that-could-stop with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 7 of 94 https://www.businessinsider.com/resignation-letters-quit-openai-anthropic-2026-2
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/The_art_of_the_squeal__What_we_can_learn_from_the_flood_of_AI_resignation_letters.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.businessinsider.com/resignation-letters-quit-openai-anthropic-2026-2 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 8 of 94 https://hackernoon.com/building-a-second-brain-for-marketing-using-ai-agents
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Building_a__Second_Brain__for_Marketing_Using_AI_Agents.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://hackernoon.com/building-a-second-brain-for-marketing-using-ai-agents with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 9 of 94 https://www.businessinsider.com/dario-amodei-anthropic-profit-pressure-versus-safety-mission-2026-2
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Dario_Amodei_says_Anthropic_struggles_to_balance__incredible_commercial_pressure__with_its__safety_stuff.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.businessinsider.com/dario-amodei-anthropic-profit-pressure-versus-safety-mission-2026-2 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 10 of 94 https://www.reddit.com/r/OpenAI/comments/1r5rnbl/sam_altman_officially_confirms_that_openai_has/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Sam_Altman_officially_confirms_that_OpenAI_has_acquired_OpenClaw__Peter_Steinberger_to_lead_personal_agents.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.reddit.com/r/OpenAI/comments/1r5rnbl/sam_altman_officially_confirms_that_openai_has/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 11 of 94 https://qwen.ai/blog?id=qwen3.5
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Qwen3.5__Towards_Native_Multimodal_Agents.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://qwen.ai/blog?id=qwen3.5 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 12 of 94 https://weandthecolor.com/real-design-trends-are-dying-under-the-weight-of-recursive-ai-echoes/208199
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Real_Design_Trends_are_Dying_Under_the_Weight_of_Recursive_AI_Echoes.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://weandthecolor.com/real-design-trends-are-dying-under-the-weight-of-recursive-ai-echoes/208199 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 13 of 94 https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Skipping ignored domain: www.bloomberg.com
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users with status: skipped
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 14 of 94 https://www.theregister.com/2026/02/16/anthropic_claude_ai_edits/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Anthropic_tries_to_hide_Claude_s_AI_actions._Devs_hate_it.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.theregister.com/2026/02/16/anthropic_claude_ai_edits/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 15 of 94 https://www.theguardian.com/technology/2026/feb/16/google-puts-users-at-risk-downplaying-disclaimers-ai-overviews
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Google_puts_users_at_risk_by_downplaying_health_disclaimers_under_AI_Overviews.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.theguardian.com/technology/2026/feb/16/google-puts-users-at-risk-downplaying-disclaimers-ai-overviews with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 16 of 94 https://www.ft.com/content/c30ded60-bece-45e0-981d-653e1e3e9818
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/KPMG_partner_fined_over_using_AI_to_pass_AI_test.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.ft.com/content/c30ded60-bece-45e0-981d-653e1e3e9818 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 17 of 94 https://www.bbc.com/news/articles/c93wq6xqgy1o
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/ByteDance_says_it__respects_IP_rights_and_we_have_heard_the_concerns_regarding_Seedance__and_it_plans_to__strengthen__safeguards__after_Disney_s_legal_threats__Osmond_Chia_BBC.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.bbc.com/news/articles/c93wq6xqgy1o with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 18 of 94 https://www.theverge.com/ai-artificial-intelligence/879644/bytedance-seedance-safeguards-ai-video-copyright-infringement
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/After_spooking_Hollywood__ByteDance_will_tweak_safeguards_on_new_AI_model.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.theverge.com/ai-artificial-intelligence/879644/bytedance-seedance-safeguards-ai-video-copyright-infringement with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 19 of 94 https://www.fool.com/investing/2026/02/16/1-unstoppable-stock-to-buy-before-it-joins-nvidia/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/1_Unstoppable_Stock_to_Buy_Before_It_Joins_Nvidia__Apple__and_Alphabet_in_the__3_Trillion_Club.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.fool.com/investing/2026/02/16/1-unstoppable-stock-to-buy-before-it-joins-nvidia/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 20 of 94 https://hackernoon.com/from-dsp-to-ai-evolving-approaches-in-audio-processing
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/From_DSP_to_AI__Evolving_Approaches_in_Audio_Processing.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://hackernoon.com/from-dsp-to-ai-evolving-approaches-in-audio-processing with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 21 of 94 https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Skipping ignored domain: www.bloomberg.com
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker with status: skipped
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 22 of 94 https://v.redd.it/rgrvl3kydqjg1
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/AI_was_supposed_to_be_used_to_cure_cancer_..html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://v.redd.it/rgrvl3kydqjg1 with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 23 of 94 https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Skipping ignored domain: www.bloomberg.com
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows with status: skipped
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 24 of 94 https://deadline.com/2026/02/the-simpsons-bart-voice-actress-ai-hopes-human-successor-1236725415/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/The_Simpsons__Bart_Voice_Actress_Tells_AI__Eat_My_Shorts___Wants_Human_Successor___AI_Has_No_Heart.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://deadline.com/2026/02/the-simpsons-bart-voice-actress-ai-hopes-human-successor-1236725415/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 25 of 94 https://hackernoon.com/the-hard-truth-about-machine-learning-for-amazon-fba-sellers
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/The_Hard_Truth_About_Machine_Learning_for_Amazon_FBA_Sellers.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://hackernoon.com/the-hard-truth-about-machine-learning-for-amazon-fba-sellers with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 26 of 94 https://www.fool.com/investing/2026/02/16/bill-ackman-buys-2-ai-stocks-soar-next-year/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Billionaire_Bill_Ackman_Buys_2_BrilliantArtificial_Intelligence_AI__Stocks_--_They_Could_Soar_in_the_Next_Year__According_to_Wall_Street.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.fool.com/investing/2026/02/16/bill-ackman-buys-2-ai-stocks-soar-next-year/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 27 of 94 https://blog.exe.dev/expensively-quadratic
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Expensively_Quadratic__The_LLM_Agent_Cost_Curve.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://blog.exe.dev/expensively-quadratic with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 28 of 94 https://www.engadget.com/ai/openai-has-hired-the-developer-behind-ai-agent-openclaw-092934041.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/OpenAI_has_hired_the_developer_behind_AI_agent_OpenClaw.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.engadget.com/ai/openai-has-hired-the-developer-behind-ai-agent-openclaw-092934041.html with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 29 of 94 https://www.news18.com/business/economy/openai-ceo-sam-altman-signals-deeper-india-ties-ahead-of-global-ai-impact-summit-2026-ws-l-9904937.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/OpenAI_CEO_Sam_Altman_Signals_Deeper_India_Ties_Ahead_Of_Global_AI_Impact_Summit_2026.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.news18.com/business/economy/openai-ceo-sam-altman-signals-deeper-india-ties-ahead-of-global-ai-impact-summit-2026-ws-l-9904937.html with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 30 of 94 https://www.engadget.com/ai/bytedance-promises-to-tighten-up-its-new-ai-video-generator-after-viral-cruise-vs-pitt-clip-112941384.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/ByteDance_promises_to_tighten_up_its_new_AI_video_generator_after_viral_Cruise_vs._Pitt_clip.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.engadget.com/ai/bytedance-promises-to-tighten-up-its-new-ai-video-generator-after-viral-cruise-vs-pitt-clip-112941384.html with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 31 of 94 https://www.reddit.com/r/ChatGPT/comments/1r5snvl/indirect_prompt_injection_in_ai_agents_is/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Indirect_prompt_injection_in_AI_agents_is_terrifying_and_I_don_t_think_enough_people_understand_this.html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 completed https://www.reddit.com/r/ChatGPT/comments/1r5snvl/indirect_prompt_injection_in_ai_agents_is/ with status: exists
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 0 fetching 32 of 94 https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | scrape_url(https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project)
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | scraping https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project to download/html
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Downloading https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Worker 1 fetching 33 of 94 https://www.forbes.com/sites/lanceeliot/2026/02/16/forcing-ai-makers-to-legally-carve-out-mental-health-capabilities-and-use-llm-therapist-apps-instead/
08:41:39 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | File already exists: download/html/Forcing_AI_Makers_To_Legally_Carve_Out_Mental_Health_Capabilities_And_Use_LLM_Therapist_Apps_Instead.html

Starting with 94 rows...
Processing 94 files...
Reading and truncating files to 8192 tokens using text-embedding-3-large tokenizer...
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Getting embeddings for 85 texts...
Creating indexed similarity matrix...
Finding pairs with similarity > 0.925...
Filtering dataframe...
Removing 0 rows due to high similarity
Final dataframe has 94 rows (removed 0 rows)
Missing files:

,title,status,final_url
85,Ray Wang on How AI Is Causing DRAM Prices to Surge,skipped,https://www.bloomberg.com/news/articles/2026-02-16/ai-is-causing-the-price-of-computer-memory-to-surge
86,Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release,skipped,https://www.bloomberg.com/news/articles/2026-02-16/alibaba-unveils-major-ai-model-upgrade-ahead-of-deepseek-release
87,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",skipped,https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker
88,MiniMax Shares Surge 25% as Optimism Over Chinese AI Firms Grows,skipped,https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows
89,"OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project",403,https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
90,"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts",skipped,https://www.bloomberg.com/news/articles/2026-02-16/anthropic-boosts-india-ai-push-via-flag-airline-cognizant-pacts
91,"OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary/Bloomberg)",skipped,https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users
92,Why the ‘AI scare trade’ might not be done,skipped,https://www.cnn.com/2026/02/16/business/ai-disruption-fears-us-stocks
93,AMD Takes on Nvidia in India With Expanded Tata AI Partnership,skipped,https://www.bloomberg.com/news/articles/2026-02-16/amd-takes-on-nvidia-in-india-with-expanded-tata-ai-partnership

08:41:48 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed Step 3: Downloaded 85 articles

✅ Completed Step 3: Downloaded 85 AI-related articles
================================================================================
⏱️  Total execution time: 10.25s
📊 Final result:
✅ Step 3 download_articles completed successfully! Total articles: 94; AI-related articles: 94; HTML files: 85; Text files: 85

In [17]:
headline_df = state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df[['id', 'source', 'title', 'status', 'final_url']].loc[headline_df["html_path"]==""])

,id,source,title,status,final_url
85,33,Bloomberg,Ray Wang on How AI Is Causing DRAM Prices to Surge,skipped,https://www.bloomberg.com/news/articles/2026-02-16/ai-is-causing-the-price-of-computer-memory-to-surge
86,35,Bloomberg,Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release,skipped,https://www.bloomberg.com/news/articles/2026-02-16/alibaba-unveils-major-ai-model-upgrade-ahead-of-deepseek-release
87,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",skipped,https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker
88,50,Bloomberg,MiniMax Shares Surge 25% as Optimism Over Chinese AI Firms Grows,skipped,https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows
89,379,Techmeme,"OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project",403,https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
90,32,Bloomberg,"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts",skipped,https://www.bloomberg.com/news/articles/2026-02-16/anthropic-boosts-india-ai-push-via-flag-airline-cognizant-pacts
91,153,Feedly AI,"OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary/Bloomberg)",skipped,https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users
92,121,Feedly AI,Why the ‘AI scare trade’ might not be done,skipped,https://www.cnn.com/2026/02/16/business/ai-disruption-fears-us-stocks
93,30,Bloomberg,AMD Takes on Nvidia in India With Expanded Tata AI Partnership,skipped,https://www.bloomberg.com/news/articles/2026-02-16/amd-takes-on-nvidia-in-india-with-expanded-tata-ai-partnership

In [18]:
hdf = pd.DataFrame(state.headline_data)
hdf

,source,title,url,published,rss_summary,id,isAI,text_path,content_length,domain,site_name,reputation,status,final_url,html_path,last_updated
0,Feedly AI,NASA trials AI-powered driving of Mars rover,https://www.semafor.com/article/02/16/2026/nas...,NaN,NaN,127,True,download/text/NASA_trials_AI-powered_driving_o...,28513,semafor.com,Semafor,1.0,exists,https://www.semafor.com/article/02/16/2026/nas...,download/html/NASA_trials_AI-powered_driving_o...,None
1,Hacker News,Qwen3.5: Towards Native Multimodal Agents,https://qwen.ai/blog?id=qwen3.5,"Mon, 16 Feb 2026 09:32:21 +0000","<a href=""https://news.ycombinator.com/item?id=...",221,True,download/text/Qwen3.5__Towards_Native_Multimod...,26506,qwen.ai,Qwen,0.0,exists,https://qwen.ai/blog?id=qwen3.5,download/html/Qwen3.5__Towards_Native_Multimod...,None
2,NewsAPI,Real Design Trends are Dying Under the Weight ...,https://weandthecolor.com/real-design-trends-a...,2026-02-15T10:33:31Z,NaN,687,True,download/text/Real_Design_Trends_are_Dying_Und...,24475,weandthecolor.com,We And The Color,0.0,exists,https://weandthecolor.com/real-design-trends-a...,download/html/Real_Design_Trends_are_Dying_Und...,None
3,Feedly AI,Forcing AI Makers To Legally Carve Out Mental ...,https://www.forbes.com/sites/lanceeliot/2026/0...,NaN,NaN,200,True,download/text/Forcing_AI_Makers_To_Legally_Car...,19446,forbes.com,Forbes,1.0,exists,https://www.forbes.com/sites/lanceeliot/2026/0...,download/html/Forcing_AI_Makers_To_Legally_Car...,None
4,NewsAPI,Why are experts sounding the alarm on AI risks?,https://www.aljazeera.com/news/2026/2/15/why-a...,2026-02-15T11:24:02Z,NaN,662,True,download/text/Why_are_experts_sounding_the_ala...,15660,aljazeera.com,Al Jazeera,0.0,exists,https://www.aljazeera.com/news/2026/2/15/why-a...,download/html/Why_are_experts_sounding_the_ala...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,Techmeme,OpenAI in Advanced Talks to Hire OpenClaw Foun...,https://www.theinformation.com/articles/openai...,NaN,NaN,379,True,,0,theinformation.com,The Information,2.0,403,https://www.theinformation.com/articles/openai...,,None
90,Bloomberg,Anthropic Boosts India AI Push Via Flag Airlin...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,32,True,,0,bloomberg.com,Bloomberg,5.0,skipped,https://www.bloomberg.com/news/articles/2026-0...,,None
91,Feedly AI,"OpenAI retired GPT-4o on February 13, angering...",https://www.bloomberg.com/news/newsletters/202...,NaN,NaN,153,True,,0,bloomberg.com,Bloomberg,5.0,skipped,https://www.bloomberg.com/news/newsletters/202...,,None
92,Feedly AI,Why the ‘AI scare trade’ might not be done,https://www.cnn.com/2026/02/16/business/ai-dis...,NaN,NaN,121,True,,0,cnn.com,CNN,1.0,skipped,https://www.cnn.com/2026/02/16/business/ai-dis...,,None
93,Bloomberg,AMD Takes on Nvidia in India With Expanded Tat...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,30,True,,0,bloomberg.com,Bloomberg,5.0,skipped,https://www.bloomberg.com/news/articles/2026-0...,,None

In [19]:
hdf.loc[hdf["title"].str.startswith("The scientist")]

,source,title,url,published,rss_summary,id,isAI,text_path,content_length,domain,site_name,reputation,status,final_url,html_path,last_updated
12,Feedly AI,The scientist using AI to hunt for antibiotics...,https://www.technologyreview.com/2026/02/16/11...,NaN,NaN,128,True,download/text/The_scientist_using_AI_to_hunt_f...,10538,technologyreview.com,Technology Review,2.0,exists,https://www.technologyreview.com/2026/02/16/11...,download/html/The_scientist_using_AI_to_hunt_f...,None

In [20]:
# User prompt to run workflow
# user_prompt = "Run step 4, Summarize articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("extract_summaries")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 AI articles for summarization
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using model 'gemini-3-flash-preview' for summarization
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=ArticleSummaryList, reasoning_effort=medium
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting summarization for 94 articles
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 94 chunks (chunk_size=1, model=gemini-3-flash-preview, concurrency=1000)
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Summarize the article below:

[
  {
    "id":127,

▶ Starting Step 4: extract_summaries

08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Summarize the article below:

[
  {
    "id":149,
    "text_content":"Page title: I asked ChatGPT for a grocery trick \u2014 and it cut my food bill in half | Tom's Guide\nSocial card title: I asked ChatGPT for a grocery trick \u2014 and it cut my food bill in half\nSocial card description: I'm saving money, but also adding more variety to our weekly meals\nI asked ChatGPT for a grocery trick \u2014 and it cut my food bill in half\nI'm saving money, but also adding more variety to our weekly meals\nHere at Tom\u2019s Guide our expert editors are committed to bringing you the best news, reviews and guides to help you stay informed and ahead of the curve!\nYou are now subscribed\nYour newsletter sign-up was successful\nWant to add more newsletters?\nDaily (Mon-Sun)\nTom's Guide Daily\nSign up to get the latest updates on all of your favorite content! From cutting-edge tech news and the hottest streaming buzz to unbeatable deals on the best products and in-depth reviews, we\u2019ve got you covered.\nWeekly on Thursday\nTom's AI Guide\nBe AI savvy with your weekly newsletter summing up all the biggest AI news you need to know. Plus, analysis from our AI editor and tips on how to use the latest AI tools!\nWeekly on Friday\nTom's iGuide\nUnlock the vast world of Apple news straight to your inbox. With coverage on everything from exciting product launches to essential software updates, this is your go-to source for the latest updates on all the best Apple content.\nWeekly on Monday\nTom's Streaming Guide\nOur weekly newsletter is expertly crafted to immerse you in the world of streaming. Stay updated on the latest releases and our top recommendations across your favorite streaming platforms.\nJoin the club\nGet full access to premium articles, exclusive features and a growing list of member rewards.\nShopping for my family of five means I go to Costco, our neighborhood grocery store and either Target or Walmart every week. I spend a ridiculous amount of money each month feeding my family basic meals. So, when I decided to lean on a chatbot that I typically use for research and brainstorming, I didn\u2019t expect it to beat my shopping apps, grocery budget spreadsheet and years of \u201cmeal planning instincts\u201d \u2014 but that\u2019s exactly what happened.\nLike most families, my grocery bill had quietly ballooned. Between inflation, impulse buys and \u201cwe might need this,\u201d I was regularly spending $300-$500 a week. I\u2019d tried coupons, bulk shopping and rotating meal plans, but nothing really worked for saving big.\nSo I did what I do for everything now: I asked AI. I opened up the ChatGPT app and used the prompt: \u201cGive me one grocery trick that could actually lower my bill.\u201d The answer surprised me \u2014 and in a month, it cut my food bill in half.\nWhat I asked ChatGPT\nFor the record, ChatGPT didn\u2019t tell me to buy generic brands or how to be one of those super couponers that I see on TLC. It also didn\u2019t lecture me for splurging occasionally on toys, sports equipment or clothes for my kids. Instead, it suggested something deceptively simple:\nShop your fridge first \u2014 and plan meals around what you already have.\nNot \u201cclean out your fridge.\u201d Not \u201ceat leftovers.\u201d But a very specific process.\nHere\u2019s exactly what ChatGPT told me to do:\n- Before you shop, take 3 photos: Fridge, freezer, pantry\n- Send them to ChatGPT and ask: \u201cMake me 5 meals using what I already have.\u201d\n- Only buy what you need to complete those meals.\nThat\u2019s it. No apps or coupons to clip. I didn't have to do any extra coupon clipping. Just my camera and ChatGPT.\nWhat happened when I tried it\nI opened my fridge and immediately realized something embarrassing: I already had so much food. I had half a bag of spinach that was wilting by the minute, chicken breasts in the freezer, pasta, canned tomatoes and beans in the pantry.\nI had a lot of random odds and ends that never made it into a meal, so I snapped photos and sent them to ChatGPT.\nWithin seconds, it suggested delicious-sounding meals like:\n- Chicken and veggie pasta\n- Spinach and feta omelets\n- Chicken tacos using pantry spices\n- Bean and tomato soup\n- Stir-fry using frozen vegetables\nSuddenly, I didn\u2019t need a \u201cbig grocery haul.\u201d I just needed a few filler items \u2014 maybe $40 worth \u2014 instead of my usual $200. It even gave me the recipes for each of the suggestions.\nWhy this actually works\nThere's one thing that surprised me probably even more than saving real money. Working with ChatGPT on groceries changed my mindset. Before this experiment, I mostly bought the same groceries to make the same meals each week. But by using up what we have before shopping for more, it made me discover new meals and added a variety \u2014 something my weeknight meals had been lacking lately.\nAfter the experiment, I was more aware of food before it went bad, avoided overbuying \"just in case\" and stopped making duplicate purchases. And for me, that's where the real savings came from.\nMy results\n- Before ChatGPT: ~$350\u2013$400 per week\n- After using this trick: ~$200\u2013$250 per week\nInterestingly enough, the more I use this method, the smarter my shopping got. I started buying versatile ingredients instead of random extras and thinking in \"meal components\" instead of individual dishes. Another shift from this experiment is that my freezer became far more organized because I had to know what I had before I shopped for more.\nChatGPT became a legit kitchen assistant.\nBottom line\nThis tip is extremely simple and something that has crossed my mind, but not to this extent. The vibe was more, \"I should cook something with that before it expires.\" Now, I actually do use what I have because ChatGPT helped me devise a plan with intent.\nI didn\u2019t expect a single AI prompt to change how I grocery shop \u2014 but this one did. If you\u2019re tired of overspending, wasting food or staring blankly at your fridge, this might be the simplest, most practical AI hack you can try today.\nFollow Tom's Guide on Google News and add us as a preferred source to get our up-to-date news, analysis, and reviews in your feeds.\nMore from Tom's Guide\nAmanda Caswell is an award-winning journalist, bestselling YA author, and one of today\u2019s leading voices in AI and technology. A celebrated contributor to various news outlets, her sharp insights and relatable storytelling have earned her a loyal readership. Amanda\u2019s work has been recognized with prestigious honors, including outstanding contribution to media.\nKnown for her ability to bring clarity to even the most complex topics, Amanda seamlessly blends innovation and creativity, inspiring readers to embrace the power of AI and emerging technologies. As a certified prompt engineer, she continues to push the boundaries of how humans and AI can work together.\nBeyond her journalism career, Amanda is a long-distance runner and mom of three. She lives in New Jersey.\nJoin the Conversation\nPlease follow our community guidelines.\nAll Comments\nYou must confirm your public display name before commenting\nPlease logout and then login again, you will then be prompted to enter your display name."
  }
]
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Summarize the article below:

[
  {
    "id":139,
    "text_content":"Page title: Building a \u2018Second Brain\u2019 for Marketing Using AI Agents | HackerNoon\nSocial card title: Building a \u2018Second Brain\u2019 for Marketing Using AI Agents | HackerNoon\nSocial card description: Modern marketing faces a subtle but significant challenge. Not a lack of tools. Not a lack of ideas. But a lack of memory.\nModern marketing faces a subtle but significant challenge.\nNot a lack of tools. Not a lack of ideas. But a lack of memory.\nCampaigns are launched, data is collected, and insights are discussed, but are often forgotten. Teams move on, repeat mistakes, and relearn lessons that have already been addressed.\nThis is where the concept of a second brain becomes valuable.\nIt serves not as a productivity gimmick, but as a fundamental improvement to marketing decision-making.\nWith AI agents, this concept is now practical.\nIt is operational.\nThe Cognitive Bottleneck in Marketing\nMost marketing teams depend on human memory more than they recognize.\n- Why did that campaign work?\n- Which audience responded best last quarter?\n- What messaging failed before, and why?\nThe answers usually live:\n- In Slack threads\n- In forgotten dashboards\n- In one person\u2019s head\nAs teams grow or experience turnover, this context is often lost.\nThe result is predictable:\n- Repeated experiments\n- Inconsistent decisions\n- Fragmented strategy\nMarketing does not fail due to poor execution.\nIt fails because of aloss of institutional memory.\nWhat a \u201cSecond Brain\u201d Actually Means in Marketing\nA second brain is more than a note-taking application.\nIn marketing, a second brain is a living system that:\n- Observes activity\n- Stores insights\n- Connects patterns\n- Feeds decisions\nIt does not replace marketers.\nIt enhances professional judgment.\nThink of it as:\n- A strategist who never forgets\n- An analyst who never sleeps\n- A historian who sees patterns across time\nAI agents make this possible because they can operate continuously, rather than only when prompted.\nWhy AI Agents (Not Just AI Tools)\nMost teams already use AI tools.\nThey generate:\n- Copy\n- Images\n- Ad variations\nWhile helpful, this approach remains superficial.\nAI agents offer a distinct advantage.\nAn agent:\n- Has a role\n- Has context\n- Has memory\n- Acts repeatedly toward an objective\nInstead of requesting, \u201cWrite me ad copy,\u201d\nYou design an agent whose job is,\u201cObserve what messaging works and update our positioning over time.\u201d\nThis shift is essential.\nThe Core Components of a Marketing Second Brain\nA functional second brain does not need to be complex; it must be well-structured.\nAt a minimum, it has four layers.\n1. Input Layer: What the System Observes\nThis includes:\n- Campaign performance data\n- Customer feedback\n- Sales conversations\n- Content engagement\n- Market signals\nAn AI agent continuously monitors these inputs.\nThe goal is not simply to report metrics, but to capture meaningful insights.\nFor example:\n- Which objections keep recurring?\n- Which messages consistently underperform?\n- Which channels are decaying over time?\n2. Memory Layer: What the System Retains\nMost marketing data is stored but not retained in a meaningful way.\nA second brain stores insights as patterns, not raw numbers.\nExamples:\n- \u201cShort-form video works better for first-touch awareness, not conversions.\u201d\n- \u201cDiscount-led messaging spikes traffic but lowers retention.\u201d\n- \u201cThis audience responds to clarity, not cleverness.\u201d\nThese insights are tagged, timestamped, and retrievable.\nMemory is only valuable if it can be recalled at the appropriate time.\n3. Reasoning Layer: What the System Connects\nThis is where AI agents shine.\nThey don\u2019t just log outcomes.\nThey look forrelationships.\n- When did performance change\u2014and what else changed at the same time?\n- Which messages work for which segments?\n- What patterns repeat across channels?\nOver time, the agent forms heuristics:\n\u201cWhen X happens, Y usually follows.\u201d\nThis is a strategy, not mere automation.\n4. Action Layer: What the System Feeds Back\nA second brain does more than observe.\nIt intervenes.\nExamples:\n- Suggests messaging adjustments before a campaign launch\n- Flags repeated mistakes\n- Recommends reallocating effort based on historical patterns\nRestraint is essential.\nThe system does not make decisions.\nItinforms.Humans still choose.\nThey make decisions with improved context.\nWhat This Looks Like in Practice\nImagine preparing a new campaign.\nInstead of starting from scratch, you query your second brain:\n- \u201cWhat positioning worked best for this audience before?\u201d\n- \u201cWhat objections caused drop-offs last time?\u201d\n- \u201cWhich channels underperformed for similar launches?\u201d\nThe agent responds with:\n- Summarized insights\n- Historical examples\n- Risks to watch for\nYou are no longer relying on guesswork.\nYou arebuilding on accumulated insight. This is the power of compounding insight.\nWhy This Beats Dashboards\nDashboards show what happened.\nSecond brains explain why it happened, and what to do next.\nDashboards are passive.\nAgents are active.\nDashboards require interpretation.\nAgents reduce cognitive load.\nMost importantly, dashboards reset with each new campaign.\nSecond brainsremember across time.\nCommon Mistakes When Building This\nTeams often fail by overcomplicating the process.\nSome pitfalls:\n- Trying to automate decisions instead of learning\n- Feeding agents raw data without context\n- Treating AI as a replacement for strategy\nThe goal is not complete autonomy.\nIt iscontinuity.\nA second brain exists to preserve learning, not to pursue perfection.\nWhy This Matters More in the AI Era\nAs AI accelerates execution, mistakes can also scale more rapidly.\nIf your system does not learn, failures will occur more quickly.\nA second brain introduces necessary friction at critical points:\n- Before repeating mistakes\n- Before scaling noise\n- Before copying trends blindly\nIn an environment where execution is accessible to all, the speed of learning becomes a key advantage.\nThe Real Payoff: Compounding Insight\nThe greatest benefit is not productivity.\nIt is the accumulation of insight.\nEvery campaign:\n- Improves the system\n- Sharpens judgment\n- Reduces waste\nOver time, decisions get easier. Confidence increases. Strategy stabilizes.\nThis is not automation.\nThis is intelligence.\nFinal Thought\nMost marketing teams do not need additional ideas.\nThey need improved organizational memory.\nAI agents make it possible to build a second brain that:\n- Learns continuously\n- Remembers context\n- Improves decisions over time\nThis is achieved not by replacing marketers, but by ensuring their best thinking is always retained.\nProof of Usefulness\nProof of Usefulness Hackathon is a global 6-month developer challenge designed to reward real-world utility projects and initiatives. With 150,000+ in cash prizes and software credits for winners and $1500+ worth of software and inventory for participants, this is undisputedly the biggest contest of the year. Learn more"
  }
]
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
08:46:29 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Summarize the article below:

[
  {
    "id":136,

✅ Completed Step 4: Generated AI summaries for 94/94 articles
================================================================================
⏱️  Total execution time: 99.49s
📊 Final result:
✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 94/94 articles.
💾 Summaries stored in headline DataFrame.

In [21]:
# if we get a refusal, examine why and delete any bad rows, e.g. blog posts about black hat hacking
bad_stuff =["Anthropic's Jack Cla",
           ]
print([len(s) for s in bad_stuff])
headline_df = state.headline_df
headline_df.loc[(headline_df["title"].str[:20].isin(bad_stuff))]

[20]

Empty DataFrame
Columns: [source, title, url, published, rss_summary, id, isAI, text_path, content_length, domain, site_name, reputation, status, final_url, html_path, last_updated, summary, description, tags, short_summary]
Index: []

In [22]:
# remove bad stuff
state.headline_df_to_dict(headline_df.loc[~headline_df["title"].str[:20].isin(bad_stuff)])

In [23]:
# User prompt to run workflow
# user_prompt = "Run step 5, Rate articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("rate_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Rating 94 AI articles using fn_rate_articles
08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Calculating article ratings for 94 articles
08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Rating recency
08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Rating quality, topic relevance, and importance concurrently
08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LangfuseClient (local prompt loader)
08:48:40 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 probability requests (model=gpt-4.1, concurrency=12)
08:48:41 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 probability requests (model=gpt-4.1, concurrency=12)

▶ Starting Step 5: rate_articles

08:48:41 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 probability requests (model=gpt-4.1, concurrency=12)
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed 94 probability requests
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed 94 probability requests
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Completed 94 probability requests
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | low quality: {0.0: 75, 1.0: 6, 0.3486451328151311: 1, 2.6810038677818034e-14: 1, 0.2689414052760013: 1, 0.9706877045032167: 1, 3.068246448279046e-13: 1, 6.144171336422507e-06: 1, 1.1896882546451464e-14: 1, 7.433680672352188e-12: 1, 0.9999984951481292: 1, 0.9999150561916036: 1, 0.9999909853565219: 1, 1.186112015134383e-08: 1, 0.999999448776502: 1}
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | on topic: {1.0: 70, 0.014063626520379485: 2, 1.026187963170189e-10: 1, 0.9999993295729128: 1, 0.9999998063873693: 1, 0.9999851444466235: 1, 0.9770226167277287: 1, 0.9999545100305701: 1, 0.9859363206911979: 1, 0.2227001469810028: 1, 0.0003353500342255387: 1, 4.539785156619626e-05: 1, 0.2689414052760013: 1, 0.3208212708736474: 1, 1.147876852587815e-05: 1, 0.8175744308728488: 1, 0.9820137760522224: 1, 0.9992903233093213: 1, 6.47594599989589e-07: 1, 1.3007123989067183e-05: 1, 0.9988304590053244: 1, 0.0: 1, 0.999088951739003: 1, 3.1608814543136926e-10: 1}
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | important: {1.0: 48, 0.0: 7, 0.5621765025686553: 3, 0.9999998063873693: 3, 0.9994471201618464: 1, 0.9971990580965346: 1, 0.9999992103693378: 1, 0.9999598739643123: 1, 0.029312225847906822: 1, 0.377540667992942: 1, 7.734421907141565e-08: 1, 0.999996587894339: 1, 2.902312105056987e-06: 1, 0.008577484930474293: 1, 7.484619074298232e-05: 1, 0.9999996871837232: 1, 0.6224593113235651: 1, 1.006039279283317e-12: 1, 0.9046504317639803: 1, 4.959358486191753e-15: 1, 0.49999999904767284: 1, 1.8795288165390832e-12: 1, 0.999980972389532: 1, 0.017986211314027313: 1, 3.331544542166412e-11: 1, 1.1399918530443554e-12: 1, 0.9840936132099872: 1, 6.023573837886479e-08: 1, 0.001501181950907551: 1, 0.9399132588278407: 1, 1.463778514125909e-12: 1, 9.545034922840628e-12: 1, 4.0063692636795675e-05: 1, 1.8925145442106525e-05: 1, 1.0603575991523846e-13: 1, 0.047425874568977164: 1, 0.9465965742432338: 1}
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | articles after rating: 94
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running Bradley-Terry rating with Swiss pairing
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Max 8 rounds
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Convergence threshold: 1
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Min rounds: 4
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 1 of max 8
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 94 ; Total stories: 94
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:48:47 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 231
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
0,0,The New York Times,Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood,24.093199,1.489059
11,11,Business Insider,"The career rise of OpenAI's billionaire CEO, Sam Altman",24.093199,1.489059
30,30,Engadget,OpenAI has hired the developer behind AI agent OpenClaw,24.093199,1.489059
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,24.093199,1.489059
40,40,The Guardian,Google puts users at risk by downplaying health disclaimers under AI Overviews,24.093199,1.489059
...,...,...,...,...,...
10,10,Bloomberg,"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts",-24.093199,-1.489059
42,42,404 Media,Ars Technica Pulls Article With AI Fabricated Quotes About AI Generated Article,-24.093199,-1.489059
14,14,Bloomberg,Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release,-24.093199,-1.489059
71,71,The Motley Fool,Should You Forget Palantir and Buy 2 OtherArtificial Intelligence(AI) Stocks Right Now?,-24.093199,-1.489059
55,55,We And The Color,Real Design Trends are Dying Under the Weight of Recursive AI Echoes,-24.093199,-1.489059

08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 1/8:
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 2988.0 (avg rank chg 31.79)
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 2 of max 8
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 94 ; Total stories: 94
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:48:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 462
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,84.317769,2.120954
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",75.630030,1.902420
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",72.863776,1.832837
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',67.582427,1.699988
11,11,Business Insider,"The career rise of OpenAI's billionaire CEO, Sam Altman",66.540645,1.673783
...,...,...,...,...,...
65,65,Business Insider,I started at Microsoft as an executive assistant and pivoted to an AI role. I don't regret my English degree.,-73.099267,-1.838761
10,10,Bloomberg,"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts",-74.352546,-1.870286
93,93,CNN,Why the ‘AI scare trade’ might not be done,-81.081393,-2.039545
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-83.055719,-2.089208
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-89.707281,-2.256524

08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 2/8:
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 1060.0 (avg rank chg 11.28)
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 3 of max 8
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 94 ; Total stories: 94
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:48:51 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:48:52 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 693
08:48:52 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,149.175505,2.116604
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",141.057431,2.001419
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",133.605308,1.895683
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',125.838724,1.785486
27,27,TechCrunch,All the important news from the ongoing India AI Impact Summit,119.016402,1.688686
...,...,...,...,...,...
86,86,Barron's,European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day,-128.138370,-1.818115
10,10,Bloomberg,"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts",-134.911710,-1.914219
93,93,CNN,Why the ‘AI scare trade’ might not be done,-142.647558,-2.023981
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-142.647558,-2.023981
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-151.443084,-2.148778

08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 3/8:
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 362.0 (avg rank chg 3.85)
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 4 of max 8
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 94 ; Total stories: 94
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:48:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 924
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,115.220495,1.599848
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",105.076718,1.459001
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",104.832031,1.455603
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,104.440483,1.450166
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',103.452427,1.436447
...,...,...,...,...,...
65,65,Business Insider,I started at Microsoft as an executive assistant and pivoted to an AI role. I don't regret my English degree.,-101.045108,-1.403021
86,86,Barron's,European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day,-101.929542,-1.415302
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-110.242945,-1.530734
93,93,CNN,Why the ‘AI scare trade’ might not be done,-110.935864,-1.540355
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-119.678987,-1.661755

08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 4/8:
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 236.0 (avg rank chg 2.51)
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 5 of max 8
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 15 battle batches
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 88 ; Total stories: 94
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 15 pre-formed batches
08:48:55 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 15 battles with concurrency = 1000
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 1140
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,113.120556,1.629896
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",102.763819,1.480671
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",102.455436,1.476228
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,102.205106,1.472621
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',100.927442,1.454212
...,...,...,...,...,...
91,91,Cageside Seats,El Grande Americano calls out ‘Original’ Americano over use of AI,-92.671347,-1.335254
86,86,Barron's,European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day,-92.790924,-1.336977
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-101.344903,-1.460227
93,93,CNN,Why the ‘AI scare trade’ might not be done,-102.037909,-1.470212
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-110.857483,-1.597289

08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 5/8:
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 158.0 (avg rank chg 1.68)
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | last_two: 2.10, prev_two: 7.56
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 6 of max 8
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 15 battle batches
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 90 ; Total stories: 94
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 15 pre-formed batches
08:48:57 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 15 battles with concurrency = 1000
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 1365
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,53.022672,1.823808
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",41.842896,1.439260
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,41.288945,1.420206
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",41.191117,1.416841
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',39.406402,1.355453
...,...,...,...,...,...
86,86,Barron's,European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day,-40.877564,-1.406056
91,91,Cageside Seats,El Grande Americano calls out ‘Original’ Americano over use of AI,-41.742517,-1.435807
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-50.353517,-1.731998
93,93,CNN,Why the ‘AI scare trade’ might not be done,-51.046634,-1.755839
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-60.472210,-2.080048

08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 6/8:
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 126.0 (avg rank chg 1.34)
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | last_two: 1.51, prev_two: 3.18
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 7 of max 8
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 92 ; Total stories: 94
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:49:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 1591
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,44.723741,2.166121
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",33.266935,1.611229
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",32.599508,1.578903
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,31.881642,1.544135
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',30.782494,1.490899
...,...,...,...,...,...
92,92,Times of India,"She earns Rs 2 crore yearly, but OpenAI employee won't say YES to marriage without this non-negotiable rule",-28.721118,-1.391060
91,91,Cageside Seats,El Grande Americano calls out ‘Original’ Americano over use of AI,-30.416407,-1.473168
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-30.425614,-1.473614
93,93,CNN,Why the ‘AI scare trade’ might not be done,-31.156588,-1.509018
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-31.443654,-1.522921

08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 7/8:
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 112.0 (avg rank chg 1.19)
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | last_two: 1.27, prev_two: 2.10
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Running round 8 of max 8
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ---------------------------------------------------
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generated 16 battle batches
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total stories in batches: 92 ; Total stories: 94
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 pre-formed batches
08:49:04 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 16 battles with concurrency = 1000
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | total battles: 1817
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputing Bradley-Terry ratings
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Recomputed Bradley-Terry ratings
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
53,53,Qwen,Qwen3.5: Towards Native Multimodal Agents,38.641701,2.828192
25,25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",26.958498,1.973097
76,76,Twitter,"Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)",26.030408,1.905170
23,23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,25.551650,1.870129
70,70,Benzinga,Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...',24.056158,1.760674
...,...,...,...,...,...
92,92,Times of India,"She earns Rs 2 crore yearly, but OpenAI employee won't say YES to marriage without this non-negotiable rule",-16.793859,-1.229145
91,91,Cageside Seats,El Grande Americano calls out ‘Original’ Americano over use of AI,-18.238001,-1.334842
35,35,Financial Times,Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?,-19.392080,-1.419309
93,93,CNN,Why the ‘AI scare trade’ might not be done,-19.844462,-1.452419
36,36,Bloomberg,"Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker",-20.000862,-1.463866

08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | After round 8/8:
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sum of absolute ranking changes: 82.0 (avg rank chg 0.87)
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | last_two: 1.03, prev_two: 1.51
08:49:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Low rated articles: 0

✅ Completed Step 5: Rated 94 articles

08:49:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sent email with 94 rated articles

================================================================================
⏱️  Total execution time: 26.63s
📊 Final result:
✅ Step 5 rate_articles completed successfully! Rated 94 articles with average rating 5.8/10.
⭐ High quality articles (≥7.0): 29
💾 Ratings stored in persistent state.

In [24]:
headline_df=state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df.sort_values("rating", ascending=False)[['site_name', 'title', 'rating', 'short_summary']])

,site_name,title,rating,short_summary
0,The New York Times,Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood,10.460049,"ByteDance's Seedance 2.0 AI tool produced a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, prompting Disney and the Motion Picture Association to allege copyright infringement and demand the company cease operations."
53,Qwen,Qwen3.5: Towards Native Multimodal Agents,9.915625,"Alibaba Cloud released Qwen3.5-397B-A17B, an open-weight vision-language model featuring a hybrid architecture that activates 17 billion parameters, achieves 19x higher decoding throughput, and supports 201 dialects for autonomous multimodal agent tasks."
11,Business Insider,"The career rise of OpenAI's billionaire CEO, Sam Altman",9.698064,OpenAI CEO Sam Altman restructured the company into a public benefit corporation in 2025 and launched the $500 billion Stargate infrastructure initiative while expanding product lines and preparing for a 2026 legal trial against Elon Musk.
25,Reuters,"Alibaba debuts Qwen 3.5, adding ""visual agentic capabilities"" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)",9.689933,"Alibaba debuted Qwen 3.5, an AI model with visual agentic capabilities for independent task execution that is 60% cheaper and eight times more efficient than its predecessor, reportedly outperforming U.S. rivals on several benchmarks."
23,Business Insider,Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers,9.585259,White House trade advisor Peter Navarro and President Trump mandated that Big Tech companies internalize all electricity and grid costs for AI data centers to protect taxpayers from $31 billion in requested utility rate hikes.
...,...,...,...,...
88,CBC,Acadia University opens up AI literacy course to public for free,1.435985,"Acadia University launched a free, 2.5-hour AI literacy course for the public that covers text-based tools like ChatGPT and Claude, following the enrollment of nearly 500 students since January."
90,Reddit,AI was supposed to be used to cure cancer….,1.154006,"Ethical discussions highlight the contrast between AI's role in oncology research, such as the targeted chemotherapy drug AOH1996, and its increasing application in creating viral deepfake media through open-source video editing workflows."
91,Cageside Seats,El Grande Americano calls out ‘Original’ Americano over use of AI,0.697374,"Professional wrestler El Grande Americano criticized his rival's use of AI-generated vignettes and voice synthesis in Lucha Libre AAA promotions, labeling the AI-filtered depiction of the Mexican flag a sign of disrespect to his culture."
92,Times of India,"She earns Rs 2 crore yearly, but OpenAI employee won't say YES to marriage without this non-negotiable rule",0.451090,OpenAI employee Gujari Singh mandates a prenuptial agreement as a non-negotiable condition for marriage to protect her annual salary of over ₹2 crore and equity-based assets.
93,CNN,Why the ‘AI scare trade’ might not be done,0.071364,"Market analysis indicates that the period of investor caution and volatility regarding artificial intelligence stocks, known as the AI scare trade, may continue."

In [25]:
headline_df

,source,title,url,published,rss_summary,id,isAI,text_path,content_length,domain,...,input_text,age,recency_score,low_quality,on_topic,important,bt_z,adjusted_len,rating,bradley_terry
0,Feedly AI,Why an A.I. Video of Tom Cruise Battling Brad ...,https://www.nytimes.com/2026/02/16/movies/tom-...,NaN,NaN,0,True,download/text/Why_an_A.I._Video_of_Tom_Cruise_...,6657,nytimes.com,...,Why an A.I. Video of Tom Cruise Battling Brad ...,1.00001,-0.000007,0.000000e+00,1.000000e+00,1.000000e+00,2.636777,0.823279,10.460049,3.523035
1,FT,Business schools search for clear AI guidelines,https://www.ft.com/content/3659b953-8a3a-4e13-...,NaN,NaN,1,True,download/text/Business_schools_search_for_clea...,5739,ft.com,...,Business schools search for clear AI guideline...,1.00001,-0.000007,0.000000e+00,9.999545e-01,9.999998e-01,1.621825,0.758836,9.380609,-5.721854
2,FT,Are Anthropic’s new AI work tools game-changin...,https://www.ft.com/content/92dfd571-8d34-42f1-...,NaN,NaN,2,True,download/text/Are_Anthropic_s_new_AI_work_tool...,1329,ft.com,...,Are Anthropic’s new AI work tools game-changin...,1.00001,-0.000007,0.000000e+00,1.000000e+00,1.000000e+00,1.599719,0.123525,8.723238,-5.923206
3,FT,KPMG partner fined over using AI to pass AI test,https://www.ft.com/content/c30ded60-bece-45e0-...,NaN,NaN,3,True,download/text/KPMG_partner_fined_over_using_AI...,1317,ft.com,...,KPMG partner fined over using AI to pass AI te...,1.00001,-0.000007,0.000000e+00,9.992903e-01,9.399133e-01,0.947166,0.119586,8.005949,-11.867115
4,Feedly AI,"OpenAI retired GPT-4o on February 13, angering...",https://www.bloomberg.com/news/newsletters/202...,NaN,NaN,4,True,,0,bloomberg.com,...,"OpenAI retired GPT-4o on February 13, angering...",1.00001,-0.000007,1.186112e-08,9.990890e-01,5.621765e-01,1.703333,0.000000,8.264592,-4.979421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,NewsAPI,Adopt AI for electronic transmission of poll r...,https://punchng.com/?p=2065067,2026-02-15T12:23:44Z,NaN,89,True,download/text/Adopt_AI_for_electronic_transmis...,4429,punchng.com,...,Adopt AI for electronic transmission of poll r...,1.00001,-0.000007,0.000000e+00,4.539785e-05,4.959358e-15,1.188539,0.646306,1.834883,-9.668522
90,Reddit,AI was supposed to be used to cure cancer….,https://v.redd.it/rgrvl3kydqjg1,NaN,NaN,90,True,download/text/AI_was_supposed_to_be_used_to_cu...,3147,redd.it,...,AI was supposed to be used to cure cancer….\n-...,1.00001,-0.000007,0.000000e+00,1.406363e-02,1.879529e-12,0.642053,0.497897,1.154006,-14.646300
91,Feedly AI,El Grande Americano calls out ‘Original’ Ameri...,https://www.cagesideseats.com/wwe/418612/el-gr...,NaN,NaN,91,True,download/text/El_Grande_Americano_calls_out__O...,2816,cagesideseats.com,...,El Grande Americano calls out ‘Original’ Ameri...,1.00001,-0.000007,1.189688e-14,1.147877e-05,0.000000e+00,0.247737,0.449633,0.697374,-18.238001
92,NewsAPI,"She earns Rs 2 crore yearly, but OpenAI employ...",https://economictimes.indiatimes.com/magazines...,2026-02-15T12:39:24Z,NaN,92,True,download/text/She_earns_Rs_2_crore_yearly__but...,11087,indiatimes.com,...,"She earns Rs 2 crore yearly, but OpenAI employ...",1.00001,-0.000007,1.000000e+00,1.026188e-10,0.000000e+00,0.406282,1.044814,0.451090,-16.793859
93,Feedly AI,Why the ‘AI scare trade’ might not be done,https://www.cnn.com/2026/02/16/business/ai-dis...,NaN,NaN,93,True,,0,cnn.com,...,Why the ‘AI scare trade’ might not be done\n- ...,1.00001,-0.000007,1.000000e+00,3.160881e-10,0.000000e+00,0.071371,0.000000,0.071364,-19.844462

In [26]:
for row in headline_df.sort_values("rating", ascending=False).itertuples():
    display(Markdown(f"""
{row.rating:.1f} - [{row.title}]({row.url}) - {row.site_name}

{row.short_summary}
    """))

10.5 - [Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood](https://www.nytimes.com/2026/02/16/movies/tom-cruise-brad-pitt-artificial-intelligence-seedance.html) - The New York Times

ByteDance's Seedance 2.0 AI tool produced a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, prompting Disney and the Motion Picture Association to allege copyright infringement and demand the company cease operations.

9.9 - [Qwen3.5: Towards Native Multimodal Agents](https://qwen.ai/blog?id=qwen3.5) - Qwen

Alibaba Cloud released Qwen3.5-397B-A17B, an open-weight vision-language model featuring a hybrid architecture that activates 17 billion parameters, achieves 19x higher decoding throughput, and supports 201 dialects for autonomous multimodal agent tasks.

9.7 - [The career rise of OpenAI's billionaire CEO, Sam Altman](https://www.businessinsider.com/sam-altman) - Business Insider

OpenAI CEO Sam Altman restructured the company into a public benefit corporation in 2025 and launched the $500 billion Stargate infrastructure initiative while expanding product lines and preparing for a 2026 legal trial against Elon Musk.

9.7 - [Alibaba debuts Qwen 3.5, adding "visual agentic capabilities" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters)](https://www.reuters.com/world/china/alibaba-unveils-new-qwen35-model-agentic-ai-era-2026-02-16/) - Reuters

Alibaba debuted Qwen 3.5, an AI model with visual agentic capabilities for independent task execution that is 60% cheaper and eight times more efficient than its predecessor, reportedly outperforming U.S. rivals on several benchmarks.

9.6 - [Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers](https://www.businessinsider.com/trump-trade-advisor-peter-navarro-ai-internalize-data-center-costs-2026-2) - Business Insider

White House trade advisor Peter Navarro and President Trump mandated that Big Tech companies internalize all electricity and grid costs for AI data centers to protect taxpayers from $31 billion in requested utility rate hikes.

9.4 - [Business schools search for clear AI guidelines](https://www.ft.com/content/3659b953-8a3a-4e13-b322-c973a545b836) - Financial Times

More than 700 US business schools have integrated AI into their curricula, though the absence of standardized benchmarks has prompted new initiatives to establish ethical and capability frameworks.

9.2 - [The art of the squeal: What we can learn from the flood of AI resignation letters](https://www.businessinsider.com/resignation-letters-quit-openai-anthropic-2026-2) - Business Insider

Researchers from OpenAI, Anthropic, and xAI have published public resignation letters citing internal conflicts between AI safety alignment and commercial pressures to prioritize product development over ethical governance.

9.1 - [Dario Amodei says Anthropic struggles to balance 'incredible commercial pressure' with its 'safety stuff'](https://www.businessinsider.com/dario-amodei-anthropic-profit-pressure-versus-safety-mission-2026-2) - Business Insider

Anthropic CEO Dario Amodei reports pressure to maintain 10x revenue growth while prioritizing AI safety, as the company reaches a $14 billion revenue run-rate and a $380 billion valuation following a $30 billion funding round.

9.0 - [All the important news from the ongoing India AI Impact Summit](https://techcrunch.com/2026/02/16/all-the-important-news-from-the-ongoing-india-ai-summit/) - TechCrunch

India earmarked $1.1 billion for a state-backed AI venture fund, Blackstone acquired a majority stake in Neysa for $600 million, and Anthropic announced its first India office during the India AI Impact Summit.

8.9 - [OpenAI has hired the developer behind AI agent OpenClaw](https://www.engadget.com/ai/openai-has-hired-the-developer-behind-ai-agent-openclaw-092934041.html) - Engadget

OpenAI hired Peter Steinberger, creator of the open-source tool OpenClaw, to lead personal agent development following a bidding war with Meta, as the tool with 196,000 GitHub stars moves to an independent foundation.

8.8 - [Fund Beating 99% of Peers Sees Few Software Firms Surviving AI](https://finance.yahoo.com/news/fund-beating-99-peers-sees-090000453.html) - Yahoo

Polar Capital fund manager Nick Evans is divesting from application software firms like Adobe and SAP, citing AI as an existential threat that enables clients and startups to build competing internal tools and infrastructure.

8.7 - [Are Anthropic’s new AI work tools game-changing for professionals?](https://www.ft.com/content/92dfd571-8d34-42f1-8be8-dce126998e37) - Financial Times

Anthropic is launching AI work tools and adaptable plug-ins for professional sectors, including legal and consulting, to compete with established specialized software.

8.5 - [The Big Tech losers as AI fears wipe billions of dollars off valuations](https://finance.yahoo.com/news/big-tech-stocks-lose-billions-093834534.html) - Yahoo

Microsoft lost approximately $613 billion in market value this year amid rising AI competition from Google and Anthropic, while investors shifted capital toward hardware and retail companies like TSMC and Walmart.

8.3 - [OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary/Bloomberg)](https://www.bloomberg.com/news/newsletters/2026-02-13/openai-retires-controversial-4o-ai-model-angering-loyal-users) - Bloomberg

OpenAI retired GPT-4o on February 13, prompting over 20,000 users to sign a petition in protest of the decision.

8.2 - [After spooking Hollywood, ByteDance will tweak safeguards on new AI model](https://www.theverge.com/ai-artificial-intelligence/879644/bytedance-seedance-safeguards-ai-video-copyright-infringement) - The Verge

ByteDance is implementing new safeguards for its Seedance 2.0 AI video generator following copyright infringement allegations and cease and desist letters from Disney, Paramount, SAG-AFTRA, and the Motion Picture Association.

8.2 - [OpenAI and Cisco Back Standards to Scale Agentic AI](https://www.pymnts.com/artificial-intelligence-2/2026/openai-and-cisco-back-standards-to-scale-agentic-ai/) - PYMNTS

OpenAI, Anthropic, and Cisco joined the Agentic AI Foundation to establish governance standards, addressing infrastructure and trust barriers as Gartner predicts 40% of enterprise software will include AI agents by 2026.

8.1 - [Why are experts sounding the alarm on AI risks?](https://www.aljazeera.com/news/2026/2/15/why-are-experts-sounding-the-alarm-on-ai-risks) - Al Jazeera

Researchers from Anthropic, OpenAI, and xAI resigned over safety concerns as Microsoft AI CEO Mustafa Suleyman predicts AGI could automate white-collar tasks within 18 months, with 60% of jobs in advanced economies currently vulnerable to disruption.

8.0 - [KPMG partner fined over using AI to pass AI test](https://www.ft.com/content/c30ded60-bece-45e0-981d-653e1e3e9818) - Financial Times

KPMG fined a partner for using artificial intelligence to complete an internal AI competency exam, marking one of several recent instances where staff used the technology to bypass internal testing requirements.

7.9 - [In a podcast, OpenClaw creator Peter Steinberger describes his phone calls with Mark Zuckerberg and Sam Altman, and says he had been contacted by “every big VC”](https://www.implicator.ai/peter-steinberger-chose-openai-the-code-was-never-the-point/) - Implicator AI

OpenClaw creator Peter Steinberger joined OpenAI to lead personal agent development following a bidding war with Meta, prioritizing the framework's 196,000 GitHub stars and 2 million weekly visitors over its codebase.

7.8 - [The scientist using AI to hunt for antibiotics just about everywhere](https://www.technologyreview.com/2026/02/16/1132516/cesar-de-la-fuente-using-ai-antibiotics-hunt/) - Technology Review

Bioengineer César de la Fuente uses the ApexOracle AI model to discover antimicrobial peptides from venom and extinct species, following successful animal trials against World Health Organization priority bacteria.

7.6 - [Living neurons integrated into modern AI processing, claims SF startup — biological computing power used to boost computer vision, generative video, and more](https://www.tomshardware.com/tech-industry/artificial-intelligence/living-neurons-integrated-into-modern-ai-processing-claims-sf-startup-biological-computing-power-used-to-boost-computer-vision-generative-video-and-more) - Tom's Hardware

San Francisco startup The Biological Computing Company raised $25 million to develop a platform integrating living neurons with AI models, claiming the technology processes data five times faster than silicon chips with lower power consumption.

7.4 - [Sam Altman officially confirms that OpenAI has acquired OpenClaw; Peter Steinberger to lead personal agents](https://www.reddit.com/r/OpenAI/comments/1r5rnbl/sam_altman_officially_confirms_that_openai_has/) - Reddit

OpenAI acquired OpenClaw and hired creator Peter Steinberger to lead the development of personal AI agents, while transitioning the technology into an open-source foundation project for enterprise-grade autonomous systems.

7.4 - [Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...'](https://www.benzinga.com/markets/tech/26/02/50636187/anthropic-ceo-dario-amodei-warns-one-wrong-ai-bet-could-bankrupt-the-company-no-hedge-on-earth-that-could-stop) - Benzinga

Anthropic CEO Dario Amodei warned that over-investing in AI compute could bankrupt the company if revenue lags, noting plans to spend $50 billion on infrastructure while predicting high-capability models will emerge within two years.

7.3 - [Anthropic tries to hide Claude's AI actions. Devs hate it](https://www.theregister.com/2026/02/16/anthropic_claude_ai_edits/) - The Register

Anthropic updated its Claude Code AI tool to hide file names by default to simplify the interface, prompting developer criticism over reduced transparency while offering a verbose mode as a compromise.

7.3 - [Pentagon threatens to cut off Anthropic in AI safeguards dispute](https://www.thehindubusinessline.com/info-tech/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute/article70635027.ece) - The Hindu Business Line

The Pentagon is considering severing ties with Anthropic due to usage restrictions on weapons development and battlefield operations, despite the Claude model's involvement in the U.S. military operation to capture Nicolas Maduro.

7.2 - [Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times)](https://t.co/iwFZFYyeEB) - Twitter

US productivity increased by approximately 2.7% in 2025, nearly doubling the 1.4% decade average, as AI-exposed sectors reduced entry-level hiring and began realizing measurable efficiency gains from technology.

7.2 - [Prompts Are Overrated. Here’s How I Built a Zero-Copy Fog AI Node Without Python](https://hackernoon.com/prompts-are-overrated-heres-how-i-built-a-zero-copy-fog-ai-node-without-python) - Hacker Noon

FogAI utilizes a Kotlin-C++ hybrid and zero-copy pipeline to achieve 50 tokens per second on-device, providing offline resilience and autonomous decision-making for Industry 4.0 applications in compliance with ISA-95 standards.

7.2 - [NASA trials AI-powered driving of Mars rover](https://www.semafor.com/article/02/16/2026/nasa-trials-ai-powered-driving-of-mars-rover) - Semafor

NASA trialed AI-powered autonomous driving on the Perseverance rover, the Pentagon threatened Anthropic's $200 million contract over weapons use, and OpenAI accused DeepSeek of unauthorized distillation techniques after Anthropic raised $30 billion at a $380 billion valuation.

7.1 - [Eric Schmidt Says 'We're Running Out Of Electricity,' Urges Space Data Centers — SpaceX CEO Elon Musk Quips: 'If Only There Were A Company'](https://www.benzinga.com/markets/tech/26/02/50635721/eric-schmidt-says-were-running-out-of-electricity-urges-space-data-centers-spacex-ceo-elon-musk-quips-if-only-there-were-a-company) - Benzinga

Eric Schmidt warned of a 92-gigawatt power shortfall for AI, prompting Elon Musk and Alphabet to develop orbital data center prototypes by 2027 to leverage continuous solar energy and reduced cooling requirements.

7.0 - [Alphabet Just Gave Nvidia and Broadcom Investors 185 Billion Reasons to Cheer](https://www.fool.com/investing/2026/02/16/alphabet-just-gave-nvidia-and-broadcom-investors-1/) - The Motley Fool

Alphabet projected capital expenditures of $175 billion to $185 billion for 2026 to expand AI infrastructure, benefiting Nvidia through GPU demand and Broadcom through custom Tensor Processing Unit development.

6.9 - [Snowflake's CEO says software giants risk becoming a 'dumb data pipe' to AI models](https://www.businessinsider.com/snowflake-ceo-sridhar-ramaswamy-software-dumb-data-pipe-ai-2026-2) - Business Insider

Snowflake CEO Sridhar Ramaswamy warns that software giants risk becoming "dumb data pipes" as AI model makers centralize enterprise data, leading Snowflake to offer flexible access for customers using third-party platforms like ChatGPT.

6.7 - [AMD Takes on Nvidia in India With Expanded Tata AI Partnership](https://www.bloomberg.com/news/articles/2026-02-16/amd-takes-on-nvidia-in-india-with-expanded-tata-ai-partnership) - Bloomberg

AMD expanded its artificial intelligence partnership with Tata Group in India to compete with Nvidia.

6.6 - [Fractal Analytics’ muted IPO debut signals persistent AI fears in India](https://techcrunch.com/2026/02/16/fractal-analytics-muted-ipo-debut-signals-persistent-ai-fears-in-india/) - TechCrunch

Fractal Analytics debuted on the Indian public market with a 7% price drop and a $1.6 billion valuation, despite reporting a 26% revenue increase to $304.8 million and shifting to profitability for the 2025 fiscal year.

6.6 - [The Guardian view on AI: safety staff departures raise worries about industry pursuing profit at all costs | Editorial](https://www.theguardian.com/commentisfree/2026/feb/15/the-guardian-view-on-ai-safety-staff-departures-raise-worries-about-industry-pursuing-profit-at-all-costs) - The Guardian

Safety researchers resigned from OpenAI and Anthropic, citing concerns that profit-driven monetization strategies are sidelining safety protocols as the US and UK governments decline to sign international safety agreements.

6.6 - [ByteDance promises to tighten up its new AI video generator after viral Cruise vs. Pitt clip](https://www.engadget.com/ai/bytedance-promises-to-tighten-up-its-new-ai-video-generator-after-viral-cruise-vs-pitt-clip-112941384.html) - Engadget

ByteDance is tightening restrictions on its AI video generator following a cease-and-desist letter from Disney regarding a viral deepfake video featuring actors Tom Cruise and Brad Pitt.

6.5 - [From DSP to AI: Evolving Approaches in Audio Processing](https://hackernoon.com/from-dsp-to-ai-evolving-approaches-in-audio-processing) - Hacker Noon

Audio intelligence systems are transitioning to hybrid models that integrate machine learning with Digital Signal Processing to enhance real-time stability and physical grounding in applications such as noise suppression and spatial audio.

6.5 - [ByteDance says it "respects IP rights and we have heard the concerns regarding Seedance" and it plans to "strengthen" safeguards, after Disney's legal threats (Osmond Chia/BBC)](https://www.bbc.com/news/articles/c93wq6xqgy1o) - BBC

ByteDance pledged to strengthen safeguards for its AI video tool Seedance 2.0 after Disney issued a cease-and-desist letter regarding the unauthorized use of Marvel and Star Wars characters.

6.5 - [How I Built a Fail-Safe Legal AI Engine for Singapore Laws Using Triple-Model RAG](https://hackernoon.com/how-i-built-fail-safe-legal-ai-engine-for-singapore-laws-using-triple-model-rag) - Hacker Noon

Developer Aditya Prasad open-sourced a legal AI engine for Singapore laws that utilizes a triple-model failover architecture and a 0.5 confidence threshold to process over 30,000 pages of government documents.

6.4 - [Peter Steinberger joins OpenAI](https://thenextweb.com/news/peter-steinberger-joins-openai) - The Next Web

OpenAI hired Peter Steinberger, creator of OpenClaw, to accelerate the development of autonomous personal AI agents that proactively manage workflows and tasks across multiple applications without explicit user prompts.

6.4 - [TikTok creator ByteDance vows to curb AI video tool after Disney threat](https://www.theguardian.com/technology/2026/feb/16/tiktok-bytedance-ai-video-tool-disney-seedance-tom-cruise-brad-pitt) - The Guardian

ByteDance is restricting its Seedance 2.0 AI video generator following a cease-and-desist letter from Disney and copyright infringement accusations from the MPA and Sag-Aftra regarding the unauthorized use of Marvel and Star Wars intellectual property.

6.4 - [Blackstone mogul warned of ‘urgent need’ for AI preparedness—Now he’s turning his $48 billion fortune into a top philanthropic foundation](https://fortune.com/2026/02/16/stephen-schwarzman-blackstone-ceo-48-billion-fortune-to-philanthropic-foundation-focused-on-ai/) - Fortune

Blackstone CEO Stephen Schwarzman is committing the majority of his $47.8 billion fortune to his foundation to support artificial intelligence and education, focusing on global AI preparedness and workforce development.

6.3 - [Following Disney, Paramount sent a cease-and-desist letter to ByteDance, alleging its AI-generated Seedance videos and Seedream images infringed Paramount's IP](https://variety.com/2026/film/news/paramount-disney-bytedance-cease-and-desist-seedance-ai-infringement-ip-1236663663/) - Variety

Paramount and Disney issued cease-and-desist letters to ByteDance, alleging that its Seedance and Seedream AI platforms infringed on intellectual property from franchises like Star Wars, Marvel, and Star Trek through unauthorized content generation and training.

6.2 - [Former NPR Host Accuses Google Of Copying His Voice For AI Offering](https://gizmodo.com/former-npr-host-accuses-google-of-copying-his-voice-for-ai-offering-2000722402) - Gizmodo

Former NPR host David Greene sued Google for allegedly training its NotebookLM AI voice on his likeness without authorization, while Google maintains the model was based on a hired professional actor.

6.2 - [Google puts users at risk by downplaying health disclaimers under AI Overviews](https://www.theguardian.com/technology/2026/feb/16/google-puts-users-at-risk-downplaying-disclaimers-ai-overviews) - The Guardian

Google places medical disclaimers in AI Overviews behind "Show more" buttons and small fonts, which experts warn prioritizes speed over accuracy and risks the spread of medical misinformation.

6.0 - [WTF is Markdown for AI agents?](https://digiday.com/media/wtf-is-markdown-for-ai-agents/) - Digiday

Cloudflare launched a tool to convert publisher content into Markdown, a format AI agents prefer over HTML for token efficiency and improved Answer Engine Optimization accuracy.

5.9 - [Amazon has a new creative agent to help your business build its own ads](https://www.techradar.com/pro/amazon-has-a-new-creative-agent-to-help-your-business-build-its-own-ads) - TechRadar

Amazon launched Creative Agent, an AI tool using AWS and Anthropic Claude to automate advertising research and generation, reducing production time from weeks to hours for small businesses in the US and Europe.

5.9 - [Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts](https://www.bloomberg.com/news/articles/2026-02-16/anthropic-boosts-india-ai-push-via-flag-airline-cognizant-pacts) - Bloomberg

Anthropic is expanding its artificial intelligence operations in India through new partnerships with Air India and Cognizant.

5.9 - [Forcing AI Makers To Legally Carve Out Mental Health Capabilities And Use LLM Therapist Apps Instead](https://www.forbes.com/sites/lanceeliot/2026/02/16/forcing-ai-makers-to-legally-carve-out-mental-health-capabilities-and-use-llm-therapist-apps-instead/) - Forbes

A proposed policy strategy would require AI developers to integrate specialized mental health components into generic LLMs to provide higher-caliber support and address legal liabilities associated with unsuitable guidance.

5.8 - [AI summit in India kicks off with focus on ‘welfare for all’](https://www.france24.com/en/asia-pacific/20260216-india-hosts-ai-summit) - France 24

India hosted the fourth annual global AI summit in New Delhi, where Google, Microsoft, and Amazon pledged $68 billion in infrastructure investment through 2030 to support application-led innovation for its 72 million daily OpenAI users.

5.8 - [Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release](https://www.bloomberg.com/news/articles/2026-02-16/alibaba-unveils-major-ai-model-upgrade-ahead-of-deepseek-release) - Bloomberg

Alibaba unveiled an upgrade to its artificial intelligence model prior to the release of a competing model from DeepSeek.

5.8 - [Demand for AI-related skills is up 109% since last year. What that means for you](https://www.fastcompany.com/91492708/demand-for-ai-related-skills-is-up-109-since-last-year-what-that-means-for-you) - Fast Company

An Upwork report shows AI-related skill demand grew 109% year-over-year, led by AI video creation at 329%, while employers prioritize human skills and learning agility for the 2026 market.

5.7 - [Indirect prompt injection in AI agents is terrifying and I don't think enough people understand this](https://www.reddit.com/r/ChatGPT/comments/1r5snvl/indirect_prompt_injection_in_ai_agents_is/) - Reddit

Security experts identify indirect prompt injection as an architectural vulnerability where attackers hide commands in data sources, recommending sandboxing, strict access controls, and multi-model consensus to prevent unauthorized AI agent actions.

5.6 - [MiniMax Shares Surge 25% as Optimism Over Chinese AI Firms Grows](https://www.bloomberg.com/news/articles/2026-02-16/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows) - Bloomberg

MiniMax shares increased by 25% following growing optimism regarding Chinese artificial intelligence firms.

5.6 - [India AI Impact Summit 2026: PM Modi to inaugurate expo on Monday](https://www.thehindubusinessline.com/news/national/india-ai-impact-summit-2026-pm-modi-to-inaugurate-expo-on-monday/article70634998.ece) - The Hindu Business Line

Prime Minister Narendra Modi will inaugurate the India AI Impact Expo 2026 on February 16, launching 12 indigenous foundation models for 22 languages as India's AI market is projected to reach $17 billion by 2027.

5.6 - [India can influence global AI regulations, says industry expert](https://www.techinasia.com/news/india-can-influence-global-ai-regulations-says-industry-expert) - Tech in Asia

India utilizes its 20% share of global data and the world's second-largest AI talent pool to influence international AI regulations while prioritizing data health and proactive governance for agentic AI risks.

5.5 - [Ray Wang on How AI Is Causing DRAM Prices to Surge](https://www.bloomberg.com/news/articles/2026-02-16/ai-is-causing-the-price-of-computer-memory-to-surge) - Bloomberg

Ray Wang states that increasing demand for artificial intelligence is driving a surge in DRAM prices.

5.4 - [Top Putin aide Maxim Oreshkin to lead Russian delegation for AI Impact Summit in New Delhi](https://economictimes.indiatimes.com/news/india/top-putin-aide-maxim-oreshkin-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi/articleshow/128381877.cms) - Times of India

Russian presidential aide Maxim Oreshkin will lead a delegation to the AI Impact Summit 2026 in New Delhi from February 16-20 to collaborate with India on developing secure, trusted, and sovereign artificial intelligence frameworks.

5.4 - [Ars Technica Pulls Article With AI Fabricated Quotes About AI Generated Article](https://www.404media.co/ars-technica-pulls-article-with-ai-fabricated-quotes-about-ai-generated-article/) - 404 Media

Ars Technica retracted an article containing fabricated quotes generated by ChatGPT after a staff writer accidentally included the AI's paraphrased output as direct quotations.

5.4 - [OpenAI CEO Sam Altman Signals Deeper India Ties Ahead Of Global AI Impact Summit 2026](https://www.news18.com/business/economy/openai-ceo-sam-altman-signals-deeper-india-ties-ahead-of-global-ai-impact-summit-2026-ws-l-9904937.html) - News18

OpenAI CEO Sam Altman announced plans to expand Delhi operations and support India's Rs 10,371.92 crore AI Mission, identifying the country as its second-largest market with 100 million weekly active ChatGPT users.

5.2 - [Building a ‘Second Brain’ for Marketing Using AI Agents](https://hackernoon.com/building-a-second-brain-for-marketing-using-ai-agents) - Hacker Noon

AI agents create a "second brain" for marketing teams by monitoring performance and retaining institutional memory to improve strategic decision-making and organizational intelligence.

5.1 - [Expensively Quadratic: The LLM Agent Cost Curve](https://blog.exe.dev/expensively-quadratic) - EXE.dev

LLM agent costs scale quadratically because every turn requires reading the entire conversation history, with cache reads accounting for up to 87% of total expenses and 50% of API costs at 27,500 tokens.

5.1 - [California ballot measures that appear aimed at OpenAI were filed by stepbrother of employee at rival Anthropic](https://nypost.com/2026/02/16/business/california-ballot-measures-that-appear-aimed-at-openai-were-filed-by-stepbrother-of-employee-at-rival-anthropic/) - New York Post

Alexander Oldham filed two California ballot measures proposing state oversight of AI firms structured as public benefit corporations, but he lacks the funding required to gather signatures to place the initiatives on the ballot.

5.0 - [Stop Guessing Thread Pool Sizes: How to Plug AI into Spring Batch Safely](https://hackernoon.com/stop-guessing-thread-pool-sizes-how-to-plug-ai-into-spring-batch-safely) - Hacker Noon

Implementing AI-assisted adaptive concurrency in Spring Batch replaces static thread pools with LLM-driven recommendations bounded by hard-coded safety guardrails to manage dynamic runtime conditions and maintain system stability.

4.9 - [The AI Stock That Could Turn the Tables on the "Magnificent Seven"](https://www.fool.com/investing/2026/02/16/the-ai-stock-that-could-turn-the-tables-on-the-mag/) - The Motley Fool

Broadcom reported a 74% year-over-year increase in AI semiconductor revenue and a $10 billion backlog for AI switches, projecting $8.2 billion in Q1 AI revenue driven by custom accelerators and networking hardware.

4.8 - [The Hard Truth About Machine Learning for Amazon FBA Sellers](https://hackernoon.com/the-hard-truth-about-machine-learning-for-amazon-fba-sellers) - Hacker Noon

Temporal Convolutional Networks with attention layers and Ray Tune optimization reduce Amazon FBA forecast errors by 28% over LSTM models, utilizing Weighted Quantile Loss to better manage inventory holding costs and stockouts.

4.8 - [Top Putin aide to lead Russian delegation for AI Impact Summit in New Delhi](https://www.business-standard.com/technology/tech-news/top-putin-aide-to-lead-russian-delegation-for-ai-impact-summit-in-new-delhi-126021500398_1.html) - Business Standard

Maxim Oreshkin, senior aide to President Vladimir Putin, leads a Russian delegation to the AI Impact Summit 2026 in New Delhi to discuss AI governance, technology partnerships, and sovereign AI systems within the BRICS framework.

4.8 - [Real Design Trends are Dying Under the Weight of Recursive AI Echoes](https://weandthecolor.com/real-design-trends-are-dying-under-the-weight-of-recursive-ai-echoes/208199) - We And The Color

Generative AI training on synthetic data causes model collapse and design homogenization, leading to 2026 trends favoring analog imperfections and the adoption of Machine Experience and Generative Engine Optimization strategies.

4.7 - [I hate my AI pet with every fiber of my being](https://www.theverge.com/gadgets/877858/life-with-casio-moflin-robot-ai-pet) - The Verge

Casio released Moflin, a $429 AI-powered social robot designed to simulate emotions and develop a unique personality for consumers in Japan and South Korea who cannot keep live animals.

4.7 - [I tested Sentai, the AI voice companion for seniors – and now I get why it’s more than just another smart speaker](https://www.techradar.com/ai-platforms-assistants/i-tested-sentai-the-ai-voice-companion-for-seniors-and-now-i-get-why-its-more-than-just-another-smart-speaker) - TechRadar

Sentai, a UK-developed AI voice companion, provides seniors with medication reminders, appointment tracking, and camera-free fall detection for a £29.50 monthly subscription to support independent living.

4.7 - [I Vibe Coded an App With 3 Popular Chatbots. The Real Winner Is a Good Prompt](https://www.cnet.com/tech/services-and-software/i-vibe-coded-an-app-with-3-popular-chatbots-the-real-winner-is-a-good-prompt/) - CNET

Comparative testing of Gemini, Claude, and ChatGPT for natural language app development demonstrated that iterative prompt refinement allows free AI models to match premium performance, making prompt engineering the primary factor in software quality.

4.7 - [Video: China’s humanoid robot masters stunning sword dance, shows perfect control](https://interestingengineering.com/ai-robotics/china-humanoid-robot-stunning-sword-dance) - Interesting Engineering

Robotera's L7 humanoid robot performed a traditional Chinese sword dance using 55 degrees of freedom to demonstrate advanced motor control and real-time AI coordination for industrial and service applications.

4.4 - [1 Unstoppable Stock to Buy Before It Joins Nvidia, Apple, and Alphabet in the $3 Trillion Club](https://www.fool.com/investing/2026/02/16/1-unstoppable-stock-to-buy-before-it-joins-nvidia/) - The Motley Fool

TSMC reported a 26% year-over-year revenue increase in Q4, driven by high-performance computing sales, as analysts forecast the company could reach a $3 trillion market cap by 2029.

4.4 - [Should You Forget Palantir and Buy 2 OtherArtificial Intelligence(AI) Stocks Right Now?](https://www.fool.com/investing/2026/02/16/should-you-forget-palantir-and-buy-2-other-artific/) - The Motley Fool

Palantir trades at 128x forward earnings while Nvidia plans a 2026 Rubin platform to reduce inference costs tenfold and AMD develops Instinct MI400 chips with 1.5 times the memory capacity of current hardware.

4.2 - [Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs?](https://www.ft.com/content/d47fc46a-12fb-4f2e-8bf5-e97b68dbecf0) - Financial Times

FT Alphaville's The Economics Show examines whether intense domestic competition in China, known as involution, will affect the robotics and artificial intelligence sectors as it has the electric vehicle market.

4.2 - [Bill Gates to visit Amaravati tomorrow, meet CM Naidu on Health, AI & Vision 2047](https://newsmeter.in/top-stories/bill-gates-to-visit-amaravati-tomorrow-meet-cm-naidu-on-health-ai-vision-2047-763064) - NewsMeter

Bill Gates will meet Andhra Pradesh Chief Minister N. Chandrababu Naidu in Amaravati to discuss collaborations in health, education, and agriculture while reviewing AI-enabled farming and data-driven public administration under the Swarnandhra Vision-2047 framework.

4.1 - [Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker](https://www.bloomberg.com/news/articles/2026-02-16/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker) - Bloomberg

Lux Capital and Flutterwave CEO Olugbenga Agboola have invested in a Nigerian drone manufacturing company.

3.3 - ['Big Short' Investor Michael Burry Targets Palantir Over 'Covert Smear' Claims, Warns Of Over 50% Stock Collapse](https://www.benzinga.com/markets/equities/26/02/50636130/big-short-investor-michael-burry-targets-palantir-over-covert-smear-claims-warns-of-over-50-stock-collapse) - Benzinga

Michael Burry disclosed a short position against Palantir, forecasting a 54% stock decline to the $50-$60 range as the UK's NHS investigates the company for allegedly hiring a digital marketing agency to conduct covert smear campaigns.

3.3 - [Rolling your own serverless OCR in 40 lines of code](https://christopherkrapu.com/blog/2026/ocr-textbooks-modal-deepseek/) - Christopher Krapu

Developers can use the Modal platform and DeepSeek's open-source model to convert a 600-page technical textbook into markdown in 45 minutes for approximately $2 using A100 GPUs.

3.2 - [I started at Microsoft as an executive assistant and pivoted to an AI role. I don't regret my English degree.](https://www.businessinsider.com/microsoft-manager-explains-how-she-pivoted-from-admin-to-ai-2026-2) - Business Insider

Microsoft manager Brit Morenus transitioned from a contract executive assistant to a senior AI gamification product manager by obtaining technical certifications and utilizing humanities skills for prompt engineering and metadata tagging.

3.2 - [Billionaire Bill Ackman Buys 2 BrilliantArtificial Intelligence(AI) Stocks -- They Could Soar in the Next Year, According to Wall Street](https://www.fool.com/investing/2026/02/16/bill-ackman-buys-2-ai-stocks-soar-next-year/) - The Motley Fool

Bill Ackman’s Pershing Square Capital Management allocated 23% of its portfolio to Amazon and Meta, citing artificial intelligence integration as a growth driver while analysts project potential gains of up to 43% over the next year.

3.1 - [I asked ChatGPT for a grocery trick — and it cut my food bill in half](https://www.tomsguide.com/ai/i-asked-chatgpt-for-a-grocery-trick-and-it-cut-my-food-bill-in-half) - Tom's Guide

A user reduced their weekly grocery bill by 50%, from $400 to $200, by using ChatGPT to generate meal plans based on photographs of their existing fridge and pantry inventory.

2.8 - [OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project](https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project) - The Information

OpenAI is in advanced negotiations to hire the founder of OpenClaw and other individuals involved in the agent project.

2.3 - [SPAR rolls out AI loss-prevention tech via Veesion partnership](https://www.retail-insight-network.com/news/spar-rolls-out-ai-loss-prevention-tech/) - Retail Insight Network

SPAR International partnered with Veesion to deploy AI-driven loss-prevention technology that integrates with existing security cameras to identify suspicious behavior and alert store personnel in real-time across its global retail network.

2.3 - [Deep-tech startup Atsuya named among top 20 in AI for All challenge](https://www.business-standard.com/companies/start-ups/deep-tech-startup-atsuya-named-among-top-20-in-ai-for-all-challenge-126021500505_1.html) - Business Standard

Atsuya Technologies' AOne platform was named a top 20 solution in the AI for All: Global Impact Challenge for using agent-driven AI to autonomously manage enterprise operations and optimize energy use across industrial sectors.

2.2 - [‘The Simpsons’ Star, 68, Fears Heartless Replacement on Show](https://www.thedailybeast.com/obsessed/simpsons-star-nancy-cartright-68-fears-heartless-replacement-on-show/) - The Daily Beast

Nancy Cartwright, the voice of Bart Simpson, opposed AI replacement in voice acting, citing a lack of human emotion, while Disney explores AI tools following a $1 billion licensing deal with OpenAI.

2.0 - [‘The Simpsons’ Bart Voice Actress Tells AI “Eat My Shorts,” Wants Human Successor: “AI Has No Heart”](https://deadline.com/2026/02/the-simpsons-bart-voice-actress-ai-hopes-human-successor-1236725415/) - Deadline

Nancy Cartwright, the voice of Bart Simpson for 37 seasons, rejected using generative AI to replicate her voice upon retirement, stating that artificial intelligence lacks the emotional capacity of a human performer.

1.8 - [Adopt AI for electronic transmission of poll results, don urges INEC](https://punchng.com/?p=2065067) - Punch Nigeria

Innocent Uwah of Nigerian British University urged the Independent National Electoral Commission to adopt artificial intelligence for electronic result transmission to improve electoral transparency and credibility before the 2027 elections.

1.6 - [AI buzzwords decoded: What terms like LLMs, generative AI, guardrails mean](https://www.business-standard.com/technology/tech-news/ai-buzzwords-decoded-what-terms-like-llms-generative-ai-guardrails-mean-126021500235_1.html) - Business Standard

Definitions for core artificial intelligence terms like Large Language Models and generative AI accompany industry applications in banking and healthcare and safety guardrails intended to mitigate bias and hallucinations.

1.6 - [European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day](https://www.barrons.com/articles/stock-market-news-today-europe-asia-dollar-gold-9b06f698) - Barron's

European stock markets rose as the artificial intelligence trading frenzy paused during the U.S. Presidents Day holiday, following weeks of volatile trading and investor concerns regarding potential industry disruptions.

1.4 - [Acadia University opens up AI literacy course to public for free](https://www.cbc.ca/news/canada/nova-scotia/acadia-university-ai-open-course-9.7073938) - CBC

Acadia University launched a free, 2.5-hour AI literacy course for the public that covers text-based tools like ChatGPT and Claude, following the enrollment of nearly 500 students since January.

1.2 - [AI was supposed to be used to cure cancer….](https://v.redd.it/rgrvl3kydqjg1) - Reddit

Ethical discussions highlight the contrast between AI's role in oncology research, such as the targeted chemotherapy drug AOH1996, and its increasing application in creating viral deepfake media through open-source video editing workflows.

0.7 - [El Grande Americano calls out ‘Original’ Americano over use of AI](https://www.cagesideseats.com/wwe/418612/el-grande-americano-warns-original-over-ai-mexican-flag) - Cageside Seats

Professional wrestler El Grande Americano criticized his rival's use of AI-generated vignettes and voice synthesis in Lucha Libre AAA promotions, labeling the AI-filtered depiction of the Mexican flag a sign of disrespect to his culture.

0.5 - [She earns Rs 2 crore yearly, but OpenAI employee won't say YES to marriage without this non-negotiable rule](https://economictimes.indiatimes.com/magazines/panache/she-earns-rs-2-crore-yearly-but-openai-employee-wont-say-yes-to-marriage-without-this-non-negotiable-rule/articleshow/128382827.cms) - Times of India

OpenAI employee Gujari Singh mandates a prenuptial agreement as a non-negotiable condition for marriage to protect her annual salary of over ₹2 crore and equity-based assets.

0.1 - [Why the ‘AI scare trade’ might not be done](https://www.cnn.com/2026/02/16/business/ai-disruption-fears-us-stocks) - CNN

Market analysis indicates that the period of investor caution and volatility regarding artificial intelligence stocks, known as the AI scare trade, may continue.

In [27]:
# User prompt to run workflow 
# user_prompt = "Run step 6, Cluster articles by topic"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("cluster_by_topic")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting topic extraction for clustering
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using model 'gemini-3-flash-preview' for topic extraction
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 articles for topic extraction
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=TopicExtractionList, reasoning_effort=low
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Extract up to 5 distinct, broad topics from the news summary below:
[
  {
    "id":0,
    "input_text":"Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood\nA 15-second clip created by an artificial intelligence tool owned by the Chinese technology company ByteDance appears more cinematic than anything so far.\n- ByteDance's Seedance 2.0 AI tool created a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, sparking alarm in Hollywood due to its professional-grade cinematic quality. - Disney and the Motion Picture Association have demanded ByteDance cease operations, alleging the tool was trained on a 'pirated library' of copyrighted characters and films. - While some industry professionals fear imminent job displacement, others argue that AI remains an 'averaging machine' incapable of producing poignant or provocative human-level artistry."
  },
  {
    "id":1,
    "input_text":"Business schools search for clear AI guidelines\nAttempts to establish shared standards are lagging behind adoption of the technology\n- Business schools are rapidly integrating AI into curricula and operations, with over 700 AI-focused programs identified in the US, yet institutions lack a standardized roadmap or clear benchmarks for implementation. - New initiatives like the Digital Education Council\u2019s benchmarking framework aim to measure AI capability and ethics, while schools like Cambridge and HEC pilot interactive AI teaching cases and automated grading assistants. - Concerns persist regarding academic integrity and the offloading of critical thinking, leading deans to emphasize transparency and the need for ethical guidelines to prevent the disintermediation of traditional education."
  },
  {
    "id":2,
    "input_text":"Are Anthropic\u2019s new AI work tools game-changing for professionals?\nAdaptable plug-ins must compete with bespoke products already used by lawyers and consultants\n- Anthropic is launching new AI work tools and adaptable plug-ins aimed at professional sectors. - The new tools are designed to compete with specialized software currently used by legal and consulting professionals. - The market impact will be determined by the ability of these general-purpose AI tools to replace established, bespoke industry products."
  },
  {
    "id":3,
    "input_text":"KPMG partner fined over using AI to pass AI test\nAccounting firm has caught several staff members in recent months using the technology for internal exams\n- A KPMG partner was fined after being caught using artificial intelligence to complete an internal exam designed to test AI competency. - The incident is part of a broader trend within the accounting firm, which has identified several staff members using AI technology to bypass internal testing requirements in recent months. - The case underscores the growing regulatory and ethical challenges professional services firms face in ensuring staff integrity as they adopt and train employees on generative AI tools."
  },
  {
    "id":4,
    "input_text":"OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary\/Bloomberg)\nno content"
  },
  {
    "id":5,
    "input_text":"AMD Takes on Nvidia in India With Expanded Tata AI Partnership\n- no content"
  },
  {
    "id":6,
    "input_text":"Anthropic tries to hide Claude's AI actions. Devs hate it\n: The software doesn't show what files it's working on\n- Anthropic updated its Claude Code AI tool to hide specific file names during operations, a move intended to simplify the UI but criticized by developers for reducing transparency. - Developers argue that seeing file paths is essential for catching context errors early, ensuring security, and managing costs by interrupting incorrect agentic actions. - Despite significant user pushback, Anthropic leadership maintains the condensed view as the default, offering a modified verbose mode as a compromise for those requiring detailed activity logs."
  },
  {
    "id":7,
    "input_text":"After spooking Hollywood, ByteDance will tweak safeguards on new AI model\nIts easier to apologise than ask permission.\n- ByteDance is updating safeguards for its Seedance 2.0 AI video generator following copyright infringement allegations from Disney, Paramount, and Hollywood trade groups. - Major studios issued cease and desist letters after the model produced hyperrealistic videos featuring protected characters and the likenesses of actors like Tom Cruise and Brad Pitt. - SAG-AFTRA and the MPA condemned the tool for violating intellectual property laws and threatening the livelihoods of human talent at a massive scale."
  },
  {
    "id":8,
    "input_text":"How I Built a Fail-Safe Legal AI Engine for Singapore Laws Using Triple-Model RAG\n- Developer Aditya Prasad created a RAG-based legal AI engine for Singapore laws featuring a triple-model failover architecture using Gemini, Llama 3, and Groq to ensure 24\/7 reliability. - The technical stack utilizes the BGE-M3 embedding model and FAISS to index over 30,000 pages of government PDFs, prioritizing a high-precision research UI over standard chat interfaces. - To mitigate hallucinations, the system enforces a 0.5 confidence threshold for document retrieval and has been open-sourced to support future LegalTech innovation and autonomous research."
  },
  {
    "id":9,
    "input_text":"From DSP to AI: Evolving Approaches in Audio Processing\nHow DSP and machine learning converge to power real-time, reliable, and physically grounded audio AI systems.\n- Modern audio intelligence is transitioning from deterministic Digital Signal Processing (DSP) to hybrid systems that integrate machine learning with classical signal processing to maintain physical grounding and real-time stability. - Hybrid approaches are being deployed in noise suppression, spatial audio for AR\/VR, and source separation, where neural networks handle complex inference while DSP components ensure phase consistency and temporal resolution. - The field is moving toward Differentiable Digital Signal Processing (DDSP) and context-aware systems that balance computational efficiency with human-aligned perceptual evaluation in safety-critical and consumer applications."
  }
]
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Extract up to 5 distinct, broad topics from the news summary below:
[
  {
    "id":10,
    "input_text":"Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts\n- no content"
  },
  {
    "id":11,
    "input_text":"The career rise of OpenAI's billionaire CEO, Sam Altman\nOpenAI CEO Sam Altman helped usher in the AI age. Now, he's doing everything he can to keep OpenAI ahead.\n- OpenAI restructured into a public benefit corporation in 2025 and expanded its product line to include the Atlas browser, Sora video app, and an upcoming AI consumer device designed with Jony Ive. - Altman spearheaded 'Stargate,' a $500 billion US AI infrastructure initiative in collaboration with Oracle, SoftBank, and the Trump administration, while preparing for a 2026 trial against Elon Musk. - Despite lacking equity in OpenAI, Altman maintains billionaire status through investments in firms like Stripe and Helion and has committed to the Giving Pledge with his husband, Oliver Mulherin."
  },
  {
    "id":12,
    "input_text":"The scientist using AI to hunt for antibiotics just about everywhere\nC\u00e9sar de la Fuente is on a mission to combat antimicrobial resistance by looking at nature\u2019s own solutions.\n- Bioengineer C\u0000\u0000sar de la Fuente is using AI for molecular de-extinction, mining genetic data from sources like venom and extinct species to discover antimicrobial peptides (AMPs). - These peptides provide a multimodal attack against pathogens, addressing the high costs and low returns of traditional antibiotic discovery. - The team is developing ApexOracle, a multimodal AI model to predict peptide efficacy, following successful animal trials against WHO-priority bacteria."
  },
  {
    "id":13,
    "input_text":"The art of the squeal: What we can learn from the flood of AI resignation letters\nWhat we can learn from the flood of \"why I quit\" letters from researchers at Anthropic, OpenAI, and xAI.\n- A surge of public resignation letters from top researchers at OpenAI, Anthropic, and xAI has emerged as a new industry trend, highlighting internal conflicts over AI safety, alignment, and the rapid pace of development toward AGI. - Departures are often driven by the tension between safety-focused research and commercial pressures to ship consumer products, exemplified by OpenAI's move toward ad-supported models and the subsequent resignation of researchers like Zo\u00eb Hitzig. - Former safety leaders like Jan Leike and Steven Adler warn that safety processes have \"taken a backseat to shiny products,\" expressing fears that the industry is sprinting toward a powerful technology it may not be able to control or govern ethically."
  },
  {
    "id":14,
    "input_text":"Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release\n- no content"
  },
  {
    "id":15,
    "input_text":"MiniMax Shares Surge 25% as Optimism Over Chinese AI Firms Grows\n- no content"
  },
  {
    "id":16,
    "input_text":"Ray Wang on How AI Is Causing DRAM Prices to Surge\n- no content"
  },
  {
    "id":17,
    "input_text":"Living neurons integrated into modern AI processing, claims SF startup \u2014 biological computing power used to boost computer vision, generative video, and more\nThe Biological Computing Company (TBC) has just raised $25m, despite its admitted decades-long plans for real-time compute implementation.\n- San Francisco startup The Biological Computing Company (TBC) raised $25 million to develop a platform that integrates living neurons with AI models to accelerate tasks like computer vision and generative video. - TBC claims its biological computing approach can process foundational AI models five times faster than silicon-based chips while consuming less power and providing greater accuracy. - The technology encodes data into neurons and decodes the resulting activity into AI-compatible representations, though founders acknowledge a 10-to-20-year timeline for full real-time compute integration."
  },
  {
    "id":18,
    "input_text":"ByteDance promises to tighten up its new AI video generator after viral Cruise vs. Pitt clip\nThe announcement comes after a cease-and-desist letter from Disney.\n- ByteDance is tightening restrictions on its AI video generator following the viral spread of a deepfake video featuring actors Tom Cruise and Brad Pitt. - The policy change was prompted by a cease-and-desist letter from Disney, highlighting growing legal and copyright concerns regarding the unauthorized use of celebrity likenesses. - The move reflects increasing pressure on tech companies to implement robust content moderation and prevent the misuse of synthetic media in AI development."
  },
  {
    "id":19,
    "input_text":"Prompts Are Overrated. Here\u2019s How I Built a Zero-Copy Fog AI Node Without Python\nFogAI is a distributed inference platform that actually survives when the internet goes dark.\n- FogAI is a distributed inference platform developed using a Kotlin-C++ hybrid to overcome Python\u2019s Global Interpreter Lock (GIL) and memory overhead in edge computing environments. - The architecture features a zero-copy pipeline and dual-engine core (Alibaba MNN and ONNX Runtime), achieving 50 tokens\/sec on-device for DeepSeek r1 1.5B and handling over 47,000 requests per second. - Built for Industry 4.0, the system adheres to the ISA-95 standard to ensure offline resilience and autonomous decision-making for robotics and smart cities when cloud connectivity is unavailable."
  }
]
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
08:50:22 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Extract up to 5 distinct, broad topics from the news summary below:
[
  {
    "id":20,
    "input_text":"Dario Amodei says Anthropic struggles to balance 'incredible commercial pressure' with its 'safety stuff'\nAnthropic CEO Dario Amodei says he's trying to keep Anthropic growing at a 10x pace while holding the line on safety.\n- Anthropic CEO Dario Amodei reports \"incredible commercial pressure\" to maintain a 10x annual revenue growth rate while upholding the company's core mission of AI safety. - The company recently announced a $30 billion Series G funding round at a $380 billion valuation, reaching a $14 billion run-rate revenue less than three years after its first dollar earned. - Internal tensions over mission drift have surfaced, evidenced by the resignation of safety researcher Mrinank Sharma, who cited the difficulty of prioritizing values over economic survival during rapid expansion."
  },
  {
    "id":21,
    "input_text":"Fractal Analytics\u2019 muted IPO debut signals persistent AI fears in India\nAs India's first AI company to IPO, Fractal Analytics didn't have a stellar first day on the public markets, as enthusiasm for the technology collided with jittery investors in the wake of a sell-off in Indian software stocks.\n- Fractal Analytics, India's first AI unicorn, debuted on the public market with a 7% drop from its issue price, resulting in a $1.6 billion market capitalization that sits below its previous private valuation of $2.4 billion. - The company reported a 26% revenue increase to $304.8 million and a shift to profitability for the fiscal year ending March 2025, despite having to reduce its IPO size by 40% due to investor caution and a broader sell-off in Indian software stocks. - Proceeds from the offering are earmarked for debt repayment, R&D investments in the Fractal Alpha unit, and potential acquisitions as India attempts to establish itself as a global AI development hub."
  },
  {
    "id":22,
    "input_text":"Former NPR Host Accuses Google Of Copying His Voice For AI Offering\nGoogle is sued over the AI podcast generation in NotebookLM.\n- Former NPR host David Greene has sued Google, alleging the company's NotebookLM AI voice was trained on his voice without authorization or compensation. - While an AI forensic firm found a 53-60% confidence match to Greene's voice, Google maintains the model was based on a hired professional actor. - The legal action follows similar high-profile likeness disputes, highlighting the lack of regulatory guardrails for using professional identities in generative AI training."
  },
  {
    "id":23,
    "input_text":"Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers\nPeter Navarro says the White House may force Big Tech to cover electricity and grid costs tied to AI data centers.\n- White House trade advisor Peter Navarro and President Trump mandated that Big Tech must \"internalize\" all electricity and grid costs for AI data centers to protect taxpayers from rising utility rates. - The directive follows a surge in utility rate hike requests totaling $31 billion, fueled by massive infrastructure spending from companies like Meta and Apple to support AI development. - Major AI players including Anthropic and Microsoft have already pledged to cover 100% of their grid upgrade costs to maintain US competitiveness against China while minimizing the burden on local communities."
  },
  {
    "id":24,
    "input_text":"Fund Beating 99% of Peers Sees Few Software Firms Surviving AI\n\u201cWe think application software faces an existential threat from AI,\u201d said Evans, whose $12 billion global technology fund beat 99% of peers over one year and 97% over five.  An exchange-traded fund tracking the US software sector is down 22%, a sharp contrast to semiconductor stocks that have soared as AI spurs computing demand.  Application software, which helps users perform tasks such as writing documents and managing payrolls, looks particularly at risk, according to Evans.\n- Polar Capital's Nick Evans warns that application software faces an \"existential threat\" from AI, leading his top-performing fund to divest from firms like Adobe and SAP in favor of semiconductors and data center infrastructure. - AI coding advancements allow clients to build internal tools and enable startups to replicate existing software, significantly increasing competition for established software companies. - The sector faces financial risks including potential cash-flow squeezes as declining stock valuations may force companies to replace equity-based compensation with cash to retain talent."
  },
  {
    "id":25,
    "input_text":"Alibaba debuts Qwen 3.5, adding \"visual agentic capabilities\" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista\/Reuters)\nAlibaba on Monday unveiled a new artificial intelligence model Qwen 3.5 designed to execute complex tasks independently, with big improvements in performance and cost that the Chinese tech giant claims beat major U.S. rival models on several benchmarks.\n- Alibaba unveiled Qwen3.5, an AI model featuring \"visual agentic capabilities\" designed to independently execute complex tasks across mobile and desktop applications. - The model is 60% cheaper and 8x more efficient than its predecessor, with Alibaba claiming it outperforms U.S. rivals including GPT-5.2 and Claude 4.5 on benchmarks. - The launch intensifies competition in China's AI market against ByteDance and DeepSeek as the industry shifts toward autonomous \"agentic AI\" solutions."
  },
  {
    "id":26,
    "input_text":"NASA trials AI-powered driving of Mars rover\nThe demonstration involved letting AI set the waypoints and identify hazards, marking a first step towards more autonomous planetary exploration.\n- NASA successfully trialed AI-powered autonomous driving on the Perseverance rover, allowing the vehicle to navigate hazards and set waypoints independently to overcome significant signal delays from Earth. - The Pentagon has reportedly threatened to terminate a $200 million contract with Anthropic after the firm refused to allow its AI models to be used for autonomous weaponry and mass surveillance. - Anthropic raised $30 billion at a $380 billion valuation amid market volatility, while OpenAI accused Chinese rival DeepSeek of using unauthorized distillation techniques to train its models."
  },
  {
    "id":27,

▶ Starting Step 6: cluster_topics

08:50:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=10, topics_list=['Anthropic', 'India', 'Airlines', 'Cognizant']), TopicExtraction(id=11, topics_list=['Sam Altman', 'OpenAI', 'Infrastructure', 'Investments', 'Sora']), TopicExtraction(id=12, topics_list=['Antibiotics', 'Bioengineering', 'Peptides', 'Pathogens', 'Drug Discovery']), TopicExtraction(id=13, topics_list=['AI Safety', 'AGI', 'Ethics', 'Anthropic', 'OpenAI']), TopicExtraction(id=14, topics_list=['Alibaba', 'DeepSeek']), TopicExtraction(id=15, topics_list=['MiniMax', 'China']), TopicExtraction(id=16, topics_list=['DRAM', 'Hardware']), TopicExtraction(id=17, topics_list=['Biological Computing', 'Computer Vision', 'Generative Video', 'Foundational Models']), TopicExtraction(id=18, topics_list=['Deepfakes', 'ByteDance', 'Copyright', 'Content Moderation']), TopicExtraction(id=19, topics_list=['Edge Computing', 'FogAI', 'Robotics', 'Smart Cities', 'DeepSeek'])]
08:50:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=30, topics_list=['OpenAI', 'Agents', 'Open Source', 'Sam Altman']), TopicExtraction(id=31, topics_list=['Social Robots', 'Casio', 'Consumer Electronics', 'Japan']), TopicExtraction(id=32, topics_list=['Market Valuations', 'Microsoft', 'Big Tech', 'Semiconductors']), TopicExtraction(id=33, topics_list=['Mental Health', 'LLMs', 'Regulation', 'Healthcare AI']), TopicExtraction(id=34, topics_list=['Skills', 'Employment', 'Upwork', 'Education']), TopicExtraction(id=35, topics_list=['China', 'Robotics', 'Economics']), TopicExtraction(id=36, topics_list=['Drones', 'Venture Capital', 'Nigeria']), TopicExtraction(id=37, topics_list=['Coding', 'Prompt Engineering', 'Chatbots', 'Software Development']), TopicExtraction(id=38, topics_list=['Markdown', 'Agents', 'Cloudflare', 'Data Formats']), TopicExtraction(id=39, topics_list=['Software Engineering', 'Spring Batch', 'Concurrency', 'Java'])]
08:50:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=60, topics_list=['Agents', 'LLM Costs', 'Context Window']), TopicExtraction(id=61, topics_list=['Humanoid Robots', 'Embodied AI', 'Robotera']), TopicExtraction(id=62, topics_list=['OpenAI', 'OpenClaw', 'Agents']), TopicExtraction(id=63, topics_list=['Alphabet', 'Nvidia', 'Broadcom', 'AI Infrastructure']), TopicExtraction(id=64, topics_list=['India', 'AI Summit', 'Economic Impact']), TopicExtraction(id=65, topics_list=['Career Pivot', 'Microsoft', 'Prompt Engineering']), TopicExtraction(id=66, topics_list=['OpenAI', 'India', 'Sam Altman']), TopicExtraction(id=67, topics_list=['Broadcom', 'Semiconductors', 'Networking Hardware']), TopicExtraction(id=68, topics_list=['SpaceX', 'xAI', 'Data Centers', 'Energy']), TopicExtraction(id=69, topics_list=['India', 'AI Summit', 'Foundation Models'])]
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=70, topics_list=['Anthropic', 'Dario Amodei', 'Infrastructure', 'Investment', 'Hardware']), TopicExtraction(id=71, topics_list=['Palantir', 'Nvidia', 'AMD', 'Semiconductors', 'Valuation']), TopicExtraction(id=72, topics_list=['ChatGPT', 'Meal Planning', 'Personal Finance', 'Household Assistants', 'Inventory Management']), TopicExtraction(id=73, topics_list=['Russia', 'India', 'Governance', 'International Relations', 'Military AI']), TopicExtraction(id=74, topics_list=['Bill Gates', 'Andhra Pradesh', 'Public Health', 'Agriculture', 'Governance']), TopicExtraction(id=75, topics_list=['Pentagon', 'Anthropic', 'Defense', 'Ethics', 'Claude']), TopicExtraction(id=76, topics_list=['Productivity', 'Economics', 'Labor Market', 'Business Performance', 'Macroeconomics']), TopicExtraction(id=77, topics_list=['OCR', 'DeepSeek', 'Serverless', 'Modal', 'Software Development']), TopicExtraction(id=78, topics_list=['Bill Ackman', 'Amazon', 'Meta', 'Cloud Computing', 'Robotics']), TopicExtraction(id=79, topics_list=['OpenAI', 'OpenClaw', 'Agents', 'Hiring'])]
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=80, topics_list=['TSMC', 'Semiconductors', 'Nvidia', 'Market Cap']), TopicExtraction(id=81, topics_list=['Retail', 'Loss Prevention', 'Veesion', 'Security']), TopicExtraction(id=82, topics_list=['Agents', 'Sustainability', 'Manufacturing', 'IoT']), TopicExtraction(id=83, topics_list=['Voice Acting', 'Disney', 'OpenAI', 'Entertainment']), TopicExtraction(id=84, topics_list=['Palantir', 'Short Selling', 'Ethics', 'NHS']), TopicExtraction(id=85, topics_list=['Voice Acting', 'Copyright', 'Disney', 'Generative AI']), TopicExtraction(id=86, topics_list=['Stock Markets', 'Europe', 'Investing']), TopicExtraction(id=87, topics_list=['LLMs', 'Generative AI', 'Guardrails', 'Healthcare']), TopicExtraction(id=88, topics_list=['Education', 'Literacy', 'ChatGPT', 'Claude']), TopicExtraction(id=89, topics_list=['Elections', 'Nigeria', 'Automation', 'Governance'])]
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=0, topics_list=['ByteDance', 'Video Generation', 'Hollywood', 'Copyright', 'Seedance']), TopicExtraction(id=1, topics_list=['Business Schools', 'Education', 'Ethics', 'Digital Education Council', 'Academic Integrity']), TopicExtraction(id=2, topics_list=['Anthropic', 'Workplace Tools', 'LegalTech', 'Consulting', 'Productivity']), TopicExtraction(id=3, topics_list=['KPMG', 'Accounting', 'Ethics', 'Internal Exams', 'Professional Integrity']), TopicExtraction(id=4, topics_list=['OpenAI', 'GPT-4o', 'Chatbots', 'User Sentiment']), TopicExtraction(id=5, topics_list=['AMD', 'Nvidia', 'India', 'Tata Group', 'Semiconductors']), TopicExtraction(id=6, topics_list=['Anthropic', 'Claude Code', 'Software Development', 'Transparency', 'Agents']), TopicExtraction(id=7, topics_list=['ByteDance', 'Seedance', 'Copyright', 'Hollywood', 'Intellectual Property']), TopicExtraction(id=8, topics_list=['LegalTech', 'RAG', 'Singapore', 'Open Source', 'Gemini']), TopicExtraction(id=9, topics_list=['Audio Processing', 'DSP', 'Machine Learning', 'AR/VR', 'Signal Processing'])]
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=40, topics_list=['Google', 'AI Overviews', 'Healthcare', 'Safety Warnings']), TopicExtraction(id=41, topics_list=['Machine Learning', 'Amazon FBA', 'Forecasting', 'Inventory Management']), TopicExtraction(id=42, topics_list=['Journalism', 'Ars Technica', 'ChatGPT', 'Editorial Standards']), TopicExtraction(id=43, topics_list=['Agents', 'OpenAI', 'Cisco', 'Governance']), TopicExtraction(id=44, topics_list=['Philanthropy', 'Stephen Schwarzman', 'Education', 'AI Preparedness']), TopicExtraction(id=45, topics_list=['OpenAI', 'Agents', 'Peter Steinberger', 'OpenClaw']), TopicExtraction(id=46, topics_list=['Intellectual Property', 'ByteDance', 'Paramount', 'Generative Video']), TopicExtraction(id=47, topics_list=['AI Safety', 'Regulation', 'Silicon Valley', 'Ethics']), TopicExtraction(id=48, topics_list=['ByteDance', 'Disney', 'Copyright', 'Licensing']), TopicExtraction(id=49, topics_list=['Amazon', 'Advertising', 'Agents', 'AWS'])]
08:50:25 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:26 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=20, topics_list=['Anthropic', 'AI Safety', 'Venture Capital', 'Revenue Growth']), TopicExtraction(id=21, topics_list=['Fractal Analytics', 'IPOs', 'India', 'Software Stocks']), TopicExtraction(id=22, topics_list=['Google', 'NotebookLM', 'Copyright', 'Generative AI']), TopicExtraction(id=23, topics_list=['Data Centers', 'Energy Infrastructure', 'Big Tech', 'Trade Policy']), TopicExtraction(id=24, topics_list=['Software Industry', 'Semiconductors', 'Coding', 'Investment Funds']), TopicExtraction(id=25, topics_list=['Alibaba', 'Qwen', 'Agents', 'China']), TopicExtraction(id=26, topics_list=['NASA', 'Space Exploration', 'Anthropic', 'DeepSeek']), TopicExtraction(id=27, topics_list=['India', 'Venture Capital', 'OpenAI', 'IT Services']), TopicExtraction(id=28, topics_list=['Snowflake', 'Data Management', 'Enterprise Software', 'OpenAI']), TopicExtraction(id=29, topics_list=['Marketing', 'Agents', 'Knowledge Management'])]
08:50:26 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:26 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=50, topics_list=['ByteDance', 'Copyright', 'Video Generation', 'Disney', 'Hollywood']), TopicExtraction(id=51, topics_list=['India', 'Regulation', 'Data Governance', 'Agents', 'Talent']), TopicExtraction(id=52, topics_list=['Elder Care', 'Smart Speakers', 'Privacy', 'Emotional Intelligence', 'Assistive Tech']), TopicExtraction(id=53, topics_list=['Qwen', 'Multimodal AI', 'Open Source', 'Alibaba Cloud', 'Agents']), TopicExtraction(id=54, topics_list=['California', 'Legislation', 'OpenAI', 'Anthropic', 'Public Benefit']), TopicExtraction(id=55, topics_list=['Design', 'Model Collapse', 'Generative AI', 'Search Optimization', 'Aesthetics']), TopicExtraction(id=56, topics_list=['Safety', 'Automation', 'Regulation', 'AGI', 'Ethics']), TopicExtraction(id=57, topics_list=['OpenAI', 'OpenClaw', 'Agents', 'Open Source', 'Acquisitions']), TopicExtraction(id=58, topics_list=['Russia', 'India', 'Sovereign AI', 'Geopolitics', 'Governance']), TopicExtraction(id=59, topics_list=['Cybersecurity', 'Prompt Injection', 'Agents', 'Sandboxing', 'Vulnerabilities'])]
08:50:26 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 10 items returned, validation passed
08:50:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: results_list=[TopicExtraction(id=90, topics_list=['Oncology', 'Deepfakes', 'AOH1996', 'Video Editing', 'Open Source']), TopicExtraction(id=91, topics_list=['Wrestling', 'Voice Synthesis', 'Lucha Libre', 'Cultural Identity', 'Deepfakes']), TopicExtraction(id=92, topics_list=['Prenuptial Agreements', 'Equity Compensation', 'Financial Independence', 'MSME', 'Parametric Insurance']), TopicExtraction(id=93, topics_list=[])]
08:50:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Received chunk: 4 items returned, validation passed
08:50:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | All 10 chunks completed for 94 items
08:50:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Successfully extracted 389 total topics across articles
08:50:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Starting canonical topic classification for 126 topics
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
08:50:34 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Processing 94 items in 10 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 3
Noise points: 54 (57.4%)
Average cluster size: 13.3 ± 9.1
Cluster size range: 5 - 26
=== Quality Scores ===
Silhouette Score: 0.411 (higher is better)
Calinski-Harabasz Score: 23.9 (higher is better)
Davies-Bouldin Score: 0.824 (lower is better)
HDBSCAN Validity Index: 0.110
Composite Score: 0.260 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 49 (52.1%)
Average cluster size: 22.5 ± 13.5
Cluster size range: 9 - 36
=== Quality Scores ===
Silhouette Score: 0.325 (higher is better)
Calinski-Harabasz Score: 17.4 (higher is better)
Davies-Bouldin Score: 0.864 (lower is better)
HDBSCAN Validity Index: 0.086
Composite Score: 0.206 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 23 (24.5%)
Average cluster size: 5.5 ± 2.6
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.384 (higher is better)
Calinski-Harabasz Score: 30.0 (higher is better)
Davies-Bouldin Score: 0.851 (lower is better)
HDBSCAN Validity Index: 0.229
Composite Score: 0.307 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 49 (52.1%)
Average cluster size: 22.5 ± 13.5
Cluster size range: 9 - 36
=== Quality Scores ===
Silhouette Score: 0.325 (higher is better)
Calinski-Harabasz Score: 17.4 (higher is better)
Davies-Bouldin Score: 0.864 (lower is better)
HDBSCAN Validity Index: 0.086
Composite Score: 0.206 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 23 (24.5%)
Average cluster size: 5.5 ± 2.6
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.384 (higher is better)
Calinski-Harabasz Score: 30.0 (higher is better)
Davies-Bouldin Score: 0.851 (lower is better)
HDBSCAN Validity Index: 0.229
Composite Score: 0.307 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 26 (27.7%)
Average cluster size: 34.0 ± 24.0
Cluster size range: 10 - 58
=== Quality Scores ===
Silhouette Score: 0.260 (higher is better)
Calinski-Harabasz Score: 17.7 (higher is better)
Davies-Bouldin Score: 0.966 (lower is better)
HDBSCAN Validity Index: 0.044
Composite Score: 0.152 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 29 (30.9%)
Average cluster size: 7.2 ± 2.2
Cluster size range: 5 - 12
=== Quality Scores ===
Silhouette Score: 0.424 (higher is better)
Calinski-Harabasz Score: 32.0 (higher is better)
Davies-Bouldin Score: 0.863 (lower is better)
HDBSCAN Validity Index: 0.267
Composite Score: 0.345 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        8
Warning: Too few clusters or too much noise for some metrics
=== Clustering Quality Metrics ===
Number of clusters: 0
Noise points: 94 (100.0%)
=== Quality Scores ===

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 21 (22.3%)
Average cluster size: 18.2 ± 20.7
Cluster size range: 5 - 54
=== Quality Scores ===
Silhouette Score: 0.202 (higher is better)
Calinski-Harabasz Score: 12.2 (higher is better)
Davies-Bouldin Score: 1.086 (lower is better)
HDBSCAN Validity Index: 0.151
Composite Score: 0.176 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 21 (22.3%)
Average cluster size: 18.2 ± 20.7
Cluster size range: 5 - 54
=== Quality Scores ===
Silhouette Score: 0.202 (higher is better)
Calinski-Harabasz Score: 12.2 (higher is better)
Davies-Bouldin Score: 1.086 (lower is better)
HDBSCAN Validity Index: 0.151
Composite Score: 0.176 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 45 (47.9%)
Average cluster size: 24.5 ± 16.5
Cluster size range: 8 - 41
=== Quality Scores ===
Silhouette Score: 0.294 (higher is better)
Calinski-Harabasz Score: 14.8 (higher is better)
Davies-Bouldin Score: 0.833 (lower is better)
HDBSCAN Validity Index: 0.116
Composite Score: 0.205 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 45 (47.9%)
Average cluster size: 24.5 ± 16.5
Cluster size range: 8 - 41
=== Quality Scores ===
Silhouette Score: 0.294 (higher is better)
Calinski-Harabasz Score: 14.8 (higher is better)
Davies-Bouldin Score: 0.833 (lower is better)
HDBSCAN Validity Index: 0.116
Composite Score: 0.205 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 11
Noise points: 22 (23.4%)
Average cluster size: 6.5 ± 2.5
Cluster size range: 3 - 12
=== Quality Scores ===
Silhouette Score: 0.394 (higher is better)
Calinski-Harabasz Score: 31.7 (higher is better)
Davies-Bouldin Score: 0.894 (lower is better)
HDBSCAN Validity Index: 0.253
Composite Score: 0.323 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 45 (47.9%)
Average cluster size: 24.5 ± 16.5
Cluster size range: 8 - 41
=== Quality Scores ===
Silhouette Score: 0.294 (higher is better)
Calinski-Harabasz Score: 14.8 (higher is better)
Davies-Bouldin Score: 0.833 (lower is better)
HDBSCAN Validity Index: 0.116
Composite Score: 0.205 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 43 (45.7%)
Average cluster size: 5.7 ± 1.6
Cluster size range: 4 - 9
=== Quality Scores ===
Silhouette Score: 0.513 (higher is better)
Calinski-Harabasz Score: 42.1 (higher is better)
Davies-Bouldin Score: 0.732 (lower is better)
HDBSCAN Validity Index: 0.284
Composite Score: 0.398 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

[I 2026-02-16 08:53:06,862] Trial 25 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,874] Trial 26 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,885] Trial 27 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,896] Trial 28 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,906] Trial 29 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,915] Trial 30 finished with value: -0.32757096377033523 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,926] Trial 31 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,937] Trial 32 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,946] Trial 33 finished with value: -0.32757096377033523 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,957] Trial 34 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,966] Trial 35 finished with value: -0.32757096377033523 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,976] Trial 36 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,984] Trial 37 finished with value: -0.32757096377033523 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:06,995] Trial 38 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,000] Trial 39 finished with value: -0.253134294423983 and parameters: {'min_cluster_size': 8, 'min_samples': 7}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,007] Trial 40 finished with value: -0.32344912548559335 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,018] Trial 41 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,029] Trial 42 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,041] Trial 43 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,051] Trial 44 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,060] Trial 45 finished with value: -0.32757096377033523 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        7
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 63 (67.0%)
Average cluster size: 15.5 ± 7.5
Cluster size range: 8 - 23
=== Quality Scores ===
Silhouette Score: 0.411 (higher is better)
Calinski-Harabasz Score: 21.0 (higher is better)
Davies-Bouldin Score: 0.727 (lower is better)
HDBSCAN Validity Index: 0.095
Composite Score: 0.253 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 11
Noise points: 22 (23.4%)
Average cluster size: 6.5 ± 2.5
Cluster size range: 3 - 12
=== Quality Scores ===
Silhouette Score: 0.394 (higher is better)
Calinski-Harabasz Score: 31.7 (higher is better)
Davies-Bouldin Score: 0.894 (lower is better)
HDBSCAN Validity Index: 0.253
Composite Score: 0.323 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 14 (14.9%)
Average cluster size: 6.2 ± 3.5
Cluster size range: 3 - 16
=== Quality Scores ===
Silhouette Score: 0.382 (higher is better)
Calinski-Harabasz Score: 27.6 (higher is better)
Davies-Bouldin Score: 0.858 (lower is better)
HDBSCAN Validity Index: 0.273
Composite Score: 0.328 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2

[I 2026-02-16 08:53:07,089] Trial 46 finished with value: -0.32344912548559335 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,107] Trial 47 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,110] Trial 48 finished with value: 1.0 and parameters: {'min_cluster_size': 9, 'min_samples': 6}. Best is trial 24 with value: -0.3997717928065585.
[I 2026-02-16 08:53:07,121] Trial 49 finished with value: -0.3997717928065585 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 24 with value: -0.3997717928065585.
08:53:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Optimization completed! Best composite score: 0.3998
08:53:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Best parameters: min_cluster_size=2, min_samples=1
08:53:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Clustering with HDBSCAN (min_cluster_size=2, min_samples=1)
08:53:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Clustering complete: 19 clusters, 16 noise points (17.0%)
08:53:07 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Generating cluster names

=== Clustering Quality Metrics ===
Number of clusters: 11
Noise points: 22 (23.4%)
Average cluster size: 6.5 ± 2.5
Cluster size range: 3 - 12
=== Quality Scores ===
Silhouette Score: 0.394 (higher is better)
Calinski-Harabasz Score: 31.7 (higher is better)
Davies-Bouldin Score: 0.894 (lower is better)
HDBSCAN Validity Index: 0.253
Composite Score: 0.323 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        6
Warning: Too few clusters or too much noise for some metrics
=== Clustering Quality Metrics ===
Number of clusters: 0
Noise points: 94 (100.0%)
=== Quality Scores ===

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 19
Noise points: 16 (17.0%)
Average cluster size: 4.1 ± 1.7
Cluster size range: 2 - 7
=== Quality Scores ===
Silhouette Score: 0.434 (higher is better)
Calinski-Harabasz Score: 30.1 (higher is better)
Davies-Bouldin Score: 0.776 (lower is better)
HDBSCAN Validity Index: 0.366
Composite Score: 0.400 (higher is better)

08:53:11 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 12: Enterprise AI Implementation and Scaling
08:53:11 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Building a ‘Second Brain’ for Marketing Using AI Agents (Marketing, Knowledge Management, Agents, Enterprise AI, Labor Markets And Productivity, Automation)
Stop Guessing Thread Pool Sizes: How to Plug AI into Spring Batch Safely (Spring Batch, Software Engineering, Concurrency, Safety And Alignment, Enterprise AI, Automation, Java)
The Hard Truth About Machine Learning for Amazon FBA Sellers (Amazon FBA, Supply Chain Optimization, Inventory Management, Forecasting, Machine Learning, Enterprise AI, Computer Vision)
OpenAI and Cisco Back Standards to Scale Agentic AI (Agents, Governance, Adoption and Spending, OpenAI, Anthropic, Cisco, Enterprise AI)
Expensively Quadratic: The LLM Agent Cost Curve (LLM Costs, Adoption and Spending, Context Window, Agents, Language Models, Coding Assistants)
SPAR rolls out AI loss-prevention tech via Veesion partnership (Retail, Loss Prevention, Veesion, Computer Vision, Security, Privacy And Surveillance, Enterprise AI)
Deep-tech startup Atsuya named among top 20 in AI for All challenge (Agents, Automation, Enterprise AI, Sustainability, IoT, Manufacturing, Energy)
08:53:11 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:14 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 8: AI Stock Market Trends and Investments
08:53:14 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | AMD Takes on Nvidia in India With Expanded Tata AI Partnership ()
Alphabet Just Gave Nvidia and Broadcom Investors 185 Billion Reasons to Cheer (Adoption and Spending, AI Infrastructure, Alphabet, Nvidia, Broadcom, Semiconductor Chips, Finance)
The AI Stock That Could Turn the Tables on the "Magnificent Seven" (Broadcom, Semiconductor Chips, Networking Hardware, AI Compute, Data Centers, Finance, Enterprise AI)
Should You Forget Palantir and Buy 2 OtherArtificial Intelligence(AI) Stocks Right Now? (Valuation, Nvidia, AMD, Palantir, Semiconductor Chips, GPUs, AI Compute)
Billionaire Bill Ackman Buys 2 BrilliantArtificial Intelligence(AI) Stocks -- They Could Soar in the Next Year, According to Wall Street (Amazon, Meta, Finance, Stocks, Robotics, Cloud Computing, Automation)
1 Unstoppable Stock to Buy Before It Joins Nvidia, Apple, and Alphabet in the $3 Trillion Club (TSMC, Semiconductors, Manufacturing, Market Cap, Finance, AI Compute, Taiwan)
'Big Short' Investor Michael Burry Targets Palantir Over 'Covert Smear' Claims, Warns Of Over 50% Stock Collapse (Palantir, Short Selling, Valuation Bubble, Ethics, Governance, NHS, Stocks)
08:53:14 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 6: ByteDance Addresses Hollywood AI Copyright Concerns
08:53:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood (ByteDance, Seedance 2.0 (Artificial Intelligence Co), Copyrights and Copyright Violations, Hollywood, Video Generation, Deepfakes, Labor Markets And Productivity)
After spooking Hollywood, ByteDance will tweak safeguards on new AI model (ByteDance, Seedance, Copyright, Intellectual Property, Hollywood, Deepfakes, Legal Issues)
ByteDance promises to tighten up its new AI video generator after viral Cruise vs. Pitt clip (ByteDance, Deepfakes, Copyright, Intellectual Property, Content Moderation, Hollywood, Legal Issues)
Following Disney, Paramount sent a cease-and-desist letter to ByteDance, alleging its AI-generated Seedance videos and Seedream images infringed Paramount's IP (ByteDance, Intellectual Property, Legal Issues, TV And Film And Movies, Generative Video, Hollywood, Ethics)
ByteDance says it "respects IP rights and we have heard the concerns regarding Seedance" and it plans to "strengthen" safeguards, after Disney's legal threats (Osmond Chia/BBC) (ByteDance, Disney, Intellectual Property, Copyright, Licensing, Legal Issues, TV And Film And Movies)
TikTok creator ByteDance vows to curb AI video tool after Disney threat (Copyright, Intellectual Property, Legal Issues, Video Generation, ByteDance, Disney, Film Industry)
08:53:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:21 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 2: Advances in AI Models and Infrastructure
08:53:21 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | From DSP to AI: Evolving Approaches in Audio Processing (Audio Processing, Signal Processing, Machine Learning, DSP, Speech Recognition And Synthesis, AR/VR)
Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release ()
Prompts Are Overrated. Here’s How I Built a Zero-Copy Fog AI Node Without Python (Edge Computing, FogAI, DeepSeek, Infrastructure, Robotics, Smart Cities, Manufacturing)
Alibaba debuts Qwen 3.5, adding "visual agentic capabilities" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters) (Alibaba, Qwen, Language Models, Agents, China, Enterprise AI, Product Launch)
Qwen3.5: Towards Native Multimodal Agents (Multimodal AI, Language Models, Qwen, Alibaba Cloud, Open Source, Agents, Computer Vision)
Rolling your own serverless OCR in 40 lines of code (OCR, DeepSeek, Modal, Serverless, Software Development, Open Source, Computer Vision)
08:53:21 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 18: OpenAI Leadership, Staffing, and Safety
08:53:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | The career rise of OpenAI's billionaire CEO, Sam Altman (OpenAI, Sam Altman, Infrastructure, Hardware, Sora, Legal Issues, Investments)
The art of the squeal: What we can learn from the flood of AI resignation letters (AI Safety, Safety And Alignment, OpenAI, Anthropic, Artificial General Intelligence, Ethics, Jobs And Careers)
The Guardian view on AI: safety staff departures raise worries about industry pursuing profit at all costs | Editorial (AI Safety, Ethics, OpenAI, Anthropic, Policy And Regulation, Safety And Alignment, Governance)
OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project ()
She earns Rs 2 crore yearly, but OpenAI employee won't say YES to marriage without this non-negotiable rule (Prenuptial Agreements, Equity Compensation, Finance, Legal Issues, OpenAI, Internet of Things, India)
08:53:24 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 17: Anthropic Business Growth and Strategic Risks
08:53:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts ()
Dario Amodei says Anthropic struggles to balance 'incredible commercial pressure' with its 'safety stuff' (Anthropic, AI Safety, Revenue Growth, Funding, Ethics, Venture Capital, Safety And Alignment)
NASA trials AI-powered driving of Mars rover (NASA, Anthropic, OpenAI, DeepSeek, Autonomous Vehicles, Ethics, Venture Capital)
All the important news from the ongoing India AI Impact Summit (India, Venture Capital, Anthropic, OpenAI, Blackstone, IT Services, Gen AI)
Anthropic CEO Dario Amodei Warns One Wrong AI Bet Could Bankrupt The Company: 'No Hedge On Earth That Could Stop...' (Adoption and Spending, AI Infrastructure, Anthropic, Dario Amodei, Valuation Bubble, Hyperscalers, Finance)
08:53:28 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:32 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 15: The Evolving Generative AI Landscape
08:53:32 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | I Vibe Coded an App With 3 Popular Chatbots. The Real Winner Is a Good Prompt (Coding Assistants, Prompt Engineering, Software Development, Gemini, Claude, ChatGPT, Gen AI)
WTF is Markdown for AI agents? (Markdown, Cloudflare, Data Formats, Media, Agents, Automation, Gen AI)
Ars Technica Pulls Article With AI Fabricated Quotes About AI Generated Article (Ars Technica, Journalism, Ethics, Editorial Standards, ChatGPT, Gen AI, Authors And Writing)
Real Design Trends are Dying Under the Weight of Recursive AI Echoes (Model Collapse, Aesthetics, Art And Design, Search Optimization, Generative AI, Society And Culture)
AI buzzwords decoded: What terms like LLMs, generative AI, guardrails mean (Language Models, Gen AI, Guardrails, Safety And Alignment, Healthcare, Drug Discovery, Bias And Fairness)
08:53:32 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:35 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 10: India Hosts AI Impact Summit
08:53:35 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | India can influence global AI regulations, says industry expert (Governance, Policy And Regulation, Data Governance, India, Talent, Agents, Safety And Alignment)
Top Putin aide Maxim Oreshkin to lead Russian delegation for AI Impact Summit in New Delhi (Geopolitics, Sovereign AI, Governance, Russia, India, BRICS, AI Impact Summit)
AI summit in India kicks off with focus on ‘welfare for all’ (India, Economic Impact, Infrastructure, Adoption and Spending, Labor Markets And Productivity, AI Summit, Hyperscalers)
India AI Impact Summit 2026: PM Modi to inaugurate expo on Monday (India, Foundation Models, AI Summit, Language Models, Governance, Economics, Politics)
Top Putin aide to lead Russian delegation for AI Impact Summit in New Delhi (Geopolitics, Governance, Russia, India, BRICS, Military AI, Policy And Regulation)
08:53:35 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 3: OpenAI acquires OpenClaw for AI agents
08:53:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | OpenAI has hired the developer behind AI agent OpenClaw (OpenAI, Peter Steinberger, OpenClaw, Open Source, Virtual Assistants, Agents, Meta)
Peter Steinberger joins OpenAI (OpenAI, Peter Steinberger, OpenClaw, Agents, Virtual Assistants, Open Source, Sam Altman)
In a podcast, OpenClaw creator Peter Steinberger describes his phone calls with Mark Zuckerberg and Sam Altman, and says he had been contacted by “every big VC” (Acquisitions, OpenClaw, OpenAI, Open Source, Agents, Virtual Assistants, Jobs And Careers)
Indirect prompt injection in AI agents is terrifying and I don't think enough people understand this (Cybersecurity, Prompt Injection, Vulnerabilities, Safety And Alignment, Agents, Sandboxing)
Sam Altman officially confirms that OpenAI has acquired OpenClaw; Peter Steinberger to lead personal agents (Mergers and Acquisitions, OpenClaw, OpenAI, Agents, Enterprise AI, Open Source, Virtual Assistants)
08:53:38 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:42 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 14: AI's Impact on the Modern Workforce
08:53:42 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | KPMG partner fined over using AI to pass AI test (KPMG, Accounting, Professional Integrity, Ethics, Internal Exams, Testing, Enterprise AI)
Demand for AI-related skills is up 109% since last year. What that means for you (Upwork, Skills, Labor Markets And Productivity, Jobs And Careers, Adoption and Spending, Education)
I started at Microsoft as an executive assistant and pivoted to an AI role. I don't regret my English degree. (Jobs And Careers, Career Pivot, Prompt Engineering, Microsoft, Labor Markets And Productivity, Society And Culture)
Analysis: US productivity rose by ~2.7% in 2025, nearly doubling the 1.4% annual average over a decade, as AI-exposed sectors cooled their entry-level hiring (Erik Brynjolfsson/Financial Times) (Economics, Productivity, Labor Markets And Productivity, Business Performance, Macroeconomics, Adoption and Spending)
08:53:42 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:46 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 9: Investor Caution and AI Market Volatility
08:53:46 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Fractal Analytics’ muted IPO debut signals persistent AI fears in India (Fractal Analytics, IPOs, India, Stocks, Finance, Enterprise AI, Valuation Bubble)
Fund Beating 99% of Peers Sees Few Software Firms Surviving AI (Software Industry, Investment Funds, Semiconductors, Data Centers, Coding, Automation, Economics)
European Stocks Rise. AI Trading Frenzy Takes a Breather for Presidents Day (Stock Markets, Finance, Europe, Economics, Investing, Equity Markets)
Why the ‘AI scare trade’ might not be done ()
08:53:46 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 13: AI Adoption and Literacy Initiatives
08:53:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Business schools search for clear AI guidelines (Business Schools, Education, Academic Integrity, Ethics, Digital Education Council, Adoption and Spending, Gen AI)
Acadia University opens up AI literacy course to public for free (Education, Literacy, Adoption and Spending, Society And Culture, ChatGPT, Claude)
Adopt AI for electronic transmission of poll results, don urges INEC (Elections, Politics, Nigeria, Governance, Automation, Policy And Regulation)
08:53:49 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 4: Anthropic Claude AI Developments and Disputes
08:53:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Anthropic tries to hide Claude's AI actions. Devs hate it (Anthropic, Claude Code, Coding Assistants, Software Development, Transparency, Agents, Products)
Amazon has a new creative agent to help your business build its own ads (Amazon, AWS, Advertising, Agents, Claude, Enterprise AI, Automation)
Pentagon threatens to cut off Anthropic in AI safeguards dispute (Anthropic, Pentagon, Defense, Military, Ethics, Safety And Alignment, Claude)
08:53:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:56 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 1: Developments in Robotics and AI
08:53:56 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | I hate my AI pet with every fiber of my being (Casio, Social Robots, Consumer Electronics, Japan, Hardware, Products, Society And Culture)
Will Chinese ‘involution’ do to robots and AI what it’s already done to EVs? ()
Video: China’s humanoid robot masters stunning sword dance, shows perfect control (Humanoid Robots, Embodied AI, Hardware, Automation, Manufacturing, Robotera, China)
08:53:56 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:53:59 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 16: Ethical and Regulatory Challenges in Healthcare AI
08:53:59 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Forcing AI Makers To Legally Carve Out Mental Health Capabilities And Use LLM Therapist Apps Instead (Mental Health, Healthcare AI, Ethics, Policy And Regulation, Safety And Alignment, Language Models, Legal Issues)
AI was supposed to be used to cure cancer…. (Oncology, Healthcare, Deepfakes, Ethics, Open Source, Video Editing, Computer Vision)
08:53:59 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:54:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 11: Emerging Technology and Investment News
08:54:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Living neurons integrated into modern AI processing, claims SF startup — biological computing power used to boost computer vision, generative video, and more (Biological Computing, Neuromorphic Computing, Brain-Computer Interfaces, Hardware, Funding, Computer Vision, Generative Video)
Lux Capital, Flutterwave CEO Invest in Nigerian Drone Maker ()
08:54:02 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:54:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 7: Simpsons Actors Oppose AI Voice Replacement
08:54:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | ‘The Simpsons’ Star, 68, Fears Heartless Replacement on Show (Voice Acting, Disney, OpenAI, Entertainment, TV And Film And Movies, Speech Recognition And Synthesis, Society And Culture)
‘The Simpsons’ Bart Voice Actress Tells AI “Eat My Shorts,” Wants Human Successor: “AI Has No Heart” (Voice Acting, Intellectual Property, Copyright, Disney, OpenAI, Entertainment, Society And Culture)
08:54:06 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:54:09 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 5: Accusations of AI voice copying
08:54:09 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Former NPR Host Accuses Google Of Copying His Voice For AI Offering (Google, NotebookLM, Intellectual Property, Legal Issues, Speech Recognition And Synthesis, Deepfakes, Ethics)
El Grande Americano calls out ‘Original’ Americano over use of AI (Wrestling, Entertainment, Speech Recognition And Synthesis, Cultural Identity, Ethics, Society And Culture, Deepfakes)
08:54:09 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 0: Energy Demands of AI Data Centers
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers (Energy Infrastructure, Data Centers, Policy And Regulation, Big Tech, Infrastructure, Politics, AI Compute)
Eric Schmidt Says 'We're Running Out Of Electricity,' Urges Space Data Centers — SpaceX CEO Elon Musk Quips: 'If Only There Were A Company' (Data Centers, Energy, SpaceX, xAI, Google, Infrastructure, Elon Musk)
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO |

08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Clustering pipeline complete
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Inserting 94 articles with topics into database...
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Successfully inserted 94/94 articles with topics

================================================================================
⏱️  Total execution time: 231.59s
📊 Final result:
✅ Step 6 cluster_topics completed successfully! Organized 94 articles into topic clusters.

In [28]:
# candidates for upgrading model, in some cases to gpt-5.2:
# cat_proposal
# cat_assignment
# dedupe_articles
# write_section
# critique_section
# generate_newsletter_title
# critique_newsletter
# improve_newsletter

In [29]:
# User prompt to run workflow
# user_prompt = "Run step 7, select section topics"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("select_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Category proposal
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=TopicCategoryList, reasoning_effort=medium
08:54:13 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: # Response Rules

- Scope: use only the supplied bullets—no external facts.
- Topic title length: ≤ 5 words, Title Case.
- Count: 10 ≤ topics ≤ 30; if fewer qualify, return all.
- Priority: rank by(impact × log frequency); break ties by higher Rating, then alphabetical.
- Redundancy: merge or drop overlapping stories.
- Tone: concise, neutral; no extra prose.
- Privacy: never reveal chain-of-thought.
- Output: one valid JSON object matching the schema supplied(double quotes only)

Scoring Heuristics(internal - do not output scores)
1. Repeated entity or theme
2. Major technological breakthrough
3. Significant biz deal / funding
4. Key product launch or update
5. Important benchmark or research finding
6. Major policy or regulatory action
7. Significant statement by influential figure

Reasoning Steps(think silently)
1. Parse each item; extract entities/themes.
2. Count their recurrence.
3. Weigh impact via the heuristics.
4. Select top 10-30 non-overlapping topics.
5. Draft ≤ 5-word titles.
6. Emit a JSON object with a list of strings using the supplied schema. *(Expose only Step 6.)*

Think carefully and output categories for this list of stories
Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood - The New York Times

Rating: 10.5

Topics: ByteDance, Seedance 2.0 (Artificial Intelligence Co), Copyrights and Copyright Violations, Hollywood, Video Generation, Deepfakes, Labor Markets And Productivity

A 15-second clip created by an artificial intelligence tool owned by the Chinese technology company ByteDance appears more cinematic than anything so far.

- ByteDance's Seedance 2.0 AI tool created a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, sparking alarm in Hollywood due to its professional-grade cinematic quality. - Disney and the Motion Picture Association have demanded ByteDance cease operations, alleging the tool was trained on a 'pirated library' of copyrighted characters and films. - While some industry professionals fear imminent job displacement, others argue that AI remains an 'averaging machine' incapable of producing poignant or provocative human-level artistry.
---

Business schools search for clear AI guidelines - Financial Times

Rating: 9.4

Topics: Business Schools, Education, Academic Integrity, Ethics, Digital Education Council, Adoption and Spending, Gen AI

Attempts to establish shared standards are lagging behind adoption of the technology

- Business schools are rapidly integrating AI into curricula and operations, with over 700 AI-focused programs identified in the US, yet institutions lack a standardized roadmap or clear benchmarks for implementation. - New initiatives like the Digital Education Council’s benchmarking framework aim to measure AI capability and ethics, while schools like Cambridge and HEC pilot interactive AI teaching cases and automated grading assistants. - Concerns persist regarding academic integrity and the offloading of critical thinking, leading deans to emphasize transparency and the need for ethical guidelines to prevent the disintermediation of traditional education.
---

Are Anthropic’s new AI work tools game-changing for professionals? - Financial Times

Rating: 8.7

Topics: Anthropic, Claude, Workplace Tools, LegalTech, Consulting, Enterprise AI, Productivity

Adaptable plug-ins must compete with bespoke products already used by lawyers and consultants

- Anthropic is launching new AI work tools and adaptable plug-ins aimed at professional sectors. - The new tools are designed to compete with specialized software currently used by legal and consulting professionals. - The market impact will be determined by the ability of these general-purpose AI tools to replace established, bespoke industry products.
---

KPMG partner fined over using AI to pass AI test - Financial Times

Rating: 8.0

Topics: KPMG, Accounting, Professional Integrity, Ethics, Internal Exams, Testing, Enterprise AI

Accounting firm has caught several staff members in recent months using the technology for internal exams

- A KPMG partner was fined after being caught using artificial intelligence to complete an internal exam designed to test AI competency. - The incident is part of a broader trend within the accounting firm, which has identified several staff members using AI technology to bypass internal testing requirements in recent months. - The case underscores the growing regulatory and ethical challenges professional services firms face in ensuring staff integrity as they adopt and train employees on generative AI tools.
---

OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary/Bloomberg) - Bloomberg

Rating: 8.3

no content
---

AMD Takes on Nvidia in India With Expanded Tata AI Partnership - Bloomberg

Rating: 6.7

- no content
---

Anthropic tries to hide Claude's AI actions. Devs hate it - The Register

Rating: 7.3

Topics: Anthropic, Claude Code, Coding Assistants, Software Development, Transparency, Agents, Products

: The software doesn't show what files it's working on

- Anthropic updated its Claude Code AI tool to hide specific file names during operations, a move intended to simplify the UI but criticized by developers for reducing transparency. - Developers argue that seeing file paths is essential for catching context errors early, ensuring security, and managing costs by interrupting incorrect agentic actions. - Despite significant user pushback, Anthropic leadership maintains the condensed view as the default, offering a modified verbose mode as a compromise for those requiring detailed activity logs.
---

After spooking Hollywood, ByteDance will tweak safeguards on new AI model - The Verge

Rating: 8.2

Topics: ByteDance, Seedance, Copyright, Intellectual Property, Hollywood, Deepfakes, Legal Issues

Its easier to apologise than ask permission.

- ByteDance is updating safeguards for its Seedance 2.0 AI video generator following copyright infringement allegations from Disney, Paramount, and Hollywood trade groups. - Major studios issued cease and desist letters after the model produced hyperrealistic videos featuring protected characters and the likenesses of actors like Tom Cruise and Brad Pitt. - SAG-AFTRA and the MPA condemned the tool for violating intellectual property laws and threatening the livelihoods of human talent at a massive scale.
---

How I Built a Fail-Safe Legal AI Engine for Singapore Laws Using Triple-Model RAG - Hacker Noon

Rating: 6.5

Topics: LegalTech, Retrieval Augmented Generation, Singapore, Gemini, Open Source, Language Models, Products

- Developer Aditya Prasad created a RAG-based legal AI engine for Singapore laws featuring a triple-model failover architecture using Gemini, Llama 3, and Groq to ensure 24/7 reliability. - The technical stack utilizes the BGE-M3 embedding model and FAISS to index over 30,000 pages of government PDFs, prioritizing a high-precision research UI over standard chat interfaces. - To mitigate hallucinations, the system enforces a 0.5 confidence threshold for document retrieval and has been open-sourced to support future LegalTech innovation and autonomous research.
---

From DSP to AI: Evolving Approaches in Audio Processing - Hacker Noon

Rating: 6.5

Topics: Audio Processing, Signal Processing, Machine Learning, DSP, Speech Recognition And Synthesis, AR/VR

How DSP and machine learning converge to power real-time, reliable, and physically grounded audio AI systems.

- Modern audio intelligence is transitioning from deterministic Digital Signal Processing (DSP) to hybrid systems that integrate machine learning with classical signal processing to maintain physical grounding and real-time stability. - Hybrid approaches are being deployed in noise suppression, spatial audio for AR/VR, and source separation, where neural networks handle complex inference while DSP components ensure phase consistency and temporal resolution. - The field is moving toward Differentiable Digital Signal Processing (DDSP) and context-aware systems that balance computational efficiency with human-aligned perceptual evaluation in safety-critical and consumer applications.
---

Anthropic Boosts India AI Push Via Flag Airline, Cognizant Pacts - Bloomberg

Rating: 5.9

- no content
---

The career rise of OpenAI's billionaire CEO, Sam Altman - Business Insider

Rating: 9.7

Topics: OpenAI, Sam Altman, Infrastructure, Hardware, Sora, Legal Issues, Investments

OpenAI CEO Sam Altman helped usher in the AI age. Now, he's doing everything he can to keep OpenAI ahead.

- OpenAI restructured into a public benefit corporation in 2025 and expanded its product line to include the Atlas browser, Sora video app, and an upcoming AI consumer device designed with Jony Ive. - Altman spearheaded 'Stargate,' a $500 billion US AI infrastructure initiative in collaboration with Oracle, SoftBank, and the Trump administration, while preparing for a 2026 trial against Elon Musk. - Despite lacking equity in OpenAI, Altman maintains billionaire status through investments in firms like Stripe and Helion and has committed to the Giving Pledge with his husband, Oliver Mulherin.
---

The scientist using AI to hunt for antibiotics just about everywhere - Technology Review

Rating: 7.8

Topics: Drug Discovery, Bioengineering, Antibiotics, Biotechnology and health, Peptides, Healthcare, Gen AI

César de la Fuente is on a mission to combat antimicrobial resistance by looking at nature’s own solutions.

- Bioengineer C  sar de la Fuente is using AI for molecular de-extinction, mining genetic data from sources like venom and extinct species to discover antimicrobial peptides (AMPs). - These peptides provide a multimodal attack against pathogens, addressing the high costs and low returns of traditional antibiotic discovery. - The team is developing ApexOracle, a multimodal AI model to predict peptide efficacy, following successful animal trials against WHO-priority bacteria.
---

The art of the squeal: What we can learn from the flood of AI resignation letters - Business Insider

Rating: 9.2

Topics: AI Safety, Safety And Alignment, OpenAI, Anthropic, Artificial General Intelligence, Ethics, Jobs And Careers

What we can learn from the flood of "why I quit" letters from researchers at Anthropic, OpenAI, and xAI.

- A surge of public resignation letters from top researchers at OpenAI, Anthropic, and xAI has emerged as a new industry trend, highlighting internal conflicts over AI safety, alignment, and the rapid pace of development toward AGI. - Departures are often driven by the tension between safety-focused research and commercial pressures to ship consumer products, exemplified by OpenAI's move toward ad-supported models and the subsequent resignation of researchers like Zoë Hitzig. - Former safety leaders like Jan Leike and Steven Adler warn that safety processes have "taken a backseat to shiny products," expressing fears that the industry is sprinting toward a powerful technology it may not be able to control or govern ethically.
---

Alibaba Unveils Major AI Model Upgrade Ahead of DeepSeek Release - Bloomberg

Rating: 5.8

- no content
---

MiniMax Shares Surge 25% as Optimism Over Chinese AI Firms Grows - Bloomberg

Rating: 5.6

- no content
---

Ray Wang on How AI Is Causing DRAM Prices to Surge - Bloomberg

Rating: 5.5

- no content
---

Living neurons integrated into modern AI processing, claims SF startup — biological computing power used to boost computer vision, generative video, and more - Tom's Hardware

Rating: 7.6

Topics: Biological Computing, Neuromorphic Computing, Brain-Computer Interfaces, Hardware, Funding, Computer Vision, Generative Video

The Biological Computing Company (TBC) has just raised $25m, despite its admitted decades-long plans for real-time compute implementation.

- San Francisco startup The Biological Computing Company (TBC) raised $25 million to develop a platform that integrates living neurons with AI models to accelerate tasks like computer vision and generative video. - TBC claims its biological computing approach can process foundational AI models five times faster than silicon-based chips while consuming less power and providing greater accuracy. - The technology encodes data into neurons and decodes the resulting activity into AI-compatible representations, though founders acknowledge a 10-to-20-year timeline for full real-time compute integration.
---

ByteDance promises to tighten up its new AI video generator after viral Cruise vs. Pitt clip - Engadget

Rating: 6.6

Topics: ByteDance, Deepfakes, Copyright, Intellectual Property, Content Moderation, Hollywood, Legal Issues

The announcement comes after a cease-and-desist letter from Disney.

- ByteDance is tightening restrictions on its AI video generator following the viral spread of a deepfake video featuring actors Tom Cruise and Brad Pitt. - The policy change was prompted by a cease-and-desist letter from Disney, highlighting growing legal and copyright concerns regarding the unauthorized use of celebrity likenesses. - The move reflects increasing pressure on tech companies to implement robust content moderation and prevent the misuse of synthetic media in AI development.
---

Prompts Are Overrated. Here’s How I Built a Zero-Copy Fog AI Node Without Python - Hacker Noon

Rating: 7.2

Topics: Edge Computing, FogAI, DeepSeek, Infrastructure, Robotics, Smart Cities, Manufacturing

FogAI is a distributed inference platform that actually survives when the internet goes dark.

- FogAI is a distributed inference platform developed using a Kotlin-C++ hybrid to overcome Python’s Global Interpreter Lock (GIL) and memory overhead in edge computing environments. - The architecture features a zero-copy pipeline and dual-engine core (Alibaba MNN and ONNX Runtime), achieving 50 tokens/sec on-device for DeepSeek r1 1.5B and handling over 47,000 requests per second. - Built for Industry 4.0, the system adheres to the ISA-95 standard to ensure offline resilience and autonomous decision-making for robotics and smart cities when cloud connectivity is unavailable.
---

Dario Amodei says Anthropic struggles to balance 'incredible commercial pressure' with its 'safety stuff' - Business Insider

Rating: 9.1

Topics: Anthropic, AI Safety, Revenue Growth, Funding, Ethics, Venture Capital, Safety And Alignment

Anthropic CEO Dario Amodei says he's trying to keep Anthropic growing at a 10x pace while holding the line on safety.

- Anthropic CEO Dario Amodei reports "incredible commercial pressure" to maintain a 10x annual revenue growth rate while upholding the company's core mission of AI safety. - The company recently announced a $30 billion Series G funding round at a $380 billion valuation, reaching a $14 billion run-rate revenue less than three years after its first dollar earned. - Internal tensions over mission drift have surfaced, evidenced by the resignation of safety researcher Mrinank Sharma, who cited the difficulty of prioritizing values over economic survival during rapid expansion.
---

Fractal Analytics’ muted IPO debut signals persistent AI fears in India - TechCrunch

Rating: 6.6

Topics: Fractal Analytics, IPOs, India, Stocks, Finance, Enterprise AI, Valuation Bubble

As India's first AI company to IPO, Fractal Analytics didn't have a stellar first day on the public markets, as enthusiasm for the technology collided with jittery investors in the wake of a sell-off in Indian software stocks.

- Fractal Analytics, India's first AI unicorn, debuted on the public market with a 7% drop from its issue price, resulting in a $1.6 billion market capitalization that sits below its previous private valuation of $2.4 billion. - The company reported a 26% revenue increase to $304.8 million and a shift to profitability for the fiscal year ending March 2025, despite having to reduce its IPO size by 40% due to investor caution and a broader sell-off in Indian software stocks. - Proceeds from the offering are earmarked for debt repayment, R&D investments in the Fractal Alpha unit, and potential acquisitions as India attempts to establish itself as a global AI development hub.
---

Former NPR Host Accuses Google Of Copying His Voice For AI Offering - Gizmodo

Rating: 6.2

Topics: Google, NotebookLM, Intellectual Property, Legal Issues, Speech Recognition And Synthesis, Deepfakes, Ethics

Google is sued over the AI podcast generation in NotebookLM.

- Former NPR host David Greene has sued Google, alleging the company's NotebookLM AI voice was trained on his voice without authorization or compensation. - While an AI forensic firm found a 53-60% confidence match to Greene's voice, Google maintains the model was based on a hired professional actor. - The legal action follows similar high-profile likeness disputes, highlighting the lack of regulatory guardrails for using professional identities in generative AI training.
---

Trump's trade advisor says Big Tech must 'internalize the cost' of AI data centers - Business Insider

Rating: 9.6

Topics: Energy Infrastructure, Data Centers, Policy And Regulation, Big Tech, Infrastructure, Politics, AI Compute

Peter Navarro says the White House may force Big Tech to cover electricity and grid costs tied to AI data centers.

- White House trade advisor Peter Navarro and President Trump mandated that Big Tech must "internalize" all electricity and grid costs for AI data centers to protect taxpayers from rising utility rates. - The directive follows a surge in utility rate hike requests totaling $31 billion, fueled by massive infrastructure spending from companies like Meta and Apple to support AI development. - Major AI players including Anthropic and Microsoft have already pledged to cover 100% of their grid upgrade costs to maintain US competitiveness against China while minimizing the burden on local communities.
---

Fund Beating 99% of Peers Sees Few Software Firms Surviving AI - Yahoo

Rating: 8.8

Topics: Software Industry, Investment Funds, Semiconductors, Data Centers, Coding, Automation, Economics

“We think application software faces an existential threat from AI,” said Evans, whose $12 billion global technology fund beat 99% of peers over one year and 97% over five.  An exchange-traded fund tracking the US software sector is down 22%, a sharp contrast to semiconductor stocks that have soared as AI spurs computing demand.  Application software, which helps users perform tasks such as writing documents and managing payrolls, looks particularly at risk, according to Evans.

- Polar Capital's Nick Evans warns that application software faces an "existential threat" from AI, leading his top-performing fund to divest from firms like Adobe and SAP in favor of semiconductors and data center infrastructure. - AI coding advancements allow clients to build internal tools and enable startups to replicate existing software, significantly increasing competition for established software companies. - The sector faces financial risks including potential cash-flow squeezes as declining stock valuations may force companies to replace equity-based compensation with cash to retain talent.
---

Alibaba debuts Qwen 3.5, adding "visual agentic capabilities" to independently execute tasks, and says it is 60% cheaper to use and 8x better at large workloads (Eduardo Baptista/Reuters) - Reuters

Rating: 9.7

Topics: Alibaba, Qwen, Language Models, Agents, China, Enterprise AI, Product Launch


▶ Starting Step 7: select_sections

08:54:50 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: items=['ByteDance Seedance Hollywood Copyright Dispute', 'Sam Altman OpenAI Infrastructure Plans', 'Alibaba Qwen 3.5 Agentic Launch', 'Trump Data Center Cost Mandate', 'Business School AI Implementation Standards', 'AI Safety Researcher Resignation Trend', 'Anthropic Commercial Growth Safety Tension', 'India AI Impact Summit 2026', 'OpenAI OpenClaw Agent Acquisition', 'Software Industry AI Existential Threat', 'Anthropic Professional Workplace Tools', 'Big Tech AI Valuation Pullback', 'OpenAI GPT-4o Retirement Backlash', 'Agentic AI Governance Standards', 'KPMG AI Exam Integrity Fine', 'AI Antibiotic Drug Discovery Breakthrough', 'Biological Computing Neuron Integration', 'Anthropic Claude Code Transparency Issues', 'NASA Autonomous Mars Rover Trial', 'FogAI Edge Computing Resilience', 'Eric Schmidt Space Data Centers', 'Alphabet AI Infrastructure Spending Surge', 'Snowflake Data Pipe Warning', 'Fractal Analytics India IPO Debut', 'Legal AI Singapore RAG Engine', 'Audio Processing AI Evolution', 'Google NotebookLM Voice Lawsuit', 'Google AI Overviews Health Risks', 'AI Skills Demand Growth', 'Indirect Prompt Injection Security Risks']
08:54:50 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Cleaning up initial categories: ['OpenAI GPT-4o Retirement Backlash', 'Trump Data Center Cost Mandate', 'Software Industry AI Existential Threat', 'Other', 'Anthropic Professional Workplace Tools', 'Eric Schmidt Space Data Centers', 'Anthropic Claude Code Transparency Issues', 'ByteDance Addresses Hollywood AI Copyright Concerns', 'Snowflake Data Pipe Warning', 'Alibaba Qwen 3.5 Agentic Launch', 'Accusations of AI voice copying', 'Simpsons Actors Oppose AI Voice Replacement', 'Enterprise AI Implementation and Scaling', 'Energy Demands of AI Data Centers', 'Big Tech AI Valuation Pullback', 'Biological Computing Neuron Integration', 'The Evolving Generative AI Landscape', 'Anthropic Commercial Growth Safety Tension', 'KPMG AI Exam Integrity Fine', 'Business School AI Implementation Standards', 'AI Safety Researcher Resignation Trend', 'Indirect Prompt Injection Security Risks', 'Agentic AI Governance Standards', 'NASA Autonomous Mars Rover Trial', 'India AI Impact Summit 2026', 'Alphabet AI Infrastructure Spending Surge', 'Ethical and Regulatory Challenges in Healthcare AI', 'Advances in AI Models and Infrastructure', 'AI Antibiotic Drug Discovery Breakthrough', 'FogAI Edge Computing Resilience', 'Google AI Overviews Health Risks', 'OpenAI acquires OpenClaw for AI agents', 'Sam Altman OpenAI Infrastructure Plans', 'OpenAI Leadership, Staffing, and Safety', 'OpenAI OpenClaw Agent Acquisition', 'AI Adoption and Literacy Initiatives', 'Emerging Technology and Investment News', 'AI Stock Market Trends and Investments', 'Google NotebookLM Voice Lawsuit', 'Anthropic Business Growth and Strategic Risks', "AI's Impact on the Modern Workforce", 'Fractal Analytics India IPO Debut', 'AI Skills Demand Growth', 'Anthropic Claude AI Developments and Disputes', 'ByteDance Seedance Hollywood Copyright Dispute', 'Investor Caution and AI Market Volatility', 'Legal AI Singapore RAG Engine', 'India Hosts AI Impact Summit', 'Audio Processing AI Evolution', 'Developments in Robotics and AI']
08:54:50 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=TopicCategoryList, reasoning_effort=low
08:54:50 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: Edit this list of technology-focused topics.

Reasoning Steps(think silently)
1. Parse input lines.
2. Apply merge / split logic.
3. Simplify and clarify, apply style guide.
4. Finalize ≤ 5-word titles.
5. Build JSON array (unique, title-case).
6. Output exactly the JSON schema—nothing else.

Think careful and output the cleaned list for these topics:
OpenAI GPT-4o Retirement Backlash
Trump Data Center Cost Mandate
Software Industry AI Existential Threat
Other
Anthropic Professional Workplace Tools
Eric Schmidt Space Data Centers
Anthropic Claude Code Transparency Issues
ByteDance Addresses Hollywood AI Copyright Concerns
Snowflake Data Pipe Warning
Alibaba Qwen 3.5 Agentic Launch
Accusations of AI voice copying
Simpsons Actors Oppose AI Voice Replacement
Enterprise AI Implementation and Scaling
Energy Demands of AI Data Centers
Big Tech AI Valuation Pullback
Biological Computing Neuron Integration
The Evolving Generative AI Landscape
Anthropic Commercial Growth Safety Tension
KPMG AI Exam Integrity Fine
Business School AI Implementation Standards
AI Safety Researcher Resignation Trend
Indirect Prompt Injection Security Risks
Agentic AI Governance Standards
NASA Autonomous Mars Rover Trial
India AI Impact Summit 2026
Alphabet AI Infrastructure Spending Surge
Ethical and Regulatory Challenges in Healthcare AI
Advances in AI Models and Infrastructure
AI Antibiotic Drug Discovery Breakthrough
FogAI Edge Computing Resilience
Google AI Overviews Health Risks
OpenAI acquires OpenClaw for AI agents
Sam Altman OpenAI Infrastructure Plans
OpenAI Leadership, Staffing, and Safety
OpenAI OpenClaw Agent Acquisition
AI Adoption and Literacy Initiatives
Emerging Technology and Investment News
AI Stock Market Trends and Investments
Google NotebookLM Voice Lawsuit
Anthropic Business Growth and Strategic Risks
AI's Impact on the Modern Workforce
Fractal Analytics India IPO Debut
AI Skills Demand Growth
Anthropic Claude AI Developments and Disputes
ByteDance Seedance Hollywood Copyright Dispute
Investor Caution and AI Market Volatility
Legal AI Singapore RAG Engine
India Hosts AI Impact Summit
Audio Processing AI Evolution
Developments in Robotics and AI
08:54:50 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Result: items=['OpenAI GPT-4o Retirement Backlash', 'Trump Data Center Mandate', 'Software Industry AI Threat', 'Anthropic Workplace Tools', 'Eric Schmidt Space Data', 'Anthropic Claude Code Issues', 'ByteDance Seedance Copyright Dispute', 'Snowflake Data Pipe Warning', 'Alibaba Qwen 3.5 Launch', 'Simpsons Actors AI Opposition', 'Enterprise AI Implementation', 'Data Center Energy Demands', 'Big Tech AI Valuation', 'Biological Computing Neuron Integration', 'Generative AI Landscape', 'Anthropic Growth Safety Tension', 'KPMG AI Exam Fine', 'Business School AI Standards', 'AI Safety Researcher Resignations', 'Indirect Prompt Injection Risks', 'Agentic AI Governance', 'NASA Autonomous Mars Rover', 'India AI Impact Summit', 'Alphabet AI Infrastructure Spending', 'Healthcare AI Ethics', 'AI Antibiotic Drug Discovery', 'FogAI Edge Computing', 'Google AI Overviews Risks', 'OpenAI OpenClaw Acquisition', 'Sam Altman Infrastructure Plans', 'Google NotebookLM Lawsuit', 'Fractal Analytics IPO', 'Legal AI Singapore RAG', 'Audio Processing AI Evolution', 'Robotics and AI Developments']
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Final categories: AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=TopicHeadline, reasoning_effort=low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
Why an A.I. Video of Tom Cruise Battling Brad Pitt Spooked Hollywood - The New York Times

Rating: 10.5

Topics: ByteDance, Seedance 2.0 (Artificial Intelligence Co), Copyrights and Copyright Violations, Hollywood, Video Generation, Deepfakes, Labor Markets And Productivity

A 15-second clip created by an artificial intelligence tool owned by the Chinese technology company ByteDance appears more cinematic than anything so far.

- ByteDance's Seedance 2.0 AI tool created a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, sparking alarm in Hollywood due to its professional-grade cinematic quality. - Disney and the Motion Picture Association have demanded ByteDance cease operations, alleging the tool was trained on a 'pirated library' of copyrighted characters and films. - While some industry professionals fear imminent job displacement, others argue that AI remains an 'averaging machine' incapable of producing poignant or provocative human-level artistry.
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
Business schools search for clear AI guidelines - Financial Times

Rating: 9.4

Topics: Business Schools, Education, Academic Integrity, Ethics, Digital Education Council, Adoption and Spending, Gen AI

Attempts to establish shared standards are lagging behind adoption of the technology

- Business schools are rapidly integrating AI into curricula and operations, with over 700 AI-focused programs identified in the US, yet institutions lack a standardized roadmap or clear benchmarks for implementation. - New initiatives like the Digital Education Council’s benchmarking framework aim to measure AI capability and ethics, while schools like Cambridge and HEC pilot interactive AI teaching cases and automated grading assistants. - Concerns persist regarding academic integrity and the offloading of critical thinking, leading deans to emphasize transparency and the need for ethical guidelines to prevent the disintermediation of traditional education.
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
Are Anthropic’s new AI work tools game-changing for professionals? - Financial Times

Rating: 8.7

Topics: Anthropic, Claude, Workplace Tools, LegalTech, Consulting, Enterprise AI, Productivity

Adaptable plug-ins must compete with bespoke products already used by lawyers and consultants

- Anthropic is launching new AI work tools and adaptable plug-ins aimed at professional sectors. - The new tools are designed to compete with specialized software currently used by legal and consulting professionals. - The market impact will be determined by the ability of these general-purpose AI tools to replace established, bespoke industry products.
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
KPMG partner fined over using AI to pass AI test - Financial Times

Rating: 8.0

Topics: KPMG, Accounting, Professional Integrity, Ethics, Internal Exams, Testing, Enterprise AI

Accounting firm has caught several staff members in recent months using the technology for internal exams

- A KPMG partner was fined after being caught using artificial intelligence to complete an internal exam designed to test AI competency. - The incident is part of a broader trend within the accounting firm, which has identified several staff members using AI technology to bypass internal testing requirements in recent months. - The case underscores the growing regulatory and ethical challenges professional services firms face in ensuring staff integrity as they adopt and train employees on generative AI tools.
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
OpenAI retired GPT-4o on February 13, angering loyal users, 20K+ of whom signed a petition; 4o showed the unique attachment that people can form with chatbots (Shirin Ghaffary/Bloomberg) - Bloomberg

Rating: 8.3

no content
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery
AI Safety Researcher Resignations
Agentic AI Governance
Alibaba Qwen 3.5 Launch
Alphabet AI Infrastructure Spending
Anthropic Claude Code Issues
Anthropic Growth Safety Tension
Anthropic Workplace Tools
Audio Processing AI Evolution
Big Tech AI Valuation
Biological Computing Neuron Integration
Business School AI Standards
ByteDance Seedance Copyright Dispute
Data Center Energy Demands
Enterprise AI Implementation
Eric Schmidt Space Data
FogAI Edge Computing
Fractal Analytics IPO
Generative AI Landscape
Google AI Overviews Risks
Google NotebookLM Lawsuit
Healthcare AI Ethics
India AI Impact Summit
Indirect Prompt Injection Risks
KPMG AI Exam Fine
Legal AI Singapore RAG
NASA Autonomous Mars Rover
OpenAI GPT-4o Retirement Backlash
OpenAI OpenClaw Acquisition
Robotics and AI Developments
Sam Altman Infrastructure Plans
Simpsons Actors AI Opposition
Snowflake Data Pipe Warning
Software Industry AI Threat
Trump Data Center Mandate

Classify the news item into exactly one of the candidate topics above. If your best match is < 60% confidence, output Other.

NEWS ITEM
AMD Takes on Nvidia in India With Expanded Tata AI Partnership - Bloomberg

Rating: 6.7

- no content
---
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: low
08:54:53 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: CANDIDATE TOPICS
AI Antibiotic Drug Discovery

✅ Completed Step 7: Categories and article counts:
cat
Anthropic Growth Safety Tension          4
Big Tech AI Valuation                   12
ByteDance Seedance Copyright Dispute     2
Enterprise AI Implementation            15
Generative AI Landscape                 10
Healthcare AI Ethics                     4
India AI Impact Summit                   9
Other                                   19
Robotics and AI Developments             5
================================================================================
⏱️  Total execution time: 63.79s
📊 Final result:
Categories and article counts:
cat
Anthropic Growth Safety Tension          4
Big Tech AI Valuation                   12
ByteDance Seedance Copyright Dispute     2
Enterprise AI Implementation            15
Generative AI Landscape                 10
Healthcare AI Ethics                     4
India AI Impact Summit                   9
Other                                   19
Robotics and AI Developments             5

In [ ]:
# User prompt to run workflow
# user_prompt = "Run step 8, draft sections"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("draft_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

08:55:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Step 8a: Selecting stories from 80 total
08:55:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 16 must-include stories with rating > 8
08:55:17 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | 64 stories with rating <= 8

▶ Starting Step 8: draft_sections

08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Selected 64 diverse Tier 2 stories via MMR
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Total selected stories: 80 (target: 100)
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Drafting sections for 9 categories (including Other) from selected stories
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Initialized LLMagent: model=gemini-3-flash-preview, vendor=gemini, output_type=Section, reasoning_effort=medium
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: STORIES:
[{"id":7,"rating":12.2096775055,"summary":"ByteDance is implementing new safeguards for its Seedance 2.0 AI video generator following copyright infringement allegations and cease and desist letters from Disney, Paramount, SAG-AFTRA, and the Motion Picture Association.","site_name":"The Verge","url":"https:\/\/www.theverge.com\/ai-artificial-intelligence\/879644\/bytedance-seedance-safeguards-ai-video-copyright-infringement"},{"id":0,"rating":10.4600489277,"summary":"ByteDance's Seedance 2.0 AI tool produced a hyper-realistic 15-second video of Tom Cruise and Brad Pitt, prompting Disney and the Motion Picture Association to allege copyright infringement and demand the company cease operations.","site_name":"The New York Times","url":"https:\/\/www.nytimes.com\/2026\/02\/16\/movies\/tom-cruise-brad-pitt-artificial-intelligence-seedance.html"}]
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: STORIES:
[{"id":1,"rating":9.3806086827,"summary":"More than 700 US business schools have integrated AI into their curricula, though the absence of standardized benchmarks has prompted new initiatives to establish ethical and capability frameworks.","site_name":"Financial Times","url":"https:\/\/www.ft.com\/content\/3659b953-8a3a-4e13-b322-c973a545b836"},{"id":2,"rating":8.7232376615,"summary":"Anthropic is launching AI work tools and adaptable plug-ins for professional sectors, including legal and consulting, to compete with established specialized software.","site_name":"Financial Times","url":"https:\/\/www.ft.com\/content\/92dfd571-8d34-42f1-8be8-dce126998e37"},{"id":43,"rating":8.1926174679,"summary":"OpenAI, Anthropic, and Cisco joined the Agentic AI Foundation to establish governance standards, addressing infrastructure and trust barriers as Gartner predicts 40% of enterprise software will include AI agents by 2026.","site_name":"PYMNTS","url":"https:\/\/www.pymnts.com\/artificial-intelligence-2\/2026\/openai-and-cisco-back-standards-to-scale-agentic-ai\/"},{"id":3,"rating":8.0059486066,"summary":"KPMG fined a partner for using artificial intelligence to complete an internal AI competency exam, marking one of several recent instances where staff used the technology to bypass internal testing requirements.","site_name":"Financial Times","url":"https:\/\/www.ft.com\/content\/c30ded60-bece-45e0-981d-653e1e3e9818"},{"id":76,"rating":7.2246871055,"summary":"US productivity increased by approximately 2.7% in 2025, nearly doubling the 1.4% decade average, as AI-exposed sectors reduced entry-level hiring and began realizing measurable efficiency gains from technology.","site_name":"Twitter","url":"https:\/\/t.co\/iwFZFYyeEB"},{"id":28,"rating":6.8769021863,"summary":"Snowflake CEO Sridhar Ramaswamy warns that software giants risk becoming \"dumb data pipes\" as AI model makers centralize enterprise data, leading Snowflake to offer flexible access for customers using third-party platforms like ChatGPT.","site_name":"Business Insider","url":"https:\/\/www.businessinsider.com\/snowflake-ceo-sridhar-ramaswamy-software-dumb-data-pipe-ai-2026-2"},{"id":49,"rating":5.890265856,"summary":"Amazon launched Creative Agent, an AI tool using AWS and Anthropic Claude to automate advertising research and generation, reducing production time from weeks to hours for small businesses in the US and Europe.","site_name":"TechRadar","url":"https:\/\/www.techradar.com\/pro\/amazon-has-a-new-creative-agent-to-help-your-business-build-its-own-ads"},{"id":10,"rating":5.8898890449,"summary":"Anthropic is expanding its artificial intelligence operations in India through new partnerships with Air India and Cognizant.","site_name":"Bloomberg","url":"https:\/\/www.bloomberg.com\/news\/articles\/2026-02-16\/anthropic-boosts-india-ai-push-via-flag-airline-cognizant-pacts"},{"id":34,"rating":5.813012401,"summary":"An Upwork report shows AI-related skill demand grew 109% year-over-year, led by AI video creation at 329%, while employers prioritize human skills and learning agility for the 2026 market.","site_name":"Fast Company","url":"https:\/\/www.fastcompany.com\/91492708\/demand-for-ai-related-skills-is-up-109-since-last-year-what-that-means-for-you"},{"id":29,"rating":5.1885144825,"summary":"AI agents create a \"second brain\" for marketing teams by monitoring performance and retaining institutional memory to improve strategic decision-making and organizational intelligence.","site_name":"Hacker Noon","url":"https:\/\/hackernoon.com\/building-a-second-brain-for-marketing-using-ai-agents"},{"id":60,"rating":5.1017660361,"summary":"LLM agent costs scale quadratically because every turn requires reading the entire conversation history, with cache reads accounting for up to 87% of total expenses and 50% of API costs at 27,500 tokens.","site_name":"EXE.dev","url":"https:\/\/blog.exe.dev\/expensively-quadratic"},{"id":39,"rating":5.0178498385,"summary":"Implementing AI-assisted adaptive concurrency in Spring Batch replaces static thread pools with LLM-driven recommendations bounded by hard-coded safety guardrails to manage dynamic runtime conditions and maintain system stability.","site_name":"Hacker Noon","url":"https:\/\/hackernoon.com\/stop-guessing-thread-pool-sizes-how-to-plug-ai-into-spring-batch-safely"},{"id":41,"rating":4.8208847719,"summary":"Temporal Convolutional Networks with attention layers and Ray Tune optimization reduce Amazon FBA forecast errors by 28% over LSTM models, utilizing Weighted Quantile Loss to better manage inventory holding costs and stockouts.","site_name":"Hacker Noon","url":"https:\/\/hackernoon.com\/the-hard-truth-about-machine-learning-for-amazon-fba-sellers"},{"id":81,"rating":2.2602085289,"summary":"SPAR International partnered with Veesion to deploy AI-driven loss-prevention technology that integrates with existing security cameras to identify suspicious behavior and alert store personnel in real-time across its global retail network.","site_name":"Retail Insight Network","url":"https:\/\/www.retail-insight-network.com\/news\/spar-rolls-out-ai-loss-prevention-tech\/"},{"id":82,"rating":2.2573968199,"summary":"Atsuya Technologies' AOne platform was named a top 20 solution in the AI for All: Global Impact Challenge for using agent-driven AI to autonomously manage enterprise operations and optimize energy use across industrial sectors.","site_name":"Business Standard","url":"https:\/\/www.business-standard.com\/companies\/start-ups\/deep-tech-startup-atsuya-named-among-top-20-in-ai-for-all-challenge-126021500505_1.html"}]
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: STORIES:
[{"id":30,"rating":12.867150372,"summary":"OpenAI hired Peter Steinberger, creator of the open-source tool OpenClaw, to lead personal agent development following a bidding war with Meta, as the tool with 196,000 GitHub stars moves to an independent foundation.","site_name":"Engadget","url":"https:\/\/www.engadget.com\/ai\/openai-has-hired-the-developer-behind-ai-agent-openclaw-092934041.html"},{"id":53,"rating":11.9156253119,"summary":"Alibaba Cloud released Qwen3.5-397B-A17B, an open-weight vision-language model featuring a hybrid architecture that activates 17 billion parameters, achieves 19x higher decoding throughput, and supports 201 dialects for autonomous multimodal agent tasks.","site_name":"Qwen","url":"https:\/\/qwen.ai\/blog?id=qwen3.5"},{"id":4,"rating":8.2645917705,"summary":"OpenAI retired GPT-4o on February 13, prompting over 20,000 users to sign a petition in protest of the decision.","site_name":"Bloomberg","url":"https:\/\/www.bloomberg.com\/news\/newsletters\/2026-02-13\/openai-retires-controversial-4o-ai-model-angering-loyal-users"},{"id":68,"rating":7.1176924947,"summary":"Eric Schmidt warned of a 92-gigawatt power shortfall for AI, prompting Elon Musk and Alphabet to develop orbital data center prototypes by 2027 to leverage continuous solar energy and reduced cooling requirements.","site_name":"Benzinga","url":"https:\/\/www.benzinga.com\/markets\/tech\/26\/02\/50635721\/eric-schmidt-says-were-running-out-of-electricity-urges-space-data-centers-spacex-ceo-elon-musk-quips-if-only-there-were-a-company"},{"id":9,"rating":6.5462800914,"summary":"Audio intelligence systems are transitioning to hybrid models that integrate machine learning with Digital Signal Processing to enhance real-time stability and physical grounding in applications such as noise suppression and spatial audio.","site_name":"Hacker Noon","url":"https:\/\/hackernoon.com\/from-dsp-to-ai-evolving-approaches-in-audio-processing"},{"id":8,"rating":6.5014766247,"summary":"Developer Aditya Prasad open-sourced a legal AI engine for Singapore laws that utilizes a triple-model failover architecture and a 0.5 confidence threshold to process over 30,000 pages of government documents.","site_name":"Hacker Noon","url":"https:\/\/hackernoon.com\/how-i-built-fail-safe-legal-ai-engine-for-singapore-laws-using-triple-model-rag"},{"id":22,"rating":6.2175980163,"summary":"Former NPR host David Greene sued Google for allegedly training its NotebookLM AI voice on his likeness without authorization, while Google maintains the model was based on a hired professional actor.","site_name":"Gizmodo","url":"https:\/\/gizmodo.com\/former-npr-host-accuses-google-of-copying-his-voice-for-ai-offering-2000722402"},{"id":55,"rating":4.7830356516,"summary":"Generative AI training on synthetic data causes model collapse and design homogenization, leading to 2026 trends favoring analog imperfections and the adoption of Machine Experience and Generative Engine Optimization strategies.","site_name":"We And The Color","url":"https:\/\/weandthecolor.com\/real-design-trends-are-dying-under-the-weight-of-recursive-ai-echoes\/208199"},{"id":37,"rating":4.7253297658,"summary":"Comparative testing of Gemini, Claude, and ChatGPT for natural language app development demonstrated that iterative prompt refinement allows free AI models to match premium performance, making prompt engineering the primary factor in software quality.","site_name":"CNET","url":"https:\/\/www.cnet.com\/tech\/services-and-software\/i-vibe-coded-an-app-with-3-popular-chatbots-the-real-winner-is-a-good-prompt\/"},{"id":87,"rating":1.5772172217,"summary":"Definitions for core artificial intelligence terms like Large Language Models and generative AI accompany industry applications in banking and healthcare and safety guardrails intended to mitigate bias and hallucinations.","site_name":"Business Standard","url":"https:\/\/www.business-standard.com\/technology\/tech-news\/ai-buzzwords-decoded-what-terms-like-llms-generative-ai-guardrails-mean-126021500235_1.html"}]
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: STORIES:
[{"id":11,"rating":9.6980636902,"summary":"OpenAI CEO Sam Altman restructured the company into a public benefit corporation in 2025 and launched the $500 billion Stargate infrastructure initiative while expanding product lines and preparing for a 2026 legal trial against Elon Musk.","site_name":"Business Insider","url":"https:\/\/www.businessinsider.com\/sam-altman"},{"id":26,"rating":7.2181548773,"summary":"NASA trialed AI-powered autonomous driving on the Perseverance rover, the Pentagon threatened Anthropic's $200 million contract over weapons use, and OpenAI accused DeepSeek of unauthorized distillation techniques after Anthropic raised $30 billion at a $380 billion valuation.","site_name":"Semafor","url":"https:\/\/www.semafor.com\/article\/02\/16\/2026\/nasa-trials-ai-powered-driving-of-mars-rover"},{"id":44,"rating":6.3714372288,"summary":"Blackstone CEO Stephen Schwarzman is committing the majority of his $47.8 billion fortune to his foundation to support artificial intelligence and education, focusing on global AI preparedness and workforce development.","site_name":"Fortune","url":"https:\/\/fortune.com\/2026\/02\/16\/stephen-schwarzman-blackstone-ceo-48-billion-fortune-to-philanthropic-foundation-focused-on-ai\/"},{"id":38,"rating":5.9660459206,"summary":"Cloudflare launched a tool to convert publisher content into Markdown, a format AI agents prefer over HTML for token efficiency and improved Answer Engine Optimization accuracy.","site_name":"Digiday","url":"https:\/\/digiday.com\/media\/wtf-is-markdown-for-ai-agents\/"},{"id":59,"rating":5.6787619854,"summary":"Security experts identify indirect prompt injection as an architectural vulnerability where attackers hide commands in data sources, recommending sandboxing, strict access controls, and multi-model consensus to prevent unauthorized AI agent actions.","site_name":"Reddit","url":"https:\/\/www.reddit.com\/r\/ChatGPT\/comments\/1r5snvl\/indirect_prompt_injection_in_ai_agents_is\/"},{"id":15,"rating":5.5985361984,"summary":"MiniMax shares increased by 25% following growing optimism regarding Chinese artificial intelligence firms.","site_name":"Bloomberg","url":"https:\/\/www.bloomberg.com\/news\/articles\/2026-02-16\/minimax-shares-surge-25-as-optimism-over-chinese-ai-firms-grows"},{"id":16,"rating":5.5015682081,"summary":"Ray Wang states that increasing demand for artificial intelligence is driving a surge in DRAM prices.","site_name":"Bloomberg","url":"https:\/\/www.bloomberg.com\/news\/articles\/2026-02-16\/ai-is-causing-the-price-of-computer-memory-to-surge"},{"id":42,"rating":5.4354851179,"summary":"Ars Technica retracted an article containing fabricated quotes generated by ChatGPT after a staff writer accidentally included the AI's paraphrased output as direct quotations.","site_name":"404 Media","url":"https:\/\/www.404media.co\/ars-technica-pulls-article-with-ai-fabricated-quotes-about-ai-generated-article\/"},{"id":54,"rating":5.0706830015,"summary":"Alexander Oldham filed two California ballot measures proposing state oversight of AI firms structured as public benefit corporations, but he lacks the funding required to gather signatures to place the initiatives on the ballot.","site_name":"New York Post","url":"https:\/\/nypost.com\/2026\/02\/16\/business\/california-ballot-measures-that-appear-aimed-at-openai-were-filed-by-stepbrother-of-employee-at-rival-anthropic\/"},{"id":36,"rating":4.0541954681,"summary":"Lux Capital and Flutterwave CEO Olugbenga Agboola have invested in a Nigerian drone manufacturing company.","site_name":"Bloomberg","url":"https:\/\/www.bloomberg.com\/news\/articles\/2026-02-16\/lux-capital-flutterwave-ceo-invests-in-nigerian-drone-maker"},{"id":77,"rating":3.3328644867,"summary":"Developers can use the Modal platform and DeepSeek's open-source model to convert a 600-page technical textbook into markdown in 45 minutes for approximately $2 using A100 GPUs.","site_name":"Christopher Krapu","url":"https:\/\/christopherkrapu.com\/blog\/2026\/ocr-textbooks-modal-deepseek\/"},{"id":83,"rating":3.2428623407,"summary":"Nancy Cartwright, the voice of Bart Simpson, opposed AI replacement in voice acting, citing a lack of human emotion, while Disney explores AI tools following a $1 billion licensing deal with OpenAI.","site_name":"The Daily Beast","url":"https:\/\/www.thedailybeast.com\/obsessed\/simpsons-star-nancy-cartright-68-fears-heartless-replacement-on-show\/"},{"id":65,"rating":3.2308585922,"summary":"Microsoft manager Brit Morenus transitioned from a contract executive assistant to a senior AI gamification product manager by obtaining technical certifications and utilizing humanities skills for prompt engineering and metadata tagging.","site_name":"Business Insider","url":"https:\/\/www.businessinsider.com\/microsoft-manager-explains-how-she-pivoted-from-admin-to-ai-2026-2"},{"id":72,"rating":3.0891810102,"summary":"A user reduced their weekly grocery bill by 50%, from $400 to $200, by using ChatGPT to generate meal plans based on photographs of their existing fridge and pantry inventory.","site_name":"Tom's Guide","url":"https:\/\/www.tomsguide.com\/ai\/i-asked-chatgpt-for-a-grocery-trick-and-it-cut-my-food-bill-in-half"},{"id":89,"rating":1.8348833693,"summary":"Innocent Uwah of Nigerian British University urged the Independent National Electoral Commission to adopt artificial intelligence for electronic result transmission to improve electoral transparency and credibility before the 2027 elections.","site_name":"Punch Nigeria","url":"https:\/\/punchng.com\/?p=2065067"},{"id":88,"rating":1.4359849101,"summary":"Acadia University launched a free, 2.5-hour AI literacy course for the public that covers text-based tools like ChatGPT and Claude, following the enrollment of nearly 500 students since January.","site_name":"CBC","url":"https:\/\/www.cbc.ca\/news\/canada\/nova-scotia\/acadia-university-ai-open-course-9.7073938"},{"id":90,"rating":1.1540061996,"summary":"Ethical discussions highlight the contrast between AI's role in oncology research, such as the targeted chemotherapy drug AOH1996, and its increasing application in creating viral deepfake media through open-source video editing workflows.","site_name":"Reddit","url":"https:\/\/v.redd.it\/rgrvl3kydqjg1"},{"id":91,"rating":0.6973741974,"summary":"Professional wrestler El Grande Americano criticized his rival's use of AI-generated vignettes and voice synthesis in Lucha Libre AAA promotions, labeling the AI-filtered depiction of the Mexican flag a sign of disrespect to his culture.","site_name":"Cageside Seats","url":"https:\/\/www.cagesideseats.com\/wwe\/418612\/el-grande-americano-warns-original-over-ai-mexican-flag"},{"id":92,"rating":0.4510895532,"summary":"OpenAI employee Gujari Singh mandates a prenuptial agreement as a non-negotiable condition for marriage to protect her annual salary of over \u20b92 crore and equity-based assets.","site_name":"Times of India","url":"https:\/\/economictimes.indiatimes.com\/magazines\/panache\/she-earns-rs-2-crore-yearly-but-openai-employee-wont-say-yes-to-marriage-without-this-non-negotiable-rule\/articleshow\/128382827.cms"}]
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | Using reasoning_effort: medium
08:55:18 | NewsletterAgent.test_newsletter_20260216080715128568 | INFO | User message: STORIES:

In [ ]:
newsletter_section_df = state.newsletter_section_df

newsletter_section_df

In [ ]:
Markdown(state.display_newsletter().replace("$","\\\$"))

In [ ]:
# User prompt to run workflow
# user_prompt = "Run step 9, finalize newsletter"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("finalize_newsletter")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

In [ ]:
display(Markdown(state.final_newsletter.replace("$", "\\\$")))

In [ ]:
print(state.get_workflow_status_report())

In [ ]:
state.print_workflow_status()