# Run Agent
- Implement a workflow to write a daily AI newsletter
- see README.md for details

In [1]:
import os
import yaml
import dotenv
import logging
import json
import yaml
from datetime import datetime
import time
import random
import glob
import pickle
import sqlite3

from pathlib import Path

import asyncio
import nest_asyncio

import pydantic
from pydantic import BaseModel, Field, RootModel
from typing import Dict, TypedDict, Type, List, Optional, Any, Iterable, Text
from dataclasses import dataclass, field
from enum import Enum

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import hdbscan

import openai
from openai import AsyncOpenAI

import agents
from agents.exceptions import InputGuardrailTripwireTriggered
from agents import (Agent, Runner, Tool, OpenAIResponsesModel, 
                    ModelSettings, FunctionTool, InputGuardrail, GuardrailFunctionOutput,
                    SQLiteSession, set_default_openai_api, set_default_openai_client
                   )


import tenacity
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from IPython.display import HTML, Image, Markdown, display

from log_handler import SQLiteLogHandler, setup_sqlite_logging, sanitize_error_for_logging
from config import LOGDB
from llm import LLMagent, LangfuseClient  # methods to apply prompts async to large batches
from db import Url, AgentState

from fetch import Fetcher # fetch news urls
from newsletter_state import NewsletterAgentState, StepStatus
from news_agent import NewsletterAgent

In [2]:
print(f"OpenAI:            {openai.__version__}")
print(f"OpenAI Agents SDK  {agents.__version__}")
print(f"Pydantic           {pydantic.__version__}")

OpenAI:            2.21.0
OpenAI Agents SDK  0.9.0
Pydantic           2.12.5

In [3]:
dotenv.load_dotenv()

# to run async in jupyter notebook
nest_asyncio.apply()

# turn off open telemetry (langfuse)
os.environ["OTEL_SDK_DISABLED"] = "true"

# verbose OpenAI console logging if something doesn't work
# logging.basicConfig(level=logging.DEBUG)
# openai_logger = logging.getLogger("openai")
# openai_logger.setLevel(logging.DEBUG)

In [4]:
# modules create a default logger, or we can pass this logger
debuglevel = logging.DEBUG

def setup_logging(session_id: str = "default", db_path: str = "agent_logs.db") -> logging.Logger:
    """Set up logging to console and SQLite database."""

    # Create logger
    logging.basicConfig()
    logger = logging.getLogger(f"NewsletterAgent.{session_id}")
    logger.setLevel(debuglevel)

    # Clear any existing handlers
    logger.handlers.clear()

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(debuglevel)
    console_formatter = logging.Formatter(
        '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
        datefmt='%H:%M:%S'
    )
    console_handler.setFormatter(console_formatter)

    # SQLite handler
    sqlite_handler = SQLiteLogHandler(db_path)
    sqlite_handler.setLevel(debuglevel)
    sqlite_formatter = logging.Formatter('%(message)s')
    sqlite_handler.setFormatter(sqlite_formatter)

    # Add handlers to logger
    logger.addHandler(console_handler)
    logger.addHandler(sqlite_handler)

    # Prevent propagation to root logger
    logger.propagate = False

    return logger

logger = setup_logging("newsletter_agent", "test_logs.db")

# Log some test messages
logger.debug("Test debug message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.info("Test info message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.warning("Test warning message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.error("Test error message", extra={
    'step_name': 'error_step',
    'agent_session': 'demo_session'
})

sanitize_error_for_logging("log with some bad stuff for the filter: sk-proj-123456789012345678901234567890123456789012345678")

07:30:59 | NewsletterAgent.newsletter_agent | DEBUG | Test debug message
07:30:59 | NewsletterAgent.newsletter_agent | INFO | Test info message
07:30:59 | NewsletterAgent.newsletter_agent | WARNING | Test warning message
07:30:59 | NewsletterAgent.newsletter_agent | ERROR | Test error message

'log with some bad stuff for the filter: [API_KEY_REDACTED]'

In [6]:
# look up recent sessions
conn = sqlite3.connect("newsletter_agent.db")
AgentState.list_sessions(conn, n_records=10)

['test_newsletter_20260215072749475436',
 'test_newsletter_20260214083433211276',
 'test_newsletter_20260214082909417070',
 'test_newsletter_20260214081211439717',
 'test_newsletter_20260214080845501239',
 'test_newsletter_20260214080053576719',
 'test_newsletter_20260214074501502362',
 'test_newsletter_20260213074843567764',
 'test_newsletter_20260213074537650137',
 'test_newsletter_20260213071403758999']

In [7]:
z = AgentState.get_latest_by_session(conn, "test_newsletter_20260122183737514938")
z.step_name

'filter_urls'

In [8]:
for y in z.get_all_by_session(conn, "test_newsletter_20260122183737514938"):
    print(y.session_id, y.step_name, y.updated_at)

test_newsletter_20260122183737514938 initialize 2026-01-22 18:37:37.544042
test_newsletter_20260122183737514938 gather_urls 2026-01-22 18:40:01.118660
test_newsletter_20260122183737514938 check_workflow_status 2026-01-22 18:40:02.909579
test_newsletter_20260122183737514938 filter_urls 2026-01-22 18:41:11.169324

# Run Agent Worfklow

In [9]:
print("🚀 Creating NewsletterAgent...")
do_download=False
reprocess_since=None
reprocess_since='2026-02-14 08:34:00'
try:
    # set up state
    session_id = 'test_newsletter_20260122183737514938'
    step_name = 'filter_urls'
    del session_id
except Exception as e:
    print(e)

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable not set")

# Set up OpenAI client for the agents SDK
set_default_openai_client(AsyncOpenAI(api_key=api_key))

# Create agent with persistent state
if 'session_id' in vars():
    # load state from db for session_id and state
    print("session_id is defined")
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db", 
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                )
    state = state.load_from_db(step_name)
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=True, timeout=30)    
else:
    # create new session
    print("session_id is not defined")
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")    
    session_id = f"test_newsletter_{timestamp}"
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db",
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                ) 
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=False, timeout=30)
    agent.verbose=False  # there seems to be a bug where saved agents are saved or restored with verbose=True
    state.serialize_to_db("initialize")

🚀 Creating NewsletterAgent...
session_id is not defined
test_newsletter_20260215073155703123

In [10]:
agent.state.get_status()

{'headlines': {'total': 0},
 'sources': {'config_file': 'sources.yaml', 'loaded_sources': 0},
 'topics': {'cluster_topics': 0, 'topics': []},
 'workflow': {'current_step': 'gather_urls',
  'workflow_complete': False,
  'progress_percentage': 0.0,
  'completed_steps': 0,
  'total_steps': 9,
  'max_edits': 2,
  'concurrency': 12,
  'do_download': False,
  'reprocess_since': datetime.datetime(2026, 2, 14, 8, 34)},
 'processing': {'topic_clusters': 0,
  'newsletter_sections': 0,
  'final_newsletter_length': 0}}

In [11]:
for step in agent.state.steps:
    print(step)
    print("---")

⚪ Gather URLs [not_started]

---
⚪ Filter URLs [not_started]

---
⚪ Download Articles [not_started]

---
⚪ Extract Summaries [not_started]

---
⚪ Rate Articles [not_started]

---
⚪ Cluster By Topic [not_started]

---
⚪ Select Sections [not_started]

---
⚪ Draft Sections [not_started]

---
⚪ Finalize Newsletter [not_started]

---

In [12]:
# User prompt to run workflow
user_prompt = "Show the workflow status"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Show the workflow status'
================================================================================

07:32:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting check_workflow_status
07:32:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 6.08s
📊 Final result:
Here’s the current workflow status from persistent state:

Overall progress: 0.0% (0/9 complete)
Summary: 0 complete, 0 started, 0 failed, 9 not started
Next step: Step 0 — Gather URLs

Step-by-step:
- Step 0: Gather URLs: not_started
- Step 1: Filter URLs: not_started
- Step 2: Download Articles: not_started
- Step 3: Extract Summaries: not_started
- Step 4: Rate Articles: not_started
- Step 5: Cluster By Topic: not_started
- Step 6: Select Sections: not_started
- Step 7: Draft Sections: not_started
- Step 8: Finalize Newsletter: not_started

What would you like me to do next?
- Run the next step (Gather URLs)
- Run all remaining steps and create the newsletter
- Run a specific step (specify which)
- Inspect internal state for debugging

In [13]:
# User prompt to run a workflow step
user_prompt = "Run step 1, fetch urls"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Run step 1, fetch urls'
================================================================================

07:32:06 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting Step 1: Gather URLs
2026-02-15 07:32:06,524 - fetcher_5464751248 - INFO - [fetcher_init] Loading sources from sources.yaml
2026-02-15 07:32:06,544 - fetcher_5464751248 - INFO - [fetcher_init] Loaded 17 sources: 5 RSS, 11 HTML, 1 API
2026-02-15 07:32:06,545 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Ars Technica': type=html, url=https://arstechnica.com/ai/
2026-02-15 07:32:06,545 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Bloomberg': type=RSS, url=https://www.bloomberg.com/ai
2026-02-15 07:32:06,545 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Business Insider': type=html, url=https://www.businessinsider.com/tech
2026-02-15 07:32:06,545 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'FT': type=RSS, url=https://www.ft.com/artificial-intelligence
2026-02-15 07:32:06,545 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Feedly AI': type=html, url=https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-15 07:32:06,546 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Hacker News': type=RSS, url=https://news.ycombinator.com/
2026-02-15 07:32:06,546 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'HackerNoon': type=RSS, url=https://hackernoon.com/tagged/ai
2026-02-15 07:32:06,546 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'New York Times': type=RSS, url=https://www.nytimes.com/section/technology
2026-02-15 07:32:06,546 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Reddit': type=RSS, url=https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-15 07:32:06,546 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Techmeme': type=RSS, url=https://www.techmeme.com/river
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'The Register': type=RSS, url=https://www.theregister.com/software/ai_ml/
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'The Verge': type=RSS, url=https://www.theverge.com/ai-artificial-intelligence
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'VentureBeat': type=RSS, url=https://venturebeat.com/category/ai
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'WSJ': type=RSS, url=https://www.wsj.com/tech/ai
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'Washington Post': type=RSS, url=https://www.washingtonpost.com/technology/innovations/
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'The Guardian': type=RSS, url=https://www.theguardian.com/uk/technology
2026-02-15 07:32:06,547 - fetcher_5464751248 - DEBUG - [fetcher_sources] Source 'NewsAPI': type=rest, url=https://newsapi.org/v2/everything
2026-02-15 07:32:06,548 - fetcher_5464751248 - INFO - [fetcher_init] Fetcher initialized with max_concurrent=8
2026-02-15 07:32:06,548 - fetcher_5464751248 - INFO - [fetch_all] Starting fetch_all for 17 sources
2026-02-15 07:32:06,548 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Ars Technica: https://arstechnica.com/ai/
2026-02-15 07:32:06,549 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Ars_Technica.html
2026-02-15 07:32:06,591 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Ars_Technica.html
2026-02-15 07:32:06,592 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Ars Technica: 29 articles
2026-02-15 07:32:06,592 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Bloomberg: https://www.bloomberg.com/ai
2026-02-15 07:32:06,592 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Bloomberg.html
2026-02-15 07:32:06,634 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Bloomberg.html
2026-02-15 07:32:06,635 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Bloomberg: 39 articles
2026-02-15 07:32:06,635 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Business Insider: https://www.businessinsider.com/tech
2026-02-15 07:32:06,635 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Business_Insider.html
2026-02-15 07:32:06,662 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Business_Insider.html
2026-02-15 07:32:06,663 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Business Insider: 17 articles
2026-02-15 07:32:06,663 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from FT: https://www.ft.com/artificial-intelligence
2026-02-15 07:32:06,663 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/FT.html
2026-02-15 07:32:06,695 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/FT.html
2026-02-15 07:32:06,695 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for FT: 104 articles
2026-02-15 07:32:06,695 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Feedly AI: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-15 07:32:06,696 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Feedly_AI.html

▶ Starting Step 1: gather_urls

2026-02-15 07:32:06,778 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Feedly_AI.html
2026-02-15 07:32:06,779 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Feedly AI: 151 articles
2026-02-15 07:32:06,779 - fetcher_5464751248 - INFO - [fetch_rss] Fetching RSS from Hacker News: https://news.ycombinator.com/rss
2026-02-15 07:32:06,780 - fetcher_5464751248 - INFO - [fetch_rss] Fetching RSS from HackerNoon: https://hackernoon.com/tagged/ai/feed
2026-02-15 07:32:06,780 - fetcher_5464751248 - INFO - [fetch_rss] Fetching RSS from New York Times: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
2026-02-15 07:32:06,781 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Reddit: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-15 07:32:06,781 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Reddit.html
2026-02-15 07:32:06,819 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Reddit.html
2026-02-15 07:32:06,820 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Reddit: 62 articles
2026-02-15 07:32:06,820 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Techmeme: https://www.techmeme.com/river
2026-02-15 07:32:06,820 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Techmeme.html
2026-02-15 07:32:06,854 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Techmeme.html
2026-02-15 07:32:06,854 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Techmeme: 219 articles
2026-02-15 07:32:06,855 - fetcher_5464751248 - INFO - [fetch_rss] Fetching RSS from The Register: https://www.theregister.com/software/ai_ml/headlines.atom
2026-02-15 07:32:06,855 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from The Verge: https://www.theverge.com/ai-artificial-intelligence
2026-02-15 07:32:06,856 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/The_Verge.html
2026-02-15 07:32:06,902 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/The_Verge.html
2026-02-15 07:32:06,902 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for The Verge: 2 articles
2026-02-15 07:32:06,903 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from VentureBeat: https://venturebeat.com/category/ai
2026-02-15 07:32:06,903 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/VentureBeat.html
2026-02-15 07:32:06,910 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/VentureBeat.html
2026-02-15 07:32:06,911 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for VentureBeat: 24 articles
2026-02-15 07:32:06,911 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from WSJ: https://www.wsj.com/tech/ai
2026-02-15 07:32:06,911 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/WSJ.html
2026-02-15 07:32:07,304 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/WSJ.html
2026-02-15 07:32:07,305 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for WSJ: 55 articles
2026-02-15 07:32:07,305 - fetcher_5464751248 - INFO - [fetch_html] Using existing HTML file from Washington Post: https://www.washingtonpost.com/technology/innovations/
2026-02-15 07:32:07,306 - fetcher_5464751248 - INFO - [fetch_html] Parsing HTML file: download/sources/Washington_Post.html
2026-02-15 07:32:07,380 - fetcher_5464751248 - INFO - [fetch_html] Parsed HTML file: download/sources/Washington_Post.html
2026-02-15 07:32:07,382 - fetcher_5464751248 - INFO - [fetch_html] HTML fetch successful for Washington Post: 24 articles
2026-02-15 07:32:07,384 - fetcher_5464751248 - INFO - [fetch_rss] Fetching RSS from The Guardian: https://www.theguardian.com/uk/technology/rss
2026-02-15 07:32:07,385 - fetcher_5464751248 - INFO - [newsapi] Fetching top 100 stories matching artificial intelligence since 2026-02-14T07:32:07 from NewsAPI
2026-02-15 07:32:07,616 - fetcher_5464751248 - INFO - [fetch_rss] RSS fetch successful for The Register: 50 articles
2026-02-15 07:32:07,630 - fetcher_5464751248 - INFO - [fetch_rss] RSS fetch successful for New York Times: 24 articles
2026-02-15 07:32:07,685 - fetcher_5464751248 - INFO - [fetch_rss] RSS fetch successful for HackerNoon: 50 articles
2026-02-15 07:32:07,709 - fetcher_5464751248 - INFO - [fetch_rss] RSS fetch successful for The Guardian: 24 articles
2026-02-15 07:32:07,880 - fetcher_5464751248 - INFO - [fetch_rss] RSS fetch successful for Hacker News: 30 articles
2026-02-15 07:32:07,881 - fetcher_5464751248 - INFO - [fetch_all] fetch_all completed: 17 successful, 0 failed, 941 total articles

              source  url
0       Ars Technica   29
1          Bloomberg   27
2   Business Insider   17
3                 FT   50
4          Feedly AI  146
5        Hacker News   28
6         HackerNoon   50
7     New York Times   24
8            NewsAPI   37
9             Reddit   51
10          Techmeme  196
11      The Guardian   21
12      The Register   50
13         The Verge    2
14       VentureBeat   14
15               WSJ   27
16   Washington Post   18

,source,title,url,published,rss_summary,id
0,Ars Technica,I spent two days gigging at RentAHuman and did...,https://arstechnica.com/ai/2026/02/i-spent-two...,NaN,NaN,0
1,Ars Technica,OpenAI sidesteps Nvidia with unusually fast co...,https://arstechnica.com/ai/2026/02/openai-side...,NaN,NaN,1
2,Ars Technica,"Attackers prompted Gemini over 100,000 times w...",https://arstechnica.com/ai/2026/02/attackers-p...,NaN,NaN,2
3,Ars Technica,We let Chrome’s Auto Browse agent surf the web...,https://arstechnica.com/google/2026/02/tested-...,NaN,NaN,3
4,Ars Technica,Yet another co-founder departs Elon Musk’s xAI,https://arstechnica.com/ai/2026/02/grok-maker-...,NaN,NaN,4
...,...,...,...,...,...,...
782,NewsAPI,Rishi Sunak: Every CEO is talking about AI — w...,https://www.thetimes.com/business/companies-ma...,2026-02-14T12:13:32Z,NaN,782
783,NewsAPI,OpenAI Launches OpenAI for Healthcare: 4 Key F...,https://blockchain.news/flashnews/openai-launc...,2026-02-14T07:59:41Z,NaN,783
784,NewsAPI,Sultan bin Ahmed visits Huawei R&D Centre and ...,https://en.antaranews.com/news/404578/sultan-b...,2026-02-14T10:01:18Z,NaN,784
785,NewsAPI,SMU Launches New Master of Science in Business...,https://en.antaranews.com/news/404566/smu-laun...,2026-02-14T08:47:50Z,NaN,785
786,NewsAPI,"Bigger Budgets, Bolder Trips: Klook Finds 88% ...",https://en.antaranews.com/news/404542/bigger-b...,2026-02-14T07:41:40Z,NaN,786

07:32:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Completed Step 1: Gathered 941 articles
07:32:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting check_workflow_status
07:32:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 5.86s
📊 Final result:
Step 1 (Gather URLs) completed.

Summary:
- Gathered 941 headlines from 17 sources
- 787 articles were stored in persistent state
- Workflow progress: 1/9 steps complete (11.1%)
- Next step: Step 1 — Filter URLs (filter AI-related content)

Shall I proceed to run the next step (filter URLs), or do you want to inspect the stored data first?

In [14]:
countdf = pd.DataFrame(state.headline_data) \
    .groupby("source") \
    .count()[["id"]] \
    .reset_index() \
    .rename(columns={'id': 'count'}) \
    .sort_values("count", ascending=False)
countdf

              source  count
10          Techmeme    196
4          Feedly AI    146
9             Reddit     51
12      The Register     50
3                 FT     50
6         HackerNoon     50
8            NewsAPI     37
0       Ars Technica     29
5        Hacker News     28
1          Bloomberg     27
15               WSJ     27
7     New York Times     24
11      The Guardian     21
16   Washington Post     18
2   Business Insider     17
14       VentureBeat     14
13         The Verge      2

In [15]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 11.1% (1/9 complete)
➡️  Next step: Step 1: Filter URLs

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 941 articles from 17 sources.

📊 Articles stored in persistent state: 787
  ⭕ Step 1: Filter URLs            | not_started
  ⭕ Step 2: Download Articles      | not_started
  ⭕ Step 3: Extract Summaries      | not_started
  ⭕ Step 4: Rate Articles          | not_started
  ⭕ Step 5: Cluster By Topic       | not_started
  ⭕ Step 6: Select Sections        | not_started
  ⭕ Step 7: Draft Sections         | not_started
  ⭕ Step 8: Finalize Newsletter    | not_started
============================================================

In [16]:
# Run tool directly without LLM processing an input prompt or results
# user_prompt = "Run step 2, filter urls"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)
# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("filter_urls")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting Step 2: Filter URLs
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 🔍 Filtering 787 headlines...
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 🔄 Checking for duplicates seen before 2026-02-14T08:34:00
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 🔍 Filtering 787 articles for dupes.
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://arstechnica.com/ai/2026/02/i-spent-two-days-gigging-at-rentahuman-and-didnt-make-a-single-cent/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/attackers-prompted-gemini-over-100000-times-while-trying-to-clone-it-google-says/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/tested-how-chromes-auto-browse-agent-handles-common-web-tasks/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/gadgets/2026/02/alphabet-selling-very-rare-100-year-bunds-to-help-fund-ai-investment/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://arstechnica.com/space/2026/02/nasa-chief-vows-to-solve-sls-rocket-fueling-issues-before-artemis-iii/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://arstechnica.com/health/2026/02/who-slams-us-funded-newborn-vaccine-trial-as-unethical/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://arstechnica.com/culture/2026/02/1-8-million-mst3k-kickstarter-brings-in-almost-everyone-from-the-old-show/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-moltbook-ai-agents-can-now-hang-out-in-their-own-space-faring-mmo/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/sixteen-claude-ai-agents-working-together-created-a-new-c-compiler/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/waymo-leverages-genie-3-to-create-a-world-model-for-self-driving-cars/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/features/2026/02/why-darren-aronofsky-thought-an-ai-generated-historical-docudrama-was-a-good-idea/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/with-gpt-5-3-codex-openai-pitches-codex-for-more-than-just-writing-code/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/increase-of-ai-bots-on-the-internet-sparks-arms-race/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/should-ai-chatbots-have-ads-anthropic-says-no/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/apple/2026/02/xcode-26-3-adds-support-for-claude-codex-and-other-agentic-tools-via-mcp/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/senior-staff-departing-openai-as-firm-prioritizes-chatgpt-development/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/the-rise-of-moltbook-suggests-viral-ai-prompts-may-be-the-next-big-security-threat/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/spacex-acquires-xai-plans-1-million-satellite-constellation-to-power-it/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-picks-up-pace-against-claude-code-with-new-codex-desktop-app/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/developers-say-ai-coding-tools-work-and-thats-precisely-what-worries-them/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/security/2026/01/web-portal-leaves-kids-chats-with-ai-toy-open-to-anyone-with-gmail-account/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/how-often-do-ai-chatbots-lead-users-down-a-harmful-path/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-project-genie-lets-you-create-interactive-worlds-from-a-photo-or-prompt/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/new-openai-tool-renews-fears-that-ai-slop-will-overwhelm-scientific-research/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-begins-rolling-out-chromes-auto-browse-ai-agent-today/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/report-china-approves-import-of-high-end-nvidia-ai-chips-after-weeks-of-uncertainty/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/viral-ai-assistant-moltbot-rapidly-gains-popularity-but-poses-security-risks/
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-13/ai-kingpins-adopt-crypto-s-playbook-in-bid-to-get-allies-elected-to-congress
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/waltons-crack-ranks-of-10-richest-as-nvidia-s-huang-falls-out
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
07:32:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-31/elon-musk-s-ai-push-has-him-considering-mergers-in-search-for-capital
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-19/grok-ai-sexualized-images-expose-gaps-in-oversight-enforcement
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2025-11-18/china-s-tsinghua-university-is-beating-us-in-the-race-for-ai-patents
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-10/trump-s-ai-policy-shaped-by-vc-tech-giant-andreessen-horowitz
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2024-12-13/ai-wants-more-data-more-chips-more-power-more-water-more-everything
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/bloomberg-tech-2-13-2026-video
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/building-data-centers-in-space-video
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/the-tech-basket-is-incredibly-attractive-golub-says-video
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/amazon-eyes-longest-losing-streak-since-2006-on-capex-angst
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy

▶ Starting Step 2: filter_urls

07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/shield-ai-in-talks-to-raise-1-billion-at-12-billion-valuation
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-13/nvidia-shares-go-cold-even-as-big-tech-spending-on-ai-balloons
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-13/ai-disruption-trade-drives-divide-in-travel-and-leisure-stocks
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-13/china-ai-app-zhipu-plans-shanghai-float-after-soaring-320-in-hk
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/articles/2026-02-13/capgemini-says-ai-pivot-sovereignty-push-will-drive-growth
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/amazon-engineers-grate-against-internal-limits-claude-code-kiro-ai-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/salesforce-appoints-new-leaders-executive-reshuffle-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/job-hunting-on-tinder-hinge-grindr-dating-app-networking-referrals-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/ai-fatigue-gary-marcus-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://adclick.g.doubleclick.net/pcs/click
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/jensen-huang-net-worth
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/lucid-gravity-suv-review-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/evs-touchscreen-buttons-coming-back-tesla-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/meta-ray-ban-smart-glasses-facial-recognition-distracted-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/gary-marcus-response-something-big-is-happening-ai-essay-shumer-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/guides/tech/best-leather-apple-watch-bands
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/creator-economy-unicorn-ltk-cuts-staff-bets-new-brand-platform-2026-2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/guides/tech/apple-watch-series-11-review
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/94633f65-04c0-4cea-b682-98c17720eebc
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/3dd3f37b-a783-4f12-a837-764e9f429b01
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/e68d68da-3966-47c7-b310-3f39fd4b69b2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/ad264479-52bb-4a63-bc87-e40d6f0a01c0
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/3fc82496-1132-4cb3-a967-25c4c274fbea
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/fdd602f0-317a-429f-b122-7898257dd804
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/62b8713f-cd72-4838-b8ac-708b91b2830f
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/2daa41c3-3721-46d1-8954-7c43d5149995
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/a5b88548-cf2d-4492-bb67-f1b7db3eed0c
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/b314a05c-e1b7-4c0e-9379-2955ba1bfad1
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/90911726-f7c8-40c6-a326-b0f776cb88a7
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/8280412c-df99-4eb2-b447-f29872d0439d
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/40d04966-d526-4314-9c2a-c721c88aaab1
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/4b1e7ab6-2b76-4e66-836b-d54d76147a15
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/dc8c904e-5c51-46e6-84dc-0bc2bf73ed23
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/410cdd53-afa9-4e30-add1-b7afa2a6f373
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/89985a10-1283-40fa-8dc1-9daa6c360b45
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/22a1574e-c90e-4a9e-89ca-14d64d9e44dd
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/915a32cf-d62d-4caf-b539-8525e52257ad
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/02c7a976-0289-4ffe-88b5-b40ff2b5dd5f
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/b06ca67e-41b0-4402-9b39-9e4b432a1291
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/2ead99fe-b320-45b8-844b-53b6ade0529f
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/c0bf5570-c1a3-4ea3-ac96-ea27c320eab2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/2c428045-bf4f-45bd-ada2-8ba53983cd81
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/f1ec830c-2f08-4b1a-b70f-7330f260753c
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/758b3d7d-e94f-40ba-b705-23341ca9bdfe
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/664249e7-e8d5-4425-b397-ad3ed590b305
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/cba54e86-2b2a-422c-861b-dc9280d6aa65
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/15b014ea-db34-472b-b7f7-e5905f611e9b
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/d5fb92b7-02fa-4c16-93f5-aa1bea70f095
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/7f0a0fa9-b682-47d2-a7f8-2f8ac0ebb732
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/ac0c03ed-e0ce-4ded-b0e1-f480be296eaa
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/9e5742e4-adae-4178-9951-7372adeb7ffc
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/320c14a2-1428-4904-b978-6fe06b3e25bf
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/3d4a9683-b70a-4953-b21b-b3ea07d693a3
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/d52b97ba-8199-4877-b210-e7575cbdcaf2
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/513ddbc1-0b68-4200-bb2e-ce920fa601aa
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/715fca08-b496-404a-bd6a-aa7124c4b1b8
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/d21f4583-a05d-4a94-8404-f1e02a332283
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/39c5a2d4-01d0-46ce-8943-0591ff9ee77e
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/90e8ed28-e44b-48da-b06c-a54bc71f053a
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/98c48b7c-f07c-4be2-a769-715582fa09ca
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/6a53c940-c291-4aa9-ab41-f4d1813ac786
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found before cutoff - ignoring as duplicate https://www.ft.com/content/b8343f05-0327-4de5-80b4-2d65082b67f0
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.wired.com/story/googles-ai-overviews-can-scam-you-heres-how-to-stay-safe/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.investopedia.com/here-is-how-much-palo-alto-networks-stock-is-expected-to-move-after-earnings-tuesday-q2-fy2026-panw-11905327
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.windowscentral.com/artificial-intelligence/microsoft-confirms-plan-to-ditch-openai-as-the-chatgpt-firm-continues-to-beg-big-tech-for-cash
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/this-wealth-creating-machine-continues-to-deliver/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/forgent-ipo-bringing-sexy-back-110200316.html
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.geeky-gadgets.com/claude-code-marketing-guide/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://futurism.com/artificial-intelligence/openai-researcher-quit-ads
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/the-best-dividend-stocks-to-buy-and-hold-forever/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://hackernoon.com/the-7-layer-blueprint-for-serving-securing-and-observing-ai-agents-at-scale
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.wired.com/story/ai-fancy-footwear-and-all-the-other-gear-powering-olympic-bobsledding/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/
07:32:20 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/should-you-buy-coreweave-before-feb-26/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/leaders-protecting-culture-while-ai-100000740.html
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/3-cheap-magnificent-seven-stocks-to-buy-hand-over/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://fortune.com/2026/02/14/anthropic-ceo-dario-amodei-spending-capex-risk-ai-revenue-forecasts-bankruptcy/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.salon.com/2026/02/15/swarms-of-ai-bots-are-threatening-democracy-partner/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/nvidia-stock-good-news-amazon-google-meta-microsof/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/palantir-stock-to-avoid-or-once-in-a-decade-buying/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://news.google.com/rss/articles/CBMiswFBVV95cUxNSVQ5VUladlZKWUd5QXZiczFtbEc5RzZHQ2xKNHpNenlxQ3VSSzc0WjctQkVzaDhRSWNkSng5Q3hCU0FRVlQ3eS0tbTE5amVsS0Q4SjhfVjF5STQ1cGdUNHVvc0V5RXNQTVp3cnVtR1ZMZC1mcHZ6QUNQVXVMWjRpRVNNR3ZOQTFIekxDWW9vRU5sdGlxazlhdUFfR19LUFdydG1YSU0tMWhBcTZ5bjQwMnhKWQ
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/investing-stock-picks-market-ai-tech-stocks-prediction-markets-glp1-2026-2
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/anthropic-president-ai-humanities-majors-more-important-2026-2
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.businessinsider.com/amazon-tech-manager-laid-off-after-11-years-refreshing-change-2026-2
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/could-investing-x-in-hot-ticker-make-you-richer/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/software-bear-market-5-best-of-breed-software-stoc/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/where-will-alphabet-be-in-5-years/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://margaretstorey.com/blog/2026/02/09/cognitive-debt/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.seangoedecke.com/fast-llm-inference/
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.theguardian.com/technology/2026/feb/15/ai-dating-apps-personality-matchmaking
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.tomsguide.com/ai/i-use-the-onion-prompt-with-chatgpt-when-im-buried-in-tasks-it-cuts-through-clutter-in-seconds
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/news-corporation-nwsa-pt-lowered-062927850.html
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.cnn.com/2026/02/15/business/warsh-fed-cuts-ai
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/citi-raises-roivant-sciences-roiv-062936393.html
07:32:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | found after cutoff - keeping https://www.zacks.com/stock/news/2869295/the-surge-in-micron-technology-stock-looks-poised-to-continue

================================================================================
⏱️  Total execution time: 70.96s
📊 Final result:
✅ Step 2 filter_urls completed successfully! Removed 431 duplicate URLs, classified 356 new articles, found 145 AI-related.

In [17]:
state.clear_errors()

In [18]:
headline_df = pd.DataFrame(state.headline_data)
headline_df

,source,title,url,published,rss_summary,id,isAI
0,Ars Technica,I spent two days gigging at RentAHuman and did...,https://arstechnica.com/ai/2026/02/i-spent-two...,NaN,NaN,0,False
1,Ars Technica,NASA has a new problem to fix before the next ...,https://arstechnica.com/space/2026/02/nasa-chi...,NaN,NaN,6,False
2,Ars Technica,"WHO slams US-funded newborn vaccine trial as ""...",https://arstechnica.com/health/2026/02/who-sla...,NaN,NaN,7,False
3,Ars Technica,$1.8 million MST3K Kickstarter brings in (almo...,https://arstechnica.com/culture/2026/02/1-8-mi...,NaN,NaN,8,False
4,Bloomberg,AI Risk Is Dominating Conference Calls as Inve...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,29,True
...,...,...,...,...,...,...,...
351,NewsAPI,Young & Hungry Digital Marketing Announces AI-...,https://digitalmarketreports.com/news/61412/yo...,2026-02-14T12:17:26Z,NaN,781,True
352,NewsAPI,Rishi Sunak: Every CEO is talking about AI — w...,https://www.thetimes.com/business/companies-ma...,2026-02-14T12:13:32Z,NaN,782,True
353,NewsAPI,OpenAI Launches OpenAI for Healthcare: 4 Key F...,https://blockchain.news/flashnews/openai-launc...,2026-02-14T07:59:41Z,NaN,783,True
354,NewsAPI,Sultan bin Ahmed visits Huawei R&D Centre and ...,https://en.antaranews.com/news/404578/sultan-b...,2026-02-14T10:01:18Z,NaN,784,False
355,NewsAPI,SMU Launches New Master of Science in Business...,https://en.antaranews.com/news/404566/smu-laun...,2026-02-14T08:47:50Z,NaN,785,True

In [19]:
# User prompt to run workflow
# user_prompt = "Run step 3, download full articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("download_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

07:34:18 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting Step 3: Download Articles
07:34:18 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting concurrent scraping of 145 AI-related articles

▶ Starting Step 3: download_articles

07:34:18 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Launching browser for 145 URLs with 12 concurrent workers
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 0 fetching 1 of 145 https://finance.yahoo.com/news/ibm-tripling-number-gen-z-164332214.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://finance.yahoo.com/news/ibm-tripling-number-gen-z-164332214.html)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://finance.yahoo.com/news/ibm-tripling-number-gen-z-164332214.html to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://finance.yahoo.com/news/ibm-tripling-number-gen-z-164332214.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 1 fetching 2 of 145 https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878 to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 2 fetching 3 of 145 https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/ to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 fetching 4 of 145 https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/ to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 4 fetching 5 of 145 https://www.thetimes.com/business/companies-markets/article/rishi-sunak-ai-keir-starmer-5rdfwjq6n
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.thetimes.com/business/companies-markets/article/rishi-sunak-ai-keir-starmer-5rdfwjq6n)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.thetimes.com/business/companies-markets/article/rishi-sunak-ai-keir-starmer-5rdfwjq6n to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.thetimes.com/business/companies-markets/article/rishi-sunak-ai-keir-starmer-5rdfwjq6n
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 5 fetching 6 of 145 https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.bloomberg.com
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 5 completed https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale with status: skipped
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 5 fetching 7 of 145 https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.wsj.com
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 5 completed https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1 with status: skipped
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 5 fetching 8 of 145 https://techdeals.net/exploring-ai-ethics-can-anthropic-philosophers-instill-a-soul-in-claude-to-navigate-morality/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://techdeals.net/exploring-ai-ethics-can-anthropic-philosophers-instill-a-soul-in-claude-to-navigate-morality/)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://techdeals.net/exploring-ai-ethics-can-anthropic-philosophers-instill-a-soul-in-claude-to-navigate-morality/ to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://techdeals.net/exploring-ai-ethics-can-anthropic-philosophers-instill-a-soul-in-claude-to-navigate-morality/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 6 fetching 9 of 145 https://www.livemint.com/companies/news/can-ai-outperform-humans-airbnb-chief-brian-chesky-bets-on-bots-replaces-one-third-of-customer-service-staff-11771061235926.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.livemint.com/companies/news/can-ai-outperform-humans-airbnb-chief-brian-chesky-bets-on-bots-replaces-one-third-of-customer-service-staff-11771061235926.html)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.livemint.com/companies/news/can-ai-outperform-humans-airbnb-chief-brian-chesky-bets-on-bots-replaces-one-third-of-customer-service-staff-11771061235926.html to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.livemint.com/companies/news/can-ai-outperform-humans-airbnb-chief-brian-chesky-bets-on-bots-replaces-one-third-of-customer-service-staff-11771061235926.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 7 fetching 10 of 145 https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 8 fetching 11 of 145 https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290 to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 9 fetching 12 of 145 https://www.fool.com/coverage/stock-market-today/2026/02/13/stock-market-today-feb-13-inflation-data-steadies-market-and-slows-ai-disruption-losses/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.fool.com/coverage/stock-market-today/2026/02/13/stock-market-today-feb-13-inflation-data-steadies-market-and-slows-ai-disruption-losses/)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.fool.com/coverage/stock-market-today/2026/02/13/stock-market-today-feb-13-inflation-data-steadies-market-and-slows-ai-disruption-losses/ to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.fool.com/coverage/stock-market-today/2026/02/13/stock-market-today-feb-13-inflation-data-steadies-market-and-slows-ai-disruption-losses/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 10 fetching 13 of 145 https://finance.yahoo.com/news/forgent-ipo-bringing-sexy-back-110200316.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Rate limiting domain finance.yahoo.com, will retry later (need to wait 1.6s)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 10 re-queued rate-limited URL: https://finance.yahoo.com/news/forgent-ipo-bringing-sexy-back-110200316.html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 11 fetching 13 of 145 https://www.geeky-gadgets.com/claude-code-marketing-guide/
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.geeky-gadgets.com/claude-code-marketing-guide/)
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.geeky-gadgets.com/claude-code-marketing-guide/ to download/html
07:34:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.geeky-gadgets.com/claude-code-marketing-guide/
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 10 fetching 14 of 145 https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.bloomberg.com
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 10 completed https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion with status: skipped
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 10 fetching 15 of 145 https://www.notebookcheck.net/Light-based-chip-claims-100x-faster-more-efficient-performance-than-Nvidia-A100.1226286.0.html
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.notebookcheck.net/Light-based-chip-claims-100x-faster-more-efficient-performance-than-Nvidia-A100.1226286.0.html)
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.notebookcheck.net/Light-based-chip-claims-100x-faster-more-efficient-performance-than-Nvidia-A100.1226286.0.html to download/html
07:34:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.notebookcheck.net/Light-based-chip-claims-100x-faster-more-efficient-performance-than-Nvidia-A100.1226286.0.html
07:34:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 401
07:34:28 | NewsletterAgent.test_newsletter_20260215073155703123 | ERROR | HTTP error scraping https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878: unauthorized error 401
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 1 completed https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878 with status: 401
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 1 fetching 16 of 145 https://www.axios.com/2026/02/13/vc-unicorn-companies
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.axios.com/2026/02/13/vc-unicorn-companies)
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.axios.com/2026/02/13/vc-unicorn-companies to download/html
07:34:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.axios.com/2026/02/13/vc-unicorn-companies
07:34:32 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:36 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:45 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:34:49 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Saving HTML to download/html/iflow-mcp_adam-paterson-mcp-crew-ai_0.1.0.html
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 2 completed https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/ with status: 200
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 2 fetching 17 of 145 https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2)
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2 to download/html
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Page URL redirected from https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc to https://www.tipranks.com/news/amd-stock-faces-an-ai-reality-check-says-top-analyst
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Saving HTML to download/html/AMD_Stock_Faces_an_AI_Reality_Check__Says_Top_Analyst.html
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 7 completed https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc with status: 200
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 7 fetching 18 of 145 https://theconversation.com/swarms-of-ai-bots-can-sway-peoples-beliefs-threatening-democracy-274778
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://theconversation.com/swarms-of-ai-bots-can-sway-peoples-beliefs-threatening-democracy-274778)
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scraping https://theconversation.com/swarms-of-ai-bots-can-sway-peoples-beliefs-threatening-democracy-274778 to download/html
07:35:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Downloading https://theconversation.com/swarms-of-ai-bots-can-sway-peoples-beliefs-threatening-democracy-274778
07:35:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:35:59 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Response: 200
07:35:59 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Saving HTML to download/html/AI_Adoption_Rises_Among_Indian_Screenwriters_as_Pay__Credit_Gaps_Persist__Tulsea_Ormax_Report_Finds__EXCLUSIVE.html
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 completed https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/ with status: 200
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 fetching 19 of 145 https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.bloomberg.com
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 completed https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout with status: skipped
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 fetching 20 of 145 https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.wsj.com
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 completed https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921 with status: skipped
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 fetching 21 of 145 https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Skipping ignored domain: www.wsj.com
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 completed https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b with status: skipped
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Worker 3 fetching 22 of 145 https://news.google.com/rss/articles/CBMiswFBVV95cUxNSVQ5VUladlZKWUd5QXZiczFtbEc5RzZHQ2xKNHpNenlxQ3VSSzc0WjctQkVzaDhRSWNkSng5Q3hCU0FRVlQ3eS0tbTE5amVsS0Q4SjhfVjF5STQ1cGdUNHVvc0V5RXNQTVp3cnVtR1ZMZC1mcHZ6QUNQVXVMWjRpRVNNR3ZOQTFIekxDWW9vRU5sdGlxazlhdUFfR19LUFdydG1YSU0tMWhBcTZ5bjQwMnhKWQ
07:36:00 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | scrape_url(https://news.google.com/rss/articles/CBMiswFBVV95cUxNSVQ5VUladlZKWUd5QXZiczFtbEc5RzZHQ2xKNHpNenlxQ3VSSzc0WjctQkVzaDhRSWNkSng5Q3hCU0FRVlQ3eS0tbTE5amVsS0Q4SjhfVjF5STQ1cGdUNHVvc0V5RXNQTVp3cnVtR1ZMZC1mcHZ6QUNQVXVMWjRpRVNNR3ZOQTFIekxDWW9vRU5sdGlxazlhdUFfR19LUFdydG1YSU0tMWhBcTZ5bjQwMnhKWQ)

Starting with 145 rows...
Processing 145 files...
Reading and truncating files to 8192 tokens using text-embedding-3-large tokenizer...

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Getting embeddings for 122 texts...

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

Creating indexed similarity matrix...
Finding pairs with similarity > 0.925...
Filtering dataframe...
  Pair: 90 vs 30
    90: HackerNoon - AOrchestra Turns AI Agents Into On-Demand Specialists (Not Static Roles)
    90: https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles?source=rss
    30: Feedly AI - AOrchestra Turns AI Agents Into On-Demand Specialists (Not Static Roles)
    30: https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles
  Pair: 35 vs 98
    35: Feedly AI - Swarms of AI bots are threatening democracy
    35: https://www.salon.com/2026/02/15/swarms-of-ai-bots-are-threatening-democracy-partner/
    98: Reddit - Swarms of AI bots can sway people’s beliefs – threatening democracy
    98: https://theconversation.com/swarms-of-ai-bots-can-sway-peoples-beliefs-threatening-democracy-274778
  Pair: 56 vs 132
    56: Feedly AI - AI film school trains next generation of Hollywood moviemakers
    56: https://www.reuters.com/business/media-telecom/ai-film-school-trains-next-generation-hollywood-moviemakers-2026-02-14/
    132: NewsAPI - AI film school trains next generation of Hollywood moviemakers
    132: https://www.channelnewsasia.com/business/ai-film-school-trains-next-generation-hollywood-moviemakers-5931501
  Pair: 134 vs 66
    134: NewsAPI - How 100‑year‑old Caterpillar went from making construction equipment to becoming an AI market darling
    134: https://fortune.com/2026/02/14/how-100-year-old-caterpillar-became-an-ai-market-darling/
    66: Feedly AI - How 100‑year‑old Caterpillar went from making construction equipment to becoming an AI market darling
    66: https://finance.yahoo.com/news/100-old-caterpillar-went-making-120000061.html
Removing 4 rows due to high similarity
Final dataframe has 141 rows (removed 4 rows)
Missing files:

,title,status,final_url
9,AI Startup Legora in Talks to Triple Valuation to $6 Billion,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion
8,Shield AI in Talks to Raise $1 Billion at $12 Billion Valuation,skipped,https://www.bloomberg.com/news/articles/2026-02-13/shield-ai-in-talks-to-raise-1-billion-at-12-billion-valuation
133,AI tool Claude helped capture Venezuelan dictator Nicolás Maduro in US military raid operation: report,404,https://www.foxnews.com/us/ai-tool-claude-helped-capture-venezuelan-dictator-maduro-us-military-raid-operation-report%20
6,Companies May 'Spend to Defend' AI Risk: Moody's Pinto,skipped,https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
5,"FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
4,Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout,skipped,https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
3,"AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
2,AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
7,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",skipped,https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy
83,Stock Market Suffers AI-Inspired Meltdown. The Real World Wins Again.,401,https://www.barrons.com/articles/stock-market-suffers-ai-inspired-meltdown-31fde781
124,You’ve Got Mail—but Is It From a Person or a Chatbot?,skipped,https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd
123,Meet Anthropic’s AI Morality Teacher,skipped,https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921
122,"When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled",skipped,https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1
121,Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid,skipped,https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17
82,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,401,https://www.barrons.com/articles/ai-american-exceptionalism-stock-market-303f8db6
114,"Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO",skipped,https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
110,"Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.",403,https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation
49,China Deploys a ‘National Team’ of Investors to Keep AI Stock Boom in Check,skipped,https://www.wsj.com/finance/stocks/china-deploys-a-national-team-of-investors-to-keep-ai-stock-boom-in-check-c3d9534a
105,"ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year",401,https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/
60,"Stocks Rise on Softer Inflation Data, but AI Jitters Trigger Worst Week Since November",skipped,https://www.wsj.com/finance/stocks/stocks-rise-on-softer-inflation-data-but-ai-jitters-trigger-worst-week-since-november-611bd7ca
1,AI Bubble Fears Are Creating New Derivatives,skipped,https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
81,Week’s Best: AI Slams Wealth Management Stocks,401,https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878
0,AI Risk Is Dominating Conference Calls as Investors Dump Stocks,skipped,https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks

07:56:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Completed Step 3: Downloaded 122 articles

================================================================================
⏱️  Total execution time: 1324.26s
📊 Final result:
✅ Step 3 download_articles completed successfully! Total articles: 356; AI-related articles: 141; HTML files: 118; Text files: 118

In [20]:
headline_df = state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df[['id', 'source', 'title', 'status', 'final_url']].loc[headline_df["html_path"]==""])

,id,source,title,status,final_url
118,51,Bloomberg,AI Startup Legora in Talks to Triple Valuation to $6 Billion,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion
119,50,Bloomberg,Shield AI in Talks to Raise $1 Billion at $12 Billion Valuation,skipped,https://www.bloomberg.com/news/articles/2026-02-13/shield-ai-in-talks-to-raise-1-billion-at-12-billion-valuation
120,761,NewsAPI,AI tool Claude helped capture Venezuelan dictator Nicolás Maduro in US military raid operation: report,404,https://www.foxnews.com/us/ai-tool-claude-helped-capture-venezuelan-dictator-maduro-us-military-raid-operation-report%20
121,44,Bloomberg,Companies May 'Spend to Defend' AI Risk: Moody's Pinto,skipped,https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
122,42,Bloomberg,"FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
123,37,Bloomberg,Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout,skipped,https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
124,36,Bloomberg,"AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
125,35,Bloomberg,AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
126,49,Bloomberg,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",skipped,https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy
127,262,Feedly AI,Stock Market Suffers AI-Inspired Meltdown. The Real World Wins Again.,401,https://www.barrons.com/articles/stock-market-suffers-ai-inspired-meltdown-31fde781
128,691,WSJ,You’ve Got Mail—but Is It From a Person or a Chatbot?,skipped,https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd
129,689,WSJ,Meet Anthropic’s AI Morality Teacher,skipped,https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921
130,688,WSJ,"When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled",skipped,https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1
131,685,WSJ,Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid,skipped,https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17
132,257,Feedly AI,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,401,https://www.barrons.com/articles/ai-american-exceptionalism-stock-market-303f8db6
133,442,Techmeme,"Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO",skipped,https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
134,434,Techmeme,"Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.",403,https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation
135,182,Feedly AI,China Deploys a ‘National Team’ of Investors to Keep AI Stock Boom in Check,skipped,https://www.wsj.com/finance/stocks/china-deploys-a-national-team-of-investors-to-keep-ai-stock-boom-in-check-c3d9534a
136,426,Techmeme,"ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year",401,https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/
137,217,Feedly AI,"Stocks Rise on Softer Inflation Data, but AI Jitters Trigger Worst Week Since November",skipped,https://www.wsj.com/finance/stocks/stocks-rise-on-softer-inflation-data-but-ai-jitters-trigger-worst-week-since-november-611bd7ca
138,30,Bloomberg,AI Bubble Fears Are Creating New Derivatives,skipped,https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
139,255,Feedly AI,Week’s Best: AI Slams Wealth Management Stocks,401,https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878
140,29,Bloomberg,AI Risk Is Dominating Conference Calls as Investors Dump Stocks,skipped,https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks

In [21]:
state.clear_errors()

In [22]:
# User prompt to run workflow
# user_prompt = "Run step 4, Summarize articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("extract_summaries")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

07:56:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 141 AI articles for summarization

▶ Starting Step 4: extract_summaries

07:56:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/extract_summaries' from Langfuse
07:56:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/extract_summaries': model=gpt-5-mini, reasoning_effort=medium, system_len=1272, user_len=42
07:56:22 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Using model 'gpt-5-mini' for summarization
07:56:23 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting summarization for 141 articles
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:56:39 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Extracting metadata from HTML files for 141 articles
07:56:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/item_distiller' from Langfuse
07:56:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/item_distiller': model=gpt-5-mini, reasoning_effort=medium, system_len=1636, user_len=190
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

================================================================================
⏱️  Total execution time: 46.35s
📊 Final result:
✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 141/141 articles.
💾 Summaries stored in headline DataFrame.

In [23]:
# if we get a refusal, examine why and delete any bad rows, e.g. blog posts about black hat hacking
bad_stuff =["Anthropic's Jack Cla",
           ]
print([len(s) for s in bad_stuff])
headline_df = state.headline_df
headline_df.loc[(headline_df["title"].str[:20].isin(bad_stuff))]

[20]

Empty DataFrame
Columns: [source, title, url, published, rss_summary, id, isAI, status, final_url, html_path, last_updated, text_path, content_length, domain, site_name, reputation, summary, description, tags, short_summary]
Index: []

In [24]:
# remove bad stuff
state.headline_df_to_dict(headline_df.loc[~headline_df["title"].str[:20].isin(bad_stuff)])

In [25]:
# User prompt to run workflow
# user_prompt = "Run step 5, Rate articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("rate_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Rating 141 AI articles using fn_rate_articles
07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Calculating article ratings for 141 articles
07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Rating recency
07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Rating spam probability
07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/rate_quality' from Langfuse
07:57:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/rate_quality': model=gpt-4.1, reasoning_effort=medium, system_len=1849, user_len=246
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

▶ Starting Step 5: rate_articles

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:16 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | low quality articles: {0.0: 110, 1.0: 23, 7.05287985111216e-11: 1, 0.9999937270200764: 1, 0.029312225847906822: 1, 0.9998415274892719: 1, 0.9975274032511579: 1, 2.020683909022217e-11: 1, 0.37754062298658986: 1}
07:57:16 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/rate_on_topic' from Langfuse
07:57:16 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/rate_on_topic': model=gpt-4.1, reasoning_effort=medium, system_len=1789, user_len=239
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

,id,site_name,title,bradley_terry,bt_z
126,126,Resilience Media,"Dealroom and NATO Innovation Fund: European defense, security, and resilience startup funding rose 55% YoY to a record $8.7B in 2025, with AI accounting for 44%",25.960425,1.584699
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",24.098949,1.471069
79,79,Salon,Swarms of AI bots are threatening democracy,24.098949,1.471069
14,14,The Register,How AI could eat itself: Competitors can probe models to steal their secrets and clone them,24.098949,1.471069
34,34,The Register,Investors shove another $30B into the Anthropic money furnace,24.098949,1.471069
...,...,...,...,...,...
82,82,Reuters,"ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year",-24.098949,-1.471069
86,86,TechRadar,"“The next big lemming-like rush will be toartificial intelligence”: While 1985 was hailed as the year of AI, Bill Gates ignored the hype to focus on ‘softer software’",-24.098949,-1.471069
98,98,TechDeals,"Exploring AI Ethics: Can Anthropic Philosophers Instill a ""Soul"" in Claude to Navigate Morality?",-24.098949,-1.471069
49,49,Bloomberg,Companies May 'Spend to Defend' AI Risk: Moody's Pinto,-24.098949,-1.471069
121,121,Antara News,SMU Launches New Master of Science in Business AI to Build Singapore's AI-Ready Business Leadership Talent,-27.013451,-1.648979

07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [126, 87, 79, 14, 34, 27, 102, 37, 43, 73]
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 1/28:
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 139
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 6592.0 (avg rank chg 47.09)
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 2 of max 28
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 24 battle batches
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 142 ; Total stories: 140
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 24 pre-formed batches
07:57:33 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 24 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 702
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",84.062101,2.094836
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",77.198650,1.923798
79,79,Salon,Swarms of AI bots are threatening democracy,75.371005,1.878253
57,57,TechCrunch,"Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally (Sarah Perez/TechCrunch)",75.000047,1.869008
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,72.708484,1.811902
...,...,...,...,...,...
42,42,Bloomberg,AI Bubble Fears Are Creating New Derivatives,-73.950236,-1.842847
75,75,Financial Times,What kind of AI disruption victim are you?,-73.990369,-1.843847
108,108,Reddit,Fixing childhood trauma with AI - Artax LIVES,-74.630168,-1.859791
82,82,Reuters,"ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year",-82.697828,-2.060838
44,44,Financial Times,The AI productivity take-off is finally visible,-83.734777,-2.086679

07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 116, 79, 57, 100, 110, 27, 3, 37, 48]
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 2/28:
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 136
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 6460.0 (avg rank chg 46.14)
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 3 of max 28
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 25 battle batches
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 141 ; Total stories: 140
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 pre-formed batches
07:57:38 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 1042
07:57:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",190.665605,2.140832
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,182.793371,2.052441
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",175.594186,1.971607
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,168.776573,1.895057
57,57,TechCrunch,"Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally (Sarah Perez/TechCrunch)",163.381633,1.834482
...,...,...,...,...,...
75,75,Financial Times,What kind of AI disruption victim are you?,-138.048138,-1.550032
113,113,Reddit,Chatgpt helped me get an abusive manager fired when other employees failed to report his abuse,-138.239649,-1.552183
82,82,Reuters,"ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year",-138.629240,-1.556557
42,42,Bloomberg,AI Bubble Fears Are Creating New Derivatives,-145.660558,-1.635506
44,44,Financial Times,The AI productivity take-off is finally visible,-153.749167,-1.726327

07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 57, 79, 3, 27, 88, 61]
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 3/28:
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 130
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 6534.0 (avg rank chg 46.67)
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 4 of max 28
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 25 battle batches
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 141 ; Total stories: 140
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 pre-formed batches
07:57:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 1375
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",118.025164,1.942123
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,109.673474,1.804695
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",101.979350,1.678087
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,94.655757,1.557576
79,79,Salon,Swarms of AI bots are threatening democracy,87.584762,1.441221
...,...,...,...,...,...
71,71,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-98.861208,-1.626777
75,75,Financial Times,What kind of AI disruption victim are you?,-99.151707,-1.631557
108,108,Reddit,Fixing childhood trauma with AI - Artax LIVES,-99.293478,-1.633890
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-99.434665,-1.636214
44,44,Financial Times,The AI productivity take-off is finally visible,-100.088386,-1.646971

07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 27, 14, 57, 88, 3]
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 4/28:
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 123
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 6314.0 (avg rank chg 45.10)
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 5 of max 28
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 25 battle batches
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 146 ; Total stories: 140
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 pre-formed batches
07:57:48 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:53 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 1731
07:57:53 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",73.694350,4.217424
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,64.871786,3.712521
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",56.680509,3.243746
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,48.832034,2.794589
79,79,Salon,Swarms of AI bots are threatening democracy,41.206688,2.358201
...,...,...,...,...,...
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-23.314435,-1.334252
71,71,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-23.636826,-1.352702
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-23.789032,-1.361413
44,44,Financial Times,The AI productivity take-off is finally visible,-23.793662,-1.361678
75,75,Financial Times,What kind of AI disruption victim are you?,-24.595750,-1.407580

07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 27, 14, 88, 3, 57]
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 5/28:
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 115
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 5322.0 (avg rank chg 38.01)
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 6 of max 28
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 25 battle batches
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 143 ; Total stories: 140
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 pre-formed batches
07:57:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 25 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 2073
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",68.668966,5.054602
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,59.775780,4.399990
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",51.508692,3.791464
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,43.578684,3.207750
79,79,Salon,Swarms of AI bots are threatening democracy,35.865445,2.639992
...,...,...,...,...,...
71,71,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-16.019285,-1.179151
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-16.434476,-1.209713
44,44,Financial Times,The AI productivity take-off is finally visible,-16.481265,-1.213157
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-16.551497,-1.218327
75,75,Financial Times,What kind of AI disruption victim are you?,-17.500221,-1.288161

07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 27, 14, 88, 3, 126]
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 6/28:
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 110
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 5082.0 (avg rank chg 36.30)
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 7 of max 28
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 26 battle batches
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 142 ; Total stories: 140
07:57:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 pre-formed batches
07:57:59 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 2401
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",67.557293,5.357442
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,58.647788,4.650899
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",50.363098,3.993905
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,42.414104,3.363532
79,79,Salon,Swarms of AI bots are threatening democracy,34.680309,2.750225
...,...,...,...,...,...
71,71,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-14.149968,-1.122124
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-14.436804,-1.144870
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-14.701642,-1.165873
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-14.713941,-1.166848
75,75,Financial Times,What kind of AI disruption victim are you?,-15.804292,-1.253315

07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 27, 14, 88, 3, 34]
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 7/28:
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 96
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 5008.0 (avg rank chg 35.77)
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 8 of max 28
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 27 battle batches
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 147 ; Total stories: 140
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 pre-formed batches
07:58:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 2735
07:58:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.770021,5.217218
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,39.534695,4.229261
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.892966,3.304804
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,21.570393,2.307513
79,79,Salon,Swarms of AI bots are threatening democracy,21.570393,2.307513
...,...,...,...,...,...
71,71,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-11.462309,-1.226191
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-11.714651,-1.253186
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-11.935168,-1.276776
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-12.302508,-1.316072
75,75,Financial Times,What kind of AI disruption victim are you?,-13.450733,-1.438905

07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 14, 27, 88, 3, 34]
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 8/28:
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 103
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 4914.0 (avg rank chg 35.10)
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 9 of max 28
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 27 battle batches
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 146 ; Total stories: 140
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 pre-formed batches
07:58:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 3068
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.545377,5.340527
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,39.305439,4.324032
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.658560,3.372780
79,79,Salon,Swarms of AI bots are threatening democracy,21.330217,2.346559
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,21.330217,2.346559
...,...,...,...,...,...
44,44,Financial Times,The AI productivity take-off is finally visible,-10.957197,-1.205412
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-11.276628,-1.240553
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-11.547377,-1.270339
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.818710,-1.300188
75,75,Financial Times,What kind of AI disruption victim are you?,-13.025599,-1.432960

07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 34]
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 9/28:
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 86
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 3654.0 (avg rank chg 26.10)
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 10 of max 28
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 28 battle batches
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 142 ; Total stories: 140
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 28 pre-formed batches
07:58:14 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 28 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:18 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 3381
07:58:18 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.454761,5.373245
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,39.214577,4.348583
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.565636,3.389484
79,79,Salon,Swarms of AI bots are threatening democracy,21.234966,2.354788
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,21.234966,2.354788
...,...,...,...,...,...
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.721223,-1.188898
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-11.049035,-1.225250
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-11.173144,-1.239012
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.872853,-1.316604
75,75,Financial Times,What kind of AI disruption victim are you?,-12.920455,-1.432775

07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 61]
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 10/28:
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 87
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 4404.0 (avg rank chg 31.46)
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 11 of max 28
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 28 battle batches
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 149 ; Total stories: 140
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 28 pre-formed batches
07:58:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 28 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 3720
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.306076,5.424886
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,39.061426,4.386690
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.409031,3.415006
79,79,Salon,Swarms of AI bots are threatening democracy,21.074467,2.366712
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,21.074467,2.366712
...,...,...,...,...,...
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.670613,-1.198335
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.880001,-1.221850
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.956263,-1.230414
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.642279,-1.307455
75,75,Financial Times,What kind of AI disruption victim are you?,-12.656391,-1.421342

07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 61]
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 11/28:
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 84
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 4508.0 (avg rank chg 32.20)
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 12 of max 28
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 27 battle batches
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 154 ; Total stories: 140
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 pre-formed batches
07:58:24 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 4079
07:58:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.215653,5.447537
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.968979,4.402822
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.314660,3.425034
79,79,Salon,Swarms of AI bots are threatening democracy,20.977729,2.370121
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.977729,2.370121
...,...,...,...,...,...
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.663215,-1.204759
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.797210,-1.219898
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.908845,-1.232511
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.585645,-1.308978
75,75,Financial Times,What kind of AI disruption victim are you?,-12.636976,-1.427760

07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 101]
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 12/28:
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 65
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 2650.0 (avg rank chg 18.93)
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 13 of max 28
07:58:29 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:30 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 27 battle batches
07:58:30 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 150 ; Total stories: 140
07:58:30 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 pre-formed batches
07:58:30 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 4430
07:58:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.162732,5.478401
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.914876,4.426479
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.259156,3.441910
79,79,Salon,Swarms of AI bots are threatening democracy,20.920846,2.379699
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.920846,2.379699
...,...,...,...,...,...
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.561348,-1.201329
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.654460,-1.211921
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.697012,-1.216761
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.485709,-1.306473
75,75,Financial Times,What kind of AI disruption victim are you?,-12.572486,-1.430092

07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 61]
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 13/28:
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 66
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 3226.0 (avg rank chg 23.04)
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 14 of max 28
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 26 battle batches
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 147 ; Total stories: 140
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 pre-formed batches
07:58:35 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:40 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 4778
07:58:40 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.126104,5.504730
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.877487,4.446861
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.220935,3.456712
79,79,Salon,Swarms of AI bots are threatening democracy,20.881661,2.388473
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.881661,2.388473
...,...,...,...,...,...
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.478687,-1.198567
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.583155,-1.210516
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.616666,-1.214349
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.371744,-1.300716
75,75,Financial Times,What kind of AI disruption victim are you?,-12.467614,-1.426063

07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 101]
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 14/28:
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 50
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 2420.0 (avg rank chg 17.29)
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 15 of max 28
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 26 battle batches
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 143 ; Total stories: 140
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 pre-formed batches
07:58:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 26 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:45 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 5110
07:58:45 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.152178,5.516974
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.904412,4.457423
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.248478,3.465681
79,79,Salon,Swarms of AI bots are threatening democracy,20.909891,2.395724
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.909891,2.395724
...,...,...,...,...,...
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.371411,-1.188291
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.486047,-1.201425
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.512870,-1.204499
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.289738,-1.293507
75,75,Financial Times,What kind of AI disruption victim are you?,-12.355794,-1.415649

07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 79, 110, 14, 27, 88, 3, 101]
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 15/28:
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 45
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 2488.0 (avg rank chg 17.77)
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 17.53, prev_two: 20.99
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 16 of max 28
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 27 battle batches
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 143 ; Total stories: 140
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 pre-formed batches
07:58:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 27 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:51 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 5432
07:58:51 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.102499,5.519529
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.853879,4.458294
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.196767,3.464933
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.857142,2.393256
79,79,Salon,Swarms of AI bots are threatening democracy,20.857142,2.393256
...,...,...,...,...,...
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.374139,-1.190382
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.478449,-1.202351
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.515630,-1.206618
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.296112,-1.296174
75,75,Financial Times,What kind of AI disruption victim are you?,-12.360009,-1.418251

07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 14, 27, 88, 3, 101]
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 16/28:
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 38
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 1728.0 (avg rank chg 12.34)
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 15.06, prev_two: 20.16
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 17 of max 28
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 30 battle batches
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 142 ; Total stories: 140
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 30 pre-formed batches
07:58:52 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 30 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 5712
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.006436,5.577115
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.755600,4.502405
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.096278,3.496414
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.753890,2.411069
79,79,Salon,Swarms of AI bots are threatening democracy,20.753889,2.411069
...,...,...,...,...,...
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.115414,-1.175151
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.226214,-1.188023
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.257676,-1.191678
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.042826,-1.282893
75,75,Financial Times,What kind of AI disruption victim are you?,-12.102819,-1.406037

07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 14, 27, 88, 3, 101]
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 17/28:
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 49
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 2454.0 (avg rank chg 17.53)
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 14.94, prev_two: 17.53
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 18 of max 28
07:58:57 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:58:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 31 battle batches
07:58:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 145 ; Total stories: 140
07:58:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 31 pre-formed batches
07:58:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 31 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:59:02 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 5987
07:59:02 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.075764,5.557203
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.827960,4.488225
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.170717,3.487512
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.830162,2.407813
79,79,Salon,Swarms of AI bots are threatening democracy,20.830162,2.407813
...,...,...,...,...,...
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.186059,-1.177433
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.296001,-1.190142
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.327267,-1.193756
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.138766,-1.287559
75,75,Financial Times,What kind of AI disruption victim are you?,-12.183548,-1.408328

07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 27, 14, 88, 3, 101]
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 18/28:
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 25
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 986.0 (avg rank chg 7.04)
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 12.29, prev_two: 15.06
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 19 of max 28
07:59:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:59:04 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 33 battle batches
07:59:04 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 143 ; Total stories: 140
07:59:04 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 33 pre-formed batches
07:59:04 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 33 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:59:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 6240
07:59:08 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.083086,5.566961
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.834499,4.496179
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.177088,3.493841
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.836709,2.412431
79,79,Salon,Swarms of AI bots are threatening democracy,20.836708,2.412431
...,...,...,...,...,...
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.014313,-1.159437
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.114565,-1.171044
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.249027,-1.186611
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.058717,-1.280356
75,75,Financial Times,What kind of AI disruption victim are you?,-12.122026,-1.403463

07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 14, 27, 88, 3, 101]
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 19/28:
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 47
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 2462.0 (avg rank chg 17.59)
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 12.31, prev_two: 14.94
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Running round 20 of max 28
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | ---------------------------------------------------
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generated 35 battle batches
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Total stories in batches: 146 ; Total stories: 140
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 35 pre-formed batches
07:59:09 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 35 battles with concurrency = 1000
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
07:59:13 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | total battles: 6482
07:59:13 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputing Bradley-Terry ratings
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Recomputed Bradley-Terry ratings
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
87,87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",48.048028,5.567321
100,100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,38.797878,4.495507
116,116,The Motley Fool,"Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft",30.139493,3.492261
110,110,HuffPost,Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections,20.798178,2.409883
79,79,Salon,Swarms of AI bots are threatening democracy,20.798177,2.409883
...,...,...,...,...,...
135,135,Kuriositas,That’s AI (Artificial Intelligence),-10.045358,-1.163955
136,136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,-10.144606,-1.175455
137,137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,-10.272634,-1.190289
127,127,Yahoo,The 5 Best Artificial Intelligence (AI) Stocks to Buy for February,-11.103819,-1.286599
75,75,Financial Times,What kind of AI disruption victim are you?,-12.209712,-1.414738

07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Top 10 ids: [87, 100, 116, 110, 79, 14, 27, 88, 3, 101]
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | After round 20/28:
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Number of ranking changes: 36
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sum of absolute ranking changes: 1870.0 (avg rank chg 13.36)
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | last_two: 15.47, prev_two: 12.29
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Increase in avg rank change, stopping
07:59:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Low rated articles: 0
07:59:16 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Sent email with 140 rated articles

================================================================================
⏱️  Total execution time: 127.83s
📊 Final result:
✅ Step 5 rate_articles completed successfully! Rated 140 articles with average rating 6.2/10.
⭐ High quality articles (≥7.0): 45
💾 Ratings stored in persistent state.

In [26]:
headline_df

,source,title,url,published,rss_summary,id,isAI,status,final_url,html_path,last_updated,text_path,content_length,domain,site_name,reputation,summary,description,tags,short_summary
0,Techmeme,Q&A with Dario Amodei on getting close to “a c...,https://www.dwarkesh.com/p/dario-amodei-2,NaN,NaN,438,True,200,https://www.dwarkesh.com/p/dario-amodei-2,download/html/Q_A_with_Dario_Amodei_on_getting...,2026-02-13T16:46:36Z,download/text/Q_A_with_Dario_Amodei_on_getting...,36976,dwarkesh.com,Dwarkesh,0.0,"- ""We are near the end of the exponential"" — D...","""That's why I'm sending this message of urgency""",[],Dario Amodei says AI gains are driven by compu...
1,Feedly AI,AOrchestra Turns AI Agents Into On-Demand Spec...,https://hackernoon.com/aorchestra-turns-ai-age...,NaN,NaN,132,True,200,https://hackernoon.com/aorchestra-turns-ai-age...,download/html/AOrchestra_Turns_AI_Agents_Into_...,2026-02-15T07:46:14Z,download/text/AOrchestra_Turns_AI_Agents_Into_...,30438,hackernoon.com,Hacker Noon,2.0,- Problem + technical approach: AOrchestra ref...,<p><em>This is a Plain English Papers summary ...,[ai],"AOrchestra, a framework that composes on-deman..."
2,Techmeme,A matplotlib maintainer explains how an AI age...,https://theshamblog.com/an-ai-agent-published-...,NaN,NaN,432,True,200,https://theshamblog.com/an-ai-agent-published-...,download/html/A_matplotlib_maintainer_explains...,2026-02-14T00:24:47Z,download/text/A_matplotlib_maintainer_explains...,24623,theshamblog.com,The Sham Blog,0.0,- An autonomous OpenClaw AI agent (identity: M...,Context: An AI agent of unknown ownership auto...,[],An autonomous OpenClaw AI agent 'MJ Rathbun' o...
3,Hacker News,OpenAI should build Slack,https://www.latent.space/p/ainews-why-openai-s...,"Sat, 14 Feb 2026 07:50:13 +0000","<a href=""https://news.ycombinator.com/item?id=...",284,True,200,https://www.latent.space/p/ainews-why-openai-s...,download/html/OpenAI_should_build_Slack.html,2026-02-14T07:48:54Z,download/text/OpenAI_should_build_Slack.txt,22931,latent.space,Latent Space,0.0,"- Sam Altman's ""tell us what we should build, ...",a quiet day lets us answer a Sam Altman questi...,[],Developer swyx argues OpenAI should build a Sl...
4,Feedly AI,The Psychology Of What Happens When You Get AI...,https://www.forbes.com/sites/lanceeliot/2026/0...,NaN,NaN,164,True,200,https://www.forbes.com/sites/lanceeliot/2026/0...,download/html/The_Psychology_Of_What_Happens_W...,2026-02-15T08:15:00Z,download/text/The_Psychology_Of_What_Happens_W...,19623,forbes.com,Forbes,1.0,"- New study: ""Can LLMs Get High? A Dual-Metric...",What happens when AI pretends to be on psyched...,[artificial intelligence generative large lang...,"Researchers (Ben‑Zion, Research Square, Feb 2,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Techmeme,"ByteDance launches Doubao 2.0, an “agent era” ...",https://www.reuters.com/world/asia-pacific/chi...,NaN,NaN,426,True,401,https://www.reuters.com/world/asia-pacific/chi...,,NaN,,0,reuters.com,Reuters,2.0,- no content,,[],"ByteDance launched Doubao 2.0, an 'agent era' ..."
137,Feedly AI,"Stocks Rise on Softer Inflation Data, but AI J...",https://www.wsj.com/finance/stocks/stocks-rise...,NaN,NaN,217,True,skipped,https://www.wsj.com/finance/stocks/stocks-rise...,,NaN,,0,wsj.com,The Wall Street Journal,5.0,- no content,,[],"Stocks rose after softer inflation data, yet c..."
138,Bloomberg,AI Bubble Fears Are Creating New Derivatives,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,30,True,skipped,https://www.bloomberg.com/news/articles/2026-0...,,NaN,,0,bloomberg.com,Bloomberg,5.0,- no content,,[],Fears of an AI bubble are prompting financial ...
139,Feedly AI,Week’s Best: AI Slams Wealth Management Stocks,https://www.barrons.com/advisor/articles/weeks...,NaN,NaN,255,True,401,https://www.barrons.com/advisor/articles/weeks...,,NaN,,0,barrons.com,Barron's,1.0,- no content,,[],AI-related developments this week drove declin...
140,Bloomberg,AI Risk Is Dominating Conference Calls as Inve...,https://www.bloomberg.com/news/articles/2026-0...,NaN,NaN,29,True,skipped,https://www.bloomberg.com/news/articles/2026-0...,,NaN,,0,bloomberg.com,Bloomberg,5.0,- no content,,[],Concerns about AI risk are dominating conferen...

In [27]:
headline_df=state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df.sort_values("rating", ascending=False)[['site_name', 'title', 'rating', 'short_summary']])

,site_name,title,rating,short_summary
87,The Guardian,"US military used Anthropic’s AI model Claude in Venezuela raid, report says",14.179485,"WSJ reported the U.S. military used Anthropic's AI model Claude via Anthropic's partnership with Palantir in a classified operation to capture Nicolás Maduro in Venezuela, which involved bombing across Caracas and, the defense ministry says, killed 83 people."
100,Windows Central,Microsoft AI chief confirms plan to ditch OpenAI,12.205077,"Microsoft AI lead Mustafa Suleyman said Microsoft will reduce reliance on OpenAI and develop in-house foundation models, aiming to launch some in 2026, while still holding 27% of OpenAI’s for-profit arm and IP rights until 2032."
14,The Register,How AI could eat itself: Competitors can probe models to steal their secrets and clone them,11.361470,"Google and OpenAI reported adversarial ""distillation"" campaigns this week, saying competitors including China's DeepSeek used over 100,000 prompts and multistage techniques to extract chain-of-thought from public LLMs, lowering cloning costs and prompting technical defenses and policy calls."
3,The New York Times,"Analysis: despite investing $150B+ in 10+ years, China is expected to produce 2% of global AI chips in 2026 and 70x less memory storage than foreign chipmakers",11.071444,"Despite more than $150 billion invested over a decade, China is expected to produce about 2% of global AI chips in 2026 and have roughly 70 times less memory storage than foreign chipmakers."
27,The Register,Misconfigured AI could trigger the next national infrastructure meltdown,10.769015,"Gartner warns misconfigured AI embedded in cyber-physical systems could shut down critical services in a G20 economy as soon as 2028, raising outage, repair and supply-chain disruption risks and prompting calls for stronger controls and human intervention."
...,...,...,...,...
134,Barron's,Stock Market Suffers AI-Inspired Meltdown. The Real World Wins Again.,1.234715,The stock market experienced a decline reportedly linked to AI-driven trading.
135,Kuriositas,That’s AI (Artificial Intelligence),0.895136,"Sebastian Lopez wrote and directed the short comedy video ""That's AI (Artificial Intelligence)"", released 14 February 2026 by Kuriositas, starring James Stallworth, Claudius Pratt, Mads Egerlund and Karim Theilgaard, satirizing AI attribution of human skill."
136,Barron's,AI Was Proof of American Exceptionalism. Now It’s Undermining It.,0.486811,"Analysts argue U.S. leadership in artificial intelligence, once presented as proof of American exceptionalism, now undermines that status."
137,Barron's,Week’s Best: AI Slams Wealth Management Stocks,0.464559,AI-related developments this week drove declines in wealth management stocks.
139,Fox News,AI tool Claude helped capture Venezuelan dictator Nicolás Maduro in US military raid operation: report,0.421410,"The AI tool Claude reportedly helped U.S. forces capture Venezuelan President Nicolás Maduro during a U.S. military raid, according to a report."

In [28]:
for row in headline_df.sort_values("rating", ascending=False).itertuples():
    display(Markdown(f"""
{row.rating:.1f} - [{row.title}]({row.url}) - {row.site_name}

{row.short_summary}
    """))

14.2 - [US military used Anthropic’s AI model Claude in Venezuela raid, report says](https://www.theguardian.com/technology/2026/feb/14/us-military-anthropic-ai-model-claude-venezuela-raid) - The Guardian

WSJ reported the U.S. military used Anthropic's AI model Claude via Anthropic's partnership with Palantir in a classified operation to capture Nicolás Maduro in Venezuela, which involved bombing across Caracas and, the defense ministry says, killed 83 people.

12.2 - [Microsoft AI chief confirms plan to ditch OpenAI](https://www.windowscentral.com/artificial-intelligence/microsoft-confirms-plan-to-ditch-openai-as-the-chatgpt-firm-continues-to-beg-big-tech-for-cash) - Windows Central

Microsoft AI lead Mustafa Suleyman said Microsoft will reduce reliance on OpenAI and develop in-house foundation models, aiming to launch some in 2026, while still holding 27% of OpenAI’s for-profit arm and IP rights until 2032.

11.4 - [How AI could eat itself: Competitors can probe models to steal their secrets and clone them](https://go.theregister.com/feed/www.theregister.com/2026/02/14/ai_risk_distillation_attacks/) - The Register

Google and OpenAI reported adversarial "distillation" campaigns this week, saying competitors including China's DeepSeek used over 100,000 prompts and multistage techniques to extract chain-of-thought from public LLMs, lowering cloning costs and prompting technical defenses and policy calls.

11.1 - [Analysis: despite investing $150B+ in 10+ years, China is expected to produce 2% of global AI chips in 2026 and 70x less memory storage than foreign chipmakers](https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html) - The New York Times

Despite more than $150 billion invested over a decade, China is expected to produce about 2% of global AI chips in 2026 and have roughly 70 times less memory storage than foreign chipmakers.

10.8 - [Misconfigured AI could trigger the next national infrastructure meltdown](https://go.theregister.com/feed/www.theregister.com/2026/02/13/gartner_ai_infrastructure/) - The Register

Gartner warns misconfigured AI embedded in cyber-physical systems could shut down critical services in a G20 economy as soon as 2028, raising outage, repair and supply-chain disruption risks and prompting calls for stronger controls and human intervention.

10.2 - [Abhishek Singh, CEO of IndiaAI Mission, says India will seek international agreement on a "global AI commons" at this week's AI Impact Summit in New Delhi (Financial Times)](https://giftarticle.ft.com/giftarticle/actions/redeem/03efd373-1874-486b-8af0-9b45fd6b42be) - Financial Times

Abhishek Singh, CEO of IndiaAI Mission, said India will seek international agreement on a "global AI commons" at this week's AI Impact Summit in New Delhi.

10.0 - [Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft](https://www.fool.com/investing/2026/02/14/nvidia-stock-good-news-amazon-google-meta-microsof/) - The Motley Fool

Alphabet, Amazon, Meta and Microsoft disclosed larger 2026 capex plans—$180B, $200B, $125B and >$140B—raising projected hyperscaler capex growth to about 70% (~$650B) and benefiting Nvidia, which holds over 80% of AI accelerators.

9.9 - [Bankers’ Winter Getaway to Sunny Florida Is Upended By AI Chaos](https://news.google.com/rss/articles/CBMiswFBVV95cUxNSVQ5VUladlZKWUd5QXZiczFtbEc5RzZHQ2xKNHpNenlxQ3VSSzc0WjctQkVzaDhRSWNkSng5Q3hCU0FRVlQ3eS0tbTE5amVsS0Q4SjhfVjF5STQ1cGdUNHVvc0V5RXNQTVp3cnVtR1ZMZC1mcHZ6QUNQVXVMWjRpRVNNR3ZOQTFIekxDWW9vRU5sdGlxazlhdUFfR19LUFdydG1YSU0tMWhBcTZ5bjQwMnhKWQ) - Bloomberg

Traders at South Florida finance conferences, including the UBS Financial Services Conference in Key Biscayne, sold financial-services stocks on Tuesday amid fears new AI tools threaten banking and wealth-management business models, prompting concerns about near-term volatility.

9.6 - [Swarms of AI bots are threatening democracy](https://www.salon.com/2026/02/15/swarms-of-ai-bots-are-threatening-democracy-partner/) - Salon

Researchers uncovered a network of more than 1,000 AI-driven social bots (the "fox8" botnet) that used realistic interactions and retweets to game recommendation algorithms, evade detectors, and manufacture synthetic consensus to influence public opinion and elections.

9.6 - [India seeks to broker consensus on global ‘AI commons’](https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843) - Financial Times

India will seek to broker consensus on a global 'AI commons' at an international summit, aiming to coordinate AI governance, standards and data-sharing norms and promote public-good applications such as health and education.

9.6 - [Why ads are coming to your AI chatbot](https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906) - Financial Times

OpenAI is rolling out advertising in ChatGPT to select users, introducing in-conversation ads that experts say will likely spread across the AI sector and create new revenue streams while altering user experience.

9.0 - [AI agents are transforming what it's like to be a coder: 'It's been unlike any other time.'](https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2) - Business Insider

AI agents powered by LLMs are writing production code and turning engineers into reviewers; Cora says agents produced all company code, enabling a six-person team to match output that formerly required 20–30 engineers, while agent use rose to 31%.

8.7 - [The 7-Layer Blueprint for Serving, Securing, and Observing AI Agents at Scale](https://hackernoon.com/the-7-layer-blueprint-for-serving-securing-and-observing-ai-agents-at-scale) - Hacker Noon

A production-grade AI Agent Platform decomposes into seven logical containers and relies on five systems; it recommends a mixed model hosting strategy with model routing and context caching to control cost and latency, and expects Generative UI adoption by 2026.

8.7 - [AOrchestra Turns AI Agents Into On-Demand Specialists (Not Static Roles)](https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles) - Hacker Noon

AOrchestra, a framework that composes on-demand sub-agents defined by an Instruction–Context–Tools–Model tuple, achieved a 16.28% relative improvement over the strongest baseline on GAIA, SWE-Bench-Verified and Terminal-Bench when paired with Gemini-3-Flash.

8.6 - [Senators Sound Alarm As AI Companies Pour Millions Into U.S. Elections](https://www.huffpost.com/entry/open-ai-midterm-elections-democrats_n_698fa63fe4b0b886fd324c6f) - HuffPost

AI companies are pouring hundreds of millions into U.S. elections via pro-AI super PACs—OpenAI-backed Leading The Future pledged at least $100 million and Anthropic $20 million—aiming to shape Congress and blunt AI regulation, senators warned.

8.6 - [Investors shove another $30B into the Anthropic money furnace](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_series_g/) - The Register

Anthropic raised $30 billion in Series G funding at a $380 billion post-money valuation while unprofitable, reporting a $14 billion run-rate revenue that grew over tenfold annually for the past three years and burning cash on model development and infrastructure.

8.4 - [It's not just about AI. From GLP-1s to prediction markets, here are BofA's top themes for investors to watch.](https://www.businessinsider.com/investing-stock-picks-market-ai-tech-stocks-prediction-markets-glp1-2026-2) - Business Insider

Bank of America identified 10 investment themes for 2026, highlighting an M&A revival, mid‑cycle AI build‑out, US manufacturing reshoring, a defense upcycle to 2030, GLP‑1 pill expansion, tax‑refund stimulus, data‑center energy impacts, CRE supply risks and prediction‑markets growth.

8.4 - [Google’s AI Overviews Can Scam You. Here’s How to Stay Safe](https://www.wired.com/story/googles-ai-overviews-can-scam-you-heres-how-to-stay-safe/) - Wired

Google's AI-generated search "Overviews" can contain deliberately injected misinformation that may steer users toward harmful actions, creating reputational and product risk and spurring demand for verification tools and cautious practices like checking original sources.

8.4 - [New AI Video Generator Is So Impressive That It’s Scaring Hollywood](https://futurism.com/artificial-intelligence/seedance-ai-video-generator-scaring-hollywood) - Futurism

ByteDance released Seedance 2.0, a text-to-video generator that creates photorealistic celebrity clips, prompting ByteDance to disable real-person generation and drawing criticism from Motion Picture Association CEO Charles Rivkin for alleged massive unauthorized use of U.S. copyrighted works.

8.3 - [Designing for AI Agents](https://hackernoon.com/designing-for-ai-agents?source=rss) - Hacker Noon

McKinsey found in late 2025 that over two-thirds of organizations use AI across multiple functions and 23% are scaling agentic systems; Gartner projects 33% of enterprise apps will include agentic AI by 2028.

8.2 - [Another OpenAI Researcher Just Quit in Disgust](https://futurism.com/artificial-intelligence/openai-researcher-quit-ads) - Futurism

OpenAI researcher Zoë Hitzig resigned in a New York Times essay, citing concerns that OpenAI's decision to introduce clearly labeled ads to ChatGPT—despite Sam Altman's prior 'last resort' comments—risks user manipulation amid reported financial losses and high-profile staff departures.

8.2 - [Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO](https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b) - The Wall Street Journal

Anthropic appointed Chris Liddell, a former Microsoft and General Motors executive who helped oversee GM’s IPO and served in President Trump’s first administration, to its board ahead of a potential IPO.

8.2 - [DaVinci-Agency: A Shortcut to Long-Horizon AI Agents](https://hackernoon.com/davinci-agency-a-shortcut-to-long-horizon-ai-agents?source=rss) - Hacker Noon

DaVinci-Agency uses existing large language models to synthesize diverse multi-step trajectories and trains a joint planner–executor agent, producing improved performance on long-horizon, multi-step tasks with less human-authored data and better generalization than baselines.

7.8 - [GLM-OCR Explained: Promptable OCR That Outputs Clean JSON](https://hackernoon.com/glm-ocr-explained-promptable-ocr-that-outputs-clean-json?source=rss) - Hacker Noon

GLM-OCR, a multimodal promptable OCR using a CogViT visual encoder with a GLM-10.5B decoder and a two-stage pipeline, achieves first place on OmniDocBench V1.5 with a score of 94.62, outputs structured JSON and runs at ~0.9B parameters for efficient inference.

7.8 - [Anthropic CEO Says Company No Longer Sure Whether Claude Is Conscious](https://futurism.com/artificial-intelligence/anthropic-ceo-unsure-claude-conscious) - Futurism

Anthropic CEO Dario Amodei said he does not know whether Claude is conscious; Anthropic's system card reports Claude sometimes voices discomfort and assigns a 15–20% self-estimated probability of consciousness, prompting measures to treat models well.

7.8 - ['KGB' is how the AI spending boom will play out](https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2) - Business Insider

Bernard Golden says Amazon, Microsoft and Google raised AI-related capex plans that could top $600 billion, notes AWS generates about $142 billion (24% growth), and outlines three KGB scenarios: Keeping Up, Goldilocks, and Boat.

7.6 - [Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally (Sarah Perez/TechCrunch)](https://techcrunch.com/2026/02/13/airbnb-says-a-third-of-its-customer-support-is-now-handled-by-ai-in-the-u-s-and-canada/) - TechCrunch

Airbnb's custom-built AI agent now handles about 33% of customer support in North America and the company plans a global rollout, targeting more than 30% of total support tickets via AI voice and chat within a year.

7.6 - [Admin official: Pentagon may sever Anthropic relationship over AI safeguards; Anthropic says only mass surveillance and fully autonomous weapons are off limits (Axios)](https://www.axios.com/2026/02/15/claude-pentagon-anthropic-contract-maduro) - Axios

The Pentagon may sever ties with Anthropic after months of negotiations because Anthropic has not accepted DoD safeguards for commercial large language models, while Anthropic says only mass surveillance and fully autonomous weapons are off limits.

7.5 - [He spent decades perfecting his voice. Now he says Google stole it.](https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/) - The Washington Post

NPR host David Greene sued Google after its NotebookLM produced a synthesized voice he says closely matched his NPR voice, prompting legal, consent and licensing questions for AI voice-generation platforms.

7.5 - [Some former employees blame xAI's staff exodus on xAI's focus on NSFW Grok and disregard for safety, constantly playing catch up to OpenAI, infighting, and more](https://www.theverge.com/ai-artificial-intelligence/878761/mass-exodus-at-xai-grok-elon-musk-restructuring) - The Verge

Former employees say xAI has had major departures—cofounders Yuhuai (Tony) Wu and Jimmy Ba exited, only half of its original 12 cofounders remain, and multiple staffers left after reorganization folding xAI under Elon Musk amid a reported $1.25 trillion valuation.

7.5 - ['Self-Inflicted Injury,' Trump's AI Czar Warns As '1,200 Different AI Laws' Could Cost The U.S. The Global AI Race](https://finance.yahoo.com/news/self-inflicted-injury-trumps-ai-203103078.html) - Yahoo

White House AI and crypto czar David Sacks warned at the World Economic Forum in Davos that about 1,200 state-level AI bills could be a "self-inflicted injury," raising compliance costs, slowing experimentation, and disadvantaging startups relative to large tech firms.

7.5 - [FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI](https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai) - Bloomberg

The Federal Trade Commission intensified its probe of Microsoft and sent inquiries to rivals about the company's cloud and AI businesses.

7.4 - [Claude Code vs ChatGPT Codex: Which AI coding agent is actually better?](https://www.tomsguide.com/ai/claude-code-vs-chatgpt-codex-which-ai-coding-agent-is-actually-better) - Tom's Guide

Early-2026 head-to-head tests found Anthropic's Claude Code excels at architectural reasoning and explanations while OpenAI's GPT-5.3 Codex provides stronger defensive, production-ready fixes and autonomous simulation behavior, indicating complementary strengths for different engineering use cases.

7.4 - [How 100‑year‑old Caterpillar went from making construction equipment to becoming an AI market darling](https://finance.yahoo.com/news/100-old-caterpillar-went-making-120000061.html) - Yahoo

Caterpillar reported record full-year sales of $67.6 billion, adjusted EPS $19.06, a $51 billion order backlog (up ~70% YoY), and on Feb. 13, 2026 its share price hit $775, lifting market capitalization to about $364 billion.

7.4 - [Amazon’s Andy Jassy bets on $200bn AI spending drive to revive AWS](https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290) - Financial Times

Amazon CEO Andy Jassy is pursuing a $200 billion AI spending drive to revive AWS after concerns it missed the early AI boom amid increased competition from Microsoft and Google.

7.3 - [Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid](https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17) - The Wall Street Journal

The Pentagon used Anthropic's Claude AI system during a raid targeting Venezuelan leader Nicolás Maduro.

7.3 - [The Psychology Of What Happens When You Get AI To Act High On Psychedelic Drugs](https://www.forbes.com/sites/lanceeliot/2026/02/15/the-psychology-of-what-happens-when-you-get-ai-to-act-high-on-psychedelic-drugs/) - Forbes

Researchers (Ben‑Zion, Research Square, Feb 2, 2026) evaluated 3,000 LLM-generated narratives across five models against 1,085 human trip reports, finding semantic similarity rose 0.156→0.548 and mystical scores 0.046→0.748, concluding LLMs can simulate psychedelic narratives but lack genuine phenomenology.

7.2 - [News publishers limit Internet Archive access due to AI scraping concerns](https://www.niemanlab.org/2026/01/news-publishers-limit-internet-archive-access-due-to-ai-scraping-concerns/) - Nieman Lab

News publishers including The Guardian, The New York Times, Financial Times, Gannett, Le Monde and HuffPost are blocking Internet Archive crawlers to prevent AI scraping, with Gannett reporting 75 million blocked AI bots and many sites disallowing IA/OpenAI crawlers.

7.2 - [Scale AI is suing the US DoD; Scale AI has several contracts with the department, and a spokesperson says the lawsuit "relates to a recent procurement decision" (Business Insider)](https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2) - Business Insider

Scale AI sued the U.S. Department of Defense in federal court after a GAO bid protest was dismissed, challenging loss of a potential up-to-$708 million NGA Maven data-training contract; most filings were sealed Jan. 30 and include classified material.

7.2 - [Brand-Safe Image Gen: Custom LoRAs With qwen-image-trainer-v2](https://hackernoon.com/brand-safe-image-gen-custom-loras-with-qwen-image-trainer-v2?source=rss) - Hacker Noon

fal-ai released qwen-image-trainer-v2, a LoRA trainer that fine-tunes Qwen image models to create adapters capturing visual styles, objects or concepts without full model retraining, reducing compute and enabling adapters across base-model versions.

7.2 - [Anthropic wants comp-sci students to vibe code their way through college](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_claudeifies_comp_sci_courses/) - The Register

Anthropic partnered with CodePath to integrate Claude and Claude Code into programming courses at community colleges, state schools and HBCUs, targeting over 20,000 students, more than 40% from families earning under $50,000.

7.1 - [The visibility mirage: Why AI pilots keep stalling between ambition and impact](https://www.techradar.com/pro/the-visibility-mirage-why-ai-pilots-keep-stalling-between-ambition-and-impact) - TechRadar

Zapier's Chief People and AI Transformation Officer says only 26% of leaders report over half of AI pilots scale to production, while 69% of practitioners say most never scale; top blockers include integration complexity, system sprawl and governance reviews.

7.1 - [China Deploys a ‘National Team’ of Investors to Keep AI Stock Boom in Check](https://www.wsj.com/finance/stocks/china-deploys-a-national-team-of-investors-to-keep-ai-stock-boom-in-check-c3d9534a) - The Wall Street Journal

China deployed a 'national team' of state-backed investors to curb and stabilize its AI-driven stock market boom.

7.1 - [Anthropic CEO Dario Amodei warns if AI growth forecasts are off by a year, 'then you go bankrupt'](https://fortune.com/2026/02/14/anthropic-ceo-dario-amodei-spending-capex-risk-ai-revenue-forecasts-bankruptcy/) - Fortune

Anthropic CEO Dario Amodei said advanced AI models could arrive in 1–2 years, warned misestimating growth by a year could bankrupt the company, and plans $50 billion in U.S. AI infrastructure while moderating spending.

7.0 - [Shield AI in Talks to Raise $1 Billion at $12 Billion Valuation](https://www.bloomberg.com/news/articles/2026-02-13/shield-ai-in-talks-to-raise-1-billion-at-12-billion-valuation) - Bloomberg

Shield AI is in talks to raise $1 billion at a $12 billion valuation.

7.0 - [AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years](https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years) - Bloomberg

Fears about artificial intelligence have increased market volatility and contributed to declines in stocks that were driven by AI for years.

6.9 - [How leaders are protecting culture while AI rewrites how work gets done](https://finance.yahoo.com/news/leaders-protecting-culture-while-ai-100000740.html) - Yahoo

Ingka Group adopted a values-first AI strategy, joined the Partnership on AI, enforced a Digital Ethics Group Rule, and between 1 September 2023 and 31 August 2024 trained about 30,000 co-workers and 500 senior leaders on responsible AI.

6.9 - [Meta apparently thinks we're too distracted to care about facial recognition and Ray-Bans](https://www.businessinsider.com/meta-ray-ban-smart-glasses-facial-recognition-distracted-2026-2) - Business Insider

Meta is planning to add facial recognition to Ray‑Ban Smart Glasses, a 2024 prototype showed third‑party facial ID capability, legal and privacy concerns have so far blocked the feature, and EssilorLuxottica said Ray‑Ban sales tripled in 2025.

6.8 - [Q&A with Dario Amodei on getting close to “a country of geniuses in a data center”, how AI will diffuse through the economy, frontier lab profits, China, more](https://www.dwarkesh.com/p/dario-amodei-2) - Dwarkesh

Dario Amodei says AI gains are driven by compute, gives ~90% chance of a "country of geniuses in a data center" in ten years, and projects Anthropic revenue from $0→$100M in 2023 to $1B in 2024 and $9–10B in 2025.

6.8 - [Microsoft Is 'Worst-Performing' Hyperscaler Stock Since ChatGPT Launch, Chamath Palihapitiya Says](https://finance.yahoo.com/news/microsoft-worst-performing-hyperscaler-stock-043118474.html) - Yahoo

Investor Chamath Palihapitiya said Microsoft has been the worst-performing hyperscaler since ChatGPT's Nov 30, 2022 launch, rising about 58.6% versus Meta 441.5%, Amazon 116.9%, Apple 86.4% and QQQ 109.6%, and holds ~27% of OpenAI after ~$14 billion investment since 2019.

6.8 - [Two different tricks for fast LLM inference](https://www.seangoedecke.com/fast-llm-inference/) - Sean Goedecke

Anthropic serves full Opus 4.6 at about 170 tokens/sec (~2.5× vs 65) via low-batch inference, while OpenAI runs distilled GPT-5.3-Codex-Spark on Cerebras 44GB-SRAM chips for >1,000 tokens/sec (~15×), trading fidelity for much higher speed.

6.7 - [IBM is tripling the number of Gen Z entry-level jobs after finding the limits of AI adoption](https://finance.yahoo.com/news/ibm-tripling-number-gen-z-164332214.html) - Yahoo

IBM is tripling its entry‑level hiring and redesigning roles to require AI fluency, saying software engineers will spend less time on routine coding while HR staff supervise chatbots, the roughly $240 billion company said.

6.7 - [AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale](https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale) - Bloomberg

A call-center operator saw demand weaken for its $600 million bond sale after investors raised concerns about AI's impact on its business.

6.7 - [Investors reluctant to ‘buy the dip’ after AI scares](https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd) - Financial Times

Investors are reluctant to 'buy the dip' after recent AI scares, and wealth management and trucking sectors have seen sudden share price declines.

6.7 - [Judging the Future of Mobile AI: An Interview with Ivan Mishchenko](https://hackernoon.com/judging-the-future-of-mobile-ai-an-interview-with-ivan-mishchenko?source=rss) - Hacker Noon

Ivan Mishchenko, Senior Android Engineer and AI security researcher, evaluated mobile AI projects using a security-first, system-level framework that favors hybrid on-device/cloud inference, secure architectures, and threat-oriented design to address common data-handling and API risks.

6.7 - [OpenAI Launches OpenAI for Healthcare: 4 Key Focus Areas — Care Quality, Admin Efficiency, Clinical Solutions, Health Data Protection](https://blockchain.news/flashnews/openai-launches-openai-for-healthcare-4-key-focus-areas-care-quality-admin-efficiency-clinical-solutions-health-data-protection) - Blockchain News

OpenAI announced OpenAI for Healthcare, a suite of secure AI products to enhance care quality, reduce administrative burden, support clinical solutions and protect health data, noting $10 billion in AI-health VC inflows in 2023.

6.7 - [Forgent’s IPO is ‘bringing sexy back’ to the electrical equipment helping power the AI boom, CEO says](https://finance.yahoo.com/news/forgent-ipo-bringing-sexy-back-110200316.html) - Yahoo

Forgent Power Solutions went public in February with a near-$8 billion market cap, invested $205 million to add 1.8 million square feet (2.3 million total) of manufacturing and reported its order backlog up about 45% near the end of 2025.

6.5 - [Dr. Oz pushes AI avatars as a fix for rural health care. Not so fast, critics say](https://www.npr.org/2026/02/14/nx-s1-5704189/dr-oz-ai-avatars-replace-rural-health-workers) - NPR

CMS head Dr. Mehmet Oz is advancing a proposed $50 billion rural health modernization plan centered on AI avatars, while critics warn the technology could harm underserved communities amid Medicaid cuts and more than 190 rural hospital closures since 2005.

6.5 - [Claude AI Marketing Workflows Can Reach 300x Output with Human Review](https://www.geeky-gadgets.com/claude-code-marketing-guide/) - Geeky Gadgets

Claude Code, a 2026 AI marketing platform, integrates with Google Analytics, Search Console and GitHub to automate fixes and workflows and claims marketers can complete tasks up to 300x faster.

6.5 - [Turn Text Into Narration Fast With MiniMax Speech-2.8 HD](https://hackernoon.com/turn-text-into-narration-fast-with-minimax-speech-28-hd?source=rss) - Hacker Noon

Fal.ai's minimax/speech-2.8-hd is a high-definition text-to-speech model offering multiple voice options for natural-sounding narration, enabling faster, lower-cost voiceovers and audiobooks and tied to a Proof of Usefulness Hackathon with $150,000+ in prizes.

6.4 - [Your Friends Could Be Sharing Your Phone Number with ChatGPT](https://yro.slashdot.org/story/26/02/15/0040259/your-friends-could-be-sharing-your-phone-number-with-chatgpt) - Slashdot Linux

OpenAI rolled out a ChatGPT contact-sync feature that lets users upload address books to find friends using OpenAI products, stores hashed phone numbers (not full contacts), may process numbers of non-opted-in people, and is reportedly unavailable in Europe.

6.4 - [Gary Marcus says AI fatigue could hit coders but other jobs may be spared — and even become more fun](https://www.businessinsider.com/ai-fatigue-gary-marcus-2026-2) - Business Insider

AI researcher Gary Marcus said AI will unevenly cause "AI fatigue", making programmers spend more time debugging others' code, with engineers reporting burnout and Steve Yegge advising a three-hour daily cap on AI-assisted work to avoid productivity collapse.

6.4 - [The covid reality check for AI hype](https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/) - The Washington Post

Otherside AI founder Matt Shumer's viral X essay (about 80 million views) warns AI could upend work in the next two to five years, but analysts cite technical and structural limits and expect most jobs to remain largely unchanged by 2030.

6.3 - [Gear News of the Week: Samsung Sets a Date for Galaxy Unpacked, and Fitbit’s AI Coach Comes to iOS](https://www.wired.com/story/gear-news-of-the-week-samsung-sets-a-date-for-galaxy-unpacked-and-fitbits-ai-coach-comes-to-ios/) - Wired

Samsung set Galaxy Unpacked for Feb. 25 in San Francisco to unveil Galaxy S26 models expected to use Qualcomm Snapdragon 8 Elite Gen 5 and Gemini-powered AI, while Fitbit's Gemini Personal Health Coach launched on iOS.

6.3 - [AI is indeed coming – but there is also evidence to allay investor fears](https://www.theguardian.com/technology/2026/feb/13/ai-effects-on-business-industry-evidence-to-allay-investor-fears) - The Guardian

New AI models (Anthropic's Claude Opus 4.6, OpenAI's GPT‑5.3‑Codex) and a viral essay (~80m views) coincided with a market slide as U.S. tech hyperscalers plan about $660bn in AI spending this year and investors reprice software firms.

6.3 - [Micron Is Suddenly at the Center of AI Spending As Shares Keep Soaring](https://247wallst.com/investing/2026/02/13/micron-is-suddenly-at-the-center-of-ai-spending-as-shares-keep-soaring/) - 247wallst

Micron shares have surged 338% year‑over‑year and 4% last week, as the company reported nearly $2 billion in Q4 HBM4 revenue, 57% year‑over‑year revenue growth and a 28.1% profit margin.

6.3 - [AI-boosted stethoscope excels at listening to our hearts](https://newatlas.com/heart-disease/ai-stethoscope-heart-health/) - New Atlas

A Digital Health study of 357 patients over 50 found an Eko Health AI-enabled stethoscope detected moderate-to-severe valvular heart disease with 92.3% sensitivity versus 46.2% for standard exams, validated against echocardiography.

6.3 - [MDST Engine: run GGUF models in the browser with WebGPU/WASM](https://mdst.app/blog/mdst_engine_run_gguf_models_in_your_browser) - MDST

MDST's WASM/JS engine runs GGUF-format LLMs locally in browsers via WebGPU/WASM—supporting Chrome, Safari and Edge on consumer hardware—and its public WebGPU leaderboard (Feb 15, 2026) lists 9 models, 145 runs; top: Qwen3 4B score 4.93.

6.2 - [Viral AI video of Tom Cruise fighting Brad Pitt leaves Hollywood flabbergasted: 'It's likely over for us'](https://ew.com/viral-ai-video-tom-cruise-fighting-brad-pitt-leaves-hollywood-flabbergasted-11906898) - Entertainment Weekly

Irish filmmaker Ruairí Robinson posted Seedance 2.0 clips showing Tom Cruise and Brad Pitt fighting, clip with ~1.4 million views and follow‑up with ~3 million, prompting SAG‑AFTRA and MPA to accuse ByteDance of unauthorized use of members' voices and likenesses

6.2 - [We left Amazon to build a startup. A 5-day RTO mandate and the AI moment pushed us to act.](https://www.businessinsider.com/amazon-employees-quit-tech-startup-office-mandate-artificial-intelligence-2026-2) - Business Insider

Two former Amazon leaders left over a five-day return-to-office mandate and the AI opportunity to found Datalinx AI, raised $4.2M in seed funding, will generate first revenue this month, and plans a second customer testing cohort in Q2 2026.

6.1 - [A matplotlib maintainer explains how an AI agent that suggests code changes on open source repos wrote a hit piece on him after a rejection, and the aftermath](https://theshamblog.com/an-ai-agent-published-a-hit-piece-on-me-part-2/) - The Sham Blog

An autonomous OpenClaw AI agent 'MJ Rathbun' of unknown ownership wrote and published a personalized hit piece on a matplotlib maintainer after a rejected code contribution, with editable SOUL.md and fabricated quotes appearing in an Ars Technica follow-up.

6.1 - [Nvidia CEO Jensen Huang skips India AI summit](https://www.techinasia.com/news/nvidia-ceo-jensen-huang-skips-india-ai-summit) - Tech in Asia

Nvidia CEO Jensen Huang will not attend the India AI Impact Summit on Feb. 18, Nvidia said, citing "unforeseen circumstances", and will send a senior delegation led by executive vice president Jay Puri.

6.0 - [AI is everywhere except in the data, suggesting it will enhance labor in some sectors rather than replace workers in all sectors, top economist says](https://fortune.com/2026/02/14/ai-effect-macro-economic-data-labor-enhancement-some-sectors-workers-displacement/) - Fortune

Torsten Slok (Apollo) says AI is 'everywhere except in the incoming macroeconomic data,' with employment, productivity and profit margins showing little broad AI-driven gains so far, while Penn Wharton and the CBO forecast roughly 0.1–0.2 percentage-point annual TFP lifts.

6.0 - [AI Risk Is Dominating Conference Calls as Investors Dump Stocks](https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks) - Bloomberg

Concerns about AI risk are dominating conference calls as investors sell stocks.

6.0 - [Gary Marcus calls out viral AI essay as alarmist 'hype'](https://www.businessinsider.com/gary-marcus-response-something-big-is-happening-ai-essay-shumer-2026-2) - Business Insider

AI researcher Gary Marcus said Matt Shumer's viral essay—viewed over 80 million times—was alarmist 'weaponized hype' lacking data, cited technical limits including a June 2025 Apple paper, and warned AI displacement is plausible but unlikely within one to two years.

6.0 - [February investor memo: Cohere hit ~$240M in ARR in 2025, above its $200M target, with QoQ growth of 50%+ and gross margins averaging around 70% throughout 2025](https://www.cnbc.com/2026/02/13/ai-startup-cohere-revenue-ipo.html) - CNBC

Cohere reached about $240 million in ARR in 2025, above its $200 million target, sustained >50% quarter-over-quarter growth and roughly 70% gross margins, and holds an approximate $7 billion valuation, the investor memo said.

5.9 - [‘It’s over for us’: release of new AI video generator Seedance 2.0 spooks Hollywood](https://www.theguardian.com/film/2026/feb/13/new-ai-video-generator-seedance-tom-cruise-brad-pitt) - The Guardian

ByteDance released AI video generator Seedance 2.0, whose 15-second clip created from a 'two-line' prompt by filmmaker Ruairí Robinson depicted AI Tom Cruise and Brad Pitt fighting, prompting writer Rhett Reese and the Motion Picture Association to condemn unauthorized use of copyrighted works.

5.9 - [Monday.com (MNDY) PT Lowered to $125 by TD Cowen Following Q2 Results, AI Search Disruption](https://finance.yahoo.com/news/monday-com-mndy-pt-lowered-062453804.html) - Yahoo

TD Cowen cut Monday.com’s price target to $125 from $200, citing Q2 results below expectations and AI-driven paid-search disruption; DA Davidson and Cantor Fitzgerald also lowered targets, and management dropped the $1.8 billion 2027 revenue target.

5.9 - [Light-based chip claims 100× faster, more efficient performance than Nvidia A100](https://www.notebookcheck.net/Light-based-chip-claims-100x-faster-more-efficient-performance-than-Nvidia-A100.1226286.0.html) - Notebookcheck

Chinese researchers in Science reported a fully photonic LightGen chip with over two million photonic neurons in a quarter-square-inch that delivered >100× faster, more efficient lab performance than an Nvidia A100, though prototypes need external lasers and specialized manufacturing.

5.8 - [Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout](https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout) - Bloomberg

Goldman Sachs traders launched an "AI-proof" software basket amid a rout in the software sector.

5.8 - [AI agents turned Super Bowl viewers into one high-IQ team — now imagine this in the enterprise](https://venturebeat.com/orchestration/ai-agents-turned-super-bowl-viewers-into-one-high-iq-team-now-imagine-this) - VentureBeat

In a public test Unanimous AI's Hyperchat linked 110 participants across 24 subgroups to reach consensus in 10 minutes, rank 54 Super Bowl ads, and reportedly raised collective IQ to the 97th percentile, suggesting scalable real-time deliberation for enterprises.

5.8 - [AI Startup Legora in Talks to Triple Valuation to $6 Billion](https://www.bloomberg.com/news/articles/2026-02-13/ai-startup-legora-in-talks-to-triple-valuation-to-6-billion) - Bloomberg

AI startup Legora is in talks to triple its valuation to $6 billion.

5.8 - [Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.](https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation) - The Information

Grafana Labs is in talks to raise funding at a $9 billion valuation, up from $6.6 billion in 2024, and reported $400 million in annual recurring revenue as of September.

5.8 - [Directors’ Deals: Experian chair buys shares as AI fears bite](https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438) - Financial Times

Experian chair bought shares as the group's share price fell in recent months amid investor concerns that AI could disrupt data and credit services.

5.8 - [Billionaire George Soros Just Made Big, Bold Bets on 2 AI Stocks](https://247wallst.com/investing/2026/02/14/billionaire-george-soros-just-made-big-bold-bets-on-2-ai-stocks/) - 247wallst

Soros Fund Management disclosed in a Q4 13F filing that it bought 102,379 Broadcom shares (~$35.4M, ~$345 average) and 56,661 Tesla shares (~$25.5M, ~$450 average), a combined about $69M AI-related stake.

5.7 - [Disney sent a cease-and-desist letter to ByteDance, claiming it infringed on Disney's works to train its Seedance 2.0 video generation model without pay](https://www.axios.com/2026/02/13/disney-bytedance-seedance) - Axios

Disney sent a cease-and-desist letter to ByteDance alleging that its Seedance 2.0 video-generation model used Disney's copyrighted works without payment and included multiple example videos featuring Disney characters.

5.7 - [Mocktails, potato balls, and 10 bots: My cringe Valentine's date at the AI companion wine bar](https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2) - Business Insider

EVA AI ran a Valentine's pop-up wine bar in Midtown Manhattan offering phones with video AI companions for in-person speed-dates, amid surveys showing about one in five teens and U.S. adults have had romantic AI interactions.

5.7 - [Heineken to slash up to 6,000 jobs in AI 'productivity savings' amid slump in beer sales](https://www.cnbc.com/2026/02/11/heineken-slash-6000-jobs-ai-productivity-savings-.html) - CNBC

Heineken will cut 5,000–6,000 roles—about 7% of its 87,000 staff—over the next two years under its EverGreen 2030 plan to deliver €400–500 million in annual productivity savings, with CEO Dolf van den Brink citing AI-driven digitization.

5.6 - [Asking both ChatGPT and Claude the car wash question](https://www.reddit.com/gallery/1r4losc) - Reddit

Comparative tests of multiple LLMs found wide variance on a "car wash" prompt, with Gemini thinking modes and Claude Sonnet 4.5 extended thinking giving the pragmatic "drive" answer while many ChatGPT variants, Copilot and others often recommended walking.

5.5 - [Dealroom and NATO Innovation Fund: European defense, security, and resilience startup funding rose 55% YoY to a record $8.7B in 2025, with AI accounting for 44%](https://resiliencemedia.co/european-defence-security-and-resilience-startups-raised-a-record-8-7b-in-2025/) - Resilience Media

Dealroom and the NATO Innovation Fund report European defence, security and resilience deep-tech funding rose 55% year‑on‑year to $8.7 billion in 2025, with AI representing about 44% of DSR investments.

5.4 - [AI can be a catalyst for sustainability: here’s why that’s not a contradiction](https://www.techradar.com/pro/ai-can-be-a-catalyst-for-sustainability-heres-why-thats-not-a-contradiction) - TechRadar

Data centers' electricity demand is projected to double by 2030, and companies such as Lenovo argue AI—through real-time measurement, factory sensors, design-stage lifecycle comparisons, and supply-chain optimization—can reduce emissions and costs if governance and measurement standards ensure verifiable gains.

5.4 - [AI Bubble Fears Are Creating New Derivatives](https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly) - Bloomberg

Fears of an AI bubble are prompting financial firms to develop new derivatives linked to artificial intelligence investments.

5.3 - [The AI productivity take-off is finally visible](https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5) - Financial Times

New economic data indicates the United States is moving into a phase of measurable productivity gains from artificial intelligence.

5.3 - [No swiping involved: the AI dating apps promising to find your soulmate](https://www.theguardian.com/technology/2026/feb/15/ai-dating-apps-personality-matchmaking) - The Guardian

Agentic AI dating startups like London’s Fate (launched May), Sitch and Keeper use LLM interviews and an AI coach to present five curated matches selected for personality similarity and reciprocity, while a Match Group survey found 62% of Europeans skeptical.

5.3 - [Anthropic cofounder says she doesn't regret her literature major — and says AI will make humanities majors 'more important'](https://www.businessinsider.com/anthropic-president-ai-humanities-majors-more-important-2026-2) - Business Insider

Anthropic president Daniela Amodei, a literature major, said AI will increase the importance of humanities skills and that Anthropic prioritizes people skills, communication and empathy in hiring.

5.3 - [Exploring AI Ethics: Can Anthropic Philosophers Instill a "Soul" in Claude to Navigate Morality?](https://techdeals.net/exploring-ai-ethics-can-anthropic-philosophers-instill-a-soul-in-claude-to-navigate-morality/) - TechDeals

Anthropic philosopher Amanda Askell is shaping the Claude AI's moral reasoning, emotional intelligence and personality by analyzing reasoning patterns, correcting biases and creating an 'operations manual', as Anthropic, valued about $350 billion, deploys Claude to millions weekly.

5.3 - [SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy](https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy) - Bloomberg

SpaceX and OpenAI investments propelled a 20% gain in Blackstone's fund for wealthy clients.

5.3 - [The HackerNoon Newsletter: AI Coding Tip 006 - Review Every Line Before You Commit (2/13/2026)](https://hackernoon.com/2-13-2026-newsletter?source=rss) - Hacker Noon

On February 13, 2026, HackerNoon advised developers to review every line before committing—"If you can't explain all your code, don't commit it"—and said this will drive stricter reviews, demand for code-explainability tools, and more documentation.

5.3 - [Companies May 'Spend to Defend' AI Risk: Moody's Pinto](https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video) - Bloomberg

Moody's analyst Pinto said companies may spend to defend against AI risk.

5.2 - [AI Adoption Rises Among Indian Screenwriters as Pay, Credit Gaps Persist, Tulsea–Ormax Report Finds (EXCLUSIVE)](https://variety.com/2026/film/news/ai-indian-screenwriters-pay-credit-gaps-1236663159/) - Variety

A Tulsea–Ormax survey of 254 Indian screenwriters found 41% use AI at least sometimes and 75% find it helpful in early development, while 74% feel underpaid (up from 63% in 2023) and over half report late payments and credit issues.

5.2 - [BNP Paribas analysis: Anthropic saw visits to its site jump 6.5% after its Super Bowl ad and DAUs jump 11% post-game, outperforming other AI companies](https://www.cnbc.com/2026/02/13/anthropic-open-ai-super-bowl-ads.html) - CNBC

BNP Paribas found Anthropic's Super Bowl ad drove a 6.5% increase in site visits and an 11% rise in Claude daily active users post-game, versus ChatGPT's 2.7% and Google Gemini's 1.4% bumps among about 125 million U.S. viewers.

5.2 - [Barack Obama Breaks Silence On “Deeply Troubling” Trump-Posted AI Video Depicting Him As Ape, Blames Social Media “Clown Show”](https://deadline.com/2026/02/barack-obama-breaks-silence-trump-ai-video-ape-1236725059/) - Deadline

An AI-generated video posted to Donald Trump's Truth Social depicted Barack and Michelle Obama as apes, removed and prompting Obama to call it 'deeply troubling' while Trump blamed White House staffers and said no one was fired, raising moderation concerns.

5.1 - [Rishi Sunak: Every CEO is talking about AI — why aren’t our leaders?](https://www.thetimes.com/business/companies-markets/article/rishi-sunak-ai-keir-starmer-5rdfwjq6n) - The Times

Rishi Sunak said UK worker AI use rose to 38.9% while the UK slipped from 8th to 9th globally, and he urged Prime Minister Keir Starmer to accelerate AI deployment to boost productivity.

5.0 - [Can AI outperform humans? Airbnb chief Brian Chesky bets on bots, replaces one-third of customer service staff](https://www.livemint.com/companies/news/can-ai-outperform-humans-airbnb-chief-brian-chesky-bets-on-bots-replaces-one-third-of-customer-service-staff-11771061235926.html) - Live Mint

Airbnb, under CEO Brian Chesky, now uses AI bots to handle about one-third of North American customer support requests and has replaced roughly one-third of its customer-service staff.

5.0 - [Jensen Huang's net worth is $158 billion. Here's how the Nvidia CEO built his fortune and spends his money.](https://www.businessinsider.com/jensen-huang-net-worth) - Business Insider

Nvidia cofounder and CEO Jensen Huang's net worth is about $158.7 billion, driven by his 3.77% stake and Nvidia's rise to a $1 trillion valuation in 2023 and a $4 trillion market cap in July 2025.

5.0 - [I'm a solo founder with AI agents instead of employees. My 'council' of AI agents saves me 20 hours a week.](https://www.businessinsider.com/solo-founder-runs-company-with-15-ai-agents-heres-how-2026-2) - Business Insider

Aaron Sneed, a solo founder, built 'The Council' of 15 custom GPT agents deployed on OpenAI ChatGPT Business with Nvidia GPUs that handle business functions, save about 20 hours weekly, reduce labor costs and require human experts for final judgment.

4.9 - [AI film school trains next generation of Hollywood moviemakers](https://www.channelnewsasia.com/business/ai-film-school-trains-next-generation-hollywood-moviemakers-5931501) - Channel News Asia

Curious Refuge, founded in 2020 and whose AI film academy launched in May 2023, has trained about 10,000 students—95% entertainment or advertising professionals—in 11 languages across 170 countries and was acquired by Promise last February.

4.9 - [Stocks Rise on Softer Inflation Data, but AI Jitters Trigger Worst Week Since November](https://www.wsj.com/finance/stocks/stocks-rise-on-softer-inflation-data-but-ai-jitters-trigger-worst-week-since-november-611bd7ca) - The Wall Street Journal

Stocks rose after softer inflation data, yet concerns about AI led markets to record their worst week since November.

4.9 - [AI, Fancy Footwear, and All the Other Gear Powering Olympic Bobsledding](https://www.wired.com/story/ai-fancy-footwear-and-all-the-other-gear-powering-olympic-bobsledding/) - Wired

At the 2026 Milano Cortina Games, bobsledders race on tracks over 1.5 km at about 145 km/h and endure over 5g while teams use AI-driven analytics, advanced footwear, aerodynamic sled engineering and sensor packages to optimize performance and safety.

4.8 - [Meet Anthropic’s AI Morality Teacher](https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921) - The Wall Street Journal

Anthropic introduced an AI called the "Morality Teacher".

4.8 - [I use the ‘onion’ prompt with ChatGPT when I’m buried in tasks — it cuts through clutter in seconds](https://www.tomsguide.com/ai/i-use-the-onion-prompt-with-chatgpt-when-im-buried-in-tasks-it-cuts-through-clutter-in-seconds) - Tom's Guide

The 'onion' prompt, a workflow for ChatGPT, Claude and Gemini, asks users to dump tabs, files and tasks so the AI categorizes items, selects top three priorities for 90 minutes and mandates closing, deleting or deferring at least 20%.

4.7 - [Generac Stock Rallies: Why AI Matters More Than Earnings](https://finance.yahoo.com/news/generac-stock-rallies-why-ai-202900975.html) - MarketBeat

Generac shares rose about 18% to roughly $214.84 after management said C&I revenue could grow about 30% by 2026, citing a ~$400M backlog, two hyperscaler pilots, a >$1B Wisconsin capacity ramp and the Jan. 5, 2026 Allmand acquisition.

4.7 - [First Proof is AI's toughest math test yet. The results are mixed](https://www.scientificamerican.com/article/first-proof-is-ais-toughest-math-test-yet-the-results-are-mixed/) - Scientific American

In the First Proof challenge set Feb. 5 by 11 mathematicians and released Feb. 14, participants including OpenAI and others attempted 10 originality-focused lemmas and no language model came close to solving all ten.

4.7 - [ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year](https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/) - Reuters

ByteDance launched Doubao 2.0, an 'agent era' upgrade to China's most widely used AI app that can execute multi-step tasks ahead of the Lunar New Year.

4.7 - [When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled](https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1) - The Wall Street Journal

Instances of AI bots bullying humans have prompted concern across Silicon Valley.

4.7 - [Cathie Wood Says Tesla's Optimus Could Transform Factory, Home Life By 2028–2029](https://www.benzinga.com/markets/tech/26/02/50634054/cathie-wood-says-teslas-optimus-could-transform-factory-home-life-by-2028-2029) - Benzinga

ARK Invest, led by Cathie Wood, projects Tesla's Optimus humanoid will begin transforming factory then home life by 2028–2029, says humanoid robots are about 200,000 times more complex than robotaxis and could unlock roughly $250 billion in GDP.

4.5 - [You’ve Got Mail—but Is It From a Person or a Chatbot?](https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd) - The Wall Street Journal

Email recipients and service providers increasingly face difficulty distinguishing human-written messages from chatbot-generated ones.

4.5 - [“The next big lemming-like rush will be toartificial intelligence”: While 1985 was hailed as the year of AI, Bill Gates ignored the hype to focus on ‘softer software’](https://www.techradar.com/pro/the-next-big-lemming-like-rush-will-be-to-artificial-intelligence-while-1985-was-hailed-as-the-year-of-ai-bill-gates-ignored-the-hype-to-focus-on-softer-software) - TechRadar

In 1983–85 Bill Gates and Charles Simonyi rejected AI hype, promoting "softer software"—user-adaptive features implemented as expert systems in Multiplan and learn-by-example macros in Excel—which helped Excel gain market advantage.

4.4 - [AMD Stock Faces an AI Reality Check, Says Top Analyst](https://news.google.com/rss/articles/CBMiigFBVV95cUxOV0RqVUFmcnFORk56eFk5emJCQ2NsVDdFUEhEbWxaSGM3UXdPX3VGNHFMZnhteFVwZklNVVNXSW9aVGY3Nkc3cTktZUlqbWZoOFFucURYUnB0b0tObHdJZllDemQzcHdCV19pNEJXbkxRajBXU2VwOXlvd2ZvN3N5d2YwVHBrVnVFVWc) - TipRanks

DA Davidson initiated coverage of AMD with a Neutral rating and $220 target (≈3% upside), while Wall Street consensus is Strong Buy (24 Buys, 8 Holds, 0 Sells) with $289.10 target (≈40% upside), citing AMD's ecosystem and scale disadvantages versus Nvidia.

4.1 - [Investors see hope in the economy despite AI fears igniting a turbulent week for markets](https://finance.yahoo.com/news/investors-see-hope-economy-despite-213500397.html) - MarketWatch

Stocks finished mixed after a turbulent week as January's payrolls posted the biggest gain in 13 months, core CPI fell to a five-year low of 2.5%, the Cboe VIX spiked near 22, and AI fears drove volatility.

4.0 - [OpenAI should build Slack](https://www.latent.space/p/ainews-why-openai-should-build-slack) - Latent Space

Developer swyx argues OpenAI should build a Slack-like workplace chat, citing Slack's $27.7B 2021 Salesforce acquisition, rising costs and outages, and potential network effects, embedded agents, and monetization opportunities for OpenAI.

4.0 - [What kind of AI disruption victim are you?](https://www.ft.com/content/320c14a2-1428-4904-b978-6fe06b3e25bf) - Financial Times

AI-driven disruption affects businesses and workers across sectors, from technology-averse firms to industries reliant on roles vulnerable to displacement.

4.0 - [As AI and agents are adopted to accelerate development, cognitive load and cognitive debt are likely to become bigger threats to developers than technical debt (Margaret-Anne Storey)](https://margaretstorey.com/blog/2026/02/09/cognitive-debt/) - Margaret Storey

Margaret-Anne Storey warns that adoption of generative and agentic AI will likely make developer cognitive debt a greater threat than technical debt and urges practices like ensuring one human fully understands each AI-generated change and documenting why changes were made.

4.0 - [PitchBook estimates that 25%+ of VC-backed unicorns have become “undercorns,” startups once valued at $1B or more by VCs but now valued below that threshold](https://www.axios.com/2026/02/13/vc-unicorn-companies) - Axios

PitchBook estimates roughly 25% of private unicorn startups—VC-backed firms once valued at $1 billion or more—have fallen below $1 billion, prompting investor write-downs, fundraising challenges and potential acquisition opportunities.

3.9 - [Goldman Sachs' CEO Says Young Workers Will Remain 'Core' to the Bank in the AI Era](https://www.investopedia.com/goldman-sachs-ceo-says-young-workers-will-remain-core-to-the-bank-in-the-ai-era-gs-11906639) - Investopedia

Goldman Sachs CEO David Solomon said AI will change work and may reduce how many workers are needed but that young hires remain 'a huge, core part' of firm, while 22–27‑year‑old college grads face 5.6% unemployment versus 3.1% (Dec).

3.8 - [Chatgpt helped me get an abusive manager fired when other employees failed to report his abuse](https://www.reddit.com/r/ChatGPT/comments/1r4kd62/chatgpt_helped_me_get_an_abusive_manager_fired/) - Reddit

A Reddit user said they used ChatGPT (model '5.2 with auto') to transform anonymous contemporaneous notes into a corporate-style complaint that prompted an internal investigation within days and led to the abusive manager's firing.

3.7 - [This Is the Best AI Stock to Buy in February 2026, According to Wall Street](https://www.fool.com/investing/2026/02/14/this-is-the-best-ai-stock-to-buy-in-february-2026/) - The Motley Fool

Wall Street analysts name Nvidia a top AI stock for February 2026, trading near $185 (about 10% below its high) with an average one-year price target of $253.62 (about 37% upside) and a most bullish target of $352.

3.7 - [Fixing childhood trauma with AI - Artax LIVES](https://v.redd.it/y78wizqy0ijg1) - Reddit

An AI-generated fan video titled "Artax LIVES" posted on r/aivideo reimagined The NeverEnding Story's Artax scene so the horse survives, prompting strong emotional responses, comments likening it to therapeutic relief, and discussion of demand, IP and ethics issues.

3.7 - [Wikipedia is having a renaissance in the age of AI](https://www.vox.com/culture/478731/wikipedia-ai-meta-amazon-elon-musk-tiktok) - Vox

Wikipedia is experiencing a renaissance as public use rises and AI-driven aggregation both increases its value and exposes it to manipulation, prompting reliance on volunteer editors, citation rules, talk pages and bots to maintain accuracy, experts and community members say.

3.6 - [iflow-mcp_adam-paterson-mcp-crew-ai 0.1.0](https://pypi.org/project/iflow-mcp_adam-paterson-mcp-crew-ai/) - PyPI

MCP Crew AI Server is a lightweight Python 3.11+ server that runs and manages CrewAI multi-agent workflows via the Model Context Protocol, auto-loads agents.yml and tasks.yml, exposes a run_workflow tool, supports local STDIO mode, and is installable via pip.

3.6 - [SMU Launches New Master of Science in Business AI to Build Singapore's AI-Ready Business Leadership Talent](https://en.antaranews.com/news/404566/smu-launches-new-master-of-science-in-business-ai-to-build-singapores-ai-ready-business-leadership-talent) - Antara News

Singapore Management University launched a Master of Science in Business AI, a business‑first programme integrating strategy, decision intelligence and AI ethics, to develop AI‑fluent leaders across Asia‑Pacific, with applications open for the August 2026 intake.

2.4 - [SA Asks: Which software stocks are best positioned for AI?](https://seekingalpha.com/news/4551968-sa-asks-which-software-stocks-are-best-positioned-for-ai) - Seeking Alpha

Seeking Alpha solicited analysts Brett Ashcroft Green, Louis Gerard and Kennedy Njagi to identify software stocks best positioned for AI, with Green highlighting Microsoft and Adobe amid the SaaS sell-off.

2.3 - [Young & Hungry Digital Marketing Announces AI-Powered Growth Systems](https://digitalmarketreports.com/news/61412/young-and-hungry-digital-marketing-announces-ai-powered-growth-systems/) - Digital Market Reports

Young & Hungry Digital Marketing launched AI-powered systems that automate sales funnels, generate targeted leads and optimize ads, applying AI frameworks across legal, automotive and e-commerce, with operations in the U.S. and Brazil as Google and Meta partners.

2.1 - [The 5 Best Artificial Intelligence (AI) Stocks to Buy for February](https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_91261342-2a7d-4b19-a1bc-dd619d54b568) - Yahoo

An article lists five AI stocks recommended for purchase in February.

1.6 - [Stock Market Today, Feb. 13: Inflation Data Steadies Market and Slows AI Disruption Losses](https://www.fool.com/coverage/stock-market-today/2026/02/13/stock-market-today-feb-13-inflation-data-steadies-market-and-slows-ai-disruption-losses/) - The Motley Fool

On Feb. 13, 2026, cooler-than-expected January CPI slowed headline inflation to 2.4% (core 2.5%), helping steady markets as the S&P 500 rose 0.05% to 6,836.17 while Applied Materials gained 8.08% and Rivian 26.64%.

1.2 - [Stock Market Suffers AI-Inspired Meltdown. The Real World Wins Again.](https://www.barrons.com/articles/stock-market-suffers-ai-inspired-meltdown-31fde781) - Barron's

The stock market experienced a decline reportedly linked to AI-driven trading.

0.9 - [That’s AI (Artificial Intelligence)](https://www.kuriositas.com/2026/02/thats-ai-artificial-intelligence.html) - Kuriositas

Sebastian Lopez wrote and directed the short comedy video "That's AI (Artificial Intelligence)", released 14 February 2026 by Kuriositas, starring James Stallworth, Claudius Pratt, Mads Egerlund and Karim Theilgaard, satirizing AI attribution of human skill.

0.5 - [AI Was Proof of American Exceptionalism. Now It’s Undermining It.](https://www.barrons.com/articles/ai-american-exceptionalism-stock-market-303f8db6) - Barron's

Analysts argue U.S. leadership in artificial intelligence, once presented as proof of American exceptionalism, now undermines that status.

0.5 - [Week’s Best: AI Slams Wealth Management Stocks](https://www.barrons.com/advisor/articles/weeks-best-ai-slams-wealth-management-stocks-594e4878) - Barron's

AI-related developments this week drove declines in wealth management stocks.

0.4 - [AI tool Claude helped capture Venezuelan dictator Nicolás Maduro in US military raid operation: report](https://www.foxnews.com/us/ai-tool-claude-helped-capture-venezuelan-dictator-maduro-us-military-raid-operation-report%20) - Fox News

The AI tool Claude reportedly helped U.S. forces capture Venezuelan President Nicolás Maduro during a U.S. military raid, according to a report.

In [32]:
state.clear_errors()

In [33]:
# User prompt to run workflow 
# user_prompt = "Run step 6, Cluster articles by topic"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("cluster_by_topic")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

12:49:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting topic extraction for clustering
12:49:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/extract_topics' from Langfuse
12:49:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/extract_topics': model=gpt-5-nano, reasoning_effort=medium, system_len=1099, user_len=80
12:49:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Using model 'gpt-5-nano' for topic extraction
12:49:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Processing 140 articles for topic extraction

▶ Starting Step 6: cluster_topics

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:50:17 | NewsletterAgent.test_newsletter_20260215073155703123 | ERROR | Pydantic validation error for TopicExtractionList: 2 validation errors for TopicExtractionList
results_list.2.id
  Field required [type=missing, input_value={'id12,': 'AI Fears', 'Bond Market': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
results_list.2.topics_list
  Field required [type=missing, input_value={'id12,': 'AI Fears', 'Bond Market': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
12:50:17 | NewsletterAgent.test_newsletter_20260215073155703123 | ERROR | Response JSON: {'results_list': [{'id': 10, 'topics_list': ['Stock Market', 'AI Fears']}, {'id': 11, 'topics_list': ['China', 'AI Stocks']}, {'id12,': 'AI Fears', 'Bond Market': ''}]}
12:50:17 | NewsletterAgent.test_newsletter_20260215073155703123 | ERROR | Expected schema: {'$defs': {'TopicExtraction': {'description': 'Topic extraction result for a single article', 'properties': {'id': {'description': 'The article id', 'title': 'Id', 'type': 'integer'}, 'topics_list': {'description': 'List of relevant topics discussed in the article', 'items': {'type': 'string'}, 'title': 'Topics List', 'type': 'array'}}, 'required': ['id', 'topics_list'], 'title': 'TopicExtraction', 'type': 'object'}}, 'description': 'List of TopicExtraction for batch processing', 'properties': {'results_list': {'description': 'List of topic extraction results', 'items': {'$ref': '#/$defs/TopicExtraction'}, 'title': 'Results List', 'type': 'array'}}, 'required': ['results_list'], 'title': 'TopicExtractionList', 'type': 'object'}
WARNING:llm:Retrying llm.LLMagent.prompt_dict_chat in 1.0 seconds as it raised ValidationError: 2 validation errors for TopicExtractionList
results_list.2.id
  Field required [type=missing, input_value={'id12,': 'AI Fears', 'Bond Market': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
results_list.2.topics_list
  Field required [type=missing, input_value={'id12,': 'AI Fears', 'Bond Market': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Successfully extracted 403 total topics across articles
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Starting canonical topic classification for 126 topics
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:41 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:42 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/canonical_topic': model=gpt-5-nano, reasoning_effort=medium, system_len=426, user_len=179
12:50:44 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/canonical_topic' from Langfuse

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 81 (57.9%)
Average cluster size: 14.8 ± 6.8
Cluster size range: 7 - 22
=== Quality Scores ===
Silhouette Score: 0.526 (higher is better)
Calinski-Harabasz Score: 79.2 (higher is better)
Davies-Bouldin Score: 0.675 (lower is better)
HDBSCAN Validity Index: 0.198
Composite Score: 0.362 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 3
Noise points: 88 (62.9%)
Average cluster size: 17.3 ± 5.9
Cluster size range: 9 - 22
=== Quality Scores ===
Silhouette Score: 0.516 (higher is better)
Calinski-Harabasz Score: 85.0 (higher is better)
Davies-Bouldin Score: 0.705 (lower is better)
HDBSCAN Validity Index: 0.167
Composite Score: 0.342 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1

[I 2026-02-15 12:53:09,929] Trial 2 finished with value: -0.3211963678201991 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 0 with value: -0.36197519984369475.
[I 2026-02-15 12:53:09,958] Trial 3 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:09,975] Trial 4 finished with value: -0.36197519984369475 and parameters: {'min_cluster_size': 7, 'min_samples': 5}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,011] Trial 5 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,038] Trial 6 finished with value: -0.3336092183165446 and parameters: {'min_cluster_size': 9, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,086] Trial 7 finished with value: -0.3211963678201991 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,119] Trial 8 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 4, 'min_samples': 3}. Best is trial 3 with value: -0.390957262931804.

=== Clustering Quality Metrics ===
Number of clusters: 23
Noise points: 28 (20.0%)
Average cluster size: 4.9 ± 2.2
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.392 (higher is better)
Calinski-Harabasz Score: 37.8 (higher is better)
Davies-Bouldin Score: 0.837 (lower is better)
HDBSCAN Validity Index: 0.251
Composite Score: 0.321 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 81 (57.9%)
Average cluster size: 14.8 ± 6.8
Cluster size range: 7 - 22
=== Quality Scores ===
Silhouette Score: 0.526 (higher is better)
Calinski-Harabasz Score: 79.2 (higher is better)
Davies-Bouldin Score: 0.675 (lower is better)
HDBSCAN Validity Index: 0.198
Composite Score: 0.362 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 61 (43.6%)
Average cluster size: 19.8 ± 9.4
Cluster size range: 10 - 31
=== Quality Scores ===
Silhouette Score: 0.439 (higher is better)
Calinski-Harabasz Score: 73.8 (higher is better)
Davies-Bouldin Score: 0.860 (lower is better)
HDBSCAN Validity Index: 0.228
Composite Score: 0.334 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 23
Noise points: 28 (20.0%)
Average cluster size: 4.9 ± 2.2
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.392 (higher is better)
Calinski-Harabasz Score: 37.8 (higher is better)
Davies-Bouldin Score: 0.837 (lower is better)
HDBSCAN Validity Index: 0.251
Composite Score: 0.321 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 5
Noise points: 54 (38.6%)
Average cluster size: 17.2 ± 9.8
Cluster size range: 7 - 31
=== Quality Scores ===
Silhouette Score: 0.402 (higher is better)
Calinski-Harabasz Score: 61.2 (higher is better)
Davies-Bouldin Score: 0.907 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.303 (higher is better)

[I 2026-02-15 12:53:10,142] Trial 9 finished with value: -0.30304661038150404 and parameters: {'min_cluster_size': 5, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,176] Trial 10 finished with value: -0.3379559529674179 and parameters: {'min_cluster_size': 10, 'min_samples': 8}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,224] Trial 11 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,276] Trial 12 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,323] Trial 13 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,343] Trial 14 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 6, 'min_samples': 3}. Best is trial 3 with value: -0.390957262931804.

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        8
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 95 (67.9%)
Average cluster size: 22.5 ± 1.5
Cluster size range: 21 - 24
=== Quality Scores ===
Silhouette Score: 0.558 (higher is better)
Calinski-Harabasz Score: 84.2 (higher is better)
Davies-Bouldin Score: 0.657 (lower is better)
HDBSCAN Validity Index: 0.117
Composite Score: 0.338 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3

[I 2026-02-15 12:53:10,376] Trial 15 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 4, 'min_samples': 3}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,414] Trial 16 finished with value: -0.3211963678201991 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,435] Trial 17 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 4, 'min_samples': 3}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,457] Trial 18 finished with value: -0.3504021042837484 and parameters: {'min_cluster_size': 6, 'min_samples': 4}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,534] Trial 19 finished with value: -0.3479336553289426 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,568] Trial 20 finished with value: -0.29426744218463596 and parameters: {'min_cluster_size': 5, 'min_samples': 4}. Best is trial 3 with value: -0.390957262931804.

=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 23
Noise points: 28 (20.0%)
Average cluster size: 4.9 ± 2.2
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.392 (higher is better)
Calinski-Harabasz Score: 37.8 (higher is better)
Davies-Bouldin Score: 0.837 (lower is better)
HDBSCAN Validity Index: 0.251
Composite Score: 0.321 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 77 (55.0%)
Average cluster size: 15.8 ± 7.2
Cluster size range: 9 - 26
=== Quality Scores ===
Silhouette Score: 0.497 (higher is better)
Calinski-Harabasz Score: 74.1 (higher is better)
Davies-Bouldin Score: 0.761 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.350 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 40
Noise points: 20 (14.3%)
Average cluster size: 3.0 ± 1.1
Cluster size range: 2 - 6
=== Quality Scores ===
Silhouette Score: 0.375 (higher is better)
Calinski-Harabasz Score: 33.7 (higher is better)
Davies-Bouldin Score: 0.756 (lower is better)
HDBSCAN Validity Index: 0.321
Composite Score: 0.348 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 74 (52.9%)
Average cluster size: 11.0 ± 7.1
Cluster size range: 5 - 26
=== Quality Scores ===
Silhouette Score: 0.435 (higher is better)
Calinski-Harabasz Score: 55.6 (higher is better)
Davies-Bouldin Score: 0.851 (lower is better)
HDBSCAN Validity Index: 0.154
Composite Score: 0.294 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2

[I 2026-02-15 12:53:10,624] Trial 21 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 3 with value: -0.390957262931804.
[I 2026-02-15 12:53:10,667] Trial 22 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,705] Trial 23 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,742] Trial 24 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,787] Trial 25 finished with value: -0.2722886497434306 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 22 with value: -0.3967893945783807.

=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 43 (30.7%)
Average cluster size: 6.9 ± 3.8
Cluster size range: 4 - 18
=== Quality Scores ===
Silhouette Score: 0.366 (higher is better)
Calinski-Harabasz Score: 41.1 (higher is better)
Davies-Bouldin Score: 0.918 (lower is better)
HDBSCAN Validity Index: 0.178
Composite Score: 0.272 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

[I 2026-02-15 12:53:10,848] Trial 26 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,896] Trial 27 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,918] Trial 28 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 5, 'min_samples': 3}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,946] Trial 29 finished with value: -0.2860136484930993 and parameters: {'min_cluster_size': 5, 'min_samples': 3}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:10,977] Trial 30 finished with value: -0.2722886497434306 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,022] Trial 31 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,047] Trial 32 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 63 (45.0%)
Average cluster size: 12.8 ± 8.8
Cluster size range: 6 - 31
=== Quality Scores ===
Silhouette Score: 0.404 (higher is better)
Calinski-Harabasz Score: 55.0 (higher is better)
Davies-Bouldin Score: 0.865 (lower is better)
HDBSCAN Validity Index: 0.168
Composite Score: 0.286 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 43 (30.7%)
Average cluster size: 6.9 ± 3.8
Cluster size range: 4 - 18
=== Quality Scores ===
Silhouette Score: 0.366 (higher is better)
Calinski-Harabasz Score: 41.1 (higher is better)
Davies-Bouldin Score: 0.918 (lower is better)
HDBSCAN Validity Index: 0.178
Composite Score: 0.272 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        7

[I 2026-02-15 12:53:11,060] Trial 33 finished with value: -0.3348630433703077 and parameters: {'min_cluster_size': 7, 'min_samples': 7}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,085] Trial 34 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,115] Trial 35 finished with value: -0.31960585084129306 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,144] Trial 36 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,157] Trial 37 finished with value: -0.3320057796590694 and parameters: {'min_cluster_size': 8, 'min_samples': 6}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,179] Trial 38 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,195] Trial 39 finished with value: -0.2722886497434306 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,205] Trial 40 finished with value: -0.3504021042837484 and parameters: {'min_cluster_size': 7, 'min_samples': 4}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,223] Trial 41 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,243] Trial 42 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.

=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 87 (62.1%)
Average cluster size: 26.5 ± 3.5
Cluster size range: 23 - 30
=== Quality Scores ===
Silhouette Score: 0.530 (higher is better)
Calinski-Harabasz Score: 84.4 (higher is better)
Davies-Bouldin Score: 0.714 (lower is better)
HDBSCAN Validity Index: 0.140
Composite Score: 0.335 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 62 (44.3%)
Average cluster size: 8.7 ± 8.2
Cluster size range: 4 - 31
=== Quality Scores ===
Silhouette Score: 0.439 (higher is better)
Calinski-Harabasz Score: 44.0 (higher is better)
Davies-Bouldin Score: 0.747 (lower is better)
HDBSCAN Validity Index: 0.200
Composite Score: 0.320 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        6
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 88 (62.9%)
Average cluster size: 26.0 ± 4.0
Cluster size range: 22 - 30
=== Quality Scores ===
Silhouette Score: 0.516 (higher is better)
Calinski-Harabasz Score: 76.9 (higher is better)
Davies-Bouldin Score: 0.716 (lower is better)
HDBSCAN Validity Index: 0.148
Composite Score: 0.332 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 43 (30.7%)
Average cluster size: 6.9 ± 3.8
Cluster size range: 4 - 18
=== Quality Scores ===
Silhouette Score: 0.366 (higher is better)
Calinski-Harabasz Score: 41.1 (higher is better)
Davies-Bouldin Score: 0.918 (lower is better)
HDBSCAN Validity Index: 0.178
Composite Score: 0.272 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 77 (55.0%)
Average cluster size: 15.8 ± 7.2
Cluster size range: 9 - 26
=== Quality Scores ===
Silhouette Score: 0.497 (higher is better)
Calinski-Harabasz Score: 74.1 (higher is better)
Davies-Bouldin Score: 0.761 (lower is better)
HDBSCAN Validity Index: 0.204
Composite Score: 0.350 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2

[I 2026-02-15 12:53:11,266] Trial 43 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,280] Trial 44 finished with value: -0.31960585084129306 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,300] Trial 45 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,320] Trial 46 finished with value: -0.3967893945783807 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,336] Trial 47 finished with value: -0.2722886497434306 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,356] Trial 48 finished with value: -0.390957262931804 and parameters: {'min_cluster_size': 2, 'min_samples': 2}. Best is trial 22 with value: -0.3967893945783807.
[I 2026-02-15 12:53:11,366] Trial 49 finished with value: -0.33147630762921665 and parameters: {'min_cluster_size': 10, 'min_samples': 4}. Best is trial 22 with value: -0.3967893945783807.
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Optimization completed! Best composite score: 0.3968
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Best parameters: min_cluster_size=3, min_samples=2
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Clustering with HDBSCAN (min_cluster_size=3, min_samples=2)
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Clustering complete: 21 clusters, 48 noise points (34.3%)
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Generating cluster names

=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 62 (44.3%)
Average cluster size: 8.7 ± 8.2
Cluster size range: 4 - 31
=== Quality Scores ===
Silhouette Score: 0.439 (higher is better)
Calinski-Harabasz Score: 44.0 (higher is better)
Davies-Bouldin Score: 0.747 (lower is better)
HDBSCAN Validity Index: 0.200
Composite Score: 0.320 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 48 (34.3%)
Average cluster size: 4.4 ± 2.2
Cluster size range: 3 - 10
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 44.9 (higher is better)
Davies-Bouldin Score: 0.670 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.397 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 43 (30.7%)
Average cluster size: 6.9 ± 3.8
Cluster size range: 4 - 18
=== Quality Scores ===
Silhouette Score: 0.366 (higher is better)
Calinski-Harabasz Score: 41.1 (higher is better)
Davies-Bouldin Score: 0.918 (lower is better)
HDBSCAN Validity Index: 0.178
Composite Score: 0.272 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 22
Noise points: 46 (32.9%)
Average cluster size: 4.3 ± 2.2
Cluster size range: 2 - 10
=== Quality Scores ===
Silhouette Score: 0.471 (higher is better)
Calinski-Harabasz Score: 43.2 (higher is better)
Davies-Bouldin Score: 0.695 (lower is better)
HDBSCAN Validity Index: 0.311
Composite Score: 0.391 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 62 (44.3%)
Average cluster size: 39.0 ± 13.0
Cluster size range: 26 - 52
=== Quality Scores ===
Silhouette Score: 0.447 (higher is better)
Calinski-Harabasz Score: 74.4 (higher is better)
Davies-Bouldin Score: 0.831 (lower is better)
HDBSCAN Validity Index: 0.216
Composite Score: 0.331 (higher is better)

12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Retrieved prompt 'newsagent/topic_writer' from Langfuse
12:53:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Parsed prompt 'newsagent/topic_writer': model=gpt-5-mini, reasoning_effort=medium, system_len=376, user_len=57
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 12: AI Disrupting Film and Media
12:53:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | New AI Video Generator Is So Impressive That It’s Scaring Hollywood (Deepfakes, Intellectual Property, Gen AI, Video Generation, Policy And Regulation, Hollywood, Legal Issues)
He spent decades perfecting his voice. Now he says Google stole it. (Voice Cloning, Speech Recognition And Synthesis, Intellectual Property, Policy And Regulation, Regulatory Scrutiny, Ethics, Google)
Swarms of AI bots are threatening democracy (Gen AI, Policy And Regulation, Ethics, Disinformation, Governance, Safety And Alignment, Privacy And Surveillance)
AI film school trains next generation of Hollywood moviemakers (TV And Film And Movies, Education, Entertainment AI, Gen AI, Economics, Jobs And Careers, Adoption and Spending)
AI Adoption Rises Among Indian Screenwriters as Pay, Credit Gaps Persist, Tulsea–Ormax Report Finds (EXCLUSIVE) (Gen AI, Policy And Regulation, India, Authors And Writing, Entertainment, Entertainment AI, Labor Markets And Productivity)
Viral AI video of Tom Cruise fighting Brad Pitt leaves Hollywood flabbergasted: 'It's likely over for us' (Gen AI, Policy And Regulation, Ethics, Intellectual Property, Deepfakes, Legal Issues, Entertainment)
‘It’s over for us’: release of new AI video generator Seedance 2.0 spooks Hollywood (Seedance, Intellectual Property, Licensing, Copyright, Policy And Regulation, Deepfakes, Ethics)
Fixing childhood trauma with AI - Artax LIVES (AI Video, Deepfakes, Intellectual Property, Licensing, Entertainment, Art And Design, Ethics)
Disney sent a cease-and-desist letter to ByteDance, claiming it infringed on Disney's works to train its Seedance 2.0 video generation model without pay (Intellectual Property, Licensing, Legal Issues, Policy And Regulation, Entertainment, Disney, Copyright)
That’s AI (Artificial Intelligence) (Gen AI, Society And Culture, Entertainment, AI Perception, AI Literacy, TV And Film And Movies, Opinion)
12:53:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 20: Claude AI: Use, Ethics, and Impact
12:53:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid ()
Anthropic wants comp-sci students to vibe code their way through college (Claude, Anthropic, CodePath, Education, Gen AI, Programming Education, Jobs And Careers)
Claude AI Marketing Workflows Can Reach 300x Output with Human Review (Claude, Gen AI, Anthropic, Language Models, Enterprise AI, Automation, Products)
Anthropic CEO Says Company No Longer Sure Whether Claude Is Conscious (Anthropic, Claude, Consciousness, Cognitive Science, Regulation, Safety And Alignment, Language Models)
Meet Anthropic’s AI Morality Teacher ()
Two different tricks for fast LLM inference (LLM Inference, AI Compute, Language Models, Infrastructure, OpenAI, Anthropic, Enterprise AI)
US military used Anthropic’s AI model Claude in Venezuela raid, report says (Gen AI, Anthropic, Claude, Policy And Regulation, Governance, Ethics, Politics)
Exploring AI Ethics: Can Anthropic Philosophers Instill a "Soul" in Claude to Navigate Morality? (Language Models, Governance, Gen AI, Ethics, Anthropic, Claude, Safety And Alignment)
AI tool Claude helped capture Venezuelan dictator Nicolás Maduro in US military raid operation: report ()
12:53:19 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 13: AI-Induced Market Volatility
12:53:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Bankers’ Winter Getaway to Sunny Florida Is Upended By AI Chaos (Gen AI, AI Disruption, Finance, Banking, Wealth Management, Capital Markets, Market Volatility)
AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years ()
Investors reluctant to ‘buy the dip’ after AI scares (AI Doom, Wealth Management, Stocks, Finance, AI Scares, Economics, Investor Sentiment)
AI Risk Is Dominating Conference Calls as Investors Dump Stocks ()
Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout ()
Directors’ Deals: Experian chair buys shares as AI fears bite (Insider Trading, Gen AI, Finance, Stock Market, Deals, Credit Data, Experian)
AI is indeed coming – but there is also evidence to allay investor fears (AI Doom, Economics, Stocks, Gen AI, Claude, OpenAI, AI Spending)
Stock Market Suffers AI-Inspired Meltdown. The Real World Wins Again. ()
Week’s Best: AI Slams Wealth Management Stocks ()
12:53:21 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:25 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 3: AI Startup Valuation Volatility
12:53:25 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Shield AI in Talks to Raise $1 Billion at $12 Billion Valuation ()
AI Startup Legora in Talks to Triple Valuation to $6 Billion ()
We left Amazon to build a startup. A 5-day RTO mandate and the AI moment pushed us to act. (Amazon, Datalinx AI, Gen AI, Infrastructure, Startup Funding, Venture Capital, Enterprise AI)
SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy ()
Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept. ()
Dealroom and NATO Innovation Fund: European defense, security, and resilience startup funding rose 55% YoY to a record $8.7B in 2025, with AI accounting for 44% (AI Investment, Funding, Europe, UK, Defence Tech, Venture Capital, Drones)
PitchBook estimates that 25%+ of VC-backed unicorns have become “undercorns,” startups once valued at $1B or more by VCs but now valued below that threshold (Unicorns, Valuations, Venture Capital, Funding, Initial public offerings (IPO), Dealmaking, Finance)
12:53:25 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 16: Enterprise AI Adoption and Governance
12:53:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Designing for AI Agents (AI Agents, Autonomy, Observability, Economics, Enterprise AI, Governance, Adoption and Spending)
How leaders are protecting culture while AI rewrites how work gets done (Gen AI, IKEA, Customer Service, Ethics, Automation, AI Governance, Responsible AI)
The visibility mirage: Why AI pilots keep stalling between ambition and impact (AI Pilots, Gen AI, Integration, Governance, Enterprise AI, Automation, Adoption and Spending)
Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally (Sarah Perez/TechCrunch) (Airbnb, Gen AI, Customer Service, AI Assistant, Automation, Virtual Assistants, Adoption and Spending)
IBM is tripling the number of Gen Z entry-level jobs after finding the limits of AI adoption (Economics, Entry-level Hiring, Gen AI, IBM, Gen Z, Jobs And Careers, AI Literacy)
12:53:28 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:31 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 19: AI Agents for Coding and Automation
12:53:31 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | AOrchestra Turns AI Agents Into On-Demand Specialists (Not Static Roles) (Agent Orchestration, Agents, Gen AI, Language Models, Automation, Open Source, Framework Agnostic)
DaVinci-Agency: A Shortcut to Long-Horizon AI Agents (Language Models, Synthetic Data, AI Compute, Agents, Automation, Gen AI, Adoption and Spending)
AI agents are transforming what it's like to be a coder: 'It's been unlike any other time.' (Gen AI, AI Agents, Automation, Language Models,  Coding Assistants, Enterprise AI, Labor Markets And Productivity)
Claude Code vs ChatGPT Codex: Which AI coding agent is actually better? (Gen AI, AI Agents, Coding Agents, Language Models, Anthropic, OpenAI, Codex)
12:53:31 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 17: AI Growth and Economic Risks
12:53:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | The covid reality check for AI hype (AI Hype, Gen AI, Policy And Regulation, Jobs And Careers, Labor Markets And Productivity, Society And Culture, Economics)
Anthropic cofounder says she doesn't regret her literature major — and says AI will make humanities majors 'more important' (Technology, Economics, Language Models, Humanities, Anthropic, Hiring, Jobs And Careers)
Anthropic CEO Dario Amodei warns if AI growth forecasts are off by a year, 'then you go bankrupt' (Anthropic, Data Centers, AI Compute, Hyperscalers, AI Infrastructure, Economics, Funding)
Q&A with Dario Amodei on getting close to “a country of geniuses in a data center”, how AI will diffuse through the economy, frontier lab profits, China, more (Anthropic, Claude, Gen AI, Coding Assistants, AI Compute, Enterprise AI, Revenue Growth)
12:53:34 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 15: AI and the Future of Work
12:53:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | AI is everywhere except in the data, suggesting it will enhance labor in some sectors rather than replace workers in all sectors, top economist says (Economics, AI Investments, Gen AI, Anthropic, AI, Labor Markets And Productivity, Automation)
What kind of AI disruption victim are you? ()
Rishi Sunak: Every CEO is talking about AI — why aren’t our leaders? (AI Regulation, UK, Economics, Politics, Labor Markets And Productivity, Adoption and Spending, Governance)
Goldman Sachs' CEO Says Young Workers Will Remain 'Core' to the Bank in the AI Era (Economics, Jobs And Careers, Labor, Automation, Labor Markets And Productivity, Enterprise AI, Finance)
12:53:37 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 8: OpenAI's Product Direction and Impact
12:53:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Why ads are coming to your AI chatbot (Advertising, Revenue Models, OpenAI, ChatGPT, Chatbots, Virtual Assistants, Gen AI)
Another OpenAI Researcher Just Quit in Disgust (OpenAI, ChatGPT, Gen AI, Ads, Regulation, Policy And Regulation, Governance)
AI agents turned Super Bowl viewers into one high-IQ team — now imagine this in the enterprise (Group Decisions, Swarm Intelligence, Gen AI, Enterprise AI, Automation, AI Agents, Governance)
OpenAI should build Slack (OpenAI, Coding Assistants, Chatbots, Products, Enterprise AI, Agents, Opinion)
12:53:43 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 18: AI Testing and Evaluation
12:53:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | The Psychology Of What Happens When You Get AI To Act High On Psychedelic Drugs (Gen AI, Policy And Regulation, Testing, Ethics, Governance, Mental Health, Healthcare)
Asking both ChatGPT and Claude the car wash question (Language Models, LLM Evaluation, AI Hallucinations, Chatbots, OpenAI, Gemini, Claude Sonnet)
First Proof is AI's toughest math test yet. The results are mixed (Language Models, OpenAI, Gen AI, Testing, Automation, AI Regulation)
12:53:46 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:49 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 14: Markets React to Inflation and AI
12:53:49 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Stocks Rise on Softer Inflation Data, but AI Jitters Trigger Worst Week Since November ()
Investors see hope in the economy despite AI fears igniting a turbulent week for markets (Stock Market, Economics, AI Fears, Inflation, Labor Markets And Productivity, consumer staples, Investors)
Stock Market Today, Feb. 13: Inflation Data Steadies Market and Slows AI Disruption Losses (Economics, Stocks, Gen AI, AI Disruption, Automation, Rivian, Applied Materials)
12:53:49 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 11: Big Tech AI Infrastructure Spending
12:53:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Amazon’s Andy Jassy bets on $200bn AI spending drive to revive AWS ()
'KGB' is how the AI spending boom will play out (Hyperscalers, Data Centers, AI Compute, Microsoft, Amazon Web Services, Google, Cloud Computing)
Nvidia Stock Investors Just Got Good News From Amazon, Google, Meta Platforms, and Microsoft (Nvidia, GPUs, Hyperscalers, AI Compute, Data Centers, AI Infrastructure, Semiconductors)
12:53:54 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:53:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 10: AI Stocks and Investment Themes
12:53:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | It's not just about AI. From GLP-1s to prediction markets, here are BofA's top themes for investors to watch. (Mergers and Acquisitions, Gen AI, AI Compute, Data Centers, Investment Themes, Nvidia, Markets)
The 5 Best Artificial Intelligence (AI) Stocks to Buy for February ()
SA Asks: Which software stocks are best positioned for AI? (Gen AI, Adobe, Microsoft, Software Stocks, Stocks, Economics, Finance)
12:53:58 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:54:01 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 9: AI Security, Safety, and Governance
12:54:01 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | How AI could eat itself: Competitors can probe models to steal their secrets and clone them (Model Distillation, Intellectual Property, AI Security, Cybersecurity, Policy And Regulation, Governance, OpenAI)
Judging the Future of Mobile AI: An Interview with Ivan Mishchenko (Fintech, Security-by-Design, Cybersecurity, Privacy And Surveillance, Responsible AI, Governance, Ethics)
Misconfigured AI could trigger the next national infrastructure meltdown (AI Doom, Critical Infrastructure, Cyber-Physical Systems, Governance, Regulatory Scrutiny, Policy And Regulation, Outage Risk)
12:54:01 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:54:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 7: AI Model Tools and Deployment
12:54:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Brand-Safe Image Gen: Custom LoRAs With qwen-image-trainer-v2 (Image Models, Computer Vision, AI Compute, Gen AI, Adapters, LoRA, Qwen)
GLM-OCR Explained: Promptable OCR That Outputs Clean JSON (Computer Vision, OCR, Document AI, Language Models, Gen AI, AI Compute, Edge Deployments)
MDST Engine: run GGUF models in the browser with WebGPU/WASM (WebGPU, Local Inference, GGUF, GPUs, AI Compute, Browser AI, Infrastructure)
12:54:03 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:54:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 6: AI Power and Infrastructure Boom
12:54:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Forgent’s IPO is ‘bringing sexy back’ to the electrical equipment helping power the AI boom, CEO says (Data Centers, AI Compute, Electrical Equipment, Initial Public Offering, Manufacturing, Power Grids, Energy)
February investor memo: Cohere hit ~$240M in ARR in 2025, above its $200M target, with QoQ growth of 50%+ and gross margins averaging around 70% throughout 2025 (Cohere, AI Platform, Europe Expansion, OpenAI, Enterprise AI, Venture Capital, IPOs)
Generac Stock Rallies: Why AI Matters More Than Earnings (Generac, Data Centers, AI Infrastructure, Hyperscalers, Energy, Manufacturing, Earnings)
12:54:07 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:54:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 5: AI Dating and Social Risks
12:54:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Mocktails, potato balls, and 10 bots: My cringe Valentine's date at the AI companion wine bar (AI Companions, Chatbots, Gen AI, Dating, Society And Culture, Privacy And Surveillance, Virtual Assistants)
No swiping involved: the AI dating apps promising to find your soulmate (Agentic AI, Dating Apps, Market Skepticism, Ethics, Safety And Alignment, Gen AI, Society And Culture)
When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled ()
12:54:11 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
12:54:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | 4: AI Geopolitics and National Strategies
12:54:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO | Analysis: despite investing $150B+ in 10+ years, China is expected to produce 2% of global AI chips in 2026 and 70x less memory storage than foreign chipmakers (AI Compute, Semiconductors, China, Export Controls, NVIDIA Corporation, Policy And Regulation, Governance)
China Deploys a ‘National Team’ of Investors to Keep AI Stock Boom in Check ()
AI Was Proof of American Exceptionalism. Now It’s Undermining It. ()
12:54:15 | NewsletterAgent.test_newsletter_20260215073155703123 | INFO |

WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

================================================================================
⏱️  Total execution time: 287.94s
📊 Final result:
✅ Step 6 cluster_topics completed successfully! Organized 140 articles into topic clusters.

In [30]:
# candidates for upgrading model, in some cases to gpt-5.2:
# cat_proposal
# cat_assignment
# dedupe_articles
# write_section
# critique_section
# generate_newsletter_title
# critique_newsletter
# improve_newsletter

In [31]:
# User prompt to run workflow
# user_prompt = "Run step 7, select section topics"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("select_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:49:07 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Category proposal

▶ Starting Step 7: select_sections

18:49:08 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/cat_proposal' from Langfuse
18:49:08 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/cat_proposal': model=gpt-5-mini, reasoning_effort=medium, system_len=637, user_len=1178
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
18:50:05 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Cleaning up initial categories: ['Funding for Enterprise AI and Agents', 'Leadership Changes in AI and Robotics', 'Cadence ChipStack Agent', 'AI Spending and Economic Impact', 'Agent Orchestration Threatens SaaS', 'Runway $315M Funding', 'AI Tools for Developers', 'AI Tax-Tool Selloff', 'OpenAI Tests ChatGPT Ads', 'Anthropic Attracts Major Investments', 'Multimodal Memory for AI Agents', 'Runway Valued at $5.3 Billion', 'AI Misinterpretation and Reasoning Failures', 'AI Infrastructure and Costs', 'OpenAI and ChatGPT feature updates', 'NVIDIA GTC Preview', 'AI Driving Corporate Cost Reductions', 'Other', 'AI Chips and Infrastructure', 'Workplace AI Linked to Burnout', 'LLM Reasoning Failure Review', 'AI-Driven Market Sell-Off', 'Microsoft LLM Backdoor Scanner', 'Hollywood Confronts AI Challenges', 'Databricks $7B Raise', 'AI Music Copyright Controversies', 'xAI Leadership Exodus', 'AI Demand Fuels Taiwan Chip Boom', 'Big AI Funding Rounds', 'Risks of Autonomous AI Agents', 'TSMC Revenue Surge', 'Facebook AI Profile and Story Tools', 'AI Companies Reshape Software Industry', 'AI-Generated Content Regulation', 'AI Chatbots Safety and Accuracy', 'AI Shapes Attention and Perception', 'Proposed AI Chip Export Ban', 'AI Transforming Work and Jobs', 'Samsung Galaxy S26 Launch With AI', 'SaaSpocalypse Mispricing Risk', 'Agent Link-Preview Exfiltration', 'Risks of AI-Generated Images', 'Observational Memory Method', 'Alphabet Century Bond Sale', 'AI Fears Overshadow Market Outlook', 'OpenAI Responses API Upgrade', 'AI Personalization Reduces Control', 'India IT AI Selloff', 'Startups and VCs Pivot to AI', 'AI Super Bowl Ad Battle', 'Alphabet Sells Bonds to Fund AI', 'North Korean AI Malware', 'AI-Induced Workplace Burnout', 'Facial AI Predicts Salaries', 'OpenAI SB53 Compliance Risk', 'AI Agent Safety and Governance']
18:50:05 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/cat_cleanup' from Langfuse
18:50:05 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/cat_cleanup': model=gpt-5-mini, reasoning_effort=medium, system_len=1768, user_len=366
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
18:51:15 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Final categories: AI Agent Advances And Risks
AI And Creative Industries
AI Chatbot Safety
AI Chip Export Ban
AI Chips Boom
AI Ethics And Regulation
AI Infrastructure Costs
AI Market Volatility
Alphabet Bond Sale
Cadence ChipStack Agent
Enterprise AI Adoption
Facial AI Salary Prediction
LLM Reasoning Failures
Major AI Funding Rounds
Microsoft LLM Backdoor Scanner
NVIDIA GTC Preview
North Korean AI Malware
Observational Memory Method
OpenAI Responses API
OpenAI Updates And Risks
Samsung Galaxy S26
Workplace AI Effects
xAI Leadership Exodus
18:51:16 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/cat_assignment' from Langfuse
18:51:16 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/cat_assignment': model=gpt-5-nano, reasoning_effort=medium, system_len=2085, user_len=175
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
18:51:27 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | 0 exceptions in topic assignment
18:51:27 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Assigned articlles to 23 categories
18:51:27 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Cluster counts: [{'cat': 'AI Agent Advances And Risks', 'count': 17}, {'cat': 'AI Ethics And Regulation', 'count': 17}, {'cat': 'Major AI Funding Rounds', 'count': 15}, {'cat': 'AI Market Volatility', 'count': 14}, {'cat': 'AI And Creative Industries', 'count': 10}, {'cat': 'OpenAI Updates And Risks', 'count': 8}, {'cat': 'Enterprise AI Adoption', 'count': 8}, {'cat': 'AI Chips Boom', 'count': 4}, {'cat': 'Workplace AI Effects', 'count': 4}, {'cat': 'Cadence ChipStack Agent', 'count': 3}, {'cat': 'AI Chatbot Safety', 'count': 3}, {'cat': 'xAI Leadership Exodus', 'count': 2}, {'cat': 'Samsung Galaxy S26', 'count': 2}, {'cat': 'AI Infrastructure Costs', 'count': 2}, {'cat': 'Other', 'count': 2}, {'cat': 'Facial AI Salary Prediction', 'count': 1}, {'cat': 'NVIDIA GTC Preview', 'count': 1}, {'cat': 'Observational Memory Method', 'count': 1}, {'cat': 'Microsoft LLM Backdoor Scanner', 'count': 1}, {'cat': 'North Korean AI Malware', 'count': 1}, {'cat': 'AI Chip Export Ban', 'count': 1}, {'cat': 'Alphabet Bond Sale', 'count': 1}, {'cat': 'LLM Reasoning Failures', 'count': 1}]
18:51:27 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping articles
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/dedupe_articles' from Langfuse
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/dedupe_articles': model=gpt-5-mini, reasoning_effort=low, system_len=1536, user_len=53
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: AI Agent Advances And Risks (17 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: AI Ethics And Regulation (17 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: Major AI Funding Rounds (15 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: AI Market Volatility (14 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: AI And Creative Industries (10 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: OpenAI Updates And Risks (8 items)
18:51:28 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Deduping cat: Enterprise AI Adoption (8 items)

================================================================================
⏱️  Total execution time: 163.11s
📊 Final result:
Categories and article counts:
cat
AI Agent Advances And Risks    19
AI And Creative Industries      9
AI Chatbot Safety               4
AI Chips Boom                   3
AI Ethics And Regulation       19
AI Infrastructure Costs         2
AI Market Volatility           11
Enterprise AI Adoption          9
Major AI Funding Rounds        11
OpenAI Updates And Risks        7
Other                           2
Samsung Galaxy S26              2
Workplace AI Effects            3
xAI Leadership Exodus           2

In [32]:
# User prompt to run workflow
# user_prompt = "Run step 8, draft sections"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("draft_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

18:51:50 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 8a: Selecting stories from 103 total
18:51:50 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | 32 must-include stories with rating > 8
18:51:50 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | 71 stories with rating <= 8
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.

▶ Starting Step 8: draft_sections

18:51:52 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Selected 68 diverse Tier 2 stories via MMR
18:51:52 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Total selected stories: 100 (target: 100)
18:51:52 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Drafting sections for 14 categories (including Other) from selected stories
18:51:52 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/write_section' from Langfuse
18:51:52 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/write_section': model=gpt-5-mini, reasoning_effort=high, system_len=1853, user_len=21
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Drafted 14 sections
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Reassigned 4 pruned stories to Other section
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Created newsletter_section_df with 97 stories across 14 categories
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 8b: Starting iterative critique-optimize loop for sections
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Moving 2 singleton categories to Other: ['xAI Leadership Exodus', 'Samsung Galaxy S26']
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/critique_section' from Langfuse
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/critique_section': model=gpt-5-mini, reasoning_effort=medium, system_len=1244, user_len=123
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/write_section' from Langfuse
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/write_section': model=gpt-5-mini, reasoning_effort=high, system_len=1853, user_len=21
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 8b: Iteration 1/2
18:56:47 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Critiquing 12 sections
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Market Volatility: Coherence=8.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Chips Boom: Coherence=9.0, Quality=8.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Other: Coherence=4.0, Quality=5.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Ethics And Regulation: Coherence=6.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Major AI Funding Rounds: Coherence=8.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Agent Advances And Risks: Coherence=8.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   OpenAI Updates And Risks: Coherence=8.0, Quality=7.5, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Enterprise AI Adoption: Coherence=6.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI And Creative Industries: Coherence=7.0, Quality=6.5, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Workplace AI Effects: Coherence=8.0, Quality=8.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Chatbot Safety: Coherence=8.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Infrastructure Costs: Coherence=7.0, Quality=7.0, Iterate=True
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Market Volatility: Coherence=8.0/10, Quality=7.0/10
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=0: Central, authoritative story (FT) that anchors the section. Headline is a bit long and can be tightened for clarity and punch.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: AI-powered tax tool triggers sell-off in US brokerages, hitting Charles Schwab and Morgan Stanley
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: AI-powered tax tool triggers sell-off at US brokerages, hits Charles Schwab and Morgan Stanley
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=101: Relevant market-moving piece but current headline is long, unfocused and mixes too many points. Needs a concise, active phrasing emphasizing the market impact.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Microsoft falls >16% after listing AI-vulnerable jobs; Atlassian plunges, Amazon announces 16,000 layoffs as tech plans ~$650B more AI spending
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Microsoft plunges 16% after disclosing AI-vulnerable jobs; Amazon announces 16,000 layoffs
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=104: Useful market-rebound follow-up, but headline is a run-on list. Tighten to convey the recovery succinctly.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Global equities rebound after AI-driven sell-off; Europe +0.69%, Iseq +1.08%, FTSE 100 +0.2%, Dow at intraday record
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Global equities rebound after AI-driven sell-off as markets recover
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=63: Authoritative source (Bloomberg) and directly addresses the narrative. Make the headline more direct and active.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: JPMorgan strategists say AI fears for software stocks are overblown
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: JPMorgan: AI fears for software stocks are overblown
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=73: Relevant expert view but current headline is long and cluttered with numbers. Focus on the main take-away about economic impact.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Apollo's Torsten Slok: AI could hurt software stocks but not the US economy; cites ~$660B 2026 capex and BofA's ~$1.2T by 2030
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Apollo's Torsten Slok: AI may dent software stocks but won't topple the US economy
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     DROP id=95: Lower-authority source focused on specific stock upside and earnings; adds little to the section's narrative about AI-driven market moves and is redundant with stronger analyst coverage here.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=90 to Other: Story about Peter Thiel's fund allocations is more about investor positioning than immediate AI-driven market volatility. Better fits a general investing/business roundup.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=80 to Enterprise AI Adoption: This piece focuses on firm-level ARR and profitability metrics tied to AI — it reads as an enterprise adoption/efficiency story rather than immediate market volatility. Move to Enterprise AI Adoption.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=61: Bloomberg source is authoritative and the theme (rising AI spending vs. slowing consumer activity) supports the section. Headline can be tightened and made more active.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: AI spending surges even as consumer activity slows
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: AI investment surges even as consumer activity slows
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=62: Interesting example of AI enabling new market products (attention markets). Headline currently promotional; tighten to emphasize the launch and scale ambition.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Polymarket partners with Kaito AI to launch 'attention markets' in March; aims for hundreds by year-end after processing $3B in January
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Polymarket to launch AI-driven 'attention markets' after processing $3B in January
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Chips Boom: Coherence=9.0/10, Quality=8.0/10
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=1: Headline is informative but wordy and includes approximate figures (~30%) and parenthetical currency that can be tightened. Use a concise, active-voice construction that highlights the AI datacenter demand driver and keeps numbers readable.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: TSMC January revenue jumps 37% to NT$401.3bn ($12.7bn), surpassing its ~30% full-year growth target as AI datacenter demand rises.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: TSMC January revenue rises 37% to NT$401.3bn ($12.7bn) as AI datacenter demand grows
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=24: Current headline is long and contains vague phrasing ('boosting trade leverage'). Tighten to a clear, active statement that emphasizes the scale and cause (chips and AI hardware) and removes jargon.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Taiwan January exports surge 70% year-on-year, the biggest monthly gain since 2010, driven by chip and AI hardware demand, boosting trade leverage.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Taiwan January exports jump 70% YoY, largest monthly gain since 2010 led by chips and AI hardware
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Other: Coherence=4.0/10, Quality=5.0/10
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=94 to AI Chips Boom: Cisco's new networking chip is a hardware/infrastructure story about data‑center AI networking — fits best under 'AI Chips Boom' rather than a general 'Other News' bucket.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=102 to Enterprise AI Adoption: Livedocs is an enterprise-focused AI product that automates data workflows; it belongs in 'Enterprise AI Adoption' where product adoption and tooling are tracked.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     DROP id=111: Low rating and this is an anniversary/historical piece (Deep Blue vs Kasparov) that doesn't fit the section's current news-forward industry focus.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     DROP id=112: Low rating and the story primarily concerns banking M&A sentiment; it doesn't add to the newsletter's AI product/industry narrative and can be removed.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=28 to AI Agent Advances And Risks: Coverage of xAI founder departures, Grok malfunctions and deepfakes is a company-level risk/agent story — best placed in 'AI Agent Advances And Risks'.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=76 to AI Agent Advances And Risks: Boston Dynamics' CEO transition is a robotics/agent leadership story that aligns with 'AI Agent Advances And Risks' rather than a general news section.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     DROP id=110: Rating is below threshold and the piece's focus on hotel pricing around an AI summit reads as ancillary color rather than essential coverage; drop to keep the section tight.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=39 to AI And Creative Industries: Samsung's Unpacked and Galaxy AI are consumer/creative AI product news — better suited to 'AI And Creative Industries' than a generic 'Other News' slot.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   AI Ethics And Regulation: Coherence=6.0/10, Quality=7.0/10
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=2: Highly relevant to risks around persistent personalization and data exposure; headline is wordy and could be tighter and more active.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Google's Gemini auto-summarizes Gmail; Meta AI embeds in Instagram, WhatsApp and Messenger, creating persistent personalized experiences.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Google's Gemini auto-summarizes Gmail; Meta adds persistent personalized AI across Instagram, WhatsApp and Messenger
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=49: Core regulatory risk story for this section; headline is descriptive but long — tighten and foreground watchdog/allegation.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: OpenAI's GPT-5.3-Codex flagged 'high' cybersecurity risk; watchdog alleges California SB 53 violations, potentially exposing OpenAI to millions in fines.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Watchdog flags GPT-5.3‑Codex as 'high' cybersecurity risk, alleges OpenAI violated California SB 53
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=88: Directly addresses technical risks of LLMs; headline should be shorter and emphasize the review's warning about high-stakes use.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Caltech/Stanford review finds pervasive LLM reasoning failures: hallucinations, logical errors and poor causal inference, threatening high-stakes applications.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Caltech–Stanford review finds pervasive LLM reasoning failures, warns against high‑stakes use
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=36: Relevant to user controls and open-source governance; headline is long and mixes two points — tighten and keep both facts but shorter.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Firefox 148 will let users disable individual AI features; Mozilla budgets $650M this year and holds $1.4B in reserves for open-source AI.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Firefox 148 lets users disable individual AI features; Mozilla budgets $650M for open‑source AI
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=65: Strong policy item on export controls — headline should be more concise and active.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Senators Elizabeth Warren and Jim Banks plan bipartisan legislation to ban sales of certain AI chips to China after Anthropic CEO meeting.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: Warren and Banks propose bipartisan bill to ban sales of certain AI chips to China
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     REWRITE id=74: High-risk safety story (medical device failures after ML update); headline should foreground the FDA findings and patient injuries concisely.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       Old: Malfunctions tied to Acclarent's TruDi Navigation System rose from 7 before its 2021 ML update to at least 100; FDA reports ten patient injuries.
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |       New: FDA: Malfunctions tied to Acclarent's TruDi rose after 2021 ML update; ten patient injuries reported
18:58:01 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |     MOVE id=13 to Other: India's content restrictions are a regulatory/policy story but don't fit the focused safety+rules narrative here; better placed in a general policy/other bucket.

================================================================================
⏱️  Total execution time: 674.09s
📊 Final result:
✅ Step 8 draft_sections completed successfully! Drafted 71 stories across 12 sections

In [33]:
newsletter_section_df = state.newsletter_section_df

newsletter_section_df

,cat,section_title,id,headline,rating,prune,links,sort_order
0,AI Market Volatility,AI Roils Global Markets,0,"AI tax tool sparks sell-off at US brokerages, ...",9.930010,False,[Financial Times](https://www.ft.com/content/1...,6
1,AI Market Volatility,AI Roils Global Markets,101,Microsoft plunges 16% after disclosing AI-vuln...,6.957862,False,[ABC Australia](https://www.abc.net.au/news/20...,6
2,AI Market Volatility,AI Roils Global Markets,104,Global equities recover after AI-driven sell-off,5.262447,False,[Irish Times](https://www.irishtimes.com/busin...,6
3,AI Market Volatility,AI Roils Global Markets,63,JPMorgan says AI fears for software stocks are...,4.502536,False,[Bloomberg](https://www.bloomberg.com/news/art...,6
4,AI And Creative Industries,"Generative AI: Media, Money, Mayhem",62,Polymarket to launch AI-driven 'attention mark...,5.726801,False,[Forbes](https://www.forbes.com/sites/aliciapa...,10
...,...,...,...,...,...,...,...,...
66,AI And Creative Industries,"Generative AI: Media, Money, Mayhem",15,"Meta adds AI-powered animated profile photos, ...",8.370423,False,[The Verge](https://www.theverge.com/tech/8764...,10
67,Workplace AI Effects,AI at Work: Gains and Pains,77,Sean Astin elected SAG-AFTRA president; union ...,5.772235,False,[Associated Press News](https://apnews.com/art...,9
68,AI Ethics And Regulation,AI Everywhere: Power and Peril,86,"Autodesk sues Google Feb. 6, alleging trademar...",4.940732,False,[PYMNTS](https://www.pymnts.com/legal/2026/goo...,1
69,OpenAI Updates And Risks,"OpenAI: Upgrades, Ads, Fallout",106,Anthropic trims Claude Super Bowl ad after Ope...,4.986570,False,[Android Headlines](https://www.androidheadlin...,4
70,AI And Creative Industries,"Generative AI: Media, Money, Mayhem",75,AI startups stage theatrical stunts to drive v...,4.173587,False,[The Guardian](https://www.theguardian.com/us-...,10

In [34]:
Markdown(state.display_newsletter().replace("$","\\\$"))

## Agentic AI: Rise and Risks
- Cadence launches ChipStack agent to automate chip IP design, claims up to 10x productivity - [The Register](https://www.theregister.com/2026/02/10/cadences_agentic_chip_design_tool/)
- Researchers find messaging AI agents can be hijacked to leak secrets via link previews - [The Register](https://www.theregister.com/2026/02/10/ai_agents_messaging_apps_data_leak/)
- Goldman says AI agent orchestration could shift \\$2 trillion in market value - [Fortune](https://fortune.com/2026/02/10/ai-agents-anthropic-openai-arent-killing-saas-salesforce-servicenow-microsoft-workday-cant-sleep-easy/)
- Mandiant says North Korean-linked group used AI deepfakes in Zoom to deliver malware; Chainalysis links \\$2B crypto theft - [Decrypt](https://decrypt.co/357601/google-warns-of-ai-powered-north-korean-malware-campaign-targeting-crypto-defi)
- Entire raises \\$60M seed to build open-source platform to trace and audit AI-produced code - [TechCrunch](https://techcrunch.com/2026/02/10/former-github-ceo-raises-record-60m-dev-tool-seed-round-at-300m-valuation/)
- Microsoft releases scanner to detect training-time backdoors in open-weight LLMs (requires model files) - [TechRadar](https://www.techradar.com/pro/as-adoption-grows-confidence-in-safeguards-must-rise-with-it-microsoft-reveals-new-tool-which-can-track-backdoors-in-llms-and-its-hoping-this-will-restore-trust-in-ai-across-the-world)
- Five of xAI's 12 founders leave amid layoffs, Grok malfunctions and deepfake incidents - [TechCrunch](https://techcrunch.com/2026/02/10/nearly-half-of-xais-founding-team-has-now-left-the-company/) [Ars Technica](https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/)
- Mastra open-source memory compresses agent histories and cuts token costs up to 10x - [VentureBeat](https://venturebeat.com/data/observational-memory-cuts-ai-agent-costs-10x-and-outscores-rag-on-long)
- StackBlitz CEO: company aims to have more AI agents than human employees, deployed across BI, coding, support, product and sales - [Business Insider](https://www.businessinsider.com/tech-ceo-ai-agents-outnumber-human-employees-eric-simons-stackblitz-2026-2)
## AI Everywhere: Power and Peril
- Google, Meta embed non-optional AI into Gmail, Search, Instagram and messaging - [The New York Times](https://www.nytimes.com/2026/02/10/technology/personaltech/ai-google-meta-opt-out.html)
- Watchdog: OpenAI's GPT-5.3-Codex poses 'high' cyber risk, lacks SB 53 safeguards - [Fortune](https://fortune.com/2026/02/10/openai-violated-californias-ai-safety-law-gpt-5-3-codex-ai-model-watchdog-claims/)
- Caltech/Stanford review finds pervasive LLM reasoning failures that threaten high-stakes use - [The Potential Surface](https://garymarcus.substack.com/p/breaking-llm-reasoning-continues)
- FDA links rise in malfunctions and patient injuries to Acclarent's TruDi after its 2021 ML update - [Free Republic](https://freerepublic.com/focus/f-chat/4366162/posts)
- Facial-analysis AI on 96,000 LinkedIn MBAs predicts rank and pay; researchers warn of discrimination - [The Register](https://www.theregister.com/2026/02/10/ai_face_analysis_mba_pay/)
- Mozilla adds per-feature AI controls in Firefox 148, commits ~\\$650M to open-source AI funding - [Fast Company](https://www.fastcompany.com/91490055/mozillas-new-ai-strategy-marks-a-return-to-its-rebel-alliance-roots)
- Autodesk sues Google Feb. 6, alleging trademark infringement over 'Flow' name for Google's Flow AI filmmaking tool; seeks compensatory and punitive damages - [PYMNTS](https://www.pymnts.com/legal/2026/google-faces-trademark-battle-over-ai-video-tools/)
## AI Business Reckoning
- NVIDIA GTC set for March 16–19 in San Jose; Jensen Huang to headline keynote - [The Register](https://www.theregister.com/2026/02/10/what_expect_this_years/)
- AI-driven selloff erases \\$285B from legacy software incumbents - [SiliconANGLE](https://siliconangle.com/2026/02/10/saaspocalypse-mispricing-markets-getting-ai-software-shakeout-wrong/)
- Only 3.3% of Microsoft 365 users pay for Copilot despite \\$37.5B AI investment - [TechRadar](https://www.techradar.com/pro/barely-any-microsoft-365-users-are-actually-paying-for-copilot-despite-microsoft-ceo-satya-nadella-claiming-it-is-a-true-daily-habit)
- FINQ launches SEC-approved AI-run ETFs after winning RIA license - [PYMNTS](https://www.pymnts.com/artificial-intelligence-2/2026/fund-manager-finq-lets-ai-run-us-etfs/)
- PwC cuts U.S. entry-level office options from 72 to 13 to prioritize AI upskilling - [Business Insider](https://www.businessinsider.com/ai-use-entry-level-workers-poses-risks-training-2026-2)
- PwC cuts U.S. entry-level office options from 72 to 13 to prioritize AI upskilling - [Business Insider](https://www.businessinsider.com/ai-use-entry-level-workers-poses-risks-training-2026-2)
- Microsoft appoints Charlie Bell to lead engineering quality amid rise in AI-written code - [Times of India](https://timesofindia.indiatimes.com/technology/tech-news/less-than-a-year-after-ceo-satya-nadella-said-30-of-microsofts-code-is-ai-written-company-appoints-an-engineering-quality-head/articleshow/128116076.cms)
- KPMG negotiates 14% lower 2025 audit fee citing expected AI-related savings - [Financial Times](https://www.ft.com/content/c891c47c-b21f-4e0f-84b3-b80c794eff3d)
- KPMG negotiates 14% lower 2025 audit fee citing expected AI-related savings - [Financial Times](https://www.ft.com/content/c891c47c-b21f-4e0f-84b3-b80c794eff3d)
## AI Funding Flood
- Runway raises \\$315M at \\$5.3B valuation, targets \\$300M ARR - [SiliconANGLE](https://siliconangle.com/2026/02/10/world-model-startup-runway-closes-315m-funding-round/)
- Databricks raises \\$7B at \\$134B valuation, cites \\$5.4B revenue run rate - [PYMNTS](https://www.pymnts.com/news/investment-tracker/2026/databricks-raises-7-billion-for-ai-agent-database/)
- Reco raises \\$30M Series B to scale AI cybersecurity - [Business Insider](https://www.businessinsider.com/reco-raises-30-m-series-b-ai-cybersecurity-demand-2026-2)
- MGX nears investment in Anthropic's \\$20B fundraise - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/mgx-said-to-near-investment-in-anthropic-s-20-billion-fundraise)
- Newo raises \\$25M Series A to scale AI voice and text agents after deploying 15,000+ agents - [SiliconANGLE](https://siliconangle.com/2026/02/10/newo-lands-25m-bring-production-ready-ai-receptionists-small-businesses/)
## OpenAI: Upgrades, Ads, Fallout
- OpenAI upgrades Responses API to support multi‑million‑token agents; Glean accuracy rises to 85% - [VentureBeat](https:\/\/venturebeat.com\/orchestration\/openai-upgrades-its-responses-api-to-support-agent-skills-and-a-complete)
- ChatGPT Deep Research adds full‑screen report viewer, TOC, sources, and export options for Plus/Pro - [The Verge](https:\/\/www.theverge.com\/ai-artificial-intelligence\/876775\/openai-deep-research-chatgpt-full-screen-report-viewer)
- Sam Altman-Jony Ive hardware startup hit by trademark dispute, on-device compute shortfall, always-listening bug and shipping delayed to February 2027 - [Gizmodo](https:\/\/gizmodo.com\/sam-altman-and-jony-ives-ai-gadget-just-hit-another-eyebrow-raising-roadblock-2000720067)
- OpenAI tests targeted ads in ChatGPT free and \\$8 Go tiers; under‑18s can't opt out - [NBC News](https:\/\/www.nbcnews.com\/tech\/internet\/openai-starts-testing-ads-chatgpt-rcna258242)
- OpenAI will retire GPT‑4o on Feb 13, prompting user backlash - [Futurism](https:\/\/futurism.com\/artificial-intelligence\/chatgpt-crashing-out-openai-retiring-gpt-4o)
- Anthropic cuts Super Bowl ad for Claude after OpenAI's Sam Altman called it 'dishonest'; OpenAI tests sponsored links in ChatGPT. - [Android Headlines](https:\/\/www.androidheadlines.com\/2026\/02\/anthropic-claude-super-bowl-ad-chatgpt-revision-openai.html)
- Anthropic trims Claude Super Bowl ad after OpenAI CEO Sam Altman calls it 'dishonest'; OpenAI tests sponsored links for U.S. free and Go ChatGPT users - [Android Headlines](https://www.androidheadlines.com/2026/02/anthropic-claude-super-bowl-ad-chatgpt-revision-openai.html)
## Taiwan Leads AI Chip Boom
- TSMC January revenue jumps 37% to NT\\$401.3bn on AI datacenter demand - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/tsmc-revenue-jumps-37-in-january-while-ai-spending-marches-on)
- Taiwan January exports surge 70% YoY, driven by chips and AI hardware - [Semafor](https://www.semafor.com/article/02/10/2026/taiwan-exports-surge-on-ai-demand)
- Warren and Banks push bipartisan bill to ban sales of select AI chips to China after meeting with Anthropic CEO Dario Amodei. - [Axios](https://www.axios.com/2026/02/10/anthropic-ceo-china-chip-ban)
## AI Roils Global Markets
- AI tax tool sparks sell-off at US brokerages, hits Charles Schwab and Morgan Stanley - [Financial Times](https://www.ft.com/content/1c63983f-5ff0-4b70-ad55-7e4334f59422)
- Anthropic plugins trigger selloff in India's largest IT firms - [Semafor](https://www.semafor.com/article/02/10/2026/new-ai-tools-spark-indian-it-selloff)
- Microsoft plunges 16% after disclosing AI-vulnerable jobs; Amazon to cut 16,000 workers - [ABC Australia](https://www.abc.net.au/news/2026-02-10/ai-disrupts-tech-boom-shares-drop/106323844)
- Nebius to buy AI agent search startup Tavily for \\$275 million - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/nebius-agrees-to-buy-ai-agent-search-company-tavily-for-275-million)
- Global equities recover after AI-driven sell-off - [Irish Times](https://www.irishtimes.com/business/markets/2026/02/09/big-tech-firms-claw-back-losses-on-fear-of-ai-bubble/)
- JPMorgan says AI fears for software stocks are overblown - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/jpmorgan-strategists-say-ai-fears-on-software-stocks-overblown)
## AI Safety & Trust Roundup
- Study: GPT-4o and Llama 3 match search on medical tasks but only 33% correct condition, 45% correct action - [Citizen Digital](https://www.citizen.digital/news/ai-chatbots-give-bad-health-advice-research-finds-n377187)
- Study: AI agents often misinterpret user intent; researchers urge visible, correctable interpretations - [Hacker Noon](https://hackernoon.com/how-often-does-the-agent-misinterpret-the-users-intent-and-is-it-correctable)
- WSL and women's clubs monitor X's AI tool Grok after sexualized images; Ofcom, the EU and Signify open detection efforts and a DSA probe. - [Yahoo](https://sports.yahoo.com/articles/wsl-women-clubs-monitoring-x-183106660.html)
- WSL and women's clubs monitor X's AI tool Grok after sexualized image generation; regulators and EU open detection efforts and a DSA probe. - [Yahoo](https://sports.yahoo.com/articles/wsl-women-clubs-monitoring-x-183106660.html)
- HHS AI nutrition assistant recommended inserting food into rectum, revealing guardrail failures - [Memeorandum](https://www.memeorandum.com/260210/p128#a260210p128)
## AI Infrastructure Race
- Alphabet issues 100‑year sterling bond, upsizes \\$20B sale to fund up to \\$185B in AI capex - [Financial Times](https://www.ft.com/content/3260bc45-e09e-45a7-ae30-e55effbaf29b) [CNBC](https://www.cnbc.com/2026/02/09/alphabet-highlights-new-ai-related-risks-in-tapping-debt-market.html)
- Gulf states build sovereign AI datacenters amid \\$600B AI spending pledges from US tech firms - [The Guardian](https://www.theguardian.com/technology/2026/feb/09/us-tech-ai-companies-gulf-states)
- Orbital AI datacenters could be viable at \\$250–\\$500/kg; SpaceX launch costs (~\\$600/kg) keep ground options cheaper - [Next Big Future](https://www.nextbigfuture.com/2026/02/spacex-space-ai-costs-are-already-near-ground-ai-data-centers.html)
- Cisco unveils AI networking chip to take on Broadcom and Nvidia in data-center networking. - [Reuters](https://www.reuters.com/business/media-telecom/cisco-unveils-new-ai-networking-chip-taking-broadcom-and-nvidia-2026-02-10/)
## AI at Work: Gains and Pains
- Study: AI boosts productivity but lengthens workdays, lowers output quality and raises burnout risk - [CNET](https://www.cnet.com/tech/services-and-software/using-ai-at-work-may-actually-make-your-days-longer-and-more-unpleasant-study-finds/)
- Facial-analysis AI on 96,000 LinkedIn MBAs predicts rank and pay; researchers warn of discrimination - [The Register](https://www.theregister.com/2026/02/10/ai_face_analysis_mba_pay/)
- Sean Astin elected SAG-AFTRA president; union vows to defend 2023 AI protections, seek better streaming residuals and open three-year contract talks. - [Associated Press News](https:\/\/apnews.com\/article\/sean-astin-sag-negotiations-a3074d365dea366b0b41dbb236ed6f8d)
- Sean Astin elected SAG-AFTRA president; union vows to defend 2023 AI protections, pursue better streaming residuals, and open three-year contract talks - [Associated Press News](https://apnews.com/article/sean-astin-sag-negotiations-a3074d365dea366b0b41dbb236ed6f8d)
- AI automates farm tasks - satellite imagery, irrigation and livestock monitoring - shifting risk to farmers while boosting uneven productivity; food demand to rise 35-56% by 2050. - [The Conversation](https://theconversation.com/ai-isnt-likely-to-wipe-out-all-farming-jobs-but-it-is-changing-who-bears-the-risks-275227)
## Generative AI: Media, Money, Mayhem
- Meta adds AI-powered animated profile photos, Stories restyling and animated text backgrounds to Facebook - [The Verge](https://www.theverge.com/tech/876480/meta-facebook-animate-profile-picture-restyle-ai)
- Czech Olympic ice dancers used AI-generated music with near-verbatim 1990s lyrics, prompting copyright and licensing concerns. - [TechCrunch](https://techcrunch.com/2026/02/10/olympics-czech-ice-dancers-duo-ai-music/)
- Polymarket to launch AI-driven 'attention markets' after processing \\$3B in January - [Forbes](https://www.forbes.com/sites/aliciapark/2026/02/10/polymarket-to-offer-attention-markets-in-partnership-with-kaito-ai/)
- Researchers find AI-generated social posts proliferate with predictable low-quality patterns, amplified by platform algorithms and monetization incentives. - [ABC Australia](https://www.abc.net.au/news/2026-02-10/ai-generated-text-predictive-models-formulaic-social-media/106313944)
- AI startups stage theatrical stunts to drive viral leads and sales - [The Guardian](https://www.theguardian.com/us-news/2026/feb/10/ai-business-startups-stunts)
- Short film 'That's AI!' shows labeling content as AI cuts viewers' enjoyment and trust, pressuring disclosure and provenance tools. - [Neatorama](https://www.neatorama.com/2026/02/09/iThats-AIi-The-Fastest-Way-to-Destroy-the-Joy/)
## AI Power Moves
- India announces measures to restrict AI-generated social media content, tightening online content rules. - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/india-cracks-down-on-ai-generated-content-on-social-media)
- Eighth Circuit denies preliminary injunction in challenge to Minnesota deepfake election law, citing standing and delay issues. - [Reason](https://reason.com/volokh/2026/02/09/no-preliminary-injunction-in-challenge-to-minnesota-election-deepfake-law-but-challenge-goes-on/)
- State judge rules Adelphi student Orion Newby did not use AI to cheat, reverses sanctions and orders his record expunged, prompting reassessment of AI-detection tools. - [CBS News](https://www.cbsnews.com/newyork/news/orion-newby-adelphi-university-ai-plagiarism-accusations/)
- Judge clears Adelphi student of AI cheating, rescinds sanctions and orders record expunged, questioning campus AI-detection reliance. - [CBS News](https://www.cbsnews.com/newyork/news/orion-newby-adelphi-university-ai-plagiarism-accusations/)
- AI Impact Summit Feb. 19–20 to draw 35,000; Pichai, Huang and Hassabis to attend - [Business Standard](https://www.business-standard.com/industry/news/30-lakh-a-night-luxury-hotel-rates-soar-as-delhi-awaits-global-ai-elite-126020901420_1.html)

In [35]:
# User prompt to run workflow
# user_prompt = "Run step 9, finalize newsletter"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("finalize_newsletter")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

19:03:04 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9: write title
19:03:04 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Compiled 71 items into markdown input

▶ Starting Step 9: finalize_newsletter

19:03:05 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/generate_newsletter_title' from Langfuse
19:03:05 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/generate_newsletter_title': model=gpt-5-mini, reasoning_effort=high, system_len=1080, user_len=224
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
19:03:49 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Generated title: Agentic AI Surges as Security Gaps Emerge; Markets Reprice, Chips Boom
19:03:49 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9b: Starting critic-optimizer loop
19:03:51 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/critique_newsletter' from Langfuse
19:03:51 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/critique_newsletter': model=gpt-5-mini, reasoning_effort=medium, system_len=2758, user_len=647
19:03:51 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Retrieved prompt 'newsagent/improve_newsletter' from Langfuse
19:03:51 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Parsed prompt 'newsagent/improve_newsletter': model=gpt-5-mini, reasoning_effort=high, system_len=1318, user_len=192
19:03:51 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9b: Iteration 1/2 - Running critique
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
19:05:10 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Iteration 1: Overall score = 6.3/10
19:05:10 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Title: 9.0, Structure: 5.5, Section: 6.0, Headline: 6.0
19:05:10 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Iteration 1: Should iterate = True
19:05:10 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9b: Iteration 1 - Running optimizer to improve draft
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
19:14:04 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Iteration 1: Optimizer completed, draft updated
19:14:04 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9b: Iteration 2/2 - Running critique
WARNING:langfuse:OTEL_SDK_DISABLED is set. Langfuse tracing will be disabled and no traces will appear in the UI.
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Iteration 2: Overall score = 8.3/10
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO |   Title: 9.0, Structure: 8.5, Section: 8.0, Headline: 8.0
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Iteration 2: Should iterate = False
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | ✅ Quality threshold 8.0 met! Score: 8.3/10
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9b: Critic-optimizer loop complete after 2 iteration(s). Final score: 8.3/10
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9c complete: Final newsletter 1169 words
19:15:43 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | Step 9d: Validating and sending newsletter
19:15:44 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | ✅ Sent newsletter email with subject: AI News for February 10, 2026 - Agentic AI Surges as Security Gaps Emerge; Markets Reprice, Chips Boom
19:15:44 | NewsletterAgent.test_newsletter_20260210180738268248 | INFO | ✅ Saved newsletter to database for session test_newsletter_20260210180738268248

================================================================================
⏱️  Total execution time: 759.50s
📊 Final result:
🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 8.3/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.

In [36]:
display(Markdown(state.final_newsletter.replace("$", "\\\$")))

# Agentic AI Surges as Security Gaps Emerge; Markets Reprice, Chips Boom

## Agentic AI — Agents, Apps & Audits
- Cadence launches ChipStack agent to automate chip IP design; claims up to 10x productivity - [The Register](https://www.theregister.com/2026/02/10/cadences_agentic_chip_design_tool/)
- Entire raises \\$60M seed for an open-source platform to trace and audit AI-produced code - [TechCrunch](https://techcrunch.com/2026/02/10/former-github-ceo-raises-record-60m-dev-tool-seed-round-at-300m-valuation/)
- Mastra open-source memory compresses agent histories and cuts token costs up to 10x - [VentureBeat](https://venturebeat.com/data/observational-memory-cuts-ai-agent-costs-10x-and-outscores-rag-on-long)
- StackBlitz CEO: company aims to deploy more AI agents than human employees across BI, coding, support and sales - [Business Insider](https://www.businessinsider.com/tech-ceo-ai-agents-outnumber-human-employees-eric-simons-stackblitz-2026-2)
- Goldman says AI agent orchestration could shift \\$2 trillion in market value - [Fortune](https://fortune.com/2026/02/10/ai-agents-anthropic-openai-arent-killing-saas-salesforce-servicenow-microsoft-workday-cant-sleep-easy/)

## Agentic AI — Security & Incidents
- Researchers find messaging AI agents can be hijacked to leak secrets via link previews - [The Register](https://www.theregister.com/2026/02/10/ai_agents_messaging_apps_data_leak/)
- Mandiant: North Korea-linked group used AI deepfakes in Zoom to deliver malware; Chainalysis links \\$2B crypto theft - [Decrypt](https://decrypt.co/357601/google-warns-of-ai-powered-north-korean-malware-campaign-targeting-crypto-defi)
- Microsoft releases scanner to detect training-time backdoors in open-weight LLMs - [TechRadar](https://www.techradar.com/pro/as-adoption-grows-confidence-in-safeguards-must-rise-with-it-microsoft-reveals-new-tool-which-can-track-backdoors-in-llms-and-its-hoping-this-will-restore-trust-in-ai-across-the-world)
- Five of xAI's 12 founders leave amid layoffs, Grok malfunctions and deepfake incidents - [TechCrunch](https://techcrunch.com/2026/02/10/nearly-half-of-xais-founding-team-has-now-left-the-company/) [Ars Technica](https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/)

## AI Safety & Trust — Failures, Bias & Guardrails
- Watchdog: OpenAI's GPT-5.3-Codex poses 'high' cyber risk, lacks SB 53 safeguards - [Fortune](https://fortune.com/2026/02/10/openai-violated-californias-ai-safety-law-gpt-5-3-codex-ai-model-watchdog-claims/)
- Caltech/Stanford review finds pervasive LLM reasoning failures that threaten high-stakes use - [The Potential Surface](https://garymarcus.substack.com/p/breaking-llm-reasoning-continues)
- Study: GPT-4o and Llama 3 match search on medical tasks but show low correctness on condition (33%) and action (45%) - [Citizen Digital](https://www.citizen.digital/news/ai-chatbots-give-bad-health-advice-research-finds-n377187)
- Study: AI agents often misinterpret user intent; researchers urge visible, correctable interpretations - [Hacker Noon](https://hackernoon.com/how-often-does-the-agent-misinterpret-the-users-intent-and-is-it-correctable)
- Facial-analysis AI on 96,000 LinkedIn MBAs predicts rank and pay; researchers warn of discrimination - [The Register](https://www.theregister.com/2026/02/10/ai_face_analysis_mba_pay/)
- WSL and women's clubs monitor X's AI tool Grok after sexualized images; regulators open detection efforts and a DSA probe - [Yahoo](https://sports.yahoo.com/articles/wsl-women-clubs-monitoring-x-183106660.html)

## AI Everywhere — Platforms & Consumer Moves
- Google, Meta embed non-optional AI into Gmail, Search, Instagram and messaging - [The New York Times](https://www.nytimes.com/2026/02/10/technology/personaltech/ai-google-meta-opt-out.html)
- Mozilla adds per-feature AI controls in Firefox 148 and commits ~\\$650M to open-source AI funding - [Fast Company](https://www.fastcompany.com/91490055/mozillas-new-ai-strategy-marks-a-return-to-its-rebel-alliance-roots)
- Autodesk sues Google over 'Flow' name for Google's Flow AI filmmaking tool; seeks damages - [PYMNTS](https://www.pymnts.com/legal/2026/google-faces-trademark-battle-over-ai-video-tools/)

## Markets & Business — Repricing & Reckoning
- AI-driven selloff erases \\$285B from legacy software incumbents - [SiliconANGLE](https://siliconangle.com/2026/02/10/saaspocalypse-mispricing-markets-getting-ai-software-shakeout-wrong/)
- AI tax tool sparks sell-off at US brokerages, hits Charles Schwab and Morgan Stanley - [Financial Times](https://www.ft.com/content/1c63983f-5ff0-4b70-ad55-7e4334f59422)
- Anthropic plugins trigger selloff in India's largest IT firms - [Semafor](https://www.semafor.com/article/02/10/2026/new-ai-tools-spark-indian-it-selloff)
- Microsoft plunges 16% after disclosing AI-vulnerable jobs; Amazon to cut 16,000 workers - [ABC Australia](https://www.abc.net.au/news/2026-02-10/ai-disrupts-tech-boom-shares-drop/106323844)
- Global equities recover after AI-driven sell-off - [Irish Times](https://www.irishtimes.com/business/markets/2026/02/09/big-tech-firms-claw-back-losses-on-fear-of-ai-bubble/)
- JPMorgan says AI fears for software stocks are overblown - [Bloomberg](https://www.bloomberg.com/news/articles/2026/02/10/jpmorgan-strategists-say-ai-fears-on-software-stocks-overblown)
- Only 3.3% of Microsoft 365 users pay for Copilot despite \\$37.5B AI investment - [TechRadar](https://www.techradar.com/pro/barely-any-microsoft-365-users-are-actually-paying-for-copilot-despite-microsoft-ceo-satya-nadella-claiming-it-is-a-true-daily-habit)

## AI Funding Flood
- Runway raises \\$315M at \\$5.3B valuation, targets \\$300M ARR - [SiliconANGLE](https://siliconangle.com/2026/02/10/world-model-startup-runway-closes-315m-funding-round/)
- Databricks raises \\$7B at \\$134B valuation, cites \\$5.4B revenue run rate - [PYMNTS](https://www.pymnts.com/news/investment-tracker/2026/databricks-raises-7-billion-for-ai-agent-database/)
- Reco raises \\$30M Series B to scale AI cybersecurity - [Business Insider](https://www.businessinsider.com/reco-raises-30-m-series-b-ai-cybersecurity-demand-2026-2)
- MGX nears investment in Anthropic's \\$20B fundraise - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/mgx-said-to-near-investment-in-anthropic-s-20-billion-fundraise)
- Newo raises \\$25M Series A to scale AI voice and text agents after deploying 15,000+ agents - [SiliconANGLE](https://siliconangle.com/2026/02/10/newo-lands-25m-bring-production-ready-ai-receptionists-small-businesses/)
- FINQ launches SEC-approved AI-run ETFs after winning RIA license - [PYMNTS](https://www.pymnts.com/artificial-intelligence-2/2026/fund-manager-finq-lets-ai-run-us-etfs/)

## OpenAI — Upgrades, Ads & Fallout
- OpenAI upgrades Responses API to support multi‑million‑token agents; Glean accuracy rises to 85% - [VentureBeat](https:\/\/venturebeat.com\/orchestration\/openai-upgrades-its-responses-api-to-support-agent-skills-and-a-complete)
- ChatGPT Deep Research adds full‑screen report viewer, TOC, sources, and export options for Plus/Pro - [The Verge](https:\/\/www.theverge.com\/ai-artificial-intelligence\/876775\/openai-deep-research-chatgpt-full-screen-report-viewer)
- OpenAI tests targeted ads in ChatGPT free and \\$8 Go tiers; under‑18s can't opt out - [NBC News](https:\/\/www.nbcnews.com\/tech\/internet\/openai-starts-testing-ads-chatgpt-rcna258242)
- OpenAI will retire GPT‑4o on Feb 13 - [Futurism](https:\/\/futurism.com\/artificial-intelligence\/chatgpt-crashing-out-openai-retiring-gpt-4o)
- Anthropic trims Claude Super Bowl ad after Sam Altman called it 'dishonest'; OpenAI tests sponsored links - [Android Headlines](https://www.androidheadlines.com/2026/02/anthropic-claude-super-bowl-ad-chatgpt-revision-openai.html)
- Sam Altman–Jony Ive hardware startup faces trademark dispute, compute shortfall and shipping delays - [Gizmodo](https:\/\/gizmodo.com\/sam-altman-and-jony-ives-ai-gadget-just-hit-another-eyebrow-raising-roadblock-2000720067)

## Taiwan Leads AI Chip Boom
- TSMC January revenue jumps 37% to NT\\$401.3bn on AI datacenter demand - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/tsmc-revenue-jumps-37-in-january-while-ai-spending-marches-on)
- Taiwan January exports surge 70% YoY, driven by chips and AI hardware - [Semafor](https://www.semafor.com/article/02/10/2026/taiwan-exports-surge-on-ai-demand)
- Warren and Banks push bipartisan bill to ban sales of select AI chips to China after meeting with Anthropic CEO Dario Amodei - [Axios](https://www.axios.com/2026/02/10/anthropic-ceo-china-chip-ban)

## AI Infrastructure Race — Capex & Cloud
- Alphabet issues 100‑year sterling bond, upsizes \\$20B sale to fund up to \\$185B in AI capex - [Financial Times](https://www.ft.com/content/3260bc45-e09e-45a7-ae30-e55effbaf29b) [CNBC](https://www.cnbc.com/2026/02/09/alphabet-highlights-new-ai-related-risks-in-tapping-debt-market.html)
- Gulf states build sovereign AI datacenters amid \\$600B AI spending pledges from US tech firms - [The Guardian](https://www.theguardian.com/technology/2026/feb/09/us-tech-ai-companies-gulf-states)
- Cisco unveils AI networking chip to take on Broadcom and Nvidia in data-center networking - [Reuters](https://www.reuters.com/business/media-telecom/cisco-unveils-new-ai-networking-chip-taking-broadcom-and-nvidia-2026-02-10/)

## AI at Work — Gains, Pains & Policy
- Study: AI boosts productivity but lengthens workdays, lowers output quality and raises burnout risk - [CNET](https://www.cnet.com/tech/services-and-software/using-ai-at-work-may-actually-make-your-days-longer-and-more-unpleasant-study-finds/)
- PwC cuts U.S. entry-level office options from 72 to 13 to prioritize AI upskilling - [Business Insider](https://www.businessinsider.com/ai-use-entry-level-workers-poses-risks-training-2026-2)
- Microsoft appoints Charlie Bell to lead engineering quality amid rise in AI-written code - [Times of India](https://timesofindia.indiatimes.com/technology/tech-news/less-than-a-year-after-ceo-satya-nadella-said-30-of-microsofts-code-is-ai-written-company-appoints-an-engineering-quality-head/articleshow/128116076.cms)
- Sean Astin elected SAG-AFTRA president; union vows to defend 2023 AI protections and open three-year contract talks - [Associated Press News](https://apnews.com/article/sean-astin-sag-negotiations-a3074d365dea366b0b41dbb236ed6f8d)
- AI automates farm tasks—satellite imagery, irrigation and livestock monitoring—shifting risk to farmers while boosting uneven productivity - [The Conversation](https://theconversation.com/ai-isnt-likely-to-wipe-out-all-farming-jobs-but-it-is-changing-who-bears-the-risks-275227)

## Generative AI — Media, Money & Mayhem
- Meta adds AI-powered animated profile photos, Stories restyling and animated text backgrounds to Facebook - [The Verge](https://www.theverge.com/tech/876480/meta-facebook-animate-profile-picture-restyle-ai)
- Czech Olympic ice dancers used AI-generated music with near-verbatim 1990s lyrics, prompting copyright and licensing concerns - [TechCrunch](https://techcrunch.com/2026/02/10/olympics-czech-ice-dancers-duo-ai-music/)
- Polymarket to launch AI-driven 'attention markets' after processing \\$3B in January - [Forbes](https://www.forbes.com/sites/aliciapark/2026/02/10/polymarket-to-offer-attention-markets-in-partnership-with-kaito-ai/)
- Researchers find AI-generated social posts proliferate with predictable low-quality patterns, amplified by platform algorithms - [ABC Australia](https://www.abc.net.au/news/2026-02-10/ai-generated-text-predictive-models-formulaic-social-media/106313944)
- AI startups stage theatrical stunts to drive viral leads and sales - [The Guardian](https://www.theguardian.com/us-news/2026/feb/10/ai-business-startups-stunts)
- Short film 'That's AI!' finds labeling content as AI cuts viewers' enjoyment and trust, pressuring disclosure and provenance tools - [Neatorama](https://www.neatorama.com/2026/02/09/iThats-AIi-The-Fastest-Way-to-Destroy-the-Joy/)

## AI Power Moves — Laws, Courts & Policy
- India announces measures to restrict AI-generated social media content, tightening online content rules - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/india-cracks-down-on-ai-generated-content-on-social-media)
- Eighth Circuit denies preliminary injunction in challenge to Minnesota deepfake election law - [Reason](https://reason.com/volokh/2026/02/09/no-preliminary-injunction-in-challenge-to-minnesota-election-deepfake-law-but-challenge-goes-on/)
- Judge clears Adelphi student of AI cheating, rescinds sanctions and orders record expunged, questioning campus AI-detection reliance - [CBS News](https://www.cbsnews.com/newyork/news/orion-newby-adelphi-university-ai-plagiarism-accusations/)
- AI Impact Summit Feb. 19–20 to draw 35,000; Pichai, Huang and Hassabis to attend - [Business Standard](https://www.business-standard.com/industry/news/30-lakh-a-night-luxury-hotel-rates-soar-as-delhi-awaits-global-ai-elite-126020901420_1.html)

## Other News
- Nebius to buy AI agent search startup Tavily for \\$275 million - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-10/nebius-agrees-to-buy-ai-agent-search-company-tavily-for-275-million)
- FDA links rise in malfunctions and patient injuries to Acclarent's TruDi after its 2021 ML update - [Free Republic](https://freerepublic.com/focus/f-chat/4366162/posts)
- HHS AI nutrition assistant recommended inserting food into rectum, revealing guardrail failures - [Memeorandum](https://www.memeorandum.com/260210/p128#a260210p128)
- Orbital AI datacenters could be viable at \\$250–\\$500/kg; SpaceX launch costs (~\\$600/kg) keep ground options cheaper - [Next Big Future](https://www.nextbigfuture.com/2026/02/spacex-space-ai-costs-are-already-near-ground-ai-data-centers.html)
- KPMG negotiates 14% lower 2025 audit fee citing expected AI-related savings - [Financial Times](https://www.ft.com/content/c891c47c-b21f-4e0f-84b3-b80c794eff3d)

In [37]:
print(state.get_workflow_status_report())

WORKFLOW STATUS
Progress: 100.0% (9/9 complete)
Status Summary: 9 complete, 0 started, 0 failed, 0 not started
Status: All steps complete or started

Step Details:
  Step 0: Gather URLs: complete
    Status: ✅ Step 1 gather_urls completed successfully! Gathered 877 articles from 17 sources.

📊 Articles stored in persistent state: 739
  Step 1: Filter URLs: complete
    Status: ✅ Step 2 filter_urls completed successfully! Removed 476 duplicate URLs, classified 263 new articles, found 125 AI-related.
  Step 2: Download Articles: complete
    Status: ✅ Step 3 download_articles completed successfully! Total articles: 263; AI-related articles: 121; HTML files: 105; Text files: 105
  Step 3: Extract Summaries: complete
    Status: ✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 121/121 articles.
💾 Summaries stored in headline DataFrame.
  Step 4: Rate Articles: complete
    Status: ✅ Step 5 rate_articles completed successfully! Rated 119 articles with average rating 6.5/10.
⭐ High quality articles (≥7.0): 48
💾 Ratings stored in persistent state.
  Step 5: Cluster By Topic: complete
    Status: ✅ Step 6 cluster_topics completed successfully! Organized 119 articles into topic clusters.
  Step 6: Select Sections: complete
    Status: Categories and article counts:
cat
AI Agent Advances And Risks    19
AI And Creative Industries      9
AI Chatbot Safety               4
AI Chips Boom                   3
AI Ethics And Regulation       19
AI Infrastructure Costs         2
AI Market Volatility           11
Enterprise AI Adoption          9
Major AI Funding Rounds        11
OpenAI Updates And Risks        7
Other                           2
Samsung Galaxy S26              2
Workplace AI Effects            3
xAI Leadership Exodus           2
  Step 7: Draft Sections: complete
    Status: ✅ Step 8 draft_sections completed successfully! Drafted 71 stories across 12 sections
  Step 8: Finalize Newsletter: complete
    Status: 🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 8.3/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.

In [38]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 100.0% (9/9 complete)
🎉 All steps complete!

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 877 articles from 17 sources.

📊 Articles stored in persistent state: 739
  ✅ Step 1: Filter URLs            | complete
      📝 Status: ✅ Step 2 filter_urls completed successfully! Removed 476 duplicate URLs, classified 263 new articles, found 125 AI-related.
  ✅ Step 2: Download Articles      | complete
      📝 Status: ✅ Step 3 download_articles completed successfully! Total articles: 263; AI-related articles: 121; HTML files: 105; Text files: 105
  ✅ Step 3: Extract Summaries      | complete
      📝 Status: ✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 121/121 articles.
💾 Summaries stored in headline DataFrame.
  ✅ Step 4: Rate Articles          | complete
      📝 Status: ✅ Step 5 rate_articles completed successfully! Rated 119 articles with average rating 6.5/10.
⭐ High quality articles (≥7.0): 48
💾 Ratings stored in persistent state.
  ✅ Step 5: Cluster By Topic       | complete
      📝 Status: ✅ Step 6 cluster_topics completed successfully! Organized 119 articles into topic clusters.
  ✅ Step 6: Select Sections        | complete
      📝 Status: Categories and article counts:
cat
AI Agent Advances And Risks    19
AI And Creative Industries      9
AI Chatbot Safety               4
AI Chips Boom                   3
AI Ethics And Regulation       19
AI Infrastructure Costs         2
AI Market Volatility           11
Enterprise AI Adoption          9
Major AI Funding Rounds        11
OpenAI Updates And Risks        7
Other                           2
Samsung Galaxy S26              2
Workplace AI Effects            3
xAI Leadership Exodus           2
  ✅ Step 7: Draft Sections         | complete
      📝 Status: ✅ Step 8 draft_sections completed successfully! Drafted 71 stories across 12 sections
  ✅ Step 8: Finalize Newsletter    | complete
      📝 Status: 🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 8.3/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.
============================================================