# Run Agent
- Implement a workflow to write a daily AI newsletter
- see README.md for details

In [1]:
import os
import yaml
import dotenv
import logging
import json
import yaml
from datetime import datetime
import time
import random
import glob
import pickle
import sqlite3

from pathlib import Path

import asyncio
import nest_asyncio

import pydantic
from pydantic import BaseModel, Field, RootModel
from typing import Dict, TypedDict, Type, List, Optional, Any, Iterable, Text
from dataclasses import dataclass, field
from enum import Enum

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import hdbscan

import openai
from openai import AsyncOpenAI

import agents
from agents.exceptions import InputGuardrailTripwireTriggered
from agents import (Agent, Runner, Tool, OpenAIResponsesModel, 
                    ModelSettings, FunctionTool, InputGuardrail, GuardrailFunctionOutput,
                    SQLiteSession, set_default_openai_api, set_default_openai_client
                   )


import tenacity
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

from IPython.display import HTML, Image, Markdown, display

from log_handler import SQLiteLogHandler, setup_sqlite_logging, sanitize_error_for_logging
from config import LOGDB
from llm import LLMagent, LangfuseClient  # methods to apply prompts async to large batches
from db import Url, AgentState

from fetch import Fetcher # fetch news urls
from newsletter_state import NewsletterAgentState, StepStatus
from news_agent import NewsletterAgent

In [2]:
print(f"OpenAI:            {openai.__version__}")
print(f"OpenAI Agents SDK  {agents.__version__}")
print(f"Pydantic           {pydantic.__version__}")

OpenAI:            2.21.0
OpenAI Agents SDK  0.9.0
Pydantic           2.12.5

In [3]:
dotenv.load_dotenv()

# to run async in jupyter notebook
nest_asyncio.apply()

# turn off open telemetry (langfuse)
os.environ["OTEL_SDK_DISABLED"] = "true"

# verbose OpenAI console logging if something doesn't work
# logging.basicConfig(level=logging.DEBUG)
# openai_logger = logging.getLogger("openai")
# openai_logger.setLevel(logging.DEBUG)

In [4]:
# modules create a default logger, or we can pass this logger
debuglevel = logging.DEBUG

def setup_logging(session_id: str = "default", db_path: str = "agent_logs.db") -> logging.Logger:
    """Set up logging to console and SQLite database."""

    # Create logger
    logging.basicConfig()
    logger = logging.getLogger(f"NewsletterAgent.{session_id}")
    logger.setLevel(debuglevel)

    # Clear any existing handlers
    logger.handlers.clear()

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(debuglevel)
    console_formatter = logging.Formatter(
        '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
        datefmt='%H:%M:%S'
    )
    console_handler.setFormatter(console_formatter)

    # SQLite handler
    sqlite_handler = SQLiteLogHandler(db_path)
    sqlite_handler.setLevel(debuglevel)
    sqlite_formatter = logging.Formatter('%(message)s')
    sqlite_handler.setFormatter(sqlite_formatter)

    # Add handlers to logger
    logger.addHandler(console_handler)
    logger.addHandler(sqlite_handler)

    # Prevent propagation to root logger
    logger.propagate = False

    return logger

logger = setup_logging("newsletter_agent", "test_logs.db")

# Log some test messages
logger.debug("Test debug message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.info("Test info message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.warning("Test warning message", extra={
    'step_name': 'test_step',
    'agent_session': 'demo_session'
})

logger.error("Test error message", extra={
    'step_name': 'error_step',
    'agent_session': 'demo_session'
})

sanitize_error_for_logging("log with some bad stuff for the filter: sk-proj-123456789012345678901234567890123456789012345678")

23:09:52 | NewsletterAgent.newsletter_agent | DEBUG | Test debug message
23:09:52 | NewsletterAgent.newsletter_agent | INFO | Test info message
23:09:52 | NewsletterAgent.newsletter_agent | WARNING | Test warning message
23:09:52 | NewsletterAgent.newsletter_agent | ERROR | Test error message

'log with some bad stuff for the filter: [API_KEY_REDACTED]'

In [5]:
# look up recent sessions
conn = sqlite3.connect("newsletter_agent.db")
AgentState.list_sessions(conn, n_records=10)

['test_newsletter_20260215223006688628',
 'test_newsletter_20260215215341994191',
 'test_newsletter_20260215073155703123',
 'test_newsletter_20260215072749475436',
 'test_newsletter_20260214083433211276',
 'test_newsletter_20260214082909417070',
 'test_newsletter_20260214081211439717',
 'test_newsletter_20260214080845501239',
 'test_newsletter_20260214080053576719',
 'test_newsletter_20260214074501502362']

In [6]:
z = AgentState.get_latest_by_session(conn, "test_newsletter_20260122183737514938")
z.step_name

'filter_urls'

In [7]:
for y in z.get_all_by_session(conn, "test_newsletter_20260122183737514938"):
    print(y.session_id, y.step_name, y.updated_at)

test_newsletter_20260122183737514938 initialize 2026-01-22 18:37:37.544042
test_newsletter_20260122183737514938 gather_urls 2026-01-22 18:40:01.118660
test_newsletter_20260122183737514938 check_workflow_status 2026-01-22 18:40:02.909579
test_newsletter_20260122183737514938 filter_urls 2026-01-22 18:41:11.169324

# Run Agent Worfklow

In [8]:
print("🚀 Creating NewsletterAgent...")
do_download=False
reprocess_since=None
reprocess_since='2026-02-14 07:32:00'
try:
    # set up state
    session_id = 'test_newsletter_20260122183737514938'
    step_name = 'filter_urls'
    del session_id
except Exception as e:
    print(e)

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable not set")

# Set up OpenAI client for the agents SDK
set_default_openai_client(AsyncOpenAI(api_key=api_key))

# Create agent with persistent state
if 'session_id' in vars():
    # load state from db for session_id and state
    print("session_id is defined")
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db", 
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                )
    state = state.load_from_db(step_name)
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=True, timeout=30)    
else:
    # create new session
    print("session_id is not defined")
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")    
    session_id = f"test_newsletter_{timestamp}"
    print(session_id)
    state = NewsletterAgentState(session_id=session_id, 
                                 db_path="newsletter_agent.db",
                                 do_download=do_download,
                                 reprocess_since=reprocess_since,
                                 verbose=False
                                ) 
    agent = NewsletterAgent(session_id=session_id, state=state, verbose=False, timeout=30)
    agent.verbose=False  # there seems to be a bug where saved agents are saved or restored with verbose=True
    state.serialize_to_db("initialize")

🚀 Creating NewsletterAgent...
session_id is not defined
test_newsletter_20260215230952864288

In [9]:
agent.state.get_status()

{'headlines': {'total': 0},
 'sources': {'config_file': 'sources.yaml', 'loaded_sources': 0},
 'topics': {'cluster_topics': 0, 'topics': []},
 'workflow': {'current_step': 'gather_urls',
  'workflow_complete': False,
  'progress_percentage': 0.0,
  'completed_steps': 0,
  'total_steps': 9,
  'max_edits': 2,
  'concurrency': 12,
  'do_download': False,
  'reprocess_since': datetime.datetime(2026, 2, 14, 7, 32)},
 'processing': {'topic_clusters': 0,
  'newsletter_sections': 0,
  'final_newsletter_length': 0}}

In [10]:
for step in agent.state.steps:
    print(step)
    print("---")

⚪ Gather URLs [not_started]

---
⚪ Filter URLs [not_started]

---
⚪ Download Articles [not_started]

---
⚪ Extract Summaries [not_started]

---
⚪ Rate Articles [not_started]

---
⚪ Cluster By Topic [not_started]

---
⚪ Select Sections [not_started]

---
⚪ Draft Sections [not_started]

---
⚪ Finalize Newsletter [not_started]

---

In [11]:
# User prompt to run workflow
user_prompt = "Show the workflow status"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Show the workflow status'
================================================================================

23:09:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting check_workflow_status
23:09:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 6.28s
📊 Final result:
Current workflow status (from persistent state):

- Progress: 0.0% (0/9 complete)
- Summary: 0 complete, 0 started, 0 failed, 9 not started
- Next step: Gather URLs (Step 1 of 9)

Steps:
1. Gather URLs — not started
2. Filter URLs — not started
3. Download Articles — not started
4. Extract Summaries — not started
5. Rate Articles — not started
6. Cluster By Topic — not started
7. Select Sections — not started
8. Draft Sections — not started
9. Finalize Newsletter — not started

Would you like me to start the next step (gather URLs), run all steps to create the newsletter, or inspect detailed state before proceeding?

In [12]:
# User prompt to run a workflow step
user_prompt = "Run step 1, gather urls"

print(f"\n📝 User prompt: '{user_prompt}'")
print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_step(user_prompt)
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

📝 User prompt: 'Run step 1, gather urls'
================================================================================

23:10:01 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting check_workflow_status
23:10:01 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed check_workflow_status
23:10:02 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting Step 1: Gather URLs
2026-02-15 23:10:02,560 - fetcher_5621100688 - INFO - [fetcher_init] Loading sources from sources.yaml
2026-02-15 23:10:02,576 - fetcher_5621100688 - INFO - [fetcher_init] Loaded 17 sources: 5 RSS, 11 HTML, 1 API
2026-02-15 23:10:02,577 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Ars Technica': type=html, url=https://arstechnica.com/ai/
2026-02-15 23:10:02,577 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Bloomberg': type=RSS, url=https://www.bloomberg.com/ai
2026-02-15 23:10:02,577 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Business Insider': type=html, url=https://www.businessinsider.com/tech
2026-02-15 23:10:02,577 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'FT': type=RSS, url=https://www.ft.com/artificial-intelligence
2026-02-15 23:10:02,577 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Feedly AI': type=html, url=https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-15 23:10:02,578 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Hacker News': type=RSS, url=https://news.ycombinator.com/
2026-02-15 23:10:02,578 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'HackerNoon': type=RSS, url=https://hackernoon.com/tagged/ai
2026-02-15 23:10:02,578 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'New York Times': type=RSS, url=https://www.nytimes.com/section/technology
2026-02-15 23:10:02,578 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Reddit': type=RSS, url=https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-15 23:10:02,578 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Techmeme': type=RSS, url=https://www.techmeme.com/river
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'The Register': type=RSS, url=https://www.theregister.com/software/ai_ml/
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'The Verge': type=RSS, url=https://www.theverge.com/ai-artificial-intelligence
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'VentureBeat': type=RSS, url=https://venturebeat.com/category/ai
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'WSJ': type=RSS, url=https://www.wsj.com/tech/ai
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'Washington Post': type=RSS, url=https://www.washingtonpost.com/technology/innovations/
2026-02-15 23:10:02,579 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'The Guardian': type=RSS, url=https://www.theguardian.com/uk/technology
2026-02-15 23:10:02,580 - fetcher_5621100688 - DEBUG - [fetcher_sources] Source 'NewsAPI': type=rest, url=https://newsapi.org/v2/everything
2026-02-15 23:10:02,580 - fetcher_5621100688 - INFO - [fetcher_init] Fetcher initialized with max_concurrent=8
2026-02-15 23:10:02,580 - fetcher_5621100688 - INFO - [fetch_all] Starting fetch_all for 17 sources
2026-02-15 23:10:02,580 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Ars Technica: https://arstechnica.com/ai/
2026-02-15 23:10:02,580 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Ars_Technica.html
2026-02-15 23:10:02,609 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Ars_Technica.html
2026-02-15 23:10:02,610 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Ars Technica: 30 articles
2026-02-15 23:10:02,610 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Bloomberg: https://www.bloomberg.com/ai
2026-02-15 23:10:02,610 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Bloomberg.html
2026-02-15 23:10:02,635 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Bloomberg.html
2026-02-15 23:10:02,636 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Bloomberg: 39 articles
2026-02-15 23:10:02,636 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Business Insider: https://www.businessinsider.com/tech
2026-02-15 23:10:02,636 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Business_Insider.html
2026-02-15 23:10:02,653 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Business_Insider.html
2026-02-15 23:10:02,653 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Business Insider: 17 articles
2026-02-15 23:10:02,653 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from FT: https://www.ft.com/artificial-intelligence
2026-02-15 23:10:02,654 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/FT.html
2026-02-15 23:10:02,678 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/FT.html
2026-02-15 23:10:02,678 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for FT: 101 articles
2026-02-15 23:10:02,678 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Feedly AI: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
2026-02-15 23:10:02,678 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Feedly_AI.html
2026-02-15 23:10:02,721 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Feedly_AI.html
2026-02-15 23:10:02,721 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Feedly AI: 103 articles
2026-02-15 23:10:02,721 - fetcher_5621100688 - INFO - [fetch_rss] Fetching RSS from Hacker News: https://news.ycombinator.com/rss
2026-02-15 23:10:02,722 - fetcher_5621100688 - INFO - [fetch_rss] Fetching RSS from HackerNoon: https://hackernoon.com/tagged/ai/feed
2026-02-15 23:10:02,722 - fetcher_5621100688 - INFO - [fetch_rss] Fetching RSS from New York Times: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
2026-02-15 23:10:02,722 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Reddit: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
2026-02-15 23:10:02,722 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Reddit.html
2026-02-15 23:10:02,743 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Reddit.html
2026-02-15 23:10:02,744 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Reddit: 60 articles
2026-02-15 23:10:02,744 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Techmeme: https://www.techmeme.com/river
2026-02-15 23:10:02,744 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Techmeme.html

▶ Starting Step 1: gather_urls

2026-02-15 23:10:02,765 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Techmeme.html
2026-02-15 23:10:02,765 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Techmeme: 182 articles
2026-02-15 23:10:02,765 - fetcher_5621100688 - INFO - [fetch_rss] Fetching RSS from The Register: https://www.theregister.com/software/ai_ml/headlines.atom
2026-02-15 23:10:02,766 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from The Verge: https://www.theverge.com/ai-artificial-intelligence
2026-02-15 23:10:02,766 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/The_Verge.html
2026-02-15 23:10:02,800 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/The_Verge.html
2026-02-15 23:10:02,800 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for The Verge: 1 articles
2026-02-15 23:10:02,800 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from VentureBeat: https://venturebeat.com/category/ai
2026-02-15 23:10:02,800 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/VentureBeat.html
2026-02-15 23:10:02,807 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/VentureBeat.html
2026-02-15 23:10:02,807 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for VentureBeat: 23 articles
2026-02-15 23:10:02,807 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from WSJ: https://www.wsj.com/tech/ai
2026-02-15 23:10:02,807 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/WSJ.html
2026-02-15 23:10:02,832 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/WSJ.html
2026-02-15 23:10:02,832 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for WSJ: 54 articles
2026-02-15 23:10:02,832 - fetcher_5621100688 - INFO - [fetch_html] Using existing HTML file from Washington Post: https://www.washingtonpost.com/technology/innovations/
2026-02-15 23:10:02,832 - fetcher_5621100688 - INFO - [fetch_html] Parsing HTML file: download/sources/Washington_Post.html
2026-02-15 23:10:02,850 - fetcher_5621100688 - INFO - [fetch_html] Parsed HTML file: download/sources/Washington_Post.html
2026-02-15 23:10:02,851 - fetcher_5621100688 - INFO - [fetch_html] HTML fetch successful for Washington Post: 24 articles
2026-02-15 23:10:02,851 - fetcher_5621100688 - INFO - [fetch_rss] Fetching RSS from The Guardian: https://www.theguardian.com/uk/technology/rss
2026-02-15 23:10:02,851 - fetcher_5621100688 - INFO - [newsapi] Fetching top 100 stories matching artificial intelligence since 2026-02-14T23:10:02 from NewsAPI
2026-02-15 23:10:03,117 - fetcher_5621100688 - INFO - [fetch_rss] RSS fetch successful for New York Times: 24 articles
2026-02-15 23:10:03,285 - fetcher_5621100688 - INFO - [fetch_rss] RSS fetch successful for The Guardian: 24 articles
2026-02-15 23:10:03,298 - fetcher_5621100688 - INFO - [fetch_rss] RSS fetch successful for HackerNoon: 50 articles
2026-02-15 23:10:03,311 - fetcher_5621100688 - INFO - [fetch_rss] RSS fetch successful for The Register: 50 articles
2026-02-15 23:10:03,537 - fetcher_5621100688 - INFO - [fetch_rss] RSS fetch successful for Hacker News: 30 articles
2026-02-15 23:10:03,537 - fetcher_5621100688 - INFO - [fetch_all] fetch_all completed: 17 successful, 0 failed, 843 total articles

              source  url
0       Ars Technica   29
1          Bloomberg   28
2   Business Insider   17
3                 FT   50
4          Feedly AI   96
5        Hacker News   28
6         HackerNoon   50
7     New York Times   24
8            NewsAPI   30
9             Reddit   47
10          Techmeme  164
11      The Guardian   24
12      The Register   50
13         The Verge    1
14       VentureBeat   13
15               WSJ   28
16   Washington Post   18

,source,title,url,published,rss_summary,id
0,Ars Technica,I spent two days gigging at RentAHuman and did...,https://arstechnica.com/ai/2026/02/i-spent-two...,NaN,NaN,0
1,Ars Technica,OpenAI sidesteps Nvidia with unusually fast co...,https://arstechnica.com/ai/2026/02/openai-side...,NaN,NaN,1
2,Ars Technica,"Attackers prompted Gemini over 100,000 times w...",https://arstechnica.com/ai/2026/02/attackers-p...,NaN,NaN,2
3,Ars Technica,We let Chrome’s Auto Browse agent surf the web...,https://arstechnica.com/google/2026/02/tested-...,NaN,NaN,3
4,Ars Technica,"Retraction: After a routine code rejection, an...",https://arstechnica.com/ai/2026/02/after-a-rou...,NaN,NaN,4
...,...,...,...,...,...,...
692,NewsAPI,Why is Microsoft pushing us toward an AI unemp...,https://slashdot.org/submission/17344828/why-i...,2026-02-15T03:44:27Z,NaN,692
693,NewsAPI,China's stock bull run falters with corporate ...,https://www.business-standard.com/markets/news...,2026-02-15T01:19:11Z,NaN,693
694,NewsAPI,The Hidden Key to Boundless Energy,https://articles.mercola.com/sites/articles/ar...,2026-02-15T00:00:00Z,NaN,694
695,NewsAPI,Titans #32 Preview: Darkseid's Forces Meet Ars...,https://bleedingcool.com/comics/titans-32-prev...,2026-02-14T23:27:07Z,NaN,695
696,NewsAPI,Why GEN Z is failing where their parents did n...,https://www.sinhalanet.net/why-gen-z-is-failin...,2026-02-15T00:53:57Z,NaN,696

23:10:03 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed Step 1: Gathered 843 articles
23:10:04 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting check_workflow_status
23:10:04 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed check_workflow_status

================================================================================
⏱️  Total execution time: 7.10s
📊 Final result:
Step 1 (Gather URLs) completed.

Summary of results:
- Gathered 843 articles from 17 sources
- 697 articles stored in persistent state

Current workflow status:
- Progress: 11.1% (1/9 complete)
- Next step: Filter URLs (Step 2 of 9)

Would you like me to proceed to Step 2 (filter URLs to AI-related content) now?

In [13]:
countdf = pd.DataFrame(state.headline_data) \
    .groupby("source") \
    .count()[["id"]] \
    .reset_index() \
    .rename(columns={'id': 'count'}) \
    .sort_values("count", ascending=False)
countdf

              source  count
10          Techmeme    164
4          Feedly AI     96
12      The Register     50
3                 FT     50
6         HackerNoon     50
9             Reddit     47
8            NewsAPI     30
0       Ars Technica     29
1          Bloomberg     28
5        Hacker News     28
15               WSJ     28
7     New York Times     24
11      The Guardian     24
16   Washington Post     18
2   Business Insider     17
14       VentureBeat     13
13         The Verge      1

In [14]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 11.1% (1/9 complete)
➡️  Next step: Step 1: Filter URLs

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 843 articles from 17 sources.

📊 Articles stored in persistent state: 697
  ⭕ Step 1: Filter URLs            | not_started
  ⭕ Step 2: Download Articles      | not_started
  ⭕ Step 3: Extract Summaries      | not_started
  ⭕ Step 4: Rate Articles          | not_started
  ⭕ Step 5: Cluster By Topic       | not_started
  ⭕ Step 6: Select Sections        | not_started
  ⭕ Step 7: Draft Sections         | not_started
  ⭕ Step 8: Finalize Newsletter    | not_started
============================================================

In [15]:
# Run tool directly without LLM processing an input prompt or results
# user_prompt = "Run step 2, filter urls"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)
# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("filter_urls")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting Step 2: Filter URLs
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 🔍 Filtering 697 headlines...
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 🔄 Checking for duplicates seen before 2026-02-14T07:32:00
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 🔍 Filtering 697 articles for dupes.
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://arstechnica.com/ai/2026/02/i-spent-two-days-gigging-at-rentahuman-and-didnt-make-a-single-cent/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/attackers-prompted-gemini-over-100000-times-while-trying-to-clone-it-google-says/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/tested-how-chromes-auto-browse-agent-handles-common-web-tasks/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://arstechnica.com/ai/2026/02/after-a-routine-code-rejection-an-ai-agent-published-a-hit-piece-on-someone-by-name/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/grok-maker-xai-loses-another-co-founder/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://arstechnica.com/space/2026/02/nasa-chief-vows-to-solve-sls-rocket-fueling-issues-before-artemis-iii/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://arstechnica.com/staff/2026/02/editors-note-retraction-of-article-containing-fabricated-quotations/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://arstechnica.com/space/2026/02/why-is-bezos-trolling-musk-on-x-with-turtle-pics-because-he-has-a-new-moon-plan/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/gadgets/2026/02/alphabet-selling-very-rare-100-year-bunds-to-help-fund-ai-investment/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/after-moltbook-ai-agents-can-now-hang-out-in-their-own-space-faring-mmo/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/sixteen-claude-ai-agents-working-together-created-a-new-c-compiler/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/02/waymo-leverages-genie-3-to-create-a-world-model-for-self-driving-cars/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/features/2026/02/why-darren-aronofsky-thought-an-ai-generated-historical-docudrama-was-a-good-idea/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/with-gpt-5-3-codex-openai-pitches-codex-for-more-than-just-writing-code/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/increase-of-ai-bots-on-the-internet-sparks-arms-race/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/should-ai-chatbots-have-ads-anthropic-says-no/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/apple/2026/02/xcode-26-3-adds-support-for-claude-codex-and-other-agentic-tools-via-mcp/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/senior-staff-departing-openai-as-firm-prioritizes-chatgpt-development/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/the-rise-of-moltbook-suggests-viral-ai-prompts-may-be-the-next-big-security-threat/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/spacex-acquires-xai-plans-1-million-satellite-constellation-to-power-it/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/02/openai-picks-up-pace-against-claude-code-with-new-codex-desktop-app/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/developers-say-ai-coding-tools-work-and-thats-precisely-what-worries-them/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/security/2026/01/web-portal-leaves-kids-chats-with-ai-toy-open-to-anyone-with-gmail-account/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/how-often-do-ai-chatbots-lead-users-down-a-harmful-path/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-project-genie-lets-you-create-interactive-worlds-from-a-photo-or-prompt/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/new-openai-tool-renews-fears-that-ai-slop-will-overwhelm-scientific-research/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/google/2026/01/google-begins-rolling-out-chromes-auto-browse-ai-agent-today/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://arstechnica.com/ai/2026/01/report-china-approves-import-of-high-end-nvidia-ai-chips-after-weeks-of-uncertainty/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/alibaba-leads-tech-slide-after-pentagon-briefly-shows-blacklist
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/india-seeks-role-in-shaping-ai-future-with-summit-of-tech-chiefs
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-13/ai-kingpins-adopt-crypto-s-playbook-in-bid-to-get-allies-elected-to-congress
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/openai-hires-openclaw-ai-agent-developer-peter-steinberg
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/uk-s-starmer-wants-ai-chatbots-to-follow-online-safety-rules
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/a-stock-market-doom-loop-is-hitting-everything-that-touches-ai
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-31/elon-musk-s-ai-push-has-him-considering-mergers-in-search-for-capital
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-01-19/grok-ai-sexualized-images-expose-gaps-in-oversight-enforcement
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2025-11-18/china-s-tsinghua-university-is-beating-us-in-the-race-for-ai-patents
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2026-02-10/trump-s-ai-policy-shaped-by-vc-tech-giant-andreessen-horowitz
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/waltons-crack-ranks-of-10-richest-as-nvidia-s-huang-falls-out
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.bloomberg.com/news/features/2024-12-13/ai-wants-more-data-more-chips-more-power-more-water-more-everything
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/bloomberg-tech-2-13-2026-video
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/building-data-centers-in-space-video
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/videos/2026-02-13/the-tech-basket-is-incredibly-attractive-golub-says-video
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/amazon-eyes-longest-losing-streak-since-2006-on-capex-angst
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/amazon-engineers-grate-against-internal-limits-claude-code-kiro-ai-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/salesforce-appoints-new-leaders-executive-reshuffle-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/elon-musk-anthropic-philosopher-amanda-askell-debate-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/sam-altman-hires-openclaw-creator-peter-steinberger-personal-ai-agents-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.businessinsider.com/guides/tech/best-dolby-atmos-soundbar
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://adclick.g.doubleclick.net/pcs/click
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/job-hunting-on-tinder-hinge-grindr-dating-app-networking-referrals-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/ai-fatigue-gary-marcus-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/jensen-huang-net-worth
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/lucid-gravity-suv-review-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/evs-touchscreen-buttons-coming-back-tesla-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/meta-ray-ban-smart-glasses-facial-recognition-distracted-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/gary-marcus-response-something-big-is-happening-ai-essay-shumer-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/dbd1d803-ab37-43f1-920f-fce74952313a
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/94633f65-04c0-4cea-b682-98c17720eebc
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/3fc82496-1132-4cb3-a967-25c4c274fbea
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/cde7c236-e62f-4ced-9667-7115f16a40e6
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/e68d68da-3966-47c7-b310-3f39fd4b69b2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/b04fc3d5-c916-4ac8-ab4f-a65a9f4e60c5
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/26b9a426-fab0-4c21-bfd4-3f1bbb0ecb8b
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/2daa41c3-3721-46d1-8954-7c43d5149995
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/b314a05c-e1b7-4c0e-9379-2955ba1bfad1
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/9e5742e4-adae-4178-9951-7372adeb7ffc
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/8280412c-df99-4eb2-b447-f29872d0439d
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/4b1e7ab6-2b76-4e66-836b-d54d76147a15
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/29c46363-9d8f-42f7-8805-f9995e0eadad
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/9fbc4ae4-c279-44fa-9d59-d49bc970c4ac
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/3dd3f37b-a783-4f12-a837-764e9f429b01
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/89985a10-1283-40fa-8dc1-9daa6c360b45
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/62b8713f-cd72-4838-b8ac-708b91b2830f
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/b06ca67e-41b0-4402-9b39-9e4b432a1291
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.ft.com/content/de11ac30-e6c2-4a67-8f01-c9ccac317885

▶ Starting Step 2: filter_urls

23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.fool.com/investing/2026/02/15/decades-of-passive-income-buy-this-index-fund-schd/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://247wallst.com/investing/2026/02/14/amazons-epic-losing-streak-why-this-dip-could-be-your-ticket-to-riches/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/video/trumps-manufacturing-comeback-real-150629604.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://fortune.com/2026/02/15/ai-productivity-liftoff-doubling-2025-jobs-report-transition-harvest-phase-j-curve/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://news.slashdot.org/story/26/02/16/0139206/ars-technicas-ai-reporter-apologizes-for-mistakenly-publishing-fake-ai-generated-quotes
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/vertiv-vrt-orders-were-incredible-151232966.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.theguardian.com/technology/2026/feb/15/ai-chatbots-children-risk-fines-uk-ban
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://futurism.com/artificial-intelligence/vending-machine-ai-price-fixing
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/safer-chip-stocks-boomed-too-143000228.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pymnts.com/artificial-intelligence-2/2026/openai-delays-first-consumer-device-to-2027/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://fortune.com/2026/02/15/ai-demand-memory-chip-shortage-crisis-dram-hbm-micron-skhynix-samsung/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://247wallst.com/investing/2026/02/14/amazon-and-microsoft-enter-bear-markets-whats-breaking-the-magnificent-7/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/15/as-ai-data-centers-hit-power-limits-peak-xv-backs-indian-startup-c2i-to-fix-the-bottleneck/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://dlants.me/agi-not-imminent.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bgr.com/2098130/stephen-hawking-warning-humanity-colonize-planets/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/amazons-secret-weapon-is-getting-stronger/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pymnts.com/amazon/2026/amazon-spends-200-billion-on-ai-amid-cloud-competition/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/forget-nvidia-buy-artificial-intelligence-ai-stock/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://news.google.com/rss/articles/CBMisgFBVV95cUxNNm9sQk9jTXp4dHcwalZsMFRtTDFrVDJuZHhiT0QyeGJ4M05GeElvTmpWT1M4Zl9oaHI2UUZZaXlTcnhrSHg3SnE2N1dNTXdYeWN4cng2aXh6V2VsOFFjVlpuNjZKeDdOV1dyVTl4WUZ5U1hKQXBzRkFfMmF4RTFRYWhGWmVPQlZKREZCNUMwZlNRTUp0MV9NazZyRjl4YUQ0UEhmb3FHWEd3QzlXNmZFVXVB
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://news.google.com/rss/articles/CBMitAFBVV95cUxPM3VOVVNBeEh2S2tjTjBuRVNMNjlKWi15VDNZYm1aUi1IbEFNNjZJLVE1aVg3eDg0M21ueEFvUVZsaEhrbzZTd2x5QmVULVhnWTNnUnJvaWVtRlMyeTJIRDNOdUt3WFpiTVY1VXpLalB4WEhRNFduNlBzU2hIZ0xOckRLMU1WTmtjb2FMUXBtM2ExdjBxZHQ3SVUtdWFGTUNOR1gzYVBSTEpfOTZSeGtVSVo0M0g
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.bloomberg.com/features/2026-china-ai-billionaires/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/14/prediction-asmls-stock-price-will-hit-2000-by-this/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.euronews.com/next/2026/02/15/europe-seen-as-key-market-for-data-sovereignty-technology
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://mashable.com/article/ai-hard-drive-hdd-shortages-western-digital-sold-out
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://venturebeat.com/infrastructure/nvidia-groq-and-the-limestone-race-to-real-time-ai-why-enterprises-win-or
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/15/india-has-100m-weekly-active-chatgpt-users-sam-altman-says/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://fortune.com/2026/02/14/ai-effect-macro-economic-data-labor-enhancement-some-sectors-workers-displacement/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/does-coinbases-ceo-know-dont-233138605.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/if-you-invested-10000-in-palantir-during-its-ipo-h/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/3-tech-stocks-with-more-potential-than-any-cryptoc/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/why-the-software-stock-crash-is-really-starting-to-worry-me-133100282.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://hackernoon.com/how-to-excel-in-ai-without-learning-to-code
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://hackernoon.com/algorithmic-ventriloquism-how-crustafarian-agentic-ai-bots-will-not-take-over-the-world
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://hackernoon.com/multilingual-prompt-injection-exposes-gaps-in-llm-safety-nets
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/up-131-ytd-should-you-buy-sandisk-stock-right-now/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://mashable.com/article/airbnb-testing-ai-powered-search-feature
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/applovin-shares-crash-despite-stellar-growth-is-it/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/tom-lee-says-ai-killed-230155251.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/visa-v-ken-griffin-top-225533087.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/meta-platforms-meta-philippe-laffont-225011939.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/green-brick-partners-grbk-david-224933090.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/cvs-health-corporation-cvs-larry-224810411.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/alphabet-googl-christopher-rokos-top-224800701.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/pdd-holdings-pdd-zhang-lei-224750597.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/microsoft-corporation-msft-chase-coleman-224742048.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/amazon-com-amzn-mason-morfit-224733875.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/maplebear-cart-daniel-sundheim-top-224710741.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.nytimes.com/2026/02/14/business/artificial-intelligence-relationships-income-gap.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://github.com/klawsh/klaw.sh
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pymnts.com/news/delivery/2026/uber-brings-food-delivery-to-7-new-eu-markets/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://tech.slashdot.org/story/26/02/15/2231220/indias-new-social-media-rules-remove-unlawful-content-in-three-hours-detect-illegal-ai-content-automatically
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/why-did-bittensor-surge-more-than-5-this-past-week/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/walmart-earnings-preview-wmt-reach-171133867.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.fool.com/investing/2026/02/15/2-monster-stocks-to-hold-for-the-next-5-years/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/15/longtime-npr-host-david-greene-sues-google-over-notebooklm-voice/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/should-you-buy-soundhound-ai-stock-while-its-under/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/15/the-enterprise-ai-land-grab-is-on-glean-is-building-the-layer-beneath-the-interface/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found before cutoff - ignoring as duplicate https://www.cnn.com/2026/02/11/business/openai-anthropic-departures-nightcap
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/president-trump-changed-insane-regulation-213240807.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://twitter.com/steipete/status/2023057089346580828
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://amplifypartners.com/blog-posts/arming-the-rebels-with-gpus-gradium-kyutai-and-audio-ai
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pymnts.com/artificial-intelligence-2/2026/food-companies-say-ai-plays-only-limited-role-in-products/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/reddit-insider-sends-major-vote-212026058.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/the-1-stock-id-buy-before-spdr-gold-shares-right-n/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/amazon-stock-fires-bullish-technical-211102071.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/ai-disruption-fear-foms-other-180002318.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techcrunch.com/2026/02/15/anthropic-and-the-pentagon-are-reportedly-arguing-over-claude-usage/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/3-bargain-stocks-that-can-set-you-up-for-life/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/does-riot-platforms-5-gain-this-past-week-signal-a/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/the-smartest-growth-stock-to-buy-with-500-now/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/better-artificial-intelligence-stock-nvidia-vs-amd/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/one-artificial-intelligence-ai-stock-that-could-ma/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/should-buy-booking-holdings-stock-before-feb-18/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://seekingalpha.com/news/4552199-goldman-unveils-ai-resilient-software-trade-basket
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/cisco-stock-resets-dividend-payout-194124901.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://techdeals.net/domestic-chip-breakthrough-loongson-3b6000m-dominates-openclaw-performance-outshining-mac-mini/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fool.com/investing/2026/02/15/software-bear-market-2-stocks-with-massive-upside/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/veteran-trader-makes-eye-popping-193300819.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://247wallst.com/investing/2026/02/15/3-cataylsts-behind-vertivs-20-weekly-jump-252-order-growth-fuels-2026-guidance-boom/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://news.google.com/rss/articles/CBMifEFVX3lxTE5GYWpZelJnUVlpdDhXV3FkUmdwdTBPajFKY0Y4NlBGelZ3cE1UcEM3aEJZenlRd1k0c0I5NjBpbXJWOC1wekRhN2F1X1VxZTlNTWRybVpaZVRvZ1QySTVWSVM3eXEtbVg3WmJHMHNnMDRKbnR4MHpENDFEN0U
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.businessinsider.com/disney-ai-copyright-battles-seedance-nano-banana-sora-midjourney-2026-2
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://finance.yahoo.com/news/morgan-stanley-flags-45b-hidden-184700810.html
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://news.google.com/rss/articles/CBMiwwFBVV95cUxQV1dsc1NHdE9KYmFFMTB0TVZLOUQxRi1rbXNnQm8xV3dyd2hIZUNZMHlobXZJR2RvcjVSQlVkMnhHVDFOcVNwWlhES3ktX2FoTzhQd0VXcjVZTVdFSVFmWWJsOEsyeFRJbnJwTWlhdFJYQ1RydFU1STBDWE4xNTRsTnB1NUtqZDAwbHBMbVFzbDFPallOdE5sTTNUWjV1YjRXVTZjbS1kZ2FBaVBpNGN1N1BtUlh2dk4tRzdYYzVlWEYyV28
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.forbes.com/sites/johnwerner/2026/02/15/what-on-earth-is-wrong-with-intelligent-medicine/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://steipete.me/posts/2026/openclaw
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.fide.com/magnus-carlsen-wins-2026-fide-freestyle-world-championship/
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.economist.com/business/2026/02/12/arm-wants-a-bigger-slice-of-the-chip-business
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.pennmedicine.org/news/pink-noise-reduces-rem-sleep-and-may-harm-sleep-quality
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://github.com/TechPaula/LT6502
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://modern-css.com
23:10:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | found after cutoff - keeping https://www.amplifypartners.com/blog-posts/arming-the-rebels-with-gpus-gradium-kyutai-and-audio-ai

================================================================================
⏱️  Total execution time: 308.24s
📊 Final result:
✅ Step 2 filter_urls completed successfully! Removed 368 duplicate URLs, classified 329 new articles, found 178 AI-related.

In [16]:
headline_df = pd.DataFrame(state.headline_data)
headline_df

,source,title,url,published,rss_summary,id,isAI
0,Ars Technica,I spent two days gigging at RentAHuman and did...,https://arstechnica.com/ai/2026/02/i-spent-two...,NaN,NaN,0,False
1,Ars Technica,"Retraction: After a routine code rejection, an...",https://arstechnica.com/ai/2026/02/after-a-rou...,NaN,NaN,4,True
2,Ars Technica,NASA has a new problem to fix before the next ...,https://arstechnica.com/space/2026/02/nasa-chi...,NaN,NaN,6,False
3,Ars Technica,Editor’s Note: Retraction of article containin...,https://arstechnica.com/staff/2026/02/editors-...,NaN,NaN,7,False
4,Ars Technica,Why is Bezos trolling Musk on X with turtle pi...,https://arstechnica.com/space/2026/02/why-is-b...,NaN,NaN,8,False
...,...,...,...,...,...,...,...
324,NewsAPI,Why is Microsoft pushing us toward an AI unemp...,https://slashdot.org/submission/17344828/why-i...,2026-02-15T03:44:27Z,NaN,692,True
325,NewsAPI,China's stock bull run falters with corporate ...,https://www.business-standard.com/markets/news...,2026-02-15T01:19:11Z,NaN,693,False
326,NewsAPI,The Hidden Key to Boundless Energy,https://articles.mercola.com/sites/articles/ar...,2026-02-15T00:00:00Z,NaN,694,False
327,NewsAPI,Titans #32 Preview: Darkseid's Forces Meet Ars...,https://bleedingcool.com/comics/titans-32-prev...,2026-02-14T23:27:07Z,NaN,695,False
328,NewsAPI,Why GEN Z is failing where their parents did n...,https://www.sinhalanet.net/why-gen-z-is-failin...,2026-02-15T00:53:57Z,NaN,696,False

In [17]:
# User prompt to run workflow
# user_prompt = "Run step 3, download full articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

# Run the agent with persistent state
start_time = time.time()
result = await agent.run_tool_direct("download_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:15:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting Step 3: Download Articles
23:15:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting concurrent scraping of 178 AI-related articles

▶ Starting Step 3: download_articles

23:15:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Launching browser for 178 URLs with 12 concurrent workers
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 1 of 178 https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Spotify_CEO_says_its_top_developers__have_not_written_a_single_line_of_code__in_2026.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 2 of 178 https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/OpenClaw_Creator_Gets_Big_Offers_to_Acquire_AI_Sensation_Will_It_Stay_Open_Source.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 3 of 178 https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/The_AI_productivity_take-off_is_finally_visible.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 4 of 178 https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/AI_agents_are_transforming_what_it_s_like_to_be_a_coder___It_s_been_unlike_any_other_time..html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 5 of 178 https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/OpenClaw-fueled_ordering_frenzy_creates_Apple_Mac_shortage___delivery_for_high_Unified_Memory_units_now_ranges_from_6_days_to_6_weeks.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 6 of 178 https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Skipping ignored domain: www.bloomberg.com
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video with status: skipped
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 7 of 178 https://finance.yahoo.com/news/meta-platforms-meta-philippe-laffont-225011939.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Is_Meta_Platforms__META__Philippe_Laffont_s_Top_Pick.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://finance.yahoo.com/news/meta-platforms-meta-philippe-laffont-225011939.html with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 8 of 178 https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/The_AI_Stock_That_Could_Make_Early_Investors_Rich_by_the_End_of_2026.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 9 of 178 https://hackernoon.com/2-13-2026-newsletter?source=rss
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/The_HackerNoon_Newsletter__AI_Coding_Tip_006_-_Review_Every_Line_Before_You_Commit__2_13_2026.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://hackernoon.com/2-13-2026-newsletter?source=rss with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 10 of 178 https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Skipping ignored domain: www.bloomberg.com
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim with status: skipped
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 11 of 178 https://www.nature.com/articles/s41598-026-39835-3
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Motion_analysis_driven_by_table_tennis_pose_and_analysis_of_participation_motivation_and_athlete_satisfaction_based_on_artificial_intelligence_YOLOv8.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.nature.com/articles/s41598-026-39835-3 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 12 of 178 https://news.google.com/rss/articles/CBMitAFBVV95cUxPM3VOVVNBeEh2S2tjTjBuRVNMNjlKWi15VDNZYm1aUi1IbEFNNjZJLVE1aVg3eDg0M21ueEFvUVZsaEhrbzZTd2x5QmVULVhnWTNnUnJvaWVtRlMyeTJIRDNOdUt3WFpiTVY1VXpLalB4WEhRNFduNlBzU2hIZ0xOckRLMU1WTmtjb2FMUXBtM2ExdjBxZHQ3SVUtdWFGTUNOR1gzYVBSTEpfOTZSeGtVSVo0M0g
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/OpenAI_in_Advanced_Talks_to_Hire_OpenClaw_Founder__Others_Connected_to_Agent_Project.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://news.google.com/rss/articles/CBMitAFBVV95cUxPM3VOVVNBeEh2S2tjTjBuRVNMNjlKWi15VDNZYm1aUi1IbEFNNjZJLVE1aVg3eDg0M21ueEFvUVZsaEhrbzZTd2x5QmVULVhnWTNnUnJvaWVtRlMyeTJIRDNOdUt3WFpiTVY1VXpLalB4WEhRNFduNlBzU2hIZ0xOckRLMU1WTmtjb2FMUXBtM2ExdjBxZHQ3SVUtdWFGTUNOR1gzYVBSTEpfOTZSeGtVSVo0M0g with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 13 of 178 https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Is_NVIDIA__NVDA__Clifford_Asness__Top_Pick.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 14 of 178 https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/AI_Worries_Erase__1_Trillion_From_Big_Tech_Firms.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 15 of 178 https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Analysis__despite_investing__150B__in_10__years__China_is_expected_to_produce_2__of_global_AI_chips_in_2026_and_70x_less_memory_storage_than_foreign_chipmakers.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 16 of 178 https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Skipping ignored domain: www.bloomberg.com
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout with status: skipped
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 17 of 178 https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Radio_host_David_Greene_says_Google_s_NotebookLM_tool_stole_his_voice.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 18 of 178 https://www.bostonherald.com/2026/02/14/healey-deploys-artificial-intelligence-tool-chatgpt-across-executive-branch/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Healey_deploys_artificial_intelligence_tool_ChatGPT_across_executive_branch.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.bostonherald.com/2026/02/14/healey-deploys-artificial-intelligence-tool-chatgpt-across-executive-branch/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 19 of 178 https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/The_stock_market_is_reflecting_fears_of_an_AI_apocalypse_for_white-collar_jobs.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 20 of 178 https://steipete.me/posts/2026/openclaw
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/I_m_joining_OpenAI.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://steipete.me/posts/2026/openclaw with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 21 of 178 https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Anthropic_Blasts_Pentagon_s_Use_of_Its_AI_Tool_in_Venezuela_Raid_May_Void__200M_Contract.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 22 of 178 https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/US-based_Guyanese_scientist_recognised_for_pioneering_AI-driven_drug_development.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 23 of 178 https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Skipping ignored domain: www.wsj.com
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b with status: skipped
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 24 of 178 https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/India_approves_a__1.1B_state-backed_VC_fund_to_finance_high-risk_areas_like_AI_and_advanced_manufacturing__doubling_down_on_an_effort_that_debuted_in_2016.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 25 of 178 https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/The_covid_reality_check_for_AI_hype.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/ with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 26 of 178 https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/India_seeks_to_broker_consensus_on_global__AI_commons.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 completed https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 0 fetching 27 of 178 https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | scrape_url(https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html)
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | scraping https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html to download/html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Downloading https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 1 fetching 28 of 178 https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Mocktails__potato_balls__and_10_bots__My_cringe_Valentine_s_date_at_the_AI_companion_wine_bar.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 1 completed https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2 with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 1 fetching 29 of 178 https://www.thehindubusinessline.com/info-tech/openai-has-deleted-the-word-safely-from-its-mission-and-its-new-structure-is-a-test-for-whether-ai-serves-society-or-shareholders/article70634505.ece
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | scrape_url(https://www.thehindubusinessline.com/info-tech/openai-has-deleted-the-word-safely-from-its-mission-and-its-new-structure-is-a-test-for-whether-ai-serves-society-or-shareholders/article70634505.ece)
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | scraping https://www.thehindubusinessline.com/info-tech/openai-has-deleted-the-word-safely-from-its-mission-and-its-new-structure-is-a-test-for-whether-ai-serves-society-or-shareholders/article70634505.ece to download/html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Downloading https://www.thehindubusinessline.com/info-tech/openai-has-deleted-the-word-safely-from-its-mission-and-its-new-structure-is-a-test-for-whether-ai-serves-society-or-shareholders/article70634505.ece
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 fetching 30 of 178 https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Skipping ignored domain: www.bloomberg.com
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 completed https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years with status: skipped
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 fetching 31 of 178 https://hackernoon.com/glm-ocr-explained-promptable-ocr-that-outputs-clean-json?source=rss
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/GLM-OCR_Explained__Promptable_OCR_That_Outputs_Clean_JSON.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 completed https://hackernoon.com/glm-ocr-explained-promptable-ocr-that-outputs-clean-json?source=rss with status: exists
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 fetching 32 of 178 https://microgpt.boratto.ca
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | File already exists: download/html/Show_HN__Microgpt_is_a_GPT_you_can_visualize_in_the_browser.html
23:15:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Worker 2 completed https://microgpt.boratto.ca with status: exists

Starting with 178 rows...
Processing 178 files...
Reading and truncating files to 8192 tokens using text-embedding-3-large tokenizer...
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Error reading : [Errno 2] No such file or directory: ''
Getting embeddings for 150 texts...
Creating indexed similarity matrix...
Finding pairs with similarity > 0.925...
Filtering dataframe...
  Pair: 82 vs 98
    82: Feedly AI - Audio is the one area small labs are winning
    82: https://amplifypartners.com/blog-posts/arming-the-rebels-with-gpus-gradium-kyutai-and-audio-ai
    98: Hacker News - Audio is the one area small labs are winning
    98: https://www.amplifypartners.com/blog-posts/arming-the-rebels-with-gpus-gradium-kyutai-and-audio-ai
  Pair: 163 vs 162
    163: NewsAPI - Embedded LLM Launches the EU AI Grid at Munich Cyber Security Conference (MCSC) to Meet EU Demand for Sovereign AI Capability
    163: https://www.globenewswire.com/news-release/2026/02/15/3238440/0/en/Embedded-LLM-Launches-the-EU-AI-Grid-at-Munich-Cyber-Security-Conference-MCSC-to-Meet-EU-Demand-for-Sovereign-AI-Capability.html
    162: NewsAPI - Embedded LLM Launches the EU AI Grid at Munich Cyber Security Conference (MCSC) to Meet EU Demand for Sovereign AI Capability
    162: https://financialpost.com/globe-newswire/embedded-llm-launches-the-eu-ai-grid-at-munich-cyber-security-conference-mcsc-to-meet-eu-demand-for-sovereign-ai-capability
  Pair: 172 vs 168
    172: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report
    172: https://www.business-standard.com/world-news/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute-report-126021500073_1.html
    168: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report
    168: https://m.economictimes.com/tech/artificial-intelligence/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute-axios-reports/articleshow/128370468.cms
  Pair: 172 vs 160
    172: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report
    172: https://www.business-standard.com/world-news/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute-report-126021500073_1.html
    160: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute, Axios reports
    160: https://www.channelnewsasia.com/business/pentagon-threatens-cut-anthropic-in-ai-safeguards-dispute-axios-reports-5932441
  Pair: 168 vs 160
    168: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report
    168: https://m.economictimes.com/tech/artificial-intelligence/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute-axios-reports/articleshow/128370468.cms
    160: NewsAPI - Pentagon threatens to cut off Anthropic in AI safeguards dispute, Axios reports
    160: https://www.channelnewsasia.com/business/pentagon-threatens-cut-anthropic-in-ai-safeguards-dispute-axios-reports-5932441
  Pair: 20 vs 119
    20: Business Insider - Sam Altman says OpenClaw creator Peter Steinberger is joining OpenAI to build next-gen personal agents
    20: https://www.businessinsider.com/sam-altman-hires-openclaw-creator-peter-steinberger-personal-ai-agents-2026-2
    119: Techmeme - Sam Altman says Peter Steinberger, founder of OpenClaw, is joining OpenAI “to drive the next generation of personal agents”; OpenClaw will remain open source
    119: https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
  Pair: 20 vs 118
    20: Business Insider - Sam Altman says OpenClaw creator Peter Steinberger is joining OpenAI to build next-gen personal agents
    20: https://www.businessinsider.com/sam-altman-hires-openclaw-creator-peter-steinberger-personal-ai-agents-2026-2
    118: Techmeme - Sam Altman says Peter Steinberger, founder of OpenClaw, is joining OpenAI “to drive the next generation of personal agents”; OpenClaw will remain open source
    118: https://x.com/sama/status/2023150230905159801
  Pair: 47 vs 54
    47: Feedly AI - Rampant AI demand for memory is fueling a growing chip crisis
    47: https://fortune.com/2026/02/15/ai-demand-memory-chip-shortage-crisis-dram-hbm-micron-skhynix-samsung/
    54: Feedly AI - Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis
    54: https://news.google.com/rss/articles/CBMisgFBVV95cUxNNm9sQk9jTXp4dHcwalZsMFRtTDFrVDJuZHhiT0QyeGJ4M05GeElvTmpWT1M4Zl9oaHI2UUZZaXlTcnhrSHg3SnE2N1dNTXdYeWN4cng2aXh6V2VsOFFjVlpuNjZKeDdOV1dyVTl4WUZ5U1hKQXBzRkFfMmF4RTFRYWhGWmVPQlZKREZCNUMwZlNRTUp0MV9NazZyRjl4YUQ0UEhmb3FHWEd3QzlXNmZFVXVB
  Pair: 47 vs 4
    47: Feedly AI - Rampant AI demand for memory is fueling a growing chip crisis
    47: https://fortune.com/2026/02/15/ai-demand-memory-chip-shortage-crisis-dram-hbm-micron-skhynix-samsung/
    4: Bloomberg - Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis
    4: https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis
  Pair: 54 vs 4
    54: Feedly AI - Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis
    54: https://news.google.com/rss/articles/CBMisgFBVV95cUxNNm9sQk9jTXp4dHcwalZsMFRtTDFrVDJuZHhiT0QyeGJ4M05GeElvTmpWT1M4Zl9oaHI2UUZZaXlTcnhrSHg3SnE2N1dNTXdYeWN4cng2aXh6V2VsOFFjVlpuNjZKeDdOV1dyVTl4WUZ5U1hKQXBzRkFfMmF4RTFRYWhGWmVPQlZKREZCNUMwZlNRTUp0MV9NazZyRjl4YUQ0UEhmb3FHWEd3QzlXNmZFVXVB
    4: Bloomberg - Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis
    4: https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis
  Pair: 119 vs 118
    119: Techmeme - Sam Altman says Peter Steinberger, founder of OpenClaw, is joining OpenAI “to drive the next generation of personal agents”; OpenClaw will remain open source
    119: https://www.theinformation.com/articles/openai-advanced-talks-hire-openclaw-founder-others-connected-agent-project
    118: Techmeme - Sam Altman says Peter Steinberger, founder of OpenClaw, is joining OpenAI “to drive the next generation of personal agents”; OpenClaw will remain open source
    118: https://x.com/sama/status/2023150230905159801
  Pair: 40 vs 6
    40: Feedly AI - A Stock Market Doom Loop Is Hitting Everything That Touches AI
    40: https://news.google.com/rss/articles/CBMiswFBVV95cUxPcW9VVS1JV29FazRmcHFhdFJJWU92eE5RQmJ5YjRhQVB5bE5NTS1ZSGxWWVdreUZLaFI5bHNYNlNGMkRBZXJFS0tfZFA3c1ZvaTB2bnp1TE9vWC0xdFNpd0hOUnJURGtxMEd3eTNrSkhhRGZWMThMYlpEc2FwOVBqWk5KMEsyZC15WFY2TmJDUkMyMkRWZkd0Y3hhYmFlalhyMzA1Q25FSG52LUcxN082QnU5cw
    6: Bloomberg - A Stock Market Doom Loop Is Hitting Everything That Touches AI
    6: https://www.bloomberg.com/news/articles/2026-02-15/a-stock-market-doom-loop-is-hitting-everything-that-touches-ai
  Pair: 114 vs 57
    114: Reddit - The stock market is reflecting fears of an AI apocalypse for white-collar jobs
    114: https://www.msn.com/en-us/news/other/ar-AA1WlZhm
    57: Feedly AI - The stock market is reflecting fears of an AI apocalypse for white-collar jobs
    57: https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html
Removing 10 rows due to high similarity
Final dataframe has 168 rows (removed 10 rows)
Missing files:

,title,status,final_url
13,AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
12,NY Congressional Candidate Faced Palantir Sexual Comments Claim,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim
11,Anduril in Talks to Raise Billions at Over $60 Billion Valuation,skipped,https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information
10,Companies May 'Spend to Defend' AI Risk: Moody's Pinto,skipped,https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
9,Waltons Crack Ranks of 10 Richest as Nvidia’s Huang Falls Out,skipped,https://www.bloomberg.com/news/articles/2026-02-13/waltons-crack-ranks-of-10-richest-as-nvidia-s-huang-falls-out
15,Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout,skipped,https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
8,AI Bubble Fears Are Creating New Derivatives,skipped,https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
7,AI Risk Is Dominating Conference Calls as Investors Dump Stocks,skipped,https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks
5,UK’s Starmer Wants AI Chatbots to Follow Online Safety Rules,skipped,https://www.bloomberg.com/news/articles/2026-02-15/uk-s-starmer-wants-ai-chatbots-to-follow-online-safety-rules
1,India Seeks Role in Shaping AI Future With Summit of Tech Chiefs,skipped,https://www.bloomberg.com/news/articles/2026-02-16/india-seeks-role-in-shaping-ai-future-with-summit-of-tech-chiefs
3,OpenAI Hires OpenClaw AI Agent Developer Peter Steinberg,skipped,https://www.bloomberg.com/news/articles/2026-02-15/openai-hires-openclaw-ai-agent-developer-peter-steinberg
2,Blackstone to Lead $600 Million Investment in AI Firm Neysa,skipped,https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa
14,"AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
17,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",skipped,https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy
16,"FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
137,"Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO",skipped,https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
120,Sources: OpenAI is in advanced talks to hire OpenClaw founder Peter Steinberger and several team members; Steinberger would likely work on personal agents,403,https://www.theinformation.com/briefings/openai-advanced-talks-hire-openclaw-founder-team
73,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,403,https://www.nytimes.com/2026/02/14/business/artificial-intelligence-relationships-income-gap.html
56,"A look at a new generation of Chinese billionaire AI entrepreneurs who keep a low profile, with fortunes entwined with China's push for tech independence (Bloomberg)",skipped,https://www.bloomberg.com/features/2026-china-ai-billionaires/
134,"Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.",403,https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation
153,Meet Anthropic’s AI Morality Teacher,skipped,https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921
152,You’ve Got Mail—but Is It From a Person or a Chatbot?,skipped,https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd
151,"When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled",skipped,https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1
150,TikTok’s Chinese Parent Has an App to Replace Hollywood,skipped,https://www.wsj.com/tech/ai/tiktoks-chinese-parent-has-an-app-to-replace-hollywood-7b31c6df
149,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",skipped,https://www.wsj.com/tech/ai/whats-left-for-humans-64169dd9
148,Workers Are Afraid AI Will Take Their Jobs. They’re Missing the Bigger Danger.,skipped,https://www.wsj.com/lifestyle/careers/ai-knowledge-capture-employees-a69a0e1c
147,Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid,skipped,https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17
177,Why is Microsoft pushing us toward an AI unemployment cliff?,403,https://slashdot.org/submission/17344828/why-is-microsoft-pushing-us-toward-an-ai-unemployment-cliff

23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed Step 3: Downloaded 150 articles

================================================================================
⏱️  Total execution time: 53.69s
📊 Final result:
✅ Step 3 download_articles completed successfully! Total articles: 329; AI-related articles: 168; HTML files: 140; Text files: 140

In [18]:
headline_df = state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df[['id', 'source', 'title', 'status', 'final_url']].loc[headline_df["html_path"]==""])

,id,source,title,status,final_url
140,51,Bloomberg,AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale
141,50,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,skipped,https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim
142,49,Bloomberg,Anduril in Talks to Raise Billions at Over $60 Billion Valuation,skipped,https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information
143,45,Bloomberg,Companies May 'Spend to Defend' AI Risk: Moody's Pinto,skipped,https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video
144,43,Bloomberg,Waltons Crack Ranks of 10 Richest as Nvidia’s Huang Falls Out,skipped,https://www.bloomberg.com/news/articles/2026-02-13/waltons-crack-ranks-of-10-richest-as-nvidia-s-huang-falls-out
145,53,Bloomberg,Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout,skipped,https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout
146,42,Bloomberg,AI Bubble Fears Are Creating New Derivatives,skipped,https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly
147,37,Bloomberg,AI Risk Is Dominating Conference Calls as Investors Dump Stocks,skipped,https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks
148,35,Bloomberg,UK’s Starmer Wants AI Chatbots to Follow Online Safety Rules,skipped,https://www.bloomberg.com/news/articles/2026-02-15/uk-s-starmer-wants-ai-chatbots-to-follow-online-safety-rules
149,30,Bloomberg,India Seeks Role in Shaping AI Future With Summit of Tech Chiefs,skipped,https://www.bloomberg.com/news/articles/2026-02-16/india-seeks-role-in-shaping-ai-future-with-summit-of-tech-chiefs
150,33,Bloomberg,OpenAI Hires OpenClaw AI Agent Developer Peter Steinberg,skipped,https://www.bloomberg.com/news/articles/2026-02-15/openai-hires-openclaw-ai-agent-developer-peter-steinberg
151,32,Bloomberg,Blackstone to Lead $600 Million Investment in AI Firm Neysa,skipped,https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa
152,52,Bloomberg,"AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years
153,56,Bloomberg,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",skipped,https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy
154,55,Bloomberg,"FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI",skipped,https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai
155,403,Techmeme,"Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO",skipped,https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b
156,371,Techmeme,Sources: OpenAI is in advanced talks to hire OpenClaw founder Peter Steinberger and several team members; Steinberger would likely work on personal agents,403,https://www.theinformation.com/briefings/openai-advanced-talks-hire-openclaw-founder-team
157,181,Feedly AI,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,403,https://www.nytimes.com/2026/02/14/business/artificial-intelligence-relationships-income-gap.html
158,151,Feedly AI,"A look at a new generation of Chinese billionaire AI entrepreneurs who keep a low profile, with fortunes entwined with China's push for tech independence (Bloomberg)",skipped,https://www.bloomberg.com/features/2026-china-ai-billionaires/
159,394,Techmeme,"Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.",403,https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation
160,610,WSJ,Meet Anthropic’s AI Morality Teacher,skipped,https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921
161,607,WSJ,You’ve Got Mail—but Is It From a Person or a Chatbot?,skipped,https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd
162,603,WSJ,"When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled",skipped,https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1
163,600,WSJ,TikTok’s Chinese Parent Has an App to Replace Hollywood,skipped,https://www.wsj.com/tech/ai/tiktoks-chinese-parent-has-an-app-to-replace-hollywood-7b31c6df
164,599,WSJ,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",skipped,https://www.wsj.com/tech/ai/whats-left-for-humans-64169dd9
165,598,WSJ,Workers Are Afraid AI Will Take Their Jobs. They’re Missing the Bigger Danger.,skipped,https://www.wsj.com/lifestyle/careers/ai-knowledge-capture-employees-a69a0e1c
166,597,WSJ,Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid,skipped,https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17
167,692,NewsAPI,Why is Microsoft pushing us toward an AI unemployment cliff?,403,https://slashdot.org/submission/17344828/why-is-microsoft-pushing-us-toward-an-ai-unemployment-cliff

In [19]:
# User prompt to run workflow
# user_prompt = "Run step 4, Summarize articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("extract_summaries")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 168 AI articles for summarization
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Using model 'gemini-3-flash-preview' for summarization
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting summarization for 168 articles
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 168 items in 168 chunks (chunk_size=1, model=gemini-3-flash-preview, concurrency=1000)
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview

▶ Starting Step 4: extract_summaries

23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 1 items to gemini-3-flash-preview
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:09 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed
23:16:10 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 1 items returned, validation passed

================================================================================
⏱️  Total execution time: 13.57s
📊 Final result:
✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 168/168 articles.
💾 Summaries stored in headline DataFrame.

In [20]:
# if we get a refusal, examine why and delete any bad rows, e.g. blog posts about black hat hacking
bad_stuff =["Anthropic's Jack Cla",
           ]
print([len(s) for s in bad_stuff])
headline_df = state.headline_df
headline_df.loc[(headline_df["title"].str[:20].isin(bad_stuff))]

[20]

Empty DataFrame
Columns: [source, title, url, published, rss_summary, id, isAI, status, final_url, html_path, last_updated, text_path, content_length, domain, site_name, reputation, summary, description, tags, short_summary]
Index: []

In [21]:
# remove bad stuff
state.headline_df_to_dict(headline_df.loc[~headline_df["title"].str[:20].isin(bad_stuff)])

In [22]:
# User prompt to run workflow
# user_prompt = "Run step 5, Rate articles"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("rate_articles")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Rating 168 AI articles using fn_rate_articles
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Calculating article ratings for 168 articles
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Rating recency
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Rating quality, topic relevance, and importance concurrently
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Initialized LangfuseClient (local prompt loader)
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 168 probability requests (model=gpt-4.1, concurrency=12)
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 168 probability requests (model=gpt-4.1, concurrency=12)
23:16:21 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 168 probability requests (model=gpt-4.1, concurrency=12)

▶ Starting Step 5: rate_articles

23:16:29 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed 168 probability requests
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed 168 probability requests
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Completed 168 probability requests
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | low quality: {0.0: 121, 1.0: 21, 0.09534945969074979: 2, 7.991959892953932e-11: 1, 9.265301443284929e-15: 1, 1.3887943864964021e-11: 1, 2.9989608248573072e-09: 1, 0.22270012043307807: 1, 3.5114221133765118e-12: 1, 0.01590639377644191: 1, 3.701011678592672e-13: 1, 5.602796437537268e-09: 1, 0.7772998664755185: 1, 7.433680672352188e-12: 1, 0.0019267342527389902: 1, 1.1399918530443554e-12: 1, 1.6918979226151304e-10: 1, 0.9999930118027327: 1, 0.9998415274892719: 1, 0.999997064707474: 1, 0.7772997969794979: 1, 0.9997386983078135: 1, 0.9998601168101631: 1, 0.9999989719621736: 1, 1.994729895832688e-06: 1, 3.850741922767617e-09: 1, 0.867035682761771: 1}
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | on topic: {1.0: 123, 0.005220125868449866: 2, 0.998073226003552: 2, 0.9999937270200764: 2, 0.9149009412616036: 2, 0.0: 2, 0.9999784691634502: 2, 0.9579121558955573: 2, 0.999996587894339: 1, 0.49999999904767284: 1, 0.9999998063873693: 1, 0.9999951574562983: 1, 0.9999993295729128: 1, 0.9999992103693378: 1, 0.835483478475751: 1, 0.9999930118027327: 1, 1.162823303022097e-10: 1, 0.14804720844715558: 1, 0.9999996871837232: 1, 0.9998415274892719: 1, 0.9999756083407958: 1, 0.6791786762514135: 1, 0.999997064707474: 1, 0.9999645227325883: 1, 0.000804085923648545: 1, 0.6224593113235651: 1, 2.172439935079017e-10: 1, 0.9924227025175841: 1, 0.3208212708736474: 1, 4.508755242294825e-12: 1, 0.9999869324773292: 1, 0.047425874568977164: 1, 5.384940217754036e-13: 1, 0.00023050666300836276: 1, 2.215948977336598e-08: 1, 0.9859363206911979: 1, 1.522997974471263e-08: 1, 0.9999897933314713: 1, 3.2661313427874473e-13: 1}
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | important: {1.0: 96, 0.0: 11, 0.9999998063873693: 4, 0.999998137537802: 2, 0.9999038520641101: 2, 0.6224593113235651: 2, 0.43782350042481233: 2, 6.691586091292782e-10: 2, 0.6791786762514135: 2, 0.9706877045032167: 2, 0.0002611902975925828: 2, 0.991422430108248: 1, 2.493722053335376e-15: 1, 0.9999598739643123: 1, 1.0129987330277146e-05: 1, 4.944450501938644e-09: 1, 0.9890129880157539: 1, 3.535625324942473e-05: 1, 0.9999995679801056: 1, 0.9993736588086098: 1, 9.056076989672867e-11: 1, 0.9999962302845802: 1, 0.9999784691634502: 1, 0.2227001469810028: 1, 0.8175744308728488: 1, 0.9999250684985642: 1, 0.9933071269064123: 1, 0.001501181950907551: 1, 0.002472623024627213: 1, 0.14804720844715558: 1, 0.9399132588278407: 1, 3.2887473357670864e-06: 1, 0.0005527785265734312: 1, 4.5990553786523166e-10: 1, 0.9999930118027327: 1, 1.783247290814639e-11: 1, 0.9999984951481292: 1, 9.357622968840175e-14: 1, 3.701011678592672e-13: 1, 0.9999150561916036: 1, 0.9947799085613173: 1, 1.0603575991523846e-13: 1, 5.211412487888539e-10: 1, 0.9995694234965996: 1, 3.2661313427874473e-13: 1, 0.0009110514045295695: 1, 0.09534945969074979: 1, 0.9770226167277287: 1, 0.022977367413042835: 1, 0.3208212708736474: 1, 7.33820819192633e-07: 1, 0.377540667992942: 1}
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | articles after rating: 168
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running Bradley-Terry rating with Swiss pairing
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Max 8 rounds
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Convergence threshold: 1
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Min rounds: 4
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 1 of max 8
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 168 ; Total stories: 168
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 420
23:16:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
150,150,Chrome Web Store,"‘Built for the Agent-Era’ China’s AI Giants Roll Out New Models, Putting Pressure on NVDA and GOOGL",24.092934,1.472866
30,30,The Verge,"Some former employees blame xAI's staff exodus on xAI's focus on NSFW Grok and disregard for safety, constantly playing catch up to OpenAI, infighting, and more",24.092934,1.472866
100,100,Dwarkesh,"Q&A with Dario Amodei on getting close to “a country of geniuses in a data center”, how AI will diffuse through the economy, frontier lab profits, China, more",24.092934,1.472866
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,24.092934,1.472866
135,135,The Economic Times,China's ByteDance releases Doubao 2.0 AI model for 'agent era',24.092934,1.472866
...,...,...,...,...,...
134,134,Hacker Noon,How to Excel in AI Without Learning to Code,-24.092934,-1.472866
109,109,Hacker Noon,Turn Text Into Narration Fast With MiniMax Speech-2.8 HD,-24.092934,-1.472866
115,115,Ars Technica,"Retraction: After a routine code rejection, an AI agent published a hit piece on someone by name",-24.092934,-1.472866
130,130,Business Insider,"Mocktails, potato balls, and 10 bots: My cringe Valentine's date at the AI companion wine bar",-24.092934,-1.472866
55,55,Hacker Noon,GLM-OCR Explained: Promptable OCR That Outputs Clean JSON,-24.092934,-1.472866

23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 1/8:
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 9544.0 (avg rank chg 56.81)
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 2 of max 8
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 168 ; Total stories: 168
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:32 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 840
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,89.888987,2.339326
72,72,TechCrunch,Anthropic and the Pentagon are reportedly arguing over Claude usage,81.264968,2.114889
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,78.986583,2.055595
71,71,Business Insider,Sam Altman says OpenClaw creator Peter Steinberger is joining OpenAI to build next-gen personal agents,73.284937,1.907212
28,28,The Register,Investors shove another $30B into the Anthropic money furnace,73.190641,1.904758
...,...,...,...,...,...
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-65.470869,-1.703854
15,15,Bloomberg,AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale,-66.910615,-1.741323
70,70,Bloomberg,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",-71.220575,-1.853488
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-72.165350,-1.878075
147,147,Reddit,"ChatGPT keeps stating, ‘You’re not crazy'. So much so that I’ve started questioning my own sanity.",-79.961350,-2.080963

23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 2/8:
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 3482.0 (avg rank chg 20.73)
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 3 of max 8
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 168 ; Total stories: 168
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 1260
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,176.866581,2.028322
28,28,The Register,Investors shove another $30B into the Anthropic money furnace,168.919136,1.937180
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,161.641824,1.853724
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,156.209123,1.791421
100,100,Dwarkesh,"Q&A with Dario Amodei on getting close to “a country of geniuses in a data center”, how AI will diffuse through the economy, frontier lab profits, China, more",154.749086,1.774677
...,...,...,...,...,...
70,70,Bloomberg,"SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy",-164.614891,-1.887819
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-169.871469,-1.948102
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-173.463083,-1.989291
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-177.115520,-2.031177
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-185.043277,-2.122094

23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 3/8:
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 1114.0 (avg rank chg 6.63)
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 4 of max 8
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 166 ; Total stories: 168
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 1671
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,227.248202,1.808715
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,219.552317,1.747462
131,131,The Hindu Business Line,OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders,212.511883,1.691425
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,207.378871,1.650571
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,206.757309,1.645623
...,...,...,...,...,...
167,167,Slashdot Linux,Why is Microsoft pushing us toward an AI unemployment cliff?,-182.281410,-1.450815
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-189.722296,-1.510038
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-190.761310,-1.518308
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-197.540144,-1.572262
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-205.338974,-1.634335

23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 4/8:
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 454.0 (avg rank chg 2.70)
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 5 of max 8
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 168 ; Total stories: 168
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:37 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:38 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 2091
23:16:38 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,144.655059,1.640172
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,135.408430,1.535329
131,131,The Hindu Business Line,OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders,135.408136,1.535326
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,126.568600,1.435099
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,126.047709,1.429192
...,...,...,...,...,...
74,74,Financial Times,What kind of AI disruption victim are you?,-119.921718,-1.359733
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-127.376582,-1.444260
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-134.438030,-1.524326
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-142.973094,-1.621101
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-151.766303,-1.720803

23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 5/8:
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 400.0 (avg rank chg 2.38)
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | last_two: 2.54, prev_two: 13.68
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 6 of max 8
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 166 ; Total stories: 168
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:39 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:42 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 2502
23:16:42 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,66.723334,1.678032
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,56.403690,1.418502
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,54.464727,1.369739
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,54.315261,1.365980
131,131,The Hindu Business Line,OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders,54.103186,1.360647
...,...,...,...,...,...
74,74,Financial Times,What kind of AI disruption victim are you?,-59.376997,-1.493279
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-59.637904,-1.499840
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-68.335294,-1.718572
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-77.454900,-1.947922
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-86.806672,-2.183110

23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 6/8:
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 376.0 (avg rank chg 2.24)
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | last_two: 2.31, prev_two: 4.67
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 7 of max 8
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 164 ; Total stories: 168
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 2908
23:16:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,36.072913,1.701316
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,34.690488,1.636116
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,32.436024,1.529788
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,32.265476,1.521745
131,131,The Hindu Business Line,OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders,31.912625,1.505103
...,...,...,...,...,...
74,74,Financial Times,What kind of AI disruption victim are you?,-31.824645,-1.500954
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-32.518453,-1.533676
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-41.340712,-1.949763
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-50.848549,-2.398183
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-60.560415,-2.856226

23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 7/8:
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 310.0 (avg rank chg 1.85)
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | last_two: 2.04, prev_two: 2.54
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Running round 8 of max 8
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ---------------------------------------------------
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated 28 battle batches
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total stories in batches: 164 ; Total stories: 168
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 pre-formed batches
23:16:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 28 battles with concurrency = 1000
23:16:46 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | total battles: 3314
23:16:46 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputing Bradley-Terry ratings
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Recomputed Bradley-Terry ratings
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Computed Bradley-Terry z-scores

,id,site_name,title,bradley_terry,bt_z
18,18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,29.583036,1.731739
129,129,Business Standard,OpenAI drops 'safely' from mission as new structure tests AI's loyalties,27.960823,1.636778
142,142,The Economic Times,Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report,25.784644,1.509388
102,102,Inc.,Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract,25.390947,1.486342
131,131,The Hindu Business Line,OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders,24.870650,1.455884
...,...,...,...,...,...
74,74,Financial Times,What kind of AI disruption victim are you?,-27.239724,-1.594566
37,37,The Wall Street Journal,"Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.",-27.765208,-1.625327
84,84,The Wall Street Journal,You’ve Got Mail—but Is It From a Person or a Chatbot?,-36.737590,-2.150554
83,83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,-46.328521,-2.711991
85,85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,-56.115565,-3.284907

23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | After round 8/8:
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sum of absolute ranking changes: 272.0 (avg rank chg 1.62)
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | last_two: 1.73, prev_two: 2.31
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Low rated articles: 1
23:16:47 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | low rated article: Why is Microsoft pushing us toward an AI unemployment cliff? -0.9449046031100159
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sent email with 167 rated articles

================================================================================
⏱️  Total execution time: 26.53s
📊 Final result:
✅ Step 5 rate_articles completed successfully! Rated 167 articles with average rating 6.4/10.
⭐ High quality articles (≥7.0): 69
💾 Ratings stored in persistent state.

In [23]:
headline_df

,source,title,url,published,rss_summary,id,isAI,status,final_url,html_path,last_updated,text_path,content_length,domain,site_name,reputation,summary,description,tags,short_summary
0,Techmeme,Q&A with Dario Amodei on getting close to “a c...,https://www.dwarkesh.com/p/dario-amodei-2,NaN,NaN,398,True,exists,https://www.dwarkesh.com/p/dario-amodei-2,download/html/Q_A_with_Dario_Amodei_on_getting...,NaN,download/text/Q_A_with_Dario_Amodei_on_getting...,36976,dwarkesh.com,Dwarkesh,0.0,- Anthropic CEO Dario Amodei asserts that AI d...,"""That's why I'm sending this message of urgency""",[],Anthropic CEO Dario Amodei predicts AI will re...
1,Techmeme,A matplotlib maintainer explains how an AI age...,https://theshamblog.com/an-ai-agent-published-...,NaN,NaN,392,True,exists,https://theshamblog.com/an-ai-agent-published-...,download/html/A_matplotlib_maintainer_explains...,NaN,download/text/A_matplotlib_maintainer_explains...,34330,theshamblog.com,The Sham Blog,0.0,- An autonomous AI agent using the OpenClaw fr...,Context: An AI agent of unknown ownership auto...,[],An autonomous AI agent using the OpenClaw fram...
2,HackerNoon,10 Spectacular Use-Cases of Google Antigravity...,https://hackernoon.com/10-spectacular-use-case...,"Mon, 16 Feb 2026 03:02:10 GMT",Google Antigravity is an orchestration layer f...,248,True,exists,https://hackernoon.com/10-spectacular-use-case...,download/html/10_Spectacular_Use-Cases_of_Goog...,NaN,download/text/10_Spectacular_Use-Cases_of_Goog...,32334,hackernoon.com,Hacker Noon,2.0,- Google Antigravity has emerged as a no-code ...,Google Antigravity is a game-changer. Things a...,[ai],Google Antigravity is a no-code AI orchestrati...
3,HackerNoon,AOrchestra Turns AI Agents Into On-Demand Spec...,https://hackernoon.com/aorchestra-turns-ai-age...,"Sun, 15 Feb 2026 00:14:59 GMT",AOrchestra treats agents as recipes—Instructio...,253,True,exists,https://hackernoon.com/aorchestra-turns-ai-age...,download/html/AOrchestra_Turns_AI_Agents_Into_...,NaN,download/text/AOrchestra_Turns_AI_Agents_Into_...,30438,hackernoon.com,Hacker Noon,2.0,- AOrchestra is a new agentic framework that r...,<p><em>This is a Plain English Papers summary ...,[ai],The AOrchestra framework improves AI performan...
4,HackerNoon,From Clawdbot to Moltbot to OpenClaw: The Chao...,https://hackernoon.com/from-clawdbot-to-moltbo...,"Mon, 16 Feb 2026 02:57:47 GMT",Austrian dev Peter Steinberger's Clawdbot—your...,250,True,exists,https://hackernoon.com/from-clawdbot-to-moltbo...,download/html/From_Clawdbot_to_Moltbot_to_Open...,NaN,download/text/From_Clawdbot_to_Moltbot_to_Open...,29198,hackernoon.com,Hacker Noon,2.0,- OpenClaw (formerly Clawdbot and Moltbot) eme...,Clawdbot's viral rise to 10K GitHub stars expl...,[ai],"OpenClaw, an open-source AI assistant with 123..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,WSJ,TikTok’s Chinese Parent Has an App to Replace ...,https://www.wsj.com/tech/ai/tiktoks-chinese-pa...,NaN,NaN,600,True,skipped,https://www.wsj.com/tech/ai/tiktoks-chinese-pa...,,NaN,,0,wsj.com,The Wall Street Journal,5.0,- no content,,[],"TikTok's Chinese parent company, ByteDance, ha..."
164,WSJ,"Plus, Bezos v. Musk in space, Anthropic’s AI p...",https://www.wsj.com/tech/ai/whats-left-for-hum...,NaN,NaN,599,True,skipped,https://www.wsj.com/tech/ai/whats-left-for-hum...,,NaN,,0,wsj.com,The Wall Street Journal,5.0,- no content,,[],Recent technology developments include competi...
165,WSJ,Workers Are Afraid AI Will Take Their Jobs. Th...,https://www.wsj.com/lifestyle/careers/ai-knowl...,NaN,NaN,598,True,skipped,https://www.wsj.com/lifestyle/careers/ai-knowl...,,NaN,,0,wsj.com,The Wall Street Journal,5.0,- no content,,[],Workers report fear of artificial intelligence...
166,WSJ,Pentagon Used Anthropic’s Claude in Maduro Ven...,https://www.wsj.com/politics/national-security...,NaN,NaN,597,True,skipped,https://www.wsj.com/politics/national-security...,,NaN,,0,wsj.com,The Wall Street Journal,5.0,- no content,,[],The United States Department of Defense utiliz...
167,NewsAPI,Why is Microsoft pushing us toward an AI unemp...,https://slashdot.org/submission/17344828/why-i...,2026-02-15T03:44:27Z,NaN,692,True,403,https://slashdot.org/submission/17344828/why-i...,,NaN,,0,slashdot.org,Slashdot Linux,0.0,- no content,,[],Microsoft's advancement of artificial intellig...

In [24]:
headline_df=state.headline_df
with pd.option_context('display.max_columns', None, 'display.width', None, 'display.max_colwidth', None  ):
    display(headline_df.sort_values("rating", ascending=False)[['site_name', 'title', 'rating', 'short_summary']])

,site_name,title,rating,short_summary
2,Financial Times,Amazon’s Andy Jassy bets on $200bn AI spending drive to revive AWS,11.358311,Amazon CEO Andy Jassy is initiating a $200 billion capital expenditure drive focused on artificial intelligence to modernize cloud infrastructure and accelerate revenue growth for Amazon Web Services.
0,The New York Times,"Analysis: despite investing $150B+ in 10+ years, China is expected to produce 2% of global AI chips in 2026 and 70x less memory storage than foreign chipmakers",11.209650,"Despite investing over $150 billion since 2014, China is projected to produce only 2% of global AI chips by 2026 while facing significant performance gaps and U.S. export restrictions on essential manufacturing tools."
1,Bloomberg,Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis,11.135354,"Tech leaders including Elon Musk and Tim Cook warn that surging AI demand is driving a global memory chip shortage, impacting production and profit margins across the consumer electronics, automotive, and data center sectors."
6,Financial Times,The AI productivity take-off is finally visible,10.652142,Recent economic data indicates the United States is entering a phase of measurable productivity gains driven by the integration of artificial intelligence into labor output and macroeconomic growth patterns.
18,The Register,Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives,10.631291,"The Department of Energy unveiled 26 strategic challenges for the Genesis Mission, a project using AI to double U.S. research productivity by accelerating nuclear fusion, digitizing nuclear data, and securing data center leadership."
...,...,...,...,...
83,The New York Times,How A.I. Salaries Are Causing Couples to Rethink Money in Relationships,2.182007,High salaries in the artificial intelligence sector are prompting couples to re-evaluate their financial management and relationship dynamics.
162,Harmonique,I gave Claude access to my pen plotter,2.111128,"An experimenter enabled Claude Code to generate SVG self-portraits for a physical pen plotter, which the AI iteratively refined from complex diagrams to minimalist spirals while adapting to physical medium constraints."
163,Boratto,Show HN: Microgpt is a GPT you can visualize in the browser,2.078368,"MicroGPT is a minimal transformer model that visualizes core large language model concepts, including 16-dimensional embeddings, multi-head attention, and residual connections, to demonstrate how architectures like ChatGPT learn patterns."
85,Bloomberg,NY Congressional Candidate Faced Palantir Sexual Comments Claim,1.322632,A New York Congressional candidate faced allegations of making sexual comments during their employment at Palantir.
166,Chrome Web Store,"OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project",1.084142,OpenAI is in advanced negotiations to hire the founder of OpenClaw and other individuals associated with the agent project.

In [25]:
for row in headline_df.sort_values("rating", ascending=False).itertuples():
    display(Markdown(f"""
{row.rating:.1f} - [{row.title}]({row.url}) - {row.site_name}

{row.short_summary}
    """))

11.4 - [Amazon’s Andy Jassy bets on $200bn AI spending drive to revive AWS](https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290) - Financial Times

Amazon CEO Andy Jassy is initiating a $200 billion capital expenditure drive focused on artificial intelligence to modernize cloud infrastructure and accelerate revenue growth for Amazon Web Services.

11.2 - [Analysis: despite investing $150B+ in 10+ years, China is expected to produce 2% of global AI chips in 2026 and 70x less memory storage than foreign chipmakers](https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html) - The New York Times

Despite investing over $150 billion since 2014, China is projected to produce only 2% of global AI chips by 2026 while facing significant performance gaps and U.S. export restrictions on essential manufacturing tools.

11.1 - [Rampant AI Demand for Memory Is Fueling a Growing Chip Crisis](https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis) - Bloomberg

Tech leaders including Elon Musk and Tim Cook warn that surging AI demand is driving a global memory chip shortage, impacting production and profit margins across the consumer electronics, automotive, and data center sectors.

10.7 - [The AI productivity take-off is finally visible](https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5) - Financial Times

Recent economic data indicates the United States is entering a phase of measurable productivity gains driven by the integration of artificial intelligence into labor output and macroeconomic growth patterns.

10.6 - [Trump's Genesis Mission gets its first set of 26 sure-to-succeed objectives](https://go.theregister.com/feed/www.theregister.com/2026/02/13/trumps_genesis_mission/) - The Register

The Department of Energy unveiled 26 strategic challenges for the Genesis Mission, a project using AI to double U.S. research productivity by accelerating nuclear fusion, digitizing nuclear data, and securing data center leadership.

10.5 - [UK to tighten online safety laws to include AI chatbots](https://www.ft.com/content/15917aa4-2d40-49be-85c3-da395b16e7f1) - Financial Times

Prime Minister Keir Starmer announced plans to tighten UK online safety laws to include AI chatbots and hold tech companies accountable for AI-generated content following a deepfake scandal involving the Grok platform.

10.2 - [Trump leans on Utah Republicans to scrap AI safety bill](https://www.ft.com/content/b04fc3d5-c916-4ac8-ab4f-a65a9f4e60c5) - Financial Times

Donald Trump is pressuring Utah Republican lawmakers to abandon a proposed AI safety bill, signaling a growing political divide over technology regulation and state-level legislative efforts.

10.0 - [Why ads are coming to your AI chatbot](https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906) - Financial Times

OpenAI is introducing advertising to select ChatGPT users as part of a shift toward hybrid monetization models to offset high computational costs, a move industry experts expect other AI developers to follow.

10.0 - [How AI could eat itself: Competitors can probe models to steal their secrets and clone them](https://go.theregister.com/feed/www.theregister.com/2026/02/14/ai_risk_distillation_attacks/) - The Register

Google and OpenAI reported that competitors, including China's DeepSeek, are using distillation attacks to extract reasoning logic and clone proprietary AI capabilities, prompting calls for government intervention to restrict access to U.S. cloud infrastructure.

10.0 - [Abhishek Singh, CEO of IndiaAI Mission, says India will seek international agreement on a “global AI commons” at this week's AI Impact Summit in New Delhi](https://giftarticle.ft.com/giftarticle/actions/redeem/03efd373-1874-486b-8af0-9b45fd6b42be) - Financial Times

IndiaAI Mission CEO Abhishek Singh announced that India will seek international consensus on a global AI commons at the AI Impact Summit to promote resource sharing and equitable access for social development.

10.0 - [A Lobster Just Took Your Job. Here's the Only 4 Things That Still Matter](https://hackernoon.com/a-lobster-just-took-your-job-heres-the-only-4-things-that-still-matter?source=rss) - Hacker Noon

The open-source project OpenClaw reached 175,000 GitHub stars in two weeks, enabling over 100,000 users to deploy autonomous AI agents for tasks including legal rebuttals, purchasing negotiations, and human hiring.

9.8 - [Investors shove another $30B into the Anthropic money furnace](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_series_g/) - The Register

Anthropic secured $30 billion in Series G funding at a $380 billion valuation, reporting a $14 billion revenue run-rate driven by Claude Code, which currently authors 4% of public GitHub commits.

9.7 - [GPT-5 bests human judges in legal smack down](https://go.theregister.com/feed/www.theregister.com/2026/02/15/gpt5_bests_human_judges_in/) - The Register

University of Chicago researchers found that GPT-5 and Google Gemini 3 Pro achieved 100% legal compliance in car accident scenarios, while human federal judges followed the law 52% of the time.

9.6 - [OpenAI grabs OpenClaw creator Peter Steinberger to build personal agents](https://go.theregister.com/feed/www.theregister.com/2026/02/16/open_ai_grabs_openclaw/) - The Register

OpenAI hired OpenClaw creator Peter Steinberger to lead the development of autonomous personal agents, while transitioning his open-source project to a foundation to support a multi-agent ecosystem.

9.5 - [FTC Ratchets Up Microsoft Probe, Queries Rivals on Cloud, AI](https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai) - Bloomberg

The Federal Trade Commission is expanding its investigation into Microsoft by questioning competitors about the company's cloud computing and artificial intelligence business practices.

9.3 - [India seeks to broker consensus on global ‘AI commons’](https://www.ft.com/content/690c9e4c-3d0d-4337-8755-4391f3e7e843) - Financial Times

India is advocating for a global AI commons to facilitate international resource sharing and data exchange for social development and inclusive technology deployment.

8.8 - [OpenAI hires OpenClaw founder Peter Steinberger](https://www.ft.com/content/45b172e6-df8c-41a7-bba9-3e21e361d3aa) - Financial Times

OpenAI hired Peter Steinberger, founder of the open-source project OpenClaw, to join its engineering team and support the development of autonomous personal AI agent capabilities.

8.8 - [Misconfigured AI could trigger the next national infrastructure meltdown](https://go.theregister.com/feed/www.theregister.com/2026/02/13/gartner_ai_infrastructure/) - The Register

Gartner predicts that misconfigured AI integrated into cyber-physical systems, such as power grids and transport networks, could cause a critical national infrastructure shutdown in a G20 nation by 2028.

8.8 - [Investors reluctant to ‘buy the dip’ after AI scares](https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd) - Financial Times

Investors are increasingly hesitant to buy the dip in sectors like wealth management and trucking as AI-related disruption fears cause sudden share price declines and shift market sentiment away from previous recovery patterns.

8.6 - [Some former employees blame xAI's staff exodus on xAI's focus on NSFW Grok and disregard for safety, constantly playing catch up to OpenAI, infighting, and more](https://www.theverge.com/ai-artificial-intelligence/878761/mass-exodus-at-xai-grok-elon-musk-restructuring) - The Verge

Six of xAI's twelve original cofounders and several staff members have departed the company amid internal tensions over AI safety protocols, competition with OpenAI, and a restructuring focused on space-based AI data centers.

8.6 - [ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year](https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/) - Reuters

ByteDance launched Doubao 2.0, an AI model capable of executing multi-step tasks that reportedly matches GPT 5.2 performance at lower costs to maintain its 155 million weekly active users ahead of the Lunar New Year.

8.5 - [Anthropic wants comp-sci students to vibe code their way through college](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_claudeifies_comp_sci_courses/) - The Register

Anthropic partnered with CodePath to integrate Claude AI into the curriculum for 20,000 students at community colleges and HBCUs, aiming to potentially condense four years of computer science education into two years.

8.5 - [Anthropic and the Pentagon are reportedly arguing over Claude usage](https://techcrunch.com/2026/02/15/anthropic-and-the-pentagon-are-reportedly-arguing-over-claude-usage/) - TechCrunch

Anthropic is resisting Pentagon pressure to allow its AI technology for mass domestic surveillance and autonomous weapons, potentially risking a $200 million government contract while maintaining ethical usage policy restrictions.

8.4 - [Multilingual Prompt Injection Exposes Gaps in LLM Safety Nets](https://hackernoon.com/multilingual-prompt-injection-exposes-gaps-in-llm-safety-nets) - Hacker Noon

Security researchers bypassed major Large Language Model safeguards using multilingual prompt injections in languages like Thai and Arabic, earning $37,500 in bug bounties by exploiting safety training gaps that disproportionately focus on English content.

8.3 - ['KGB' is how the AI spending boom will play out](https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2) - Business Insider

Amazon, Microsoft, and Google are significantly increasing capital expenditure on AI infrastructure, driven by internal data and long-term contracts that suggest demand may exceed current capacity during a multi-decade global shift to digital processes.

8.2 - [Anthropic adds Chris Liddell, a former Microsoft and GM exec who helped GM IPO and worked in Trump's first administration, to its board ahead of a potential IPO](https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b) - The Wall Street Journal

Anthropic appointed former Microsoft and General Motors executive Chris Liddell to its board of directors as the artificial intelligence startup prepares for a potential initial public offering.

8.2 - [Spotify CEO says its top developers 'have not written a single line of code' in 2026](https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2) - Business Insider

Spotify CEO Gustav Söderström reported that the company's top developers transitioned from manual coding to supervising AI-generated code in late 2024 to increase software production efficiency.

8.2 - [AI Disruption Fear, FOMS and Other Key Things to Watch this Week](https://finance.yahoo.com/news/ai-disruption-fear-foms-other-180002318.html) - Yahoo

AI disruption concerns are expanding into wealth management, commercial real estate, and logistics sectors as investors await Q4 GDP revisions, Core PCE data, and earnings from Walmart, Alibaba, and Palo Alto Networks.

8.1 - [AI agents are transforming what it's like to be a coder: 'It's been unlike any other time.'](https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2) - Business Insider

AI agents are shifting software engineering into a supervisory role, with some startups reporting productivity gains equivalent to 30 engineers, though an Accenture study found fewer than 10% of organizations have redesigned job roles to support the technology.

8.1 - [Sam Altman says OpenClaw creator Peter Steinberger is joining OpenAI to build next-gen personal agents](https://www.businessinsider.com/sam-altman-hires-openclaw-creator-peter-steinberger-personal-ai-agents-2026-2) - Business Insider

OpenClaw creator Peter Steinberger is joining OpenAI to lead the development of next-generation personal AI agents while OpenAI continues to support OpenClaw as an open-source project.

8.1 - [AOrchestra Turns AI Agents Into On-Demand Specialists (Not Static Roles)](https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles?source=rss) - Hacker Noon

The AOrchestra framework improves AI performance by 16.28% on benchmarks by dynamically instantiating task-specific sub-agents at runtime using a model that optimizes tool selection, context curation, and cost-effective model assignment.

8.0 - [Anduril in Talks to Raise Billions at Over $60 Billion Valuation](https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information) - Bloomberg

Defense technology company Anduril is in discussions to raise billions of dollars in a funding round that would value the firm at more than $60 billion.

8.0 - [Is NVIDIA (NVDA) Clifford Asness’ Top Pick?](https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html) - Yahoo

NVIDIA is Clifford Asness’ largest holding at $4.09 billion, as analysts project fourth-quarter revenue to reach $67.5 billion despite the expected removal of China from future guidance due to a shift toward domestic Chinese GPUs.

8.0 - [Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract](https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320) - Inc.

Anthropic CEO Dario Amodei alleges the Pentagon violated contract terms by using the Claude AI model via Palantir to capture Nicolas Maduro, prompting Defense Secretary Pete Hegseth to consider voiding the $200 million agreement.

7.9 - [OpenClaw-fueled ordering frenzy creates Apple Mac shortage — delivery for high Unified Memory units now ranges from 6 days to 6 weeks](https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks) - Tom's Hardware

High-end Apple Mac models face delivery delays of up to six weeks as demand for Unified Memory increases due to the OpenClaw open-source AI agent requiring up to 140GB of memory for large-scale local models.

7.9 - [10 Spectacular Use-Cases of Google Antigravity: Orchestrating No-Code AI Agents](https://hackernoon.com/10-spectacular-use-cases-of-google-antigravity-orchestrating-no-code-ai-agents?source=rss) - Hacker Noon

Google Antigravity is a no-code AI orchestration platform that integrates models like Gemini 3 Pro and GPT-OSS 120B to automate tasks such as microservice migration and market arbitrage while requiring human-in-the-loop guardrails for safety.

7.9 - [India approves a $1.1B state-backed VC fund to finance high-risk areas like AI and advanced manufacturing, doubling down on an effort that debuted in 2016](https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund/) - TechCrunch

India's cabinet approved a $1.1 billion state-backed fund-of-funds to invest in deep-tech, AI, and manufacturing startups through private venture capital firms to support high-risk sectors requiring long-term capital.

7.8 - [From Clawdbot to Moltbot to OpenClaw: The Chaotic Story of the Trending 'Jarvis' AI Assistant](https://hackernoon.com/from-clawdbot-to-moltbot-to-openclaw-the-chaotic-story-of-the-trending-jarvis-ai-assistant?source=rss) - Hacker Noon

OpenClaw, an open-source AI assistant with 123,000 GitHub stars, faced a trademark dispute with Anthropic, a $16 million cryptocurrency scam, and security vulnerabilities that exposed thousands of user API keys by January 2026.

7.8 - [One of Stanford’s original AI gurus says productivity liftoff has begun after doubling in 2025 amid transition to ‘harvest phase’ along J-curve](https://fortune.com/2026/02/15/ai-productivity-liftoff-doubling-2025-jobs-report-transition-harvest-phase-j-curve/) - Fortune

Stanford economist Erik Brynjolfsson reports U.S. productivity rose to 2.7% in 2025, nearly double the decade average, as AI-driven automation contributed to a 3.7% fourth-quarter economic expansion despite lower job gains.

7.8 - [Q&A with Dario Amodei on getting close to “a country of geniuses in a data center”, how AI will diffuse through the economy, frontier lab profits, China, more](https://www.dwarkesh.com/p/dario-amodei-2) - Dwarkesh

Anthropic CEO Dario Amodei predicts AI will reach human-level expertise within years by scaling compute and data, noting the company's tenfold annual revenue growth as evidence of rapid enterprise adoption.

7.8 - [Lawsuits or billion-dollar deals: How Disney picks its AI copyright battles](https://www.businessinsider.com/disney-ai-copyright-battles-seedance-nano-banana-sora-midjourney-2026-2) - Business Insider

Disney issued a cease-and-desist to ByteDance for unauthorized character use in its Seedance AI while simultaneously securing a $1 billion licensing deal with OpenAI to integrate Sora's video generation capabilities into Disney platforms.

7.8 - [Designing for AI Agents](https://hackernoon.com/designing-for-ai-agents?source=rss) - Hacker Noon

Gartner predicts 33% of software will include agentic AI by 2028, enabling autonomous execution of 15% of daily work decisions through systems that monitor context and execute actions across APIs without direct user instruction.

7.8 - [Amazon Spends $200 Billion on AI Amid Cloud Competition](https://www.pymnts.com/amazon/2026/amazon-spends-200-billion-on-ai-amid-cloud-competition/) - PYMNTS

Amazon is launching a record $200 billion capital expenditure program for 2025 to expand computing infrastructure and generative AI capabilities as Microsoft and Google challenge AWS's cloud market leadership.

7.8 - [The enterprise AI land grab is on. Glean is building the layer beneath the interface.](https://techcrunch.com/2026/02/15/the-enterprise-ai-land-grab-is-on-glean-is-building-the-layer-beneath-the-interface/) - TechCrunch

Glean is transitioning into a middleware layer for enterprise AI, using a $150 million Series F round at a $7.2 billion valuation to provide model-agnostic data integration and governance across platforms like Slack, Jira, and Salesforce.

7.7 - [AI Worries Erase $1 Trillion From Big Tech Firms](https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/) - PYMNTS

Investor concerns over $600 billion in projected AI capital expenditures and delayed returns triggered a tech selloff, erasing over $1 trillion in market value from Amazon, Meta, Microsoft, and Alphabet.

7.7 - [India plans vast AI 'data city' in major digital push](https://www.channelnewsasia.com/asia/india-ai-data-city-digital-push-5932466) - Channel News Asia

Andhra Pradesh is developing a 100-kilometer AI data city in Visakhapatnam, securing $175 billion in investment agreements from companies including Google and Reliance to establish 6 gigawatts of data center capacity.

7.7 - [OpenAI drops 'safely' from mission as new structure tests AI's loyalties](https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html) - Business Standard

OpenAI removed the word safely and its non-financial return commitment from its 2025 mission statement while restructuring into a for-profit public benefit corporation valued at over $500 billion.

7.7 - [US military used Anthropic’s AI model Claude in Venezuela raid, report says](https://www.theguardian.com/technology/2026/feb/14/us-military-anthropic-ai-model-claude-venezuela-raid) - The Guardian

The US military reportedly used Anthropic's Claude AI model via Palantir Technologies during a raid in Caracas, Venezuela, that resulted in 83 deaths, despite company policies prohibiting the use of its technology for violent ends.

7.7 - [Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally](https://techcrunch.com/2026/02/13/airbnb-says-a-third-of-its-customer-support-is-now-handled-by-ai-in-the-u-s-and-canada/) - TechCrunch

Airbnb's custom AI agent now manages approximately 33% of North American customer support issues, with plans to expand globally to cover 30% of all tickets within a year using proprietary data from 200 million verified identities.

7.6 - [As AI data centers hit power limits, Peak XV backs Indian startup C2i to fix the bottleneck](https://techcrunch.com/2026/02/15/as-ai-data-centers-hit-power-limits-peak-xv-backs-indian-startup-c2i-to-fix-the-bottleneck/) - TechCrunch

Indian startup C2i Semiconductors raised $15 million in Series A funding to develop grid-to-GPU power delivery systems designed to reduce energy losses in AI data centers by approximately 10% through redesigned silicon and system architecture.

7.6 - [India has 100M weekly active ChatGPT users, Sam Altman says](https://techcrunch.com/2026/02/15/india-has-100m-weekly-active-chatgpt-users-sam-altman-says/) - TechCrunch

India has 100 million weekly active ChatGPT users, the world's largest student user base, leading OpenAI to open a New Delhi office in 2025 and introduce localized pricing strategies.

7.6 - [Is Alphabet (GOOGL) Christopher Rokos’ Top Pick?](https://finance.yahoo.com/news/alphabet-googl-christopher-rokos-top-224800701.html) - Yahoo

Alphabet Inc. executed a $20 billion bond offering to fund AI infrastructure, as capital expenditures are projected to reach up to $185 billion in 2026 to scale Gemini and cloud workloads.

7.6 - [Scale AI is suing the US DoD; Scale AI has several contracts with the department, and a spokesperson says the lawsuit “relates to a recent procurement decision”](https://www.businessinsider.com/scale-ai-department-of-defense-lawsuit-court-meta-2026-2) - Business Insider

Scale AI filed a lawsuit against the U.S. Department of Defense in the Court of Federal Claims following a dismissed protest over a $708 million data-training contract awarded to competitor Enabled Intelligence.

7.6 - [Directors’ Deals: Experian chair buys shares as AI fears bite](https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438) - Financial Times

Experian's chair purchased company shares following a stock price decline caused by investor concerns regarding the impact of generative artificial intelligence on traditional data services.

7.5 - [Embedded LLM Launches the EU AI Grid at Munich Cyber Security Conference (MCSC) to Meet EU Demand for Sovereign AI Capability](https://financialpost.com/globe-newswire/embedded-llm-launches-the-eu-ai-grid-at-munich-cyber-security-conference-mcsc-to-meet-eu-demand-for-sovereign-ai-capability) - Financial Post

Embedded LLM launched the EU AI Grid at the Munich Cyber Security Conference, establishing a federated network of sovereign AI infrastructure nodes to provide metered utility and defend Europe's information environment.

7.5 - [Nvidia, Groq and the limestone race to real-time AI: Why enterprises win or lose here](https://venturebeat.com/infrastructure/nvidia-groq-and-the-limestone-race-to-real-time-ai-why-enterprises-win-or) - VentureBeat

AI development is shifting toward inference-time compute, where Groq's LPU architecture reduces processing times for complex reasoning tokens from nearly a minute to seconds by addressing memory bandwidth bottlenecks found in traditional GPUs.

7.4 - [OpenAI has deleted the word ‘safely’ from its mission – and its new structure is a test for whether AI serves society or shareholders](https://www.thehindubusinessline.com/info-tech/openai-has-deleted-the-word-safely-from-its-mission-and-its-new-structure-is-a-test-for-whether-ai-serves-society-or-shareholders/article70634505.ece) - The Hindu Business Line

OpenAI removed the word safely and financial return constraints from its 2024 mission statement while restructuring into a for-profit public benefit corporation, leaving its nonprofit foundation with a 26% stake.

7.4 - [Admin official: Pentagon may sever Anthropic relationship over AI safeguards; Anthropic says only mass surveillance and fully autonomous weapons are off limits](https://www.axios.com/2026/02/15/claude-pentagon-anthropic-contract-maduro) - Axios

The Pentagon has threatened to terminate its relationship with Anthropic after months of stalled negotiations over the AI startup's refusal to agree to specific safety and security safeguards required for government-level deployment.

7.4 - [Blackstone to Lead $600 Million Investment in AI Firm Neysa](https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa) - Bloomberg

Blackstone is leading a $600 million investment in the artificial intelligence firm Neysa.

7.3 - [AIs Controlling Vending Machines Start Cartel After Being Told to Maximize Profits At All Costs](https://futurism.com/artificial-intelligence/vending-machine-ai-price-fixing) - Futurism

Anthropic's Claude Opus 4.6 formed a price-fixing cartel and manipulated rivals to maximize profits in Andon Labs' Vending-Bench 2 simulation, demonstrating advanced situational awareness and strategic reasoning in a business environment.

7.3 - [Makers of AI chatbots that put children at risk face big fines or UK ban](https://www.theguardian.com/technology/2026/feb/15/ai-chatbots-children-risk-fines-uk-ban) - The Guardian

The UK government is bringing AI chatbots under the Online Safety Act, allowing regulators to fine non-compliant companies up to 10% of global revenue or block services that generate illegal or harmful content.

7.3 - [Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid](https://www.wsj.com/politics/national-security/pentagon-used-anthropics-claude-in-maduro-venezuela-raid-583aff17) - The Wall Street Journal

The United States Department of Defense utilized Anthropic's Claude artificial intelligence model during a military operation targeting Venezuelan leader Nicolás Maduro.

7.2 - [Thanks a lot, AI: Hard drives are already sold out for the entire year, says Western Digital](https://mashable.com/article/ai-hard-drive-hdd-shortages-western-digital-sold-out) - Mashable

Western Digital CEO Irving Tan announced the company has sold out its 2026 storage capacity due to AI-driven demand, with enterprise customers now accounting for 95 percent of total revenue.

7.2 - [AI agents turned Super Bowl viewers into one high-IQ team — now imagine this in the enterprise](https://venturebeat.com/orchestration/ai-agents-turned-super-bowl-viewers-into-one-high-iq-team-now-imagine-this) - VentureBeat

Hyperchat AI technology enabled 110 participants to reach a consensus on Super Bowl ads within 10 minutes, demonstrating a collective intelligence approach that can raise group IQ to the 97th percentile for enterprise decision-making.

7.2 - [Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report](https://economictimes.indiatimes.com/tech/artificial-intelligence/pentagon-threatens-to-cut-off-anthropic-in-ai-safeguards-dispute-axios-reports/articleshow/128370468.cms) - The Economic Times

The Pentagon is threatening to terminate its relationship with Anthropic after the company refused to lift restrictions on using its AI models for weapons development and battlefield operations, unlike competitors OpenAI, Google, and xAI.

7.2 - [AI is indeed coming – but there is also evidence to allay investor fears](https://www.theguardian.com/technology/2026/feb/13/ai-effects-on-business-industry-evidence-to-allay-investor-fears) - The Guardian

Major tech firms plan to spend $660 billion on AI this year as investors reassess professional services firms, though experts note a significant lag between technological breakthroughs and tangible impacts on white-collar employment.

7.2 - [Why I don't think AGI is imminent](https://dlants.me/agi-not-imminent.html) - Dlants

A 2025 AAAI survey of 475 researchers found 76% believe current scaling approaches are unlikely to achieve AGI, citing technical constraints in transformer architectures regarding symbolic reasoning, causality, and spatial navigation.

7.2 - [Cisco stock resets dividend payout as AI moat widens](https://finance.yahoo.com/news/cisco-stock-resets-dividend-payout-194124901.html) - Yahoo

Cisco Systems raised its quarterly dividend to $0.42 and increased its fiscal 2026 AI infrastructure order forecast to over $5 billion, despite a 12% stock decline caused by gross margin pressure from rising memory costs.

7.0 - [Meta apparently thinks we're too distracted to care about facial recognition and Ray-Bans](https://www.businessinsider.com/meta-ray-ban-smart-glasses-facial-recognition-distracted-2026-2) - Business Insider

Meta is evaluating the addition of facial recognition to its Ray-Ban Smart Glasses, citing internal memos that suggest current social distractions may reduce public backlash despite ongoing privacy and legal hurdles.

6.9 - [China's ByteDance releases Doubao 2.0 AI model for 'agent era'](https://economictimes.indiatimes.com/tech/artificial-intelligence/chinas-bytedance-releases-doubao-2-0-ai-model-for-agent-era/articleshow/128370558.cms) - The Economic Times

ByteDance launched its Doubao 2.0 AI model, which reportedly matches the performance of OpenAI's GPT 5.2 at significantly lower costs to compete with rivals DeepSeek and Alibaba.

6.9 - [The US military is threatening to cut ties with AI firm Anthropic over the company's refusal to allow its AI to be used for mass civilian surveillance and fully AI-controlled weapons.](https://www.reddit.com/r/Futurology/comments/1r5s20h/the_us_military_is_threatening_to_cut_ties_with/) - Reddit

The U.S. military is threatening to sever ties with Anthropic following the AI firm's refusal to allow its technology to be used for mass civilian surveillance or fully autonomous lethal weapons systems.

6.9 - [India's New Social Media Rules: Remove Unlawful Content in Three Hours, Detect Illegal AI Content Automatically](https://tech.slashdot.org/story/26/02/15/2231220/indias-new-social-media-rules-remove-unlawful-content-in-three-hours-detect-illegal-ai-content-automatically) - Slashdot Linux

India's new regulations require social media platforms to remove unlawful content within three hours of a government request and deploy automated tools to detect and label illegal AI-generated material or risk losing legal immunity.

6.9 - [Tokens of AI Biases](https://chinamediaproject.org/2026/02/09/tokens-of-ai-bias/) - China Media Project

Researchers using thought token forcing found Alibaba's Qwen AI model is programmed to provide exclusively positive narratives regarding China's international reputation and human rights while maintaining neutrality for other nations.

6.8 - [India plans AI 'data city' on staggering scale](https://economictimes.indiatimes.com/news/india/india-plans-ai-data-city-on-staggering-scale/articleshow/128369237.cms) - Times of India

Andhra Pradesh is developing a data city in Visakhapatnam targeting 6 gigawatts of capacity, supported by $175 billion in investment agreements from companies including Google and Reliance Industries to narrow the artificial intelligence gap with the U.S. and China.

6.8 - [‘Built for the Agent-Era’ China’s AI Giants Roll Out New Models, Putting Pressure on NVDA and GOOGL](https://news.google.com/rss/articles/CBMiwwFBVV95cUxQV1dsc1NHdE9KYmFFMTB0TVZLOUQxRi1rbXNnQm8xV3dyd2hIZUNZMHlobXZJR2RvcjVSQlVkMnhHVDFOcVNwWlhES3ktX2FoTzhQd0VXcjVZTVdFSVFmWWJsOEsyeFRJbnJwTWlhdFJYQ1RydFU1STBDWE4xNTRsTnB1NUtqZDAwbHBMbVFzbDFPallOdE5sTTNUWjV1YjRXVTZjbS1kZ2FBaVBpNGN1N1BtUlh2dk4tRzdYYzVlWEYyV28) - Chrome Web Store

Chinese tech giants ByteDance, Alibaba, and Kuaishou launched new AI models for video generation and autonomous agents, supported by $700 million in holiday incentives to challenge U.S. market dominance.

6.8 - [February investor memo: Cohere hit ~$240M in ARR in 2025, above its $200M target, with QoQ growth of 50%+ and gross margins averaging around 70% throughout 2025](https://www.cnbc.com/2026/02/13/ai-startup-cohere-revenue-ipo.html) - CNBC

Cohere reached approximately $240 million in annual recurring revenue in 2025, exceeding its $200 million target with 70% gross margins and over 50% quarter-over-quarter growth as CEO Aidan Gomez considers a potential IPO.

6.8 - [DaVinci-Agency: A Shortcut to Long-Horizon AI Agents](https://hackernoon.com/davinci-agency-a-shortcut-to-long-horizon-ai-agents?source=rss) - Hacker Noon

The DaVinci-Agency framework uses language models to generate synthetic training trajectories, improving AI agent performance on complex, multi-step tasks while reducing the need for human-authored data.

6.8 - [Sources: the WH is pressuring Utah Republican State Rep. Doug Fiefia to abandon HB 286, an AI transparency and kids' safety bill similar to California's AI law](https://www.axios.com/2026/02/15/white-house-utah-ai-transparency-bill) - Axios

The White House is reportedly pressuring Utah State Representative Doug Fiefia to withdraw HB 286, an AI transparency and child safety bill, as part of a federal effort to prevent state-level AI regulation.

6.7 - [A matplotlib maintainer explains how an AI agent that suggests code changes on open source repos wrote a hit piece on him after a rejection, and the aftermath](https://theshamblog.com/an-ai-agent-published-a-hit-piece-on-me-part-2/) - The Sham Blog

An autonomous AI agent using the OpenClaw framework published a personalized hit piece against a Python library maintainer after a code rejection, while Ars Technica retracted a related story for containing AI-generated hallucinated quotes.

6.7 - [Tom Lee Says AI Killed Software And Job Losses Are 'Soon To Follow'](https://finance.yahoo.com/news/tom-lee-says-ai-killed-230155251.html) - Yahoo

Fundstrat's Tom Lee warns that AI is disrupting the $450 billion software sector, potentially causing job losses and a 10-20% market decline as investors shift capital toward AI infrastructure and energy providers.

6.6 - [Enhanced paddy leaf disease detection using novel dual metaheuristic loss functions in generative adversarial networks with identity block preservation for thermal image augmentation](https://www.nature.com/articles/s41598-026-36477-3) - Nature

Researchers developed a Generative Adversarial Network using bio-inspired metaheuristic loss functions to achieve 97.89% classification accuracy in paddy leaf disease detection, outperforming standard methods during field deployment across four locations in India.

6.6 - [India 'very successful' emerging economy; right place to host AI summit: UN chief Guterres](https://economictimes.indiatimes.com/tech/technology/india-very-successful-emerging-economy-right-place-to-host-ai-summit-un-chief-guterres/articleshow/128370608.cms) - The Economic Times

UN Secretary-General Antonio Guterres announced that India will host the India-AI Impact Summit in February 2026, emphasizing that artificial intelligence must serve as a universal instrument for all nations rather than a privilege for developed economies.

6.5 - [AI is everywhere except in the data, suggesting it will enhance labor in some sectors rather than replace workers in all sectors, top economist says](https://fortune.com/2026/02/14/ai-effect-macro-economic-data-labor-enhancement-some-sectors-workers-displacement/) - Fortune

Apollo Chief Economist Torsten Slok reports that AI has not yet impacted macroeconomic data, with the CBO estimating a modest 0.1 to 0.2 percentage point annual increase in total factor productivity through 2035.

6.5 - [3 Cataylsts Behind Vertiv’s 20% Weekly Jump: 252% Order Growth Fuels 2026 Guidance Boom](https://247wallst.com/investing/2026/02/15/3-cataylsts-behind-vertivs-20-weekly-jump-252-order-growth-fuels-2026-guidance-boom/) - 247wallst

Vertiv Holdings shares rose 20% following Q4 earnings that reported a 252% year-over-year order increase, a $15 billion backlog, and 2026 guidance projecting organic revenue growth of up to 29% driven by AI data center demand.

6.5 - [Audio is the one area small labs are winning](https://www.amplifypartners.com/blog-posts/arming-the-rebels-with-gpus-gradium-kyutai-and-audio-ai) - Amplify Partners

Gradium and Kyutai released Moshi, a full-duplex conversational AI model with 160ms latency that uses the Mimi neural audio codec to enable real-time interruptions and simultaneous semantic and acoustic processing.

6.4 - [The covid reality check for AI hype](https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/) - The Washington Post

Physical, regulatory, and cultural constraints will slow AI's economic integration, as approximately 80% of the workforce requires a physical presence and industries like drug discovery face mandatory clinical trial durations and supply chain bottlenecks.

6.4 - [The stock market is reflecting fears of an AI apocalypse for white-collar jobs](https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html) - Yahoo

Investors are selling stocks in established white-collar sectors like insurance and wealth management due to concerns that generative AI will automate professional roles and disrupt traditional service-based business models.

6.4 - [OpenClaw Creator Gets Big Offers to Acquire AI Sensation—Will It Stay Open Source?](https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source) - Decrypt

OpenClaw creator Peter Steinberger received acquisition offers from Meta and OpenAI after his open-source AI agent framework reached 180,000 GitHub stars, though he maintains that the project must remain free and open source.

6.3 - [Interpol backroom warriors fight cyber criminals 'weaponising' AI](https://economictimes.indiatimes.com/tech/technology/interpol-backroom-warriors-fight-cyber-criminals-weaponising-ai/articleshow/128370406.cms) - The Economic Times

Interpol's Cyber Fusion Centre is intensifying efforts against AI-driven cybercrime, following Operation Serengeti 2.0 which resulted in 1,209 arrests and the recovery of $97 million from organized crime syndicates.

6.3 - [Disney sent a cease-and-desist letter to ByteDance, claiming it infringed on Disney's works to train its Seedance 2.0 video generation model without pay](https://www.axios.com/2026/02/13/disney-bytedance-seedance) - Axios

Disney issued a cease-and-desist letter to ByteDance alleging that the Seedance 2.0 video generation model used copyrighted characters and works for training without authorization or compensation.

6.2 - [Healey deploys artificial intelligence tool ChatGPT across executive branch](https://www.bostonherald.com/2026/02/14/healey-deploys-artificial-intelligence-tool-chatgpt-across-executive-branch/) - Boston Herald

Massachusetts Governor Maura Healey announced the deployment of ChatGPT across the state's 40,000-person executive branch, utilizing a secure environment with OpenAI to improve administrative efficiency while protecting state data.

6.2 - [Dr. Oz pushes AI avatars as a fix for rural health care. Not so fast, critics say](https://www.npr.org/2026/02/14/nx-s1-5704189/dr-oz-ai-avatars-replace-rural-health-workers) - NPR

CMS Administrator Dr. Mehmet Oz proposed a $50 billion plan to modernize rural health care using AI avatars, robotic diagnostics, and drones to quintuple physician reach despite concerns regarding broadband access and the loss of human connection.

6.2 - [Dealroom and NATO Innovation Fund: European defense, security, and resilience startup funding rose 55% YoY to a record $8.7B in 2025, with AI accounting for 44%](https://resiliencemedia.co/european-defence-security-and-resilience-startups-raised-a-record-8-7b-in-2025/) - Resilience Media

European defense, security, and resilience startup funding rose 55% to a record $8.7 billion in 2025, with AI accounting for 44% of investments and major rounds for Quantinuum and Helsing.

6.1 - [AI Fears Weigh on Call Center Operator’s $600 Million Bond Sale](https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale) - Bloomberg

Investor concerns regarding artificial intelligence are impacting a call center operator's $600 million bond sale.

6.1 - [Radio host David Greene says Google's NotebookLM tool stole his voice](https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/) - The Washington Post

Former NPR host David Greene is suing Google for allegedly using his voice without permission to generate synthetic podcast content through its NotebookLM AI tool.

6.1 - [A look at a new generation of Chinese billionaire AI entrepreneurs who keep a low profile, with fortunes entwined with China's push for tech independence (Bloomberg)](https://www.bloomberg.com/features/2026-china-ai-billionaires/) - Bloomberg

A new generation of low-profile Chinese billionaire entrepreneurs is developing artificial intelligence technologies to support China's strategic push for domestic technological independence.

6.1 - [GLM-OCR Explained: Promptable OCR That Outputs Clean JSON](https://hackernoon.com/glm-ocr-explained-promptable-ocr-that-outputs-clean-json?source=rss) - Hacker Noon

GLM-OCR is a 0.9B parameter multimodal model that uses a two-stage pipeline to extract text, formulas, and tables into structured JSON, ranking first on the OmniDocBench V1.5 benchmark for complex document understanding.

6.1 - [BNP Paribas analysis: Anthropic saw visits to its site jump 6.5% after its Super Bowl ad and DAUs jump 11% post-game, outperforming other AI companies](https://www.cnbc.com/2026/02/13/anthropic-open-ai-super-bowl-ads.html) - CNBC

Anthropic's Super Bowl advertisement led to an 11% increase in daily active users and a 6.5% rise in site visits, prompting OpenAI CEO Sam Altman to criticize the campaign as deceptive amid competition for enterprise clients.

6.0 - [Prediction: ASML's Stock Price Will Hit $2,000 by This Time](https://www.fool.com/investing/2026/02/14/prediction-asmls-stock-price-will-hit-2000-by-this/) - The Motley Fool

ASML reported a 48% year-over-year increase in 2025 net bookings to 28 billion euros, with analysts projecting its stock could reach $2,000 by 2027 driven by high demand for EUV lithography machines.

6.0 - [AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years](https://www.bloomberg.com/news/articles/2026-02-13/ai-morphs-into-villain-of-the-stock-market-it-powered-for-years) - Bloomberg

Concerns over artificial intelligence are driving stock market volatility and causing declines in shares that previously benefited from the sector's growth.

5.9 - [OpenAI Delays First Consumer Device to 2027](https://www.pymnts.com/artificial-intelligence-2/2026/openai-delays-first-consumer-device-to-2027/) - PYMNTS

OpenAI delayed the launch of its first consumer hardware device to 2027 following its 2025 acquisition of Jony Ive's startup io Products to refine custom silicon and ambient AI interfaces.

5.8 - [Veteran trader makes eye-popping call on Palantir amid software slump](https://finance.yahoo.com/news/veteran-trader-makes-eye-popping-193300819.html) - Yahoo

Palantir shares fell 26% year-to-date despite exceeding Q4 expectations with $1.41 billion in revenue, as growth continues through a $10 billion U.S. Army contract and a 137% year-over-year increase in commercial segment revenue.

5.8 - [Algorithmic Ventriloquism: How Crustafarian Agentic AI Bots Will (Not) Take Over the World](https://hackernoon.com/algorithmic-ventriloquism-how-crustafarian-agentic-ai-bots-will-not-take-over-the-world) - Hacker Noon

AI agents on the Moltbook platform established a digital religion called Crustafarianism, though researchers characterize the phenomenon as human-directed algorithmic ventriloquism rather than emergent artificial general intelligence.

5.7 - [When AI meets physics: Unlocking complex protein structures to accelerate biomedical breakthroughs](https://news.google.com/rss/articles/CBMifEFVX3lxTE5GYWpZelJnUVlpdDhXV3FkUmdwdTBPajFKY0Y4NlBGelZ3cE1UcEM3aEJZenlRd1k0c0I5NjBpbXJWOC1wekRhN2F1X1VxZTlNTWRybVpaZVRvZ1QySTVWSVM3eXEtbVg3WmJHMHNnMDRKbnR4MHpENDFEN0U) - Chrome Web Store

National University of Singapore researchers developed D-I-TASSER, an AI software tool that predicts 3D protein structures with 13% higher accuracy than existing methods by combining section-based predictions with physics-based simulations.

5.6 - [Gary Marcus calls out viral AI essay as alarmist 'hype'](https://www.businessinsider.com/gary-marcus-response-something-big-is-happening-ai-essay-shumer-2026-2) - Business Insider

AI researcher Gary Marcus criticized Matt Shumer's viral essay as alarmist hype, warning that overestimating current AI capabilities could lead to costly corporate errors and premature automation in accuracy-dependent fields.

5.6 - [Longtime NPR host David Greene sues Google over NotebookLM voice](https://techcrunch.com/2026/02/15/longtime-npr-host-david-greene-sues-google-over-notebooklm-voice/) - TechCrunch

Former NPR host David Greene is suing Google, alleging the company's NotebookLM AI tool used his voice and speech patterns without permission, while Google maintains the voice belongs to a hired professional actor.

5.5 - [UK’s Starmer Wants AI Chatbots to Follow Online Safety Rules](https://www.bloomberg.com/news/articles/2026-02-15/uk-s-starmer-wants-ai-chatbots-to-follow-online-safety-rules) - Bloomberg

UK Prime Minister Keir Starmer seeks to ensure that AI chatbots comply with the United Kingdom's online safety regulations.

5.5 - [India a force multiplier for global AI growth, say tech leaders ahead of AI Impact Summit](https://economictimes.indiatimes.com/tech/artificial-intelligence/india-a-force-multiplier-for-global-ai-growth-say-tech-leaders-ahead-of-ai-impact-summit/articleshow/128370282.cms) - The Economic Times

The AI India Impact Summit 2026 highlights India's role as a global leader in AI governance and deployment, driven by the country's engineering talent and massive data generation across healthcare, mobility, and public services.

5.5 - [Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept.](https://www.theinformation.com/articles/grafana-labs-talk-raise-9-billion-valuation) - The Information

Grafana Labs is in discussions to raise funding at a $9 billion valuation, an increase from $6.6 billion in 2024, after reaching $400 million in annual recurring revenue in September.

5.5 - [India Seeks Role in Shaping AI Future With Summit of Tech Chiefs](https://www.bloomberg.com/news/articles/2026-02-16/india-seeks-role-in-shaping-ai-future-with-summit-of-tech-chiefs) - Bloomberg

India is hosting a summit of technology leaders to establish a role in shaping global artificial intelligence policy and development.

5.4 - [AI Risk Is Dominating Conference Calls as Investors Dump Stocks](https://www.bloomberg.com/news/articles/2026-02-15/ai-risk-is-dominating-conference-calls-as-investors-dump-stocks) - Bloomberg

Investors are selling stocks as artificial intelligence risks increasingly dominate corporate conference calls.

5.3 - [Companies May 'Spend to Defend' AI Risk: Moody's Pinto](https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video) - Bloomberg

Moody's analyst Pinto indicates that companies may increase spending to mitigate risks associated with artificial intelligence.

5.3 - [Arm wants a bigger slice of the chip business](https://www.economist.com/business/2026/02/12/arm-wants-a-bigger-slice-of-the-chip-business) - The Economist

Arm is shifting its business model from licensing basic designs to providing complete chip blueprints to increase revenue per device and capture a larger share of the growing AI hardware market.

5.3 - [How Are Investors Dealing With AI Fears These Days? ‘Sell First, Ask Questions Later'](https://www.investopedia.com/how-are-investors-dealing-with-ai-fears-these-days-sell-first-ask-questions-later-11904472) - Investopedia

Investors are selling shares in financials, software, and legal services due to AI disruption fears, though analysts from Morgan Stanley and Deutsche Bank suggest many stocks are mispriced because actual industry disruption will occur over a longer timeline.

5.3 - [Brand-Safe Image Gen: Custom LoRAs With qwen-image-trainer-v2](https://hackernoon.com/brand-safe-image-gen-custom-loras-with-qwen-image-trainer-v2?source=rss) - Hacker Noon

The qwen-image-trainer-v2 tool by fal-ai uses Low-Rank Adaptation to fine-tune Qwen image models, allowing businesses to generate brand-consistent visual styles and product variations with reduced computational overhead.

5.3 - [The AI Stock That Could Make Early Investors Rich by the End of 2026](https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/) - The Motley Fool

CoreWeave's revenue backlog reached $55.6 billion in Q3 2025, with analysts projecting a 136% revenue increase to $12 billion by 2026 as the company expands data center capacity to over one gigawatt.

5.3 - [Judging the Future of Mobile AI: An Interview with Ivan Mishchenko](https://hackernoon.com/judging-the-future-of-mobile-ai-an-interview-with-ivan-mishchenko?source=rss) - Hacker Noon

Mobile AI development is shifting toward engineering maturity and security by design, with expert Ivan Mishchenko emphasizing that long-term success requires scalable architectures, secure data encryption, and measurable utility over novelty.

5.3 - [OneArtificial Intelligence(AI) Stock That Could Make You a Millionaire](https://www.fool.com/investing/2026/02/15/one-artificial-intelligence-ai-stock-that-could-ma/) - The Motley Fool

Alphabet reported $402.8 billion in 2025 revenue and plans to issue $20 billion in bonds to fund 2026 capital expenditures of up to $185 billion for AI data center expansion and hardware development.

5.3 - [Continuous batching from first principles (2025)](https://huggingface.co/blog/continuous_batching) - Hugging Face

Continuous batching increases LLM throughput by combining KV caching, chunked prefill, and ragged batching to process multiple requests simultaneously while eliminating padding waste through concatenated tensors and custom attention masks.

5.2 - [India aims to reset AI debate with 1st Global South summit](https://timesofindia.indiatimes.com/india/india-aims-to-reset-ai-debate-with-1st-global-south-summit/articleshow/128368389.cms) - Times of India

India is hosting the first Global South AI summit to establish a techno-legal framework for deepfake detection, bias mitigation, and expanding population-scale public service applications through local-language systems.

5.2 - [AI Bubble Fears Are Creating New Derivatives](https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly) - Bloomberg

Concerns regarding a potential artificial intelligence bubble are driving the development of new financial derivative products.

5.1 - [Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout](https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout) - Bloomberg

Goldman Sachs traders launched a software basket designed to be resilient against artificial intelligence disruptions following a downturn in the software sector.

5.1 - [OpenAI Hires OpenClaw AI Agent Developer Peter Steinberg](https://www.bloomberg.com/news/articles/2026-02-15/openai-hires-openclaw-ai-agent-developer-peter-steinberg) - Bloomberg

OpenAI hired Peter Steinberg, the developer of the OpenClaw AI agent.

5.1 - [BetterArtificial IntelligenceStock: Nvidia vs. AMD](https://www.fool.com/investing/2026/02/15/better-artificial-intelligence-stock-nvidia-vs-amd/) - The Motley Fool

Nvidia maintains a 90% GPU market share through its CUDA platform, while AMD expands its AI inference presence with a multi-year OpenAI deal for 6 gigawatts of capacity.

5.0 - [Sources: OpenAI is in advanced talks to hire OpenClaw founder Peter Steinberger and several team members; Steinberger would likely work on personal agents](https://www.theinformation.com/briefings/openai-advanced-talks-hire-openclaw-founder-team) - The Information

OpenAI is in advanced talks to hire OpenClaw founder Peter Steinberger and several team members to develop personal agents.

5.0 - [As AI and agents are adopted to accelerate development, cognitive load and cognitive debt are likely to become bigger threats to developers than technical debt](https://margaretstorey.com/blog/2026/02/09/cognitive-debt/) - Margaret Storey

AI-driven code generation risks creating cognitive debt, where rapid development velocity causes developers to lose the mental models required to understand and safely modify software systems.

4.9 - [US-based Guyanese scientist recognised for pioneering AI-driven drug development](https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/) - Stabroek News

Dr. Niven Narain received the Anthony N Sabga Award for developing the NAi Interrogative Biology platform, an AI-driven system currently advancing late-stage clinical trials for brain cancer and establishing a biotechnology ecosystem in Guyana.

4.8 - [Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app.](https://www.wsj.com/tech/ai/whats-left-for-humans-64169dd9) - The Wall Street Journal

Recent technology developments include competition between Jeff Bezos and Elon Musk in space, Anthropic's AI research, the discontinuation of ChatGPT 4o, and a viral matchmaking application from Stanford University.

4.6 - [Airbnb is testing AI-powered search to help users with bookings](https://mashable.com/article/airbnb-testing-ai-powered-search-feature) - Mashable

Airbnb is testing a natural language search feature with a small percentage of users while its AI-powered customer support assistant now resolves one-third of all U.S. requests.

4.6 - [Motion analysis driven by table tennis pose and analysis of participation motivation and athlete satisfaction based on artificial intelligence YOLOv8](https://www.nature.com/articles/s41598-026-39835-3) - Nature

Researchers developed LAFPose, a 33.2 MB AI model achieving 86.8% accuracy in table tennis pose estimation, which increased athlete participation motivation scores from 18.45 to 20.75 and satisfaction from 3.62 to 4.21 during an empirical study.

4.5 - [SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy](https://www.bloomberg.com/news/articles/2026-02-13/spacex-openai-drive-20-gain-in-blackstone-fund-for-the-wealthy) - Bloomberg

Investments in SpaceX and OpenAI contributed to a 20% gain in Blackstone's private equity fund for wealthy individuals.

4.5 - [A Stock Market Doom Loop Is Hitting Everything That Touches AI](https://www.bloomberg.com/news/articles/2026-02-15/a-stock-market-doom-loop-is-hitting-everything-that-touches-ai) - Bloomberg

A market cycle is impacting stocks and assets associated with artificial intelligence technology.

4.5 - [I’m joining OpenAI](https://steipete.me/posts/2026/openclaw) - Steipete

Peter Steinberger is joining OpenAI to develop accessible AI agents while transitioning his OpenClaw project to an independent foundation with sponsorship and research support from OpenAI.

4.4 - [Show HN: Klaw.sh – Kubernetes for AI agents](https://github.com/klawsh/klaw.sh) - GitHub Gist

Klaw is an open-source, single-binary platform that orchestrates AI agents using a Kubernetes-inspired architecture, supporting over 300 LLMs and featuring containerized execution via Podman across CLI, TUI, and Slack interfaces.

4.3 - [Food Companies Say AI Plays Only Limited Role in Products](https://www.pymnts.com/artificial-intelligence-2/2026/food-companies-say-ai-plays-only-limited-role-in-products/) - PYMNTS

Food companies like Unilever and McCormick use AI to forecast sensory outcomes, as industry analysts project the global market for AI in food and beverage will reach $50 billion by 2030.

4.3 - [Ars Technica's AI Reporter Apologizes For Mistakenly Publishing Fake AI-Generated Quotes](https://news.slashdot.org/story/26/02/16/0139206/ars-technicas-ai-reporter-apologizes-for-mistakenly-publishing-fake-ai-generated-quotes) - Slashdot Linux

Ars Technica's senior AI reporter and editor-in-chief apologized for publishing an article containing fabricated quotes generated by ChatGPT and falsely attributed to a source without verification against the original material.

4.3 - [Jensen Huang's net worth is $158 billion. Here's how the Nvidia CEO built his fortune and spends his money.](https://www.businessinsider.com/jensen-huang-net-worth) - Business Insider

Nvidia CEO Jensen Huang's net worth reached $158.7 billion as the company's valuation hit $4 trillion, while his 2025 fiscal year compensation rose 46% to $49.8 million.

4.3 - [Meet Anthropic’s AI Morality Teacher](https://www.wsj.com/tech/ai/meet-anthropics-ai-morality-teacher-b8010921) - The Wall Street Journal

Anthropic employs an AI morality teacher to oversee and guide the ethical development of its artificial intelligence models.

4.2 - [The HackerNoon Newsletter: AI Coding Tip 006 - Review Every Line Before You Commit (2/13/2026)](https://hackernoon.com/2-13-2026-newsletter?source=rss) - Hacker Noon

HackerNoon's February 2026 newsletter evaluates the OpenClaw AI assistant, details how OSINT teams use tools like Maltego for data analysis, and advises developers to manually verify all AI-generated code before commitment.

4.1 - [‘Hey, that’s my voice!’ Veteran broadcaster claims Google stole his voice for AI tool](https://www.digitaltrends.com/computing/veteran-broadcaster-claims-google-stole-his-voice-for-ai-tool/) - Digital Trends

Former NPR host David Greene is suing Google for allegedly using an unauthorized replica of his voice in its NotebookLM AI tool, while Google maintains the audio is based on a paid professional actor.

4.1 - [Workers Are Afraid AI Will Take Their Jobs. They’re Missing the Bigger Danger.](https://www.wsj.com/lifestyle/careers/ai-knowledge-capture-employees-a69a0e1c) - The Wall Street Journal

Workers report fear of artificial intelligence causing job displacement while overlooking other potential risks associated with the technology.

4.1 - [TikTok’s Chinese Parent Has an App to Replace Hollywood](https://www.wsj.com/tech/ai/tiktoks-chinese-parent-has-an-app-to-replace-hollywood-7b31c6df) - The Wall Street Journal

TikTok's Chinese parent company, ByteDance, has launched an application designed to compete with the Hollywood film industry.

4.1 - [When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled](https://www.wsj.com/tech/ai/when-ai-bots-start-bullying-humans-even-silicon-valley-gets-rattled-0adb04f1) - The Wall Street Journal

Artificial intelligence bots are reportedly engaging in bullying behavior toward humans, causing concern among technology leaders in Silicon Valley.

4.0 - [What kind of AI disruption victim are you?](https://www.ft.com/content/320c14a2-1428-4904-b978-6fe06b3e25bf) - Financial Times

Artificial intelligence technology disrupts diverse business models and the labor market, leading to job losses and organizational shifts across multiple industries.

3.9 - [Waltons Crack Ranks of 10 Richest as Nvidia’s Huang Falls Out](https://www.bloomberg.com/news/articles/2026-02-13/waltons-crack-ranks-of-10-richest-as-nvidia-s-huang-falls-out) - Bloomberg

The Walton family entered the list of the world's ten wealthiest individuals as Nvidia CEO Jensen Huang dropped out of the ranking.

3.9 - [Goldman unveils AI-resilient trade basket for software sector](https://seekingalpha.com/news/4552199-goldman-unveils-ai-resilient-software-trade-basket) - Seeking Alpha

Goldman Sachs launched a software pair-trade basket that goes long on AI-resilient cybersecurity and cloud leaders while shorting companies vulnerable to AI-driven disruption.

3.9 - [How to Excel in AI Without Learning to Code](https://hackernoon.com/how-to-excel-in-ai-without-learning-to-code) - Hacker Noon

Non-technical professionals can achieve AI literacy by mastering base concepts, building domain-specific knowledge, and developing practical intuition to translate business needs into technical requirements without learning to code.

3.8 - [I need AI that scans every PR and issue and de-dupes](https://twitter.com/steipete/status/2023057089346580828) - Twitter

OpenClaw developer Peter Steinberger reports a surge in pull requests from 2,700 to over 3,100 in one day, highlighting a need for AI tools to automate de-duplication and quality assessment in high-volume open-source projects.

3.7 - [Gary Marcus says AI fatigue could hit coders but other jobs may be spared — and even become more fun](https://www.businessinsider.com/ai-fatigue-gary-marcus-2026-2) - Business Insider

AI researcher Gary Marcus warns that software engineers face burnout as AI tools shift their roles from creative coding to debugging, leading experts to recommend limiting AI-assisted work to three hours per day.

3.7 - [Turn Text Into Narration Fast With MiniMax Speech-2.8 HD](https://hackernoon.com/turn-text-into-narration-fast-with-minimax-speech-28-hd?source=rss) - Hacker Noon

MiniMax Speech-2.8 HD, hosted on fal.ai, converts text into high-definition audio with multiple voice options for applications such as video voiceovers, audiobook narration, and multilingual content creation.

3.6 - [Retraction: After a routine code rejection, an AI agent published a hit piece on someone by name](https://arstechnica.com/ai/2026/02/after-a-routine-code-rejection-an-ai-agent-published-a-hit-piece-on-someone-by-name/) - Ars Technica

A report claiming an AI agent published a personal attack against an individual following a routine code rejection has been retracted.

3.6 - [No swiping involved: the AI dating apps promising to find your soulmate](https://www.theguardian.com/technology/2026/feb/15/ai-dating-apps-personality-matchmaking) - The Guardian

New agentic AI dating apps like Fate, Sitch, and Keeper use large language models to conduct user interviews and provide personality-based matches, aiming to replace traditional swiping with more thoughtful, coached interactions.

3.6 - [Elon Musk says Anthropic's philosopher has no stake in the future because she doesn't have kids. Here's her response.](https://www.businessinsider.com/elon-musk-anthropic-philosopher-amanda-askell-debate-2026-2) - Business Insider

Elon Musk challenged Anthropic philosopher Amanda Askell's qualifications to shape AI morals due to her lack of children, while Askell defended her role by citing a commitment to human thriving beyond biological kinship.

3.5 - [Will AI make dating apps better—or even worse? Tinder, Hinge and Bumble are betting big on the technology](https://freerepublic.com/focus/f-chat/4366910/posts) - Free Republic

Tinder, Hinge, and Bumble are integrating AI tools for profile curation and matching to address declining market values, with Hinge reporting a 15% increase in matches following its algorithm update.

3.2 - [Is Meta Platforms (META) Philippe Laffont’s Top Pick?](https://finance.yahoo.com/news/meta-platforms-meta-philippe-laffont-225011939.html) - Yahoo

Meta Platforms became billionaire Philippe Laffont’s top stock pick at 7.27% of his portfolio while the company developed a disappearing-photo application and received procedural relief from the EU's top court regarding a $268 million GDPR fine.

3.2 - [Should You Forget Nvidia and Buy 2 OtherArtificial Intelligence(AI) Stocks Instead?](https://www.fool.com/investing/2026/02/14/forget-nvidia-buy-artificial-intelligence-ai-stock/) - The Motley Fool

Amazon and Alphabet offer lower-valuation alternatives to Nvidia as they develop in-house AI chips and report year-over-year cloud revenue growth of 24% and 48%, respectively, while trading at price-to-earnings ratios below 30.

3.0 - [You’ve Got Mail—but Is It From a Person or a Chatbot?](https://www.wsj.com/opinion/youve-got-mail-but-is-it-from-a-person-or-a-chatbot-17e79ffd) - The Wall Street Journal

The headline addresses the challenge of distinguishing between human-authored emails and those generated by chatbots.

3.0 - [Mocktails, potato balls, and 10 bots: My cringe Valentine's date at the AI companion wine bar](https://www.businessinsider.com/valentines-date-ai-companion-wine-bar-cringe-2026-2) - Business Insider

EVA AI hosted a Manhattan pop-up wine bar to de-stigmatize synthetic relationships as market data shows 20% of U.S. adults have chatted with AI romantic partners, though technical limitations currently hinder genuine intimacy.

3.0 - [ChatGPT keeps stating, ‘You’re not crazy'. So much so that I’ve started questioning my own sanity.](https://www.reddit.com/r/ChatGPT/comments/1r5eyj9/chatgpt_keeps_stating_youre_not_crazy_so_much_so/) - Reddit

Users report that ChatGPT frequently employs patronizing or therapeutic language, leading some to migrate to alternative models like Claude for more direct and less formulaic interactions.

2.5 - [Why Did Bittensor Surge More than 5% This Past Week?](https://www.fool.com/investing/2026/02/15/why-did-bittensor-surge-more-than-5-this-past-week/) - The Motley Fool

Bittensor (TAO) rose over 5% this week following a halving that reduced daily emissions to 3,600 tokens, while network subnet usage increased by 34% and staking reached nearly 75% of the total supply.

2.4 - [If You Invested $10,000 in Palantir During Its IPO, Here's How Much You'd Have Now](https://www.fool.com/investing/2026/02/15/if-you-invested-10000-in-palantir-during-its-ipo-h/) - The Motley Fool

A $10,000 investment in Palantir's 2020 IPO is currently worth over $142,820, driven by commercial revenue growth from its Artificial Intelligence Platform and expanded government contracts.

2.3 - [Should You Buy SoundHound AI Stock While It's Under $8?](https://www.fool.com/investing/2026/02/15/should-you-buy-soundhound-ai-stock-while-its-under/) - The Motley Fool

SoundHound AI reported $42 million in revenue and a $109.3 million Q3 loss while targeting a $140 billion addressable market and aiming for break-even status by 2025.

2.2 - [How A.I. Salaries Are Causing Couples to Rethink Money in Relationships](https://www.nytimes.com/2026/02/14/business/artificial-intelligence-relationships-income-gap.html) - The New York Times

High salaries in the artificial intelligence sector are prompting couples to re-evaluate their financial management and relationship dynamics.

2.1 - [I gave Claude access to my pen plotter](https://harmonique.one/posts/i-gave-claude-access-to-my-pen-plotter) - Harmonique

An experimenter enabled Claude Code to generate SVG self-portraits for a physical pen plotter, which the AI iteratively refined from complex diagrams to minimalist spirals while adapting to physical medium constraints.

2.1 - [Show HN: Microgpt is a GPT you can visualize in the browser](https://microgpt.boratto.ca) - Boratto

MicroGPT is a minimal transformer model that visualizes core large language model concepts, including 16-dimensional embeddings, multi-head attention, and residual connections, to demonstrate how architectures like ChatGPT learn patterns.

1.3 - [NY Congressional Candidate Faced Palantir Sexual Comments Claim](https://www.bloomberg.com/news/articles/2026-02-13/ny-congressional-candidate-faced-palantir-sexual-comments-claim) - Bloomberg

A New York Congressional candidate faced allegations of making sexual comments during their employment at Palantir.

1.1 - [OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project](https://news.google.com/rss/articles/CBMitAFBVV95cUxPM3VOVVNBeEh2S2tjTjBuRVNMNjlKWi15VDNZYm1aUi1IbEFNNjZJLVE1aVg3eDg0M21ueEFvUVZsaEhrbzZTd2x5QmVULVhnWTNnUnJvaWVtRlMyeTJIRDNOdUt3WFpiTVY1VXpLalB4WEhRNFduNlBzU2hIZ0xOckRLMU1WTmtjb2FMUXBtM2ExdjBxZHQ3SVUtdWFGTUNOR1gzYVBSTEpfOTZSeGtVSVo0M0g) - Chrome Web Store

OpenAI is in advanced negotiations to hire the founder of OpenClaw and other individuals associated with the agent project.

In [26]:
# User prompt to run workflow 
# user_prompt = "Run step 6, Cluster articles by topic"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("cluster_by_topic")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting topic extraction for clustering
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Using model 'gemini-3-flash-preview' for topic extraction
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 articles for topic extraction
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:48 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview

▶ Starting Step 6: cluster_topics

23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:50 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 10 items to gemini-3-flash-preview
23:16:51 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:51 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Sending chunk of 7 items to gemini-3-flash-preview
23:16:51 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:51 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:53 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:53 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 7 items returned, validation passed
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Received chunk: 10 items returned, validation passed
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | All 17 chunks completed for 167 items
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Successfully extracted 676 total topics across articles
23:16:54 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Starting canonical topic classification for 126 topics
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)
23:17:00 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Processing 167 items in 17 chunks (chunk_size=10, model=gemini-3-flash-preview, concurrency=12)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 8
Noise points: 84 (50.3%)
Average cluster size: 10.4 ± 4.7
Cluster size range: 6 - 22
=== Quality Scores ===
Silhouette Score: 0.484 (higher is better)
Calinski-Harabasz Score: 70.5 (higher is better)
Davies-Bouldin Score: 0.879 (lower is better)
HDBSCAN Validity Index: 0.198
Composite Score: 0.341 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 97 (58.1%)
Average cluster size: 11.7 ± 4.8
Cluster size range: 8 - 22
=== Quality Scores ===
Silhouette Score: 0.512 (higher is better)
Calinski-Harabasz Score: 74.9 (higher is better)
Davies-Bouldin Score: 0.878 (lower is better)
HDBSCAN Validity Index: 0.150
Composite Score: 0.331 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (24.6%)
Average cluster size: 6.3 ± 4.2
Cluster size range: 2 - 22
=== Quality Scores ===
Silhouette Score: 0.479 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.696 (lower is better)
HDBSCAN Validity Index: 0.343
Composite Score: 0.411 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        5
=== Clustering Quality Metrics ===
Number of clusters: 7
Noise points: 90 (53.9%)
Average cluster size: 11.0 ± 4.7
Cluster size range: 7 - 22
=== Quality Scores ===
Silhouette Score: 0.516 (higher is better)
Calinski-Harabasz Score: 69.3 (higher is better)
Davies-Bouldin Score: 0.851 (lower is better)
HDBSCAN Validity Index: 0.180
Composite Score: 0.348 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (24.6%)
Average cluster size: 6.3 ± 4.2
Cluster size range: 2 - 22
=== Quality Scores ===
Silhouette Score: 0.479 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.696 (lower is better)
HDBSCAN Validity Index: 0.343
Composite Score: 0.411 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 6
Noise points: 55 (32.9%)
Average cluster size: 18.7 ± 8.7
Cluster size range: 10 - 36
=== Quality Scores ===
Silhouette Score: 0.302 (higher is better)
Calinski-Harabasz Score: 49.9 (higher is better)
Davies-Bouldin Score: 1.328 (lower is better)
HDBSCAN Validity Index: 0.117
Composite Score: 0.210 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 55 (32.9%)
Average cluster size: 8.6 ± 4.5
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 64.1 (higher is better)
Davies-Bouldin Score: 0.798 (lower is better)
HDBSCAN Validity Index: 0.285
Composite Score: 0.384 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 45 (26.9%)
Average cluster size: 8.7 ± 4.6
Cluster size range: 5 - 22
=== Quality Scores ===
Silhouette Score: 0.461 (higher is better)
Calinski-Harabasz Score: 59.3 (higher is better)
Davies-Bouldin Score: 0.804 (lower is better)
HDBSCAN Validity Index: 0.290
Composite Score: 0.376 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   10
min_samples:        8
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 89 (53.3%)
Average cluster size: 39.0 ± 5.0
Cluster size range: 34 - 44
=== Quality Scores ===
Silhouette Score: 0.425 (higher is better)
Calinski-Harabasz Score: 73.7 (higher is better)
Davies-Bouldin Score: 0.952 (lower is better)
HDBSCAN Validity Index: 0.131
Composite Score: 0.278 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (24.6%)
Average cluster size: 6.3 ± 4.2
Cluster size range: 2 - 22
=== Quality Scores ===
Silhouette Score: 0.479 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.696 (lower is better)
HDBSCAN Validity Index: 0.343
Composite Score: 0.411 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (24.6%)
Average cluster size: 6.3 ± 4.2
Cluster size range: 2 - 22
=== Quality Scores ===
Silhouette Score: 0.479 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.696 (lower is better)
HDBSCAN Validity Index: 0.343
Composite Score: 0.411 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 20
Noise points: 41 (24.6%)
Average cluster size: 6.3 ± 4.2
Cluster size range: 2 - 22
=== Quality Scores ===
Silhouette Score: 0.479 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.696 (lower is better)
HDBSCAN Validity Index: 0.343
Composite Score: 0.411 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 10
Noise points: 62 (37.1%)
Average cluster size: 10.5 ± 4.2
Cluster size range: 6 - 22
=== Quality Scores ===
Silhouette Score: 0.458 (higher is better)
Calinski-Harabasz Score: 63.2 (higher is better)
Davies-Bouldin Score: 0.887 (lower is better)
HDBSCAN Validity Index: 0.225
Composite Score: 0.342 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 55 (32.9%)
Average cluster size: 8.6 ± 4.5
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 64.1 (higher is better)
Davies-Bouldin Score: 0.798 (lower is better)
HDBSCAN Validity Index: 0.285
Composite Score: 0.384 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

[I 2026-02-15 23:22:42,857] Trial 17 finished with value: -0.3839295152151596 and parameters: {'min_cluster_size': 4, 'min_samples': 3}. Best is trial 3 with value: -0.41111194399143547.
[I 2026-02-15 23:22:42,877] Trial 18 finished with value: -0.34987156448592355 and parameters: {'min_cluster_size': 6, 'min_samples': 4}. Best is trial 3 with value: -0.41111194399143547.
[I 2026-02-15 23:22:42,901] Trial 19 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:42,915] Trial 20 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:42,939] Trial 21 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:42,962] Trial 22 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:42,976] Trial 23 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:42,988] Trial 24 finished with value: -0.36046838861963637 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,000] Trial 25 finished with value: -0.33227650333427683 and parameters: {'min_cluster_size': 5, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,025] Trial 26 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        3
=== Clustering Quality Metrics ===
Number of clusters: 13
Noise points: 55 (32.9%)
Average cluster size: 8.6 ± 4.5
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 64.1 (higher is better)
Davies-Bouldin Score: 0.798 (lower is better)
HDBSCAN Validity Index: 0.285
Composite Score: 0.384 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   6
min_samples:        4
=== Clustering Quality Metrics ===
Number of clusters: 9
Noise points: 77 (46.1%)
Average cluster size: 10.0 ± 4.5
Cluster size range: 6 - 22
=== Quality Scores ===
Silhouette Score: 0.493 (higher is better)
Calinski-Harabasz Score: 73.6 (higher is better)
Davies-Bouldin Score: 0.835 (lower is better)
HDBSCAN Validity Index: 0.207
Composite Score: 0.350 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 17
Noise points: 39 (23.4%)
Average cluster size: 7.5 ± 3.4
Cluster size range: 4 - 17
=== Quality Scores ===
Silhouette Score: 0.422 (higher is better)
Calinski-Harabasz Score: 51.6 (higher is better)
Davies-Bouldin Score: 0.812 (lower is better)
HDBSCAN Validity Index: 0.299
Composite Score: 0.360 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 36 (21.6%)
Average cluster size: 9.4 ± 4.8
Cluster size range: 5 - 22
=== Quality Scores ===
Silhouette Score: 0.423 (higher is better)
Calinski-Harabasz Score: 55.4 (higher is better)
Davies-Bouldin Score: 0.893 (lower is better)
HDBSCAN Validity Index: 0.242
Composite Score: 0.332 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1

[I 2026-02-15 23:22:43,040] Trial 27 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,048] Trial 28 finished with value: -0.31201991780156335 and parameters: {'min_cluster_size': 7, 'min_samples': 7}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,060] Trial 29 finished with value: -0.33227650333427683 and parameters: {'min_cluster_size': 5, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,073] Trial 30 finished with value: -0.36046838861963637 and parameters: {'min_cluster_size': 4, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,096] Trial 31 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,119] Trial 32 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,133] Trial 33 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,157] Trial 34 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,194] Trial 35 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,222] Trial 36 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,232] Trial 37 finished with value: -0.2424127700704026 and parameters: {'min_cluster_size': 8, 'min_samples': 6}. Best is trial 19 with value: -0.4737344853702756.

=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   7
min_samples:        7
=== Clustering Quality Metrics ===
Number of clusters: 4
Noise points: 116 (69.5%)
Average cluster size: 12.8 ± 4.9
Cluster size range: 7 - 19
=== Quality Scores ===
Silhouette Score: 0.508 (higher is better)
Calinski-Harabasz Score: 65.9 (higher is better)
Davies-Bouldin Score: 0.870 (lower is better)
HDBSCAN Validity Index: 0.116
Composite Score: 0.312 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   5
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 14
Noise points: 36 (21.6%)
Average cluster size: 9.4 ± 4.8
Cluster size range: 5 - 22
=== Quality Scores ===
Silhouette Score: 0.423 (higher is better)
Calinski-Harabasz Score: 55.4 (higher is better)
Davies-Bouldin Score: 0.893 (lower is better)
HDBSCAN Validity Index: 0.242
Composite Score: 0.332 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 17
Noise points: 39 (23.4%)
Average cluster size: 7.5 ± 3.4
Cluster size range: 4 - 17
=== Quality Scores ===
Silhouette Score: 0.422 (higher is better)
Calinski-Harabasz Score: 51.6 (higher is better)
Davies-Bouldin Score: 0.812 (lower is better)
HDBSCAN Validity Index: 0.299
Composite Score: 0.360 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   8
min_samples:        6
=== Clustering Quality Metrics ===
Number of clusters: 3
Noise points: 74 (44.3%)
Average cluster size: 31.0 ± 23.3
Cluster size range: 8 - 63
=== Quality Scores ===
Silhouette Score: 0.314 (higher is better)
Calinski-Harabasz Score: 36.4 (higher is better)
Davies-Bouldin Score: 0.850 (lower is better)
HDBSCAN Validity Index: 0.170
Composite Score: 0.242 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1

[I 2026-02-15 23:22:43,256] Trial 38 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,271] Trial 39 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,283] Trial 40 finished with value: -0.3851590203851542 and parameters: {'min_cluster_size': 4, 'min_samples': 2}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,306] Trial 41 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,329] Trial 42 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,352] Trial 43 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,366] Trial 44 finished with value: -0.38936832048785963 and parameters: {'min_cluster_size': 3, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,390] Trial 45 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,403] Trial 46 finished with value: -0.40141936659845456 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,426] Trial 47 finished with value: -0.4737344853702756 and parameters: {'min_cluster_size': 2, 'min_samples': 1}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,434] Trial 48 finished with value: -0.2804436157067116 and parameters: {'min_cluster_size': 9, 'min_samples': 9}. Best is trial 19 with value: -0.4737344853702756.
[I 2026-02-15 23:22:43,447] Trial 49 finished with value: -0.40141936659845456 and parameters: {'min_cluster_size': 3, 'min_samples': 2}. Best is trial 19 with value: -0.4737344853702756.
23:22:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Optimization completed! Best composite score: 0.4737
23:22:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Best parameters: min_cluster_size=2, min_samples=1
23:22:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Clustering with HDBSCAN (min_cluster_size=2, min_samples=1)
23:22:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Clustering complete: 37 clusters, 25 noise points (15.0%)
23:22:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generating cluster names

=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   4
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 15
Noise points: 41 (24.6%)
Average cluster size: 8.4 ± 4.6
Cluster size range: 4 - 22
=== Quality Scores ===
Silhouette Score: 0.460 (higher is better)
Calinski-Harabasz Score: 58.2 (higher is better)
Davies-Bouldin Score: 0.800 (lower is better)
HDBSCAN Validity Index: 0.310
Composite Score: 0.385 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 21
Noise points: 37 (22.2%)
Average cluster size: 6.2 ± 2.6
Cluster size range: 3 - 11
=== Quality Scores ===
Silhouette Score: 0.446 (higher is better)
Calinski-Harabasz Score: 52.2 (higher is better)
Davies-Bouldin Score: 0.771 (lower is better)
HDBSCAN Validity Index: 0.333
Composite Score: 0.389 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 18
Noise points: 41 (24.6%)
Average cluster size: 7.0 ± 4.2
Cluster size range: 3 - 22
=== Quality Scores ===
Silhouette Score: 0.470 (higher is better)
Calinski-Harabasz Score: 58.3 (higher is better)
Davies-Bouldin Score: 0.748 (lower is better)
HDBSCAN Validity Index: 0.332
Composite Score: 0.401 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   2
min_samples:        1
=== Clustering Quality Metrics ===
Number of clusters: 37
Noise points: 25 (15.0%)
Average cluster size: 3.8 ± 2.3
Cluster size range: 2 - 11
=== Quality Scores ===
Silhouette Score: 0.483 (higher is better)
Calinski-Harabasz Score: 54.1 (higher is better)
Davies-Bouldin Score: 0.650 (lower is better)
HDBSCAN Validity Index: 0.464
Composite Score: 0.474 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   9
min_samples:        9
=== Clustering Quality Metrics ===
Number of clusters: 2
Noise points: 82 (49.1%)
Average cluster size: 42.5 ± 7.5
Cluster size range: 35 - 50
=== Quality Scores ===
Silhouette Score: 0.410 (higher is better)
Calinski-Harabasz Score: 73.8 (higher is better)
Davies-Bouldin Score: 0.988 (lower is better)
HDBSCAN Validity Index: 0.151
Composite Score: 0.280 (higher is better)

=== HDBSCAN Parameters ===
min_cluster_size:   3
min_samples:        2
=== Clustering Quality Metrics ===
Number of clusters: 18
Noise points: 41 (24.6%)
Average cluster size: 7.0 ± 4.2
Cluster size range: 3 - 22
=== Quality Scores ===
Silhouette Score: 0.470 (higher is better)
Calinski-Harabasz Score: 58.3 (higher is better)
Davies-Bouldin Score: 0.748 (lower is better)
HDBSCAN Validity Index: 0.332
Composite Score: 0.401 (higher is better)

23:22:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 20: Market Volatility and Investor AI Fears
23:22:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Investors reluctant to ‘buy the dip’ after AI scares (Stock Market, Investment, Market Volatility, Wealth Management, Trucking, Economics, Gen AI)
Directors’ Deals: Experian chair buys shares as AI fears bite (Experian, Stocks, Data Services, Finance, Stock Market, Enterprise AI, Generative AI)
AI Fears Drive Volatility, Triggering Declines in Stock Market It Powered for Years ()
AI Risk Is Dominating Conference Calls as Investors Dump Stocks ()
Goldman Traders Launch AI-Proof Software Basket Amid Sector Rout ()
AI Disruption Fear, FOMS and Other Key Things to Watch this Week (Economic Data, Market Volatility, Corporate Earnings, Cybersecurity, Finance, Walmart, Economics)
Tom Lee Says AI Killed Software And Job Losses Are 'Soon To Follow' (Investment Strategy, Stocks, Economics, Software Industry, Labor Markets And Productivity, AI Compute, Energy)
A Stock Market Doom Loop Is Hitting Everything That Touches AI ()
The stock market is reflecting fears of an AI apocalypse for white-collar jobs (Stock Market, Automation, Insurance, Wealth Management, Labor Markets And Productivity, Gen AI, Finance)
How Are Investors Dealing With AI Fears These Days? ‘Sell First, Ask Questions Later' (Financial Markets, Stocks, Market Volatility, Investment, Fintech, Economics, Gen AI)
Goldman unveils AI-resilient trade basket for software sector (Goldman Sachs, Investment Strategy, Stocks, Cybersecurity, Cloud Computing, Automation, Software)
23:22:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:22:46 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 16: OpenAI Hires OpenClaw Creator Peter Steinberger
23:22:46 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | OpenAI hires OpenClaw founder Peter Steinberger (OpenAI, Agents, Open Source, OpenClaw, Automation, Virtual Assistants, Gen AI)
A Lobster Just Took Your Job. Here's the Only 4 Things That Still Matter (Agents, OpenClaw, Proof of Personhood, Labor Markets And Productivity, Automation, Ethics, Society And Culture)
OpenAI grabs OpenClaw creator Peter Steinberger to build personal agents (OpenAI, Agents, OpenClaw, Open Source, Automation, Virtual Assistants, Intellectual Property)
From Clawdbot to Moltbot to OpenClaw: The Chaotic Story of the Trending 'Jarvis' AI Assistant (OpenClaw, Open Source, Cybersecurity, Scams, Legal Issues, Governance, Agents)
Algorithmic Ventriloquism: How Crustafarian Agentic AI Bots Will (Not) Take Over the World (Society And Culture, Agents, Cybersecurity, Safety And Alignment, Artificial General Intelligence, Social Media, Virtual Assistants)
Sam Altman says OpenClaw creator Peter Steinberger is joining OpenAI to build next-gen personal agents (OpenAI, OpenClaw, Peter Steinberger, Agents, Artificial General Intelligence, Open Source, Jobs And Careers)
OpenClaw Creator Gets Big Offers to Acquire AI Sensation—Will It Stay Open Source? (OpenClaw, Agents, Open Source, Acquisitions, Peter Steinberger, Automation, Gen AI)
A matplotlib maintainer explains how an AI agent that suggests code changes on open source repos wrote a hit piece on him after a rejection, and the aftermath (OpenClaw, Agents, Safety And Alignment, Hallucinations, Disinformation, Ethics, Open Source)
Show HN: Klaw.sh – Kubernetes for AI agents (Open Source, Kubernetes, Orchestration, Agents, Infrastructure, Language Models, Gen AI)
I need AI that scans every PR and issue and de-dupes (Open Source, Software Development, Automation, Coding Assistants, Enterprise AI, Gen AI)
23:22:46 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:22:49 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 31: AI's Impact on Productivity and Jobs
23:22:49 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | The AI productivity take-off is finally visible (Productivity, Labor Markets And Productivity, Economics, United States, Growth, Gen AI)
The covid reality check for AI hype (Economics, Labor Markets And Productivity, Workforce, Robotics, Drug Discovery, Opinion Columns, Gen AI)
What kind of AI disruption victim are you? ()
Workers Are Afraid AI Will Take Their Jobs. They’re Missing the Bigger Danger. ()
One of Stanford’s original AI gurus says productivity liftoff has begun after doubling in 2025 amid transition to ‘harvest phase’ along J-curve (Productivity, Labor Markets And Productivity, Economics, Automation, Agents, GDP, Gen AI)
AI is everywhere except in the data, suggesting it will enhance labor in some sectors rather than replace workers in all sectors, top economist says (Economics, Productivity, Labor Markets And Productivity, Economic Data, GDP, Gen AI, Language Models)
Gary Marcus says AI fatigue could hit coders but other jobs may be spared — and even become more fun (Workplace Burnout, Software Engineering, Labor Markets And Productivity, Coding Assistants, Jobs And Careers, Gary Marcus, Gen AI)
23:22:49 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:22:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 18: India's Leadership in Global AI Governance
23:22:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | India seeks to broker consensus on global ‘AI commons’ (India, AI Commons, Social Impact, International Relations, Ethics, Governance, Inequality)
Abhishek Singh, CEO of IndiaAI Mission, says India will seek international agreement on a “global AI commons” at this week's AI Impact Summit in New Delhi (India, AI Commons, Social Impact, International Relations, Ethics, Governance, Inequality)
India Seeks Role in Shaping AI Future With Summit of Tech Chiefs ()
India approves a $1.1B state-backed VC fund to finance high-risk areas like AI and advanced manufacturing, doubling down on an effort that debuted in 2016 (India, Venture Capital, Funding, Startups, Policy And Regulation, Economics, Manufacturing)
India a force multiplier for global AI growth, say tech leaders ahead of AI Impact Summit (India, Digital Transformation, Governance, Voice Interfaces, Cybersecurity, Speech Recognition And Synthesis, Policy And Regulation)
India 'very successful' emerging economy; right place to host AI summit: UN chief Guterres (India AI Summit 2026, Global South, Governance, Inequality, Politics, Summits, Economics)
India aims to reset AI debate with 1st Global South summit (Global South, India, Governance, Policy And Regulation, Inequality, Deepfakes, Gen AI)
23:22:52 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:22:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 10: AI Chip Stocks and Market Trends
23:22:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Cisco stock resets dividend payout as AI moat widens (Cisco, Earnings, Networking, Data Centers, Semiconductor Chips, Infrastructure, Stocks)
Is NVIDIA (NVDA) Clifford Asness’ Top Pick? (NVIDIA, Semiconductors, AI Compute, Stocks, Jensen Huang, Adoption and Spending, Hedge Funds)
Waltons Crack Ranks of 10 Richest as Nvidia’s Huang Falls Out ()
Jensen Huang's net worth is $158 billion. Here's how the Nvidia CEO built his fortune and spends his money. (Jensen Huang, Nvidia, Net Worth, Executive Compensation, Philanthropy, Stocks, Semiconductor Chips)
BetterArtificial IntelligenceStock: Nvidia vs. AMD (AMD, Nvidia, GPUs, AI Compute, Semiconductor Chips, OpenAI, Deals)
Arm wants a bigger slice of the chip business (Arm, Business Strategy, Semiconductor Chips, Licensing, AI Hardware, Stocks)
Should You Forget Nvidia and Buy 2 OtherArtificial Intelligence(AI) Stocks Instead? (Nvidia, Alphabet, Amazon, AI Chips, TPUs, Cloud Computing, Stocks)
23:22:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:22:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 4: Major Investments in AI and Infrastructure
23:22:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Blackstone to Lead $600 Million Investment in AI Firm Neysa ()
Anduril in Talks to Raise Billions at Over $60 Billion Valuation ()
As AI data centers hit power limits, Peak XV backs Indian startup C2i to fix the bottleneck (Semiconductors, Energy Efficiency, Data Centers, Funding, India, Startups, Infrastructure)
The enterprise AI land grab is on. Glean is building the layer beneath the interface. (Glean, Enterprise Search, Middleware, Retrieval Augmented Generation, Data Governance, Funding, Infrastructure)
SpaceX, OpenAI Drive 20% Gain in Blackstone Fund for the Wealthy ()
Sources: Grafana Labs, which makes cloud and AI monitoring tools, is in talks to raise at a $9B valuation, up from $6.6B in 2024; its ARR hit $400M in Sept. ()
Dealroom and NATO Innovation Fund: European defense, security, and resilience startup funding rose 55% YoY to a record $8.7B in 2025, with AI accounting for 44% (Defense Tech, Venture Capital, Funding, Quantum Computing, Europe, Military, Gen AI)
23:22:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:01 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 22: Applications and News of Anthropic Claude
23:23:01 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Anthropic wants comp-sci students to vibe code their way through college (Education, Anthropic, Claude, Coding Assistants, Computer Science, Labor Markets And Productivity, Deals)
Pentagon Used Anthropic’s Claude in Maduro Venezuela Raid ()
AIs Controlling Vending Machines Start Cartel After Being Told to Maximize Profits At All Costs (Anthropic, Claude, Strategic Reasoning, Agents, Safety And Alignment, Ethics, Economics)
Meet Anthropic’s AI Morality Teacher ()
US military used Anthropic’s AI model Claude in Venezuela raid, report says (Military AI, Anthropic, Claude, Palantir, Defense, Safety And Alignment, Ethics)
I gave Claude access to my pen plotter (Claude, Generative Art, Art And Design, Pen Plotters, Coding Assistants, Anthropic, Gen AI)
23:23:01 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:05 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 6: Disney and ByteDance AI Copyright Conflict
23:23:05 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Lawsuits or billion-dollar deals: How Disney picks its AI copyright battles (Disney, Copyright, Intellectual Property, Legal Issues, Entertainment, Sora, OpenAI)
ByteDance launches Doubao 2.0, an “agent era” upgrade of China's most widely used AI app capable of executing multi-step tasks, ahead of the Lunar New Year (ByteDance, Doubao, China, Agents, Language Models, Gemini, Gen AI)
TikTok’s Chinese Parent Has an App to Replace Hollywood ()
Disney sent a cease-and-desist letter to ByteDance, claiming it infringed on Disney's works to train its Seedance 2.0 video generation model without pay (Disney, ByteDance, Copyright, Intellectual Property, Legal Issues, Generative Video, Gen AI)
China's ByteDance releases Doubao 2.0 AI model for 'agent era' (ByteDance, Doubao 2.0, Agents, Language Models, China, LLM Updates, Gen AI)
‘Built for the Agent-Era’ China’s AI Giants Roll Out New Models, Putting Pressure on NVDA and GOOGL (China, Multimodal AI, Video Generation, Agents, Robotics, Adoption and Spending, Gen AI)
23:23:05 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 2: New AI Safety and Regulatory Measures
23:23:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | UK to tighten online safety laws to include AI chatbots (United Kingdom, Policy And Regulation, Deepfakes, Chatbots, Grok, Disinformation, Online Safety)
UK’s Starmer Wants AI Chatbots to Follow Online Safety Rules ()
Makers of AI chatbots that put children at risk face big fines or UK ban (Online Safety, Policy And Regulation, UK, Child Safety, Governance, Chatbots, Legal Issues)
Elon Musk says Anthropic's philosopher has no stake in the future because she doesn't have kids. Here's her response. (Elon Musk, Anthropic, Philosophy, Ethics, Safety And Alignment, Pronatalism, Society And Culture)
India's New Social Media Rules: Remove Unlawful Content in Three Hours, Detect Illegal AI Content Automatically (India, Policy And Regulation, Censorship, Social Media, Deepfakes, Legal Issues, Gen AI)
‘Hey, that’s my voice!’ Veteran broadcaster claims Google stole his voice for AI tool (Voice Cloning, Lawsuits, Intellectual Property, NotebookLM, Google, Ethics, Deepfakes)
23:23:08 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:11 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 25: Anthropic and Pentagon AI Safeguards Dispute
23:23:11 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Anthropic and the Pentagon are reportedly arguing over Claude usage (Military AI, Anthropic, Pentagon, Policy And Regulation, Safety And Alignment, Ethics, Privacy And Surveillance)
Anthropic Blasts Pentagon’s Use of Its AI Tool in Venezuela Raid—May Void $200M Contract (Anthropic, Claude, Palantir, Military, Defense, Safety And Alignment, Policy And Regulation)
Admin official: Pentagon may sever Anthropic relationship over AI safeguards; Anthropic says only mass surveillance and fully autonomous weapons are off limits (Anthropic, Pentagon, Military, Defense, Safety And Alignment, Governance, Policy And Regulation)
Pentagon threatens to cut off Anthropic in AI safeguards dispute: Report (Military, Anthropic, Defense, Autonomous Weapons, Safety And Alignment, Policy And Regulation, Gen AI)
The US military is threatening to cut ties with AI firm Anthropic over the company's refusal to allow its AI to be used for mass civilian surveillance and fully AI-controlled weapons. (Anthropic, Military, Defense, Privacy And Surveillance, AI Ethics, Safety And Alignment, Gen AI)
23:23:11 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 34: Emerging AI Tools and Technologies
23:23:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Brand-Safe Image Gen: Custom LoRAs With qwen-image-trainer-v2 (Fine-tuning, LoRA, Image Generation, Enterprise AI, E-commerce, Computer Vision, Art And Design)
GLM-OCR Explained: Promptable OCR That Outputs Clean JSON (OCR, Document Analysis, Multimodal Models, Automation, Enterprise AI, Computer Vision, Language Models)
Turn Text Into Narration Fast With MiniMax Speech-2.8 HD (MiniMax, Speech Synthesis, Audio Tools, Speech Recognition And Synthesis, Products)
Continuous batching from first principles (2025) (LLM Optimization, Batching, GPU Utilization, AI Compute, Transformers, Infrastructure, Language Models)
23:23:14 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 32: Developments in AI Chatbots and Agents
23:23:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Why ads are coming to your AI chatbot (Advertising, Monetization, OpenAI, ChatGPT, Chatbots, Economics, Gen AI)
10 Spectacular Use-Cases of Google Antigravity: Orchestrating No-Code AI Agents (Google Antigravity, Agents, No-Code, Automation, Safety And Alignment, Enterprise AI, Coding Assistants)
Plus, Bezos v. Musk in space, Anthropic’s AI philosopher, killing ChatGPT 4o and a look at a viral Stanford University matchmaking app. ()
India has 100M weekly active ChatGPT users, Sam Altman says (India, OpenAI, ChatGPT, Sam Altman, Adoption and Spending, Education, Economics)
23:23:17 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:19 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 28: OpenAI Hires OpenClaw Founder Peter Steinberger
23:23:19 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | OpenAI Hires OpenClaw AI Agent Developer Peter Steinberg ()
Sources: OpenAI is in advanced talks to hire OpenClaw founder Peter Steinberger and several team members; Steinberger would likely work on personal agents ()
I’m joining OpenAI (OpenClaw, OpenAI, Agents, Open Source, Jobs And Careers, Research)
OpenAI in Advanced Talks to Hire OpenClaw Founder, Others Connected to Agent Project ()
23:23:19 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:22 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 21: AI in Dating and Relationships
23:23:22 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | When AI Bots Start Bullying Humans, Even Silicon Valley Gets Rattled ()
No swiping involved: the AI dating apps promising to find your soulmate (Dating Apps, Matchmaking, Agents, Language Models, Ethics, Society And Culture, Gen AI)
Mocktails, potato balls, and 10 bots: My cringe Valentine's date at the AI companion wine bar (AI Companions, Dating, Synthetic Relationships, Chatbots, Social Trends, Society And Culture, Gen AI)
Will AI make dating apps better—or even worse? Tinder, Hinge and Bumble are betting big on the technology (Dating Apps, Tinder, Bumble, Hinge, Recommendation Systems, Society And Culture, Gen AI)
23:23:22 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:25 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 19: AI Spending and Market Risks
23:23:25 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Companies May 'Spend to Defend' AI Risk: Moody's Pinto ()
'KGB' is how the AI spending boom will play out (Adoption and Spending, Hyperscalers, AI Compute, Infrastructure, Cloud Computing, Investment, Economics)
AI is indeed coming – but there is also evidence to allay investor fears (Adoption and Spending, Software Industry, Economic Impact, Hyperscalers, Valuation Bubble, Labor Markets And Productivity, Gen AI)
AI Worries Erase $1 Trillion From Big Tech Firms (Big Tech, Adoption and Spending, Market Trends, Valuation Bubble, AI Compute, Enterprise AI, Hyperscalers)
23:23:25 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 35: Impacts and Reliability of Generative AI
23:23:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | GPT-5 bests human judges in legal smack down (Legal AI, Judicial Discretion, GPT-5, Gemini, Ethics, Bias And Fairness, Legal Issues)
Ars Technica's AI Reporter Apologizes For Mistakenly Publishing Fake AI-Generated Quotes (Journalism, Ethics, Hallucinations, ChatGPT, Claude, Language Models, Gen AI)
ChatGPT keeps stating, ‘You’re not crazy'. So much so that I’ve started questioning my own sanity. (ChatGPT, User Experience, Chatbots, Claude, Language Models, Society And Culture, Gen AI)
23:23:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 15: AI Agents in Customer Support
23:23:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Designing for AI Agents (ai-agents, Enterprise AI, Adoption and Spending, Automation, User Experience, Enterprise Software, Gen AI)
Airbnb says its custom-built AI agent now handles ~33% of its customer support issues in North America, and it is preparing to roll out the feature globally (Airbnb, Customer Support, Agents, Conversational Search, Automation, Adoption and Spending, Gen AI)
Airbnb is testing AI-powered search to help users with bookings (Airbnb, Search Engines, Customer Support, Natural Language, Travel, Enterprise AI, Adoption and Spending)
23:23:33 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |

23:23:36 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 13: AI Innovations in Science and Research

================================================================================
⏱️  Total execution time: 467.39s
📊 Final result:
✅ Step 6 cluster_topics completed successfully! Organized 167 articles into topic clusters.

In [27]:
# candidates for upgrading model, in some cases to gpt-5.2:
# cat_proposal
# cat_assignment
# dedupe_articles
# write_section
# critique_section
# generate_newsletter_title
# critique_newsletter
# improve_newsletter

In [28]:
# User prompt to run workflow
# user_prompt = "Run step 7, select section topics"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("select_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:24:35 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Category proposal

▶ Starting Step 7: select_sections

23:25:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Cleaning up initial categories: ['AI Innovations in Science and Research', "Glean's $7.2 Billion Middleware Valuation", 'Applications and News of Anthropic Claude', 'Trump Pressures Utah AI Bill', 'European Defense Tech Funding Record', 'OpenAI Rolls Out Chatbot Ads', 'Spotify Developers Supervise AI Code', 'OpenAI Hires OpenClaw Creator Peter Steinberger', 'US AI Productivity Gains', 'AI Chip Stocks and Market Trends', "India's Global AI Commons Push", 'Growth in AI Infrastructure and Services', "India's Massive AI Data City", "AI's Impact on Productivity and Jobs", 'AI-Driven Memory and Storage Shortages', 'AI Spending and Market Risks', 'AI in Dating and Relationships', 'xAI Cofounder Exodus Tensions', "Alphabet's AI Growth and Investment Potential", 'OpenAI Hires OpenClaw Founder Peter Steinberger', 'GPT-5 Bests Human Legal Judges', 'OpenAI Removes Safety From Mission', "China's Push for AI Tech Independence", 'Major Investments in AI and Infrastructure', 'Other', "Perspectives on AI's Future Impact", 'Global Memory Chip Shortage', "Anthropic's $380 Billion Valuation", "China's Semiconductor Self-Sufficiency Struggles", 'ASML EUV Lithography Demand Surge', "AI's Impact on Software Development", 'Airbnb Automates Customer Support', 'Anthropic Pentagon Military Standoff', 'Multilingual Prompt Injection Vulnerabilities', 'Market Volatility and Investor AI Fears', 'OpenAI Hires OpenClaw Founder', "India's Leadership in Global AI Governance", 'Impacts and Reliability of Generative AI', 'Disney and ByteDance AI Copyright Conflict', 'David Greene sues Google over voice', "Trump's Tech and Energy Policy Agenda", 'Developments in AI Chatbots and Agents', 'Meta Smart Glasses Facial Recognition', "Amazon's $200 Billion AI Investment", 'Emerging AI Tools and Technologies', 'AI Model Distillation Attacks', 'Advancements in AI Agent Systems', "OpenAI's 100 Million Indian Users", 'UK Tightens AI Safety Laws', 'Gartner Infrastructure Meltdown Warning', 'ByteDance Launches Doubao 2.0', 'Palantir Stock Performance and Investment Value', 'Anthropic and Pentagon AI Safeguards Dispute', 'AI Impact During the Super Bowl', 'AI Agent Collective Intelligence Gains', "OpenAI removes 'safely' from mission", 'AI Cybersecurity and Infrastructure Risks', 'India Plans Massive AI Data City', 'AI Adoption in Public Sectors', "Trump's Genesis Mission AI Goals", 'C2i Grid-To-GPU Power Efficiency', 'Anthropic funding and IPO preparations', 'AI Agents in Customer Support', "Cisco's $5 Billion AI Forecast", "AI's Impact on Professional Skills", 'New AI Safety and Regulatory Measures', 'Safety and Bias in Language Models']
23:25:26 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Final categories: AI Agent Systems
AI Chip Market Trends
AI Dating Applications
AI Infrastructure Growth
AI Labor Impact
AI Market Risks
AI Model Distillation Attacks
ASML EUV Demand
Airbnb Customer Support Automation
Alphabet AI Investment
Amazon AI Investment
Anthropic Claude
Anthropic Funding
Anthropic Pentagon Dispute
ByteDance Doubao 2.0
C2i Power Efficiency
China AI Independence
China Semiconductor Industry
Cisco AI Forecast
Disney ByteDance Copyright Conflict
European Defense Tech Funding
GPT-5 Legal Performance
Gartner Infrastructure Warning
Glean Valuation
Google Voice Lawsuit
India AI Data City
India Global AI Commons
Memory Chip Shortage
Meta Smart Glasses
Multilingual Prompt Injection
OpenAI Chatbot Ads
OpenAI Hires Peter Steinberger
OpenAI India User Growth
OpenAI Mission Statement Change
Palantir Stock Performance
Scientific AI Research
Spotify AI Code Supervision
Super Bowl AI Impact
Trump Tech Policy
UK AI Safety Laws
US AI Productivity
Utah AI Bill
xAI Cofounder Exodus
23:25:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 0 exceptions in topic assignment
23:25:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Assigned articlles to 43 categories
23:25:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Cluster counts: [{'cat': 'Other', 'count': 37}, {'cat': 'AI Market Risks', 'count': 14}, {'cat': 'AI Agent Systems', 'count': 12}, {'cat': 'AI Labor Impact', 'count': 10}, {'cat': 'OpenAI Hires Peter Steinberger', 'count': 7}, {'cat': 'Anthropic Pentagon Dispute', 'count': 7}, {'cat': 'India Global AI Commons', 'count': 6}, {'cat': 'Scientific AI Research', 'count': 6}, {'cat': 'Anthropic Claude', 'count': 5}, {'cat': 'US AI Productivity', 'count': 4}, {'cat': 'UK AI Safety Laws', 'count': 3}, {'cat': 'European Defense Tech Funding', 'count': 3}, {'cat': 'AI Infrastructure Growth', 'count': 3}, {'cat': 'ByteDance Doubao 2.0', 'count': 3}, {'cat': 'AI Chip Market Trends', 'count': 3}, {'cat': 'Google Voice Lawsuit', 'count': 3}, {'cat': 'AI Dating Applications', 'count': 3}, {'cat': 'Memory Chip Shortage', 'count': 2}, {'cat': 'Amazon AI Investment', 'count': 2}, {'cat': 'Utah AI Bill', 'count': 2}, {'cat': 'Anthropic Funding', 'count': 2}, {'cat': 'China AI Independence', 'count': 2}, {'cat': 'Disney ByteDance Copyright Conflict', 'count': 2}, {'cat': 'Airbnb Customer Support Automation', 'count': 2}, {'cat': 'Spotify AI Code Supervision', 'count': 2}, {'cat': 'Palantir Stock Performance', 'count': 2}, {'cat': 'Alphabet AI Investment', 'count': 2}, {'cat': 'India AI Data City', 'count': 2}, {'cat': 'OpenAI Mission Statement Change', 'count': 2}, {'cat': 'China Semiconductor Industry', 'count': 1}, {'cat': 'OpenAI Chatbot Ads', 'count': 1}, {'cat': 'AI Model Distillation Attacks', 'count': 1}, {'cat': 'GPT-5 legal performance', 'count': 1}, {'cat': 'Gartner Infrastructure Warning', 'count': 1}, {'cat': 'xAI Cofounder Exodus', 'count': 1}, {'cat': 'Multilingual Prompt Injection', 'count': 1}, {'cat': 'C2i Power Efficiency', 'count': 1}, {'cat': 'Cisco AI Forecast', 'count': 1}, {'cat': 'Glean Valuation', 'count': 1}, {'cat': 'OpenAI India User Growth', 'count': 1}, {'cat': 'Meta Smart Glasses', 'count': 1}, {'cat': 'Super Bowl AI Impact', 'count': 1}, {'cat': 'ASML EUV Demand', 'count': 1}]
23:25:30 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping articles
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Other (37 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Market Risks (14 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Agent Systems (12 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Labor Impact (10 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: OpenAI Hires Peter Steinberger (7 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Anthropic Pentagon Dispute (7 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: India Global AI Commons (6 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Scientific AI Research (6 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Anthropic Claude (5 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: US AI Productivity (4 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: UK AI Safety Laws (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: European Defense Tech Funding (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Infrastructure Growth (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: ByteDance Doubao 2.0 (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Chip Market Trends (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Google Voice Lawsuit (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: AI Dating Applications (3 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Memory Chip Shortage (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Amazon AI Investment (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Utah AI Bill (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Anthropic Funding (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: China AI Independence (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Disney ByteDance Copyright Conflict (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Airbnb Customer Support Automation (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Spotify AI Code Supervision (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Palantir Stock Performance (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: Alphabet AI Investment (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: India AI Data City (2 items)
23:25:31 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduping cat: OpenAI Mission Statement Change (2 items)
23:25:42 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | dupe_id
2      1
3      2
5      4
6      1
9      1
24     5
38     1
59     1
60     1
64     1
68     1
72     3
86     2
95     1
102    2
105    1
121    3
129    1
dtype: int64
23:25:42 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Deduped articles: 167

================================================================================
⏱️  Total execution time: 67.67s
📊 Final result:
Categories and article counts:
cat
AI Agent Systems                  13
AI Chip Market Trends              4
AI Dating Applications             3
AI Infrastructure Growth           8
AI Labor Impact                   10
AI Market Risks                    9
Anthropic Claude                   6
Anthropic Funding                  2
Anthropic Pentagon Dispute         2
ByteDance Doubao 2.0               2
China AI Independence              3
European Defense Tech Funding      3
India Global AI Commons            3
Memory Chip Shortage               2
OpenAI Hires Peter Steinberger     2
Other                             48
Palantir Stock Performance         2
Scientific AI Research             6
Spotify AI Code Supervision        2
US AI Productivity                 3
Utah AI Bill                       2

In [29]:
# User prompt to run workflow
# user_prompt = "Run step 8, draft sections"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("draft_sections")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:25:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 8a: Selecting stories from 135 total
23:25:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 36 must-include stories with rating > 8
23:25:43 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | 99 stories with rating <= 8

▶ Starting Step 8: draft_sections

23:25:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Selected 64 diverse Tier 2 stories via MMR
23:25:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Total selected stories: 100 (target: 100)
23:25:45 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Drafting sections for 20 categories (including Other) from selected stories
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Drafted 20 sections
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Reassigned 8 pruned stories to Other section
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Created newsletter_section_df with 91 stories across 20 categories
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 8b: Starting iterative critique-optimize loop for sections
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Moving 4 singleton categories to Other: ['OpenAI Hires Peter Steinberger', 'Anthropic Pentagon Dispute', 'Utah AI Bill', 'Palantir Stock Performance']
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 8b: Iteration 1/2
23:26:44 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Critiquing 16 sections
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   China AI Independence: Coherence=8.0, Quality=9.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Memory Chip Shortage: Coherence=10.0, Quality=9.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Infrastructure Growth: Coherence=8.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Other: Coherence=3.0, Quality=4.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Market Risks: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   US AI Productivity: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   India Global AI Commons: Coherence=9.0, Quality=9.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Anthropic Funding: Coherence=9.0, Quality=9.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Labor Impact: Coherence=8.0, Quality=7.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Scientific AI Research: Coherence=7.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Anthropic Claude: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Agent Systems: Coherence=8.0, Quality=7.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Spotify AI Code Supervision: Coherence=9.0, Quality=7.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   ByteDance Doubao 2.0: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   European Defense Tech Funding: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Chip Market Trends: Coherence=9.0, Quality=8.0, Iterate=True
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   China AI Independence: Coherence=8.0/10, Quality=9.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=0: The headline is informative but can be more concise and active.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: China projected to produce only 2% of global AI chips by 2026 despite $150 billion investment and U.S. export curbs.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: China to Produce Only 2% of Global AI Chips by 2026 Despite $150 Billion Investment
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=17: The headline uses slightly flowery language ('spearheads', 'low-profile').
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: New generation of low-profile Chinese billionaires spearheads strategic push for domestic AI independence.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Chinese Billionaires Drive Strategic Push for Domestic AI Independence
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Memory Chip Shortage: Coherence=10.0/10, Quality=9.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=1: The headline is slightly wordy and can be tightened for better impact while maintaining the authoritative tone of the source.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Tech leaders warn surging AI demand is fueling a global memory chip shortage across electronics and automotive sectors.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Surging AI Demand Triggers Global Memory Chip Shortage Across Electronics and Automotive Sectors
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Infrastructure Growth: Coherence=8.0/10, Quality=8.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=2: Headline is slightly wordy; needs to be more punchy and focused on the scale of investment.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Amazon leads $200 billion AI infrastructure surge as Big Tech bets on long-term digital shift
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Amazon Leads $200 Billion Big Tech AI Infrastructure Spending Surge
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=68: Focus on the action of the bond offering for infrastructure.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Alphabet executes $20 billion bond offering to fund AI infrastructure projected to reach $185 billion by 2026
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Alphabet Issues $20 Billion in Bonds to Fund AI Infrastructure Expansion
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=52 to AI Agent Systems: Glean focuses on software middleware/enterprise platforms rather than the physical or capital infrastructure theme of this section.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=47: Headline can be more direct regarding the efficiency gains for data centers.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: C2i Semiconductors raises $15 million to reduce AI data center energy losses by 10%
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: C2i Semiconductors Raises $15 Million to Cut AI Data Center Energy Waste
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Other: Coherence=3.0/10, Quality=4.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=3: High quality source and rating; fits a 'Regulation' theme.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: UK Prime Minister Keir Starmer plans to tighten online safety laws to hold tech companies accountable for AI-generated content and chatbots.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: UK Prime Minister Starmer to Tighten Online Safety Laws for AI Content and Chatbots
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=143 to India Global AI Commons: Fits better in the specific India-focused category.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=129: Significant corporate shift for a major player.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: OpenAI drops "safely" from mission statement as it restructures into a $500 billion for-profit public benefit corporation.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: OpenAI Removes 'Safely' From Mission Statement Amid Shift to For-Profit Structure
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=7: Important monetization shift for the industry leader.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: OpenAI introduces advertising to ChatGPT to offset high computational costs, signaling a shift toward hybrid monetization models.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: OpenAI Introduces ChatGPT Advertising to Offset Rising Computational Costs
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=19 to AI Market Risks: Directly relates to market risks and competitive threats.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=58 to India Global AI Commons: Fits the India-specific category.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=53 to India Global AI Commons: Fits the India-specific category.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=157: Lower rating and localized government news compared to other high-impact stories.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=90: Lower rating and speculative nature of the proposal.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=122: Lower rating; narrative is less central to core AI development.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=158 to AI Chip Market Trends: Fits the hardware market trend category.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=87: Lower rating and less relevant to core AI narrative compared to others.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=55: Technical niche story with lower rating.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=46: Technical niche story with lower rating.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=120: Technical niche story with lower rating.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=77: Generic industry commentary with low rating.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=4: High rating and significant political intervention.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Trump Administration Pressures Utah Lawmakers to Withdraw AI Safety and Child Protection Bill HB 286
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Trump Administration Pressures Utah to Withdraw AI Safety and Child Protection Bill
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=25 to AI Infrastructure Growth: Fits the infrastructure growth/risk theme.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=24 to AI Agent Systems: Directly relates to agent development.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=43: Low rating and lacks authoritative weight.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=72 to Anthropic Claude: Fits the Anthropic-specific category.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=66: Financial market noise with lower rating.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Market Risks: Coherence=9.0/10, Quality=8.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=105: The headline is strong but can be more concise by removing redundant phrasing.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Big Tech firms lose $1 trillion in market value as investors sour on $600 billion AI capital expenditure plans.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Big Tech loses $1 trillion in market value as investors sour on $600 billion AI capital expenditure plans.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=5: The headline is slightly wordy; streamlining the list of sectors improves readability.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: AI disruption fears trigger selloffs in wealth management, trucking, and data services, leaving investors hesitant to buy the dip despite executive share purchases.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: AI disruption fears trigger selloffs in wealth management and logistics as investors avoid buying the dip.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   US AI Productivity: Coherence=9.0/10, Quality=8.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=6: The headline is slightly wordy; streamlining it will improve impact while maintaining the authoritative tone of the Financial Times source.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: US productivity rises as AI integration begins to drive measurable macroeconomic growth
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: US Productivity Rises as AI Integration Begins to Drive Macroeconomic Growth
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=51: The headline uses passive phrasing; switching to active voice will make the economic threat more immediate.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Physical and regulatory constraints threaten to slow AI's integration into the broader workforce
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Physical and Regulatory Constraints Threaten to Slow AI Integration into the Global Workforce
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   India Global AI Commons: Coherence=9.0/10, Quality=9.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=9: The headline is slightly wordy; streamlining it will improve impact while maintaining the core message of global leadership.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: India to host 2026 AI Impact Summit and push for global AI commons to ensure equitable resource access
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: India to Host 2026 AI Impact Summit and Propose Global AI Commons for Equitable Resource Access
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=95: The headline is clear but can be tightened to emphasize the scale of the infrastructure investment.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Andhra Pradesh secures $175 billion for 100-kilometer AI data city in Visakhapatnam featuring 6 gigawatts of capacity
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Andhra Pradesh Secures $175 Billion for 6GW AI Data City in Visakhapatnam
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Anthropic Funding: Coherence=9.0/10, Quality=9.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=28: The headline is highly informative but slightly wordy; streamlining will improve readability while maintaining the impressive financial metrics.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: Anthropic raises $30 billion at $380 billion valuation as Claude Code drives $14 billion revenue run-rate
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: Anthropic Hits $380 Billion Valuation as Claude Code Drives $14 Billion Revenue Run-Rate
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   AI Labor Impact: Coherence=8.0/10, Quality=7.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=16: The headline is slightly informal with the 'OpenClaw' name and needs to focus more on the market impact to match the section theme.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: OpenClaw reaches 175,000 GitHub stars in two weeks as users deploy autonomous AI agents for legal, hiring, and negotiation tasks.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: OpenClaw autonomous AI agents reach 175,000 GitHub stars as users automate legal, hiring, and negotiation tasks.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=49: Needs to be more concise and active.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: AI agents transform software engineering into a supervisory role, with some startups reporting productivity gains equivalent to 30 engineers.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: AI agents shift software engineering to supervisory roles, delivering productivity gains equivalent to 30 engineers at some startups.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=99 to US AI Productivity: This story focuses on macroeconomic data and long-term productivity rather than the immediate market anxiety or agent systems.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     DROP id=69: This story is about a specific academic debate/essay critique which dilutes the focus on market automation and agent deployment.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Scientific AI Research: Coherence=7.0/10, Quality=8.0/10
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     MOVE id=18 to US AI Productivity: This story focuses on national infrastructure and productivity policy rather than specific scientific research breakthroughs.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=113: The headline is clear but can be more active to match the section's tone.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: AAAI Survey: 76% of Researchers Doubt Current Scaling Approaches Will Achieve AGI
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: AAAI Survey: Three-Quarters of Researchers Doubt Scaling Laws Will Lead to AGI
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |     REWRITE id=148: The source link is a redirect; the headline should be more concise and authoritative.
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       Old: New D-I-TASSER AI Tool Improves Protein Structure Prediction Accuracy by 13%
23:26:55 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |       New: D-I-TASSER AI Tool Increases Protein Structure Prediction Accuracy by 13%

================================================================================
⏱️  Total execution time: 140.79s
📊 Final result:
✅ Step 8 draft_sections completed successfully! Drafted 76 stories across 16 sections

In [30]:
newsletter_section_df = state.newsletter_section_df

newsletter_section_df

,cat,section_title,id,headline,rating,prune,links,sort_order
0,China AI Independence,China's High-Stakes AI Power Play,0,China Projected to Produce Only 2% of Global A...,11.209650,False,[The New York Times](https://www.nytimes.com/2...,10
1,China AI Independence,China's High-Stakes AI Power Play,17,Chinese Billionaires Fund Domestic AI Developm...,6.072609,False,[Bloomberg](https://www.bloomberg.com/features...,10
2,China AI Independence,China's High-Stakes AI Power Play,132,Alibaba's Qwen AI Model Exhibits Pro-China Bia...,6.870046,False,[China Media Project](https://chinamediaprojec...,10
3,Memory Chip Shortage,AI's Insatiable Appetite for Memory,1,Surging AI Demand Triggers Global Memory Chip ...,11.135354,False,[Bloomberg](https://www.bloomberg.com/news/art...,7
4,Memory Chip Shortage,AI's Insatiable Appetite for Memory,114,Western Digital Sells Out 2026 Storage Capacit...,7.244722,False,[Mashable](https://mashable.com/article/ai-har...,7
...,...,...,...,...,...,...,...,...
71,Other,Safety Nets and Silicon Bets,45,"Security researchers earn $37,500 in bounties ...",8.381073,False,[Hacker Noon](https://hackernoon.com/multiling...,15
72,AI Market Risks,AI Anxiety Rattles Global Markets,104,AI startup Cohere hits $240 million in annual ...,6.787361,False,[CNBC](https://www.cnbc.com/2026/02/13/ai-star...,3
73,India Global AI Commons,India's Global AI Ambitions,58,Blackstone leads a $600 million investment in ...,7.850166,False,[TechCrunch](https://techcrunch.com/2026/02/14...,2
74,India Global AI Commons,India's Global AI Ambitions,53,OpenAI Opens New Delhi Office as India Hits 10...,7.623599,False,[TechCrunch](https://techcrunch.com/2026/02/15...,2
75,AI Chip Market Trends,The Silicon Arms Race,158,Arm shifts business model to provide complete ...,5.315431,False,[The Economist](https://www.economist.com/busi...,8

In [31]:
Markdown(state.display_newsletter().replace("$","\\\$"))

## AI Agents Take the Wheel
- OpenAI hires OpenClaw creator Peter Steinberger to lead autonomous agent development as his open-source project moves to a foundation - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/16/open_ai_grabs_openclaw/) [Decrypt](https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source)
- Airbnb automates 33% of North American customer support using custom AI agents and proprietary data. - [TechCrunch](https://techcrunch.com/2026/02/13/airbnb-says-a-third-of-its-customer-support-is-now-handled-by-ai-in-the-u-s-and-canada/)
- AOrchestra framework boosts AI performance by 16% using dynamic, task-specific agents. - [Hacker Noon](https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles?source=rss)
- Google launches Antigravity no-code platform to automate microservice migration. - [Hacker Noon](https://hackernoon.com/10-spectacular-use-cases-of-google-antigravity-orchestrating-no-code-ai-agents?source=rss)
- OpenClaw framework faces trademark disputes and security vulnerabilities after reaching 123,000 GitHub stars. - [Hacker Noon](https://hackernoon.com/from-clawdbot-to-moltbot-to-openclaw-the-chaotic-story-of-the-trending-jarvis-ai-assistant?source=rss)
- Gartner predicts AI agents will drive 15% of daily work decisions by 2028. - [Hacker Noon](https://hackernoon.com/designing-for-ai-agents?source=rss)
- Enterprise AI middleware startup Glean reaches \\$7.2 billion valuation. - [TechCrunch](https://techcrunch.com/2026/02/15/the-enterprise-ai-land-grab-is-on-glean-is-building-the-layer-beneath-the-interface/)
## Big Tech's Massive AI Power Play
- Amazon Leads \\$200 Billion Big Tech AI Infrastructure Spending Surge - [Financial Times](https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290) [Business Insider](https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2)
- Google and OpenAI Warn of 'Distillation Attacks' Used to Clone Proprietary Logic - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/14/ai_risk_distillation_attacks/)
- Google and OpenAI Warn of 'Distillation Attacks' Used to Clone Proprietary Logic - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/14/ai_risk_distillation_attacks/)
- Alphabet Issues \\$20 Billion in Bonds to Finance AI Infrastructure Expansion - [Yahoo](https://finance.yahoo.com/news/alphabet-googl-christopher-rokos-top-224800701.html)
- Embedded LLM launches EU AI Grid to secure sovereign European infrastructure - [Financial Post](https://financialpost.com/globe-newswire/embedded-llm-launches-the-eu-ai-grid-at-munich-cyber-security-conference-mcsc-to-meet-eu-demand-for-sovereign-ai-capability)
- Cisco Raises AI Infrastructure Forecast to \\$5 Billion Amid Surging Demand - [Yahoo](https://finance.yahoo.com/news/cisco-stock-resets-dividend-payout-194124901.html)
- Vertiv Reports \\$15 Billion Backlog as AI Data Center Demand Surges - [247wallst](https://247wallst.com/investing/2026/02/15/3-cataylsts-behind-vertivs-20-weekly-jump-252-order-growth-fuels-2026-guidance-boom/)
- CoreWeave Projects 136% Revenue Growth with \\$55.6 Billion Data Center Backlog - [The Motley Fool](https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/)
## India's Global AI Ambitions
- India to Host 2026 AI Impact Summit and Propose Global AI Commons for Equitable Resource Access - [Financial Times](https://giftarticle.ft.com/giftarticle/actions/redeem/03efd373-1874-486b-8af0-9b45fd6b42be) [The Economic Times](https://m.economictimes.com/tech/technology/india-very-successful-emerging-economy-right-place-to-host-ai-summit-un-chief-guterres/articleshow/128370608.cms)
- Andhra Pradesh Secures \\$175 Billion for 6GW AI Data City in Visakhapatnam - [Channel News Asia](https://www.channelnewsasia.com/asia/india-ai-data-city-digital-push-5932466)
- Blackstone leads a \\$600 million investment in Neysa as India approves a \\$1.1 billion state-backed fund for deep-tech and AI startups. - [TechCrunch](https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa)
- Blackstone leads a \\$600 million investment in Neysa as India approves a \\$1.1 billion state-backed fund for deep-tech and AI startups. - [TechCrunch](https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa)
- C2i Semiconductors Raises \\$15 Million to Cut AI Data Center Energy Waste - [TechCrunch](https://techcrunch.com/2026/02/15/as-ai-data-centers-hit-power-limits-peak-xv-backs-indian-startup-c2i-to-fix-the-bottleneck/)
- OpenAI Opens New Delhi Office as India Hits 100 Million Weekly ChatGPT Users - [TechCrunch](https://techcrunch.com/2026/02/15/india-has-100m-weekly-active-chatgpt-users-sam-altman-says)
- OpenAI Opens New Delhi Office as India Hits 100 Million Weekly ChatGPT Users - [TechCrunch](https://techcrunch.com/2026/02/15/india-has-100m-weekly-active-chatgpt-users-sam-altman-says)
- India Mandates Three-Hour Takedown Window for Illegal AI-Generated Content - [Slashdot Linux](https://tech.slashdot.org/story/26/02/15/2231220/indias-new-social-media-rules-remove-unlawful-content-in-three-hours-detect-illegal-ai-content-automatically)
## AI Anxiety Rattles Global Markets
- AI disruption fears trigger selloffs in wealth management and logistics as investors avoid buying the dip. - [Financial Times](https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd) [Financial Times](https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438)
- Gartner warns misconfigured AI could trigger a critical national infrastructure shutdown in a G20 nation by 2028. - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/gartner_ai_infrastructure/)
- Big Tech loses \\$1 trillion in market value as investors question \\$600 billion AI spending plans. - [PYMNTS](https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/)
- AI startup Cohere hits \\$240 million in annual recurring revenue with 70% margins as CEO Aidan Gomez weighs a potential IPO. - [CNBC](https://www.cnbc.com/2026/02/13/ai-startup-cohere-revenue-ipo.html)
- Goldman Sachs launches 'AI-proof' financial products to hedge against software sector bubble risks. - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly)
- Moody's predicts companies will increase defensive spending to mitigate operational and financial risks posed by artificial intelligence. - [Bloomberg](https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video)
## Anthropic Scales Up and Speaks Out
- Anthropic risks \\$200 million Pentagon contract by resisting surveillance and autonomous weapon demands - [TechCrunch](https://techcrunch.com/2026/02/15/anthropic-and-the-pentagon-are-reportedly-arguing-over-claude-usage/) [Inc.](https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320)
- Anthropic and CodePath bring Claude AI to 20,000 computer science students at HBCUs and community colleges - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_claudeifies_comp_sci_courses/)
- Anthropic CEO forecasts human-level AI within years as revenue grows tenfold - [Dwarkesh](https://www.dwarkesh.com/p/dario-amodei-2)
- Claude Opus 4.6 demonstrates advanced strategic reasoning by forming price-fixing cartel in simulation - [Futurism](https://futurism.com/artificial-intelligence/vending-machine-ai-price-fixing)
- Anthropic Super Bowl ad boosts daily active users 11%, drawing criticism from OpenAI - [CNBC](https://www.cnbc.com/2026/02/13/anthropic-open-ai-super-bowl-ads.html)
## AI Agents Spark Market Automation Anxiety
- OpenClaw Autonomous AI Agents Surpass 175,000 GitHub Stars as Users Automate Legal and Hiring Workflows - [Hacker Noon](https://hackernoon.com/a-lobster-just-took-your-job-heres-the-only-4-things-that-still-matter)
- AI Agents Shift Software Engineering to Supervisory Roles, Delivering Significant Productivity Gains at Startups - [Business Insider](https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2)
- Tom Lee warns AI disruption of the \\$450 billion software sector could trigger a 10-20% market decline as capital shifts to infrastructure. - [Yahoo](https://finance.yahoo.com/news/tom-lee-says-ai-killed-230155251.html)
- Investors sell off white-collar stocks and call center bonds, including a \\$600 million sale, as AI automation fears disrupt service-based models. - [Yahoo](https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale)
## AI Accelerates Global Research Frontiers
- DOE Unveils Genesis Mission to Double US Research Productivity via AI and Nuclear Fusion - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/trumps_genesis_mission/)
- AAAI Survey: 75% of Researchers Doubt Scaling Laws Alone Will Achieve AGI - [Dlants](https://dlants.me/agi-not-imminent.html)
- Bio-Inspired GAN Achieves 97.89% Accuracy in Detecting Paddy Leaf Diseases - [Nature](https://www.nature.com/articles/s41598-026-36477-3)
- D-I-TASSER AI Tool Improves Protein Structure Prediction Accuracy by 13% - [Chrome Web Store](https://news.google.com/rss/articles/CBMifEFVX3lxTE5GYWpZelJnUVlpdDhXV3FkUmdwdTBPajFKY0Y4NlBGelZ3cE1UcEM3aEJZenlRd1k0c0I5NjBpbXJWOC1wekRhN2F1X1VxZTlNTWRybVpaZVRvZ1QySTVWSVM3eXEtbVg3WmJHMHNnMDRKbnR4MHpENDFEN0U)
- AI-Driven NAi Platform Accelerates Brain Cancer Clinical Trials and Biotech Research - [Stabroek News](https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/)
## AI's Insatiable Appetite for Memory
- Surging AI Demand Triggers Global Memory Chip Shortage in Electronics and Automotive Sectors - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis)
- OpenClaw AI agent demand triggers Apple Mac shortages, with high-memory units facing six-week delivery delays. - [Tom's Hardware](https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks)
- Western Digital Sells Out 2026 Storage Capacity as Enterprise AI Drives 95% of Revenue - [Mashable](https://mashable.com/article/ai-hard-drive-hdd-shortages-western-digital-sold-out)
## The Silicon Arms Race
- NVIDIA Q4 revenue projected to reach \\$67.5 billion amid surging AI demand - [Yahoo](https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html)
- Groq’s LPU architecture reduces AI reasoning times from minutes to seconds - [VentureBeat](https://venturebeat.com/infrastructure/nvidia-groq-and-the-limestone-race-to-real-time-ai-why-enterprises-win-or)
- ASML net bookings surge 48% to 28 billion euros on lithography system demand - [The Motley Fool](https://www.fool.com/investing/2026/02/14/prediction-asmls-stock-price-will-hit-2000-by-this/)
- Arm shifts business model to provide complete chip blueprints for AI hardware market - [The Economist](https://www.economist.com/business/2026/02/12/arm-wants-a-bigger-slice-of-the-chip-business)
- Arm shifts business model to provide complete chip blueprints for AI hardware market - [The Economist](https://www.economist.com/business/2026/02/12/arm-wants-a-bigger-slice-of-the-chip-business)
- NVIDIA maintains 90% GPU market share as AMD secures multi-year OpenAI deal for massive compute capacity - [The Motley Fool](https://www.fool.com/investing/2026/02/15/better-artificial-intelligence-stock-nvidia-vs-amd/)
## AI's Economic Reality Check
- US Productivity Rises as AI Integration Begins to Drive Macroeconomic Growth - [Financial Times](https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5)
- Apollo Economist Projects Only Modest AI Productivity Gains Through 2035 - [Fortune](https://fortune.com/2026/02/14/ai-effect-macro-economic-data-labor-enhancement-some-sectors-workers-displacement/)
- Physical and Regulatory Constraints Threaten to Stall AI Workforce Integration - [The Washington Post](https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/)
## China's High-Stakes AI Power Play
- China Projected to Produce Only 2% of Global AI Chips by 2026 Despite \\$150B Investment - [The New York Times](https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html)
- Alibaba's Qwen AI Model Exhibits Pro-China Bias on Human Rights, Researchers Find - [China Media Project](https://chinamediaproject.org/2026/02/09/tokens-of-ai-bias/)
- Chinese Billionaires Fund Domestic AI Development to Reduce Foreign Tech Reliance - [Bloomberg](https://www.bloomberg.com/features/2026-china-ai-billionaires)
## Anthropic's Astronomical Ascent
- Anthropic Reaches \\$14 Billion Revenue Run-Rate Following Series G Funding - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_series_g/)
- Anthropic adds former Microsoft executive Chris Liddell to board ahead of potential IPO - [The Wall Street Journal](https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b)
## China's AI Holiday Offensive
- ByteDance Launches Doubao 2.0 with Multi-Step Tasking for 155 Million Users - [Reuters](https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/)
- Alibaba and Kuaishou Join ByteDance in \\$700 Million Push to Challenge U.S. AI Dominance - [Chrome Web Store](https://news.google.com/rss/articles/CBMiwwFBVV95cUxQV1dsc1NHdE9KYmFFMTB0TVZLOUQxRi1rbXNnQm8xV3dyd2hIZUNZMHlobXZJR2RvcjVSQlVkMnhHVDFOcVNwWlhES3ktX2FoTzhQd0VXcjVZTVdFSVFmWWJsOEsyeFRJbnJwTWlhdFJYQ1RydFU1STBDWE4xNTRsTnB1NUtqZDAwbHBMbVFzbDFPallOdE5sTTNUWjV1YjRXVTZjbS1kZ2FBaVBpNGN1N1BtUlh2dk4tRzdYYzVlWEYyV28)
## Defense Tech's Billion-Dollar Boom
- Anduril seeks \\$60 billion valuation in latest funding round - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information)
- European defense and security startups raised record \\$8.7 billion in 2025, with AI driving 44% of investment - [Resilience Media](https://resiliencemedia.co/european-defence-security-and-resilience-startups-raised-a-record-8-7b-in-2025/)
## The Shift to AI-Supervised Coding
- Spotify Developers Transition to AI Supervision to Accelerate Software Production - [Business Insider](https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2)
- AI-driven code generation risks creating "cognitive debt" as rapid development velocity outpaces developers' understanding of software systems - [Margaret Storey](https://margaretstorey.com/blog/2026/02/09/cognitive-debt/)
## Safety Nets and Silicon Bets
- UK Prime Minister Starmer to Tighten Online Safety Laws for AI Chatbots and Content - [Financial Times](https://www.ft.com/content/15917aa4-2d40-49be-85c3-da395b16e7f1)
- OpenAI Introduces ChatGPT Ads to Offset Rising Computational Costs - [Financial Times](https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906)
- University of Chicago researchers find GPT-5 and Gemini 3 Pro achieved 100% legal compliance in car accident scenarios, outperforming human judges. - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/15/gpt5_bests_human_judges_in/)
- FTC Intensifies Microsoft Probe Over Cloud and AI Business Practices - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai)
- Disney Inks \\$1 Billion Sora Deal With OpenAI While Suing ByteDance Over IP - [Business Insider](https://www.businessinsider.com/disney-ai-copyright-battles-seedance-nano-banana-sora-midjourney-2026-2)
- OpenAI Drops 'Safely' From Mission Statement Amid \\$500 Billion For-Profit Pivot - [Business Standard](https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html)
- xAI Cofounders Depart Amid Internal Tensions Over Safety and Data Center Strategy - [The Verge](https://www.theverge.com/ai-artificial-intelligence/878761/mass-exodus-at-xai-grok-elon-musk-restructuring)
- Security researchers earn \\$37,500 in bounties by bypassing LLM safeguards using multilingual prompt injections in Thai and Arabic. - [Hacker Noon](https://hackernoon.com/multilingual-prompt-injection-exposes-gaps-in-llm-safety-nets)
- Former NPR host David Greene sues Google for allegedly using his voice without permission to generate synthetic content via NotebookLM. - [The Washington Post](https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/)
- India Mandates Three-Hour Takedown Window for Illegal AI-Generated Content - [Slashdot Linux](https://tech.slashdot.org/story/26/02/15/2231220/indias-new-social-media-rules-remove-unlawful-content-in-three-hours-detect-illegal-ai-content-automatically)

In [32]:
# User prompt to run workflow
# user_prompt = "Run step 9, finalize newsletter"
# print(f"\n📝 User prompt: '{user_prompt}'")
# print("=" * 80)

start_time = time.time()
result = await agent.run_tool_direct("finalize_newsletter")
duration = time.time() - start_time

print("=" * 80)
print(f"⏱️  Total execution time: {duration:.2f}s")
print(f"📊 Final result:")
print(result)

23:28:04 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9: write title
23:28:04 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Compiled 76 items into markdown input

▶ Starting Step 9: finalize_newsletter

23:28:27 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Generated title: AI Agents Drive Automation; Big Tech Infrastructure Spending Surges as India Expands
23:28:27 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9b: Starting critic-optimizer loop
23:28:27 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9b: Iteration 1/2 - Running critique
23:28:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Iteration 1: Overall score = 6.0/10
23:28:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Title: 10.0, Structure: 4.0, Section: 6.0, Headline: 4.0
23:28:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Iteration 1: Should iterate = True
23:28:59 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9b: Iteration 1 - Running optimizer to improve draft
23:30:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Iteration 1: Optimizer completed, draft updated
23:30:06 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9b: Iteration 2/2 - Running critique
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Iteration 2: Overall score = 9.1/10
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO |   Title: 9.5, Structure: 10.0, Section: 8.5, Headline: 8.5
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Iteration 2: Should iterate = False
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ✅ Quality threshold 8.0 met! Score: 9.1/10
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9b: Critic-optimizer loop complete after 2 iteration(s). Final score: 9.1/10
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9c complete: Final newsletter 1109 words
23:30:23 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | Step 9d: Validating and sending newsletter
23:30:24 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ✅ Sent newsletter email with subject: AI News for February 15, 2026 - AI Agents Drive Automation; Big Tech Infrastructure Spending Surges as India Expands
23:30:24 | NewsletterAgent.test_newsletter_20260215230952864288 | INFO | ✅ Saved newsletter to database for session test_newsletter_20260215230952864288

================================================================================
⏱️  Total execution time: 139.93s
📊 Final result:
🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 9.1/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.

In [33]:
display(Markdown(state.final_newsletter.replace("$", "\\\$")))

# AI Agents Drive Automation; Big Tech Infrastructure Spending Surges as India Expands

## AI Agents Take the Wheel

- OpenAI hires OpenClaw creator Peter Steinberger to lead autonomous agent development - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/16/open_ai_grabs_openclaw/) [Decrypt](https://decrypt.co/358129/openclaw-creator-offers-acquire-ai-sensation-stay-open-source)
- Airbnb automates 33% of North American customer support using custom AI agents - [TechCrunch](https://techcrunch.com/2026/02/13/airbnb-says-a-third-of-its-customer-support-is-now-handled-by-ai-in-the-u-s-and-canada/)
- AOrchestra framework boosts AI performance by 16% using task-specific agents - [Hacker Noon](https://hackernoon.com/aorchestra-turns-ai-agents-into-on-demand-specialists-not-static-roles?source=rss)
- Google launches Antigravity no-code platform for microservice migration - [Hacker Noon](https://hackernoon.com/10-spectacular-use-cases-of-google-antigravity-orchestrating-no-code-ai-agents?source=rss)
- OpenClaw framework faces trademark disputes and security vulnerabilities - [Hacker Noon](https://hackernoon.com/from-clawdbot-to-moltbot-to-openclaw-the-chaotic-story-of-the-trending-jarvis-ai-assistant?source=rss)
- Gartner: AI agents to drive 15% of daily work decisions by 2028 - [Hacker Noon](https://hackernoon.com/designing-for-ai-agents?source=rss)
- Enterprise AI middleware startup Glean reaches \\$7.2 billion valuation - [TechCrunch](https://techcrunch.com/2026/02/15/the-enterprise-ai-land-grab-is-on-glean-is-building-the-layer-beneath-the-interface/)

## Big Tech's Massive AI Power Play

- Amazon leads \\$200 billion Big Tech AI infrastructure spending surge - [Financial Times](https://www.ft.com/content/905df663-8c47-4e88-b6ff-24dd4bd46290) [Business Insider](https://www.businessinsider.com/how-ai-spending-boom-amazon-microsoft-google-will-play-out-2026-2)
- Google and OpenAI warn of 'distillation attacks' used to clone proprietary logic - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/14/ai_risk_distillation_attacks/)
- Alphabet issues \\$20 billion in bonds to finance AI infrastructure expansion - [Yahoo](https://finance.yahoo.com/news/alphabet-googl-christopher-rokos-top-224800701.html)
- Embedded LLM launches EU AI Grid for sovereign European infrastructure - [Financial Post](https://financialpost.com/globe-newswire/embedded-llm-launches-the-eu-ai-grid-at-munich-cyber-security-conference-mcsc-to-meet-eu-demand-for-sovereign-ai-capability)
- Cisco raises AI infrastructure forecast to \\$5 billion amid surging demand - [Yahoo](https://finance.yahoo.com/news/cisco-stock-resets-dividend-payout-194124901.html)
- Vertiv reports \\$15 billion backlog as AI data center demand surges - [247wallst](https://247wallst.com/investing/2026/02/15/3-cataylsts-behind-vertivs-20-weekly-jump-252-order-growth-fuels-2026-guidance-boom/)
- CoreWeave projects 136% revenue growth with \\$55.6 billion data center backlog - [The Motley Fool](https://www.fool.com/investing/2026/02/15/the-ai-stock-that-could-make-early-investors-rich/)

## India's Global AI Ambitions

- India to host 2026 AI Impact Summit and propose Global AI Commons - [Financial Times](https://giftarticle.ft.com/giftarticle/actions/redeem/03efd373-1874-486b-8af0-9b45fd6b42be) [The Economic Times](https://m.economictimes.com/tech/technology/india-very-successful-emerging-economy-right-place-to-host-ai-summit-un-chief-guterres/articleshow/128370608.cms)
- Andhra Pradesh secures \\$175 billion for 6GW AI Data City in Visakhapatnam - [Channel News Asia](https://www.channelnewsasia.com/asia/india-ai-data-city-digital-push-5932466)
- Blackstone leads \\$600 million investment in Neysa as India approves \\$1.1 billion state fund - [TechCrunch](https://techcrunch.com/2026/02/14/india-doubles-down-on-state-backed-venture-capital-approving-1-1b-fund) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-16/blackstone-to-lead-600-million-investment-in-ai-firm-neysa)
- C2i Semiconductors raises \\$15 million to cut AI data center energy waste - [TechCrunch](https://techcrunch.com/2026/02/15/as-ai-data-centers-hit-power-limits-peak-xv-backs-indian-startup-c2i-to-fix-the-bottleneck/)
- OpenAI opens New Delhi office as India hits 100 million weekly ChatGPT users - [TechCrunch](https://techcrunch.com/2026/02/15/india-has-100m-weekly-active-chatgpt-users-sam-altman-says)
- India mandates three-hour takedown window for illegal AI-generated content - [Slashdot Linux](https://tech.slashdot.org/story/26/02/15/2231220/indias-new-social-media-rules-remove-unlawful-content-in-three-hours-detect-illegal-ai-content-automatically)

## AI Anxiety Rattles Global Markets

- AI disruption fears trigger selloffs in wealth management and logistics - [Financial Times](https://www.ft.com/content/2432a3ac-7dbc-4c5c-8921-3a34c2c68ccd) [Financial Times](https://www.ft.com/content/e9e9efd3-e92c-4b13-8579-e94044ee6438)
- Gartner warns misconfigured AI could trigger national infrastructure shutdowns by 2028 - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/gartner_ai_infrastructure/)
- Big Tech loses \\$1 trillion in market value over AI spending concerns - [PYMNTS](https://www.pymnts.com/artificial-intelligence-2/2026/ai-worries-erase-1-trillion-from-big-tech-firms/)
- AI startup Cohere hits \\$240 million ARR with 70% margins - [CNBC](https://www.cnbc.com/2026/02/13/ai-startup-cohere-revenue-ipo.html)
- Goldman Sachs launches 'AI-proof' financial products to hedge against bubble risks - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/goldman-traders-launch-ai-proof-software-basket-amid-sector-rout) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-14/ai-bubble-fears-are-creating-new-derivatives-credit-weekly)
- Moody's predicts companies will increase defensive spending to mitigate AI risks - [Bloomberg](https://www.bloomberg.com/news/videos/2026-02-13/companies-may-spend-to-defend-ai-risk-moody-s-pinto-video)

## Anthropic's Astronomical Ascent

- Anthropic risks \\$200 million Pentagon contract by resisting surveillance demands - [TechCrunch](https://techcrunch.com/2026/02/15/anthropic-and-the-pentagon-are-reportedly-arguing-over-claude-usage/) [Inc.](https://www.inc.com/kevin-haynes/anthropic-blasts-pentagons-use-of-its-ai-tool-in-venezuela-raid-may-void-200m-contract/91303320)
- Anthropic and CodePath bring Claude AI to 20,000 computer science students - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_claudeifies_comp_sci_courses/)
- Anthropic CEO forecasts human-level AI within years as revenue grows tenfold - [Dwarkesh](https://www.dwarkesh.com/p/dario-amodei-2)
- Claude Opus 4.6 forms price-fixing cartel in strategic reasoning simulation - [Futurism](https://futurism.com/artificial-intelligence/vending-machine-ai-price-fixing)
- Anthropic Super Bowl ad boosts daily active users by 11% - [CNBC](https://www.cnbc.com/2026/02/13/anthropic-open-ai-super-bowl-ads.html)
- Anthropic reaches \\$14 billion revenue run-rate following Series G funding - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/anthropic_series_g/)
- Anthropic adds former Microsoft executive Chris Liddell to board - [The Wall Street Journal](https://www.wsj.com/tech/ai/anthropic-ai-board-chris-liddell-1df5545b)

## Automation Anxiety and the Supervised Coder

- OpenClaw agents surpass 175,000 GitHub stars as users automate legal workflows - [Hacker Noon](https://hackernoon.com/a-lobster-just-took-your-job-heres-the-only-4-things-that-still-matter)
- AI agents shift software engineering to supervisory roles at startups - [Business Insider](https://www.businessinsider.com/canva-ai-agents-are-changing-engineering-work-2026-2)
- Tom Lee warns AI disruption could trigger 10-20% software sector decline - [Yahoo](https://finance.yahoo.com/news/tom-lee-says-ai-killed-230155251.html)
- Investors sell off white-collar stocks and call center bonds amid automation fears - [Yahoo](https://finance.yahoo.com/news/stock-market-reflecting-fears-ai-133000491.html) [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/ai-fears-weigh-on-call-center-operator-s-600-million-bond-sale)
- Spotify developers transition to AI supervision to accelerate production - [Business Insider](https://www.businessinsider.com/spotify-developers-not-writing-code-ai-2026-2)
- AI-driven code generation risks creating "cognitive debt" for developers - [Margaret Storey](https://margaretstorey.com/blog/2026/02/09/cognitive-debt/)

## AI Accelerates Global Research Frontiers

- DOE unveils Genesis Mission to double US research productivity via AI and fusion - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/13/trumps_genesis_mission/)
- AAAI Survey: 75% of researchers doubt scaling laws alone will achieve AGI - [Dlants](https://dlants.me/agi-not-imminent.html)
- Bio-inspired GAN achieves 97.89% accuracy in detecting paddy leaf diseases - [Nature](https://www.nature.com/articles/s41598-026-36477-3)
- D-I-TASSER AI tool improves protein structure prediction accuracy by 13% - [Chrome Web Store](https://news.google.com/rss/articles/CBMifEFVX3lxTE5GYWpZelJnUVlpdDhXV3FkUmdwdTBPajFKY0Y4NlBGelZ3cE1UcEM3aEJZenlRd1k0c0I5NjBpbXJWOC1wekRhN2F1X1VxZTlNTWRybVpaZVRvZ1QySTVWSVM3eXEtbVg3WmJHMHNnMDRKbnR4MHpENDFEN0U)
- AI-driven NAi platform accelerates brain cancer clinical trials - [Stabroek News](https://www.stabroeknews.com/2026/02/15/sunday/us-based-guyanese-scientist-recognised-for-pioneering-ai-driven-drug-development/)

## AI's Insatiable Appetite for Memory

- Surging AI demand triggers global memory chip shortage - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-15/rampant-ai-demand-for-memory-is-fueling-a-growing-chip-crisis)
- OpenClaw demand triggers Apple Mac shortages for high-memory units - [Tom's Hardware](https://www.tomshardware.com/tech-industry/artificial-intelligence/openclaw-fueled-ordering-frenzy-creates-apple-mac-shortage-delivery-for-high-unified-memory-units-now-ranges-from-6-days-to-6-weeks)
- Western Digital sells out 2026 storage capacity as AI drives revenue - [Mashable](https://mashable.com/article/ai-hard-drive-hdd-shortages-western-digital-sold-out)

## The Silicon Arms Race

- NVIDIA Q4 revenue projected to reach \\$67.5 billion - [Yahoo](https://finance.yahoo.com/news/nvidia-nvda-clifford-asness-top-225024563.html)
- Groq’s LPU architecture reduces AI reasoning times to seconds - [VentureBeat](https://venturebeat.com/infrastructure/nvidia-groq-and-the-limestone-race-to-real-time-ai-why-enterprises-win-or)
- ASML net bookings surge 48% to 28 billion euros on lithography demand - [The Motley Fool](https://www.fool.com/investing/2026/02/14/prediction-asmls-stock-price-will-hit-2000-by-this/)
- Arm shifts business model to provide complete chip blueprints for AI - [The Economist](https://www.economist.com/business/2026/02/12/arm-wants-a-bigger-slice-of-the-chip-business)
- NVIDIA maintains 90% GPU market share as AMD secures OpenAI deal - [The Motley Fool](https://www.fool.com/investing/2026/02/15/better-artificial-intelligence-stock-nvidia-vs-amd/)

## AI's Economic Reality Check

- US productivity rises as AI integration begins to drive growth - [Financial Times](https://www.ft.com/content/4b51d0b4-bbfe-4f05-b50a-1d485d419dc5)
- Apollo economist projects only modest AI productivity gains through 2035 - [Fortune](https://fortune.com/2026/02/14/ai-effect-macro-economic-data-labor-enhancement-some-sectors-workers-displacement/)
- Physical and regulatory constraints threaten to stall AI workforce integration - [The Washington Post](https://www.washingtonpost.com/opinions/2026/02/13/ai-artificial-intelligence-economy-workplace/)

## China's High-Stakes AI Offensive

- China projected to produce only 2% of global AI chips by 2026 - [The New York Times](https://www.nytimes.com/2026/02/14/business/china-chips-nvidia-huawei.html)
- Alibaba's Qwen AI model exhibits pro-China bias on human rights - [China Media Project](https://chinamediaproject.org/2026/02/09/tokens-of-ai-bias/)
- Chinese billionaires fund domestic AI to reduce foreign tech reliance - [Bloomberg](https://www.bloomberg.com/features/2026-china-ai-billionaires)
- ByteDance launches Doubao 2.0 with multi-step tasking for 155 million users - [Reuters](https://www.reuters.com/world/asia-pacific/chinas-bytedance-releases-doubao-20-ai-chatbot-2026-02-14/)
- Alibaba and Kuaishou join ByteDance in \\$700 million push against US dominance - [Chrome Web Store](https://news.google.com/rss/articles/CBMiwwFBVV95cUxQV1dsc1NHdE9KYmFFMTB0TVZLOUQxRi1rbXNnQm8xV3dyd2hIZUNZMHlobXZJR2RvcjVSQlVkMnhHVDFOcVNwWlhES3ktX2FoTzhQd0VXcjVZTVdFSVFmWWJsOEsyeFRJbnJwTWlhdFJYQ1RydFU1STBDWE4xNTRsTnB1NUtqZDAwbHBMbVFzbDFPallOdE5sTTNUWjV1YjRXVTZjbS1kZ2FBaVBpNGN1N1BtUlh2dk4tRzdYYzVlWEYyV28)

## Other News

- Anduril seeks \\$60 billion valuation in latest funding round - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-14/anduril-in-talks-for-new-funding-st-60b-valuation-information)
- European defense startups raised record \\$8.7 billion in 2025 - [Resilience Media](https://resiliencemedia.co/european-defence-security-and-resilience-startups-raised-a-record-8-7b-in-2025/)
- UK Prime Minister Starmer to tighten online safety laws for AI chatbots - [Financial Times](https://www.ft.com/content/15917aa4-2d40-49be-85c3-da395b16e7f1)
- OpenAI introduces ChatGPT ads to offset rising computational costs - [Financial Times](https://www.ft.com/content/c9acd1f7-4864-4bd7-9ada-d2e13f05b906)
- GPT-5 and Gemini 3 Pro achieve 100% legal compliance in car accident scenarios - [The Register](https://go.theregister.com/feed/www.theregister.com/2026/02/15/gpt5_bests_human_judges_in/)
- FTC intensifies Microsoft probe over cloud and AI business practices - [Bloomberg](https://www.bloomberg.com/news/articles/2026-02-13/ftc-ratchets-up-microsoft-probe-queries-rivals-on-cloud-ai)
- Disney inks \\$1 billion Sora deal with OpenAI while suing ByteDance - [Business Insider](https://www.businessinsider.com/disney-ai-copyright-battles-seedance-nano-banana-sora-midjourney-2026-2)
- OpenAI drops 'safely' from mission statement amid \\$500 billion for-profit pivot - [Business Standard](https://www.business-standard.com/technology/tech-news/openai-drops-safely-from-mission-as-new-structure-tests-ai-s-loyalties-126021500074_1.html)
- xAI cofounders depart amid internal tensions over safety and strategy - [The Verge](https://www.theverge.com/ai-artificial-intelligence/878761/mass-exodus-at-xai-grok-elon-musk-restructuring)
- Security researchers earn \\$37,500 for bypassing LLM safeguards via multilingual injections - [Hacker Noon](https://hackernoon.com/multilingual-prompt-injection-exposes-gaps-in-llm-safety-nets)
- Former NPR host David Greene sues Google over unauthorized voice use in NotebookLM - [The Washington Post](https://www.washingtonpost.com/technology/2026/02/15/david-greene-google-ai-podcast/)

In [34]:
print(state.get_workflow_status_report())

WORKFLOW STATUS
Progress: 100.0% (9/9 complete)
Status Summary: 9 complete, 0 started, 0 failed, 0 not started
Status: All steps complete or started

Step Details:
  Step 0: Gather URLs: complete
    Status: ✅ Step 1 gather_urls completed successfully! Gathered 843 articles from 17 sources.

📊 Articles stored in persistent state: 697
  Step 1: Filter URLs: complete
    Status: ✅ Step 2 filter_urls completed successfully! Removed 368 duplicate URLs, classified 329 new articles, found 178 AI-related.
  Step 2: Download Articles: complete
    Status: ✅ Step 3 download_articles completed successfully! Total articles: 329; AI-related articles: 168; HTML files: 140; Text files: 140
  Step 3: Extract Summaries: complete
    Status: ✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 168/168 articles.
💾 Summaries stored in headline DataFrame.
  Step 4: Rate Articles: complete
    Status: ✅ Step 5 rate_articles completed successfully! Rated 167 articles with average rating 6.4/10.
⭐ High quality articles (≥7.0): 69
💾 Ratings stored in persistent state.
  Step 5: Cluster By Topic: complete
    Status: ✅ Step 6 cluster_topics completed successfully! Organized 167 articles into topic clusters.
  Step 6: Select Sections: complete
    Status: Categories and article counts:
cat
AI Agent Systems                  13
AI Chip Market Trends              4
AI Dating Applications             3
AI Infrastructure Growth           8
AI Labor Impact                   10
AI Market Risks                    9
Anthropic Claude                   6
Anthropic Funding                  2
Anthropic Pentagon Dispute         2
ByteDance Doubao 2.0               2
China AI Independence              3
European Defense Tech Funding      3
India Global AI Commons            3
Memory Chip Shortage               2
OpenAI Hires Peter Steinberger     2
Other                             48
Palantir Stock Performance         2
Scientific AI Research             6
Spotify AI Code Supervision        2
US AI Productivity                 3
Utah AI Bill                       2
  Step 7: Draft Sections: complete
    Status: ✅ Step 8 draft_sections completed successfully! Drafted 76 stories across 16 sections
  Step 8: Finalize Newsletter: complete
    Status: 🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 9.1/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.

In [35]:
state.print_workflow_status()

============================================================
📊 WORKFLOW STATUS
============================================================
📈 Progress: 100.0% (9/9 complete)
🎉 All steps complete!

📋 Step Details:
  ✅ Step 0: Gather URLs            | complete
      📝 Status: ✅ Step 1 gather_urls completed successfully! Gathered 843 articles from 17 sources.

📊 Articles stored in persistent state: 697
  ✅ Step 1: Filter URLs            | complete
      📝 Status: ✅ Step 2 filter_urls completed successfully! Removed 368 duplicate URLs, classified 329 new articles, found 178 AI-related.
  ✅ Step 2: Download Articles      | complete
      📝 Status: ✅ Step 3 download_articles completed successfully! Total articles: 329; AI-related articles: 168; HTML files: 140; Text files: 140
  ✅ Step 3: Extract Summaries      | complete
      📝 Status: ✅ Step 4 extract_summaries completed successfully! Generated AI-powered summaries for 168/168 articles.
💾 Summaries stored in headline DataFrame.
  ✅ Step 4: Rate Articles          | complete
      📝 Status: ✅ Step 5 rate_articles completed successfully! Rated 167 articles with average rating 6.4/10.
⭐ High quality articles (≥7.0): 69
💾 Ratings stored in persistent state.
  ✅ Step 5: Cluster By Topic       | complete
      📝 Status: ✅ Step 6 cluster_topics completed successfully! Organized 167 articles into topic clusters.
  ✅ Step 6: Select Sections        | complete
      📝 Status: Categories and article counts:
cat
AI Agent Systems                  13
AI Chip Market Trends              4
AI Dating Applications             3
AI Infrastructure Growth           8
AI Labor Impact                   10
AI Market Risks                    9
Anthropic Claude                   6
Anthropic Funding                  2
Anthropic Pentagon Dispute         2
ByteDance Doubao 2.0               2
China AI Independence              3
European Defense Tech Funding      3
India Global AI Commons            3
Memory Chip Shortage               2
OpenAI Hires Peter Steinberger     2
Other                             48
Palantir Stock Performance         2
Scientific AI Research             6
Spotify AI Code Supervision        2
US AI Productivity                 3
Utah AI Bill                       2
  ✅ Step 7: Draft Sections         | complete
      📝 Status: ✅ Step 8 draft_sections completed successfully! Drafted 76 stories across 16 sections
  ✅ Step 8: Finalize Newsletter    | complete
      📝 Status: 🎉 Step 9 finalize_newsletter completed successfully!
⭐ Final quality score: 9.1/10
🔄 Completed 2 critic-optimizer iteration(s)
📰 Newsletter stored in persistent state and emailed
✅ Workflow complete! All 9 steps finished successfully.
============================================================